var data = [
	// one
	[
		{
			index: 1,
			name: "Blood Demon",
			ranks: 5,
			desc: "Increases the chance that Vampire's Sigil, Invigoration, Seed of Life, Dark Contract, and Blood Rite will activate Vampire form by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the chance that Vampire\'s Sigil, Invigoration, Seed of Life, Dark Contract, and Blood Rite will activate Vampire form by <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 2,
			name: "Blood Sign",
			ranks: 5,
			desc: "Increases the amount of Health restored by Vampire's Sigil by <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your max Health.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [0.6, 1.2, 1.8, 2.4, 3.0],
		},
		{
			index: 5,
			name: "Extended Charmed Strike",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the range of Charmed Strike by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 6,
			name: "Advanced Vampire's Sigil",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduces the cooldown of Vampire's Sigil by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Vampire\'s Sigil by <span class="tooltip-value">2.5</span> second(s).</div>'],
		},
		{
			index: 8,
			name: "Evil Blood",
			ranks: 4,
			desc: "The duration of Blood Curse is increased by <span class='tooltip-value'>#</span> seconds. The base Health of enemies affected by Blood Curse is reduced by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>The duration of Blood Curse is increased by <span class="tooltip-value">25</span> seconds. The base Health of enemies affected by Blood Curse is reduced by an additional <span class="tooltip-value">5%</span>.</div>'],
		},
		{
			index: 9,
			name: "Bloody Evil Strike",
			ranks: 4,
			desc: "Charmed Strike drains <span class='tooltip-value'>#</span> Health at the most from the target and deals an additional <span class='tooltip-value'>#%</span> damage to targets affected by Blood Curse.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100, 150, 200],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Charmed Strike drains <span class="tooltip-value">250</span> Health at the most from the target and deals an additional <span class="tooltip-value">50%</span> damage to targets affected by Blood Curse.</div>'],
			parent: 2,
		},
		{
			index: 11,
			name: "Seed of Life",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 10 seconds</span>\n<span class='left'>Single-target blessing</span><span class='right'>Range: 16 meters</span>\n\nAfter 5 seconds, Seed of Life heals the target for <span class='tooltip-value'>#</span> Health. Has a 2% Crit Chance, which causes this skill to heal for double the amount. The healing effect instantly activates if the target's Health drops below 50%. Has a 10% chance to activate Vampire form.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n'],
			rankInfo2: [211, 313, 416],
			rankInfo3: ['1896-2093', '2787-3077', '3632-4011'],
			rankInfo4: ['', '', '<div class="runelvl">\n<br>Level: 4/3 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">522</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 10 seconds</span>\n<br><span class="left">Single-target blessing</span><span class="right">Range: 16 meters</span>\n\n<br><br>After 5 seconds, Seed of Life heals the target for <span class="tooltip-value">4432-4894</span> Health. Has a 2% Crit Chance, which causes this skill to heal for double the amount. The healing effect instantly activates if the target\'s Health drops below 50%. Has a 10% chance to activate Vampire form.</div>'],
		},
		{
			index: 12,
			name: "Blood Knowledge",
			ranks: 3,
			desc: "Reduces the Mana costs of your healing skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [8, 16, 24],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the Mana costs of your healing skills by <span class="tooltip-value">32%</span>.</div>'],
		},
		{
			index: 13,
			name: "Advanced Dark Contract",
			ranks: 5,
			desc: "Reduces the cooldown of Dark Contract by <span class='tooltip-value'>#</span> second(s). Increases the amount of Health restored by Dark Contract by <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 14,
			name: "Insignia Energy",
			ranks: 4,
			desc: "Increases the base damage of Vampire's Sigil by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the base damage of Vampire\'s Sigil by <span class="tooltip-value">50%</span>.</div>'],
			parent: 3,
		},
		{
			index: 18,
			name: "Batwing Shadow",
			ranks: 2,
			desc: "Gale Wings grants you immunity to ensnare effects for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Gale Wings grants you immunity to ensnare effects for <span class="tooltip-value">8</span> seconds.</div>'],
		},
		{
			index: 19,
			name: "Force of Life",
			ranks: 4,
			desc: "Increases the amount of Health restored by Seed of Life by <span class='tooltip-value'>#%</span> and its Crit Chance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [2, 4, 6, 8],
			parent: 6,
		},
		{
			index: 20,
			name: "Blood Feast",
			ranks: 3,
			desc: "Feast increases your Defense by an additional <span class='tooltip-value'>#%</span> and your Health recovery rate by an additional <span class='tooltip-value'>#%</span> per second.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [80, 160, 240],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Feast increases your Defense by an additional <span class="tooltip-value">320%</span> and your Health recovery rate by an additional <span class="tooltip-value">8%</span> per second.</div>'],
		},
		{
			index: 21,
			name: "Blood Link",
			ranks: 4,
			ranksnw: 1,
			desc: "Invigoration costs an additional <span class='tooltip-value'>#%</span> of your max Health and increases the target's Attack by <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: [8, 16, 24, 32],
		},
		{
			index: 22,
			name: "Blood Tie",
			ranks: 3,
			ranksnw: 2,
			desc: "While in Vampire form, the effectiveness of your healing skills is increased by an additional <span class='tooltip-value'>#%</span>, and killing enemies restores an additional <span class='tooltip-value'>#%</span> of your max Health.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 24,
			name: "Night Escape",
			ranks: 2,
			desc: "Reduces the amount of threat generated by your healing skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the amount of threat generated by your healing skills by <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 25,
			name: "Bestow Life",
			ranks: 2,
			ranksnw: 1,
			desc: "Invigoration increases the target's max Health by <span class='tooltip-value'>#%</span> for 20 seconds.",
			rankInfo: [10, 20],
			parent: 13,
		},
		{
			index: 26,
			name: "Bloodpact",
			ranks: 3,
			desc: "Increases the Crit Chance of Dark Contract and Seed of Life by an additional <span class='tooltip-value'>#%</span> while you're in Vampire form.",
			rankInfo: [15, 30, 45],
			parent: 14,
		},
		{
			index: 27,
			name: "Bloody Evil Death",
			ranks: 2,
			ranksnw: 2,
			desc: "Increases the amount of Health drained by Wrath Kill by <span class='tooltip-value'>#%</span>.",
			rankInfo: [100, 200],
		},
		{
			index: 30,
			name: "Blood Curse",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Darkness</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: 16 meters</span>\n\nWithin 6 meters, up to <span class='tooltip-value'>#</span> enemies are inflicted with Blood Curse for 15 seconds. Targets affected by Blood Curse are inflicted with the Congealed Blood effect for 20 seconds when attacked. Congealed Blood reduces the target's max Health by 4%. Stacks 5 times. Has a 10% chance to activate Vampire form.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [385, 464],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">549</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Darkness</span><span class="right">Cooldown: 30 seconds</span>\n<br><span class="left">Multi-target curse</span><span class="right">Range: 16 meters</span>\n\n<br><br>Within 6 meters, up to <span class="tooltip-value">25</span> enemies are inflicted with Blood Curse for 15 seconds. Targets affected by Blood Curse are inflicted with the Congealed Blood effect for 20 seconds when attacked. Congealed Blood reduces the target\'s max Health by 4%. Stacks 5 times. Has a 10% chance to activate Vampire form.</div>'],
		},
		{
			index: 31,
			name: "Improved Wrath Kill",
			ranks: 3,
			desc: "Reduces the cooldown of Wrath Kill by <span class='tooltip-value'>#</span> second(s). Targets affected by Blood Curse are inflicted with a bleed effect that deals <span class='tooltip-value'>#</span> damage every 2 seconds.",
			rankInfo: [1, 2, 3],
			rankInfo2: [80, 160, 240],
			parent: 18,
		},
		{
			index: 33,
			name: "Fresh Blood",
			ranks: 2,
			desc: "Increases the amount of Health restored by Invigoration by <span class='tooltip-value'>#%</span> for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [4, 8],
			rankInfo2: [10, 20],
			parent: 16,
		},
		{
			index: 34,
			name: "Stagnate",
			ranks: 2,
			desc: "Increases the range of Blood Curse by <span class='tooltip-value'>#</span> meter(s). Targets affected by Congealed Blood are also inflicted with the Congealed Health effect, which reduces the effectiveness of healing skills cast on the target by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the range of Blood Curse by <span class="tooltip-value">3</span> meter(s). Targets affected by Congealed Blood are also inflicted with the Congealed Health effect, which reduces the effectiveness of healing skills cast on the target by <span class="tooltip-value">45%</span>.</div>'],
			parent: 19,
		},
		{
			index: 36,
			name: "Blood Control",
			ranks: 1,
			desc: "<span class='left'>1000 Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 10 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nHeal of Invigoration by 25% of your Attack. Increases heal of Dark Contract equal to 5% of Max Health, and heals yourself immediately by 3% of your Max Health. Seed of Life heals an additional amount equal to 5% of your Max Health and performs an immediate heal upon casting. May only cast Curse and Blessing skills while Blood Control is active. May only activate this skill while not in combat. Cancel this skill's effect by using it again.",
			rankInfo: [],
		},
		{
			index: 37,
			name: "Extended Bloodwork",
			ranks: 2,
			desc: "Using Blood skills increases the duration of Vampire form by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [4, 8],
		},
		{
			index: 38,
			name: "Hasted Healing",
			ranks: 2,
			desc: "Reduces the cooldowns of Seed of Life and Invigoration by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4],
		},
		{
			index: 39,
			name: "Ritual",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the duration of Blood Rite by 2 seconds. Increases the amount of Health restored by Dark Contract and Seed of Life by an amount equal to <span class='tooltip-value'>#%</span> of your Health.",
			rankInfo: [1, 2],
		},
		{
			index: 40,
			name: "Surging Blood",
			ranks: 2,
			desc: "Increases your max Health by <span class='tooltip-value'>#%</span>. Increases your max Health and your max Mana by an additional <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4],
			rankInfo2: [300, 600],
		},
		{
			index: 42,
			name: "Blood Tie Extension",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the range of your healing skills by <span class='tooltip-value'>#</span> meters and the amount of Health they restore by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
			rankInfo2: [15, 30],
		},
		{
			index: 43,
			name: "Blood Fever",
			ranks: 2,
			ranksnw: 1,
			desc: "While Blood Rite is active, Dark Contract and Invigoration increase the movement speed and all Masteries of the target by <span class='tooltip-value'>#%</span> and <span class='tooltip-value'>#</span> respectively for 5 seconds and Vampire's Sigil reduces the movement speed and all Masteries of the target by <span class='tooltip-value'>#%</span> and <span class='tooltip-value'>#</span> respectively for 5 seconds.",
			rankInfo: [25, 30],
			rankInfo2: [80, 160],
			rankInfo3: [25, 30],
			rankInfo4: [80, 160],
			parent: 26,
		},
		{
			index: 46,
			name: "Withered Space",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>327 Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Darkness</span><span class='right'>Cooldown: 300 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: None</span>\n\nYou cannot move or use attack skills for 25 seconds. You can use Healing and Curse skills. Immune to silence and stun effects. Increases your max Health by 50%, and increases the range of your Healing spells by 50%. Casts Dark Contract and Seed of Life on the target, and applies same effects to you. Reduces all Resistances of all enemies within 20 meters by 200. Cancel this skill's effect by using it again.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
			parent: 28,
		},
		{
			index: 47,
			name: "Wither",
			ranks: 4,
			desc: "Reduces Health recovered from Healing Effects on targets affected by Withered Space by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
			parent: 30,
		},
		{
			index: 49,
			name: "Bloodlust Gene",
			ranks: 3,
			desc: "Blood healing skills (Seed of Life, Dark Contract, Invigoration) increases target's Crit Chance by <span class='tooltip-value'>#%</span> for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 3, 4],
			rankInfo2: [7, 9, 11],
		},
		{
			index: 51,
			name: "Spewed Blood",
			ranks: 2,
			desc: "Increases Crit Dodge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Demon Realm",
			ranks: 1,
			desc: "Withered Space increases your Crit Dodge by 20%.",
			rankInfo: [],
			parent: 30,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Demon of Darkness",
			ranks: 5,
			desc: "Increases the chance that Dark Ripple, Seed of Darkness, Dark Contract, Wrath Kill, Mana Explosion, and Shadow Scar will activate Vampire form by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the chance that Dark Ripple, Seed of Darkness, Dark Contract, Wrath Kill, Mana Explosion, and Shadow Scar will activate Vampire form by <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 3,
			name: "Force of Shadow",
			ranks: 5,
			desc: "Dark Ripple and Shadow Scar cost an additional <span class='tooltip-value'>#%</span> of your max Health. That amount is still added to their damage. Increases the Crit Chance of Dark Ripple by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Dark Ripple and Shadow Scar cost an additional <span class="tooltip-value">3%</span> of your max Health. That amount is still added to their damage. Increases the Crit Chance of Dark Ripple by <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 5,
			name: "Spell Surge",
			ranks: 2,
			desc: "Reduces the cooldown of Charmed Strike by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [0.3, 0.5],
		},
		{
			index: 7,
			name: "Advanced Dark Ripple",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduces the cooldown of Dark Ripple by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Dark Ripple by <span class="tooltip-value">2.5</span> second(s).</div>'],
		},
		{
			index: 8,
			name: "Expansion of Darkness",
			ranks: 4,
			desc: "Increases the duration of Dark Curse by <span class='tooltip-value'>#</span> seconds and reduces the target's Accuracy by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [6, 12, 18, 24],
		},
		{
			index: 9,
			name: "Dark Strike",
			ranks: 4,
			desc: "The first hit of Charmed Strike has a <span class='tooltip-value'>#%</span> chance to stun the target for 1 second. The second hit has a <span class='tooltip-value'>#%</span> chance to stun the target for 1 second. Charmed Strike deals an additional <span class='tooltip-value'>#%</span> damage to targets affected by Dark Curse.",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [12, 25, 37, 50],
			rankInfo3: [10, 20, 30, 40],
		},
		{
			index: 10,
			name: "Seed of Darkness",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Darkness</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Single-target curse</span><span class='right'>Range: 12 meters</span>\n\nCosts 1% of your max Health. After 5 seconds, reduces the target's movement speed by 50.0% for <span class='tooltip-value'>#</span> seconds. Dark Curse can trigger this effect early. Has a 10% chance to activate Vampire form.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n'],
			rankInfo2: [235, 337, 441],
			rankInfo3: [8, 10, 12],
			rankInfo4: ['', '', '<div class="runelvl">\n<br>Level: 4/3 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">548</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Darkness</span><span class="right">Cooldown: 30 seconds</span>\n<br><span class="left">Single-target curse</span><span class="right">Range: 12 meters</span>\n\n<br><br>Costs 1% of your max Health. After 5 seconds, reduces the target\'s movement speed by 50.0% for <span class="tooltip-value">14</span> seconds. Dark Curse can trigger this effect early. Has a 10% chance to activate Vampire form.</div>'],
		},
		{
			index: 12,
			name: "Hemophilia",
			ranks: 3,
			desc: "Increases the duration of Feast by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the duration of Feast by <span class="tooltip-value">4</span> second(s).</div>'],
		},
		{
			index: 14,
			name: "Force of Darkness",
			ranks: 3,
			ranksnw: 2,
			desc: "Seed of Darkness reduces the target's movement speed by an additional <span class='tooltip-value'>#%</span>. Targets affected by Seed of Darkness become silenced for <span class='tooltip-value'>#</span> second(s) after being struck 4 times.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 6,
		},
		{
			index: 15,
			name: "Darkness Invasion",
			ranks: 5,
			desc: "Dark Ripple reduces the target's Dark Resistance by an additional <span class='tooltip-value'>#</span> for 15 seconds. Increases Dark Ripple's chance of inflicting Dark Curse on the target by <span class='tooltip-value'>#%</span> when cast out of Vampire form.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60, 75],
			rankInfo2: [4, 8, 12, 16, 20],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Dark Ripple reduces the target\'s Dark Resistance by an additional <span class="tooltip-value">90</span> for 15 seconds. Increases Dark Ripple\'s chance of inflicting Dark Curse on the target by <span class="tooltip-value">24%</span> when cast out of Vampire form.</div>'],
			parent: 3,
		},
		{
			index: 17,
			name: "Stimulation",
			ranks: 4,
			desc: "Increases the duration of Invigoration by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 18,
			name: "Sprout",
			ranks: 2,
			desc: "Reduces the cooldown of Seed of Darkness by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Seed of Darkness by <span class="tooltip-value">15</span> seconds.</div>'],
			parent: 8,
		},
		{
			index: 20,
			name: "Eyes of Darkness",
			ranks: 3,
			desc: "Increases the Accuracy of your Dark skills by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the Accuracy of your Dark skills by <span class="tooltip-value">40</span>.</div>'],
		},
		{
			index: 21,
			name: "Wrath Illusion",
			ranks: 4,
			ranksnw: 1,
			desc: "Increases the Crit Chance of Wrath Kill by <span class='tooltip-value'>#%</span> and reduces its cooldown by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 23,
			name: "Contract Aftermath",
			ranks: 4,
			desc: "Dark Contract increases the target's Evasion by <span class='tooltip-value'>#</span> for 3 seconds if the target is a party member.",
			rankInfo: [20, 40, 60, 80],
		},
		{
			index: 26,
			name: "Advanced Dark Bonds",
			ranks: 2,
			desc: "Increases the duration of Dark Bonds' controlling effect on players by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4],
		},
		{
			index: 28,
			name: "Vampire Power",
			ranks: 3,
			desc: "Vampire form increases your Attack by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 29,
			name: "Darkened Wrath Kill",
			ranks: 2,
			desc: "Wrath Kill reduces the Attack of targets affected by Dark Curse by an additional <span class='tooltip-value'>#%</span> and reduces their movement speed by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Wrath Kill reduces the Attack of targets affected by Dark Curse by an additional <span class="tooltip-value">30%</span> and reduces their movement speed by an additional <span class="tooltip-value">30%</span>.</div>'],
			parent: 13,
		},
		{
			index: 30,
			name: "Mana Explosion",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Dark damage</span><span class='right'>Cooldown: 8 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: None</span>\n\nAffects multiple enemies within a 10 range. Costs 1% of your Health. Deals 100% of your base Attack plus <span class='tooltip-value'>#</span> bonus damage. This skill has the same effect on curses as Wrath Kill. Vampire form further enhances this skill's effects. Has a 10% chance to activate Vampire form.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [432, 520],
			rankInfo3: [1047, 1532],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">615</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Dark damage</span><span class="right">Cooldown: 8 seconds</span>\n<br><span class="left">Multi-target attack</span><span class="right">Range: None</span>\n\n<br><br>Affects multiple enemies within a 10 range. Costs 1% of your Health. Deals 100% of your base Attack plus <span class="tooltip-value">1987</span> bonus damage. This skill has the same effect on curses as Wrath Kill. Vampire form further enhances this skill\'s effects. Has a 10% chance to activate Vampire form.</div>'],
		},
		{
			index: 32,
			name: "Darkness Expertise",
			ranks: 3,
			desc: "Increases your Dark Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 34,
			name: "Mana Explosion Mastery",
			ranks: 2,
			desc: "Increases the base damage of Mana Explosion by <span class='tooltip-value'>#%</span> and its range by <span class='tooltip-value'>#</span> meter(s).",
			rankInfo: [10, 20],
			rankInfo2: [1, 2],
			parent: 18,
		},
		{
			index: 35,
			name: "Sudden Darkness",
			ranks: 2,
			desc: "Reduces the cooldowns of Dark Bonds and Mana Explosion by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldowns of Dark Bonds and Mana Explosion by <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 37,
			name: "Dark Vampire State",
			ranks: 1,
			desc: "While in Vampire form, skills that cost Health instead restore double the amount of Health normally consumed.",
			rankInfo: [],
		},
		{
			index: 38,
			name: "Inscribed Defense",
			ranks: 2,
			desc: "Reduces the cooldown of Blood Rite by <span class='tooltip-value'>#</span> seconds, and gives it a <span class='tooltip-value'>#%</span> chance to dispel any ensnare or stun effects affecting you.",
			rankInfo: [20, 40],
			rankInfo2: [50, 100],
		},
		{
			index: 40,
			name: "Endless Darkness",
			ranks: 2,
			desc: "Increases your Dark Resistance by <span class='tooltip-value'>#</span> and your Evasion by <span class='tooltip-value'>#</span>.",
			rankInfo: [25, 50],
			rankInfo2: [4, 8],
		},
		{
			index: 41,
			name: "Congealed Veins",
			ranks: 1,
			desc: "You are immune to slow effects while Vampire form is active.",
			rankInfo: [],
		},
		{
			index: 42,
			name: "Soul Power",
			ranks: 4,
			desc: "Increases the base damage of Dark Ripple, Charmed Strike, Wrath Kill, and Shadow Scar by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 43,
			name: "Shadow Rage",
			ranks: 2,
			desc: "Reduces the cooldown of Shadow Scar by <span class='tooltip-value'>#</span> seconds, and increases the Crit Chance of its attacks by <span class='tooltip-value'>#%</span> and <span class='tooltip-value'>#%</span>, respectively.",
			rankInfo: [2, 4],
			rankInfo2: [2, 4],
			rankInfo3: [4, 8],
		},
		{
			index: 46,
			name: "Imp Form",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>249 Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Single-target blessing</span><span class='right'>Range: None</span>\n\nYou transform into an imp, and your Evasion is increased by 100. You cannot use any skill but Charmed Strike for 20 seconds. The cooldown of Charmed Strike becomes 3 seconds, and its base damage is reduced to 10%. Reduces the Evasion and Accuracy of targets within 5 meters by 60 and 60, respectively. Cancel this skill's effect by using it again.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Misty",
			ranks: 4,
			desc: "While in Imp Form, Movement Speed is increased by <span class='tooltip-value'>#%</span> and Evasion is increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [8, 16, 24, 32],
			parent: 28,
		},
		{
			index: 49,
			name: "Shrouding World",
			ranks: 3,
			desc: "Dark multi-target skills (Mana Explosion, Blood Sea) reduce targets' Dark Resistance by <span class='tooltip-value'>#</span> for 10 seconds.",
			rankInfo: [30, 45, 60],
		},
		{
			index: 51,
			name: "Lightless",
			ranks: 2,
			desc: "Increases the Range of Dark Bonds by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [1, 2],
		},
		{
			index: 54,
			name: "Blood Curse",
			ranks: 1,
			desc: "The Duration of Imp Form is increased by 5 second(s).",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Dark Curse",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the duration of Dark Curse by <span class='tooltip-value'>#</span> seconds. Increases the range of Dark Curse by <span class='tooltip-value'>#</span> meter(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12, 16, 20],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the duration of Dark Curse by <span class="tooltip-value">24</span> seconds. Increases the range of Dark Curse by <span class="tooltip-value">6</span> meter(s).</div>'],
		},
		{
			index: 3,
			name: "Underworld Scorching",
			ranks: 5,
			desc: "Increases the bonus damage of Evil Flame by <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your Fire Mastery.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100, 150, 200, 250],
			rankInfo2: [40, 80, 120, 160, 200],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the bonus damage of Evil Flame by <span class="tooltip-value">300</span> plus <span class="tooltip-value">240%</span> of your Fire Mastery.</div>'],
		},
		{
			index: 6,
			name: "Curse Energy",
			ranks: 3,
			desc: "Dark Curse reduces the target's Fire and Dark Resistances by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Dark Curse reduces the target\'s Fire and Dark Resistances by <span class="tooltip-value">40</span>.</div>'],
			parent: [0],
		},
		{
			index: 7,
			name: "Flash Flame",
			ranks: 5,
			ranksnw: 1,
			desc: "Reduces the cooldown of Evil Flame by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Reduces the cooldown of Evil Flame by <span class="tooltip-value">6</span> second(s).</div>'],
		},
		{
			index: 9,
			name: "Blazing Charmed Strike",
			ranks: 4,
			desc: "Charmed Strike reduces the Defense of targets affected by Dark Curse by <span class='tooltip-value'>#</span> for 30 seconds. Stacks 5 times. Charmed Strike deals an additional <span class='tooltip-value'>#</span> damage to targets affected by Flame Curse.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12],
			rankInfo2: [26, 52, 78, 104],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Charmed Strike reduces the Defense of targets affected by Dark Curse by <span class="tooltip-value">15</span> for 30 seconds. Stacks 5 times. Charmed Strike deals an additional <span class="tooltip-value">130</span> damage to targets affected by Flame Curse.</div>'],
		},
		{
			index: 10,
			name: "Seed of Flame",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Fire</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Single-target curse</span><span class='right'>Range: 12 meters</span>\n\nTargets affected by Seed of Flame are burned for <span class='tooltip-value'>#</span> damage each time they attack or are attacked. This effect lasts for 20 seconds. Seed of Flame removes all curse effects on the target and deals damage instantly for each curse removed. Flame Curse deals <span class='tooltip-value'>#</span> damage, while Blood Curse and Dark Curse deal <span class='tooltip-value'>#</span> damage. Has a 5% chance to activate Vampire form.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n'],
			rankInfo2: [200, 287, 376],
			rankInfo3: [50, 80, 110],
			rankInfo4: [1202, 1922, 2634],
			rankInfo5: [601, 961, 1317],
			rankInfo6: ['', '', '<div class="runelvl">\n<br>Level: 4/3 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">466</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Fire</span><span class="right">Cooldown: 20 seconds</span>\n<br><span class="left">Single-target curse</span><span class="right">Range: 12 meters</span>\n\n<br><br>Targets affected by Seed of Flame are burned for <span class="tooltip-value">140</span> damage each time they attack or are attacked. This effect lasts for 20 seconds. Seed of Flame removes all curse effects on the target and deals damage instantly for each curse removed. Flame Curse deals <span class="tooltip-value">3339</span> damage, while Blood Curse and Dark Curse deal <span class="tooltip-value">1669</span> damage. Has a 5% chance to activate Vampire form.</div>'],
		},
		{
			index: 12,
			name: "Lingering Blaze",
			ranks: 4,
			desc: "Increases the duration of Flame Curse by <span class='tooltip-value'>#</span> seconds. Reduces the target's Fire Resistance by an additional <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the duration of Flame Curse by <span class="tooltip-value">25</span> seconds. Reduces the target\'s Fire Resistance by an additional <span class="tooltip-value">50</span>.</div>'],
		},
		{
			index: 13,
			name: "Flame Demon",
			ranks: 5,
			desc: "Increases the chance that Dark Curse, Evil Flame, Hellfire Death, Seed of Flame, and Infernal Slaughter will activate Vampire form by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 15,
			name: "Necroflame Curse",
			ranks: 2,
			desc: "Evil Flame has a <span class='tooltip-value'>#%</span> chance to apply two stacks of Magic Flame to targets affected by Dark Curse.",
			rankInfo: [50, 100],
			parent: 3,
		},
		{
			index: 16,
			name: "Gluttony",
			ranks: 3,
			desc: "Feast drains an additional amount of Health equal to <span class='tooltip-value'>#%</span> of your max Health. Reduces the duration of the ensnare effect on you by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Feast drains an additional amount of Health equal to <span class="tooltip-value">2%</span> of your max Health. Reduces the duration of the ensnare effect on you by <span class="tooltip-value">4</span> second(s).</div>'],
		},
		{
			index: 18,
			name: "Flame Torture",
			ranks: 4,
			ranksnw: 1,
			desc: "Targets affected by Seed of Flame take an additional <span class='tooltip-value'>#%</span> damage when they attack or are attacked.",
			rankInfo: [25, 50, 75, 100],
			parent: 5,
		},
		{
			index: 19,
			name: "Gale Wings",
			ranks: 3,
			desc: "When bat form ends, you retain 60% of the movement speed bonus for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 7, 9],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>When bat form ends, you retain 60% of the movement speed bonus for <span class="tooltip-value">11</span> seconds.</div>'],
		},
		{
			index: 21,
			name: "Blazing Evil Death",
			ranks: 4,
			desc: "Wrath Kill reduces the Defense of targets affected by Flame Curse by an additional <span class='tooltip-value'>#%</span> for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Wrath Kill reduces the Defense of targets affected by Flame Curse by an additional <span class="tooltip-value">125%</span> for <span class="tooltip-value">5</span> second(s).</div>'],
		},
		{
			index: 23,
			name: "Flame Suppression",
			ranks: 2,
			desc: "Reduces the amount of threat generated by your Fire and Curse skills and reduces their Mana costs by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 26,
			name: "Magic Eclipse",
			ranks: 4,
			desc: "When targets affected by Seed of Flame attack or are attacked, they lose an amount of Mana equal to <span class='tooltip-value'>#%</span> of your Fire Mastery.",
			rankInfo: [15, 30, 45, 60],
			parent: 10,
		},
		{
			index: 28,
			name: "Necroflame Endurance",
			ranks: 4,
			desc: "Increases your Fire Resistance by <span class='tooltip-value'>#</span> and your Defense by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 30,
			name: "Inferno Bat",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: <span class='tooltip-value'>#</span> seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nYou transform into an Inferno Bat for <span class='tooltip-value'>#</span> seconds. Your Attack is increased by <span class='tooltip-value'>#%</span>, your movement speed is increased by <span class='tooltip-value'>#%</span>, and the range of your skills is increased by 50%. In this form, you can only use Fire skills. Evil Flame doesn't have a cooldown, but it deals 40% less bonus damage. Its cast time is reduced to 1 second. Seed of Flame deals <span class='tooltip-value'>#</span> damage and stuns the target for 2 seconds. Reduces the cooldown of Gale Wings to 6 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [162, 199],
			rankInfo3: [150, 120],
			rankInfo4: [20, 25],
			rankInfo5: [5, 7],
			rankInfo6: [20, 30],
			rankInfo7: [1202, 1922],
			rankInfo8: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">239</span> Mana</span><span class="right">Cast time: Instant</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: <span class="tooltip-value">90</span> seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>You transform into an Inferno Bat for <span class="tooltip-value">30</span> seconds. Your Attack is increased by <span class="tooltip-value">9%</span>, your movement speed is increased by <span class="tooltip-value">40%</span>, and the range of your skills is increased by 50%. In this form, you can only use Fire skills. Evil Flame doesn\'t have a cooldown, but it deals 40% less bonus damage. Its cast time is reduced to 1 second. Seed of Flame deals <span class="tooltip-value">2634</span> damage and stuns the target for 2 seconds. Reduces the cooldown of Gale Wings to 6 seconds.</div>'],
		},
		{
			index: 31,
			name: "Weaken",
			ranks: 3,
			desc: "Dark Bonds reduces the target's Resistances by <span class='tooltip-value'>#</span> for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: [20, 35, 50],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Dark Bonds reduces the target\'s Resistances by <span class="tooltip-value">80</span> for <span class="tooltip-value">65</span> seconds.</div>'],
		},
		{
			index: 33,
			name: "Hasted Hellfire",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduces the cooldown of Hellfire Death by <span class='tooltip-value'>#</span> second(s) and increases its base damage by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Hellfire Death by <span class="tooltip-value">3</span> second(s) and increases its base damage by <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 34,
			name: "Bat Shape",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduces the cooldown of Inferno Bat by <span class='tooltip-value'>#</span> seconds. While you are in Inferno Bat form, you deal an amount of damage equal to <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your Fire Mastery every 3 seconds to targets within 10 meters that are affected by Dark Curse.",
			rankInfo: [10, 20, 30],
			rankInfo2: [300, 600, 900],
			rankInfo3: [10, 20, 30],
			parent: 16,
		},
		{
			index: 37,
			name: "Hellfire Pulse",
			ranks: 2,
			desc: "Hellfire Death knocks the target back <span class='tooltip-value'>#</span> meters, and has a <span class='tooltip-value'>#%</span> chance to stun the target tor 3 seconds.",
			rankInfo: [2, 4],
			rankInfo2: [20, 40],
			parent: 18,
		},
		{
			index: 38,
			name: "Hellfire Bat",
			ranks: 2,
			desc: "Reduces the cooldown of Hellfire Death by <span class='tooltip-value'>#</span> second(s), its cast time by <span class='tooltip-value'>#</span> second(s), and increases its range by <span class='tooltip-value'>#%</span> while in Inferno Bat form.",
			rankInfo: [1, 2],
			rankInfo2: [0.5, 1],
			rankInfo3: [25, 50],
			parent: 19,
		},
		{
			index: 40,
			name: "Flame Maneuver",
			ranks: 3,
			desc: "Increases your Fire Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 42,
			name: "Hellfire Fury",
			ranks: 3,
			desc: "Increases the bonus damage of Evil Flame and Hellfire Death by an additional <span class='tooltip-value'>#%</span>, and increases their Crit Chance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 43,
			name: "Scorching Curse",
			ranks: 3,
			desc: "Dark Curse and Hellfire Death inflict the Soulfire Curse effect on their targets. After <span class='tooltip-value'>#</span> second(s), Soulfire Curse absorbs an amount of Health equal to <span class='tooltip-value'>#</span> times your Fire Mastery and drains <span class='tooltip-value'>#%</span> Mana from the target.",
			rankInfo: [3, 4, 5],
			rankInfo2: [400, 800, 1200],
			rankInfo3: [30, 60, 90],
		},
		{
			index: 46,
			name: "Infernal Slaughter",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>365 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 12 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 12 meters</span>\n\n\Deals 120% of your Attack plus 2119 bonus damage. Deals an amount of damage equal to 1500 plus 100% of your Fire Mastery to targets affected by Flame Curse. Stuns a target affected by Blood Curse, Dark Curse, and Flame Curse at the same time for 3 seconds. Has a 5% chance to trigger Vampire form.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Burning Out",
			ranks: 4,
			desc: "Increases the Crit Chance of Infernal Slaughter by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			parent: 25,
		},
		{
			index: 49,
			name: "Burning Life",
			ranks: 3,
			desc: "Increases the Duration of Blood Rite by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 4, 6],
		},
		{
			index: 51,
			name: "Flame Vampire Form",
			ranks: 2,
			desc: "In Vampire form, Fire Skills' Crit Chance is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 54,
			name: "Hellfire",
			ranks: 1,
			desc: "Increases Base Attack by 30%. Only Flame Curse is needed to stun target.",
			rankInfo: [],
			parent: 25,
		},
	]
];