var data = [
	// one
	[
		{
			index: 2,
			name: "Cravo Misterioso",
			ranks: 5,
			desc: "Aumenta o dano bônus do Assassinato em <span class='tooltip-value'>#%</span> e concede uma chance de <span class='tooltip-value'>#%</span> para gerar um Orbe da Agonia.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 3,
			name: "Ataque da Dor",
			ranks: 5,
			desc: "Aumenta o efeito dos Orbes da Agonia no Fim do Pesadelo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40, 60, 80, 100],
		},
		{
			index: 5,
			name: "Ataque Súbito",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta o dano base do Impulso da Dor em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 7,
			name: "Dor do Pesadelo",
			ranks: 3,
			desc: "Concede ao Fim do Pesadelo uma chance de <span class='tooltip-value'>#%</span> para não consumir nenhum Orbe da Agonia.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40, 60],
		},
		{
			index: 8,
			name: "Assassino da Escuridão",
			ranks: 4,
			desc: "Aumenta a sua Maestria em Escuridão em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 9,
			name: "Dor Apressada",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduz o intervalo do Impulso da Dor em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [0.5, 1, 1.5, 2],
			parent: 2,
		},
		{
			index: 10,
			name: "Ferrão à Espreita",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Intervalo: 8 segundo(s)</span><span class='right'>Ataque contra alvo único</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Curto alcance</span>\n\nAcerta o alvo duas vezes. Cada golpe que acertar causa 70% de dano mais <span class='tooltip-value'>#</span> de dano bônus. A Chance Crítica do primeiro ataque aumenta em 2% e do segundo em 4%. Gera um Orbe da Agonia.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [179, 262, 346, 431],
			rankInfo3: [801, 1418, 2024, 2619],
		},
		{
			index: 11,
			name: "Evasão da Sombra",
			ranks: 2,
			desc: "Aumenta a duração do bônus de Evasão concedido pela Proteção da Sombra em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 3],
		},
		{
			index: 13,
			name: "Ferrões Duplos",
			ranks: 3,
			desc: "O Impulso da Dor tem uma chance de <span class='tooltip-value'>#%</span> para gerar um Orbe da Agonia adicional.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [9, 18, 27],
			parent: 5,
		},
		{
			index: 14,
			name: "Ferrão à Espreita Avançado",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduz o intervalo de uso de Ferrão à Espreita em <span class='tooltip-value'>#</span> segundo(s) e aumenta a Precisão em <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [15, 30, 45],
			parent: 6,
		},
		{
			index: 16,
			name: "Ataque Tóxico",
			ranks: 2,
			desc: "O Fim do Pesadelo reduz a Defesa dos alvos que não estão com a Saúde cheia em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 15],
		},
		{
			index: 17,
			name: "Ataque Doloroso",
			ranks: 3,
			desc: "Reduz o intervalo do Lançador em <span class='tooltip-value'>#</span> segundo(s) e aumenta seu dano base em <span class='tooltip-value'>#%</span>. Cada Orbe da Agonia aumenta adicionalmente o dano base causado pelo Lançador em <span class='tooltip-value'>#%</span>. Na Classificação 3, também silencia o alvo por 1 segundo se você tiver 3 Orbes da Agonia.",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: [5, 10, 15],
		},
		{
			index: 19,
			name: "Amplificação da Dor",
			ranks: 3,
			desc: "Cada Orbe da Agonia aumenta adicionalmente o seu Ataque em <span class='tooltip-value'>#</span>. Aumenta a duração dos Orbes da Agonia em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 20,
			name: "Arte da Escuridão",
			ranks: 3,
			desc: "Reduz o custo de Mana das suas habilidades de ataque de Escuridão em <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 21,
			name: "Lâmina da Hipnose Avançada",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduz o intervalo de uso da Lâmina da Hipnose em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20, 30],
		},
		{
			index: 22,
			name: "Ataque da Queima do Sangue",
			ranks: 3,
			desc: "Aumenta o dano base do Ferrão à Espreita em <span class='tooltip-value'>#%</span> e drena <span class='tooltip-value'>#%</span> da sua Saúde atual. O segundo ataque causa dano equivalente a <span class='tooltip-value'>#%</span> da sua Saúde atual.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: [2, 4, 6],
			parent: 9,
		},
		{
			index: 23,
			name: "Veneno da Escuridão",
			ranks: 3,
			desc: "Os seus ataques de Escuridão têm uma chance de <span class='tooltip-value'>#%</span> de envenenar o alvo, o que o faz perder <span class='tooltip-value'>#</span> de Saúde a cada segundo e reduz a velocidade do movimento em 10% por <span class='tooltip-value'>#</span> segundo(s). Reduz a velocidade do movimento em 15% no nível 4.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [60, 80, 100],
			rankInfo2: [50, 70, 90],
			rankInfo3: [4, 5, 5],
		},
		{
			index: 25,
			name: "Teoria da Hipnose",
			ranks: 1,
			desc: "A Lâmina da Hipnose fica eficaz contra todos os monstros.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 26,
			name: "Finais Amplificados",
			ranks: 2,
			desc: "Aumenta o dano base das suas habilidades de Finalização em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 28,
			name: "Fortificação de Poder",
			ranks: 4,
			desc: "Aumenta o seu Ataque base em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 29,
			name: "Pausa de Ofensa",
			ranks: 2,
			desc: "Impulso da Dor e Ferrão à Espreita reduzem o Ataque do alvo em <span class='tooltip-value'>#%</span> por 8 segundos.",
			rankInfo: [3, 6],
		},
		{
			index: 30,
			name: "Arte Secreta - Agonia",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nZera os intervalos do Ferrão à Espreita e Impulso da Dor e gera 2 Orbes da Agonia.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [333, 408],
			rankInfo3: [60, 45],
		},
		{
			index: 31,
			name: "Pesadelo Intensificado",
			ranks: 2,
			desc: "O Pesadelo Sombrio reduz as Resistências do alvo em em <span class='tooltip-value'>#</span> e sua duração aumenta em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40],
			rankInfo2: [1, 2],
		},
		{
			index: 34,
			name: "Arte Avançada - Agonia",
			ranks: 2,
			desc: "A Arte Secreta - Agonia tem uma chance de <span class='tooltip-value'>#%</span> para gerar um Orbe da Agonia adicional. Reduz o intervalo de uso em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [40, 80],
			rankInfo2: [5, 10],
			parent: 21,
		},
		{
			index: 35,
			name: "Manipulação da Agonia",
			ranks: 3,
			desc: "A Intenção Cruel consome Orbes da Agonia para aumentar a sua Defesa e Evasão por <span class='tooltip-value'>#</span> segundo(s). Com 0/1/2/3/4 Orbes da Agonia, sua Defesa aumenta em <span class='tooltip-value'>#</span> e sua Evasão em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: ['10/20/30/40/50', '20/30/40/50/60', '30/40/50/60/70'],
			rankInfo3: ['2/4/6/8/10', '4/6/8/10/12', '6/8/10/12/14'],
		},
		{
			index: 38,
			name: "Semente da Agonia",
			ranks: 2,
			desc: "Suas habilidades de Finalização causam o efeito da Semente da Agonia ao alvo, o que faz com que este perca Saúde sempre que atacar. Consome 0/1/2/3/4 Orbes da Agonia para causar dano equivalente a <span class='tooltip-value'>#</span> da Saúde atual do alvo. Este efeito pode ser acumulado 3 vezes e tem duração de 10 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['2%/3%/4%/5%/6%', '4%/5%/6%/7%/8%'],
		},
		{
			index: 39,
			name: "Perícia na Escuridão",
			ranks: 3,
			desc: "Causa efeito de sangramento ao alvo e reduz suas Maestrias em 15. Aumenta o dano bônus das suas habilidades de Escuridão ofensivas em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 42,
			name: "Lâmina Venenosa",
			ranks: 3,
			desc: "Faro e Mutilação têm uma chance de envenenar o alvo por 10 segundos. O veneno aumenta o dano causado pelos efeitos de sangramento em 20% e deixa o alvo devagar em <span class='tooltip-value'>#%</span>. Com 0/1/2/3/4 Orbes da Agonia, a chance deste efeito ocorrer é de <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: ['10%/20%/30%/40%/50%', '20%/30%/40%/50%/60%', '30%/40%/50%/60%/70%'],
		},
		{
			index: 43,
			name: "Abominação",
			ranks: 3,
			desc: "Suas habilidades de finalização tratam <span class='tooltip-value'>#</span> Orbes da Explosão como se fossem Orbes da Agonia. Na classificação 3, o efeito dos Orbes da Explosão não são reduzidos.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 46,
			name: "Mutilação",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>604 Mana</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Dano de escuridão</span><span class='right'>Sem intervalo</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Curto alcance</span>\n\nO Pesadelo Sombrio tem uma chance de possibilitar o uso da Mutilação. 0/1/2/3/4 Orbes da Agonia têm uma chance de 10%/20%/30%/40%/50% de possibilitar o uso desta habilidade. Dura 45 segundo. Este efeito desaparece depois que você usar a Mutilação uma vez. Acerta o alvo quatro vezes. Cada golpe que acertar ganha mais 2% de Chance Crítica. Cada golpe que atingir causa 70% do seu Ataque mais 1219 de dano bônus. O alvo perde 1% da Saúde atual por segundo e fica 10% mais devagar por 10 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		}
	],
		// two
	[
		{
			index: 2,
			name: "Selo Final",
			ranks: 5,
			desc: "Quando os Orbes da Explosão são consumidos pelo Fim do Pesadelo, o Ataque do alvo é reduzido adicionalmente em <span class='tooltip-value'>#</span> por Orbe.",
			rankInfo: [20, 40, 60, 80, 100],
		},
		{
			index: 3,
			name: "Espinho do Selo",
			ranks: 5,
			ranksnw: 3,
			desc: "Aumenta o dano bônus do Assassinato em <span class='tooltip-value'>#%</span> e concede uma chance de <span class='tooltip-value'>#%</span> para gerar um Orbe da Explosão.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 5,
			name: "Sombra da Escuridão",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta o dano base do Selo de Garganta em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 6,
			name: "Limitação da Velocidade",
			ranks: 2,
			desc: "Aumenta a duração do efeito devagar causado pelo Fim do Pesadelo em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [2, 3],
		},
		{
			index: 8,
			name: "Olho Crítico",
			ranks: 4,
			desc: "Aumenta a sua Maestria Física em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 9,
			name: "Crueldade Feroz",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduz o intervalo do Selo de Garganta em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [0.5, 1, 1.5, 2],
			parent: 2,
		},
		{
			index: 10,
			name: "Arrancada",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano físico</span><span class='right'>Intervalo: 8 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Curto alcance</span>\n\nAcerta o alvo duas vezes. Cada golpe que atingir causa 70% do seu Ataque mais <span class='tooltip-value'>#</span> de dano bônus. A Chance Crítica do primeiro ataque aumenta em 2% e do segundo em 4%. Gera um Orbe da Explosão.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [179, 262, 346, 431],
			rankInfo3: [801, 1418, 2024, 2619],
		},
		{
			index: 11,
			name: "Impulso",
			ranks: 3,
			desc: "Aumenta a Chance Crítica do Assassinato em <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 7, 10],
			parent: 1,
		},
		{
			index: 13,
			name: "Banimento Drástico",
			ranks: 3,
			desc: "O Selo de Garganta ganha uma chance de <span class='tooltip-value'>#%</span> para gerar um Orbe da Explosão adicional.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [8, 16, 24],
			parent: 5,
		},
		{
			index: 15,
			name: "Foco Mental",
			ranks: 3,
			desc: "Reduz o intervalo de uso do Perseguidor Mortal em <span class='tooltip-value'>#</span> segundo(s). A classificação 3 aumenta a duração do efeito devagar em 2 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6, 9],
		},
		{
			index: 16,
			name: "Ataque da Borda",
			ranks: 3,
			desc: "Aumenta a Precisão das suas habilidades Físicas de ataque em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Ataque da Sombra Quebrado",
			ranks: 2,
			desc: "Aumenta a sua Chance Crítica em <span class='tooltip-value'>#%</span> enquanto furtivo.",
			rankInfo: [20, 40],
		},
		{
			index: 18,
			name: "Arrancada Avançada",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta a Chance Crítica de ambos os ataques da Arrancada em <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
			parent: 6,
		},
		{
			index: 19,
			name: "Conhecimento do Selo",
			ranks: 3,
			desc: "Cada Orbe da Explosão aumenta adicionalmente o seu Dano Crítico em <span class='tooltip-value'>#%</span>. Aumenta a duração dos Orbes da Explosão em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 21,
			name: "Provocação Hipnótica",
			ranks: 3,
			desc: "A Lâmina da Hipnose silencia o alvo por <span class='tooltip-value'>#</span> segundo(s) ou até que sofra 3 ataques.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6],
		},
		{
			index: 22,
			name: "Lâmina Afiada",
			ranks: 3,
			desc: "Aumenta o dano base da Arrancada em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			parent: 12,
		},
		{
			index: 23,
			name: "Inflição de Ferida",
			ranks: 3,
			desc: "Suas habilidades de Finalização ganham uma chance de <span class='tooltip-value'>#%</span> de infligir o efeito da ferida ao alvo causando 0/1/2/3/4 Orbes da Explosão para aumentar sua Chance Crítica em 1%/2%/3%/4%/5% por 10 segundos.",
			rankInfo: [60, 80, 100],
		},
		{
			index: 26,
			name: "Centro do Alvo",
			ranks: 3,
			desc: "Quando o Selo de Garganta ou Arrancada acertarem um golpe, o alvo ficará atordoado por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: ['0-1', '1-2', '2-3'],
		},
		{
			index: 28,
			name: "Impiedade",
			ranks: 3,
			desc: "Aumenta o seu Dano Crítico em <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 29,
			name: "Selo Empoeirado",
			ranks: 2,
			desc: "Aumenta a duração do efeito de silêncio do Pesadelo Sombrio em <span class='tooltip-value'>#</span> segundo(s) e aumenta o dano base em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 30,
			name: "Arte Secreta - Explosão",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nZera os intervalos do Selo de Garganta e Arrancada e gera 2 Orbes da Explosão.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [333, 408],
			rankInfo3: [60, 45],
		},
		{
			index: 31,
			name: "Lâminas Compostas",
			ranks: 2,
			desc: "Aumenta a Chance Crítica das suas habilidades de Finalização em <span class='tooltip-value'>#%</span> e aumenta o dano bônus em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 33,
			name: "Contra-ataque Ligeiro",
			ranks: 3,
			desc: "Enquanto você estiver devagar, o Lançador reduz a velocidade do alvo igualmente por <span class='tooltip-value'>#</span> segundo(s). Tem uma chance de <span class='tooltip-value'>#%</span> dissipar o efeito devagar em você.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [4, 6, 8],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 34,
			name: "Arte Avançada - Explosão",
			ranks: 2,
			desc: "A Arte Secreta - Explosão tem uma chance de <span class='tooltip-value'>#%</span> de gerar um Orbe da Explosão adicional. Reduz o intervalo de uso em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [40, 80],
			rankInfo2: [5, 10],
			parent: 20,
		},
		{
			index: 37,
			name: "Cravos da Sombra",
			ranks: 3,
			desc: "Habilidades com ataques múltiplos têm uma chance de reduzir a Evasão do alvo em <span class='tooltip-value'>#</span> e a Saúde Máxima em <span class='tooltip-value'>#%</span> por 8 segundos. Com 1/2/3/4 Orbes da Explosão, a chance deste efeito ocorrer é de 15%/30%/45%/60%.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 38,
			name: "Agressão Intensificada",
			ranks: 2,
			desc: "Aumenta a duração da Intenção Cruel em <span class='tooltip-value'>#</span> segundo(s). Enquanto a Intenção Cruel estiver ativa, se o Assassinato, Selo de Garganta ou Arrancada acertarem um Crítico, o alvo sofre dano adicional de <span class='tooltip-value'>#%</span> dos ataques Físicos e de Escuridão subsequentes por <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4],
			rankInfo2: [15, 30],
			rankInfo3: [10, 15],
		},
		{
			index: 41,
			name: "Abraço da Morte",
			ranks: 3,
			desc: "Aumenta as durações da Sombra Destruidora e Representante de Morte em <span class='tooltip-value'>#</span> segundo(s). Enquanto o Representante de Morte estiver ativo, a Precisão das habilidades com golpes múltiplos aumenta em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 43,
			name: "Proibição",
			ranks: 2,
			desc: "Selo de Garganta e Arrancada têm uma chance de reduzir a velocidade de movimento do alvo em <span class='tooltip-value'>#%</span> e sua Precisão em <span class='tooltip-value'>#</span> por 4 segundos. Com 0/1/2/3/4 Orbes da Explosão, a chance deste efeito ocorrer é de <span class='tooltip-value'>#</span>.",
			rankInfo: [25, 50],
			rankInfo2: [15, 30],
			rankInfo3: ['10%/20%/30%/40%/50%', '20%/30%/40%/50%/60%'],
		},
		{
			index: 46,
			name: "Retalho Perigoso",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>559 Mana</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Dano físico</span><span class='right'>Sem intervalo</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Curto alcance</span>\n\nO Fim do Pesadelo tem uma chance de possibilitar o uso do Retalho Perigoso. 0/1/2/3/4 Orbes da Explosão têm uma chance de 10%/20%/30%/40%/50% de possibilitar o uso desta habilidade. Dura 45 segundo. Este efeito desaparece depois que você usar o Retalho Perigoso uma vez. Acerta o alvo quatro vezes. O Dano Crítico de cada golpe que acertar aumenta em 4%/6%/8%/10%, respectivamente. Cada golpe que atingir causa 70% do seu Ataque base mais 1396 de dano bônus.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// three
	[
		{
			index: 2,
			name: "Perseguição Ligeira",
			ranks: 5,
			desc: "Reduz o intervalo de uso Sombra de Perseguição em <span class='tooltip-value'>#</span> segundo(s). Aumenta a sua Evasão em <span class='tooltip-value'>#%</span> enquanto furtivo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [20, 40, 60, 80, 100],
		},
		{
			index: 4,
			name: "Sombra Fantasma",
			ranks: 5,
			desc: "Aumenta a sua velocidade do movimento em <span class='tooltip-value'>#%</span> enquanto a Sombra de Perseguição estiver ativa.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [7.5, 15, 22.5, 30, 37.5],
		},
		{
			index: 5,
			name: "Degolação",
			ranks: 3,
			desc: "Aumenta o dano base do Selo de Garganta em <span class='tooltip-value'>#%</span> e concede uma chance de <span class='tooltip-value'>#%</span> para acionar o efeito de Sombra Rápida. Enquanto você estiver afetado pela Sombra Rápida, o Selo de Garganta e Impulso da Dor não têm intervalo de uso. O efeito da Sombra Rápida termina depois de um uso.",
			rankInfo: [8, 16, 24],
			rankInfo2: [6, 12, 18],
		},
		{
			index: 6,
			name: "Assassino da Sombra",
			ranks: 3,
			desc: "Aumenta a Chance Crítica do Impulso da Dor em <span class='tooltip-value'>#%</span> e concede uma chance de <span class='tooltip-value'>#%</span> de acionar o efeito de Sombra Rápida. Enquanto estiver afetado pela Sombra Rápida, o Selo da Garganta e Impulso da Dor não têm intervalo de uso. A Sombra Rápida tem duração de 5 segundos e termina após um uso.",
			rankInfo: [3, 6, 9],
			rankInfo2: [6, 12, 18],
		},
		{
			index: 7,
			name: "Maestria em Assassinato",
			ranks: 4,
			desc: "Selo de Garganta e Impulso da Dor drenam o Mana do alvo em <span class='tooltip-value'>#%</span> e causam 50% da quantidade drenada como dano.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 4, 5, 6],
		},
		{
			index: 9,
			name: "Perseguição Persistente",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta o alcance do Perseguidor Mortal em <span class='tooltip-value'>#</span> metro(s).",
			rankInfo: [1, 2, 3],
		},
		{
			index: 10,
			name: "Evasão Rápida",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 300 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nAumenta a sua Evasão em <span class='tooltip-value'>#</span> e reduz o dano sofrido em <span class='tooltip-value'>#%</span>. Dura <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [106, 151, 197, 243],
			rankInfo3: [150, 180, 210, 240],
			rankInfo4: [20, 17, 14, 11],
			rankInfo5: [12, 14, 16, 18],
		},
		{
			index: 12,
			name: "Impulso de Precisão",
			ranks: 4,
			desc: "Aumenta a sua Precisão em <span class='tooltip-value'>#</span>.",
			rankInfo: [6, 12, 18, 24],
		},
		{
			index: 13,
			name: "Arte da Caça",
			ranks: 3,
			desc: "Reduz o intervalo de uso do Perseguidor Mortal em <span class='tooltip-value'>#</span> segundo(s) e aumenta o bônus da velocidade do movimento em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6, 9],
			rankInfo2: [20, 40, 60],
			parent: 5,
		},
		{
			index: 14,
			name: "Escapatória",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduz o intervalo de uso da Evasão Rápida em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40, 60],
			parent: 6,
		},
		{
			index: 15,
			name: "Proteção da Sombra Avançada",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduz o intervalo de uso da Proteção da Sombra em <span class='tooltip-value'>#</span> segundo(s) e aumenta sua duração em <span class='tooltip-value'>#</span> segundo(s). A classificação 4 também remove efeitos de sangramento.",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [2, 4, 6, 8],
		},
		{
			index: 17,
			name: "Sombra Imóvel",
			ranks: 2,
			desc: "Reduz o intervalo de uso do Assassinato em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2],
		},
		{
			index: 18,
			name: "Clarão de Velocidade",
			ranks: 2,
			desc: "A Evasão Rápida aumenta a velocidade do movimento em <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
			parent: 9,
		},
		{
			index: 20,
			name: "Ataque Rápido",
			ranks: 3,
			desc: "Aumenta a chance de que o Impulso da Dor e o Selo de Garganta acionem o efeito de Sombra Rápida em <span class='tooltip-value'>#%</span> e aumenta a duração da Sombra Rápida em <span class='tooltip-value'>#</span> segundo(s). Enquanto estiver sob o efeito da Sombra Rápida, o Selo da Garganta e Impulso da Dor não têm intervalo de uso. O efeito da Sombra Rápida termina depois de um uso.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [6, 12, 18],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 21,
			name: "Vento Ligeiro",
			ranks: 4,
			ranksnw: 3,
			desc: "O bônus de velocidade do movimento concedido pela Sombra da Tempestade aumenta em <span class='tooltip-value'>#%</span> e sua duração aumenta em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [0.5, 1, 1.5, 2],
		},
		{
			index: 22,
			name: "Sensação de Movimento",
			ranks: 1,
			desc: "Aumenta a Precisão das suas habilidades com ataques múltiplos em 15.",
			rankInfo: [],
		},
		{
			index: 23,
			name: "Olhos de Sombra",
			ranks: 1,
			desc: "A Proteção da Sombra gera um Orbe da Agonia e um Orbe da Explosão.",
			rankInfo: [],
			parent: 10,
		},
		{
			index: 25,
			name: "Velocidade do Vento",
			ranks: 2,
			desc: "Reduz o intervalo de uso Sombra da Tempestade em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20],
			parent: 14,
		},
		{
			index: 26,
			name: "Velocidade da Escuridão",
			ranks: 1,
			desc: "A Sombra Rápida zera os intervalos das suas habilidades de Finalização.",
			rankInfo: [],
		},
		{
			index: 28,
			name: "Disforme",
			ranks: 4,
			desc: "Aumenta a sua Evasão em <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12, 16],
		},
		{
			index: 29,
			name: "Armadilha da Sombra",
			ranks: 1,
			desc: "Perseguidor Mortal atordoa o alvo por 2 segundos se a distância entre você e o alvo for maior que 15 metros.",
			rankInfo: [],
		},
		{
			index: 30,
			name: "Contrato de Sangue",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: Instantâneo</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 120 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nDepois de 2 segundos, sua Saúde Máxima é reduzida em 20%. Enquanto este efeito estiver ativo, você fica imune a todos os efeitos de controle. Depois de <span class='tooltip-value'>#</span> segundo(s), sua Saúde Máxima volta ao normal.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [306, 376],
			rankInfo3: [5, 7],
		},
		{
			index: 31,
			name: "Teoria Furtiva",
			ranks: 3,
			desc: "Aumenta os efeitos da Intenção Cruel e da Evasão Rápida em <span class='tooltip-value'>#%</span> enquanto estiver furtivo. Aumenta o alcance da Lâmina da Hipnose em <span class='tooltip-value'>#</span> metro(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
			rankInfo2: [4, 8, 12],
		},
		{
			index: 33,
			name: "Crença da Velocidade",
			ranks: 3,
			desc: "Cada Orbe da Agonia e Orbe da Explosão aumenta a sua velocidade do movimento em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
		},
		{
			index: 35,
			name: "Manobra Focada",
			ranks: 3,
			desc: "A Manobra Focada é acionada toda vez que ficar furtivo ou ganhar um bônus na sua velocidade de movimento. A Manobra Focada aumenta a sua Precisão em <span class='tooltip-value'>#</span> e sua Evasão em <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45],
			rankInfo2: [6, 12, 18],
			rankInfo3: [9, 12, 15],
		},
		{
			index: 37,
			name: "Maestria em Golpe Mortal",
			ranks: 2,
			desc: "Reduz o intervalo de uso das habilidades de Finalização em <span class='tooltip-value'>#</span> segundo(s) e aumenta o dano base em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 38,
			name: "Contrato de Sangue Avançado",
			ranks: 2,
			desc: "Reduz o intervalo de uso do Contrato de Sangue em <span class='tooltip-value'>#</span> segundo(s) e aumenta sua duração em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20],
			rankInfo2: [1, 2],
			parent: 21,
		},
		{
			index: 40,
			name: "Qualidade Implacável",
			ranks: 3,
			desc: "Aumenta a sua Chance Crítica em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 42,
			name: "Ação Fásica",
			ranks: 3,
			desc: "Se você se esquivar de 5 ataques enquanto a Evasão Ligeira estiver ativa, um estado aprimorado de furtivo é acionado. O Furtivo não acaba quando você ataca ou é atacado por <span class='tooltip-value'>#</span> segundo(s) ou até que você sofra 4 ataques. O tempo entre duas esquivas bem-sucedidas não deve passar de 2 segundos.",
			rankInfo: [3, 4, 5],
		},
		{
			index: 43,
			name: "Perseguidor Disfarçado",
			ranks: 2,
			desc: "O dano bônus de Assassinato, Impulso da Dor, Selo de Garganta e Lançador aumenta em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
		},
		{
			index: 46,
			name: "Mordidas da Sombra",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>489 Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de escuridão</span><span class='right'>Intervalo: 10 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Curto alcance</span>\n\nRequer Furtivo. Acerta o alvo 3 vezes. Cada golpe que atingir causa 70% do seu Ataque base mais 1680 de dano bônus e há uma chance de 15% de silenciar o alvo por 3 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},	
	]
];