var data = [
	// one
	[
		{
			index: 1,
			name: "Explosão de Bola de Fogo",
			ranks: 5,
			ranksnw: 3,
			desc: "Aumenta o dano do efeito de queima causado pela Bola de Fogo em <span class='tooltip-value'>#%</span>, e sua duração em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [20, 40, 60, 80, 100],
		},
		{
			index: 3,
			name: "Força da Proteção",
			ranks: 5,
			desc: "Se for atingido enquanto estiver usando a Proteção Sinistra, você recebe o efeito da Força da Proteção por 5 segundos. Acumula 5 vezes. Aumenta o dano bônus do seu próximo ataque em uma quantidade equivalente a <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [0.4, 0.8, 1.2, 1.6, 2],
		},
		{
			index: 5,
			name: "Energia de Bola de Fogo",
			ranks: 5,
			ranksnw: 1,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> a chance de que a Bola de Fogo cause um efeito de queima ao alvo. Reduz o custo de Mana da Bola de Fogo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [6, 12, 18, 24, 30],
			parent: [0],
		},
		{
			index: 6,
			name: "Arte da Mágica Avançada",
			ranks: 2,
			desc: "Aumenta a duração da Arte da Mágica em <span class='tooltip-value'>#</span> minuto(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30],
		},
		{
			index: 8,
			name: "Chama Sinistra",
			ranks: 3,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> o bônus de Maestria em Fogo concedido pelo Conhecimento Sinistro.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Inspiração da Chama",
			ranks: 2,
			desc: "Reduz o intervalo de uso de Assalto em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
			parent: 2,
		},
		{
			index: 10,
			name: "Chama da Fúria",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 3 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nCausa 100% do seu Ataque base mais <span class='tooltip-value'>#</span> de dano bônus ao alvo e a todos os inimigos num raio de 8 metros.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [250, 368, 487, 608],
			rankInfo3: [782, 1420, 2047, 2663],
		},
		{
			index: 11,
			name: "Fogo Prolongado",
			ranks: 4,
			desc: "Feitiços de fogo aplicam o efeito de Fogo Prolongado em alvos paralisados causando dano instantâneo equivalente a <span class='tooltip-value'>#%</span> do seu Mana Máximo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 3, 4, 5],
		},
		{
			index: 14,
			name: "Chama da Fúria Avançada",
			ranks: 4,
			desc: "A Chama da Fúria reduz as Resistências Aquática, de Fogo e de Vento em <span class='tooltip-value'>#</span> por 15 segundos. Acumula 3 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15, 20],
			parent: 6,
		},
		{
			index: 15,
			name: "Transformação Ligeira",
			ranks: 3,
			ranksnw: 3,
			desc: "Reduz o intervalo de uso de Transformar em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
		},
		{
			index: 16,
			name: "Barreira da Chama",
			ranks: 3,
			desc: "Aumenta a sua Resistência de Fogo em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Chama dos Demônios",
			ranks: 3,
			ranksnw: 1,
			desc: "A Raiva dos Demônios causa um efeito de queima no alvo por 5 segundos, que causa <span class='tooltip-value'>#</span> de dano de Fogo por segundo.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 18,
			name: "Movimento do Vento Estável",
			ranks: 2,
			desc: "Aumenta a duração do Movimento do Vento em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4],
		},
		{
			index: 19,
			name: "Conjuração",
			ranks: 1,
			desc: "Transformar pode ser lançado em monstros imunes ao feitiço.",
			rankInfo: [],
			parent: 9,
		},
		{
			index: 21,
			name: "Respiração Profunda",
			ranks: 2,
			desc: "Dá à Raiva dos Demônios uma chance de <span class='tooltip-value'>#%</span> de derrubar os alvos.",
			rankInfo: [50, 100],
			parent: 11,
		},
		{
			index: 24,
			name: "Conhecimento de Fogo",
			ranks: 6,
			desc: "Aumenta o dano dos seus feitiços ofensivos de Fogo em <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
		},
		{
			index: 26,
			name: "Mestre da Ignição",
			ranks: 4,
			desc: "Aumenta o dano dos efeitos de queima causado por suas habilidades de Fogo em <span class='tooltip-value'>#%</span>. A duração dos efeitos aumenta em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 27,
			name: "Meditação do Fogo",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta em <span class='tooltip-value'>#</span> o bônus de Maestria em Fogo concedido pela Meditação Mágica.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45],
		},
		{
			index: 29,
			name: "Espelho de Reflexão",
			ranks: 3,
			desc: "O Escudo de Fogo cega os agressores, reduzindo a Precisão deles em <span class='tooltip-value'>#</span> por 5 segundos. Acumula 10 vezes.",
			rankInfo: [3, 6, 9],
			parent: [19],
		},
		{
			index: 30,
			name: "Escudo de Fogo",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 20 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nAumenta as suas Resistências Física e de Fogo em <span class='tooltip-value'>#</span> e a sua Chance Crítica em <span class='tooltip-value'>#%</span> por 5 minutos. Aumenta a sua Maestria em Fogo em <span class='tooltip-value'>#</span> por 10 segundos quando for atingido. Acumula 8 vezes. Não pode ser usado em conjunto com o Escudo de Gelo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [3, 5],
			rankInfo5: [5, 7],
		},
		{
			index: 31,
			name: "Queima Apressada",
			ranks: 2,
			desc: "Aumenta o dano dos seus efeitos de queima em <span class='tooltip-value'>#%</span> e reduz suas durações em <span class='tooltip-value'>#%</span> enquanto a Meditação Mágica estiver ativa.",
			rankInfo: [100, 200],
			rankInfo2: [20, 40],
			parent: [17],
		},
		{
			index: 33,
			name: "Chamas Apressadas",
			ranks: 3,
			desc: "Reduz os intervalos de uso da Bola de Fogo, Chama da Fúria e Raiva dos Demônios em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 34,
			name: "Mente em Fúria",
			ranks: 2,
			desc: "Reduz o Dano Crítico da Chama da Fúria e Raiva dos Demônios em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20],
		},
		{
			index: 36,
			name: "Vaporização",
			ranks: 3,
			desc: "A Bola de Fogo tem uma chance de <span class='tooltip-value'>#%</span> de zerar os intervalos de uso da Bola de Fogo, Chama da Fúria e Raiva dos Demônios.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Mestre do Calor",
			ranks: 3,
			desc: "Quando o seu Mana estiver acima de 50%, as suas habilidades de Fogo causarão o efeito de Armadura Derretida ao alvo. Armadura Derretida reduz a Defesa do alvo em <span class='tooltip-value'>#</span> por 10 segundos. Acumula 10 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45],
		},
		{
			index: 39,
			name: "Dissipação de Magia",
			ranks: 3,
			desc: "A Purgação Mágica reduz a Resistência de Fogo do alvo em <span class='tooltip-value'>#</span> por 20 segundos e drena uma quantidade de Mana do alvo equivalente a <span class='tooltip-value'>#%</span> do seu Ataque.",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 42,
			name: "Sopro do Inferno",
			ranks: 3,
			desc: "Aumenta o dano base da Bola de Fogo, Raiva dos Demônios e Chama da Fúria em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 43,
			name: "Evocação",
			ranks: 2,
			desc: "Dá aos seus feitiços de Fogo uma chance de <span class='tooltip-value'>#%</span> de aumentar o seu Dano Crítico em 2%. Pode ser acumulado 10 vezes e tem duração de 10 segundos.",
			rankInfo: [50, 100],
		},
		{
			index: 46,
			name: "Explosão de Faíscas",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>1346 Mana</span><span class='right'>Tempo de ativação: 5 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 25 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nCausa 200% do seu Ataque mais 5229 de dano bônus em inimigos num raio de 10 metros do alvo. Os inimigos atingidos ficarão atordoados por 1-5 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// two
	[
		{
			index: 1,
			name: "Trovão Paralisante",
			ranks: 4,
			ranksnw: 1,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> a chance de que o Trovão paralise um inimigo e reduz seu custo de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [5, 10, 15, 20],
		},
		{
			index: 2,
			name: "Fonte Mágica",
			ranks: 3,
			desc: "A Arte da Mágica aumenta adicionalmente o seu Mana Máximo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1.5, 3, 4.5],
		},
		{
			index: 3,
			name: "Sombra do Relâmpago",
			ranks: 2,
			desc: "Reduz o intervalo de uso do Trovão em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2], 
		},
		{
			index: 5,
			name: "Expansão de Choque",
			ranks: 4,
			ranksnw: 2,
			desc: "Aumenta o alcance do Trovão em <span class='tooltip-value'>#%</span>. Aumenta em <span class='tooltip-value'>#</span> o número máximo de alvos atingidos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [30, 60, 90, 120],
			rankInfo2: [2, 4, 6, 8],
			parent: [0],
		},
		{
			index: 7,
			name: "Contrato de Alma",
			ranks: 2,
			ranksnw: 1,
			desc: "Aumenta a duração da Proteção Sinistra em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20],
		},
		{
			index: 8,
			name: "Vento Sinistro",
			ranks: 3,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> o bônus de Maestria em Vento concedido pelo Conhecimento Sinistro.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Trovoada",
			ranks: 4,
			desc: "Aumenta a Chance Crítica de Trovão em <span class='tooltip-value'>#%</span>. Este efeito é duplicado enquanto a Tempestade de Trovão estiver ativa.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1.5, 3, 4.5, 6],
			parent: 3,
		},
		{
			index: 10,
			name: "Sequência de Relâmpago",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de vento</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nCausa 100% do seu Ataque mais <span class='tooltip-value'>#</span> de dano bônus em alvos em uma linha reta de 21 metros à sua frente. Tem uma chance de 25% de interromper o lançamento de habilidade do alvo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [259, 382, 506, 631],
			rankInfo3: [8, 7, 6, 5],
			rankInfo4: [1339, 2362, 3366, 4351],
		},
		{
			index: 11,
			name: "Energia da Proteção",
			ranks: 3,
			desc: "Reduz a quantidade de Mana drenada por ponto de dano que a Proteção Sinistra absorve em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 50],
			parent: 4,
		},
		{
			index: 14,
			name: "Golpe de Choque Avançado",
			ranks: 4,
			desc: "A Sequência de Relâmpago tem uma chance de <span class='tooltip-value'>#%</span> de paralisar e derrubar os alvos.",
			rankInfo: [25, 50, 75, 100],
			parent: 7,
		},
		{
			index: 15,
			name: "Alta Voltagem",
			ranks: 2,
			ranksnw: 1,
			desc: "Seus feitiços de ataque de Vento têm uma chance de <span class='tooltip-value'>#%</span> de gerar uma carga de Alta Voltagem. Depois que 8 cargas forem geradas, você receberá a força Tempestade de Trovão. A Tempestade de Trovão aumenta a Chance Crítica dos seus feitiços de vento e reduz os intervalos de uso. Dura 10 segundo.",
			rankInfo: [50, 100],
		},
		{
			index: 16,
			name: "Maestria em Vento",
			ranks: 4,
			ranksnw: 3,
			desc: "Aumenta a sua Maestria em Vento em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Transformar Avançado",
			ranks: 3,
			desc: "Aumenta a duração de Transformar em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [3, 6, 9],
		},
		{
			index: 18,
			name: "Movimento do Vento Ligeiro",
			ranks: 2,
			desc: "O Movimento do Vento aumenta a velocidade do movimento em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40],
		},
		{
			index: 20,
			name: "Concentração do Trovão",
			ranks: 6,
			desc: "Aumenta o dano dos seus feitiços ofensivos de Vento em <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
			parent: 11,
		},
		{
			index: 21,
			name: "Paralisia Avançada",
			ranks: 2,
			desc: "Os seus efeitos de paralisia reduzem a Evasão do alvo em <span class='tooltip-value'>#%</span> e a Resistência de Vento em <span class='tooltip-value'>#</span> A duração aumenta em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [50, 100],
			rankInfo2: [10, 20],
			rankInfo3: [3, 6],
		},
		{
			index: 23,
			name: "Energia Sustentada",
			ranks: 4,
			desc: "Aumenta a duração da Tempestade de Trovão em <span class='tooltip-value'>#</span> segundo(s). Cada carga de Alta Voltagem aumenta sua velocidade de movimento em 5%.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3, 4],
			parent: 10,
		},
		{
			index: 26,
			name: "Meditação do Vento",
			ranks: 3,
			desc: "Aumenta em <span class='tooltip-value'>#</span> o bônus de Maestria em Vento concedido pela Meditação Mágica.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45],
		},
		{
			index: 28,
			name: "Barreira do Trovão",
			ranks: 3,
			desc: "Aumenta a sua Resistência de Vento em <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 29,
			name: "Campo Estático",
			ranks: 3,
			ranksnw: 1,
			desc: "A Força Sinistra tem uma chance de <span class='tooltip-value'>#%</span> de paralisar alvos dentro do alcance a cada 4 segundos.",
			rankInfo: [40, 70, 100],
			parent: 20,
		},
		{
			index: 30,
			name: "Força Sinistra",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>50% do Mana atual</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Vento</span><span class='right'>Intervalo: 180 segundo(s)</span>\n<span class='left'>Maldição contra múltiplos alvos</span><span class='right'>Alcance: Nenhum</span>\n\Custa 50% do seu Mana atual. Num raio de <span class='tooltip-value'>#</span> metro(s), drena o Mana de até <span class='tooltip-value'>#</span> alvos. A quantidade de Mana perdido equivale a 30% do Mana atual dos alvos. A Explosão de Mana pode ser usada a cada 20 segundos. Por 20 segundos, os alvos que atacarem você perderão Mana equivalente a 1.0% do seu Mana Máxim\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [12, 15],
			rankInfo3: [20, 25],
		},
		{
			index: 33,
			name: "Constrição Sinistra",
			ranks: 4,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> a quantidade de Mana drenada dos agressores enquanto a Força Sinistra estiver ativa. Silencia os alvos quando o Mana deles cai para menos de 20% por <span class='tooltip-value'>#</span> segundo(s). (Disponível uma vez a cada 20 segundos.) Restaura uma quantidade do seu Mana equivalente à quantia drenada do alvo. Este efeito pode ocorrer até 20 vezes.",
			rankInfo: [50, 100, 150, 200],
			rankInfo2: [1, 2, 3, 4],
			parent: 19,
		},
		{
			index: 35,
			name: "Quebra de Gelo",
			ranks: 2,
			desc: "Os seus feitiços de ataque de Vento causam o efeito Gelo Quebrado nos alvos congelados. Pelos próximos 15 segundos, o alvo recebe <span class='tooltip-value'>#%</span> a mais de dano quando atacado.",
			rankInfo: [5, 10],
		},
		{
			index: 37,
			name: "Rajada de Vento",
			ranks: 3,
			desc: "Concede uma chance de <span class='tooltip-value'>#%</span> para que os seus feitiços de Vento interrompam o lançamento do alvo.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Poderio do Trovão",
			ranks: 3,
			desc: "Aumenta o dano do Trovão e Sequência do Relâmpago em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 39,
			name: "Vento Dissipante",
			ranks: 3,
			desc: "Concede à Purgação da Magia uma chance de <span class='tooltip-value'>#%</span> de dissipar uma força adicional do alvo.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 42,
			name: "Paralisia Amplificada",
			ranks: 2,
			desc: "Concede à Fúria da Natureza uma chance de <span class='tooltip-value'>#%</span> de causar um poderoso efeito paralisante no alvo, o que reduz sua Precisão em 60 e sua Evasão em 40 por 15 segundos.",
			rankInfo: [50, 100],
		},
		{
			index: 43,
			name: "Tempestade de Trovão",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>5% do Mana máximo</span><span class='right'>Tempo de ativação: Instantâneo</span>\n<span class='left'>Dano de vento</span><span class='right'>Intervalo: 90 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nConcede a força Tempestade de Trovão.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
		},
		{
			index: 46,
			name: "Purgatório do Relâmpago",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>1064 Mana</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Dano de vento</span><span class='right'>Intervalo: 15 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: Nenhum</span>\n\nAtinge seis vezes os alvos num raio de 16 metros. Cada golpe que atingir causa 50% do seu Ataque base mais 818 de dano bônus. Tem uma chance de 40% de paralisar os alvos afetados.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// three
	[
		{
			index: 1,
			name: "Precisão da Água",
			ranks: 5,
			ranksnw: 3,
			desc: "Aumenta em <span class='tooltip-value'>#</span> a Precisão da Flecha de Gelo e o dano base em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 2,
			name: "Gelo Arrepiante",
			ranks: 5,
			ranksnw: 1,
			desc: "A Flecha de Gelo causa o efeito Gelo Arrepiante que reduz as resistências de Água e Fogo do alvo em <span class='tooltip-value'>#</span> por 15 segundos. Acumula 10 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 5,
			name: "Inspiração do Gelo",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduz o intervalo de uso da Flecha de Gelo em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
			parent: [0],
		},
		{
			index: 7,
			name: "Dimensão da Extremidade",
			ranks: 4,
			desc: "Aumenta a duração da Barreira de Gelo em <span class='tooltip-value'>#</span> segundo(s). Restaura <span class='tooltip-value'>#%</span> da sua Saúde por segundo enquanto a Barreira de Gelo estiver ativa.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 8,
			name: "Fluxo Sinistro",
			ranks: 3,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> o bônus de Maestria em Água concedido pelo Conhecimento Sinistro.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Cristal de Gelo",
			ranks: 5,
			desc: "Concede uma chance de <span class='tooltip-value'>#%</span> para que a Flecha de Gelo congele os alvos por 6 segundos. Alvos congelados ficam paralisados e silenciados, mas a Defesa deles aumenta em 15%.",
			rankInfo: [3, 6, 9, 12, 15],
			parent: 2,
		},
		{
			index: 10,
			name: "Pico de Gelo",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de água</span><span class='right'>Intervalo: 5 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nInflige 100% do seu Ataque básico mais <span class='tooltip-value'>#</span> de bônus de dano. Esta habilidade aplica 3 acumulações de Gelo Arrepiante quando acerta um golpe Crítico. Se o alvo já estiver congelado, este sofrerá <span class='tooltip-value'>#</span> de dano bônus.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [168, 240, 313, 386],
			rankInfo3: [991, 1650, 2297, 2932],
			rankInfo4: [200, 300, 400, 500],
			parent: 1,
		},
		{
			index: 11,
			name: "Pele de Dragão",
			ranks: 3,
			desc: "A Proteção Sinistra cria um escudo protetor adicional por <span class='tooltip-value'>#</span> segundo(s). O escudo absorve 100% do dano sofrido e pode absorver uma quantidade total de dano igual a <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 13,
			name: "Supressão Mágica",
			ranks: 2,
			desc: "Transformar reduz a velocidade do movimento em <span class='tooltip-value'>#%</span> e a taxa de recuperação de Saúde em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [30, 60],
			rankInfo2: [15, 30],
		},
		{
			index: 14,
			name: "Pico de Gelo Avançado",
			ranks: 5,
			desc: "Aumenta o dano bônus causado pelo Pico de Gelo contra alvos congelados em <span class='tooltip-value'>#%</span> e a sua Chance Crítica em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: [2, 4, 6, 8, 10],
			parent: 6,
		},
		{
			index: 15,
			name: "Movimento do Vento Avançado",
			ranks: 2,
			desc: "Tem uma chance de <span class='tooltip-value'>#%</span> de dissipar o efeito enredar e devagar em você.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [50, 100],
		},
		{
			index: 18,
			name: "Congelamento Severo",
			ranks: 5,
			desc: "A Flecha de Gelo e o Pico de Gelo têm uma chance de <span class='tooltip-value'>#%</span> de acionar o efeito Congelamento Severo por 20 segundos. Este efeito desaparece depois de um uso. Enquanto o Congelamento Severo estiver ativo, o seu próximo Pico de Gelo tem 100% de chance de causar um golpe Crítico, e a sua próxima Flecha de Gelo tem 100% de chance de congelar o alvo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 20,
			name: "Concentração do Gelo",
			ranks: 6,
			desc: "Aumenta o dano dos seus feitiços ofensivos de Água em <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
		},
		{
			index: 21,
			name: "Domínio da Geada Avançado",
			ranks: 2,
			ranksnw: 1,
			desc: "Aumenta a duração do efeito congelante do Domínio da Geada em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
		},
		{
			index: 23,
			name: "Escudo Glacial",
			ranks: 3,
			desc: "Aumenta a sua Resistência Aquática em <span class='tooltip-value'>#</span> e a sua Defesa em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 25,
			name: "Fronteira",
			ranks: 4,
			desc: "Alvos congelados pelo Domínio da Geada perderão continuadamente <span class='tooltip-value'>#%</span> do Mana Máximo. Aumenta o dano base do Domínio da Geada em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [15, 30, 45, 60],
			parent: 13,
		},
		{
			index: 26,
			name: "Frio Perfurante",
			ranks: 3,
			desc: "Aumenta o dano bônus da Flecha de Gelo e do Pico de Gelo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 30,
			name: "Escudo de Gelo",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 20 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nAumenta as suas Resistências Física e Aquática em <span class='tooltip-value'>#</span> e a sua Defesa em <span class='tooltip-value'>#</span>. Reduz todo dano recebido em <span class='tooltip-value'>#%</span>. Tem duração de 5 minutos. Quando você for atacado, a velocidade do agressor é reduzida em 10%. Dura 5 segundo(s). Acumula 5 vezes. Não pode ser usado em conjunto com o Escudo de Fogo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [50, 80],
			rankInfo5: [3, 5],
		},
		{
			index: 31,
			name: "Escudo Congelado",
			ranks: 3,
			desc: "O Escudo de Gelo aumenta adicionalmente a sua Defesa em <span class='tooltip-value'>#%</span>. A duração do efeito devagar aumenta em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 17,
		},
		{
			index: 33,
			name: "Meditação da Água",
			ranks: 2,
			desc: "Reduz o intervalo de uso da Flecha de Gelo, Pico de Gelo, Domínio da Geada e Ponta de Gelo em <span class='tooltip-value'>#%</span> enquanto a Meditação Mágica estiver ativa.",
			rankInfo: [30, 60],
		},
		{
			index: 34,
			name: "Congelamento Severo Estendido",
			ranks: 2,
			desc: "O efeito de Congelamento Severo tem uma chance de <span class='tooltip-value'>#%</span> para permanecer ativo depois de usado.",
			rankInfo: [15, 30],
		},
		{
			index: 36,
			name: "Maestria em Gelo",
			ranks: 3,
			desc: "Aumenta a sua Maestria em Água em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 38,
			name: "Nevasca",
			ranks: 3,
			ranksnw: 3,
			desc: "A Fúria do Gelo tem uma chance de <span class='tooltip-value'>#%</span> de causar o efeito de Cristal de Gelo ao alvo por 3 segundos. Remove os efeitos de queima do alvo.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 39,
			name: "Espírito de Tempestade de Gelo",
			ranks: 2,
			desc: "Aumenta o dano base da Fúria do Gelo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			parent: 22,
		},
		{
			index: 42,
			name: "Prisão Congelada",
			ranks: 2,
			desc: "A Flecha de Gelo e Pico de Gelo removem os efeitos de queima e paralisação do alvo e causam o efeito Prisão Congelada por 10 segundos. A Prisão Congelada reduz o Ataque, Defesa e velocidade do movimento do alvo em <span class='tooltip-value'>#%</span>, <span class='tooltip-value'>#%</span> e 25%, respectivamente.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 43,
			name: "Água Dissipante",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduz os intervalos de uso do Domínio da Geada e Ponta de Gelo em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10],
		},
		{
			index: 47,
			name: "Ponta de Gelo",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>775 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de água</span><span class='right'>Intervalo: 45 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nAtaca até 16 alvos dentro de 10 metros. Causa 100% do seu Ataque mais 1852 de dano bônus. Causa um efeito congelante e aumenta a Defesa dos alvos em 5%, e impede que se movam. O efeito de congelamento termina depois que o alvo é atingido duas vezes.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			parent: 25,
		},	
	]
];