var data = [
    // one
    [
        {
            index: 1,
            name: "Céfiro",
            ranks: 5,
			ranksnw: 1,
			desc: "Incrementa la Precisión del Acorde del Viento, la Rapsodia del Viento, y el Réquiem en <span class='tooltip-value'>#</span>.",
            rankInfo: [9, 18, 27, 36, 45],
        },
        {
            index: 3,
            name: "Enfurecer",
            ranks: 5,
			desc: "Incrementa el Ataque adicional concedido por el Movimiento: Coraje por <span class='tooltip-value'>#</span> por pila.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6, 9, 12, 15],
        },
        {
            index: 5,
            name: "Conocimiento de la Melodía del Viento",
            ranks: 4,
			ranksnw: 1,
			desc: "Reduce las reactivaciones del Acorde del Viento, la Rapsodia del Viento, y del Réquiem en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [0.5, 1, 1.5, 2],
			parent: [0],
        },
        {
            index: 6,
            name: "Vento Disonante",
            ranks: 3,
			desc: "Reduce la reactivación del Viento Disonante en <span class='tooltip-value'>#</span> segundo(s). El Sonido Disonante reduce la Resistencia al Viento del blanco en <span class='tooltip-value'>#</span> más 5 por nivel de Sonido Disonante por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [1, 2, 3],
            rankInfo2: [10, 20, 30],
            rankInfo3: [10, 20, 30],
        },
        {
            index: 7,
            name: "Arte de la Música",
            ranks: 2,
			desc: "Incrementa el rango de tus Movimientos y habilidades de Himno en <span class='tooltip-value'>#</span> metros.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4],
        },
        {
            index: 8,
            name: "Extensión Acústica",
            ranks: 3,
			desc: "Incrementa la duración de tus Movimientos y de los Acordes en Do <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 10,
            name: "Solo del Viento",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nGenera 2 Acordes en Do que proveen el mismo efecto que aquel os generados por el Acorde del Viento.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [230, 327, 425, 524],
			rankInfo3: [30, 27, 24, 21],
        },
        {
            index: 11,
            name: "Rápida Melodía",
            ranks: 3,
			desc: "Cada Acorde Do activo incrementa tu velocidad de movimiento en <span class='tooltip-value'>#%</span>.",
            rankInfo: [4, 8, 12],
        },
        {
            index: 12,
            name: "Suave Oscilación",
            ranks: 4,
			desc: "Incrementa el efecto que el Movimiento: Coraje, el Movimiento: Fantasía, el Himno: Bautismo, el Himno: Majestad, y el Himno: Canción de la Vida tiene en los miembros del grupo en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15, 20],
        },
        {
            index: 13,
            name: "Sombra del Vento",
            ranks: 3,
			ranksnw: 1,
			desc: "Incrementa el Chance Crítico del Coro del Viento, el Réquiem, y la Rapsodia del viento en <span class='tooltip-value'>#%</span> Reducen la Defensa del blanco en <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [1, 2, 3],
			rankInfo2: [0.5, 1, 1.5],
			rankInfo3: [25, 50, 75],
			rankInfo4: [10, 12, 14],
			parent: 2,
        },
        {
            index: 15,
            name: "Música Divina del Viento",
            ranks: 3,
			desc: "Incrementa la duración de efecto de sueño infligido por la Divina Comedia en <span class='tooltip-value'>#</span> segundo(s). La Divina Comedia incrementa tu Evasión en <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			rankInfo3: [13, 14, 15],
        },
        {
            index: 16,
            name: "Melodía del Viento",
            ranks: 4,
			desc: "Incrementa tu Dominio del Viento <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 17,
            name: "Tormenta de Arena",
            ranks: 2,
			desc: "El Acorde de Viento, la Rapsodia del Viento y el Réquiem, reducen la efectividad del despliegue de habilidades sanatorias en el blanco en <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [15, 30],
			rankInfo2: [10, 15],
			parent: 9,
        },
        {
            index: 18,
            name: "Solo de Viento Avanzado",
            ranks: 3,
			desc: "Reduce la reactivación del Solo de Viento en 10 segundos. El Solo de Viento dispara el efecto de Viento de Protección, el cual reduce el daño entrante en <span class='tooltip-value'>#%</span> por 10 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [4, 7, 10],
			parent: 6,
        },
        {
            index: 19,
            name: "Maniobra del Viento",
            ranks: 2,
			desc: "La Canción del Viento otorga a los blancos afectados inmunidad frente a los efectos lentos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [],
			rankInfo2: [],
        },
        {
            index: 22,
            name: "Ritmo del Viento",
            ranks: 2,
			desc: "Reduce la reactivación de la Nota de Descanso en <span class='tooltip-value'>#</span> segundos. Incrementa el daño base del Acorde del Viento, la Rapsodia del Viento y el Réquiem en <span class='tooltip-value'>#%</span> mientras la Nota de Descanso está activa.",
            rankInfo: [10, 15],
			rankInfo2: [8, 16],
        },
        {
            index: 24,
            name: "Resistencia al Viento",
            ranks: 4,
			desc: "Incrementa tu Resistencia al Viento en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45, 60],
        },
        {
            index: 25,
            name: "Acorde del Viento Mejorado",
            ranks: 3,
			desc: "Un Acorde en Do activo incrementa el daño de base del Acorde del Viento, la Rapsodia del Viento, y el Réquiem en <span class='tooltip-value'>#%</span> Este efecto no se acumula con Acordes en Do.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 26,
            name: "Movimiento: Canción del Viento",
            ranks: 2,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span>Se activa cuando completas un una combinación de Acordes Do Do Do y tocas la Nota de Descanso. Aumenta la rapidez del movimiento de miembros del grupo dentro de 16 metros por 170% durante <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 50</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 65</span>\n\n'],
            rankInfo2: [10, 12],
        },
        {
            index: 28,
            name: "Ferocidad del Viento",
            ranks: 2,
			desc: "Tus habilidades de Movimiento incrementan la Precisión de los miembros del grupo afectados en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 25],
        },
        {
            index: 29,
            name: "Rapsodia del Viento Avanzada",
            ranks: 2,
			desc: "Reduce la reactivación de la Rapsodia del Viento en <span class='tooltip-value'>#</span> segundo(s). Incrementa el daño de base de la Rapsodia del Viento en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2],
			rankInfo2: [10, 20],
        },
        {
            index: 30,
            name: "Voz de Libertad",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Bendición multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nRepele los efectos lentos y de encierro de los miembros del grupo dentro de 16 metros. Puede ser usado cuando sea aturdido o silenciado.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [345, 414],
			rankInfo3: [90, 60],
        },
        {
            index: 31,
            name: "Velocidad del Vento",
            ranks: 2,
			desc: "Incrementa la velocidad de movimiento adicional de la Canción del Viento en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30],
        },
        {
            index: 35,
            name: "Movimiento Viento de Tormenta",
            ranks: 2,
			desc: "Tus habilidades de Movimiento incrementan el Chance Crítico y la Evasión de Crítica Y de los miembros del grupo en <span class='tooltip-value'>#%</span> y <span class='tooltip-value'>#%</span> respectivamente y tiene un <span class='tooltip-value'>#%</span> de probabilidad de restaurar 25% el máximo Maná de los miembros del grupo afectados cada 4 segundos. El Movimiento: Canción del viento tiene un 20% de probabilidad de restaurar el Maná cada segundo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [0.5, 1],
			rankInfo2: [1, 2],
			rankInfo3: [0.5, 1],
        },
        {
            index: 36,
            name: "Escudo Espada de Viento",
            ranks: 3,
			desc: "Reduce el daño entrante en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
        },
        {
            index: 38,
            name: "Voz de Libertad Avanzada",
            ranks: 2,
			desc: "La Voz de Libertad repele los efectos adormecedores. Reduce la reactivación de la Voz de Libertad en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
			parent: 21,
        },
        {
            index: 39,
            name: "Inspirar",
            ranks: 3,
			desc: "Cada pila del Movimiento: Coraje incrementa el Ataque de los miembros del grupo afectados en un <span class='tooltip-value'>#%</span> adicional de tu Ataque.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [0.6, 1.2, 1.8],
        },
        {
            index: 41,
            name: "Notas del Viento",
            ranks: 2,
			desc: "Incrementa el daño base del Acorde del Viento, la Rapsodia del Viento, la Tormenta Helada y el Réquiem en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30],
        },
        {
            index: 42,
            name: "Inspiración del Viento",
            ranks: 3,
			desc: "Reduce las reactivaciones del Solo del Viento, la Voz de Libertad, el Réquiem, y la Tormenta Helada en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 46,
            name: "Réquiem",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>491 Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>EI daño de viento</span><span class='right'>Reactivación: 6 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 14 metros</span>\n\nInflige 100% of de tu Ataque de base más 1495 de daño extra hasta 15 blancos dentro de 10 metros. Genera un Acorde en Do.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // two
    [
        {
            index: 1,
            name: "Acorde Avanzado de Gotas de Lluvia",
            ranks: 5,
			desc: "Incrementa el daño de base del Acorde de agua en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#%</span> de tu Dominio de Agua.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15, 20, 25],
            rankInfo2: [20, 40, 60, 80, 100],
        },
        {
            index: 3,
            name: "Rizado Ondulante",
            ranks: 5,
			desc: "Incrementa el Ataque adicional otorgado por el Aria: Aumento en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [30, 60, 90, 120, 150],
        },
        {
            index: 5,
            name: "Dominio de Rizado",
            ranks: 4,
			ranksnw: 1,
			desc: "Reduce la reactivación del Acorde del Agua, la Rapsodia del Agua, y la Fuga Congelada en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [0.5, 1, 1.5, 2],
        },
        {
            index: 6,
            name: "Agua Disonante",
            ranks: 3,
			desc: "Incrementa el Chance Crítico del Sonido Disonante en <span class='tooltip-value'>#%</span> El Sonido Disonante reduce la Resistencia al Agua en <span class='tooltip-value'>#</span> más 5 por Nivel de Sonido Disonante por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
        },
        {
            index: 7,
            name: "Sello de Hielo",
            ranks: 3,
			desc: "El Viento del Aria: Hielo reduce la velocidad de movimiento del blanco en un adicional <span class='tooltip-value'>#%</span> Rango 3 incrementa la duración del efecto congelante en 1 segundo.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 8,
            name: "Melodía Persistente",
            ranks: 3,
			desc: "Incrementa la duración de tus habilidades de Aria y Acordes en Re en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 9,
            name: "Hielo Serrado",
            ranks: 3,
			desc: "El Acorde de Agua, la Rapsodia de Agua y la Fuga Congelada reducen el Maná del blanco en un adicional <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6, 9],
			parent: 2,
        },
        {
            index: 10,
            name: "Sonata Agua",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nDispara el efecto Aria Égida, el cual previene que seas aturdido o silenciado, y reduce el daño entrante 40%. Restaura <span class='tooltip-value'>#%</span> de tu Maná máximo cuando eres golpeado. Este efecto puede ocurrir hasta 6 veces. La duración se incrementa <span class='tooltip-value'>#</span> segundos mientras 2 Acordes en Re están activos. Esta habilidad no es influido por los efectos controladores.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [268, 381, 496, 612],
			rankInfo3: [40, 35, 30, 25],
			rankInfo4: [5, 7, 9, 11],
			rankInfo5: [12, 14, 16, 18],
        },
        {
            index: 12,
            name: "Código Mágico",
            ranks: 3,
			desc: "Reduce los costos de Maná de tus habilidades ofensivas en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15],
        },
        {
            index: 13,
            name: "Aparición Inspirada",
            ranks: 3,
			desc: "Cada Acorde en Re activo incrementa tu Defensa en <span class='tooltip-value'>#%</span> y tu Evasión en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
			rankInfo2: [3, 6, 9],
        },
        {
            index: 15,
            name: "Música de Agua",
            ranks: 1,
			desc: "Cuando un blanco afectado es atacado por uno de tus Habilidades de Agua dentro de los 20 segundos, el blanco se congela por 3 segundos. El efecto congelante termina si el blanco es alcanzado 3 veces.",
            rankInfo: [],
        },
        {
            index: 16,
            name: "Dominio de la Melodía",
            ranks: 4,
			desc: "Incrementa tu Dominio del Agua <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 18,
            name: "Solo Avanzado de Fluidez",
            ranks: 3,
			desc: "Reduce la reactivación de la Sonata del Agua en <span class='tooltip-value'>#</span> segundos e incrementa la duración en 1<span class='tooltip-value'>#</span> segundo(s). Restaura una cantidad de Salud igual al <span class='tooltip-value'>#%</span> de tu Salud máxima cuando te alcanza mientras el Aria Egida está activa.",
            rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			rankInfo3: [2, 4, 6],
			parent: 7,
        },
        {
            index: 19,
            name: "Canto del Vento",
            ranks: 3,
			desc: "Incrementa la duración de la Canción del Viento en <span class='tooltip-value'>#</span> segundo(s). El reactivación de la Canción del viento también se reduce en <span class='tooltip-value'>#</span> segundos por cada punto puesto en este Talento.",
            rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
        },
        {
            index: 20,
            name: "Perdurar",
            ranks: 2,
			desc: "Incrementa tu Evasión de Crítica por <span class='tooltip-value'>#%</span> mientras una habilidad Armieia esta activa.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
        },
        {
            index: 22,
            name: "Dominio del Agua Ondulante",
            ranks: 2,
			desc: "Incrementa el Chance Crítico del Acorde del Agua, la Rapsodia del Agua, y la Fuga Congelada en <span class='tooltip-value'>#%</span> y su Daño Crítico en <span class='tooltip-value'>#%</span> mientras la Nota de Descanso está activa. Incrementa la duración del efecto congelante de la Fuga Congelada en <span class='tooltip-value'>#</span> segundo por punto en este talento.",
            rankInfo: [2, 4],
			rankInfo2: [5, 10],
			rankInfo3: [1, 2],
        },
        {
            index: 24,
            name: "Flujo Dividido",
            ranks: 4,
			desc: "Incrementa tu Resistencia Agua <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45, 60],
        },
        {
            index: 25,
            name: "Acorde del Agua Mejorado",
            ranks: 3,
			desc: "Un Acorde en Mi activo incrementa la daño de base del Acorde del Agua, la Rapsodia del Agua y la Fuga Congelada en <span class='tooltip-value'>#%</span>. Este efecto no se acumula con Acordes en Re adicionales.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 26,
            name: "Aria: Canción del Agua",
            ranks: 2,
			ranksnw: 1,
			desc: "Activado cuando completas una combinación de acordes Re Re Re y tocas la Nota del Descanso. Dura por <span class='tooltip-value'>#</span> segundos. Incrementa tu Ataque de base en <span class='tooltip-value'>#%</span> por cada acorde en Re subsecuente que generes. Se acumula 5 veces. Cada pila reinicia los 10 segundos de duración.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 50</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 65</span>\n\n'],
            rankInfo2: [15, 17],
			rankInfo3: [5, 6],
        },
        {
            index: 27,
            name: "Agudeza",
            ranks: 2,
			desc: "Incrementa el Ataque adicional otorgado por el Aria: Canción del Agua en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
			parent: 18,
        },
        {
            index: 29,
            name: "Rompehielos",
            ranks: 3,
			desc: "Tienes un <span class='tooltip-value'>#%</span> de probabilidad de reíniciar las reactivaciones del Acorde del Agua y la Rapsodia del Agua cuando activas una habilidad Aria.",
            rankInfo: [30, 60, 100],
        },
        {
            index: 30,
            name: "Triple Partita",
            ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>295 Maná</span><span class='right'>Tiempo de hechizar: 1.50 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: 90 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nReduces la reactivación de tus habilidades ofensivas Agua en 60%. Incrementa la reactivación de tus habilidades Viento y Agua en 60%. Incrementa el Chance Crítico de tus habilidades ofensivas Agua en 4% por 15 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n'],
        },
        {
            index: 31,
            name: "Armonías del Agua",
            ranks: 1,
			ranksnw: 1,
			desc: "Incrementa la duración de la Triple Partita en 6 segundos. Incrementa el rango de las habilidades de Agua en 3 metros mientras la Triple Partita está activa.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [],
			parent: 21,
        },
        {
            index: 33,
            name: "Rapsodia del Agua Avanzada",
            ranks: 3,
			desc: "La Rapsodia del Agua agota el Maná del blanco y maneja una cantidad de daño igual a la cantidad agotada más <span class='tooltip-value'>#</span>. Reduce la reactivación de la Rapsodia del Agua en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [100, 200, 300],
			rankInfo2: [1, 2, 3],
        },
        {
            index: 36,
            name: "Estocada Cuchilla de Hielo",
            ranks: 3,
			desc: "Incrementa tu Ataque <span class='tooltip-value'>#</span>.",
            rankInfo: [30, 60, 90],
        },
        {
            index: 38,
            name: "Triple Partita Avanzada",
            ranks: 3,
			desc: "La Triple Partita incrementa el Chance Crítico de tus habilidades de Agua en <span class='tooltip-value'>#%</span> En el Rango 3, también reduce sus reactivaciones en 20% y reduce la reactivación de la Triple Partita en 10 segundos.",
            rankInfo: [1, 2, 3],
			parent: 21,
        },
        {
            index: 39,
            name: "Rimas del Agua",
            ranks: 2,
			desc: "La Rapsodia del Agua y la Fuga Congelada reduce el Ataque del blanco en <span class='tooltip-value'>#%</span> y su Precisión en <span class='tooltip-value'>#</span> por 10 segundos mientras el Aria: Aumento está activa.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10],
			rankInfo2: [15, 30],
        },
        {
            index: 42,
            name: "Reflexión",
            ranks: 3,
			desc: "Mientras la Sonata del Agua está activa, los enemigos que te ataque son perjudicados por un efecto lento, el cual reduce su velocidad de movimiento en <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundos. Son encerrados mientras el Aria Égida está activa.",
            rankInfo: [30, 40, 50],
			rankInfo2: [5, 6, 7],
        },
        {
            index: 43,
            name: "Pulso de la Espada de Agua",
            ranks: 2,
			desc: "Incrementa el daño extra causado por el Acorde del Agua, la Rapsodia del agua y la Fuga Congelada en <span class='tooltip-value'>#%</span> La Tormenta Helada tiene un <span class='tooltip-value'>#%</span> de probabilidad de interrumpir el despliegue del blanco.",
            rankInfo: [10, 20],
			rankInfo2: [50, 100],
        },
        {
            index: 46,
            name: "Frozen Fugue",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>425 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Water damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 14 meters</span>\n\nDeals 100% of your base Attack plus 2217 bonus damage. Generates a D Chord. Has a 25% chance to freeze the target for 2 seconds.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // three
    [
        {
            index: 1,
            name: "Armonía de la Luz Avanzada",
            ranks: 5,
			desc: "Incrementa el daño base del Acorde de la Luz en <span class='tooltip-value'>#%</span> y el daño extra en <span class='tooltip-value'>#%</span> de tu Dominio de la Luz.",
            rankInfo: [5, 10, 15, 20, 25],
            rankInfo2: [20, 40, 60, 80, 100],
        },
        {
            index: 2,
            name: "Bendiciones de Luz",
            ranks: 5,
			desc: "Restaura <span class='tooltip-value'>#</span> de tu Salud cuando generas un Acorde en Mi.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [40, 80, 120, 160, 200],
        },
        {
            index: 5,
            name: "Brillo",
            ranks: 3,
			desc: "El Acorde de la Luz. la Sonata de la Luz, y el Concierto de la Vida reducen la Precisión de sus blanco en <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [12, 16, 20],
            rankInfo2: [6, 8, 10],
        },
        {
            index: 6,
            name: "Luz Disonante",
            ranks: 3,
			desc: "Incrementa el daño de base del Sonido Disonante en <span class='tooltip-value'>#%</span>. El Sonido Disonante reduce la Resistencia a la Luz del blanco en <span class='tooltip-value'>#</span> más 5 por cada nivel de Sonido Disonante por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [5, 10, 15],
            rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
        },
        {
            index: 7,
            name: "Música Divina de la Luz",
            ranks: 3,
			desc: "La Divina Comedia reduce la Defensa de los enemigos cercan os en <span class='tooltip-value'>#%</span> y su Precisión en <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [10, 13, 18],
            rankInfo2: [20, 30, 50],
			rankInfo3: [11, 13, 15],
        },
        {
            index: 8,
            name: "Melodía Sostenida",
            ranks: 3,
			desc: "Incrementa la duración de tus habilidades de Himno y Acordes en Mi <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 9,
            name: "Mirada Fija",
            ranks: 3,
			desc: "Reduces la probabilidad de ser interrumpido mientras despliegas habilidades de bendecir o sanar en <span class='tooltip-value'>#%</span>.",
            rankInfo: [20, 30, 50],
        },
        {
            index: 10,
            name: "Solo de Luz",
            ranks: 4,
			ranksnw: 1,	
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Sanar</span><span class='right'>Reactivación: 15 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nRestaura <span class='tooltip-value'>#</span> de tu Salud mientras 0/1/2/3 E Acordes estén activos. Tiene un 2% Chance Crítico, el cual causa que esta habilidad sane por el doble de la cantidad. Dispara el efecto Brújula Relajante, que incrementa la cantidad de Salud recuperada por tus habilidades de sanación en 20% por 10 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [201, 305, 410, 516],
			rankInfo3: ['1272-1404/1462-1615/1653-1825/1844-2036', '1881-2078/2164-2389/2446-2701/2728-3013', '2461-2717/2830-3125/3199-3533/3569-3941', '3010-3324/3462-3822/3913-4321/4365-4820'],
        },
        {
            index: 12,
            name: "Halo",
            ranks: 3,
			desc: "Incrementa el rango de todas las bendiciones y maleficios del grupo en <span class='tooltip-value'>#</span> metros.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
        },
        {
            index: 13,
            name: "Ducha Divina",
            ranks: 3,
			desc: "Himno: La Majestad incrementa tu Defensa en un adicional <span class='tooltip-value'>#%</span> y la Defensa de los miembros de grupo en un adicional <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30],
			rankInfo2: [3, 6, 9],
        },
        {
            index: 15,
            name: "Luz de Vida",
            ranks: 3,
			desc: "Reduce la reactivación de la Sonata de Vida en <span class='tooltip-value'>#</span> segundos. Adquiere una <span class='tooltip-value'>#%</span> probabilidad para repeler efectos lentos, de encierro, aturdidores, sangrantes y ardientes del blanco. La probabilidad de repeler los efectos se dobla en los blancos dentro de 8 metros.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 3, 4],
			rankInfo2: [15, 25, 35],
        },
        {
            index: 16,
            name: "Melodía de la Luz",
            ranks: 4,
			desc: "Incrementa tu Dominio de la Luz <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 17,
            name: "Coro Angelical",
            ranks: 2,
			desc: "Concede a tus habilidades sanadoras un <span class='tooltip-value'>#%</span> de probabilidad de disparar el Coro Angelical por 10 segundos. El Coro Angelical reduce las reactivaciones y costos de Maná de tus habilidades sanadoras en 50%.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30],
        },
        {
            index: 18,
            name: "Solo de Luz Avanzado",
            ranks: 3,
			desc: "Incrementa la cantidad de Salud recuperada por el Solo de la Luz I en <span class='tooltip-value'>#%</span> y reduce su reactivación en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 7,
        },
        {
            index: 19,
            name: "Melodía de Sanación",
            ranks: 3,
			desc: "Cada Acorde en Mi activo incrementa la efectividad de las habilidades sanadoras desplegadas en ti en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15],
        },
        {
            index: 22,
            name: "Notas de Luz",
            ranks: 2,
			desc: "Reduce las reactivaciones del Acorde de Luz, la Sonata de la Luz, y el Concierto de la Vida en <span class='tooltip-value'>#</span> segundo(s). Mientras la Nota de Descanso está activa, el daño entrante restaura <span class='tooltip-value'>#%</span> de tu Salud Máxima. Este efecto se dispara hasta 10 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
			rankInfo2: [3, 5],
        },
        {
            index: 24,
            name: "Resistencia al Halo",
            ranks: 4,
			desc: "Incrementa tu Resistencia a la Luz en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45, 60],
        },
        {
            index: 25,
            name: "Acorde de la Luz Mejorado",
            ranks: 3,
			desc: "Un Acorde en Mi activado incrementa el daño de base del Acorde de Luz, la Sonata de la Luz y el Concierto de la Vida <span class='tooltip-value'>#%</span>. Este efecto no se acumula con Acordes en Mi adicionales.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 26,
            name: "Himno: Canción de la Vida",
            ranks: 2,
			ranksnw: 1,
			desc: "Activado cuando completas una combinación de acordes Mi Mi Mi y tocas la Nota de Descanso. Restaura un 16% de la Salud máxima de todos los miembros del equipo dentro de <span class='tooltip-value'>#</span> metros y repele todos los efectos negativos en ellos. Incrementa la Salud máxima de todos los miembros del grupo en <span class='tooltip-value'>#%</span> por 10 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 50</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 65</span>\n\n'],
			rankInfo2: [20, 25],
			rankInfo3: [10, 15],
        },
        {
            index: 27,
            name: "Canción de los Santos",
            ranks: 2,
			desc: "El Himno: Canción de la Vida incrementa la efectividad de las habilidades sanadoras desplegadas en blancos afectados en <span class='tooltip-value'>#%</span> de su Salud máxima. Incrementa su/rv elocidad de movimiento y de Evasión en <span class='tooltip-value'>#%</span> y <span class='tooltip-value'>#</span> respectivamente en 6 segundos.",
            rankInfo: [5, 10],
			rankInfo2: [15, 30],
			rankInfo3: [15, 30],
			parent: 18,
        },
        {
            index: 29,
            name: "Baño de Luz",
            ranks: 2,
			desc: "Incrementa la cantidad de Salud recuperada por el himno: Bautismo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20],
        },
        {
            index: 30,
            name: "Canto del Renacimiento",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 5 segundos</span>\n<span class='left'>Revivir</span><span class='right'>Reactivación: 15 segundos</span>\n<span class='left'>Bendición objetivo único</span><span class='right'>Alcance: 16 metros</span>\n\nRevive el blanco y restaura el <span class='tooltip-value'>#%</span> de su Salud y Maná. Cada Acorde en Do activo incrementa el rango en 20%. Cada Acorde en Re activo reduce el costo de Maná en 20%. Cada Acorde en Mi reduce la reactivación en 5 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [1250, 1531],
			rankInfo3: [15, 30],
        },
        {
            index: 31,
            name: "Melodía Suavizante",
            ranks: 2,
			desc: "Incrementa la efectividad de las habilidades sanadoras en blancos afectados por tus habilidades de Aria, Movimiento, e Himno en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10],
        },
        {
            index: 35,
            name: "Life Awaken",
            ranks: 3,
			desc: "Tienes un <span class='tooltip-value'>#%</span> de probabilidad de reiniciarlas reactivaciones de la Sonata de la Vida y del Solo de la Luz cuando activas una habilidad Himno.",
            rankInfo: [40, 70, 100],
        },
        {
            index: 36,
            name: "Intercambio de la Espada de Luz",
            ranks: 3,
			desc: "Incrementa tu Evasión en <span class='tooltip-value'>#</span>.",
            rankInfo: [4, 8, 12],
        },
        {
            index: 38,
            name: "Canto del Renacimiento Avanzado",
            ranks: 2,
			desc: "El Canto del Renacimiento restaura un <span class='tooltip-value'>#%</span> adicional de la Salud y el Maná del blanco.",
            rankInfo: [15, 30],
			parent: 21,
        },
        {
            index: 39,
            name: "Crescendo",
            ranks: 3,
			desc: "El Acorde de la Luz, la Sonata de la Luz, y el Concierto de la Vida reducen la Evasión del blanco por <span class='tooltip-value'>#</span> y su Defensa en <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [8, 16, 24],
            rankInfo2: [4, 7, 10],
			rankInfo3: [9, 12, 15],
        },
        {
            index: 41,
            name: "Melodía San adora",
            ranks: 3,
			desc: "Incrementa la Probabilidad Crítica de la Sonada de la Vida, el Solo de la Luz, y del Himno: Bautismo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6, 9],
        },
        {
            index: 43,
            name: "Brillo",
            ranks: 2,
			desc: "Incrementa el daño extra del Acorde de la Luz, la Voz de Luz, y del Concierto de la Vida en <span class='tooltip-value'>#%</span> Reduce sus reactivación en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [15, 30],
			rankInfo2: [0.5, 1],
        },
        {
            index: 46,
            name: "Concierto de la Vida",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>736 Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño leve</span><span class='right'>Reactivación: 8 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Alcance: 14 metros</span>\n\nInflige 90% de tu Ataque de base más plus 6124 de dalo adicional. Genera un Acorde en Mi. Restaura una cantidad de Salud igual al 5% de tu Salud actual. Dispara el efecto Enigma de Vida, el cual incrementa la efectividad de las habilidades de sanación desplegadas en ti en 15% por 10 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ]
];