var data = [
	// one
	[
		{
			index: 1,
			name: "Marca de Ponto Fraco",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta a duração da Marca de Caçador em <span class='tooltip-value'>#</span> segundo(s) e reduz a Defesa do alvo em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: [60, 75, 90, 105, 120],
		},
		{
			index: 3,
			name: "Disparo Sólido",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta o dano bônus do Fogo à Vontade em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#%</span> da sua Maestria em Terra.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Armadilha da Alma Ligeira",
			ranks: 5,
			desc: "Reduz o intervalo da Bala Arranca-Mente em <span class='tooltip-value'>#</span> segundo(s) e aumenta seu dano bônus em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [2, 4, 6, 8, 10],
		},
		{
			index: 8,
			name: "Infusão da Terra",
			ranks: 5,
			desc: "Aumenta a sua Maestria em Terra em <span class='tooltip-value'>#</span> e o dano bônus das suas habilidades de Terra em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 9,
			name: "Análise Completa",
			ranks: 3,
			desc: "A Marca de Caçador reduz as Resistências do alvo em <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
			parent: [0],
		},
		{
			index: 10,
			name: "Disparo Mirado",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de terra</span><span class='right'>Intervalo: 5 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance:	18 metro(s)</span>\n\nCausa 100% do seu Ataque mais <span class='tooltip-value'>#</span> de dano bônus. Causa efeito de sangramento ao alvo, o que faz com que perca <span class='tooltip-value'>#</span> de Saúde por segundo por 10 segundos. Acumula 3 vezes. Tem uma chance de 25% de derrubar os alvos 4 metros para trás. O Disparo Mirado custa 1 Bala de Alma, tem seu dano bônus aumentado em 20%, o dano do efeito de sangramento é duplicado e a habilidade tem 100% de chance de jogar o alvo afetado pela Marca de Caçador4 metros para trás, enquanto o Tempo de Tiro Excelente estiver ativo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [124, 185, 246, 309],
			rankInfo3: [1313, 2312, 3293, 4256],
			rankInfo4: [29, 46, 64, 81],
		},
		{
			index: 11,
			name: "Preservação da Alma",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduz o custo de Fogo à Vontade em <span class='tooltip-value'>#%</span>, e aumenta a sua Chance Crítica em <span class='tooltip-value'>#%</span> enquanto a Captura de Alma estiver ativa.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [2, 4, 6, 8],
			parent: 1,
		},
		{
			index: 14,
			name: "Mira Precisa",
			ranks: 4,
			ranksnw: 2,
			desc: "Aumenta a Chance Crítica do Disparo Mirado em <span class='tooltip-value'>#%</span> e sua chance de derrubar o alvo para trás em <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [15, 30, 45, 60],
			parent: 5,
		},
		{
			index: 16,
			name: "Mente de Ferro",
			ranks: 4,
			desc: "Aumenta a sua Defesa e Resistência Terrestre em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Nuvem de Engasgo",
			ranks: 2,
			desc: "A Nuvem de Enfraquecimento reduz a velocidade de movimento dos alvos em <span class='tooltip-value'>#%</span>. Reduz o intervalo da Nuvem de Enfraquecimento em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20],
			rankInfo2: [15, 30],
		},
		{
			index: 18,
			name: "Surto de Poder",
			ranks: 2,
			desc: "Aumenta o dano base do Disparo Mirado em <span class='tooltip-value'>#%</span> e o dano de seu efeito de sangramento em <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
			rankInfo2: [50, 100],
			parent: 7,
		},
		{
			index: 19,
			name: "Treino com Alvos",
			ranks: 4,
			ranksnw: 2,
			desc: "O Fogo à Vontade reduz a Defesa do alvo em <span class='tooltip-value'>#</span> por 10 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [25, 50, 75, 100],
			parent: 6,
		},
		{
			index: 21,
			name: "Precisão de Pulso",
			ranks: 2,
			desc: "Aumenta o alcance máximo do Impulso de Disparo em <span class='tooltip-value'>#</span> metro(s), e reduz o seu alcance mínimo em <span class='tooltip-value'>#%</span> enquanto o Tempo de Tiro Excelente estiver ativo.",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
		},
		{
			index: 24,
			name: "Retorno da Força d'Alma",
			ranks: 3,
			ranksnw: 1,
			desc: "Restaura <span class='tooltip-value'>#%</span> do seu Mana Máximo quando você gera uma Bala de Alma.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 1.5, 2],
		},
		{
			index: 25,
			name: "Mestre Franco-Atirador",
			ranks: 2,
			ranksnw: 2,
			desc: "Faz com que o Disparo da Alma jogue para trás alvos com Saúde acima de <span class='tooltip-value'>#%</span>. Aumenta a Precisão da Mira Extrema em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [30, 20],
			rankInfo2: [20, 40],
		},
		{
			index: 26,
			name: "Contato",
			ranks: 3,
			desc: "A Guia de Precisão aumenta a sua Chance Crítica em <span class='tooltip-value'>#%</span>. Aumenta sua duração em <span class='tooltip-value'>#</span> minuto(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 27,
			name: "Fogo em Rajada",
			ranks: 3,
			desc: "Dá ao Fogo à Vontade uma chance de <span class='tooltip-value'>#%</span> de zerar os intervalos de uso das outras habilidades de ataque de Terra.",
			rankInfo: [4, 8, 12],
			parent: 11,
		},
		{
			index: 29,
			name: "Impacto Feroz",
			ranks: 1,
			desc: "A Mira Extrema causará o efeito de Planta e Humanoide nos alvos com Saúde acima de 75%, com efeito de sono por 30 segundos. Este efeito acaba quando o alvo for atacado.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 30,
			name: "Encorajar",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: Instantâneo</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: 5 segundo(s)</span>\n<span class='left'>Bênção de aura</span><span class='right'>Alcance: Nenhum</span>\n\nAumenta o Ataque de todos os integrantes do grupo num raio de 16 metros em <span class='tooltip-value'>#%</span> da sua Precisão. Enquanto esta habilidade estiver ativa, consumirá 0.30% do seu Mana Máximo a cada 2 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [206, 254],
			rankInfo3: [50, 70],
		},
		{
			index: 32,
			name: "Relaxamento",
			ranks: 3,
			desc: "Restaura <span class='tooltip-value'>#%</span> da sua Saúde Máxima quando você gera uma Bala de Alma.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 1.5, 2],
			parent: 13,
		},
		{
			index: 33,
			name: "Fissura",
			ranks: 3,
			desc: "Quando suas habilidades ofensivas de Terra acertam um Golpe Crítico, elas reduzem a Esquiva Crítica do alvo em <span class='tooltip-value'>#%</span> por até 10 segundos.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 35,
			name: "Marca da Dor",
			ranks: 3,
			desc: "Aumenta o dano causado em alvos afetados pela Marca de Caçador em <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 6, 8],
		},
		{
			index: 37,
			name: "Bala de Exorcismo Amplificada",
			ranks: 3,
			desc: "Aumenta o dano bônus da Bala de Exorcismo em <span class='tooltip-value'>#%</span>, e a chance de dissipar um buff do alvo aumenta em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 30, 40],
		},
		{
			index: 38,
			name: "Conduta",
			ranks: 2,
			desc: "Aumenta o Ataque concedido pela habilidade Encorajar em <span class='tooltip-value'>#%</span> de sua Precisão, e reduz o custo de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
			rankInfo2: [20, 40],
			parent: 18,
		},
		{
			index: 42,
			name: "Controle Letal",
			ranks: 2,
			desc: "O Disparo Duplo aumenta a Maestria em Terra e Chance Crítica em <span class='tooltip-value'>#</span> e <span class='tooltip-value'>#%</span> respectivamente. Cada ataque tem uma chance de <span class='tooltip-value'>#%</span> de gerar uma Bala de Alma em vez de perder.",
			rankInfo: [40, 80],
			rankInfo2: [4, 8],
			rankInfo3: [50, 100],
		},
		{
			index: 43,
			name: "Fortalecer Mais",
			ranks: 3,
			desc: "Aumenta o seu Ataque em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [25, 50, 75],
		},
		{
			index: 46,
			name: "Disparo Ofuscante",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>433 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Terra</span><span class='right'>Intervalo: 30 segundo(s)</span>\n<span class='left'>Maldição contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nReduz as Maestrias do alvo em 80 e seu Dano Crítico em 35% por 15 segundo(s).",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// two
	[
		{
			index: 2,
			name: "Arte de Recarregar",
			ranks: 5,
			desc: "Reduz o intervalo de uso da Recarga Rápida em <span class='tooltip-value'>#</span> segundo(s). Aumenta a quantidade de Saúde restaurada em <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 3,
			name: "Absorção",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta o dano base da Bala Arranca-Mente em <span class='tooltip-value'>#%</span> e a duração da Captura de Alma em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [4, 8, 12, 16, 20],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 5,
			name: "Caçador Profissional",
			ranks: 3,
			desc: "A Marca de Caçador reduz a Evasão do alvo em <span class='tooltip-value'>#</span>. Aumenta o alcance da Marca de Caçador em <span class='tooltip-value'>#</span> metro(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 8,
			name: "Precisão Fatal",
			ranks: 5,
			desc: "Aumenta a Precisão concedida pela Arte de Mirar em <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12, 16, 20],
		},
		{
			index: 9,
			name: "Sexto Sentido",
			ranks: 3,
			desc: "Aumenta a duração da Nuvem de Enfraquecimento em <span class='tooltip-value'>#</span> segundo(s) e a duração da Marca de Caçador em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 10,
			name: "Descarga da Alma",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 10 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nInflige 100% do seu Ataque mais <span class='tooltip-value'>#</span> de bônus de dano. Gera uma Bala de Alma. A Descarga da Alma não vai custar nenhuma Bala de Alma e o dano base aumenta em 20% enquanto o Tempo de Tiro Excelente estiver ativo. Um alvo afetado pela Marca de Caçador perderá <span class='tooltip-value'>#%</span> de seu Mana atual mais <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [126, 181, 238, 295],
			rankInfo3: [663, 1112, 1552, 1984],
			rankInfo4: [5, 6, 7, 8],
			rankInfo5: [150, 300, 400, 600],
		},
		{
			index: 11,
			name: "Fenda da Alma",
			ranks: 4,
			desc: "Aumenta a chance da Bala Arranca-Mente acionar a Captura de Alma em <span class='tooltip-value'>#%</span> e causa <span class='tooltip-value'>#</span> de dano adicional contra alvos com Saúde abaixo de 25%.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [60, 120, 180, 240],
			parent: 1,
		},
		{
			index: 13,
			name: "Névoa",
			ranks: 3,
			desc: "A Nuvem de Enfraquecimento reduz a Precisão dos alvos em <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 15,
			name: "Durabilidade",
			ranks: 4,
			ranksnw: 2,
			desc: "Aumenta a duração da Ação Rápida em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1.5, 3, 4.5, 6],
		},
		{
			index: 18,
			name: "Esfola da Alma",
			ranks: 3,
			ranksnw: 2,
			desc: "Aumenta o dano base da Descarga da Alma em <span class='tooltip-value'>#%</span>. Aumenta a quantidade de Mana drenado de alvos afetados pela Marca de Caçador em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [25, 50, 75],
			parent: 5,
		},
		{
			index: 19,
			name: "Sem Lançamento",
			ranks: 1,
			desc: "Dá à Ação Rápida uma chance de 100% de dissipar os efeitos enredar e devagar em você.",
			rankInfo: [],
			parent: 8,
		},
		{
			index: 20,
			name: "Direção de Alma",
			ranks: 3,
			desc: "Aumenta a Chance Crítica de todas as habilidades em <span class='tooltip-value'>#%</span> durante o Tempo de Tiro Excelente.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
		},
		{
			index: 21,
			name: "Cinza da Alma",
			ranks: 3,
			ranksnw: 2,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> o dano causado pelo Disparo da Alma e aumenta sua Chance Crítica em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 22,
			name: "Extração de Alma",
			ranks: 2,
			desc: "Reduz o intervalo de uso da Descarga de Alma em <span class='tooltip-value'>#</span> segundo(s). Reduz o Mana máximo de um alvo afetado pela Marca de Caçador em uma quantidade igual a <span class='tooltip-value'>#%</span> do Mana perdido por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [2, 4],
			rankInfo2: [50, 100],
			rankInfo3: [20, 30],
			parent: 9,
		},
		{
			index: 23,
			name: "Bala Perdida",
			ranks: 2,
			desc: "Dá ao Fogo à Vontade <span class='tooltip-value'>#%</span> de chance de gerar uma Bala de Alma enquanto a Meditação Mágica estiver ativa, e reduz o intervalo em <span class='tooltip-value'>#</span> segundo por ponto nesse talento.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40],
			rankInfo2: [0.5, 1],
		},
		{
			index: 26,
			name: "Suspensão da Alma",
			ranks: 2,
			desc: "Aumenta a duração do efeito devagar do Impulso de Disparo em alvos afetados pela Marca de Caçador em <span class='tooltip-value'>#</span> segundo(s). Aumenta o efeito devagar em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 27,
			name: "Concentração da Alma",
			ranks: 4,
			desc: "Sempre que você gerar uma Bala de Alma enquanto a Recarga Rápida estiver ativa, você terá uma chance de <span class='tooltip-value'>#%</span> de gerar uma Bala de Alma adicional. Reduz a chance de sofrer uma interrupção durante a ativação em <span class='tooltip-value'>#%</span>. Reduz o intervalo de uso da Recarga Rápida em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [25, 50, 75, 100],
			rankInfo3: [3, 7, 11, 15],
		},
		{
			index: 29,
			name: "Detonação de Alma",
			ranks: 3,
			desc: "Aumenta o dano bônus do Disparo da Alma em <span class='tooltip-value'>#%</span>. Quando acertar um Golpe Crítico, terá uma chance de <span class='tooltip-value'>#%</span> de atordoar o alvo por 2 segundos.",
			rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
			parent: 12,
		},
		{
			index: 30,
			name: "Explosão de Raiva",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 20 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nAcerta o alvo 6 vezes. Cada disparo causa 75% do seu Ataque mais <span class='tooltip-value'>#</span> de dano bônus. Requer pelo menos 1 Bala de Alma para lançar e pode custar até 3 Balas de Alma. Se tiver menos do que 3 Balas de Alma, você não atacará todas as 6 vezes, e o seu lançamento será interrompido. Enquanto o Tempo de Tiro Excelente estiver ativo, cada disparo tem uma chance de 30% de custar uma Bala de Alma adicional, mas o intervalo de uso cairá pela metade.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [517, 639],
			rankInfo3: [643, 1027],
		},
		{
			index: 32,
			name: "Maestria de Tiro Excelente",
			ranks: 3,
			desc: "A Ampliação de Poder de Fogo aumenta o seu Dano Crítico em <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 33,
			name: "Disparo Atordoante",
			ranks: 3,
			desc: "Aumenta o dano bônus da Mira Extrema em <span class='tooltip-value'>#%</span> e dá uma chance de <span class='tooltip-value'>#%</span> de causar 50% de efeito devagar por 4 segundos enquanto o Tempo de Tiro Excelente estiver ativo.",
			rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
		},
		{
			index: 35,
			name: "Restos da Alma",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta a quantidade de dano gerada pela Resolução da Alma em <span class='tooltip-value'>#%</span> e reduz seu custo de Mana em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 37,
			name: "Armadilha de Magia",
			ranks: 3,
			desc: "Aumenta o dano da Bala de Exorcismo em <span class='tooltip-value'>#%</span>, e faz com que os alvos afetados pela Marca de Caçador desçam das montarias e sejam silenciados por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Opressão",
			ranks: 3,
			desc: "Aumenta o dano bônus de cada disparo da Explosão de Raiva em <span class='tooltip-value'>#%</span>. Aumenta o dano em <span class='tooltip-value'>#%</span> enquanto o Tempo de Tiro Excelente estiver ativo.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 18,
		},
		{
			index: 40,
			name: "Sorte do Anão",
			ranks: 2,
			desc: "Aumenta em <span class='tooltip-value'>#%</span> a chance de que os seus ataques contra alvo único causem seus efeitos.",
			rankInfo: [5, 10],
		},
		{
			index: 42,
			name: "Marca de Dificuldade",
			ranks: 2,
			desc: "Reduz a velocidade do movimento dos alvos afetados pela Marca de Caçador em <span class='tooltip-value'>#%</span>. Reduz a eficácia das habilidades de cura lançadas no alvo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 43,
			name: "Foco da Alma",
			ranks: 3,
			desc: "Reduz o intervalo de uso da Resolução da Alma em <span class='tooltip-value'>#</span> segundo(s), do Disparo Duplo em <span class='tooltip-value'>#</span> segundos e da Munição Extra em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 15, 20],
			rankInfo3: [10, 20, 30],
			parent: 21,
		},
		{
			index: 46,
			name: "Munição Extra",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>463 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: 120 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nGera 5 Balas de Alma e zera os intervalos de uso da Resolução da Alma e Disparo Duplo. Pelos próximos 10 segundo(s), as suas habilidades de ataque de Fogo contra alvo único não gastarão Balas de Alma enquanto o Tempo de Tiro Excelente estiver ativo.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// three
	[
		{
			index: 1,
			name: "Bala de Calor",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta o dano bônus do Disparo da Alma em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [45, 60, 75, 90, 105],
		},
		{
			index: 2,
			name: "Explosão de Lava",
			ranks: 5,
			ranksnw: 2,
			desc: "Dá ao Disparo Penetrante <span class='tooltip-value'>#%</span> de chance de reduzir as resistências de Água e Fogo do alvo em <span class='tooltip-value'>#</span> por 10 segundos, além de <span class='tooltip-value'>#%</span> de chance de não gastar Balas de Alma enquanto o Tempo de Tiro Excelente estiver ativo.",
			rankInfo: [80, 85, 90, 95, 100],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Penetração Ligeira",
			ranks: 4,
			desc: "Reduz o intervalo de uso do Disparo Penetrante em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3, 4],
			parent: 1,
		},
		{
			index: 7,
			name: "Discreto",
			ranks: 3,
			ranksnw: 2,
			desc: "Aumenta o alcance da Nuvem de Enfraquecimento em <span class='tooltip-value'>#</span> metro(s) e reduz seu intervalo de uso em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 8,
			name: "Maestria de Chamas",
			ranks: 5,
			desc: "Aumenta a sua Maestria em Fogo em <span class='tooltip-value'>#</span> e aumenta seu efeito em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [2, 4, 6, 8, 10],
		},
		{
			index: 9,
			name: "Queima da Alma",
			ranks: 2,
			desc: "Dá ao Disparo da Alma uma chance de <span class='tooltip-value'>#%</span> de causar um efeito de queima ao alvo por 8 segundos, que inflige dano equivalente a <span class='tooltip-value'>#</span> mais 10% da sua Maestria em Fogo por segundo.",
			rankInfo: [50, 100],
			rankInfo2: [75, 100],
			parent: [0],
		},
		{
			index: 10,
			name: "Ancinho da Fúria",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 6 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 16 metro(s)</span>\n\nAtaca alvos em um arco de 90 graus num raio de 18.0 metro(s). Inflige 100% do seu Ataque mais <span class='tooltip-value'>#</span> de bônus de dano. Causa um efeito de queima a todos os alvos num raio de 6 metros por 5 segundo(s), que inflige dano equivalente a <span class='tooltip-value'>#</span> mais 20% da sua Maestria em Fogo. Além de 8 metros, a chance de queimar um alvo cai pela metade. O Ancinho da Fúria custa 1 Bala de Alma e tem seu dano bônus aumentado em 20%. A duração do efeito de queima aumenta em 3 segundo(s) e causa dano bônus equivalente a 30% da sua Maestria em Fogo enquanto o Tempo de Tiro Excelente estiver ativo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [202, 299, 398, 498],
			rankInfo3: [791, 1436, 2069, 2690],
			rankInfo4: [60, 120, 180, 240],
		},
		{
			index: 13,
			name: "Velocidade do Fogo",
			ranks: 4,
			ranksnw: 1,
			desc: "A Ação Rápida aumenta a velocidade do seu movimento em <span class='tooltip-value'>#%</span> e a da sua Evasão em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [15, 30, 45, 60],
		},
		{
			index: 14,
			name: "Calor Ardente",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta o dano do efeito de queima causado pelo Ancinho da Fúria em <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
			parent: 6,
		},
		{
			index: 15,
			name: "Inflamável",
			ranks: 1,
			desc: "A Nuvem de Enfraquecimento reduz a Saúde e o Mana dos alvos afetados por um efeito de queima em 1000. Este efeito aumenta em 500 para cada nível da Nuvem de Enfraquecimento. Também interrompe o lançamento e derruba os alvos para trás. (Só funciona contra monstros.)",
			rankInfo: [],
			parent: 3,
		},
		{
			index: 17,
			name: "Suporte Zeloso",
			ranks: 2,
			desc: "Reduz o intervalo da Ação Rápida em <span class='tooltip-value'>#</span> segundo(s). Dá á Ação Rápida uma chance de <span class='tooltip-value'>#%</span> de permanecer ativa depois de ser atingido 5 vezes.",
			rankInfo: [5, 10],
			rankInfo2: [50, 100],
			parent: 7,
		},
		{
			index: 19,
			name: "Fogo de Apoio",
			ranks: 2,
			desc: "Reduz os intervalos do Disparo Penetrante e Ancinho da Fúria em <span class='tooltip-value'>#%</span> enquanto a Recarga Rápida está ativa.",
			rankInfo: [50, 100],
		},
		{
			index: 20,
			name: "Sangue Ardente",
			ranks: 3,
			desc: "Aumenta a sua Resistência de Fogo em <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 21,
			name: "Penetração Eficiente",
			ranks: 3,
			ranksnw: 2,
			desc: "Aumenta o dano bônus do Disparo Penetrante em <span class='tooltip-value'>#%</span> e reduz seu custo de Mana em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 22,
			name: "Tela de Balas",
			ranks: 4,
			desc: "Aumenta o alcance das suas habilidades de ataque contra alvos múltiplos em <span class='tooltip-value'>#%</span>. Reduz o intervalo de uso do Ancinho da Fúria em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			parent: 8,
		},
		{
			index: 27,
			name: "Pedra Fundida",
			ranks: 4,
			desc: "O Impulso de Disparo reduz a Saúde Máxima dos alvos afetados por um efeito de queima em <span class='tooltip-value'>#</span> e reduz a eficácia de habilidades de cura lançadas neles em <span class='tooltip-value'>#%</span> por 10 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [250, 500, 750, 100],
			rankInfo2: [10, 20, 30, 40],
		},
		{
			index: 28,
			name: "Profissão das Chamas",
			ranks: 5,
			desc: "Reduz os custos de Mana das suas habilidades de ataque de Fogo em <span class='tooltip-value'>#%</span> e aumenta o dano delas em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 29,
			name: "Estilhaço",
			ranks: 3,
			desc: "Aumenta o dano do Disparo Penetrante em <span class='tooltip-value'>#%</span>. A duração do efeito devagar aumenta em <span class='tooltip-value'>#</span> segundo(s) enquanto o Tempo de Tiro Excelente estiver ativo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 13,
		},
		{
			index: 30,
			name: "Raiva Ardente",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: 30 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nAumenta o dano dos seus 3 próximos ataques em <span class='tooltip-value'>#%</span> do seu Ataque Máximo. A duração é de até 15 segundo(s). Se for atacado durante o lançamento, você entrará em um estado de raiva que aumenta a Chance Crítica dos seus próximos 3 ataques em 10% por até 15 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [245, 301],
			rankInfo3: [15, 20],
		},
		{
			index: 31,
			name: "Motivar",
			ranks: 3,
			desc: "Guia de Precisão aumenta o seu Dano Crítico em <span class='tooltip-value'>#%</span>. O custo de Mana é reduzido em <span class='tooltip-value'>#%</span> e aumenta a duração em <span class='tooltip-value'>#</span> minuto(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [5, 10, 15],
		},
		{
			index: 34,
			name: "Raiva Imortal",
			ranks: 3,
			ranksnw: 2,
			desc: "Aumenta a duração da Raiva Ardente em <span class='tooltip-value'>#</span> segundo(s). Se for atacado dentro de <span class='tooltip-value'>#</span> segundo(s) do lançamento, você entrará em um estado de Raiva.",
			rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			parent: 18,
		},
		{
			index: 35,
			name: "Captura de Alma",
			ranks: 3,
			desc: "Se usar a Raiva Ardente ou Disparo Duplo para matar um alvo dentro de um raio de 10 metros ao seu redor, ou matar o alvo enquanto a Resolução da Alma estiver ativa, você terá uma chance de <span class='tooltip-value'>#%</span> de gerar uma Bala de Alma.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 37,
			name: "Resistência de Alma",
			ranks: 3,
			desc: "Quando você for atacado enquanto a Resolução da Alma estiver ativa, suas Resistências aumentarão em <span class='tooltip-value'>#</span> e a sua Defesa em <span class='tooltip-value'>#</span> por 10 segundos. Acumula 3 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 39,
			name: "Queima Estendida",
			ranks: 2,
			desc: "Aumenta a duração dos seus efeitos de queima em <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 42,
			name: "Chispa del Alma",
			ranks: 2,
			desc: "Restablece <span class='tooltip-value'>#%</span> el máximo de tu Salud mientras que la Furia Extrema está activa. Estas habilidades tienen una <span class='tooltip-value'>#%</span> posibilidad de no cobrar ninguna Bala de Alma mientras que el Tiempo para el Tirador Experto está activo.",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
			parent: 20,
			// Error desc 1114. Used ES. //
		},
		{
			index: 43,
			name: "Fogo Enervante",
			ranks: 2,
			desc: "Disparo da Alma e Ancinho da Fúria causam ao alvo um efeito de queimadura reduzindo seu ataque base em <span class='tooltip-value'>#%</span>. Acumula 10 vezes.",
			rankInfo: [1, 2],
		},
		{
			index: 46,
			name: "Disparo de Alta Velocidade",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>781 Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 20 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nAtaca todos os inimigos em um raio de 16.0 metro(s) do alvo. Causa 15% do seu Ataque base mais 100% de dano bônus. Quando o Tempo de Tiro Excelente está ativo, o Disparo em Alta Velocidade consome 1 Bala da Alma, o dano bônus aumenta em 20% e ele desfaz efeitos de queimadura causados pelo Disparo da Alma e Ancinho da Fúria. Silencia o alvo por até 4 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	]
];