var data = [
    // one
    [
        {
            index: 1,
            name: "Etiqueta de Punto Débil",
            ranks: 5,
			ranksnw: 2,
			desc: "Incrementa la duración de Marca de Cazador en <span class='tooltip-value'>#</span> segundos, y reduce la Defensa de su objetivo en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6, 8, 10],
            rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: [60, 75, 90, 105, 120],
        },
        {
            index: 3,
            name: "Disparo Sólido",
            ranks: 5,
			ranksnw: 2,
			desc: "Incrementa el daño extra de Fuego a Voluntad en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#%</span> de tu Dominio de Tierra.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6, 8, 10],
            rankInfo2: [10, 20, 30, 40, 50],
        },
        {
            index: 6,
            name: "Trampa Veloz de Almas",
            ranks: 5,
			desc: "Reduce la reactivación de Bala Despellejante de Mente en <span class='tooltip-value'>#</span> segundo(s) e incrementa su daño extra en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3, 4, 5],
            rankInfo2: [2, 4, 6, 8, 10],
        },
        {
            index: 8,
            name: "Infusión de Tierra",
            ranks: 5,
			desc: "Incrementa tu Dominio de Tierra en <span class='tooltip-value'>#</span> y el daño extra de tus habilidades de Tierra en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30, 40, 50],
            rankInfo2: [1, 2, 3, 4, 5],
        },
        {
            index: 9,
            name: "Análisis Completo",
            ranks: 3,
			desc: "Marca de Cazador reduce las Resistencias del objetivo en un <span class='tooltip-value'>#</span> adicional.",
            rankInfo: [20, 40, 60],
			parent: [0],
        },
        {
            index: 10,
            name: "Disparo con Puntería",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>EI daño de tierra</span><span class='right'>Reactivación: 5 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Alcance: 18 metros</span>\n\nInflige el 100% de tu Ataque, más <span class='tooltip-value'>#</span> de daño extra. Inflige un efecto de sangrado sobre el objetivo, lo que causa que el mismo pierda <span class='tooltip-value'>#</span> de Salud cada segundo por 10 segundos. Se acumula 3 veces. Tiene una posibilidad del 25% de golpear al objetivo atrás 4 metros. Disparo con Puntería consume una Bala de Alma, su daño extra se incrementa en 20%, el daño del efecto de sangrado es duplicado, y la habilidad tiene una posibilidad del 100% de golpear a un objetivo afectado por Marca de Cazador hacia atrás 4 metros mientras el Tiempo para Tirador Experto está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [124, 185, 246, 309],
            rankInfo3: [1313, 2312, 3293, 4256],
			rankInfo4: [29, 46, 64, 81],
        },
        {
            index: 11,
            name: "Conservación de Alma",
            ranks: 4,
			ranksnw: 2,
			desc: "Reduce el costo de Maná de Fuego a Voluntad en <span class='tooltip-value'>#%</span> e incrementa su Chance Crítico en <span class='tooltip-value'>#%</span> mientras Captura Alma está activa.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45, 60],
            rankInfo2: [2, 4, 6, 8],
			parent: 1,
        },
        {
            index: 14,
            name: "Puntería Exacta",
            ranks: 4,
			ranksnw: 2,
			desc: "Incrementa el Chance Crítico de Disparo con Puntería en <span class='tooltip-value'>#%</span> y su posibilidad de golpear de nuevo a un objetivo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [2, 4, 6, 8],
            rankInfo2: [15, 30, 45, 60],
			parent: 5,
        },
        {
            index: 16,
            name: "Mente de Hierro",
            ranks: 4,
			desc: "Incrementa tu Defensa y tu Resistencia de Tierra en <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 17,
            name: "Nube Asfixiante",
            ranks: 2,
			desc: "Nube de Debilitamiento reduce la velocidad de movimiento del objetivo en un <span class='tooltip-value'>#%</span> adicional. Reduce la reactivación de Nube de Debilitamiento en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
            rankInfo2: [15, 30],
        },
        {
            index: 18,
            name: "Subida de Voltaje",
            ranks: 2,
			desc: "Incrementa el daño extra de Disparo con Puntería en <span class='tooltip-value'>#%</span> y el daño de su efecto de sangrado en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10],
            rankInfo2: [50, 100],
			parent: 7,
        },
        {
            index: 19,
            name: "Práctica de Tiro al Blanco",
            ranks: 4,
			ranksnw: 2,
			desc: "Fuego a Voluntad reduce la Defensa del objetivo en <span class='tooltip-value'>#</span> por 10 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [25, 50, 75, 100],
			parent: 6,
        },
        {
            index: 21,
            name: "Precisión de Pulso",
            ranks: 2,
			desc: "Incrementa el rango máximo de Disparo a Pulso en <span class='tooltip-value'>#</span> metros, y reduce su rango mínimo en <span class='tooltip-value'>#%</span> Tiempo para Tirador Experto está activo.",
            rankInfo: [3, 6],
            rankInfo2: [50, 100],
        },
        {
            index: 24,
            name: "Regreso de Fuerza de Alma",
            ranks: 3,
			ranksnw: 1,
			desc: "Restablece el <span class='tooltip-value'>#%</span> de tu Maná máximo cuando generas una Bala de Alma.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 1.5, 2],
        },
        {
            index: 25,
            name: "Maestro Francotirador",
            ranks: 2,
			ranksnw: 2,
			desc: "Disparo de Alma golpea de nuevo a objetivos con más del <span class='tooltip-value'>#%</span> de Salud. Incrementa la Precisión de Francotirador Extremo en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [30, 20],
			rankInfo2: [20, 40],
        },
        {
            index: 26,
            name: "Contacto",
            ranks: 3,
			desc: "Guía de Precisión incrementa tu Chance Crítico en un <span class='tooltip-value'>#%</span> adicional. Incrementa su duración en <span class='tooltip-value'>#</span> minutos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 1.5, 2],
			rankInfo2: [5, 10, 15],
        },
        {
            index: 27,
            name: "Estallido de Fuego",
            ranks: 3,
			desc: "Concede a Fuego a Voluntad una posibilidad del <span class='tooltip-value'>#%</span> de reiniciar las reactivaciones de tus otras habilidades ofensivas de Tierra.",
            rankInfo: [4, 8, 12],
			parent: 11,
        },
        {
            index: 29,
            name: "Impacto Violento",
            ranks: 1,
			desc: "Francotirador Extremo infligirá a objetivos Vegetales y Humanoides con más del 75% de Salud un efecto de sueño por 30 segundos. Este efecto termina cuando el objetivo es atacado.",
            rankInfo: [],
			parent: 14,
        },
        {
            index: 30,
            name: "Estimular",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: Instantáneo</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: 5 segundos</span>\n<span class='left'>Bendición de Aura</span><span class='right'>Alcance: Ninguno</span>\n\nIncrementa el Ataque de todos los miembros del grupo a 16 metros de ti en un <span class='tooltip-value'>#%</span> de tu Precisión. Mientras esta habilidad está activa, consumirá el 0.30% de tu Maná máximo cada 2 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [206, 254],
			rankInfo3: [50, 70],
        },
        {
            index: 32,
            name: "Relajación",
            ranks: 3,
			desc: "Restablece el <span class='tooltip-value'>#%</span> de tu Salud máxima cuando generas una Bala de Alma.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 1.5, 2],
			parent: 13,
        },
        {
            index: 33,
            name: "Grieta",
            ranks: 3,
			desc: "Cuando tus habilidades ofensivas de Tierra de un sólo objetivo bajan una Criatura, reducirán la Evasión de Crítica del objetivo en <span class='tooltip-value'>#%</span> por 10 segundos.",
            rankInfo: [2, 4, 6],
        },
        {
            index: 35,
            name: "Marca de Dolor",
            ranks: 3,
			desc: "Aumenta el daño relacionado con los objetivos afectados por la Marca del Cazador en <span class='tooltip-value'>#%</span>.",
            rankInfo: [4, 6, 8],
        },
        {
            index: 37,
            name: "Bala Exorcizante amplificada",
            ranks: 3,
			desc: "Aumenta el daño extra de la Bala Exorcizante por <span class='tooltip-value'>#%</span> y la oportunidad que tiene de esparcir un buff del objetivo por <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30],
			rankInfo2: [20, 30, 40],
        },
        {
            index: 38,
            name: "Guiar",
            ranks: 2,
			desc: "Aumenta la cantidad de Ataques otorgados por Promover en <span class='tooltip-value'>#%</span> por tu Precisión, y reduce el costo de su Maná en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30],
			rankInfo2: [20, 40],
			parent: 18,
        },
        {
            index: 42,
            name: "Control Mortífero",
            ranks: 2,
			desc: "El Doble Disparo aumenta tu Dominio de la Tierra y tu Chance Crítico en <span class='tooltip-value'>#</span> y <span class='tooltip-value'>#%</span> respectivamente. Cada ataque tiene una <span class='tooltip-value'>#%</span> posibilidad de generar una Bala de Alma en lugar de cobrar una.",
            rankInfo: [40, 80],
			rankInfo2: [4, 8],
			rankInfo3: [50, 100],
        },
        {
            index: 43,
            name: "Fortalecer",
            ranks: 3,
			desc: "Aumenta tu Ataque en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#</span>.",
            rankInfo: [2, 4, 6],
			rankInfo2: [25, 50, 75],
        },
        {
            index: 46,
            name: "Disparo Deslumbrante",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>433 Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Tierra</span><span class='right'>Reactivación: 30 segundos</span>\n<span class='left'>Maldición objetivo único</span><span class='right'>Alcance: 18 metros</span>\n\nReduce los Dominios del objetivo en 80 y el daño de su Crítica en 35% por 15 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // two
    [
        {
            index: 2,
            name: "Arte de Recargar",
            ranks: 5,
			desc: "Reduce la reactivación de Recarga Rápida en <span class='tooltip-value'>#</span> segundos. Incrementa la cantidad de Maná restablecido en <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [6, 12, 18, 24, 30],
        },
        {
            index: 3,
            name: "Absorción",
            ranks: 5,
			ranksnw: 2,
			desc: "Incrementa el daño de base de Bala Despellejante de Mente en <span class='tooltip-value'>#%</span> y la duración de Captura Alma en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [4, 8, 12, 16, 20],
            rankInfo2: [1, 2, 3, 4, 5],
        },
        {
            index: 5,
            name: "Cazador Profesional",
            ranks: 3,
			desc: "Marca de Cazador reduce la Evasión del objetivo en un <span class='tooltip-value'>#</span> adicional. Incrementa el rango de Marca de Cazador en <span class='tooltip-value'>#</span> metros.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15],
            rankInfo2: [3, 6, 9],
        },
        {
            index: 8,
            name: "Precisión Mortal",
            ranks: 5,
			desc: "Incrementa la cantidad de Precisión concedida por el Arte de Seleccionar un objetivo en <span class='tooltip-value'>#</span>.",
            rankInfo: [4, 8, 12, 16, 20],
        },
        {
            index: 9,
            name: "Sexto Sentido",
            ranks: 3,
			desc: "Incrementa la duración de Nube de Debilitamiento en <span class='tooltip-value'>#</span> segundo(s) y la duración de Marca de Cazador en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
            rankInfo2: [2, 4, 6],
        },
        {
            index: 10,
            name: "Liberación de Alma",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>El daño de fuego</span><span class='right'>Reactivación: 10 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Alcance: 18 metros</span>\n\nInflige el 100% de tu Ataque más <span class='tooltip-value'>#</span> de daño extra. Genera una Bala de Alma. Liberación de Alma no costará ninguna Bala de Alma y su daño extra se incrementa en 20% mientras el Tiempo para Tirador Experto está activo. Un objetivo afectado por Marca de Cazador perderá <span class='tooltip-value'>#%</span> de su Maná actual más <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [126, 181, 238, 295],
            rankInfo3: [663, 1112, 1552, 1984],
			rankInfo4: [5, 6, 7, 8],
			rankInfo5: [150, 300, 400, 600],
        },
        {
            index: 11,
            name: "Grieta de Alma",
            ranks: 4,
			desc: "Incrementa la posibilidad de Bala Despellejante de Mente de desencadenar Captura Alma en <span class='tooltip-value'>#%</span> y causa <span class='tooltip-value'>#</span> de daño extra a los objetivos con menos del 25% de Salud.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15, 20],
            rankInfo2: [60, 120, 180, 240],
			parent: 1,
        },
        {
            index: 13,
            name: "Neblina",
            ranks: 3,
			desc: "Nube de Debilitamiento reduce la Precisión de sus objetivos en un <span class='tooltip-value'>#%</span> adicional.",
            rankInfo: [20, 40, 60],
        },
        {
            index: 15,
            name: "Durabilidad",
            ranks: 4,
			ranksnw: 2,
			desc: "Incrementa la duración de Acción Rápida en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1.5, 3, 4.5, 6],
        },
        {
            index: 18,
            name: "Desnudamiento de Alma",
            ranks: 3,
			ranksnw: 2,
			desc: "Incrementa el daño de base de Liberación de Alma en <span class='tooltip-value'>#%</span>. Incrementa la cantidad de Maná drenado de los objetivos afectados por Marca de Cazador <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45],
			rankInfo2: [25, 50, 75],
			parent: 5,
        },
        {
            index: 19,
            name: "Desprendimiento",
            ranks: 1,
			desc: "Concede a Acción Rápida una posibilidad del 100% de disipar cualquier efecto lento o de atrapar sobre ti.",
            rankInfo: [],
			parent: 8,
        },
        {
            index: 20,
            name: "Guía de Alma",
            ranks: 3,
			desc: "Incrementa el Chance Crítico de tus habilidades en <span class='tooltip-value'>#%</span> mientras el Tiempo para Tirador Experto está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
        },
        {
            index: 21,
            name: "Ceniza de Alma",
            ranks: 3,
			ranksnw: 2,
			desc: "Incrementa el daño causado por Disparo de Alma en <span class='tooltip-value'>#%</span> e incrementa su Chance Crítico en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
        },
        {
            index: 22,
            name: "Extracción de Alma",
            ranks: 2,
			desc: "Reduce la reactivación de Liberación de Alma en <span class='tooltip-value'>#</span> segundos. Reduce el Maná máximo de un objetivo afectado por Marca de Cazador en una cantidad igual al <span class='tooltip-value'>#%</span> del total de Maná perdido por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [2, 4],
			rankInfo2: [50, 100],
			rankInfo3: [20, 30],
			parent: 9,
        },
        {
            index: 23,
            name: "Bala Perdida",
            ranks: 2,
			desc: "Concede a Fuego a Voluntad una posibilidad del <span class='tooltip-value'>#%</span> de generar una Bala de Alma mientras Captura Alma no está activa y reduce su reactivación en <span class='tooltip-value'>#</span> segundos por punto en este talento.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40],
			rankInfo2: [0.5, 1],
        },
        {
            index: 26,
            name: "Suspensión de Alma",
            ranks: 2,
			desc: "Incrementa la duración del efecto lento de Disparo a Pulso sobre los objetivos afectados por Marca de Cazador en <span class='tooltip-value'>#</span> segundos. Incrementa el efecto retrasador en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
			rankInfo2: [10, 20],
        },
        {
            index: 27,
            name: "Concentración de Alma",
            ranks: 4,
			desc: "Cada vez que generas una Bala de Alma mientras Recarga Rápida esta activa, tienes una posibilidad del <span class='tooltip-value'>#%</span> de generar una Bala de Alma adicional. Reduce la posibilidad de ser interrumpido mientras hechizas en <span class='tooltip-value'>#%</span>. Reduce la reactivación de Recarga Rápida en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45, 60],
			rankInfo2: [25, 50, 75, 100],
			rankInfo3: [3, 7, 11, 15],
        },
        {
            index: 29,
            name: "Detonación del Alma",
            ranks: 3,
			desc: "Aumenta el daño extra del Disparo de Alma en <span class='tooltip-value'>#%</span>. Cuando lanza una Crítica, tiene una <span class='tooltip-value'>#%</span> oportunidad de impactar el objetivo por 2 segundos.",
            rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
			parent: 12,
        },
        {
            index: 30,
            name: "Estallido de Ira",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>El daño de fuego</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Alcance: 18 metros</span>\n\nGolpea el objetivo 6 veces. Cada disparo causa el 75% de tu Ataque más <span class='tooltip-value'>#</span> de daño extra. Requiere al menos 1 Bala de Alma para hechizar, y cuesta hasta 3 Balas de Alma. Si hay menos de 3 Balas de Alma disponibles, no atacarás las 6 veces, y tu hechizo será interrumpido. Mientras Tiempo para Tirador Experto está activo, cada disparo tiene una posibilidad del 30% de costar una Bala de Alma extra, pero la reactivación será dividida en dos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [517, 639],
			rankInfo3: [643, 1027],
        },
        {
            index: 32,
            name: "Dominio de Buen Tirador",
            ranks: 3,
			desc: "La Amplificación de Arsenal aumenta tu daño de Crítica con una adición de <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6, 9],
        },
        {
            index: 33,
            name: "Disparo Contundente",
            ranks: 3,
			desc: "Aumenta el daño extra de Lanzamiento Extremo por <span class='tooltip-value'>#%</span> y le otorga una <span class='tooltip-value'>#%</span> oportunidad de disminuir la velocidad del objetivo en 50% por 4 segundos mientras que el Tiempo para el Tirador Experto está activo.",
            rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
        },
        {
            index: 35,
            name: "Despojos del Alma",
            ranks: 3,
			ranksnw: 1,
			desc: "Aumenta la cantidad de daño absorbido por la Resolución del Alma por <span class='tooltip-value'>#%</span> y reduce el costo de su Maná en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
        },
        {
            index: 37,
            name: "Trampa de Magia",
            ranks: 3,
			desc: "Aumenta el daño extra de la Bala Exorcizante por <span class='tooltip-value'>#%</span> y hace que se desmonten y se silencien los objetivos afectados por la Marca del Cazador durante <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
        },
        {
            index: 38,
            name: "Opresión",
            ranks: 3,
			desc: "Aumenta el daño extra de cada disparo de la Metralla de Ira en <span class='tooltip-value'>#%</span>. Aumenta su daño en <span class='tooltip-value'>#%</span> mientras que el Tiempo para el Tirador Experto está activo.",
            rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 18,
        },
        {
            index: 40,
            name: "Suerte de Enano",
            ranks: 2,
			desc: "Aumenta la posibilidad de que tus ataques al único objetivo apliquen sus efectos en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10],
        },
        {
            index: 42,
            name: "Marca Entorpecedora",
            ranks: 2,
			desc: "Reduce la velocidad del movimiento de los objetivos afectados por la Marca del Cazador en <span class='tooltip-value'>#%</span>. Reduce la efectividad de las habilidades curativas reutilizadas por el objetivo por un extra de <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20],
			rankInfo2: [10, 20],
        },
        {
            index: 43,
            name: "Enfoque del Alma",
            ranks: 3,
			desc: "Reduce el retraso de la Resolución del Alma en <span class='tooltip-value'>#</span> segundos, Doble Disparo en <span class='tooltip-value'>#</span> segundos, y Munición de más en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [5, 10, 15],
			rankInfo2: [10, 15, 20],
			rankInfo3: [10, 20, 30],
			parent: 21,
        },
        {
            index: 46,
            name: "Munición de más",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>463 Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: 120 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nGenera 5 Balas de Alma, y reajusta las reactivaciones de la Resolución del Alma y el Doble Disparo. Durante los siguientes 10 segundos, tus habilidades de Fuego para atacar un solo objetivo note cuesta ninguna Bala de Alma mientras que el Tiempo para el Tirador Experto está activo. Esta habilidad no se ve afectada por los efectos de control.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // three
    [
        {
            index: 1,
            name: "Bala de Calor",
            ranks: 5,
			ranksnw: 2,
			desc: "Incrementa el daño extra de Disparo de Alma en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6, 8, 10],
            rankInfo2: [45, 60, 75, 90, 105],
        },
        {
            index: 2,
            name: "Estallido de Lava",
            ranks: 5,
			ranksnw: 2,
			desc: "Concede a Disparo Penetrante una posibilidad del <span class='tooltip-value'>#%</span> de reducir las Resistencias de Tierra y Fuego del objetivo en <span class='tooltip-value'>#</span> por 10 segundos, y una posibilidad del <span class='tooltip-value'>#%</span> de no consumir Balas de Alma mientras Tiempo para Tirador Experto está activo.",
            rankInfo: [80, 85, 90, 95, 100],
            rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: [10, 20, 30, 40, 50],
        },
        {
            index: 6,
            name: "Penetración Veloz",
            ranks: 4,
			desc: "Reduce la reactivación de Disparo Penetrante en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3, 4],
			parent: 1,
        },
        {
            index: 7,
            name: "Discreto",
            ranks: 3,
			ranksnw: 2,
			desc: "Incrementa el rango de Nube de Debilitamiento en <span class='tooltip-value'>#</span> metros y reduce su reactivación en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
        },
        {
            index: 8,
            name: "Dominio de Llama",
            ranks: 5,
			desc: "Incrementa tu Dominio de Fuego en <span class='tooltip-value'>#</span> e incrementa su efecto en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30, 40, 50],
            rankInfo2: [2, 4, 6, 8, 10],
        },
        {
            index: 9,
            name: "Quemadura de Alma",
            ranks: 2,
			desc: "Concede a Disparo de Alma una posibilidad del <span class='tooltip-value'>#%</span> de infligir un efecto de quemadura al objetivo por 8 segundos, lo que causa una cantidad de daño igual al <span class='tooltip-value'>#</span> más 10% de tu Dominio de Fuego cada segundo.",
            rankInfo: [50, 100],
			rankInfo2: [75, 100],
			parent: [0],
        },
        {
            index: 10,
            name: "Rastrillo de Furia",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>EI daño de fuego</span><span class='right'>Reactivación: 6 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 16 metros</span>\n\nAtaca a objetivos en un arco de 90 grados dentro de 18.0 metros. Causa el 100% de tu Ataque más <span class='tooltip-value'>#</span> de daño extra. Inflige un efecto de quemadura sobre cada objetivo dentro de 8 metros por 5 segundos, lo que causa un daño igual al <span class='tooltip-value'>#</span> más 20% de tu Dominio de Fuego. Pasando los 8 metros, la posibilidad de quemar a un objetivo es dividida por la mitad. Rastrillo de Furia cuesta 1 Bala de Alma, su daño extra se incrementa en 20%, la duración del efecto de quemadura se incrementa en 3 segundos, y causa un daño extra igual al 30% de tu Dominio de Fuego mientras el Tiempo para Tirador Experto está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [202, 299, 398, 498],
			rankInfo3: [791, 1436, 2069, 2690],
			rankInfo4: [60, 120, 180, 240],
        },
        {
            index: 13,
            name: "Velocidad de Fuego",
            ranks: 4,
			ranksnw: 1,
			desc: "Acción Rápida incrementa la velocidad de tu movimiento en un <span class='tooltip-value'>#%</span> adicional y tu Evasión en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15, 20],
			rankInfo2: [15, 30, 45, 60],
        },
        {
            index: 14,
            name: "Calor Abrasador",
            ranks: 3,
			ranksnw: 1,
			desc: "Incrementa el daño del efecto de quemadura infligido por Rastrillo de Furia en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100, 150],
			parent: 6,
        },
        {
            index: 15,
            name: "Inflamable",
            ranks: 1,
			desc: "Nube de Debilitamiento reduce la Salud y el Maná de los objetivos afectados por un efecto de quemadura en 1000. Este efecto se incrementa en 500 por cada nivel de Nube de Debilitamiento. También interrumpe el hechizo y golpea de nuevo el objetivo. (Sólo es efectivo contra pandillas.)",
            rankInfo: [],
			parent: 3,
        },
        {
            index: 17,
            name: "Apoyo Entusiasta",
            ranks: 2,
			desc: "Reduce la reactivación de Acción Rápida en <span class='tooltip-value'>#</span> segundos. Concede a Acción Rápida una posibilidad del <span class='tooltip-value'>#%</span> de permanecer activa luego de haber sido golpeada 5 veces.",
            rankInfo: [5, 10],
			rankInfo2: [50, 100],
			parent: 7,
        },
        {
            index: 19,
            name: "Fuego de Respaldo",
            ranks: 2,
			desc: "Reduce las reactivaciones de Disparo Penetrante y Rastrillo de Furia en <span class='tooltip-value'>#%</span> mientras Recarga Rápida está activa.",
            rankInfo: [50, 100],
        },
        {
            index: 20,
            name: "Sangre Abrasadora",
            ranks: 3,
			desc: "Incrementa tu Resistencia de Fuego en <span class='tooltip-value'>#</span>.",
            rankInfo: [20, 40, 60],
        },
        {
            index: 21,
            name: "Penetración Eficiente",
            ranks: 3,
			ranksnw: 2,
			desc: "Incrementa el daño extra de Disparo Penetrante en <span class='tooltip-value'>#%</span> y reduce su costo de Maná en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
        },
        {
            index: 22,
            name: "Pantalla de Bala",
            ranks: 4,
			desc: "Incrementa el rango de tus habilidades ofensivas multi-objetivo en <span class='tooltip-value'>#%</span> Reduce la reactivación de Rastrillo de Furia en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			parent: 8,
        },
        {
            index: 27,
            name: "Piedra Fundida",
            ranks: 4,
			desc: "Tiro de Pulso reduce la Salud máxima de los objetivos afectados por un efecto de quemadura en <span class='tooltip-value'>#</span> y reduce la efectividad de las habilidades de sanación lanzadas sobre ellos en <span class='tooltip-value'>#%</span> por 10 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [250, 500, 750, 100],
			rankInfo2: [10, 20, 30, 40],
        },
        {
            index: 28,
            name: "Profesión de Llama",
            ranks: 5,
			desc: "Reduce los costos de Maná de tus habilidades ofensivas de Fuego en <span class='tooltip-value'>#%</span> e incrementa su daño en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: [1, 2, 3, 4, 5],
        },
        {
            index: 29,
            name: "Metralla",
            ranks: 3,
			desc: "Aumenta el daño del Disparo Penetrante en <span class='tooltip-value'>#%</span>. Aumenta la duración de su efecto lento en <span class='tooltip-value'>#</span> segundo(s) mientras que el Tiempo para el Tirador Experto está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 13,
        },
        {
            index: 30,
            name: "Ira Ardiente",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: 30 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nIncrementa el daño de tus próximos 3 ataques en <span class='tooltip-value'>#%</span> de tu Ataque máximo. Dura hasta por 15 segundos. Si eres atacado mientras estás hechizando, entrarás en un estado de ira, lo que incrementa el Chance Crítico de tus próximos 3 ataques en 10% por hasta 15 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [245, 301],
			rankInfo3: [15, 20],
        },
        {
            index: 31,
            name: "Motivar",
            ranks: 3,
			desc: "La Orientación de Presición aumenta el daño de tu Crítica en <span class='tooltip-value'>#%</span>. Reduce el costo de su Maná en <span class='tooltip-value'>#%</span> y aumenta su duración en <span class='tooltip-value'>#</span> minutos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [5, 10, 15],
        },
        {
            index: 34,
            name: "Ira Eterna",
            ranks: 3,
			ranksnw: 2,
			desc: "Aumenta la duración de la Ira en Llamas en <span class='tooltip-value'>#</span> segundos. Si te atacan a <span class='tooltip-value'>#</span> segundo(s) de haberlo desplegado, entrarás en el estado de Ira.",
            rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			parent: 18,
        },
        {
            index: 35,
            name: "Captura de Alma",
            ranks: 3,
			desc: "Si utilizas la Ira en Llamas o el Disparo Doble para matar un objetivo a tus 10 niveles propios, o si lo matas mientras que la Resolución del Alma está activa, tendrás una <span class='tooltip-value'>#%</span> oportunidad de crear una Bala de Alma.",
            rankInfo: [40, 70, 100],
        },
        {
            index: 37,
            name: "Resistencia del Alma",
            ranks: 3,
			desc: "Cuando eres atacado mientras la Resolución del Alma está activa, tus Resistencias serán aumentadas en <span class='tooltip-value'>#</span> y tu Defensa será aumentada en <span class='tooltip-value'>#</span> durante 10 segundos. Se acumula 3 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
        },
        {
            index: 39,
            name: "Quemadura Extendida",
            ranks: 2,
			desc: "Aumenta las duraciones de tus efectos de quemadura en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100],
        },
        {
            index: 42,
            name: "Chispa del Alma",
            ranks: 2,
			desc: "Restablece <span class='tooltip-value'>#%</span> el máximo de tu Salud mientras que la Furia Extrema está activa. Estas habilidades tienen una <span class='tooltip-value'>#%</span> posibilidad de no cobrar ninguna Bala de Alma mientras que el Tiempo para el Tirador Experto está activo.",
            rankInfo: [3, 6],
			rankInfo2: [50, 100],
			parent: 20,
        },
        {
            index: 43,
            name: "Fuego Debilitante",
            ranks: 2,
			desc: "El Disparo de Alma and el Rastrillo de Furia causa un efecto quemante en el objetivo que reduce el ataque de la base del objetivo en <span class='tooltip-value'>#%</span> Acumula 10 veces.",
            rankInfo: [1, 2],
        },
        {
            index: 46,
            name: "Disparo de Alta Velocidad",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>781 Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>EI daño de fuego</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 18 metros</span>\n\nAtaca a todos los enemigos a 16.0 metros del objetivo. Inflige 15 de tu Ataque de base, además de 100% daño extra. Mientras que el Tirador Experto está activo, el Disparo de Alta Velocidad cuesta 1 Bala de Alma, su daño extra se incrementa en un 20%, y disipa efectos quemantes en 4366 ocasionados por el Disparo de Alma y el Rastrillo de Furia en el objetivo. Acalla el objetivo hasta por 4 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ]
];