var data = [
	// one
	[
		{
			index: 1,
			name: "Extreme Fury",
			ranks: 5,
			desc: "Each stack of Fury increases the base damage of Force of Fury by <span class='tooltip-value'>#%</span> and the bonus damage by <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 2,
			name: "Crushing Power",
			ranks: 5,
			desc: "Increases the bonus damage of Hard Smash by <span class='tooltip-value'>#%</span> plus an additional <span class='tooltip-value'>#%</span> of your Earth Mastery.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [20, 40, 60, 80, 100],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the bonus damage of Hard Smash by <span class="tooltip-value">12%</span> plus an additional <span class="tooltip-value">120%</span> of your Earth Mastery.</div>'],
		},
		{
			index: 5,
			name: "Recover",
			ranks: 5,
			desc: "Increases the Health recovery rate bonus granted by Recovery Aura by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Defense Surge",
			ranks: 3,
			desc: "Increases the base damage of Counter Strike by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 7,
			name: "Will of Earth",
			ranks: 3,
			desc: "Each stack of Fury increases your chance to resist Slow effects while Mental Focus is active by <span class='tooltip-value'>#%</span>. Each stack of Fury increases your movement speed by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 9,
			name: "Crushing Attack",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1.50 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nDeals 100% of your Attack plus <span class='tooltip-value'>#</span> bonus damage. Reduces the target's Earth Mastery by <span class='tooltip-value'>#</span> for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [111, 168, 227, 287],
			rankInfo3: [1243, 2211, 3162, 4096],
			rankInfo4: [9, 10, 11, 12],
			rankInfo5: [30, 45, 60, 75],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">349</span> Mana</span><span class="right">Cast time: 1.50 seconds</span>\n<br><span class="left">Earth damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Short Range</span>\n\n<br><br>Deals 100% of your Attack plus <span class="tooltip-value">5012</span> bonus damage. Reduces the target\'s Earth Mastery by <span class="tooltip-value">13</span> for <span class="tooltip-value">90</span> seconds.</div>'],
		},
		{
			index: 10,
			name: "Crushing Rage",
			ranks: 3,
			desc: "Each stack of Fury increases the Crit Chance of Crushing Attack by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Each stack of Fury increases the Crit Chance of Crushing Attack by <span class="tooltip-value">4%</span>.</div>'],
			parent: 5,
		},
		{
			index: 11,
			name: "Lineage of Rocks",
			ranks: 4,
			ranksnw: 4,
			desc: "Increases the duration of Rocky Protection by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the duration of Rocky Protection by <span class="tooltip-value">5</span> second(s).</div>'],
		},
		{
			index: 13,
			name: "Code of Fury",
			ranks: 3,
			desc: "Reduces the cooldown of Force of Fury by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Force of Fury by <span class="tooltip-value">8</span> second(s).</div>'],
		},
		{
			index: 15,
			name: "Force of Rocks",
			ranks: 2,
			desc: "Rocky Protection increases your Attack by <span class='tooltip-value'>#%</span> instead of reducing it.",
			rankInfo: [10, 30],
			parent: 7,
		},
		{
			index: 16,
			name: "Earth Essence",
			ranks: 3,
			desc: "Increases your Earth Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 30, 40],
		},
		{
			index: 17,
			name: "Code of Rift",
			ranks: 3,
			ranksnw: 2,
			desc: "Reduces the cooldown of Earth Rift by <span class='tooltip-value'>#</span> second(s). Increases the Accuracy of Earth Rift by <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 18,
			name: "Magic Taunt",
			ranks: 3,
			desc: "Taunt reduces target's Mana by <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of their current Mana.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Taunt reduces target\'s Mana by <span class="tooltip-value">20</span> plus <span class="tooltip-value">20%</span> of their current Mana.</div>'],
		},
		{
			index: 20,
			name: "Pulse Mastery",
			ranks: 4,
			desc: "Increases your Earth Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 30, 40, 50],
		},
		{
			index: 21,
			name: "Sunder",
			ranks: 3,
			desc: "Gives Earth Rift a <span class='tooltip-value'>#%</span> chance to stun the target for 1-3 second(s).",
			rankInfo: [20, 35, 50],
			parent: 11,
		},
		{
			index: 22,
			name: "Gust",
			ranks: 4,
			ranksnw: 2,
			desc: "Increases the movement speed bonus granted by Gale Force by <span class='tooltip-value'>#%</span> and reduces its cooldown by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [5, 10, 15, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the movement speed bonus granted by Gale Force by <span class="tooltip-value">25%</span> and reduces its cooldown by <span class="tooltip-value">25</span> seconds.</div>'],
		},
		{
			index: 23,
			name: "Invigorating Breeze",
			ranks: 1,
			desc: "Gale Force dispels slow and ensnare effects on you.",
			rankInfo: [],
			parent: 15,
		},
		{
			index: 25,
			name: "Brutal Force",
			ranks: 3,
			desc: "Increases the duration that Force of Fury and Earth Rift stun their targets by <span class='tooltip-value'>#</span> second(s). This effect may not occur each time these skills are cast.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 26,
			name: "Earth Source",
			ranks: 3,
			desc: "Reduces the Mana costs of your offensive Earth skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the Mana costs of your offensive Earth skills by <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 27,
			name: "Brutal Plunder",
			ranks: 2,
			desc: "Increases the chance for Fury of Light to disarm the target by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 30,
			name: "Absolute Counter Measure",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 90 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nLasts for <span class='tooltip-value'>#</span> seconds. Deals damage equal to <span class='tooltip-value'>#%</span> of your Defense to enemies that attack you. Has a 50% chance to stun targets for 2 seconds. Each stack of Fury increases the chance to stun by 5%.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [185, 232],
			rankInfo3: [8, 10],
			rankInfo4: [100, 200],
			rankInfo5: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">281</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 90 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Lasts for <span class="tooltip-value">12</span> seconds. Deals damage equal to <span class="tooltip-value">300%</span> of your Defense to enemies that attack you. Has a 50% chance to stun targets for 2 seconds. Each stack of Fury increases the chance to stun by 5%.</div>'],
		},
		{
			index: 32,
			name: "Extension of Life",
			ranks: 3,
			desc: "Increases your max Health by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [200, 400, 600],
		},
		{
			index: 33,
			name: "Earthen Rage",
			ranks: 2,
			desc: "Your offensive Earth skills have a <span class='tooltip-value'>#%</span> chance to generate an extra stack of Fury.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Your offensive Earth skills have a <span class="tooltip-value">18%</span> chance to generate an extra stack of Fury.</div>'],
		},
		{
			index: 35,
			name: "Loyalty",
			ranks: 1,
			desc: "Reduces the Health cost of Loyal Guardian by 50%. Removes your and your target's last bleed effect after casting.",
			rankInfo: [],
		},
		{
			index: 37,
			name: "Force of the Land",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the base damage of Hard Smash, Force of Fury, Crushing Attack, and Earthen Penance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 15, 20],
		},
		{
			index: 38,
			name: "Counter Time",
			ranks: 3,
			desc: "Reduces the cooldown of Absolute Counter Measure by <span class='tooltip-value'>#</span> seconds. Increases your max Health by <span class='tooltip-value'>#%</span> while Absolute Counter Measure is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Absolute Counter Measure by <span class="tooltip-value">20</span> seconds. Increases your max Health by <span class="tooltip-value">40%</span> while Absolute Counter Measure is active.</div>'],
			parent: 20,
		},
		{
			index: 42,
			name: "Weakness Exposure",
			ranks: 1,
			desc: "Earthen Penance reduces the target's Crit Chance by an additional 3%-6%. Increases the duration of the effect by 5 seconds.",
			rankInfo: [],
		},
		{
			index: 43,
			name: "Hardened Will",
			ranks: 2,
			desc: "Each stack of Fury has a <span class='tooltip-value'>#%</span> chance to dispel ensnare and slow effects on you. At Rank 2, dispels the most recent negative effect placed on you.",
			rankInfo: [5, 10],
		},
		{
			index: 45,
			name: "Soul of the Land",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>498 Mana</span><span class='right'>Cast time: 2.50 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 25 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nDeals 150% of your Attack plus 5164 bonus damage. Inflicts the Earthen Soulbreak effect on the target, which increases the damage it takes by 8% for 10 seconds. Each stack of Fury increases the duration of Earthen Soulbreak by 1 second.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
			parent: 24,
		},
		{
			index: 46,
			name: "Break Soul",
			ranks: 4,
			desc: "Increases the bonus damage of Soul of the Land by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			parent: 28,
		},
		{
			index: 50,
			name: "Mount Howl",
			ranks: 3,
			desc: "Reduces the Cooldown of Rockslide by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [5, 10, 15],
		},
		{
			index: 52,
			name: "Thorned Plate",
			ranks: 2,
			desc: "Increases your Attack an amount equal to <span class='tooltip-value'>#%</span> of your Defense.",
			rankInfo: [10, 20],
		},
		{
			index: 53,
			name: "Ancestor's Blessing",
			ranks: 1,
			desc: "Soul of the Land has a reduced Casting Time by 1 second, reduced the Cooldown by 15 second(s), and an additional effect that increases Accuracy by 50.",
			rankInfo: [],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Mental Protection",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases the base damage of Counter Strike by <span class='tooltip-value'>#%</span> while Mental Focus is active. At rank 5, reduces the target's Attack by 10% for 9 seconds.",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 2,
			name: "Rage of the Mind",
			ranks: 5,
			desc: "Increases the duration of Mental Focus by <span class='tooltip-value'>#</span> seconds. Each stack of Fury increases your Attack by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [60, 120, 180, 240, 300],
			rankInfo2: [0.2, 0.4, 0.6, 0.8, 1.0],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the duration of Mental Focus by <span class="tooltip-value">360</span> seconds. Each stack of Fury increases your Attack by <span class="tooltip-value">1.2%</span>.</div>'],
		},
		{
			index: 5,
			name: "Soul of Protection",
			ranks: 3,
			desc: "Increases the duration of Guardian Mode by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4, 6],
			parent: [0],
		},
		{
			index: 6,
			name: "Fury Lock",
			ranks: 3,
			desc: "Force of Fury and Fury of Light have a <span class='tooltip-value'>#%</span> chance to consume no Fury.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 50],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Force of Fury and Fury of Light have a <span class="tooltip-value">60%</span> chance to consume no Fury.</div>'],
		},
		{
			index: 7,
			name: "Ode of Light",
			ranks: 5,
			desc: "While Recovery Aura is active, affected party members recover an additional amount of Mana equal to <span class='tooltip-value'>#%</span> of the original effect when struck.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>While Recovery Aura is active, affected party members recover an additional amount of Mana equal to <span class="tooltip-value">120%</span> of the original effect when struck.</div>'],
		},
		{
			index: 9,
			name: "Blessings of Rocks",
			ranks: 3,
			desc: "Rocky Protection removes all negative status effects affecting party members within 20 meters of you and makes you immune to incoming damage. Affected party members are immune to all negative status effects for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 3, 5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Rocky Protection removes all negative status effects affecting party members within 20 meters of you and makes you immune to incoming damage. Affected party members are immune to all negative status effects for <span class="tooltip-value">7</span> second(s).</div>'],
		},
		{
			index: 10,
			name: "Nature Aura",
			ranks: 4,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Aura blessing</span><span class='right'>Range: None</span>\n\nIncreases the Earth and Wind Resistances of all party members within 16 meters of you by <span class='tooltip-value'>#</span>. Consumes 0.5% of your max Mana every 5 seconds. Only one Aura can be active at a time.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [112, 160, 210, 261],
			rankInfo3: [45, 70, 95, 120],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">313</span> Mana</span><span class="right">Cast time: Instant</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Aura blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases the Earth and Wind Resistances of all party members within 16 meters of you by <span class="tooltip-value">145</span>. Consumes 0.5% of your max Mana every 5 seconds. Only one Aura can be active at a time.</div>'],
		},
		{
			index: 12,
			name: "Precision of Light",
			ranks: 3,
			desc: "Increases your Accuracy by <span class='tooltip-value'>#</span>. Nature Aura, Iceflame Aura, and Chaos Aura grant the Precision of Light effect, which increases the Accuracy of affected party members by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [11, 16, 21],
			rankInfo2: [11, 16, 21],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases your Accuracy by <span class="tooltip-value">26</span>. Nature Aura, Iceflame Aura, and Chaos Aura grant the Precision of Light effect, which increases the Accuracy of affected party members by <span class="tooltip-value">26</span>.</div>'],
		},
		{
			index: 13,
			name: "Mass Protection",
			ranks: 3,
			desc: "Increases the duration of Protection of Strength by <span class='tooltip-value'>#</span> seconds, reduces its Mana cost by <span class='tooltip-value'>#%</span>, and increases the Defense it grants by 15/rank.",
			rankInfo: [300, 600, 900],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 14,
			name: "Iceflame Aura",
			ranks: 4,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Aura blessing</span><span class='right'>Range: None</span>\n\nIncreases the Water and Fire Resistances of all party members within 16 meters of you by <span class='tooltip-value'>#</span>. Consumes 0.5% of your max Mana every 5 seconds. Only one Aura can be active at a time.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv35</span>\n\n', '<span class="req">Requires character to be Lv50</span>\n\n', '<span class="req">Requires character to be Lv65</span>\n\n', '<span class="req">Requires character to be Lv80</span>\n\n'],
			rankInfo2: [112, 160, 210, 261],
			rankInfo3: [45, 70, 95, 120],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">313</span> Mana</span><span class="right">Cast time: Instant</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Aura blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases the Water and Fire Resistances of all party members within 16 meters of you by <span class="tooltip-value">145</span>. Consumes 0.5% of your max Mana every 5 seconds. Only one Aura can be active at a time.</div>'],
		},
		{
			index: 16,
			name: "Light Barrier",
			ranks: 3,
			desc: "Increases your Light Resistance by <span class='tooltip-value'>#</span> and your Defense by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 30, 40],
			rankInfo2: [10, 15, 20],
		},
		{
			index: 18,
			name: "Chaos Aura",
			ranks: 4,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Aura blessing</span><span class='right'>Range: None</span>\n\nIncreases the Light and Dark Resistances of all party members within 16 meters of you by <span class='tooltip-value'>#</span>. Consumes 0.5% of your max Mana every 5 seconds. Only one Aura can be active at a time.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv40</span>\n\n', '<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n', '<span class="req">Requires character to be Lv80</span>\n\n'],
			rankInfo2: [112, 160, 210, 261],
			rankInfo3: [45, 70, 95, 120],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">313</span> Mana</span><span class="right">Cast time: Instant</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Aura blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases the Light and Dark Resistances of all party members within 16 meters of you by <span class="tooltip-value">145</span>. Consumes 0.5% of your max Mana every 5 seconds. Only one Aura can be active at a time.</div>'],
		},
		{
			index: 20,
			name: "Light Mastery",
			ranks: 4,
			desc: "Increases your Light Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 30, 40, 50],
		},
		{
			index: 21,
			name: "Flurries",
			ranks: 3,
			desc: "Increases the movement speed bonus granted by Gale Force by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 23,
			name: "Aura Focus",
			ranks: 4,
			ranksnw: 2,
			desc: "Your Aura skills increase your Evasion by <span class='tooltip-value'>#</span> and your Crit Dodge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12, 16],
			rankInfo2: [1.5, 2.0, 2.5, 3.0],
		},
		{
			index: 25,
			name: "Anger of Light",
			ranks: 4,
			ranksnw: 2,
			desc: "Fury of Light reduces the target's Crit Dodge by <span class='tooltip-value'>#%</span> and the effectiveness of healing skills cast on targets below 50% Health by <span class='tooltip-value'>#%</span> for 15 seconds.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [10, 20, 30, 40],
		},
		{
			index: 26,
			name: "Fury of Light Knowledge",
			ranks: 2,
			desc: "Reduces the cooldown of Fury of Light by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Fury of Light by <span class="tooltip-value">4.5</span> seconds.</div>'],
			parent: 15,
		},
		{
			index: 28,
			name: "Aura Efficiency",
			ranks: 4,
			desc: "Reduces the Mana costs of your Aura skills by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 29,
			name: "Eye of the Storm",
			ranks: 2,
			desc: "Increases the range of Gale Force by <span class='tooltip-value'>#</span> meters. Dispels slow effects from affected party members. (Lv2 also dispels ensnare, Lv3 also dispels disarm).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the range of Gale Force by <span class="tooltip-value">15</span> meters. Dispels slow effects from affected party members. (Lv2 also dispels ensnare, Lv3 also dispels disarm).</div>'],
		},
		{
			index: 30,
			name: "Fist of Heaven",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1.50 seconds</span>\n<span class='left'>Light damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nDeals 100% of your Attack, plus <span class='tooltip-value'>#</span> bonus damage. Reduces the target's Resistances by <span class='tooltip-value'>#</span> for <span class='tooltip-value'>#</span> seconds. Stacks 3 times. Each stack of Fury increases the bonus damage by 2% and the duration by 0.5 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [218, 280],
			rankInfo3: [1802, 2746],
			rankInfo4: [30, 45],
			rankInfo5: [9, 10],
			rankInfo6: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">344</span> Mana</span><span class="right">Cast time: 1.50 seconds</span>\n<br><span class="left">Light damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Short Range</span>\n\n<br><br>Deals 100% of your Attack, plus <span class="tooltip-value">3626</span> bonus damage. Reduces the target\'s Resistances by <span class="tooltip-value">60</span> for <span class="tooltip-value">11</span> seconds. Stacks 3 times. Each stack of Fury increases the bonus damage by 2% and the duration by 0.5 seconds.</div>'],
		},
		{
			index: 33,
			name: "Enrage",
			ranks: 2,
			desc: "Your offensive Light skills have a <span class='tooltip-value'>#%</span> chance to generate a stack of Fury.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [8, 16],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Your offensive Light skills have a <span class="tooltip-value">24%</span> chance to generate a stack of Fury.</div>'],
		},
		{
			index: 35,
			name: "Aura Wisdom",
			ranks: 3,
			desc: "Increases your max Mana by <span class='tooltip-value'>#%</span> while an Aura is active.",
			rankInfo: [20, 30, 40],
			parent: 14,
		},
		{
			index: 37,
			name: "Soul of Penance",
			ranks: 2,
			desc: "Reduces the cooldown of Earthen Penance by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10],
		},
		{
			index: 38,
			name: "Light of Destruction",
			ranks: 2,
			desc: "Increases the bonus damage of Fury of Light and Fist of Heaven by <span class='tooltip-value'>#%</span>. Fist of Heaven reduces the Resistances and the effectiveness of healing skills cast on the target by <span class='tooltip-value'>#%</span>. Stacks 3 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [5, 10],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the bonus damage of Fury of Light and Fist of Heaven by <span class="tooltip-value">30%</span>. Fist of Heaven reduces the Resistances and the effectiveness of healing skills cast on the target by <span class="tooltip-value">15%</span>. Stacks 3 times.</div>'],
			parent: 19,
		},
		{
			index: 41,
			name: "Might of Light",
			ranks: 2,
			desc: "The cooldowns of your offensive Light skills are reduced by <span class='tooltip-value'>#</span> second(s) and their Crit Chance is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [3, 6],
		},
		{
			index: 43,
			name: "Guard Courage",
			ranks: 2,
			desc: "Increases your Crit Dodge by <span class='tooltip-value'>#%</span> while an Aura skill is active.",
			rankInfo: [1, 2],
		},
		{
			index: 46,
			name: "Defensive Assist",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>343 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Multi-target blessing</span><span class='right'>Range: None</span>\n\nReduces incoming damage by 30% for all party members within 10 meters for 15 seconds. This skill has no effect on you.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Rescue",
			ranks: 4,
			desc: "While Defensive Assist is active, allies affected by the skill recover Health equal to <span class='tooltip-value'>#%</span> of your Defense every 2 seconds.",
			rankInfo: [30, 60, 90, 120],
			parent: 26,
		},
		{
			index: 49,
			name: "Wrath of Light",
			ranks: 3,
			desc: "Increases Light Skills Attack Bonus by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 51,
			name: "Piety",
			ranks: 2,
			desc: "While Asylum Aura is active, increases Health recovered from Healing Effects on affected targets by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 54,
			name: "Sacred Body",
			ranks: 1,
			desc: "You will also benefit from Defensive Assist. Duration increased by 5 seconds. Cooldown reduced by 30 seconds.",
			rankInfo: [],
			parent: 26,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Art of Guardians",
			ranks: 5,
			desc: "Reduces the cooldown of Counter Strike by <span class='tooltip-value'>#</span> second(s). Guardian Mode reduces incoming damage by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Reduces the cooldown of Counter Strike by <span class="tooltip-value">6</span> second(s). Guardian Mode reduces incoming damage by an additional <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 2,
			name: "Crushing Punch",
			ranks: 5,
			desc: "Hard Smash gains a <span class='tooltip-value'>#%</span> chance to reduce the target's base Attack by <span class='tooltip-value'>#%</span> for 20 seconds. Stacks 3 times.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 5,
			name: "Code of Taunt",
			ranks: 3,
			desc: "Reduces the cooldown of Taunt by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 6, 8],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Taunt by <span class="tooltip-value">10</span> seconds.</div>'],
		},
		{
			index: 6,
			name: "Abominable Will",
			ranks: 3,
			desc: "Mental Focus increases your Accuracy by <span class='tooltip-value'>#</span>, and the amount of threat generated by your skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Mental Focus increases your Accuracy by <span class="tooltip-value">24</span>, and the amount of threat generated by your skills by <span class="tooltip-value">80%</span>.</div>'],
		},
		{
			index: 7,
			name: "Source of Recovery",
			ranks: 5,
			desc: "Recovery Aura increases the effectiveness of healing skills cast on affected party members by <span class='tooltip-value'>#%</span>. Increases the amount of Health they recover by <span class='tooltip-value'>#%</span> while being attacked.",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [20, 40, 60, 80, 100],
		},
	   {
			index: 9,
			name: "Mass Taunt",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Earth</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: None</span>\n\nTaunts up to <span class='tooltip-value'>#</span> targets within 20 meters for <span class='tooltip-value'>#</span> seconds. Removes stealth and prevents them from entering stealth for 8 seconds. Mass Taunt's success rate is the same as Taunt's.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n'],
			rankInfo2: [624, 893, 1170],
			rankInfo3: [16, 17, 18],
			rankInfo4: [6, 7, 8],
			rankInfo5: ['', '', '<div class="runelvl">\n<br>Level: 4/3 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">1454</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Earth</span><span class="right">Cooldown: 60 seconds</span>\n<br><span class="left">Multi-target curse</span><span class="right">Range: None</span>\n\n<br><br>Taunts up to <span class="tooltip-value">19</span> targets within 20 meters for <span class="tooltip-value">9</span> seconds. Removes stealth and prevents them from entering stealth for 8 seconds. Mass Taunt\'s success rate is the same as Taunt\'s.</div>'],
		},
		{
			index: 10,
			name: "Chaos Taunt",
			ranks: 3,
			ranksnw: 1,
			desc: "Taunt reduces the target's Evasion by <span class='tooltip-value'>#</span> for 8 seconds. Mass Taunt reduces the target's Accuracy by <span class='tooltip-value'>#</span> for 8 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: [30, 60, 90],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Taunt reduces the target\'s Evasion by <span class="tooltip-value">60</span> for 8 seconds. Mass Taunt reduces the target\'s Accuracy by <span class="tooltip-value">120</span> for 8 seconds.</div>'],
			parent: 5,
		},
	   {
			index: 11,
			name: "Spirit of Rocks",
			ranks: 4,
			desc: "Reduces the cooldown of Rocky Protection by <span class='tooltip-value'>#</span> second(s). Rocky Protection increases the effectiveness of healing effects cast on you by <span class='tooltip-value'>#%</span> and restores <span class='tooltip-value'>#%</span> of your max Health every 2 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: [2, 4, 6, 8],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Rocky Protection by <span class="tooltip-value">75</span> second(s). Rocky Protection increases the effectiveness of healing effects cast on you by <span class="tooltip-value">50%</span> and restores <span class="tooltip-value">10%</span> of your max Health every 2 seconds.</div>'],
		},
		{
			index: 13,
			name: "Faith of Protection",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases your max Health by 4% plus <span class='tooltip-value'>#</span> when you are struck while Protection of Strength is active. Stacks 10 times and lasts for 15 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 200, 300],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases your max Health by 4% plus <span class="tooltip-value">400</span> when you are struck while Protection of Strength is active. Stacks 10 times and lasts for 15 seconds.</div>'],
		},
		{
			index: 15,
			name: "Firepower Coverage",
			ranks: 2,
			desc: "Increases the amount of threat generated by bonus damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 16,
			name: "Stone Skin",
			ranks: 4,
			desc: "Increases your Physical Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 30, 40, 50],
		},
		{
			index: 17,
			name: "Light of Belief",
			ranks: 3,
			desc: "Increases the duration of the Faith of Protection effect by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10, 15],
			parent: 8,
		},
		{
			index: 19,
			name: "Landslide",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the number of enemies affected by Earth Rift by <span class='tooltip-value'>#</span> and increases its range by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [2, 4, 6],
			rankInfo2: [2, 4, 6],
		},
	   {
			index: 20,
			name: "Protection Fortify",
			ranks: 4,
			desc: "Increases your Defense by <span class='tooltip-value'>#</span>.",
			rankInfo: [16, 24, 32, 40],
		},
		{
			index: 21,
			name: "Whirlwind's Blessing",
			ranks: 3,
			desc: "Increases the duration of Gale Force by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4, 6],
		},
	   {
			index: 23,
			name: "Schism",
			ranks: 4,
			desc: "Earth Rift reduces targets' movement speed by an additional <span class='tooltip-value'>#%</span>. Rank 2 increases the duration of the slow effect.",
			rankInfo: [3.5, 7, 10.5, 14],
			parent: 12,
		},
		{
			index: 25,
			name: "Guardian Boulder",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases your base Defense by <span class='tooltip-value'>#%</span> and reduces incoming damage by an additional <span class='tooltip-value'>#%</span> while Guardian Mode is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases your base Defense by <span class="tooltip-value">8%</span> and reduces incoming damage by an additional <span class="tooltip-value">8%</span> while Guardian Mode is active.</div>'],
		},
		{
			index: 26,
			name: "Infamous Scourge",
			ranks: 3,
			desc: "Reduces the cooldown of Mass Taunt by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [12, 24, 36],
			parent: 6,
		},
		{
			index: 27,
			name: "Wisdom",
			ranks: 2,
			desc: "Reduces the Mana costs of Mental Focus, Taunt, Mass Taunt, and Protection of Strength by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 30,
			name: "Upheaval",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1.50 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 8 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 8 meters</span>\n\nDeals 100% of your Attack plus <span class='tooltip-value'>#</span> bonus damage to up to 15 targets in front of you within 8 meters. Reduces the target's Evasion by <span class='tooltip-value'>#</span>. Lasts 10 seconds. Each stack of Fury increases the bonus damage by 2% and the duration of the Evasion reduction effect by 0.5 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [292, 373],
			rankInfo3: [2319, 3526],
			rankInfo4: [10, 12],
			rankInfo5: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">458</span> Mana</span><span class="right">Cast time: 1.50 seconds</span>\n<br><span class="left">Earth damage</span><span class="right">Cooldown: 8 seconds</span>\n<br><span class="left">Multi-target attack</span><span class="right">Range: 8 meters</span>\n\n<br><br>Deals 100% of your Attack plus <span class="tooltip-value">4651</span> bonus damage to up to 15 targets in front of you within 8 meters. Reduces the target\'s Evasion by <span class="tooltip-value">14</span>. Lasts 10 seconds. Each stack of Fury increases the bonus damage by 2% and the duration of the Evasion reduction effect by 0.5 seconds.</div>'],
		},
		{
			index: 31,
			name: "Magma Burst",
			ranks: 2,
			desc: "Increases the base damage of Upheaval by <span class='tooltip-value'>#%</span>. Increases the amount of threat generated by Upheaval and Earth Rift by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: [50, 100],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the base damage of Upheaval by <span class="tooltip-value">45%</span>. Increases the amount of threat generated by Upheaval and Earth Rift by <span class="tooltip-value">150%</span>.</div>'],
			parent: 19,
		},
		{
			index: 34,
			name: "Heart of the Sentinel",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the duration of Loyal Guardian by <span class='tooltip-value'>#</span> seconds and the range by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Loyal Guardian by <span class="tooltip-value">9</span> seconds and the range by <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 35,
			name: "Tenacity of Rock",
			ranks: 3,
			desc: "Increases your Crit Dodge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 37,
			name: "Protection Mastery",
			ranks: 3,
			desc: "Reduces the Attack penalty caused by Guardian Mode by <span class='tooltip-value'>#%</span>.",
			rankInfo: [30, 60, 100],
			parent: 16,
		},
		{
			index: 39,
			name: "Energy of the Land",
			ranks: 2,
			desc: "Each stack of Fury increases the base damage of Earth Rift and Earthen Penance by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Each stack of Fury increases the base damage of Earth Rift and Earthen Penance by <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 42,
			name: "Faith",
			ranks: 2,
			desc: "Reduces the cooldown of Loyal Guardian by <span class='tooltip-value'>#</span> seconds. If you are struck within 12 seconds of casting it, <span class='tooltip-value'>#%</span> of the Health used to create the shield is restored. This effect can occur up to 5 times.",
			rankInfo: [5, 10],
			rankInfo2: [15, 30],
			parent: 21,
		},
		{
			index: 43,
			name: "Entrench",
			ranks: 3,
			desc: "Increases the bonus damage of Hard Smash, Counter Strike, Fury of Light, and Earthen Penance by <span class='tooltip-value'>#%</span> of your Defense. Increases the amount of damage Retaliation Aura reflects back at attackers by <span class='tooltip-value'>#%</span> of your Defense.",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 47,
			name: "Soul of Stone",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>150 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nDispels negative effects and absorbs 60% of incoming damage for 15 seconds. Reduces your movement speed by 75%. This skill can be used while silenced or stunned.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 48,
			name: "Harden",
			ranks: 4,
			desc: "Crusta Skin increases your Defense by <span class='tooltip-value'>#</span>.",
			rankInfo: [300, 600, 900, 1200],
			parent: 27,
		},
		{
			index: 50,
			name: "Furious Taunt",
			ranks: 2,
			desc: "Using Taunt and Mass Taunt grants a <span class='tooltip-value'>#%</span> chance to generate 2 stacks of Fury.",
			rankInfo: [50, 100],
		},
		{
			index: 52,
			name: "Unyielding",
			ranks: 3,
			desc: "When your Health is lower than 30%, you recover <span class='tooltip-value'>#%</span> Health and Mana in one second, and you ignore the next source of direct damage within 5 seconds. This effect has an internal Cooldown of 10 minutes.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 55,
			name: "Unbending",
			ranks: 1,
			desc: "Crusta Skin no longer slows your Movement Speed. Each stack of Faith of Protection increases your Tenacity by 45 (PvE only).",
			rankInfo: [],
			parent: 27,
		},
	]
];