var data = [
	// one
	[
		{
			index: 1,
			name: "Пламя огненного шара",
			ranks: 5,
			ranksnw: 3,
			desc: "Увеличивает урон от эффекта горения, вызванного навыком «Огненный шар», на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100, 125],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивает урон от эффекта горения, вызванного навыком «Огненный шар», на <span class="tooltip-value">150%</span>.</div>'],
		},
		{
			index: 3,
			name: "Защитная сила",
			ranks: 5,
			desc: "При получении урона маг, находящийся под защитой навыка «Щит магии» получает эффект «Защитная сила», который увеличивает урон любого атакующего навыка на <span class='tooltip-value'>#%</span> от максимального количества ОМ мага. Длительность эффекта 5 сек. Эффект суммируется до 5 раз.",
			rankInfo: [0.4, 0.8, 1.2, 1.6, 2],
		},
		{
			index: 5,
			name: "Энергия огненного шара",
			ranks: 5,
			ranksnw: 1,
			desc: "Повышает вероятность воспламенения от «Огненного шара» на <span class='tooltip-value'>#%</span>. Уменьшает расход ОМ на «Огненный шар» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [7, 14, 21, 28, 35],
			parent: [0],
		},
		{
			index: 6,
			name: "Усиленное колдовство",
			ranks: 2,
			desc: "Увеличивает длительность навыка «Колдовство» на <span class='tooltip-value'>#</span> мин. «Колдовство» уменьшает расход ОМ персонажа навыками Огня на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: [5, 10],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает длительность навыка «Колдовство» на <span class="tooltip-value">45</span> мин. «Колдовство» уменьшает расход ОМ персонажа навыками Огня на <span class="tooltip-value">15%</span>.</div>'],
		},
		{
			index: 8,
			name: "Магический огонь",
			ranks: 3,
			desc: "Прирост мастерства огня от навыка «Власть стихий» дополнительно повышается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Магическое пламя",
			ranks: 2,
			desc: "Уменьшает время перезарядки «Огненного шара» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшает время перезарядки «Огненного шара» на <span class="tooltip-value">3</span> сек.</div>'],
			parent: 2,
		},
		{
			index: 10,
			name: "Величие огня",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Огня</span><span class='right'>Время перезарядки: 3 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nНаносит огненный урон врагам в радиусе 8 м от цели. Наносит 100% базового урона и увеличивает силу атаки на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [250, 368, 487, 608],
			rankInfo3: [782, 1420, 2047, 2663],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">730</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Урон от Огня</span><span class="right">Время перезарядки: 3 сек.</span>\n<br><span class="left">Массовая атака</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Наносит огненный урон врагам в радиусе 8 м от цели. Наносит 100% базового урона и увеличивает силу атаки на <span class="tooltip-value">3268</span> ед.</div>'],
		},
		{
			index: 11,
			name: "Детонация",
			ranks: 4,
			desc: "Навыки огня накладывают на парализованную цель эффект детонации, наносящий урон в размере <span class='tooltip-value'>#%</span> от общего количества ОМ заклинателя.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4, 5],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Навыки огня накладывают на парализованную цель эффект детонации, наносящий урон в размере <span class="tooltip-value">6%</span> от общего количества ОМ заклинателя.</div>'],
		},
		{
			index: 14,
			name: "Безмерное величие огня",
			ranks: 4,
			desc: "Атака навыком «Величие огня» снижает сопротивление Воде, Огню и Воздуху на <span class='tooltip-value'>#</span> ед. Суммируется до 3 раз. Длительность 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Атака навыком «Величие огня» снижает сопротивление Воде, Огню и Воздуху на <span class="tooltip-value">25</span> ед. Суммируется до 3 раз. Длительность 15 сек.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Быстрая трансформация",
			ranks: 3,
			ranksnw: 3,
			desc: "Уменьшает время перезарядки навыка «Трансформация» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время перезарядки навыка «Трансформация» на <span class="tooltip-value">20</span> сек.</div>'],
		},
		{
			index: 16,
			name: "Огненный барьер",
			ranks: 3,
			desc: "Увеличивает сопротивление Огню мага на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Дьявольское пламя",
			ranks: 3,
			ranksnw: 1,
			desc: "Продлевает горение от навыка от навыка «Ярость огня» на 5 сек. Каждую секунду цель получает <span class='tooltip-value'>#</span> огненного урона.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 18,
			name: "Усиленный порыв ветра",
			ranks: 2,
			desc: "Продлевает время действия навыка «Порыв ветра» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Продлевает время действия навыка «Порыв ветра» на <span class="tooltip-value">6</span> сек.</div>'],
		},
		{
			index: 19,
			name: "Чары",
			ranks: 1,
			desc: "Навык «Трансформация» действует на монстров, на которых ранее действовать не мог.",
			rankInfo: [],
			parent: 9,
		},
		{
			index: 21,
			name: "Призыв огня",
			ranks: 2,
			desc: "Время перезарядки навыка «Ярость огня» уменьшается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2],
			parent: 11,
		},
		{
			index: 24,
			name: "Средоточие огня",
			ranks: 6,
			desc: "Увеличивает урон от навыков Огня на <span class='tooltip-value'>#%</span> от максимума ОМ.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
		},
		{
			index: 26,
			name: "Сущность огня",
			ranks: 4,
			desc: "Повышает урон от эффектов горения на <span class='tooltip-value'>#%</span> и их длительность на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 27,
			name: "Медитация огня",
			ranks: 3,
			ranksnw: 1,
			desc: "«Медитация» увеличивает мастерство и сопротивление огня на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
		},
		{
			index: 29,
			name: "Отражение",
			ranks: 3,
			desc: "«Огненный щит» на короткое время ослепляет атакующего. Меткость врага уменьшается на <span class='tooltip-value'>#</span> ед. Длительность 5 сек., можно совместить 10 раз.",
			rankInfo: [3, 6, 9],
			parent: [19],
		},
		{
			index: 30,
			name: "Огненный щит",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nФизическое сопротивление и сопротивление Огню усиливаются на <span class='tooltip-value'>#</span> ед., вероятность критической атаки повышается на <span class='tooltip-value'>#</span>. Длительность 5 мин. При атаке под действием навыка «Огненный щит» мастерство Огня мага увеличивается на <span class='tooltip-value'>#</span> ед. Длительность 10 сек., суммируется до 8 раз. Невозможно использовать одновременно с «Ледяным щитом».\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [3, 5],
			rankInfo5: [5, 7],
			rankInfo6: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">510</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 20 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Физическое сопротивление и сопротивление Огню усиливаются на <span class="tooltip-value">60</span> ед., вероятность критической атаки повышается на <span class="tooltip-value">7</span>. Длительность 5 мин. При атаке под действием навыка «Огненный щит» мастерство Огня мага увеличивается на <span class="tooltip-value">9</span> ед. Длительность 10 сек., суммируется до 8 раз. Невозможно использовать одновременно с «Ледяным щитом».</div>'],
		},
		{
			index: 31,
			name: "Быстрое сгорание",
			ranks: 2,
			desc: "Во время действия навыка «Медитация», урон от всех воспламеняющих эффектов увеличивается на <span class='tooltip-value'>#%</span>. Длительность горения уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [100, 200],
			rankInfo2: [20, 40],
			parent: [17],
		},
		{
			index: 33,
			name: "Стремительное пламя",
			ranks: 3,
			desc: "Уменьшает время перезарядки навыков «Огненный шар», «Величие огня» и «Ярость огня» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время перезарядки навыков «Огненный шар», «Величие огня» и «Ярость огня» на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 34,
			name: "Гневное сердце",
			ranks: 2,
			desc: "Увеличивает урон от навыков «Величие огня» и «Ярость огня» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает урон от навыков «Величие огня» и «Ярость огня» на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 36,
			name: "Запал",
			ranks: 3,
			desc: "Во время использования навыка «Огненный шар», с вероятностью <span class='tooltip-value'>#%</span> обнуляет время перезарядки навыков «Величие огня» и «Ярость огня».",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Мастер огня",
			ranks: 3,
			desc: "Если количество ОМ превышает 50%, атакующие огненные навыки наносят на цель эффект «Расплавленные доспехи», снижающий защину на <span class='tooltip-value'>#</span> ед. на 10 сек. Эффект может суммироваться до 10 раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Если количество ОМ превышает 50%, атакующие огненные навыки наносят на цель эффект «Расплавленные доспехи», снижающий защину на <span class="tooltip-value">60</span> ед. на 10 сек. Эффект может суммироваться до 10 раз.</div>'],
		},
		{
			index: 39,
			name: "Развеянные чары",
			ranks: 3,
			desc: "Навык «Развеянные чары» снижает у врага сопротивление Огню на <span class='tooltip-value'>#</span> ед. Длится 20 сек. Сжигает количество маны, равное <span class='tooltip-value'>#%</span> от базового урона мага.",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 42,
			name: "Дыхание огня",
			ranks: 3,
			desc: "Увеличивает базовый урон от навыков «Огненный шар», «Яростное пламя» и «Величие пламени» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 43,
			name: "Сгусток энергии",
			ranks: 2,
			desc: "Навыки и заклинания, наносящие урон огнем, с вероятностью в <span class='tooltip-value'>#%</span>, могут увеличить критический урон на 2%. Эффект складывается до 10 раз. Длительность: 10 сек.",
			rankInfo: [50, 100],
		},
		{
			index: 46,
			name: "Искры",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>1346</span> ОМ</span><span class='right'>Чтение: 5 сек.</span>\n<span class='left'>Урон от огня</span><span class='right'>Время перезарядки: 25 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nНаносит 200% базового урона и дополнительно 5229 ед. урона целям в радиусе 10 м. Оглушает атакованных противников на 1-5 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Падающая звезда",
			ranks: 4,
			desc: "Повышает силу базовой атаки навыка «Искры» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [25, 50, 75, 100],
			parent: 28,
		},
		{
			index: 49,
			name: "Зов звезд",
			ranks: 3,
			desc: "Навыки «Величие огня» и «Ярость огня» с вероятностью <span class='tooltip-value'>#%</span> сбрасывают время восстановления навыка «Искры». Увеличивает базовую атаку навыков «Величие огня» и «Ярость огня» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 10],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 51,
			name: "Аннигиляция",
			ranks: 2,
			desc: "Навыки стихии огня, наносящие урон по площади («Ярость огня», «Величие огня» и «Искры») при нанесении цели критического урона снижают ее крит. уклонение на <span class='tooltip-value'>#%</span>; продолжительность - 30 сек.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Повелитель стихий",
			ranks: 1,
			desc: "Уменьшает время сотворения заклинания «Искры» на 2 сек., увеличивает минимальную продолжительность головокружения с 1 до 2 сек.",
			rankInfo: [],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Ошеломляющий гром",
			ranks: 4,
			ranksnw: 1,
			desc: "Вероятность возникновения паралича от навыка «Громовой удар» увеличивается на <span class='tooltip-value'>#%</span>. Расход ОМ на навык уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [5, 10, 15, 20],
		},
		{
			index: 2,
			name: "Магический источник",
			ranks: 3,
			desc: "Усиливает эффект увеличения макс. маны навыка «Колдовство» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 3, 4.5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Усиливает эффект увеличения макс. маны навыка «Колдовство» на <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 3,
			name: "Гнев молний",
			ranks: 3,
			desc: "Увеличивает базовый урон от навыка «Громовой удар» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 5,
			name: "Раскаты грома",
			ranks: 4,
			ranksnw: 2,
			desc: "Радиус действия навыка «Громовой удар» увеличивается на <span class='tooltip-value'>#%</span>. Максимальное количество атакуемых врагов увеличивается на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 60, 90, 120],
			rankInfo2: [2, 4, 6, 8],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Радиус действия навыка «Громовой удар» увеличивается на <span class="tooltip-value">150%</span>. Максимальное количество атакуемых врагов увеличивается на <span class="tooltip-value">10</span> ед.</div>'],
			parent: [0],
		},
		{
			index: 7,
			name: "Сделка",
			ranks: 2,
			ranksnw: 1,
			desc: "Продлевает время действия навыка «Щит магии» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Продлевает время действия навыка «Щит магии» на <span class="tooltip-value">30</span> сек.</div>'],
		},
		{
			index: 8,
			name: "Магический ветер",
			ranks: 3,
			desc: "Прирост мастерства Воздуха от навыка «Власть стихий» дополнительно повышается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Разрушительность",
			ranks: 4,
			desc: "Увеличивает вероятность нанести крит. урон навыком «Громовой удар» на <span class='tooltip-value'>#%</span>. При активации навыка «Неистовая гроза» эффект удваивается.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Увеличивает вероятность нанести крит. урон навыком «Громовой удар» на <span class="tooltip-value">7.5%</span>. При активации навыка «Неистовая гроза» эффект удваивается.</div>'],
			parent: 3,
		},
		{
			index: 10,
			name: "Пронзающая молния",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Воздуха</span><span class='right'>Время перезарядки: <span class='tooltip-value'>#</span> сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nАтакует врагов на прямой линии, находящихся на расстоянии 21 м. Наносит 100% базового урона + <span class='tooltip-value'>#</span> ед. дополнительного урона. Атакует максимум <span class='tooltip-value'>#</span> врагов. С вероятностью 25% заклинание врага прерывается.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [259, 382, 506, 631],
			rankInfo3: [8, 7, 6, 5],
			rankInfo4: [1339, 2362, 3366, 4351],
			rankInfo5: [16, 17, 18, 19],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">757</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Урон от Воздуха</span><span class="right">Время перезарядки: <span class="tooltip-value">4</span> сек.</span>\n<br><span class="left">Массовая атака</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Атакует врагов на прямой линии, находящихся на расстоянии 21 м. Наносит 100% базового урона + <span class="tooltip-value">5319</span> ед. дополнительного урона. Атакует максимум <span class="tooltip-value">20</span> врагов. С вероятностью 25% заклинание врага прерывается.</div>'],
		},
		{
			index: 11,
			name: "Энергия защиты",
			ranks: 3,
			desc: "Количество маны, расходуемое навыком «Щит магии» на поглащение 1 ед. урона, снижается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 50],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Количество маны, расходуемое навыком «Щит магии» на поглащение 1 ед. урона, снижается на <span class="tooltip-value">60%</span>.</div>'],
			parent: 4,
		},
		{
			index: 14,
			name: "Усиленная пронзающая молния",
			ranks: 4,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> навык «Пронзающая молния» может наложить на цель оцепенение. Отбрасывает цель-монстра.",
			rankInfo: [25, 50, 75, 100],
			parent: 7,
		},
		{
			index: 15,
			name: "Напряжение",
			ranks: 2,
			ranksnw: 1,
			desc: "После каждой атаки Воздухом, с вероятностью <span class='tooltip-value'>#%</span> накапливается один этап напряжения. 8 этапов запускают навык «Неистовая гроза». Вероятность критической атаки навыками Воздуха возрастает, а время их перезарядки снижается. Длительность 10 сек.",
			rankInfo: [50, 100],
		},
		{
			index: 16,
			name: "Повелитель ветра",
			ranks: 4,
			ranksnw: 3,
			desc: "Увеличивает мастерство Воздуха на <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Усиленная трансформация",
			ranks: 3,
			desc: "Продлевает время действия навыка «Трансформация» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 18,
			name: "Стремительный порыв",
			ranks: 2,
			desc: "Усиливает эффект ускорения навыка «Порыв ветра» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Усиливает эффект ускорения навыка «Порыв ветра» на <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 20,
			name: "Концентрация грома",
			ranks: 6,
			desc: "Повышает урон от всех атакующих навыков Воздуха на <span class='tooltip-value'>#%</span> от максимального количества ОМ мага.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
			parent: 11,
		},
		{
			index: 21,
			name: "Сильное оцепенение",
			ranks: 2,
			desc: "Оцепенение от навыка «Громовой удар» снижает шанс уклонения врага на <span class='tooltip-value'>#%</span> и сопротивление Воздуху на <span class='tooltip-value'>#</span> ед. Длительность паралича увеличивается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100],
			rankInfo2: [10, 20],
			rankInfo3: [3, 6],
			rankInfo4: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Оцепенение от навыка «Громовой удар» снижает шанс уклонения врага на <span class="tooltip-value">150%</span> и сопротивление Воздуху на <span class="tooltip-value">30</span> ед. Длительность паралича увеличивается на <span class="tooltip-value">9</span> сек.</div>'],
		},
		{
			index: 23,
			name: "Неиссякаемая энергия",
			ranks: 4,
			desc: "Продлевает действие навыка «Неистовая гроза» на <span class='tooltip-value'>#</span> сек. Каждая единица эффекта «Напряжение» дополнительно увеличивает скорость передвижения мага на 5%. Во время действия «Неистовой грозы» скорость передвижения мага увеличивается на 50%.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Продлевает действие навыка «Неистовая гроза» на <span class="tooltip-value">5</span> сек. Каждая единица эффекта «Напряжение» дополнительно увеличивает скорость передвижения мага на 5%. Во время действия «Неистовой грозы» скорость передвижения мага увеличивается на 50%.</div>'],
			parent: 10,
		},
		{
			index: 26,
			name: "Медитация воздуха",
			ranks: 3,
			desc: "«Медитация» увеличивает мастерство и сопротивления Воздуха на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Медитация» увеличивает мастерство и сопротивления Воздуха на <span class="tooltip-value">60</span> ед.</div>'],
		},
		{
			index: 28,
			name: "Грозовой перевал",
			ranks: 3,
			desc: "Повышает сопротивление Воздуху на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 29,
			name: "Сделка с тьмой",
			ranks: 3,
			ranksnw: 3,
			desc: "Навык «Сила магии» создаёт ауру воздействия, в радиусе действия которой каждые 4 секунды цели с вероятностью <span class='tooltip-value'>#%</span> парализуются.",
			rankInfo: [40, 70, 100],
			parent: 20,
		},
		{
			index: 30,
			name: "Сила магии",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>50% ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Воздух</span><span class='right'>Время перезарядки: 180 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – нет</span>\n\nРасходует 50% маны, враги в радиусе <span class='tooltip-value'>#</span> м. поражаются магическим взрывом. Атакует до <span class='tooltip-value'>#</span> врагов. Мана мгновенно уменьшается на 30% от текущего значения (эффект применяется 1 раз в 20 сек.). В следующие 20 сек, любой, враг, атакующий мага, потеряет количество ОМ, равное 1.0% максимального количества ОМ мага.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [12, 15],
			rankInfo3: [20, 25],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left">50% ОМ</span><span class="right">Чтение: 3 сек.</span>\n<br><span class="left">Воздух</span><span class="right">Время перезарядки: 180 сек.</span>\n<br><span class="left">Массовое проклятие</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Расходует 50% маны, враги в радиусе <span class="tooltip-value">18</span> м. поражаются магическим взрывом. Атакует до <span class="tooltip-value">30</span> врагов. Мана мгновенно уменьшается на 30% от текущего значения (эффект применяется 1 раз в 20 сек.). В следующие 20 сек, любой, враг, атакующий мага, потеряет количество ОМ, равное 1.0% максимального количества ОМ мага.</div>'],
		},
		{
			index: 33,
			name: "Магические оковы",
			ranks: 4,
			desc: "Количество ОМ, сжигаемое навыком «Сила магии» увеличивается на <span class='tooltip-value'>#%</span>. Когда количество ОМ врага падает ниже 20%, на него накладывается молчание на <span class='tooltip-value'>#</span> сек. (можно использовать раз в 20 сек.). Эффект может появиться до 20 раз.",
			rankInfo: [50, 100, 150, 200],
			rankInfo2: [1, 2, 3, 4],
			parent: 19,
		},
		{
			index: 35,
			name: "Хрупкий лед",
			ranks: 2,
			desc: "Атакующие навыки Воздуха накладывают на замороженную цель эффект «Хрупкий лед». В следующие 15 сек. урон врага от всех полученных ударов увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 37,
			name: "Запрет грома",
			ranks: 3,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> атака воздухом прерывает заклинание врага.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Благословение громовержца",
			ranks: 2,
			desc: "Сокращает время перезарядки навыков «Громовой удар» и «Пронзающая молния» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2],
		},
		{
			index: 39,
			name: "Бушующий ветер",
			ranks: 3,
			desc: "Навык «Развеянные чары» с вероятностью <span class='tooltip-value'>#%</span> может снять с цели благотворный эффект.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 42,
			name: "Полное оцепенение",
			ranks: 2,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> добавляет навыку «Ярость молнии» эффект оцепенения. Меткость врага уменьшается на 60 очков, уклонение – на 40 очков. Длительность 15 сек.",
			rankInfo: [50, 100],
		},
		{
			index: 43,
			name: "Неистовая гроза",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>5% ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Урон от Воздуха </span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nВо время неистовой грозы электрические разряды появляются один за другим.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
		},
		{
			index: 46,
			name: "Чистилище",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>1064 ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Урон от Воздуха </span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – нет</span>\n\nАтакует цели в радиусе 16 м. шесть раз. Каждый удар наносит 50% базового урона и дополнительно 818 ед. урона. С вероятностью в 40% парализует цель.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Электрошок",
			ranks: 4,
			desc: "Каждый этап атаки навыка «Чистилище» с вероятностью <span class='tooltip-value'>#%</span> накладывает на цель эффект «Электрошок» (эффект суммируется до 5 раз). Если цель в этом состоянии получает удар в результате применения навыка «Чистилище», она парализуется на 1-5 сек. в зависимости от количества действующих эффектов «Электрошока». Урон от навыка «Чистилище» зависит от количества действующих на цель эффектов «Электрошок». Каждый действующий эффект «Электрошок» увеличивает базовый урон навыка «Чистилище» на 1%; время действия эффекта «Электрошок» - 20 сек.",
			rankInfo: [10, 20, 30, 40],
			parent: 28,
		},
		{
			index: 49,
			name: "Очищение",
			ranks: 3,
			desc: "Уменьшает время восстановления навыка «Рассеянные чары» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 51,
			name: "Спазмы",
			ranks: 2,
			desc: "Навыки, способные парализовать цель, также снижают скорость чтения заклинаний парализованной цели на <span class='tooltip-value'>#%</span>, снижают скорость передвижения на <span class='tooltip-value'>#%</span>; продолжительность - 15 сек.",
			rankInfo: [5, 10],
			rankInfo2: [10, 20],
		},
		{
			index: 54,
			name: "Гнев Бога грома",
			ranks: 1,
			desc: "Увеличивает бонус к базовой атаке каждой атаки навыка «Чистилище» на 20%, увеличивает вероятность наложения эффекта «Электрошок» на 50% (даже если навык «Электрошок» не изучен).",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Меткость воды",
			ranks: 5,
			ranksnw: 3,
			desc: "Повышает меткость навыка «Ледяная стрела» на <span class='tooltip-value'>#</span>. Базовый урон увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [5, 10, 15, 20, 25],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Повышает меткость навыка «Ледяная стрела» на <span class="tooltip-value">18</span>. Базовый урон увеличивается на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 2,
			name: "Лед",
			ranks: 5,
			ranksnw: 1,
			desc: "Дополнительный эффект оледенения навыка «Ледяная стрела» понижает сопротивление Огню и Воде на <span class='tooltip-value'>#</span> ед. Длительность 15 сек., можно повторить 10 раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Дополнительный эффект оледенения навыка «Ледяная стрела» понижает сопротивление Огню и Воде на <span class="tooltip-value">12</span> ед. Длительность 15 сек., можно повторить 10 раз.</div>'],
		},
		{
			index: 5,
			name: "Магический лед",
			ranks: 2,
			ranksnw: 1,
			desc: "Уменьшает время перезарядки навыка «Ледяная стрела» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшает время перезарядки навыка «Ледяная стрела» на <span class="tooltip-value">3</span> сек.</div>'],
			parent: [0],
		},
		{
			index: 7,
			name: "Измерения пространства",
			ranks: 4,
			desc: "Время действия навыка «Ледяной щит» увеличивается на <span class='tooltip-value'>#</span> сек. Восстанавливает <span class='tooltip-value'>#%</span> ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Время действия навыка «Ледяной щит» увеличивается на <span class="tooltip-value">7.5</span> сек. Восстанавливает <span class="tooltip-value">5%</span> ОЗ.</div>'],
		},
		{
			index: 8,
			name: "Магическая вода",
			ranks: 3,
			desc: "Прирост мастерства Воды от навыка «Власть стихий» дополнительно повышается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Ледяной кристалл",
			ranks: 5,
			desc: "С помощью навыка «Ледяная стрела» можно полностью заморозить врага на 6 сек. Вероятность возникновения заморозки <span class='tooltip-value'>#%</span>. Враг подвергается действию паралича и молчания, защита усиливается на 15%.",
			rankInfo: [3, 6, 9, 12, 15],
			parent: 2,
		},
		{
			index: 10,
			name: "Ледяные шипы",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Воды</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nНаносит 100% базового урона + <span class='tooltip-value'>#</span> дополнительного урона. Во время атаки критическим ударом на врага насылается тройной эффект оледенения, как от навыка «Ледяная стрела». Если в это время на врага действует эффект заморозки, ему дополнительно наносится <span class='tooltip-value'>#</span> урона.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [168, 240, 313, 386],
			rankInfo3: [991, 1650, 2297, 2932],
			rankInfo4: [200, 300, 400, 500],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">460</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Урон от Воды</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Наносит 100% базового урона + <span class="tooltip-value">3555</span> дополнительного урона. Во время атаки критическим ударом на врага насылается тройной эффект оледенения, как от навыка «Ледяная стрела». Если в это время на врага действует эффект заморозки, ему дополнительно наносится <span class="tooltip-value">600</span> урона.</div>'],
			parent: 1,
		},
		{
			index: 11,
			name: "Холодная кожа",
			ranks: 3,
			desc: "Во время действия навыка «Щит магии» на <span class='tooltip-value'>#</span> сек. персонаж получает щит, поглощающий 100% урона. Количество поглощаемого урона не может превышать <span class='tooltip-value'>#%</span> от максимума ОМ персонажа.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 13,
			name: "Подавление",
			ranks: 2,
			desc: "Может замедлить скорость врага, находящегося под действием навыка «Трансформация», с вероятностью <span class='tooltip-value'>#%</span>. Восстановление здоровья замедляется на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 60],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Может замедлить скорость врага, находящегося под действием навыка «Трансформация», с вероятностью <span class="tooltip-value">90%</span>. Восстановление здоровья замедляется на <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 14,
			name: "Совершенные ледяные шипы",
			ranks: 5,
			desc: "Дополнительный урон, наносимый замороженным врагам навыком «Ледяные шипы» увеличивается на <span class='tooltip-value'>#%</span>. Вероятность критической атаки увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: [2, 4, 6, 8, 10],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Дополнительный урон, наносимый замороженным врагам навыком «Ледяные шипы» увеличивается на <span class="tooltip-value">120%</span>. Вероятность критической атаки увеличивается на <span class="tooltip-value">12%</span>.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Сильный порыв ветра",
			ranks: 2,
			desc: "Навык «Порыв ветра» дает эффект иммунитета к <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['замедлению', 'замедлению и параличу'],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Навык «Порыв ветра» дает эффект иммунитета к <span class="tooltip-value">замедлению, параличу и кровотечению</span>.</div>'],
		},
		{
			index: 18,
			name: "Глубокая заморозка",
			ranks: 5,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> к навыкам «Ледяная стрела» и «Ледяные шипы» добавляется эффект глубокой заморозки. Длительность 20 сек, исчезает после первого запуска. Во время действия следующая атака навыком «Ледяные шипы» наносит критический урон. Атака навыком «Ледяная стрела» замораживает врага.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>С вероятностью <span class="tooltip-value">12%</span> к навыкам «Ледяная стрела» и «Ледяные шипы» добавляется эффект глубокой заморозки. Длительность 20 сек, исчезает после первого запуска. Во время действия следующая атака навыком «Ледяные шипы» наносит критический урон. Атака навыком «Ледяная стрела» замораживает врага.</div>'],
		},
		{
			index: 20,
			name: "Ледяные жилы",
			ranks: 6,
			desc: "Увеличивает урон от всех навыков Воды на <span class='tooltip-value'>#%</span> от максимума ОМ мага.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
		},
		{
			index: 21,
			name: "Царство вечного льда",
			ranks: 2,
			ranksnw: 1,
			desc: "Время заморозки, вызванной навыком «Царство льда», увеличивается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Время заморозки, вызванной навыком «Царство льда», увеличивается на <span class="tooltip-value">3</span> сек.</div>'],
		},
		{
			index: 23,
			name: "Ледяные латы",
			ranks: 3,
			desc: "Увеличивает сопротивление Воде мага на <span class='tooltip-value'>#</span> ед. Защита усиливается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 25,
			name: "Разрушение границ",
			ranks: 4,
			desc: "Навык «Царство льда» отнимает у врага <span class='tooltip-value'>#%</span> от его макс ОМ. Урон от навыка увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [15, 30, 45, 60],
			parent: 13,
		},
		{
			index: 26,
			name: "Ледяной кинжал",
			ranks: 3,
			desc: "Увеличивает дополнительный урон от навыков «Ледяная стрела» и «Ледяные шипы» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 30,
			name: "Ледяной щит",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nСопротивление Воде усиливается на <span class='tooltip-value'>#</span> ед. Защита усиливается на <span class='tooltip-value'>#</span> ед. Общий урон уменьшается на <span class='tooltip-value'>#%</span>, длительность 5 мин. Атакующие враги замедляются на 10% на 5 сек. Эффект складывается 5 раз. Невозможно использовать одновременно с «Огненным щитом».\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [50, 80],
			rankInfo5: [3, 5],
			rankInfo6: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">510</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 20 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Сопротивление Воде усиливается на <span class="tooltip-value">60</span> ед. Защита усиливается на <span class="tooltip-value">110</span> ед. Общий урон уменьшается на <span class="tooltip-value">7%</span>, длительность 5 мин. Атакующие враги замедляются на 10% на 5 сек. Эффект складывается 5 раз. Невозможно использовать одновременно с «Огненным щитом».</div>'],
		},
		{
			index: 31,
			name: "Снежный щит",
			ranks: 3,
			desc: "Навык «Ледяной щит» дополнительно увеличивает силу основной защиты на <span class='tooltip-value'>#%</span>. Действие замедления продлевается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 17,
		},
		{
			index: 33,
			name: "Медитация воды",
			ranks: 2,
			desc: "Во время действии медитации уменьшает перезарядки навыков «Ледяная стрела», «Ледяные шипы» и «Царство льда» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [30, 60],
		},
		{
			index: 34,
			name: "Длительная заморозка",
			ranks: 2,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> сохраняет эффект «Глубокая заморозка» на ещё один удар по врагу.",
			rankInfo: [15, 30],
		},
		{
			index: 36,
			name: "Повелитель льда",
			ranks: 3,
			desc: "Увеличивает мастерство Воды на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 38,
			name: "Метель",
			ranks: 3,
			ranksnw: 3,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> навык «Ледяное безумие» насылает заморозку на 3 сек. Избавляет от действия эффекта горения.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 39,
			name: "Дух метели",
			ranks: 2,
			desc: "Увеличивает базовый урон от навыка «Ледяное безумие» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			parent: 22,
		},
		{
			index: 42,
			name: "Ледяные оковы",
			ranks: 2,
			desc: "Навыки «Ледяная стрела» и «Ледяные шипы» замораживают горящую или парализованную цель. Сила атаки цели уменьшается на <span class='tooltip-value'>#%</span>, а защита – на <span class='tooltip-value'>#%</span>, передвижение замедляется на 25%, длительность 10 сек.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 43,
			name: "Быстрое оледенение",
			ranks: 2,
			ranksnw: 1,
			desc: "Уменьшает время восстановления навыков «Царство льда» и «Царство холода» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10],
		},
		{
			index: 47,
			name: "Царство холода",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>775 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Воды</span><span class='right'>Время перезарядки: 45 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nВ радиусе 10 м. атакует до 16 целей. Наносит 100% базового урона и дополнительно 1852 ед. урона. парализует атакованные цели и увеличивает их защиту на 5%. Эффект пропадает после того, как цель будет атакована дважды.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			parent: 25,
		},
		{
			index: 48,
			name: "Суровый холод",
			ranks: 4,
			ranksnw: 1,
			desc: "«Царство холода» снижает сопротивление цели Льду на <span class='tooltip-value'>#</span>, продолжительность - 12 сек.",
			rankInfo: [20, 40, 60, 80],
			parent: 26,
		},
		{
			index: 49,
			name: "Обморожение",
			ranks: 2,
			desc: "Увеличивает шанс крит. удара от навыка «Холодный туман» на <span class='tooltip-value'>#%</span>. Если этим навыком наносится критический удар, то цель замораживается. Ежесекундно цель теряет <span class='tooltip-value'>#</span> ОЗ; продолжительность - 5 сек.",
			rankInfo: [3, 6],
			rankInfo2: [546, 1092],
		},
		{
			index: 51,
			name: "Хрупкость",
			ranks: 3,
			desc: "Снижает крит. уклонение цели, парализованной в результате применения навыков «Царство холода» и «Царство льда» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [7, 14, 21],
		},
		{
			index: 56,
			name: "Неудержимый мороз",
			ranks: 1,
			desc: "«Царство холода» увеличивает базовую атаку на 50%. Персонаж в течение 12 секунд при применении навыка «Ледяное безумие» получает иммунитет к урону, наносимому ответным ударом, и кровотечению.",
			rankInfo: [],
			parent: 27,
		},
	]
];