var data = [
	// one
	[
		{
			index: 1,
			name: "Demônio do Sangue",
			ranks: 5,
			desc: "Aumenta a chance do Sigilo do Vampiro, Fortalecimento, Semente da Vida, Contrato Sombrio e Ritual de Sangue ativarem a forma de Vampiro em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Aumenta a chance do Sigilo do Vampiro, Fortalecimento, Semente da Vida, Contrato Sombrio e Ritual de Sangue ativarem a forma de Vampiro em <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 2,
			name: "Marca de Sangue",
			ranks: 5,
			desc: "Aumenta a quantidade de Saúde restaurada pelo Sigilo do Vampiro em <span class='tooltip-value'>#</span> mais <span class='tooltip-value'>#%</span> da sua Saúde Máxima.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [0.6, 1.2, 1.8, 2.4, 3.0],
		},
		{
			index: 5,
			name: "Ataque Encantado Estendido",
			ranks: 2,
			ranksnw: 1,
			desc: "Aumenta o alcance do Ataque Encantado em <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 6,
			name: "Sigilo do Vampiro Avançado",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduz o intervalo do Sigilo do Vampiro em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>Reduz o intervalo do Sigilo do Vampiro em <span class="tooltip-value">2.5</span> segundo(s).</div>'],
		},
		{
			index: 8,
			name: "Sangue Maligno",
			ranks: 4,
			desc: "Aumenta a duração do Sangue Maligno em <span class='tooltip-value'>#</span> segundo(s). Reduz a Saúde máxima do alvo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>Aumenta a duração do Sangue Maligno em <span class="tooltip-value">25</span> segundo(s). Reduz a Saúde máxima do alvo em <span class="tooltip-value">5%</span>.</div>'],
		},
		{
			index: 9,
			name: "Ataque Maligno Sangrento",
			ranks: 4,
			desc: "O Ataque Encantado drena <span class='tooltip-value'>#</span> de Saúde do alvo e causa danos adicionais de <span class='tooltip-value'>#%</span> a alvos afetados pela Maldição de Sangue.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100, 150, 200],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>O Ataque Encantado drena <span class="tooltip-value">250</span> de Saúde do alvo e causa danos adicionais de <span class="tooltip-value">50%</span> a alvos afetados pela Maldição de Sangue.</div>'],
			parent: 2,
		},
		{
			index: 11,
			name: "Semente da Vida",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 10 segundo(s)</span>\n<span class='left'>Bênção para alvo único</span><span class='right'>Alcance: 16 metro(s)</span>\n\nApós 5 segundo(s), a Semente da Vida cura o alvo restaurando <span class='tooltip-value'>#</span> de Saúde. Tem uma Chance Crítica de 2%, o que faz com que esta habilidade cure o dobro da quantidade. O efeito de cura se ativa instantaneamente se a Saúde do alvo fica abaixo de 50%. Tem 10% de chance de ativar a forma de Vampiro.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n'],
			rankInfo2: [211, 313, 416],
			rankInfo3: ['1896-2093', '2787-3077', '3632-4011'],
			rankInfo4: ['', '', '<div class="runelvl">\n<br>Nível: 4/3 (precisa runa)\n\n<br><br><span class="left"><span class="tooltip-value">522</span> Mana</span><span class="right">Tempo de ativação: 2 segundo(s)</span>\n<br><span class="left">Defesa</span><span class="right">Intervalo: 10 segundo(s)</span>\n<br><span class="left">Bênção para alvo único</span><span class="right">Alcance: 16 metro(s)</span>\n\n<br><br>Após 5 segundo(s), a Semente da Vida cura o alvo restaurando <span class="tooltip-value">4432-4894</span> de Saúde. Tem uma Chance Crítica de 2%, o que faz com que esta habilidade cure o dobro da quantidade. O efeito de cura se ativa instantaneamente se a Saúde do alvo fica abaixo de 50%. Tem 10% de chance de ativar a forma de Vampiro.</div>'],
		},
		{
			index: 12,
			name: "Conhecimento do Sangue",
			ranks: 3,
			desc: "Reduz o custo de Mana das suas habilidades de cura em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [8, 16, 24],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Reduz o custo de Mana das suas habilidades de cura em <span class="tooltip-value">32%</span>.</div>'],
		},
		{
			index: 13,
			name: "Contrato Sombrio Avançado",
			ranks: 5,
			desc: "Reduz o intervalo do Contrato Sombrio em <span class='tooltip-value'>#</span> segundo(s). Aumenta a quantidade de Saúde restaurada pelo Contrato Sombrio em <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 14,
			name: "Energia da Insígnia",
			ranks: 4,
			desc: "Aumenta o dano base do Sigilo do Vampiro em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>Aumenta o dano base do Sigilo do Vampiro em <span class="tooltip-value">50%</span>.</div>'],
			parent: 3,
		},
		{
			index: 18,
			name: "Sombra de Asa de Morcego",
			ranks: 2,
			desc: "As Asas da Tempestade concedem imunidade aos efeitos de enredamento por <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>As Asas da Tempestade concedem imunidade aos efeitos de enredamento por <span class="tooltip-value">8</span> segundo(s).</div>'],
		},
		{
			index: 19,
			name: "Força da Vida",
			ranks: 4,
			desc: "Aumenta a quantidade de Saúde restaurada pela Semente da Vida em <span class='tooltip-value'>#</span> e sua Chance Crítica em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [2, 4, 6, 8],
			parent: 6,
		},
		{
			index: 20,
			name: "Banquete de Sangue",
			ranks: 3,
			desc: "Banquete aumenta a sua Defesa por um adicional de <span class='tooltip-value'>#%</span> e sua taxa de Recuperação de Saúde por um adicional de <span class='tooltip-value'>#%</span> por segundo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [80, 160, 240],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Banquete aumenta a sua Defesa por um adicional de <span class="tooltip-value">320%</span> e sua taxa de Recuperação de Saúde por um adicional de <span class="tooltip-value">8%</span> por segundo.</div>'],
		},
		{
			index: 21,
			name: "Elo de Sangue",
			ranks: 4,
			ranksnw: 1,
			desc: "Fortalecimento custa um adicional de <span class='tooltip-value'>#%</span> da sua Saúde Máxima e aumenta o Ataque do alvo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: [8, 16, 24, 32],
		},
		{
			index: 22,
			name: "Laço de Sangue",
			ranks: 3,
			ranksnw: 2,
			desc: "Enquanto se está na forma de Vampiro, a efetividade de suas habilidades de cura aumenta por <span class='tooltip-value'>#%</span>, e matar inimigos restaura <span class='tooltip-value'>#%</span> de sua Saúde máxima.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 24,
			name: "Fuga Noturna",
			ranks: 2,
			desc: "Reduz a quantidade de ameaça gerada pelas habilidades de cura em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>Reduz a quantidade de ameaça gerada pelas habilidades de cura em <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 25,
			name: "Vida Concedida",
			ranks: 2,
			ranksnw: 1,
			desc: "Fortalecimento aumenta a Saúde Máxima do alvo em <span class='tooltip-value'>#%</span> durante 20 segundos.",
			rankInfo: [10, 20],
			parent: 13,
		},
		{
			index: 26,
			name: "Pacto de Sangue",
			ranks: 3,
			desc: "Aumenta a Chance Crítica do Contrato Sombrio e Semente da Vida em <span class='tooltip-value'>#%</span> enquanto você está na forma de Vampiro.",
			rankInfo: [15, 30, 45],
			parent: 14,
		},
		{
			index: 27,
			name: "Morte Maligna Sangrenta",
			ranks: 2,
			ranksnw: 2,
			desc: "Aumenta a quantidade de Saúde drenada pela Fúria da Morte em <span class='tooltip-value'>#%</span>.",
			rankInfo: [100, 200],
		},
		{
			index: 30,
			name: "Maldição de Sangue",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Escuridão</span><span class='right'>Intervalo: 30 segundo(s)</span>\n<span class='left'>Maldição contra múltiplos alvos</span><span class='right'>Alcance: 16 metro(s)</span>\n\nDentro de 6 metro(s), até <span class='tooltip-value'>#</span> inimigos são afetados pela Maldição de Sangue durante 15 segundos. Alvos afetados pela Maldição de Sangue recebem o efeito Sangue Congelado por 20 segundos quando atacados. Sangue Congelado reduz a Saúde Máxima do alvo em 4%. Acumula 5 vezes. Tem 10% de chance de ativar a forma de Vampiro.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [385, 464],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Nível: 3/2 (precisa runa)\n\n<br><br><span class="left"><span class="tooltip-value">549</span> Mana</span><span class="right">Tempo de ativação: 1 segundo(s)</span>\n<br><span class="left">Escuridão</span><span class="right">Intervalo: 30 segundo(s)</span>\n<br><span class="left">Maldição contra múltiplos alvos</span><span class="right">Alcance: 16 metro(s)</span>\n\n<br><br>Dentro de 6 metro(s), até <span class="tooltip-value">25</span> inimigos são afetados pela Maldição de Sangue durante 15 segundos. Alvos afetados pela Maldição de Sangue recebem o efeito Sangue Congelado por 20 segundos quando atacados. Sangue Congelado reduz a Saúde Máxima do alvo em 4%. Acumula 5 vezes. Tem 10% de chance de ativar a forma de Vampiro.</div>'],
		},
		{
			index: 31,
			name: "Fúria da Morte Melhorada",
			ranks: 3,
			desc: "Reduz o intervalo da Fúria da Morte em <span class='tooltip-value'>#</span> segundo(s). Alvos afetados pela Maldição de Sangue recebem um efeito de sangramento que causa <span class='tooltip-value'>#</span> de dano a cada 2 segundos.",
			rankInfo: [1, 2, 3],
			rankInfo2: [80, 160, 240],
			parent: 18,
		},
		{
			index: 33,
			name: "Sangue Fresco",
			ranks: 2,
			desc: "Aumenta a quantidade de Saúde restaurada Pelo Fortalecimento em <span class='tooltip-value'>#%</span> durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [4, 8],
			rankInfo2: [10, 20],
			parent: 16,
		},
		{
			index: 34,
			name: "Estagnar",
			ranks: 2,
			desc: "Aumenta o alcance da Maldição de Sangue em <span class='tooltip-value'>#</span> metro(s). Alvos atingidos pelo Sangue Congelado também são afetados com o efeito da Saúde Congelada, o que reduz a efetividade de habilidades de cura lançadas sobre o alvo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>Aumenta o alcance da Maldição de Sangue em <span class="tooltip-value">3</span> metro(s). Alvos atingidos pelo Sangue Congelado também são afetados com o efeito da Saúde Congelada, o que reduz a efetividade de habilidades de cura lançadas sobre o alvo em <span class="tooltip-value">45%</span>.</div>'],
			parent: 19,
		},
		{
			index: 37,
			name: "Trabalho de Sangue Estendido",
			ranks: 2,
			desc: "Usar habilidades de Sangue aumenta a duração da forma de Vampiro em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [4, 8],
		},
		{
			index: 38,
			name: "Cura Acelerada",
			ranks: 2,
			desc: "Reduz os intervalos da Semente da Vida e Fortalecimento em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [2, 4],
		},
		{
			index: 39,
			name: "Tempo do Ritual",
			ranks: 2,
			ranksnw: 1,
			desc: "Aumenta a duração do Ritual de Sangue em 2 segundo(s). Aumenta a quantidade de Saúde restaurada pelo Contrato Sombrio e Semente da Vida em uma quantidade equivalente a <span class='tooltip-value'>#%</span> da sua Saúde.",
			rankInfo: [1, 2],
		},
		{
			index: 40,
			name: "Sangue do Surto",
			ranks: 2,
			desc: "Aumenta a sua Saúde Máxima em <span class='tooltip-value'>#%</span>. Aumenta a sua Saúde Máxima e o seu Mana Máximo em um adicional de <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4],
			rankInfo2: [300, 600],
		},
		{
			index: 42,
			name: "Extensão do Laço de Sangue",
			ranks: 2,
			ranksnw: 1,
			desc: "Aumenta o alcance das suas habilidades de cura em <span class='tooltip-value'>#</span> metro(s) e a quantidade de Saúde restaurada em <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
			rankInfo2: [15, 30],
		},
		{
			index: 43,
			name: "Febre do Sangue",
			ranks: 2,
			ranksnw: 1,
			desc: "Enquanto o Ritual de Sangue está ativo, o Contrato Sombrio e Fortalecimento aumentam a velocidade de movimento e todas as Maestrias do alvo em <span class='tooltip-value'>#%</span> e <span class='tooltip-value'>#</span> respectivamente durante 5 segundos e o Sigilo do Vampiro reduz a velocidade de movimento e todas as Maestrias do alvo em <span class='tooltip-value'>#%</span> e <span class='tooltip-value'>#</span> respectivamente durante 5 segundos.",
			rankInfo: [25, 30],
			rankInfo2: [80, 160],
			rankInfo3: [25, 30],
			rankInfo4: [80, 160],
			parent: 26,
		},
		{
			index: 46,
			name: "Espaço de Murcho",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>327 Mana</span><span class='right'>Tempo de ativação: Instantâneo</span>\n<span class='left'>Escuridão</span><span class='right'>Intervalo: 300 segundo(s)</span>\n<span class='left'>Maldição contra múltiplos alvos</span><span class='right'>Alcance: Nenhum</span>\n\nVocê não pode se mover ou usar habilidades de ataque durante 25 segundo(s). Você pode usar habilidades de Cura e de Maldição. Aumenta a sua Saúde Máxima em 50% e aumenta o alcance dos seus feitiços de Cura em 50%. Lança o Contrato Sombrio e a Semente da Vida sobre o alvo e aplica os mesmos efeitos em você. Reduz todas as Resistência de todos os inimigos dentro de 20 metros em 200. Cancele o efeito desta habilidade usando-a novamente.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Demônio da Escuridão",
			ranks: 5,
			desc: "Aumenta a chance da Ondulação Sombria, Semente da Escuridão, Contrato Sombrio, Fúria da Morte, Explosão de Mana e Cicatriz Sombria ativar a forma de Vampiro em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Aumenta a chance da Ondulação Sombria, Semente da Escuridão, Contrato Sombrio, Fúria da Morte, Explosão de Mana e Cicatriz Sombria ativar a forma de Vampiro em <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 3,
			name: "Força das Sombras",
			ranks: 5,
			desc: "Ondulação Sombria e Cicatriz Sombria custam <span class='tooltip-value'>#%</span> de sua Saúde máxima. Esse total ainda é adicionado ao seu dano. Aumenta a Chance Crítica da Ondulação Sombria em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Ondulação Sombria e Cicatriz Sombria custam <span class="tooltip-value">3%</span> de sua Saúde máxima. Esse total ainda é adicionado ao seu dano. Aumenta a Chance Crítica da Ondulação Sombria em  <span class="tooltip-value">6%</span>.</div>'],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 5,
			name: "Surto de Feitiço",
			ranks: 2,
			desc: "Reduz o intervalo do Ataque Encantado em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [0.3, 0.5],
		},
		{
			index: 7,
			name: "Ondulação Sombria Avançada",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduz o intervalo da Ondulação Sombria em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>Reduz o intervalo da Ondulação Sombria em <span class="tooltip-value">2.5</span> segundo(s).</div>'],
		},
		{
			index: 8,
			name: "Expansão da Escuridão",
			ranks: 4,
			desc: "Aumenta a duração da Maldição Escura em <span class='tooltip-value'>#</span> segundo(s). Ele reduz a Precisão do alvo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [6, 12, 18, 24],
		},
		{
			index: 9,
			name: "Ataque Sombrio",
			ranks: 4,
			desc: "O primeiro golpe do Ataque Encantado tem uma chance de <span class='tooltip-value'>#%</span> de atordoar o alvo durante 1 segundo. O segundo golpe tem uma chance de <span class='tooltip-value'>#%</span> de atordoar o alvo durante 1 segundo. Ataque Encantado causa um dano adicional de <span class='tooltip-value'>#%</span> em alvos afetados pela Maldição Escura.",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [12, 25, 37, 50],
			rankInfo3: [10, 20, 30, 40],
		},
		{
			index: 10,
			name: "Semente da Escuridão",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Escuridão</span><span class='right'>Intervalo: 30 segundo(s)</span>\n<span class='left'>Maldição contra alvo único</span><span class='right'>Alcance: 12 metro(s)</span>\n\nCusta 1% da sua Saúde Máxima. Após 5 segundo(s), reduz a velocidade de movimento do alvo em 50.0% por <span class='tooltip-value'>#</span> segundo(s). Maldição Escura pode desencadear este efeito mais cedo. Tem 10% de chance de ativar a forma de Vampiro.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n'],
			rankInfo2: [235, 337, 441],
			rankInfo3: [8, 10, 12],
			rankInfo4: ['', '', '<div class="runelvl">\n<br>Nível: 4/3 (precisa runa)\n\n<br><br><span class="left"><span class="tooltip-value">548</span> Mana</span><span class="right">Tempo de ativação: 1 segundo(s)</span>\n<br><span class="left">Escuridão</span><span class="right">Intervalo: 30 segundo(s)</span>\n<br><span class="left">Maldição contra alvo único</span><span class="right">Alcance: 12 metro(s)</span>\n\n<br><br>Custa 1% da sua Saúde Máxima. Após 5 segundo(s), reduz a velocidade de movimento do alvo em 50.0% por <span class="tooltip-value">14</span> segundo(s). Maldição Escura pode desencadear este efeito mais cedo. Tem 10% de chance de ativar a forma de Vampiro.</div>'],
		},
		{
			index: 12,
			name: "Hemofilia",
			ranks: 3,
			desc: "Aumenta a duração do Banquete em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Aumenta a duração do Banquete em <span class="tooltip-value">4</span> segundo(s).</div>'],
		},
		{
			index: 14,
			name: "Força da Escuridão",
			ranks: 3,
			ranksnw: 2,
			desc: "A Semente da Escuridão reduz a velocidade de movimento do alvo em <span class='tooltip-value'>#%</span>. Alvos afetados pela Semente da Escuridão serão silenciados durante <span class='tooltip-value'>#</span> segundo(s) após serem atingidos 4 vezes.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 6,
		},
		{
			index: 15,
			name: "Invasão da Escuridão",
			ranks: 5,
			desc: "Ondulação Sombria reduz a Resistência da Escuridão do alvo em um adicional <span class='tooltip-value'>#</span> durante 15 segundos. Aumenta a chance da Ondulação Sombria infligir a Maldição Escura ao alvo em <span class='tooltip-value'>#%</span> quando lançada na forma de Vampiro.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60, 75],
			rankInfo2: [4, 8, 12, 16, 20],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Ondulação Sombria reduz a Resistência da Escuridão do alvo em um adicional <span class="tooltip-value">90</span> durante 15 segundos. Aumenta a chance da Ondulação Sombria infligir a Maldição Escura ao alvo em <span class="tooltip-value">24%</span> quando lançada na forma de Vampiro.</div>'],
			parent: 3,
		},
		{
			index: 17,
			name: "Estímulo",
			ranks: 4,
			desc: "Aumenta a duração do Fortalecimento em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 18,
			name: "Broto",
			ranks: 2,
			desc: "Reduz o intervalo da Semente da Escuridão em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>Reduz o intervalo da Semente da Escuridão em <span class="tooltip-value">15</span> segundo(s).</div>'],
			parent: 8,
		},
		{
			index: 20,
			name: "Olhos da Escuridão",
			ranks: 3,
			desc: "Aumenta a Precisão de todas as suas habilidades da Escuridão em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Aumenta a Precisão de todas as suas habilidades da Escuridão em <span class="tooltip-value">40</span>.</div>'],
		},
		{
			index: 21,
			name: "Ilusão da Fúria",
			ranks: 4,
			ranksnw: 1,
			desc: "Aumenta a Chance Crítica da Fúria da Morte em <span class='tooltip-value'>#%</span> e reduz seu intervalo em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 23,
			name: "Consequências do Contrato",
			ranks: 4,
			desc: "O Contrato Sombrio aumenta a Evasão do alvo em <span class='tooltip-value'>#</span> por 3 segundos, se o alvo for um integrante do grupo.",
			rankInfo: [20, 40, 60, 80],
		},
		{
			index: 26,
			name: "Títulos Sombrios Avançados",
			ranks: 2,
			desc: "Aumenta a duração do efeito controlador dos Títulos Sombrios em jogadores durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [2, 4],
		},
		{
			index: 28,
			name: "Poder do Vampiro",
			ranks: 3,
			desc: "A forma de Vampiro aumenta o seu Ataque em um adicional de <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 29,
			name: "Fúria da Morte Escurecida",
			ranks: 2,
			desc: "Fúria da Morte reduz o Ataque dos alvos afetados pela Maldição Escura em um adicional de <span class='tooltip-value'>#%</span> e reduz suas velocidades de movimento em um adicional de <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>Fúria da Morte reduz o Ataque dos alvos afetados pela Maldição Escura em um adicional de <span class="tooltip-value">30%</span> e reduz suas velocidades de movimento em um adicional de <span class="tooltip-value">30%</span>.</div>'],
			parent: 13,
		},
		{
			index: 30,
			name: "Explosão de Mana",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de escuridão</span><span class='right'>Intervalo: 8 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: Nenhum</span>\n\nAfeta múltiplos inimigos em um alcance de 10. Custa 1% da sua Saúde. Inflige 100% do seu Ataque básico mais <span class='tooltip-value'>#</span> de bônus de dano. Esta habilidade tem o mesmo efeito em maldições que a Fúria da Morte. A forma de Vampiro aprimora ainda os efeitos desta habilidade. Tem 10% de chance de ativar a forma de Vampiro.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [432, 520],
			rankInfo3: [1047, 1532],
			rankInfo4: ['', '<div class="runelvl">\n<br>Nível: 3/2 (precisa runa)\n\n<br><br><span class="left"><span class="tooltip-value">615</span> Mana</span><span class="right">Tempo de ativação: 1 segundo(s)</span>\n<br><span class="left">Dano de escuridão</span><span class="right">Intervalo: 8 segundo(s)</span>\n<br><span class="left">Ataque contra múltiplos alvos</span><span class="right">Alcance: Nenhum</span>\n\n<br><br>Afeta múltiplos inimigos em um alcance de 10. Custa 1% da sua Saúde. Inflige 100% do seu Ataque básico mais <span class="tooltip-value">1987</span> de bônus de dano. Esta habilidade tem o mesmo efeito em maldições que a Fúria da Morte. A forma de Vampiro aprimora ainda os efeitos desta habilidade. Tem 10% de chance de ativar a forma de Vampiro.</div>'],
		},
		{
			index: 32,
			name: "Especialidade em Escuridão",
			ranks: 3,
			desc: "Aumenta a sua Maestria em Escuridão em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 34,
			name: "Maestria em Explosão de Mana",
			ranks: 2,
			desc: "Aumenta o dano base da Explosão de Mana em <span class='tooltip-value'>#%</span> e aumenta seu alcance em <span class='tooltip-value'>#%</span> metro(s).",
			rankInfo: [10, 20],
			rankInfo2: [1, 2],
			parent: 18,
		},
		{
			index: 35,
			name: "Escuridão Repentina",
			ranks: 2,
			desc: "Reduz os intervalos dos Títulos Sombrios e Explosão de Mana em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>Reduz os intervalos dos Títulos Sombrios e Explosão de Mana em <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 37,
			name: "Estado de Vampiro Sombrio",
			ranks: 1,
			desc: "Enquanto se está na forma de Vampiro, habilidades que custam Saúde passam a restaurá-la em dobro em relação à quantidade normalmente consumida.",
			rankInfo: [],
		},
		{
			index: 38,
			name: "Defesa Inscrita",
			ranks: 2,
			desc: "Reduz o intervalo do Ritual de Sangue em <span class='tooltip-value'>#</span> segundo(s) e dá <span class='tooltip-value'>#%</span> de chance de dissipar qualquer efeito de enredamento ou atordoamento que estiver te afetando.",
			rankInfo: [20, 40],
			rankInfo2: [50, 100],
		},
		{
			index: 40,
			name: "Escuridão Sem Fim",
			ranks: 2,
			desc: "Aumenta a sua Resistência da Escuridão em <span class='tooltip-value'>#</span> e a sua Evasão em <span class='tooltip-value'>#</span>.",
			rankInfo: [25, 50],
			rankInfo2: [4, 8],
		},
		{
			index: 41,
			name: "Veias Congeladas",
			ranks: 1,
			desc: "Você fica imune a efeitos de retardamento enquanto a forma de Vampiro está ativa.",
			rankInfo: [],
		},
		{
			index: 42,
			name: "Poder da Alma",
			ranks: 4,
			desc: "Aumenta o dano base da Ondulação Sombria, Ataque Encantado, Fúria da Morte e Cicatriz Sombria em <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 43,
			name: "Raiva Sombria",
			ranks: 2,
			desc: "Reduz o intervalo da Cicatriz Sombria em <span class='tooltip-value'>#</span> segundos e aumenta a Chance Crítica de seus ataques em <span class='tooltip-value'>#%</span> e <span class='tooltip-value'>#%</span>, respectivamente.",
			rankInfo: [2, 4],
			rankInfo2: [2, 4],
			rankInfo3: [4, 8],
		},
		{
			index: 46,
			name: "Forma de Demônio",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>249 Mana</span><span class='right'>Tempo de ativação: Instantâneo</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 120 segundo(s)</span>\n<span class='left'>Bênção para alvo único</span><span class='right'>Alcance: Nenhum</span>\n\nVocê se transforma em um Demônio e sua Evasão aumenta em 100. Você não pode usar nenhuma habilidade além do Ataque Encantado durante 20 segundos. O intervalo do Ataque Encantado dura 3 segundos e seu dano base é reduzido em 10%. Reduz em 60 a Evasão de alvos em um raio de 5 metros. Cancele o efeito desta habilidade usando-a novamente.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// three
	[
		{
			index: 2,
			name: "Chamas Insaciáveis",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta a duração da Maldição Escura em <span class='tooltip-value'>#</span> segundo(s). Aumenta o alcance da Maldição Escura em <span class='tooltip-value'>#</span> metro(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12, 16, 20],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Aumenta a duração da Maldição Escura em <span class="tooltip-value">24</span> segundo(s). Aumenta o alcance da Maldição Escura em <span class="tooltip-value">6</span> metro(s).</div>'],
		},
		{
			index: 3,
			name: "Submundo Chamuscante",
			ranks: 5,
			desc: "Aumenta o bônus de dano da Chama do Mal em <span class='tooltip-value'>#</span> mais <span class='tooltip-value'>#%</span> da sua Maestria em Fogo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100, 150, 200, 250],
			rankInfo2: [40, 80, 120, 160, 200],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Aumenta o bônus de dano da Chama do Mal em <span class="tooltip-value">300</span> mais <span class="tooltip-value">240%</span> da sua Maestria em Fogo.</div>'],
		},
		{
			index: 6,
			name: "Energia da Maldição",
			ranks: 3,
			desc: "Maldição Escura reduz as Resistências da Escuridão e de Fogo do alvo em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Maldição Escura reduz as Resistências da Escuridão e de Fogo do alvo em <span class="tooltip-value">40</span>.</div>'],
			parent: [0],
		},
		{
			index: 7,
			name: "Chama do Clarão",
			ranks: 5,
			ranksnw: 1,
			desc: "Reduz o intervalo da Chama do Mal em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nível: 6/5 (precisa runa)\n\n<br><br>Reduz o intervalo da Chama do Mal em <span class="tooltip-value">6</span> segundo(s).</div>'],
		},
		{
			index: 9,
			name: "Ataque Encantado Flamejante",
			ranks: 4,
			desc: "O Ataque Encantado reduz a Defesa dos alvos afetados pela Maldição Escura em <span class='tooltip-value'>#</span> por 30 segundos. Acumula 5 vezes. Ataque Encantado causa um dano adicional de 26 em alvos afetados pela Maldição da Chama.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>O Ataque Encantado reduz a Defesa dos alvos afetados pela Maldição Escura em <span class="tooltip-value">15</span> por 30 segundos. Acumula 5 vezes. Ataque Encantado causa um dano adicional de 26 em alvos afetados pela Maldição da Chama.</div>'],
		},
		{
			index: 10,
			name: "Semente da Chama",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Fogo</span><span class='right'>Intervalo: 20 segundo(s)</span>\n<span class='left'>Maldição contra alvo único</span><span class='right'>Alcance: 12 metro(s)</span>\n\nAlvos afetados pela Semente da Chama são queimados e recebem <span class='tooltip-value'>#</span> de dano cada vez que atacam ou são atacados. Este efeito dura 20 segundos. Semente da Chama remove todos os efeitos de maldições do alvo e causa dano instantaneamente para cada maldição removida. A Maldição da Chama causa <span class='tooltip-value'>#</span> de dano, enquanto a Maldição de Sangue e a Maldição Escura causam <span class='tooltip-value'>#</span> de dano. Tem 5% de chance de ativar a forma de Vampiro.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n'],
			rankInfo2: [200, 287, 376],
			rankInfo3: [50, 80, 110],
			rankInfo4: [1202, 1922, 2634],
			rankInfo5: [601, 961, 1317],
			rankInfo6: ['', '', '<div class="runelvl">\n<br>Nível: 4/3 (precisa runa)\n\n<br><br><span class="left"><span class="tooltip-value">466</span> Mana</span><span class="right">Tempo de ativação: 1 segundo(s)</span>\n<br><span class="left">Fogo</span><span class="right">Intervalo: 20 segundo(s)</span>\n<br><span class="left">Maldição contra alvo único</span><span class="right">Alcance: 12 metro(s)</span>\n\n<br><br>Alvos afetados pela Semente da Chama são queimados e recebem <span class="tooltip-value">140</span> de dano cada vez que atacam ou são atacados. Este efeito dura 20 segundos. Semente da Chama remove todos os efeitos de maldições do alvo e causa dano instantaneamente para cada maldição removida. A Maldição da Chama causa <span class="tooltip-value">3339</span> de dano, enquanto a Maldição de Sangue e a Maldição Escura causam <span class="tooltip-value">1669</span> de dano. Tem 5% de chance de ativar a forma de Vampiro.</div>'],
		},
		{
			index: 12,
			name: "Chama Persistente",
			ranks: 4,
			desc: "Aumenta a duração da Maldição da Chama em <span class='tooltip-value'>#</span> segundo(s). Reduz a Resistência de Fogo do alvo em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>Aumenta a duração da Maldição da Chama em <span class="tooltip-value">25</span> segundo(s). Reduz a Resistência de Fogo do alvo em <span class="tooltip-value">50</span>.</div>'],
		},
		{
			index: 13,
			name: "Demônio da Chama",
			ranks: 5,
			desc: "Aumenta a chance da Maldição Escura, Chama do Mal, Morte do Fogo do Inferno, Semente da Chama e Massacre Infernal ativarem a forma de Vampiro em <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 15,
			name: "Maldição da Necrochama",
			ranks: 2,
			desc: "Chama do Mal tem <span class='tooltip-value'>#%</span> de chance de aplicar duas pilhas de Chama Mágica aos alvos afetados pela Maldição Escura.",
			rankInfo: [50, 100],
			parent: 3,
		},
		{
			index: 16,
			name: "Gulodice",
			ranks: 3,
			desc: "Banquete drena uma quantidade de Saúde adicional equivalente a <span class='tooltip-value'>#%</span> da sua Saúde Máxima. Reduz a duração do efeito Enredar em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Banquete drena uma quantidade de Saúde adicional equivalente a <span class="tooltip-value">2%</span> da sua Saúde Máxima. Reduz a duração do efeito Enredar em <span class="tooltip-value">4</span> segundo(s).</div>'],
		},
		{
			index: 18,
			name: "Tortura da Chama",
			ranks: 4,
			ranksnw: 1,
			desc: "Alvos afetados pela Semente da Chama recebem um dano adicional de <span class='tooltip-value'>#%</span> quando atacam ou são atacados.",
			rankInfo: [25, 50, 75, 100],
			parent: 5,
		},
		{
			index: 19,
			name: "Asas Fantasma",
			ranks: 3,
			desc: "Quando a forma de morcego termina, você retém 60% do bônus de velocidade de movimento durante <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 7, 9],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Quando a forma de morcego termina, você retém 60% do bônus de velocidade de movimento durante <span class="tooltip-value">11</span> segundo(s).</div>'],
		},
		{
			index: 21,
			name: "Morte Maligna Flamejante",
			ranks: 4,
			desc: "Fúria da Morte reduz a Defesa dos alvos afetados pela Maldição da Chama em um adicional de <span class='tooltip-value'>#%</span> durante <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nível: 5/4 (precisa runa)\n\n<br><br>Fúria da Morte reduz a Defesa dos alvos afetados pela Maldição da Chama em um adicional de <span class="tooltip-value">125%</span> durante <span class="tooltip-value">5</span> segundo(s).</div>'],
		},
		{
			index: 23,
			name: "Supressão da Chama",
			ranks: 2,
			desc: "Reduz a quantidade de ameaça gerada pelas suas habilidades de Fogo e Maldição e reduz seus custos de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 26,
			name: "Eclipse Mágico",
			ranks: 4,
			desc: "Quando alvos afetados pela Semente da Chama atacam ou são atacados, eles perdem uma quantidade de Mana equivalente a <span class='tooltip-value'>#%</span> da sua Maestria em Fogo.",
			rankInfo: [15, 30, 45, 60],
			parent: 10,
		},
		{
			index: 28,
			name: "Tolerância da Necrochama",
			ranks: 4,
			desc: "Aumenta a sua Resistência ao Fogo em <span class='tooltip-value'>#</span> e a sua Defesa em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 30,
			name: "Morcego do Inferno",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: Instantâneo</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nVocê se transforma em um Morcego do Inferno durante <span class='tooltip-value'>#</span> segundo(s). O seu Ataque aumenta em <span class='tooltip-value'>#%</span>, a sua velocidade de movimento aumenta em <span class='tooltip-value'>#%</span> e o alcance das suas habilidades aumenta em 50%. Nesta forma você só pode usar habilidades de Fogo. Chama do Mal não possui um intervalo, mas causa 40% menos bônus de dano. Seu tempo de conjuração é reduzido para 1 segundo. Semente da Chama causa <span class='tooltip-value'>#</span> de dano e atordoa o alvo durante 2 segundos. Reduz o intervalo das Asas da Tempestade para 6 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [162, 199],
			rankInfo3: [150, 120],
			rankInfo4: [20, 25],
			rankInfo5: [5, 7],
			rankInfo6: [20, 30],
			rankInfo7: [1202, 1922],
			rankInfo8: ['', '<div class="runelvl">\n<br>Nível: 3/2 (precisa runa)\n\n<br><br><span class="left"><span class="tooltip-value">239</span> Mana</span><span class="right">Tempo de ativação: Instantâneo</span>\n<br><span class="left">Ataque</span><span class="right">Intervalo: <span class="tooltip-value">90</span> segundo(s)</span>\n<br><span class="left">Autobênção</span><span class="right">Alcance: Nenhum</span>\n\n<br><br>Você se transforma em um Morcego do Inferno durante <span class="tooltip-value">30</span> segundo(s). O seu Ataque aumenta em <span class="tooltip-value">9%</span>, a sua velocidade de movimento aumenta em <span class="tooltip-value">40%</span> e o alcance das suas habilidades aumenta em 50%. Nesta forma você só pode usar habilidades de Fogo. Chama do Mal não possui um intervalo, mas causa 40% menos bônus de dano. Seu tempo de conjuração é reduzido para 1 segundo. Semente da Chama causa <span class="tooltip-value">2634</span> de dano e atordoa o alvo durante 2 segundos. Reduz o intervalo das Asas da Tempestade para 6 segundos.</div>'],
		},
		{
			index: 31,
			name: "Enfraquecido",
			ranks: 3,
			desc: "Títulos Sombrios reduzem as Resistências do alvo em <span class='tooltip-value'>#</span> durante <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: [20, 35, 50],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Nível: 4/3 (precisa runa)\n\n<br><br>Títulos Sombrios reduzem as Resistências do alvo em <span class="tooltip-value">80</span> durante <span class="tooltip-value">65</span> segundo(s).</div>'],
		},
		{
			index: 33,
			name: "Fogo do Inferno Acelerado",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduz o intervalo da Morte do Fogo do Inferno em <span class='tooltip-value'>#</span> segundo(s) e aumenta o seu dano base em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Nível: 3/2 (precisa runa)\n\n<br><br>Reduz o intervalo da Morte do Fogo do Inferno em <span class="tooltip-value">3</span> segundo(s) e aumenta o seu dano base em <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 34,
			name: "Formato de Morcego",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduz o intervalo do Morcego do Inferno em <span class='tooltip-value'>#</span> segundo(s). Enquanto se está na forma do Morcego do Inferno, você causa uma quantidade de dano equivalente a <span class='tooltip-value'>#</span> mais <span class='tooltip-value'>#%</span> da sua Maestria em Fogo a cada 3 segundos a alvos dentro de 10 metros que foram afetados pela Maldição Escura.",
			rankInfo: [10, 20, 30],
			rankInfo2: [300, 600, 900],
			rankInfo3: [10, 20, 30],
			parent: 16,
		},
		{
			index: 37,
			name: "Pulso do Fogo do Inferno",
			ranks: 2,
			desc: "Morte do Fogo do Inferno empurra o alvo a <span class='tooltip-value'>#</span> metro(s) e tem uma chance de <span class='tooltip-value'>#%</span> de atordoar o alvo durante 3 segundos.",
			rankInfo: [2, 4],
			rankInfo2: [20, 40],
			parent: 18,
		},
		{
			index: 38,
			name: "Morcego do Fogo do Inferno",
			ranks: 2,
			desc: "Reduz o intervalo de uso da Morte do Fogo do Inferno em <span class='tooltip-value'>#</span> segundo(s), seu tempo de conjuração em <span class='tooltip-value'>#</span> segundo(s) e aumenta seu alcance em <span class='tooltip-value'>#%</span> enquanto você está na forma de Vampiro do Inferno.",
			rankInfo: [1, 2],
			rankInfo2: [0.5, 1],
			rankInfo3: [25, 50],
			parent: 19,
		},
		{
			index: 40,
			name: "Manobra da Chama",
			ranks: 3,
			desc: "Aumenta a sua Maestria em Fogo em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 42,
			name: "Fúria do Fogo do Inferno",
			ranks: 3,
			desc: "Aumenta o dano de bônus da Chama do Mal em e Morte do Fogo do Inferno em um adicional de <span class='tooltip-value'>#%</span> e aumenta sua Chance Crítica em <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 43,
			name: "Maldição Chamuscante",
			ranks: 3,
			desc: "A Maldição Escura e Morte do Fogo do Inferno causam em seus alvos o efeito Maldição do Fogo da Alma, que absorve um total de Saúde equivalente a <span class='tooltip-value'>#</span> vezes a sua Maestria de Fogo e drena <span class='tooltip-value'>#</span> de Mana do alvo.",
			rankInfo: [3, 4, 5],
			rankInfo2: [400, 800, 1200],
		},
		{
			index: 46,
			name: "Massacre Infernal",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>365 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de fogo</span><span class='right'>Intervalo: 12 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 12 metro(s)</span>\n\n\Inflige 120% do seu Ataque mais 2119 de bônus de dano. Causa dano equivalente a 1500 mais 100% da sua Maestria de Fogo em alvos afetados pela Maldição da Chama. Atordoa um alvo afetado pela Maldição de Sangue, Maldição Escura e Maldição da Chama, ao mesmo tempo, por 3 segundos. Tem 5% de chance de ativar a forma de Vampiro.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	]
];