var data = [
    // one
    [
        {
            index: 1,
            name: "Sabotaje",
            ranks: 5,
			desc: "Embate obtiene un 50% de posibilidad de reducir la Defensa del objetivo en <span class='tooltip-value'>#</span> por 20 segundos. Cada pila de Postura de Combate aumenta la posibilidad de que este efecto ocurra en un 20%. Se acumula 3 veces. En Posición 5, cada pila reduce la Defensa del objetivo en un 1% adicional.",
            rankInfo: [5, 10, 15, 20, 25],
        },
        {
            index: 3,
            name: "Maniaco de Batalla",
            ranks: 5,
			desc: "Cada pila de Postura de Combate aumenta el bono de Defensa en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#</span>.",
            rankInfo: [0.3, 0.6, 0.9, 1.2, 1.5],
            rankInfo2: [3, 6, 9, 12, 15],
        },
        {
            index: 5,
            name: "Furia de relámpagos",
            ranks: 3,
			desc: "Aumenta el daño extra de ambos golpes de Cuchillada de Rayo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6, 9],
        },
        {
            index: 7,
            name: "Canción de Guerra de Agilidad",
            ranks: 5,
			ranksnw: 2,
			desc: "Grito de Guerra aumenta tu Defensa en un <span class='tooltip-value'>#</span> adicional y tu Evasión en <span class='tooltip-value'>#</span> Aumenta tu Defensa base en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [1, 2, 3, 4, 5],
            rankInfo3: [0.5, 1, 1.5, 2, 2.5],
        },
        {
            index: 8,
            name: "Desprecio",
            ranks: 3,
			desc: "Aumenta la cantidad de amenaza generada a partir del daño extra en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100, 150],
        },
        {
            index: 9,
            name: "Rugido Aplastante",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Físico</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Maldición multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nLa Precisión de los enemigos a menos de 10 metros es reducida en <span class='tooltip-value'>#</span> y su Ataque es reducido en <span class='tooltip-value'>#</span> por 15 segundos. Pone al descubierto a enemigos ocultos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [104, 148, 193, 239],
            rankInfo3: [20, 30, 40, 50],
            rankInfo4: [20, 40, 60, 80],
        },
        {
            index: 10,
            name: "Comprensión de la Guerra",
            ranks: 4,
			desc: "Reduce la reactivación de Apoyo Divino en <span class='tooltip-value'>#</span> segundos. Si tu Salud cae por debajo de 50%, mientras Apoyo Divino está activo, el bono de Defensa es aumentado en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45, 60],
            rankInfo2: [10, 20, 30, 40],
        },
        {
            index: 12,
            name: "Tenacidad",
            ranks: 4,
			desc: "Aumenta tu Salud máxima en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 13,
            name: "Aplasta Agallas",
            ranks: 3,
			desc: "La duración de Rugido Aplastante es aumentada en <span class='tooltip-value'>#</span> segundo(s) y gana un <span class='tooltip-value'>#%</span> de posibilidad de interrumpir a un enemigo lanzando hechizos.",
            rankInfo: [1, 2, 3],
            rankInfo2: [20, 40, 60],
			parent: 5,
        },
        {
            index: 14,
            name: "Brisa de Exorcismo",
            ranks: 5,
			ranksnw: 3,
			desc: "Aumenta el daño extra de Guarda Maligna en <span class='tooltip-value'>#%</span> y reduce la Resistencia al Viento del objetivo en <span class='tooltip-value'>#</span>.",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [10, 20, 30, 40, 50],
        },
        {
            index: 16,
            name: "Resistencia a Tormenta",
            ranks: 3,
			desc: "Aumenta tu Resistencia al Viento en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
        },
        {
            index: 18,
            name: "Corrupción Decadente",
            ranks: 4,
			desc: "Guarda Maligna obtiene un <span class='tooltip-value'>#%</span> de posibilidad de provocar a su objetivo por 2 segundos. Aumenta su alcance en <span class='tooltip-value'>#</span> metro(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [25, 50, 75, 100],
            rankInfo2: [1, 2, 3, 4],
			parent: 9,
        },
        {
            index: 20,
            name: "Fortificar Defensa",
            ranks: 3,
			desc: "Aumenta tu Resistencia Física en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 21,
            name: "El Arte de Sobrevivir",
            ranks: 3,
			desc: "Reduce los costos del Maná de Grito de Guerra, Postura de Combate, Rugido Aplastante y Rugido Amenazador en <span class='tooltip-value'>#%</span> Aumenta la duración de Apoyo Divino en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
            rankInfo2: [2, 4, 6],
        },
        {
            index: 23,
            name: "Especialista de Combate",
            ranks: 2,
			desc: "Cada pila de Postura de Combate reduce el daño a recibir en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6],
			parent: 3,
        },
        {
            index: 25,
            name: "Fuente de la Fuerza",
            ranks: 3,
			ranksnw: 2,
			desc: "Aumenta la duración de Poder de Dragón en <span class='tooltip-value'>#</span> minutos.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 26,
            name: "Art of Sortie",
            ranks: 2,
			desc: "Reduces the minimum range of Assault by <span class='tooltip-value'>#%</span> and increases the amount of threat it generates while you are in Combat Stance.",
            rankInfo: [50, 100],
        },
        {
            index: 27,
            name: "Despertar",
            ranks: 2,
			desc: "Reduce la sanción de ataque causada por Postura de Combate en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100],
        },
        {
            index: 29,
            name: "Sangre de Dragón",
            ranks: 2,
			desc: "Poder de Dragón aumenta la Salud máxima del objetivo en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6],
			parent: 15,
        },
        {
            index: 30,
            name: "Guardián de Vida",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 180 segundos</span>\n<span class='left'>Bendición multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nCura y aumenta la Salud máxima de los miembros del grupo a menos de 16 metros en <span class='tooltip-value'>#%</span>. Aumenta tu Salud máxima en un 5% adicional. Este efecto dura <span class='tooltip-value'>#</span> segundos. Esta habilidad no se ve afectada por efectos controladores.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [223, 277],
            rankInfo3: [15, 16],
            rankInfo4: [25, 30],
        },
        {
            index: 31,
            name: "Ruptura de Guardia",
            ranks: 2,
			desc: "El efecto causado por Cuchillada de Trueno reduce la Evasión de Crítica en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
        },
        {
            index: 35,
            name: "Voluntad de Sangre",
            ranks: 2,
			desc: "Reduce la cantidad de Salud perdida mientras Empapado de sangre está activo en <span class='tooltip-value'>#%</span>. Reduce el costo de Maná de Empapado de sangre en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [25, 50],
            rankInfo2: [25, 50],
        },
        {
            index: 36,
            name: "Defensa de Combate",
            ranks: 3,
			desc: "Aumenta tu Defensa base en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#</span>.",
            rankInfo: [1, 2, 3],
            rankInfo2: [15, 25, 40],
        },
        {
            index: 38,
            name: "Esperanza",
            ranks: 3,
			ranksnw: 1,
			desc: "Reduce la reactivación de Guardián de Vida en <span class='tooltip-value'>#</span> segundos. Mientras Guardián de Vida está activo, cada golpe que recibas restaura <span class='tooltip-value'>#%</span> de tu Salud máxima.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40, 60],
            rankInfo2: [2, 5, 8],
			parent: 19,
        },
        {
            index: 39,
            name: "Decadencia Moral",
            ranks: 2,
			desc: "Alas de Rayo obtiene un 75% de posibilidad de reducir el ataque del objetivo en <span class='tooltip-value'>#%</span> por 15 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
        },
        {
            index: 42,
            name: "Concentración",
            ranks: 2,
			desc: "Mientras Guardián de Vida está activo, la eficacia de las habilidades curativas aplicadas en ti es aumentada en <span class='tooltip-value'>#%</span> y no puedes ser interrumpido mientras lanzas hechizos.",
            rankInfo: [20, 40],
			parent: 23,
        },
        {
            index: 43,
            name: "Coro de Trueno",
            ranks: 3,
			ranksnw: 1,
			desc: "Aumenta el daño base de Cuchillada de Rayo, Cuchillada de Trueno, y Choque Embravecido en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15],
        },
        {
            index: 47,
            name: "Choque Embravecido",
            ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>301 Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>EI daño de viento</span><span class='right'>Reactivación: 6 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nInflige 100% de tu Ataque más 2193 de daño extra. Requiere Postura de Combate. Reduce los Dominios del objetivo en 300 para sus próximos 2 ataques. Dura 8 segundos. Genera una gran cantidad de amenaza.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
			parent: 26,
        },
    ],
        // two
    [
        {
            index: 1,
            name: "Ataque Tormenta",
            ranks: 5,
			ranksnw: 3,
			desc: "Aumenta el daño extra de Embate en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#%</span> de tu Dominio Físico.",
            rankInfo: [2, 4, 6, 8, 10],
            rankInfo2: [10, 20, 30, 40, 50],
        },
        {
            index: 2,
            name: "A la carga",
            ranks: 2,
			desc: "Reduce el alcance mínimo de Asalto en <span class='tooltip-value'>#</span> metro(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
        },
        {
            index: 3,
            name: "Código de Misión de Combate",
            ranks: 3,
			desc: "Reduce la reactivación de Asalto en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
        },
        {
            index: 5,
            name: "Partir",
            ranks: 3,
			desc: "Aumenta el Chance Crítico de Embate en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
			parent: [0],
        },
        {
            index: 6,
            name: "Canción Tormenta",
            ranks: 4,
			desc: "Grito de Guerra aumenta tus Dominios de Viento y Físico en <span class='tooltip-value'>#</span> adicional.",
            rankInfo: [5, 10, 15, 20],
        },
        {
            index: 7,
            name: "Ciénaga de Rayo",
            ranks: 3,
			desc: "Aumenta la posibilidad de que el segundo golpe de Cuchillada de Rayo frene al objetivo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 9,
            name: "Arco Carmesí",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño físico</span><span class='right'>Reactivación: 5 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nGolpea al objetivo dos veces. Cada golpe inflige 90% de tu Ataque base más <span class='tooltip-value'>#</span> de daño extra y tiene un 25% de posibilidad de causar un efecto de sangrado que inflige <span class='tooltip-value'>#</span> de daño por segundo. Dura 10 segundos. Se acumula 3 veces. Con 1/2/3 pila(s) de Postura de Ira de Sangre, la posibilidad de causar el efecto de sangrado es aumentada en 5%/10%/15%.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [105, 162, 221, 281],
            rankInfo3: [446, 876, 1299, 1715],
            rankInfo4: [50, 100, 150, 200],
        },
        {
            index: 10,
            name: "Floración de Vida",
            ranks: 5,
			desc: "Cada pila de Postura de Ira de Sangre aumenta tu Salud máxima en <span class='tooltip-value'>#%</span> más <span class='tooltip-value'>#</span>.",
            rankInfo: [0.3, 0.6, 0.9, 1.2, 1.5],
            rankInfo2: [50, 100, 150, 200, 250],
        },
        {
            index: 12,
            name: "Constante",
            ranks: 3,
			desc: "Reduce la posibilidad de ser interrumpido mientras se lanzan hechizos en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
        },
        {
            index: 13,
            name: "Amputar",
            ranks: 3,
			ranksnw: 2,
			desc: "Cada golpe de Arco Carmesí inflige daño extra igual a <span class='tooltip-value'>#%</span> de tu Salud máxima.",
            rankInfo: [1, 1.5, 2],
			parent: 6,
        },
        {
            index: 14,
            name: "Santuario de Guerra",
            ranks: 3,
			desc: "Aumenta la duración de Apoyo Divino en <span class='tooltip-value'>#%</span>. Aumenta tu Daño Crítico en <span class='tooltip-value'>#%</span> mientras Apoyo Divino está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
            rankInfo2: [10, 20, 30],
        },
        {
            index: 15,
            name: "Sangriento",
            ranks: 3,
			ranksnw: 2,
			desc: "Aumenta el daño extra de Cuchillada Chupasangre en <span class='tooltip-value'>#%</span>. Aumenta la cantidad de Salud drenada en <span class='tooltip-value'>#%</span> de tu Salud máxima.",
            rankInfo: [5, 10, 15],
            rankInfo2: [1, 1.5, 2],
        },
        {
            index: 18,
            name: "Prisa",
            ranks: 3,
			desc: "Reduce la reactivación de Choque Precipitado en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 19,
            name: "Quemadura de Sangre",
            ranks: 3,
			desc: "Reduce la reactivación de Cuchillada Chupasangre en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
			parent: 11,
        },
        {
            index: 20,
            name: "Dominio en Manejo de la Espada",
            ranks: 4,
			desc: "Aumenta tu Dominio Físico en <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 21,
            name: "Elegancia Carmesí",
            ranks: 3,
			desc: "Reduce la reactivación de Arco Carmesí en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 1.5, 2],
			parent: 9,
        },
        {
            index: 22,
            name: "Sangre Hirviendo",
            ranks: 2,
			desc: "Cada pila de Postura de Ira de Sangre aumenta la eficacia de las habilidades de curación aplicadas en ti en <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6],
        },
        {
            index: 25,
            name: "Sabotaje de Armas",
            ranks: 2,
			desc: "Aumenta la posibilidad de Cuchillada de Trueno para desarmar al objetivo en <span class='tooltip-value'>#%</span>\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
        },
        {
            index: 26,
            name: "Ferocidad",
            ranks: 4,
			desc: "Aumenta el daño base de Cuchillada Chupasangre y Arco Carmesí en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15, 20],
        },
        {
            index: 29,
            name: "Brote de Ira de Sangre",
            ranks: 2,
			desc: "Reduce la sanción causada por la Postura de Ira de Sangre en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100],
        },
        {
            index: 30,
            name: "Furia de Sed de sangre",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: 120 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nCuesta 5% de tu Salud máxima. Disipa y concede inmunidad a efectos de sangrado por 18 segundos. Mientras Furia de Sed de sangre está activo, cada uno de tus ataques cuesta 1% de tu Salud máxima y aumentan tu Chance Crítico en <span class='tooltip-value'>#%</span>. El bono de Chance Crítico dura 15 segundos y se acumula 8 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [189, 236],
            rankInfo3: [1, 1.5],
        },
        {
            index: 31,
            name: "Bloodlust Frenzy",
            ranks: 2,
			desc: "Reduces the cooldown of Bloodsuck Slash by <span class='tooltip-value'>#%</span> and increases the amount of Health it drains by <span class='tooltip-value'>#%</span> while Bloodlust Fury is active.",
            rankInfo: [30, 60],
            rankInfo2: [100, 200],
			parent: 20,
        },
        {
            index: 33,
            name: "Silencio de Trueno",
            ranks: 2,
			desc: "Cuchillada de Trueno silencia al objetivo por <span class='tooltip-value'>#</span> segundo(s) cuando asesta un golpe Crítico.",
            rankInfo: [1, 2],
        },
        {
            index: 35,
            name: "Contrato de Sangre",
            ranks: 3,
			ranksnw: 2,
			desc: "Reduce la reactivación de Empapado de sangre en <span class='tooltip-value'>#</span> segundos y aumenta su duración en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [5, 10, 15],
            rankInfo2: [2, 4, 6],
        },
        {
            index: 38,
            name: "Sed de sangre Extendida",
            ranks: 2,
			desc: "Aumenta la duración de Furia de Sed de sangre en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [3, 6],
			parent: 20,
        },
        {
            index: 39,
            name: "Baile de Sangre",
            ranks: 3,
			desc: "Aumenta el daño base de Embate en <span class='tooltip-value'>#%</span> y le concede un <span class='tooltip-value'>#%</span> de posibilidad de atrapar al objetivo por 2 segundos, mientras que Empapado de sangre está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
            rankInfo2: [20, 40, 60],
			parent: 23,
        },
        {
            index: 42,
            name: "Espada de Alta Frecuencia",
            ranks: 3,
			desc: "Aumenta el Daño Crítico de Embate, Guarda Maligna, Cuchillada Chupasangre, y Sacrificio en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15],
        },
        {
            index: 43,
            name: "Devorar a la Fuerza",
            ranks: 2,
			desc: "Aumenta la duración de Devorar el Alma por <span class='tooltip-value'>#</span> segundos. Tiene un <span class='tooltip-value'>#%</span> de posibilidad de obtener una pila adicional de Devorar el Alma cuando te hacen daño. Aumenta el daño extra concedido por Devorar el Alma en <span class='tooltip-value'>#%</span>.",
            rankInfo: [2, 4],
            rankInfo2: [50, 100],
            rankInfo3: [0.5, 1],
        },
        {
            index: 46,
            name: "Sacrificio",
            ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>231 Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño físico</span><span class='right'>Reactivación: 15 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nRequiere Postura de Ira de Sangre. Golpea al objetivo dos veces. Cada golpe inflige 90% de tu Ataque base más 1159 de daño extra. Sacrifica 10% de tu Salud y agrega esa cantidad a tu Ataque.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // three
    [
        {
            index: 1,
            name: "Arrasar",
            ranks: 5,
			desc: "Cada pila de Postura de Frenesí aumenta tu Ataque en un <span class='tooltip-value'>#%</span> adicional más un <span class='tooltip-value'>#</span>.",
            rankInfo: [0.3, 0.6, 0.9, 1.2, 1.5],
            rankInfo2: [10, 20, 30, 40, 50],
        },
        {
            index: 2,
            name: "Rayo Mortal",
            ranks: 5,
			ranksnw: 3,
			desc: "Aumenta tu Ataque en <span class='tooltip-value'>#</span> por 10 segundos cuando matas a un objetivo en menos de 10 segundos al usar Cuchillada de Rayo. Este efecto también aumenta tu Ataque base en 1%.",
            rankInfo: [20, 35, 50, 65, 80],
        },
        {
            index: 5,
            name: "Misión de Combate Valiente",
            ranks: 5,
			desc: "Aumenta la posibilidad de activar el efecto Misión de Combate Valiente en <span class='tooltip-value'>#%</span> Misión de Combate Valiente aumenta tu Precisión en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [6, 12, 18, 24, 30],
            rankInfo2: [10, 20, 30, 40, 50],
        },
        {
            index: 6,
            name: "Misterio de Rayo",
            ranks: 3,
			desc: "Reduce la reactivación de Cuchillada de Rayo en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
			parent: 1,
        },
        {
            index: 7,
            name: "Dominio de Canción de Guerra",
            ranks: 3,
			ranksnw: 3,
			desc: "Aumenta la duración de Grito de Guerra en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [300, 600, 900],
        },
        {
            index: 9,
            name: "Devastación de Combate",
            ranks: 3,
			desc: "Aumenta tu Ataque en <span class='tooltip-value'>#%</span> por 10 segundos cuando eres golpeado mientras Apoyo Divino está activo. Se acumula 5 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
        },
        {
            index: 10,
            name: "Rugido Amenazador",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Físico</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Maldición multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nReduce la Evasión en <span class='tooltip-value'>#</span> la Defensa en <span class='tooltip-value'>#</span> y la velocidad de movimiento en 25% a los enemigos a menos de 10 metros por 10 segundos. Pone al descubierto a enemigos ocultos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [87, 123, 161, 199],
            rankInfo3: [15, 25, 35, 45],
            rankInfo4: [25, 50, 75, 100],
        },
        {
            index: 11,
            name: "Canción de Guerra Élfica",
            ranks: 3,
			desc: "Grito de Guerra aumenta tu Ataque en <span class='tooltip-value'>#</span> tu Precisión en <span class='tooltip-value'>#</span> y tu Ataque base en un <span class='tooltip-value'>#%</span> adicional.",
            rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
            rankInfo3: [0.5, 1, 1.5],
			parent: 4,
        },
        {
            index: 14,
            name: "Aullido",
            ranks: 3,
			desc: "Aumenta la duración de Rugido Amenazador en <span class='tooltip-value'>#</span> segundos y reduce la Resistencia al Viento de los objetivos en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
            rankInfo2: [10, 20, 30],
			parent: 6,
        },
        {
            index: 15,
            name: "Exorcismo",
            ranks: 4,
			desc: "Guarda Maligna reduce la Resistencia Física del objetivo en <span class='tooltip-value'>#</span> y su Maná máximo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45, 60],
            rankInfo2: [5, 10, 15, 20],
        },
        {
            index: 16,
            name: "Dominio de Tormenta",
            ranks: 4,
			desc: "Aumenta tu Dominio del Viento en <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 17,
            name: "Código de Prisa",
            ranks: 3,
			desc: "Aumenta la duración de Choque Precipitado en <span class='tooltip-value'>#</span> segundo(s). Choque Precipitado aumenta tu velocidad de movimiento en un <span class='tooltip-value'>#%</span> adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
			rankInfo2: [2.5, 5, 7.5],
        },
        {
            index: 18,
            name: "Toque Sangrante",
            ranks: 3,
			desc: "Cuchillada Chupasangre reduce la eficacia de las habilidades de curación aplicadas en el objetivo en <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [25, 35, 45],
            rankInfo2: [6, 8, 10],
        },
        {
            index: 19,
            name: "Baile de Hoja",
            ranks: 4,
			desc: "Aumenta el Chance Crítico de Cuchillada de Rayo en <span class='tooltip-value'>#%</span> mientras se está en Postura de Frenesí. Cada pila adicional de Postura de Frenesí aumenta aún más el Chance Crítico.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [0.5, 1, 1.5, 2],
        },
        {
            index: 21,
            name: "Exposición de Debilidad",
            ranks: 2,
			ranksnw: 2,
			desc: "Asalto reduce la Evasión de Crítica del objetivo en <span class='tooltip-value'>#%</span> hasta 10 segundos. Este efecto termina cuando el objetivo es golpeado 3 veces.",
            rankInfo: [2, 4],
        },
        {
            index: 22,
            name: "Tormenta de Truenos",
            ranks: 4,
			ranksnw: 3,
			desc: "Aumenta el Chance Crítico de ambos ataques de Cuchillada de Trueno en <span class='tooltip-value'>#%</span> y reduce la reactivación de la habilidad en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3, 4],
            rankInfo2: [0.5, 1, 1.5, 2],
        },
        {
            index: 25,
            name: "Ira de Guerra",
            ranks: 1,
			desc: "Asalto no tiene reactivación mientras Apoyo Divino está activo, pero la duración del efecto de aturdir que causa se reduce a 1 segundo.",
            rankInfo: [],
			parent: 14,
        },
        {
            index: 26,
            name: "Golpe de Trueno",
            ranks: 2,
			desc: "Cuchillada de Trueno aturde al objetivo por <span class='tooltip-value'>#</span> segundo(s) cuando asesta un golpe Crítico.",
            rankInfo: ['1-2', '2-3'],
			parent: 15,
        },
        {
            index: 28,
            name: "Frenesí Rápido",
            ranks: 2,
			desc: "Reduce las reutilizaciones de Choque Precipitado, Poder de Dragón, y Espada de Reflexión en <span class='tooltip-value'>#%</span> mientras se está en Postura de Frenesí.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
        },
        {
            index: 29,
            name: "Alma de Dragón",
            ranks: 2,
			desc: "Poder de Dragón aumenta el Ataque base del objetivo en un <span class='tooltip-value'>#%</span> adicional.",
            rankInfo: [3, 6],
        },
        {
            index: 30,
            name: "Espada de Reflexión",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: 90 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nCuando eres alcanzado por un ataque directo, mientras que la habilidad está activa, lanzas un contraataque, que inflige un daño igual a 100% de tu Ataque base, e ignora Defensa y Resistencias. Este efecto dura <span class='tooltip-value'>#</span> segundos y no se ve afectado por efectos controladores.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [213, 265],
            rankInfo3: [12, 15],
        },
        {
            index: 31,
            name: "Brote de Frenesí",
            ranks: 2,
			desc: "Las sanciones de Evasión y Defensa causadas por Postura de Frenesí son reducidas en <span class='tooltip-value'>#%</span>.",
            rankInfo: [25, 50],
        },
        {
            index: 33,
            name: "Dominio de Empapado de sangre",
            ranks: 2,
			ranksnw: 1,
			desc: "Aumenta la duración de Empapado de sangre en <span class='tooltip-value'>#</span> segundos y su posibilidad de desmontar el objetivo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10],
            rankInfo2: [5, 10],
        },
        {
            index: 35,
            name: "Fuerza Frenética",
            ranks: 2,
			desc: "Aumenta el daño extra de Embate, Cuchillada de Rayo, y Cuchillada de Trueno en <span class='tooltip-value'>#%</span> mientras se está en Postura de Frenesí.",
            rankInfo: [8, 16],
        },
        {
            index: 38,
            name: "Contra Maestro",
            ranks: 3,
			desc: "Aumenta la duración de Espada de Reflexión en <span class='tooltip-value'>#</span> segundo(s) y el daño del contraataque en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2, 3],
            rankInfo2: [20, 40, 60],
			parent: 20,
        },
        {
            index: 39,
            name: "Rayo Veloz",
            ranks: 3,
			desc: "Reduce la reactivación de Alas de Rayo en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15],
        },
        {
            index: 41,
            name: "Lluvia de Sangre",
            ranks: 3,
			desc: "Reduce la Defensa de los objetivos afectados por Empapado de sangre en <span class='tooltip-value'>#%</span> y su Evasión en <span class='tooltip-value'>#</span>. Aumenta el alcance de Empapado de Sangre en <span class='tooltip-value'>#</span> metros.",
            rankInfo: [5, 10, 15],
            rankInfo2: [15, 30, 45],
            rankInfo3: [2, 4, 6],
			parent: 22,
        },
        {
            index: 43,
            name: "Devoración Embravecida",
            ranks: 2,
			desc: "Reduce la reactivación de Devorar el Alma en <span class='tooltip-value'>#</span> segundos. Tienes un <span class='tooltip-value'>#%</span> de posibilidad de resistir efectos lentos mientras Devorar el Alma está activo. Este efecto termina después de un ataque exitoso.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30],
			rankInfo2: [50, 100],
        },
        {
            index: 46,
            name: "Ciclón de Espadas",
            ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>396 Maná</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>El daño de viento</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Corto Alcance</span>\n\nRequiere Postura de Frenesí. Ataca hasta 10 objetivos a menos de 7 metros en un arco de 120 grados. Golpea 3 veces. Cada golpe inflige 50% de tu Ataque base más 1067 de daño extra. La Precisión es aumentada con un Dominio del Viento superior. El primer golpe tiene un 25% de posibilidad de reducir la velocidad de movimiento del objetivo en un 50% por 5 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ]
];