var data = [
	// one
	[
		{
			index: 2,
			name: "Mysterious Spike",
			ranks: 5,
			desc: "Increases the bonus damage of Assassinate by <span class='tooltip-value'>#%</span> and grants it a <span class='tooltip-value'>#%</span> chance to generate an Agony Orb.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 3,
			name: "Strike of Pain",
			ranks: 5,
			desc: "Increases the effect of Agony Orbs on Nightmare Termination by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the effect of Agony Orbs on Nightmare Termination by <span class="tooltip-value">120%</span>.</div>'],
		},
		{
			index: 5,
			name: "Sudden Strike",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the base damage of Thrust of Pain by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the base damage of Thrust of Pain by <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 7,
			name: "Wolf Shadow",
			ranks: 3,
			desc: "Finisher skills have a <span class='tooltip-value'>#%</span> rate to trigger Agony Orb effects without consuming Agony Orbs. Agony Orbs are consumed normally while in Werewolf state.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Finisher skills have a <span class="tooltip-value">60%</span> rate to trigger Agony Orb effects without consuming Agony Orbs. Agony Orbs are consumed normally while in Werewolf state.</div>'],
		},
		{
			index: 8,
			name: "Killer of Darkness",
			ranks: 4,
			desc: "Increases your Dark Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 9,
			name: "Hurried Pain",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduces the cooldown of Thrust of Pain by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Thrust of Pain by <span class="tooltip-value">2.5</span> second(s).</div>'],
			parent: 2,
		},
		{
			index: 10,
			name: "Lurking Sting",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Dark damage</span><span class='right'>Cooldown: 8 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nStrikes the target twice. Each hit deals 75% damage plus <span class='tooltip-value'>#</span> bonus damage. The first attack Crit Chance is increased by 2% and the second by 4%. Generates one Agony Orb.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [179, 262, 346, 431],
			rankInfo3: [801, 1418, 2024, 2619],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">517</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Dark damage</span><span class="right">Cooldown: 8 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Short Range</span>\n\n<br><br>Strikes the target twice. Each hit deals 75% damage plus <span class="tooltip-value">3204</span> bonus damage. The first attack Crit Chance is increased by 2% and the second by 4%. Generates one Agony Orb.</div>'],
		},
		{
			index: 11,
			name: "Shadow Evasion",
			ranks: 2,
			desc: "Increases the duration of the Evasion bonus from Shadow Protection by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of the Evasion bonus from Shadow Protection by <span class="tooltip-value">4</span> seconds.</div>'],
		},
		{
			index: 13,
			name: "Dual Stings",
			ranks: 3,
			desc: "Thrust of Pain has a <span class='tooltip-value'>#%</span> chance to generate an additional Agony Orb.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [9, 18, 27],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Thrust of Pain has a <span class="tooltip-value">36%</span> chance to generate an additional Agony Orb.</div>'],
			parent: 5,
		},
		{
			index: 14,
			name: "Advanced Lurking Sting",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduces the cooldown of Lurking Sting by <span class='tooltip-value'>#</span> second(s) and increases its Accuracy by <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			parent: 6,
		},
		{
			index: 16,
			name: "Toxic Strike",
			ranks: 2,
			desc: "Nightmare Termination reduces the Defense of targets that are not at full Health by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 15],
		},
		{
			index: 17,
			name: "Pain Strike",
			ranks: 3,
			desc: "Reduces the cooldown of Pitch by <span class='tooltip-value'>#</span> seconds and increases its base damage by <span class='tooltip-value'>#%</span>. Each Agony Orb increases the base damage of Pitch by an additional <span class='tooltip-value'>#%</span>. At Rank 3, it also silences the target for 1 second if you have 3 Agony Orbs.",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: [5, 10, 15],
		},
		{
			index: 19,
			name: "Pain Amplification",
			ranks: 3,
			desc: "Each Agony Orb increases your Attack by an additional <span class='tooltip-value'>#</span>. Increases the duration of Agony Orbs by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [3, 6, 9],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Each Agony Orb increases your Attack by an additional <span class="tooltip-value">40</span>. Increases the duration of Agony Orbs by <span class="tooltip-value">12</span> seconds.</div>'],
		},
		{
			index: 20,
			name: "Art of Darkness",
			ranks: 3,
			desc: "Reduces the Mana costs of your offensive Dark skills by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 21,
			name: "Advanced Blade of Hypnosis",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduces the cooldown of Blade of Hypnosis by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 22,
			name: "Lurking Impact",
			ranks: 3,
			desc: "Increases the base damage of Lurking Sting by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			parent: 9,
		},
		{
			index: 23,
			name: "Darkness Poison",
			ranks: 3,
			desc: "Your Dark attacks have a <span class='tooltip-value'>#%</span> chance to poison the target, which drains <span class='tooltip-value'>#</span> Health each second and reduces its movement speed by 10% for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [60, 80, 100],
			rankInfo2: [50, 70, 90],
			rankInfo3: [4, 5, 5],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Your Dark attacks have a <span class="tooltip-value">100%</span> chance to poison the target, which drains <span class="tooltip-value">90</span> Health each second and reduces its movement speed by <span class="tooltip-value">15%</span> for <span class="tooltip-value">5</span> seconds.</div>'],
		},
		{
			index: 25,
			name: "Hypnosis Theory",
			ranks: 1,
			desc: "Blade of Hypnosis is effective against all monsters.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 26,
			name: "Amplified Endings",
			ranks: 2,
			desc: "Increases the base damage of your Finisher skills by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 28,
			name: "Strength Fortification",
			ranks: 4,
			desc: "Increases your base Attack by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 29,
			name: "Offense Break",
			ranks: 2,
			desc: "Thrust of Pain, Lurking Sting and Mutilation reduce target's attack by <span class='tooltip-value'>#%</span>, lasts for 8 seconds, lands Crit has a <span class='tooltip-value'>#%</span> to silence target for 3 seconds.",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
		},
		{
			index: 30,
			name: "Secret Art - Agony",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: <span class='tooltip-value'>#</span> seconds.</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nResets the cooldowns of Lurking Sting and Thrust of Pain and generates 2 Agony Orbs.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [333, 408],
			rankInfo3: [60, 45],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">488</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: <span class="tooltip-value">30</span> seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Resets the cooldowns of Lurking Sting and Thrust of Pain and generates 2 Agony Orbs.</div>'],
		},
		{
			index: 31,
			name: "Intensified Nightmare",
			ranks: 2,
			desc: "Dark Nightmare reduces the target's Resistances by an additional <span class='tooltip-value'>#</span> and its duration is increased by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: [1, 2],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Dark Nightmare reduces the target\'s Resistances by an additional <span class="tooltip-value">60</span> and its duration is increased by <span class="tooltip-value">3</span> second(s).</div>'],
		},
		{
			index: 34,
			name: "Advanced Art - Agony",
			ranks: 2,
			desc: "Secret Art - Agony has a <span class='tooltip-value'>#%</span> chance to generate an additional Agony Orb. Reduces its cooldown by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [40, 80],
			rankInfo2: [5, 10],
			parent: 21,
		},
		{
			index: 35,
			name: "Agony Manipulation",
			ranks: 3,
			desc: "Vicious Intention consumes Agony Orbs to increase your Defense and Evasion for <span class='tooltip-value'>#</span> seconds. With 0/1/2/3/4 Agony Orbs, your Defense is increased by <span class='tooltip-value'>#</span> and your Evasion by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: ['10/20/30/40/50', '20/30/40/50/60', '30/40/50/60/70'],
			rankInfo3: ['2/4/6/8/10', '4/6/8/10/12', '6/8/10/12/14'],
		},
		{
			index: 38,
			name: "Seed of Agony",
			ranks: 2,
			desc: "Your Finisher skills inflict the Seed of Agony effect on the target, which causes it to lose Health each time it attacks. Consumes 0/1/2/3/4 Agony Orbs to deal damage equal to <span class='tooltip-value'>#</span> of the target's current Health. This effect lasts for 10 seconds and can be triggered up to 3 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['2%/3%/4%/5%/6%', '4%/5%/6%/7%/8%'],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Your Finisher skills inflict the Seed of Agony effect on the target, which causes it to lose Health each time it attacks. Consumes 0/1/2/3/4 Agony Orbs to deal damage equal to <span class="tooltip-value">6%/7%/8%/9%/10%</span> of the target\'s current Health. This effect lasts for 10 seconds and can be triggered up to 3 times.</div>'],
		},
		{
			index: 39,
			name: "Night Hunter",
			ranks: 3,
			desc: "Increases an additional damage of Dark attack skills by <span class='tooltip-value'>#%</span>. Reduces the target's Masteries by <span class='tooltip-value'>#</span> points when you use a Dark attack while in Werewolf state, lasts for 10 seconds Has a <span class='tooltip-value'>#%</span> chance to extend your Transform time by 1 second.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
			rankInfo3: [10, 20, 30],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases an additional damage of Dark attack skills by <span class="tooltip-value">40%</span>. Reduces the target\'s Masteries by <span class="tooltip-value">60</span> points when you use a Dark attack while in Werewolf state, lasts for 10 seconds Has a <span class="tooltip-value">40%</span> chance to extend your Transform time by 1 second.</div>'],
		},
		{
			index: 42,
			name: "Venomous Blade",
			ranks: 3,
			desc: "Flair and Mutilation have a chance to poison the target for 10 seconds. The poison increases the damage dealt by bleed effects by 20%, and slows the target by <span class='tooltip-value'>#%</span>. With 0/1/2/3/4 Agony Orbs, this skill has a <span class='tooltip-value'>#</span> chance to occur.",
			rankInfo: [15, 30, 45],
			rankInfo2: ['10%/20%/30%/40%/50%', '20%/30%/40%/50%/60%', '30%/40%/50%/60%/70%'],
		},
		{
			index: 43,
			name: "Abomination",
			ranks: 3,
			desc: "Your finisher skills treat <span class='tooltip-value'>#</span> Blast Orbs as if they were Agony Orbs. At rank 3, the effect of the Blast Orbs is not reduced.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 46,
			name: "Mutilation",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>604 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Dark damage</span><span class='right'>No cooldown</span>\n<span class='left'>Multi-target attack</span><span class='right'>Short Range</span>\n\nFinisher skills have a chance to enable you to use Mutilation based on Agony Orbs or Blast Orbs. 0/1/2/3/4 Agony Orbs have a 10%/40%/70%/100%/100% chance to enable the use of this skill. Lasts for 45 seconds. This effect disappears after you use Mutilation once. Strikes up to 18 targets four times in a 90 degree arc. Each strike gains an additional 2% Crit Chance. Each strike deals 85% of your Attack plus 1219 bonus damage, the last strike cause. The target loses 1% of its max Health per second, and is slowed by 20% for 10 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Extended Agony",
			ranks: 4,
			desc: "Mutilation's Crit Chance is increased by <span class='tooltip-value'>#%</span>, the last attack of Mutilation has a <span class='tooltip-value'>#%</span> chance to generate 1 additional Agony Orb and Blast Orb.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [25, 50, 75, 100],
			parent: 29,
		},
		{
			index: 49,
			name: "Torment",
			ranks: 3,
			desc: "While Vicious Intention is active, each Agony Orb increases your Dark Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 51,
			name: "Magic Amplifier",
			ranks: 2,
			desc: "For 10 seconds after using Secret Art - Agony, your Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 54,
			name: "Serene",
			ranks: 1,
			desc: "Increases Mutilation's additional Crit Damage by 40% and Base Attack bonus by 20%. Has a 50% chance to recast.",
			rankInfo: [],
			parent: 29,
		},
	],
		// two
	[
		{
			index: 2,
			name: "Final Seal",
			ranks: 5,
			desc: "When Blast Orbs are consumed by Nightmare Termination, the target's Attack is reduced by an additional <span class='tooltip-value'>#</span> per Orb.",
			rankInfo: [20, 40, 60, 80, 100],
		},
		{
			index: 3,
			name: "Seal Thorn",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases the bonus damage of Assassinate by <span class='tooltip-value'>#%</span> and gives it a <span class='tooltip-value'>#%</span> chance to generate one Blast Orb.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 5,
			name: "Dark Shadow",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the base damage of Throat Seal by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 6,
			name: "Speed Seal",
			ranks: 2,
			desc: "Increases the slow effect of Nightmare Termination caused by Blast Orbs by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 80],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the slow effect of Nightmare Termination caused by Blast Orbs by <span class="tooltip-value">120%</span>.</div>'],
		},
		{
			index: 8,
			name: "Keen Eye",
			ranks: 4,
			desc: "Increases your Physical Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 9,
			name: "Feral Cruelty",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduces the cooldown of Throat Seal by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Throat Seal by <span class="tooltip-value">2.5</span> second(s).</div>'],
			parent: 2,
		},
		{
			index: 10,
			name: "Gouge",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Physical damage</span><span class='right'>Cooldown: 8 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nStrikes the target twice. Each hit deals 75% of your Attack plus <span class='tooltip-value'>#</span> bonus damage. The first attack Crit Chance is increased by 2% and the second by 4%. Generates one Blast Orb.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [179, 262, 346, 431],
			rankInfo3: [801, 1418, 2024, 2619],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">517</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Physical damage</span><span class="right">Cooldown: 8 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Short Range</span>\n\n<br><br>Strikes the target twice. Each hit deals 75% of your Attack plus <span class="tooltip-value">3204</span> bonus damage. The first attack Crit Chance is increased by 2% and the second by 4%. Generates one Blast Orb.</div>'],
		},
		{
			index: 11,
			name: "Thrust",
			ranks: 3,
			desc: "Increases the Crit Chance of Assassinate by <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 7, 10],
			parent: 1,
		},
		{
			index: 13,
			name: "Drastic Banish",
			ranks: 3,
			desc: "Throat Seal gains a <span class='tooltip-value'>#%</span> chance to generate an additional Blast Orb.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [8, 16, 24],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Throat Seal gains a <span class="tooltip-value">32%</span> chance to generate an additional Blast Orb.</div>'],
			parent: 5,
		},
		{
			index: 15,
			name: "Hunting Mania",
			ranks: 3,
			desc: "Adds to your speed increase by <span class='tooltip-value'>#%</span> during Deadly Chaser. Extends the Transform time by <span class='tooltip-value'>#</span> seconds when used in Werewolf state.",
			rankInfo: [8, 16, 24],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 16,
			name: "Edge Strike",
			ranks: 3,
			desc: "Increases the Accuracy of your offensive Physical skills by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Broken Shadow Strike",
			ranks: 2,
			desc: "Increases your Crit Chance by <span class='tooltip-value'>#%</span> while stealthed.",
			rankInfo: [20, 40],
		},
		{
			index: 18,
			name: "Advanced Gouge",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the Crit Chance of both attacks of Gouge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
			parent: 6,
		},
		{
			index: 19,
			name: "Seal Knowledge",
			ranks: 3,
			desc: "Each Blast Orb increases your Crit damage by an additional <span class='tooltip-value'>#%</span>. Increases the duration of Blast Orbs by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [3, 6, 9],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Each Blast Orb increases your Crit damage by an additional <span class="tooltip-value">4%</span>. Increases the duration of Blast Orbs by <span class="tooltip-value">12</span> seconds.</div>'],
		},
		{
			index: 21,
			name: "Hypnotic Aggravation",
			ranks: 3,
			desc: "Blade of Hypnosis silences target for <span class='tooltip-value'>#</span> seconds or until the target takes 3 hits.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Blade of Hypnosis silences target for <span class="tooltip-value">8</span> seconds or until the target takes 3 hits.</div>'],
		},
		{
			index: 22,
			name: "Sharpened Blade",
			ranks: 3,
			desc: "Increases the base damage of Gouge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			parent: 12,
		},
		{
			index: 23,
			name: "Wound Infliction",
			ranks: 3,
			desc: "Your Finisher skills gain a <span class='tooltip-value'>#%</span> chance to inflict a wound effect on the target, which causes 0/1/2/3/4 Blast Orbs to increase your Crit Chance against the target by 1%/2%/3%/4%/5% for 10 seconds.",
			rankInfo: [60, 80, 100],
		},
		{
			index: 26,
			name: "Bull's Eye",
			ranks: 3,
			desc: "When Throat Seal or Gouge land a successful crit, the target is stunned for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: ['0-1', '1-2', '2-3'],
		},
		{
			index: 28,
			name: "Ruthlessness",
			ranks: 3,
			desc: "Increases your Crit Damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 29,
			name: "Dust Seal",
			ranks: 2,
			desc: "Increases the duration of Dark Nightmare's silence effect by <span class='tooltip-value'>#</span> second(s) and increases its base damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 30,
			name: "Secret Art - Blast",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: <span class='tooltip-value'>#</span> seconds.</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nResets the cooldowns of Throat Seal and Gouge and generates 2 Blast Orbs.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [333, 408],
			rankInfo3: [60, 45],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">488</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: <span class="tooltip-value">30</span> seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Resets the cooldowns of Throat Seal and Gouge and generates 2 Blast Orbs.</div>'],
		},
		{
			index: 31,
			name: "Sharp Claw",
			ranks: 2,			
			desc: "The Crit rate of each stack of Finisher skills is increased by <span class='tooltip-value'>#%</span>. The additional attack of Finisher skills is increased by <span class='tooltip-value'>#%</span> in Werewolf state.",
			rankInfo: [1.5, 3],
			rankInfo2: [15, 30],
		},
		{
			index: 33,
			name: "Swift Counter",
			ranks: 3,
			desc: "While you are slowed, Pitch slows the target by a rate equal to your movement speed reduction for <span class='tooltip-value'>#</span> seconds. Has a <span class='tooltip-value'>#%</span> chance to remove the slow effect on you.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 6, 8],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>While you are slowed, Pitch slows the target by a rate equal to your movement speed reduction for <span class="tooltip-value">10</span> seconds. Has a <span class="tooltip-value">40%</span> chance to remove the slow effect on you.</div>'],
		},
		{
			index: 34,
			name: "Advanced Art - Blast",
			ranks: 2,
			desc: "Secret Art - Blast has a <span class='tooltip-value'>#%</span> chance to generate an additional Blast Orb. 1 Reduces its cooldown by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [40, 80],
			rankInfo2: [5, 10],
			parent: 20,
		},
		{
			index: 37,
			name: "Shadow Spikes",
			ranks: 3,
			desc: "Flair. Mutilation, Imperiling Hack, and Shadow Bites have a chance to reduce the target's Evasion by <span class='tooltip-value'>#</span> and Max Health by <span class='tooltip-value'>#%</span> for 8 seconds. With 1/2/3/4 Blast Orbs, the chance for this effect to occur is 15%/30%/45%/60%.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Flair. Mutilation, Imperiling Hack, and Shadow Bites have a chance to reduce the target\'s Evasion by <span class="tooltip-value">60</span> and Max Health by <span class="tooltip-value">20%</span> for 8 seconds. With 1/2/3/4 Blast Orbs, the chance for this effect to occur is 15%/30%/45%/60%.</div>'],
		},
		{
			index: 38,
			name: "Intensified Aggression",
			ranks: 2,
			desc: "Increases the duration of Vicious Intention by <span class='tooltip-value'>#</span> seconds. If Assassinate, Throat Seal, or Gouge land a Crit while Vicious Intention is active, the target takes <span class='tooltip-value'>#%</span> additional damage from subsequent Physical and Dark attacks for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: [15, 30],
			rankInfo3: [7, 10],
			rankInfo4: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Vicious Intention by <span class="tooltip-value">6</span> seconds. If Assassinate, Throat Seal, or Gouge land a Crit while Vicious Intention is active, the target takes <span class="tooltip-value">45%</span> additional damage from subsequent Physical and Dark attacks for <span class="tooltip-value">13</span> seconds.</div>'],
		},
		{
			index: 41,
			name: "Embrace of Death",
			ranks: 3,
			desc: "Increases the durations of Shadowbreak and Deputy of Death by <span class='tooltip-value'>#</span> seconds. While Deputy of Death is active, the Accuracy of skills with multiple strikes is increased by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the durations of Shadowbreak and Deputy of Death by <span class="tooltip-value">8</span> seconds. While Deputy of Death is active, the Accuracy of skills with multiple strikes is increased by <span class="tooltip-value">40</span>.</div>'],
		},
		{
			index: 43,
			name: "Prohibition",
			ranks: 2,
			desc: "Throat Seal and Gouge have a chance to reduce the target's movement speed by <span class='tooltip-value'>#%</span> and its Accuracy by <span class='tooltip-value'>#</span> for 4 seconds. With 0/1/2/4 Blast Orbs, this effect has a <span class='tooltip-value'>#</span> chance to occur.",
			rankInfo: [25, 50],
			rankInfo2: [15, 30],
			rankInfo3: ['10%/20%/30%/40%/50%', '20%/30%/40%/50%/60%'],
		},
		{
			index: 46,
			name: "Imperiling Hack",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>559 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Physical damage</span><span class='right'>No cooldown</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nFinisher skills have a chance to enable you to use Imperiling Hack based on Agony Orbs or Blast Orbs. 0/1/2/3/4 Blast Orbs have a 10%-40%-70%-100%-100% chance to enable the use of this skill. Lasts for 45 seconds. This effect disappears after you use Imperiling Hack once. Strikes the target four times. Each hit's Crit damage is increased by 4%/6%/8%/10%, respectively, the last strike generates a point of Blast Orb. Each hit deals 80% of your base Attack, plus 1396 bonus damage.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Broken",
			ranks: 4,
			desc: "Each attack on the target of Imperiling Hack reduces the target's Evasion by <span class='tooltip-value'>#</span> and physical resistance by <span class='tooltip-value'>#</span>. Stacks 6 times, lasts 20 seconds.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [8, 16, 24, 32],
			parent: 28,
		},
		{
			index: 49,
			name: "Frenzied",
			ranks: 3,
			desc: "While using Finisher Skills (Dark Nightmare, Nightmare Termination), grants a <span class='tooltip-value'>#%</span> chance to increase your casting speed by 20% for the next 4 seconds.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 51,
			name: "Massacre Mastery",
			ranks: 2,
			desc: "While Deputy of Death is active, each effect increasing crit chance will also increase your crit damage by <span class='tooltip-value'>#%</span>. Duration of the effect is increased by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [3, 6],
			rankInfo2: [2, 4],
		},
		{
			index: 54,
			name: "Soul Dance",
			ranks: 1,
			desc: "Increases Imperiling Hack's additional Crit Chance by 10% and Base Attack bonus by 20%. Each strike of Imperiling Hack has a chance to trigger the Bull's Eye effect (needs to learn the talent first).",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Swift Stalk",
			ranks: 5,
			desc: "Reduces the cooldown of Stalking Shadow by <span class='tooltip-value'>#</span> seconds. Increases the Evasion bonus of Stalking Shadow by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [20, 40, 60, 80, 100],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Reduces the cooldown of Stalking Shadow by <span class="tooltip-value">18</span> seconds. Increases the Evasion bonus of Stalking Shadow by <span class="tooltip-value">120%</span>.</div>'],
		},
		{
			index: 4,
			name: "Ghost Shadow",
			ranks: 5,
			desc: "Increases your movement speed by <span class='tooltip-value'>#%</span> while Stalking Shadow is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [7.5, 15, 22.5, 30, 37.5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases your movement speed by <span class="tooltip-value">45%</span> while Stalking Shadow is active.</div>'],
		},
		{
			index: 5,
			name: "Throat Cut",
			ranks: 3,
			desc: "Increases the base damage of Throat Seal by <span class='tooltip-value'>#%</span> and grants it a <span class='tooltip-value'>#%</span> chance to trigger the Rapid Shadow effect. While Rapid Shadow is active, Throat Seal and Thrust of Pain have no cooldown. The Rapid Shadow effect ends after one use.",
			rankInfo: [8, 16, 24],
			rankInfo2: [6, 12, 18],
		},
		{
			index: 6,
			name: "Shadow Assassin",
			ranks: 3,
			desc: "Increases the Crit Chance of Thrust of Pain by <span class='tooltip-value'>#%</span> and gives it a <span class='tooltip-value'>#%</span> chance to trigger the Rapid Shadow effect. While you are affected by Rapid Shadow, Throat Seal and Thrust of Pain have no cooldown. Rapid Shadow lasts for 5 seconds and ends after one use.",
			rankInfo: [3, 6, 9],
			rankInfo2: [6, 12, 18],
		},
		{
			index: 7,
			name: "Assassination Mastery",
			ranks: 4,
			desc: "Throat Seal and Thrust of Pain drain the target's Mana by <span class='tooltip-value'>#%</span> and deals 50% of the amount drained as damage to the target. Note: this effect only applies to Player vs. Player combat.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 4, 5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Throat Seal and Thrust of Pain drain the target\'s Mana by <span class="tooltip-value">7%</span> and deals 50% of the amount drained as damage to the target. Note: this effect only applies to Player vs. Player combat.</div>'],
		},
		{
			index: 9,
			name: "Persistent Chase",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the range of Deadly Chaser by <span class='tooltip-value'>#</span> meter(s).",
			rankInfo: [1, 2, 3],
		},
		{
			index: 10,
			name: "Swift Evasion",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 300 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nIncreases your Evasion by <span class='tooltip-value'>#</span> and reduces Attack by <span class='tooltip-value'>#%</span>. Lasts for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [106, 151, 197, 243],
			rankInfo3: [210, 270, 330, 390],
			rankInfo4: [10, 8, 6, 4],
			rankInfo5: [12, 14, 16, 18],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">291</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 300 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases your Evasion by <span class="tooltip-value">450</span> and reduces Attack by <span class="tooltip-value">2%</span>. Lasts for <span class="tooltip-value">20</span> seconds.</div>'],
		},
		{
			index: 12,
			name: "Accuracy Boost",
			ranks: 4,
			desc: "Increases your Accuracy by <span class='tooltip-value'>#</span>.",
			rankInfo: [6, 12, 18, 24],
		},
		{
			index: 13,
			name: "Art of Hunting",
			ranks: 3,
			desc: "Reduces the cooldown of Deadly Chaser by <span class='tooltip-value'>#</span> seconds. It increases your movement speed by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Deadly Chaser by <span class="tooltip-value">12</span> seconds. It increases your movement speed by an additional <span class="tooltip-value">80%</span>.</div>'],
			parent: 5,
		},
		{
			index: 14,
			name: "Evasiveness",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduces the cooldown of Swift Evasion by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Swift Evasion by <span class="tooltip-value">80</span> seconds.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Advanced Shadow Protection",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduces the cooldown of Shadow Protection by <span class='tooltip-value'>#</span> seconds, and increases its duration by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [2, 4, 6, 8],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Shadow Protection by <span class="tooltip-value">75</span> seconds, and increases its duration by <span class="tooltip-value">10</span> seconds. <span class="tooltip-value">Dispels all controlling effects above Lv5.</span></div>'],
		},
		{
			index: 17,
			name: "Still Shadow",
			ranks: 2,
			desc: "Reduces the cooldown of Assassinate by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2],
		},
		{
			index: 18,
			name: "Speed Flash",
			ranks: 2,
			desc: "Swift Evasion increases your movement speed by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
			parent: 9,
		},
		{
			index: 20,
			name: "Rapid Attack",
			ranks: 3,
			desc: "Increases the chance that Thrust of Pain and Throat Seal will trigger the Rapid Shadow effect by <span class='tooltip-value'>#%</span> and increases the duration of Rapid Shadow <span class='tooltip-value'>#</span> second(s). While you are affected by Rapid Shadow, Throat Seal and Thrust of Pain have no cooldown. The Rapid Shadow effect ends after one use.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the chance that Thrust of Pain and Throat Seal will trigger the Rapid Shadow effect by <span class="tooltip-value">24%</span> and increases the duration of Rapid Shadow <span class="tooltip-value">4</span> second(s). While you are affected by Rapid Shadow, Throat Seal and Thrust of Pain have no cooldown. The Rapid Shadow effect ends after one use.</div>'],
		},
		{
			index: 21,
			name: "Swift Wind",
			ranks: 4,
			ranksnw: 3,
			desc: "The movement speed bonus granted by Shadow of Gale is increased by <span class='tooltip-value'>#%</span> and its duration is increased by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [0.5, 1, 1.5, 2],
		},
		{
			index: 22,
			name: "Sense of Motion",
			ranks: 1,
			desc: "Increases the Accuracy of all your skills with multiple attacks by 15.",
			rankInfo: [],
		},
		{
			index: 23,
			name: "Eyes of Shadow",
			ranks: 1,
			desc: "Shadow Protection generates one Agony Orb and one Blast Orb.",
			rankInfo: [],
			parent: 10,
		},
		{
			index: 25,
			name: "Wind Speed",
			ranks: 2,
			desc: "Reduces the cooldown of Shadow of Gale <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [10, 20],
			parent: 14,
		},
		{
			index: 26,
			name: "Speed of Darkness",
			ranks: 1,
			desc: "Rapid Shadow resets the cooldowns of your Finisher skills.",
			rankInfo: [],
		},
		{
			index: 28,
			name: "Shapeless",
			ranks: 4,
			desc: "Increases your Evasion by <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12, 16],
		},
		{
			index: 29,
			name: "Shadow Snare",
			ranks: 1,
			desc: "Deadly Chaser stuns the target for 2 seconds if the distance between you and the target is over 15 meters.",
			rankInfo: [],
		},
		{
			index: 30,
			name: "Moon step",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nDispels and grants immunity to ensnare and slow effects. Last  <span class='tooltip-value'>#</span> seconds. The cooldown is reduced by 30% when used in the Werewolf state.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [306, 376],
			rankInfo3: [2, 3],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">450</span> Mana</span><span class="right">Cast time: Instant</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 120 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Dispels and grants immunity to ensnare and slow effects. Last  <span class="tooltip-value">4</span> seconds. The cooldown is reduced by 30% when used in the Werewolf state.</div>'],
		},
		{
			index: 31,
			name: "Stealth Theory",
			ranks: 3,
			desc: "Increases the effects of Vicious Intention and Swift Evasion by <span class='tooltip-value'>#%</span> while you are stealthed. Increases the range of Blade of Hypnosis by <span class='tooltip-value'>#</span> meters.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [4, 8, 12],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the effects of Vicious Intention and Swift Evasion by <span class="tooltip-value">40%</span> while you are stealthed. Increases the range of Blade of Hypnosis by <span class="tooltip-value">16</span> meters.</div>'],
		},
		{
			index: 33,
			name: "Belief of Speed",
			ranks: 3,
			desc: "Each Agony Orb and Blast Orb increases your movement speed by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Each Agony Orb and Blast Orb increases your movement speed by <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 35,
			name: "Focused Maneuver",
			ranks: 3,
			desc: "Focused Maneuver is triggered each time you enter stealth or gain a bonus to your movement speed. Focused Maneuver increases your Accuracy by <span class='tooltip-value'>#</span> and your Evasion by <span class='tooltip-value'>#</span> for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: [6, 12, 18],
			rankInfo3: [9, 12, 15],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Focused Maneuver is triggered each time you enter stealth or gain a bonus to your movement speed. Focused Maneuver increases your Accuracy by <span class="tooltip-value">60</span> and your Evasion by <span class="tooltip-value">24</span> for <span class="tooltip-value">18</span> seconds.</div>'],
		},
		{
			index: 37,
			name: "Deathblow Mastery",
			ranks: 2,
			desc: "Reduces the cooldowns of your Finisher skills by <span class='tooltip-value'>#</span> second(s) and increases their base damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 38,
			name: "Improved Moon Step",
			ranks: 2,
			desc: "The cooldown of Moon Step is reduced by <span class='tooltip-value'>#</span> seconds, the duration of immunity is increased by <span class='tooltip-value'>#</span> seconds Moon Step increases your movement by 50%.",
			rankInfo: [15, 30],
			rankInfo2: [1, 2],
			parent: 21,
		},
		{
			index: 40,
			name: "Relentless Quality",
			ranks: 3,
			desc: "Increases your Crit Chance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 42,
			name: "Phased Action",
			ranks: 3,
			desc: "If you evade 5 attacks while Swift Evasion is active, an enhanced stealth state is triggered. Stealth does not end when you attack or are attacked for <span class='tooltip-value'>#</span> seconds or until you are struck by 4 attacks. The time between two successful evasions must not exceed 2 seconds.",
			rankInfo: [3, 4, 5],
		},
		{
			index: 43,
			name: "Covert Stalker",
			ranks: 2,
			desc: "The bonus damage of Assassinate, Thrust of Pain, Throat Seal and Pitch is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
		},
		{
			index: 46,
			name: "Shadow Bites",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>489 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Dark damage</span><span class='right'>Cooldown: 10 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nRequires you to be stealthed. Strikes the target three times. Each hit deals 80% of your base Attack plus 1680 bonus damage, and has a 30% chance to silence the target for 3 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Shadow Dance",
			ranks: 4,
			desc: "Increases the chance for Shadow Bites to trigger the Silence effect by <span class='tooltip-value'>#%</span> and increases Shadow Bites' Base Attack by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [5, 10, 15, 20],
			parent: 30,
		},
		{
			index: 49,
			name: "Shadow",
			ranks: 3,
			desc: "Deadly Chaser's casting distance is increased by <span class='tooltip-value'>#</span> meters. The duration of the initial (100%) Slow effect is increased by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [1, 2, 3],
			rankInfo2: [0.5, 1, 1.5],
		},
		{
			index: 51,
			name: "Agility",
			ranks: 2,
			desc: "While Vicious Intention is active, your movement and riding speed are increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 54,
			name: "Dark Shadow",
			ranks: 1,
			desc: "Using Shadow Bites or Sneak Attack will grant the Swift Dark effect (Movement Speed increased by 100%, cooldowns removed from Thrust of Pain and Throat Seal. Lasts 10 seconds).",
			rankInfo: [],
			parent: 30,
		},
	]
];