var data = [
	// one
	[
		{
			index: 1,
			name: "Sabotage",
			ranks: 5,
			desc: "Bash gains a 50% chance to reduce the target's Defense by <span class='tooltip-value'>#</span> for 20 seconds. Each stack of Combat Stance increases the chance for this effect to occur by 20%. Stacks 3 times. At Rank 5, each stack reduces the target's Defense by an additional 1%.",
			rankInfo: [5, 10, 15, 20, 25],
		},
		{
			index: 3,
			name: "Battle Maniac",
			ranks: 5,
			desc: "Combat Stance increases your base Defense by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [0.9, 1.8, 2.7, 3.6, 4.5],
			rankInfo2: [9, 18, 27, 36, 45],
		},
		{
			index: 5,
			name: "Lightning Fury",
			ranks: 3,
			desc: "Increases the bonus damage of both hits of Lightning Slash by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 7,
			name: "Warsong of Agility",
			ranks: 5,
			ranksnw: 2,
			desc: "War Cry increases your Defense by an additional <span class='tooltip-value'>#</span> and your Evasion by <span class='tooltip-value'>#</span>. Increases your base Defense by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: [0.5, 1, 1.5, 2, 2.5],
			rankInfo4: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>War Cry increases your Defense by an additional <span class="tooltip-value">18</span> and your Evasion by <span class="tooltip-value">6</span>. Increases your base Defense by <span class="tooltip-value">3%</span>.</div>'],
		},
		{
			index: 8,
			name: "Contempt",
			ranks: 3,
			desc: "Increases the amount of threat generated from bonus damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Crushing Roar",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Physical</span><span class='right'>Cooldown: 10 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: None</span>\n\nEnemies within 10 meters have their Accuracy reduced by <span class='tooltip-value'>#</span> and their Attack reduced by <span class='tooltip-value'>#</span>. Deal high Threat to enemies lasts for 15 seconds. In addition, it will deal <span class='tooltip-value'>#%</span> base Attack damage and reveal stealthed enemies Using Sword Cyclone and Lightning Wings within 5 seconds of Crushing Roar will not generate any cooldown and will produce extremely high Threat However, base Attack bonus will be decreased by 50%, and will not generate Ensnare. Disarm or Interrupt effects.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [104, 148, 193, 239],
			rankInfo3: [20, 30, 40, 50],
			rankInfo4: [20, 40, 60, 80],
			rankInfo5: [20, 30, 40, 50],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">286</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Physical</span><span class="right">Cooldown: 10 seconds</span>\n<br><span class="left">Multi-target curse</span><span class="right">Range: None</span>\n\n<br><br>Enemies within 10 meters have their Accuracy reduced by <span class="tooltip-value">60</span> and their Attack reduced by <span class="tooltip-value">100</span>. Deal high Threat to enemies lasts for 15 seconds. In addition, it will deal <span class="tooltip-value">60%</span> base Attack damage and reveal stealthed enemies Using Sword Cyclone and Lightning Wings within 5 seconds of Crushing Roar will not generate any cooldown and will produce extremely high Threat However, base Attack bonus will be decreased by 50%, and will not generate Ensnare. Disarm or Interrupt effects.</div>'],
		},
		{
			index: 10,
			name: "Comprehension of War",
			ranks: 4,
			desc: "Reduces the cooldown of Divine Uphold by <span class='tooltip-value'>#</span> seconds. If your Health drops below 50% while Divine Uphold is active, the Defense bonus is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Divine Uphold by <span class="tooltip-value">75</span> seconds. If your Health drops below 50% while Divine Uphold is active, the Defense bonus is increased by <span class="tooltip-value">50%</span>.</div>'],
		},
		{
			index: 12,
			name: "Toughness",
			ranks: 4,
			desc: "Increases your max Health by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 13,
			name: "Gut Crush",
			ranks: 3,
			desc: "The duration of Crushing Roar is increased by <span class='tooltip-value'>#</span> second(s), and it gains a <span class='tooltip-value'>#%</span> chance to interrupt an enemy's casting. Cooldown is decreased by 2 second(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			parent: 5,
		},
		{
			index: 14,
			name: "Exorcism Breeze",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases the bonus damage of Evil Ward by <span class='tooltip-value'>#%</span> and reduces the target's Wind Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 16,
			name: "Storm Withstand",
			ranks: 3,
			desc: "Increases your Wind Resistance by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases your Wind Resistance by <span class="tooltip-value">60</span>.</div>'],
		},
		{
			index: 18,
			name: "Fading Corruption",
			ranks: 4,
			desc: "Evil Ward has a <span class='tooltip-value'>#%</span> chance to taunt the target for 2 seconds. The range is increased by <span class='tooltip-value'>#</span> meter(s). In Combat Stances, has a <span class='tooltip-value'>#%</span> chance to dispell the last Defense and assistant buff state. The rate is reduced by half in non-combat stance.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: [20, 40, 60, 80],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Evil Ward has a <span class="tooltip-value">100%</span> chance to taunt the target for 2 seconds. The range is increased by <span class="tooltip-value">5</span> meter(s). In Combat Stances, has a <span class="tooltip-value">100%</span> chance to dispell the last Defense and assistant buff state. The rate is reduced by half in non-combat stance.</div>'],
			parent: 9,
		},
		{
			index: 20,
			name: "Defense Fortify",
			ranks: 3,
			desc: "Increases your Physical Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 21,
			name: "Art of Surviving",
			ranks: 3,
			desc: "Reduces the Mana costs of War Cry, Combat Stance, Crushing Roar, and Threatening Roar by <span class='tooltip-value'>#%</span>. Increases the duration of Divine Uphold by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the Mana costs of War Cry, Combat Stance, Crushing Roar, and Threatening Roar by <span class="tooltip-value">60%</span>. Increases the duration of Divine Uphold by <span class="tooltip-value">8</span> seconds.</div>'],
		},
		{
			index: 23,
			name: "Combat Specialist",
			ranks: 2,
			desc: "Combat Stance reduces incoming damage by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Combat Stance reduces incoming damage by <span class="tooltip-value">9%</span>.</div>'],
			parent: 3,
		},
		{
			index: 25,
			name: "Fountain of Strength",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the duration of Dragon Power by <span class='tooltip-value'>#</span> minutes.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Art of Sortie",
			ranks: 2,
			desc: "Reduces the minimum range of Assault by <span class='tooltip-value'>#%</span> and increases the amount of threat it generates while you are in Combat Stance.",
			rankInfo: [50, 100],
		},
		{
			index: 27,
			name: "Awaken",
			ranks: 2,
			desc: "Reduces the Attack penalty caused by Combat Stance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 29,
			name: "Dragon Blood",
			ranks: 2,
			desc: "Dragon Power increases the target's max Health by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Dragon Power increases the target\'s max Health by <span class="tooltip-value">9%</span>.</div>'],
			parent: 15,
		},
		{
			index: 30,
			name: "Life Guardian",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 3 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 180 seconds</span>\n<span class='left'>Multi-target blessing</span><span class='right'>Range: None</span>\n\nRestores and increases the max Health of an ally within 16 meters by <span class='tooltip-value'>#%</span>. Increases your max Health by 5%. Lasts for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [223, 277],
			rankInfo3: [15, 16],
			rankInfo4: [25, 30],
			rankInfo5: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">335</span> Mana</span><span class="right">Cast time: 3 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 180 seconds</span>\n<br><span class="left">Multi-target blessing</span><span class="right">Range: None</span>\n\n<br><br>Restores and increases the max Health of an ally within 16 meters by <span class="tooltip-value">17%</span>. Increases your max Health by 5%. Lasts for <span class="tooltip-value">35</span> seconds.</div>'],
		},
		{
			index: 31,
			name: "Guard Break",
			ranks: 2,
			desc: "The Thunder effect caused by Thunder Slash reduces the target's Crit Dodge by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>The Thunder effect caused by Thunder Slash reduces the target\'s Crit Dodge by <span class="tooltip-value">3%</span>.</div>'],
		},
		{
			index: 35,
			name: "Blood Will",
			ranks: 2,
			desc: "Reduces the amount of Health lost while Blood Soak is active by <span class='tooltip-value'>#%</span>. Reduces the Mana cost of Blood Soak by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50],
			rankInfo2: [25, 50],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the amount of Health lost while Blood Soak is active by <span class="tooltip-value">75%</span>. Reduces the Mana cost of Blood Soak by <span class="tooltip-value">75%</span>.</div>'],
		},
		{
			index: 36,
			name: "Combat Defense",
			ranks: 3,
			desc: "Increases your base Defense by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [15, 25, 40],
		},
		{
			index: 38,
			name: "Hope",
			ranks: 3,
			ranksnw: 1,
			desc: "Reduces the cooldown of Life Guardian by <span class='tooltip-value'>#</span> seconds. While Life Guardian is active, each hit you take restores <span class='tooltip-value'>#%</span> of your max Health.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: [2, 5, 8],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Life Guardian by <span class="tooltip-value">80</span> seconds. While Life Guardian is active, each hit you take restores <span class="tooltip-value">11%</span> of your max Health.</div>'],
			parent: 19,
		},
		{
			index: 39,
			name: "Morale Decay",
			ranks: 2,
			desc: "Lightning Wings gains a 75% chance to reduce the target's Attack by <span class='tooltip-value'>#%</span> for 15 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Lightning Wings gains a 75% chance to reduce the target\'s Attack by <span class="tooltip-value">30%</span> for 15 seconds.</div>'],
		},
		{
			index: 42,
			name: "Concentration",
			ranks: 2,
			desc: "While Life Guardian is active, the effectiveness of healing skills cast on you is increased by <span class='tooltip-value'>#%</span>, and you cannot be interrupted while casting.",
			rankInfo: [20, 40],
			parent: 23,
		},
		{
			index: 43,
			name: "Choir of Thunder",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the base damage of Lightning Slash, Thunder Slash, and Raging Shock by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 47,
			name: "Raging Shock",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>301 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Wind damage</span><span class='right'>Cooldown: 6 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nDeals 100% of your Attack plus 2193 bonus damage. Requires Combat Stance. Reduces the target's Masteries by 300 for its next 2 attacks. Lasts for 8 seconds. Generates a large amount of threat.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
			parent: 26,
		},
		{
			index: 48,
			name: "Rage Blast",
			ranks: 4,
			desc: "Threat generated by Raging Shock is increased by <span class='tooltip-value'>#%</span>. Mastery reduction is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60, 80],
			rankInfo2: [10, 20, 30, 40],
			parent: 27,
		},
		{
			index: 50,
			name: "Die Hard",
			ranks: 2,
			desc: "While Combat Stance is active, every hit you receive will recover <span class='tooltip-value'>#%</span> of your lost Health (3 second cooldown).",
			rankInfo: [2, 4],
		},
		{
			index: 52,
			name: "Will of the Warrior",
			ranks: 3,
			desc: "Threat generated by Sword Cyclone is slightly increased. While Combat Stance is active, Tenacity is increased by <span class='tooltip-value'>#</span> (PVE only).",
			rankInfo: [33, 66, 99],
		},
		{
			index: 55,
			name: "Damnation",
			ranks: 1,
			desc: "Raging Shock increases your Tenacity by 50 for 10 seconds, stacks 8 times (PvE Only).",
			rankInfo: [],
			parent: 27,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Storm Attack",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases the bonus damage of Bash by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#%</span> of your Physical Mastery.",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 2,
			name: "Charge",
			ranks: 2,
			desc: "Reduces the minimum range of Assault by <span class='tooltip-value'>#</span> meter(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the minimum range of Assault by <span class="tooltip-value">3</span> meter(s).</div>'],
		},
		{
			index: 3,
			name: "Code of Sortie",
			ranks: 3,
			desc: "Reduces the cooldown of Assault by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Assault by <span class="tooltip-value">4</span> second(s).</div>'],
		},
		{
			index: 5,
			name: "Cleave",
			ranks: 3,
			desc: "Increases the Crit Chance of Bash by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the Crit Chance of Bash by <span class="tooltip-value">8%</span>.</div>'],
			parent: [0],
		},
		{
			index: 6,
			name: "Storm Song",
			ranks: 4,
			desc: "War Cry increases your Wind and Physical Masteries by an additional <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 7,
			name: "Lightning Bog",
			ranks: 3,
			desc: "Increases the chance for second hit of Lightning Slash to slow the target by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 9,
			name: "Crimson Arc",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Physical damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nStrikes the target twice. Each hit deals 90% of your base Attack plus <span class='tooltip-value'>#</span> bonus damage and has a 25% chance to inflict a bleed effect that deals <span class='tooltip-value'>#</span> damage per second. Lasts for 10 seconds. Stacks 3 times. With 3 stack(s) of Bloodrage Stance, the chance to inflict the bleed effect is increased by 15%.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [105, 162, 221, 281],
			rankInfo3: [446, 876, 1299, 1715],
			rankInfo4: [50, 100, 150, 200],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">343</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Physical damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Short Range</span>\n\n<br><br>Strikes the target twice. Each hit deals 90% of your base Attack plus <span class="tooltip-value">2123</span> bonus damage and has a 25% chance to inflict a bleed effect that deals <span class="tooltip-value">250</span> damage per second. Lasts for 10 seconds. Stacks 3 times. With 3 stack(s) of Bloodrage Stance, the chance to inflict the bleed effect is increased by 15%.</div>'],
		},
		{
			index: 10,
			name: "Life Bloom",
			ranks: 5,
			desc: "Bloodrage Stance increases your max Health by an additional <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [0.9, 1.8, 2.7, 3.6, 4.5],
			rankInfo2: [150, 300, 450, 600, 750],
		},
		{
			index: 12,
			name: "Steady",
			ranks: 3,
			desc: "Reduces the chance of being interrupted while casting by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the chance of being interrupted while casting by <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 13,
			name: "Sever",
			ranks: 3,
			ranksnw: 2,
			desc: "Each strike of Crimson Arc deals additional bonus damage equal to <span class='tooltip-value'>#%</span> of your max Health.",
			rankInfo: [1, 1.5, 2],
			parent: 6,
		},
		{
			index: 14,
			name: "Sanctuary of War",
			ranks: 3,
			desc: "Increases the duration of Divine Uphold by <span class='tooltip-value'>#%</span>. Increases your Crit Damage by <span class='tooltip-value'>#%</span> while Divine Uphold is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the duration of Divine Uphold by <span class="tooltip-value">40%</span>. Increases your Crit Damage by <span class="tooltip-value">40%</span> while Divine Uphold is active.</div>'],
		},
		{
			index: 15,
			name: "Gore",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the bonus damage of Bloodsuck Slash by <span class='tooltip-value'>#%</span>. Increases the amount of Health drained by <span class='tooltip-value'>#%</span> of your max Health.",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 1.5, 2],
		},
		{
			index: 18,
			name: "Haste",
			ranks: 3,
			desc: "Reduces the cooldown of Crash Dash by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Crash Dash by <span class="tooltip-value">40</span> seconds.</div>'],
		},
		{
			index: 19,
			name: "Blood Burn",
			ranks: 3,
			desc: "Reduces the cooldown of Bloodsuck Slash by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Bloodsuck Slash by <span class="tooltip-value">8</span> seconds.</div>'],
			parent: 11,
		},
		{
			index: 20,
			name: "Swordplay Mastery",
			ranks: 4,
			desc: "Increases your Physical Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 21,
			name: "Crimson Elegance",
			ranks: 3,
			desc: "Reduces the cooldown of Crimson Arc by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Crimson Arc by <span class="tooltip-value">2.5</span> second(s).</div>'],
			parent: 9,
		},
		{
			index: 22,
			name: "Boiling Blood",
			ranks: 2,
			desc: "Bloodrage Stance increases the effectiveness of healing skills cast on you by <span class='tooltip-value'>#%</span>.",
			rankInfo: [9, 18],
		},
		{
			index: 25,
			name: "Weapon Sabotage",
			ranks: 2,
			desc: "Increases the rate of target to be disarmed by <span class='tooltip-value'>#%</span> rate for the 2nd stack of Thunder, makes each stack of Sword Cyclone has a <span class='tooltip-value'>#%</span> rate to disarm target for 3 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the rate of target to be disarmed by <span class="tooltip-value">30%</span> rate for the 2nd stack of Thunder, makes each stack of Sword Cyclone has a <span class="tooltip-value">30%</span> rate to disarm target for 3 seconds.</div>'],
		},
		{
			index: 26,
			name: "Ferocity",
			ranks: 4,
			desc: "Increases the base damage of Bloodsuck Slash and Crimson Arc by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 29,
			name: "Bloodrage Outbreak",
			ranks: 2,
			desc: "Reduces the Defense penalty caused by Bloodrage Stance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 30,
			name: "Bloodlust Fury",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nCosts 5% of your max Health. Dispels and grants immunity to bleed effects for 18 seconds. While Bloodlust Fury is active, each of your attacks cost 1% of your max Health and increase your Crit Chance by <span class='tooltip-value'>#%</span>. The Crit Chance bonus lasts for 15 seconds and stacks 8 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [189, 236],
			rankInfo3: [1, 1.5],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">285</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: 120 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Costs 5% of your max Health. Dispels and grants immunity to bleed effects for 18 seconds. While Bloodlust Fury is active, each of your attacks cost 1% of your max Health and increase your Crit Chance by <span class="tooltip-value">2%</span>. The Crit Chance bonus lasts for 15 seconds and stacks 8 times.</div>'],
		},
		{
			index: 31,
			name: "Bloodlust Frenzy",
			ranks: 2,
			desc: "Reduces the cooldown of Bloodsuck Slash by <span class='tooltip-value'>#%</span> and increases the amount of Health it drains by <span class='tooltip-value'>#%</span> while Bloodlust Fury is active.",
			rankInfo: [30, 60],
			rankInfo2: [100, 200],
			parent: 20,
		},
		{
			index: 33,
			name: "Thunder Silence",
			ranks: 2,
			desc: "If either hit of the 2nd stack of Lightning Slash and Crimson Arc lands a Crit, then silences target for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2],
		},
		{
			index: 35,
			name: "Contract of Blood",
			ranks: 3,
			ranksnw: 2,
			desc: "Reduces the cooldown of Blood Soak by <span class='tooltip-value'>#</span> seconds and increases its duration by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10, 15],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Extended Bloodlust",
			ranks: 2,
			desc: "Increases the duration of Bloodlust Fury by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [3, 6],
			parent: 20,
		},
		{
			index: 39,
			name: "Dance of Blood",
			ranks: 3,
			desc: "Increases the base damage of Bash by <span class='tooltip-value'>#%</span> and grants it a <span class='tooltip-value'>#%</span> chance to ensnare the target for 2 seconds while Blood Soak is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the base damage of Bash by <span class="tooltip-value">40%</span> and grants it a <span class="tooltip-value">80%</span> chance to ensnare the target for 2 seconds while Blood Soak is active.</div>'],
			parent: 23,
		},
		{
			index: 42,
			name: "High Frequency Blade",
			ranks: 3,
			desc: "Increases the Crit damage of Bash, Evil Ward, Bloodsuck Slash, and Sacrifice by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 43,
			name: "Enforced Devour",
			ranks: 2,
			desc: "The duration of Soul Devour is increased by <span class='tooltip-value'>#</span> seconds. Has a <span class='tooltip-value'>#%</span> chance to remove the cooldown of Assault every time you are attacked, the damage of the affected attack will be increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
			rankInfo2: [12, 24],
			rankInfo3: [1, 2],
		},
		{
			index: 46,
			name: "Sacrifice",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>231 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Physical damage</span><span class='right'>Cooldown: 15 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nRequires Bloodrage Stance. Strikes the target twice. Each hit deals 90% of your base Attack plus 1159 bonus damage. Sacrifices 10% of your Health and adds that amount to your Attack.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Severe Wound",
			ranks: 4,
			desc: "Sacrifice has a <span class='tooltip-value'>#%</span> chance to cause target to bleed <span class='tooltip-value'>#</span> Health and slow the target by <span class='tooltip-value'>#%</span>. Lasts 4 seconds.",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [200, 300, 400, 500],
			rankInfo3: [10, 20, 30, 40],
			parent: 28,
		},
		{
			index: 49,
			name: "Cyclone Master",
			ranks: 3,
			desc: "Sword Cyclone's Base Attack bonus is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 51,
			name: "Warrior Poet",
			ranks: 2,
			desc: "The duration of War Cry is increased by <span class='tooltip-value'>#</span> seconds, healing effect on target is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [300, 600],
			rankInfo2: [3, 6],
		},
		{
			index: 54,
			name: "Deadly Will",
			ranks: 1,
			desc: "The Accuracy of Sacrifice is increased by 80.",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Rampage",
			ranks: 5,
			desc: "Frenzy Stance increases the Attack bonus granted by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [0.9, 1.8, 2.7, 3.6, 4.5],
			rankInfo2: [30, 60, 90, 120, 150],
		},
		{
			index: 2,
			name: "Lethal Lightning",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases your Attack by <span class='tooltip-value'>#</span> for 10 seconds when you kill a target within 10 seconds of using Lightning Slash. This effect also increases your base Attack by 1%.",
			rankInfo: [20, 35, 50, 65, 80],
		},
		{
			index: 5,
			name: "Valiant Sortie",
			ranks: 5,
			desc: "Increases the chance for Assault to trigger the Valiant Sortie effect by <span class='tooltip-value'>#%</span>. Valiant Sortie increases your Accuracy by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the chance for Assault to trigger the Valiant Sortie effect by <span class="tooltip-value">36%</span>. Valiant Sortie increases your Accuracy by <span class="tooltip-value">60</span>.</div>'],
		},
		{
			index: 6,
			name: "Lightning Mystery",
			ranks: 3,
			desc: "Reduces the cooldown of Lightning Slash by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Lightning Slash by <span class="tooltip-value">4</span> second(s).</div>'],
			parent: 1,
		},
		{
			index: 7,
			name: "Warsong Mastery",
			ranks: 3,
			ranksnw: 3,
			desc: "Increases the duration of War Cry by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [300, 600, 900],
		},
		{
			index: 9,
			name: "Combat Rampage",
			ranks: 3,
			desc: "Increases your Attack by <span class='tooltip-value'>#%</span> for 10 seconds when you are struck while Divine Uphold is active. Stacks 5 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases your Attack by <span class="tooltip-value">8%</span> for 10 seconds when you are struck while Divine Uphold is active. Stacks 5 times.</div>'],
		},
		{
			index: 10,
			name: "Threatening Roar",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Physical</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: None</span>\n\nReduces the Evasion by <span class='tooltip-value'>#</span>, Defense by <span class='tooltip-value'>#</span>, and movement speed by 25% of enemies within 10 meters for 10 seconds. Reveals stealthed enemies.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [87, 123, 161, 199],
			rankInfo3: [15, 25, 35, 45],
			rankInfo4: [25, 50, 75, 100],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">239</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Physical</span><span class="right">Cooldown: 20 seconds</span>\n<br><span class="left">Multi-target curse</span><span class="right">Range: None</span>\n\n<br><br>Reduces the Evasion by <span class="tooltip-value">55</span>, Defense by <span class="tooltip-value">125</span>, and movement speed by 25% of enemies within 10 meters for 10 seconds. Reveals stealthed enemies.</div>'],
		},
		{
			index: 11,
			name: "Elven Warsong",
			ranks: 3,
			desc: "War Cry increases your Attack by <span class='tooltip-value'>#</span>, your Accuracy by <span class='tooltip-value'>#</span>, and your base Attack by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
			rankInfo3: [0.5, 1, 1.5],
			parent: 4,
		},
		{
			index: 14,
			name: "Howl",
			ranks: 3,
			desc: "Increases the duration of Threatening Roar by <span class='tooltip-value'>#</span> seconds and reduces the Wind Resistance of the targets by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the duration of Threatening Roar by <span class="tooltip-value">8</span> seconds and reduces the Wind Resistance of the targets by <span class="tooltip-value">40</span>.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Exorcism",
			ranks: 4,
			desc: "Evil Ward reduces the target's Physical Resistance by <span class='tooltip-value'>#</span> and its max Mana by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [5, 10, 15, 20],
		},
		{
			index: 16,
			name: "Storm Mastery",
			ranks: 4,
			desc: "Increases your Wind Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Code of Haste",
			ranks: 3,
			desc: "Increases the duration of Crash Dash by <span class='tooltip-value'>#</span> second(s). Crash Dash increases your movement speed by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [2.5, 5, 7.5],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the duration of Crash Dash by <span class="tooltip-value">4</span> second(s). Crash Dash increases your movement speed by an additional <span class="tooltip-value">10%</span>.</div>'],
		},
		{
			index: 18,
			name: "Bleeding Touch",
			ranks: 3,
			desc: "Bloodsuck Slash reduces the effectiveness of healing skills cast on the target by <span class='tooltip-value'>#%</span> for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [25, 35, 45],
			rankInfo2: [6, 8, 10],
		},
		{
			index: 19,
			name: "Leaf Dance",
			ranks: 4,
			desc: "Increases the Crit Chance of Lightning Slash by <span class='tooltip-value'>#%</span> while in Frenzy Stance.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the Crit Chance of Lightning Slash by <span class="tooltip-value">7.5%</span> while in Frenzy Stance.</div>'],
		},
		{
			index: 21,
			name: "Weakness Exposure",
			ranks: 2,
			ranksnw: 2,
			desc: "Assault reduces the target's Crit Dodge by <span class='tooltip-value'>#%</span> for up to 10 seconds. This effect ends after the target is struck 3 times.",
			rankInfo: [2, 4],
		},
		{
			index: 22,
			name: "Thunder Storm",
			ranks: 4,
			ranksnw: 3,
			desc: "Increases the Crit Chance of both Thunder Slash attacks by <span class='tooltip-value'>#%</span> and reduces the skill's cooldown by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the Crit Chance of both Thunder Slash attacks by <span class="tooltip-value">5%</span> and reduces the skill\'s cooldown by <span class="tooltip-value">2.5</span> second(s).</div>'],
		},
		{
			index: 25,
			name: "Rage of War",
			ranks: 1,
			desc: "Assault has no cooldown while Divine Uphold is active, but the duration of the stun effect it causes is reduced to 1 second.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 26,
			name: "Thunder Struck",
			ranks: 2,
			desc: "Thunder Slash stuns the target for <span class='tooltip-value'>#</span> second(s) when it lands a Crit.",
			rankInfo: ['1-2', '2-3'],
			parent: 15,
		},
		{
			index: 28,
			name: "Swift Frenzy",
			ranks: 2,
			desc: "Reduces the cooldowns of Crash Dash, Dragon Power, and Blade of Reflection by <span class='tooltip-value'>#%</span> while in Frenzy Stance.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldowns of Crash Dash, Dragon Power, and Blade of Reflection by <span class="tooltip-value">30%</span> while in Frenzy Stance.</div>'],
		},
		{
			index: 29,
			name: "Soul of Dragon",
			ranks: 2,
			desc: "Dragon Power increases the target's base Attack by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 30,
			name: "Blade of Reflection",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 90 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nWhen struck by a direct attack while this skill is active, you launch a counterattack, which deals damage equal to 100% of your base Attack, and bypasses Defense and Resistances. This effect lasts for <span class='tooltip-value'>#</span> seconds and is not affected by controlling effects.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [213, 265],
			rankInfo3: [12, 15],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">321</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: 90 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>When struck by a direct attack while this skill is active, you launch a counterattack, which deals damage equal to 100% of your base Attack, and bypasses Defense and Resistances. This effect lasts for <span class="tooltip-value">18</span> seconds and is not affected by controlling effects.</div>'],
		},
		{
			index: 31,
			name: "Frenzy Outbreak",
			ranks: 2,
			desc: "The Evasion and Defense penalties caused by Frenzy Stance are reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [25, 50],
		},
		{
			index: 33,
			name: "Blood Soak Mastery",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the duration of Blood Soak by <span class='tooltip-value'>#</span> seconds and its chance to force the target to dismount by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
			rankInfo2: [5, 10],
		},
		{
			index: 35,
			name: "Frenzied Force",
			ranks: 2,
			desc: "Increases the bonus damage of Bash, Lightning Slash, and Thunder Slash by <span class='tooltip-value'>#%</span> while in Frenzy Stance. Changes the damage property of Bash to Wind damage.",
			rankInfo: [8, 16],
		},
		{
			index: 38,
			name: "Counter Master",
			ranks: 3,
			desc: "Increases the duration of Blade of Reflection by <span class='tooltip-value'>#</span> second(s) and the damage of the counterattack by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			parent: 20,
		},
		{
			index: 39,
			name: "Swift Lightning",
			ranks: 3,
			desc: "Cooldown of Lightning Wings is reduced by <span class='tooltip-value'>#</span> seconds, casting time is reduced by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Cooldown of Lightning Wings is reduced by <span class="tooltip-value">20</span> seconds, casting time is reduced by <span class="tooltip-value">80%</span>.</div>'],
		},
		{
			index: 41,
			name: "Rain of Blood",
			ranks: 3,
			desc: "Affected targets' basic Defense and Evasion are reduced by <span class='tooltip-value'>#%</span> and <span class='tooltip-value'>#</span>, respectively. The range is increased by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
			rankInfo3: [2, 4, 6],
			parent: 22,
		},
		{
			index: 43,
			name: "Raging Devour",
			ranks: 2,
			desc: "Reduces the cooldown of Soul Devour by <span class='tooltip-value'>#</span> seconds. You have a <span class='tooltip-value'>#%</span> chance to resist stun and sleep effects while Soul Devour is active. This effect ends after a successful attack.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: [30, 60],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Soul Devour by <span class="tooltip-value">45</span> seconds. You have a <span class="tooltip-value">100%</span> chance to resist stun and sleep effects while Soul Devour is active. This effect ends after a successful attack.</div>'],
		},
		{
			index: 46,
			name: "Slash Storm",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>396 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Wind damage</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Short Range</span>\n\nRequires Frenzy Stance. Attacks up to 10 targets within 7 meters in a 120 degree arc. Strikes 3 times. Each hit deals 100% of your base Attack plus 1067 bonus damage. The Accuracy is increased with a higher Wind Mastery. The first hit has an additional Thunder Slash state to slow the target's movement speed by 50% for 5 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Perfect Storm",
			ranks: 4,
			desc: "The cooldown of Slash Storm is reduced by <span class='tooltip-value'>#</span> seconds, while the Attack bonus is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [5, 10, 15, 20],
			parent: 28,
		},
		{
			index: 49,
			name: "Blitz Cleave",
			ranks: 2,
			desc: "The cooldown of Thunderous Cleave is reduced by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [3, 6],
		},
		{
			index: 51,
			name: "Blood of the Wargod",
			ranks: 3,
			desc: "The duration of Blood Soak is increased by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 54,
			name: "Storm Lord",
			ranks: 1,
			desc: "The cooldown of Slash Storm is reduced by 10 seconds and the Base Attack bonus is increased by 50%.",
			rankInfo: [],
			parent: 28,
		},
	]
];