var data = [
	// one
	[
		{
			index: 1,
			name: "Recuperação Abençoada",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta a quantidade de Saúde restaurada por Curar em <span class='tooltip-value'>#</span> mais <span class='tooltip-value'>#%</span> do seu Mana Máximo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [50, 100, 150, 200, 250],
			rankInfo2: [2, 3, 4, 5, 6],
		},
		{
			index: 3,
			name: "Vida Florescente",
			ranks: 5,
			desc: "A Bênção da Vida aumenta a Saúde Máxima dos alvos em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3, 4, 5],
		},
		{
			index: 6,
			name: "Roda da Fortuna",
			ranks: 3,
			desc: "Aumenta a duração da Bênção da Fortuna em <span class='tooltip-value'>#</span> minuto(s) e a eficácia das habilidades de cura lançadas no alvo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 7,
			name: "Brilho",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta a quantidade de Saúde restaurada pela Luz do Santuário em <span class='tooltip-value'>#%</span> e reduz o intervalo de uso em <span class='tooltip-value'>#</span> segundo (s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [4, 8, 12],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 8,
			name: "Fonte da Magia",
			ranks: 4,
			desc: "Aumenta o seu Mana Máximo em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [50, 100, 150, 200],
		},
		{
			index: 9,
			name: "Cura Natural",
			ranks: 4,
			desc: "A Cura aciona o efeito de Proteção Natural, que aumenta a quantidade de Saúde restaurada de suas habilidades de cura em <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundos.",
			rankInfo: [5, 10, 15, 20],
			parent: [0],
		},
		{
			index: 10,
			name: "Luz Divina",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 4 segundo(s)</span>\n<span class='left'>Curar</span><span class='right'>Intervalo: 8 segundo(s)</span>\n<span class='left'>Bênção para alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nRestaura <span class='tooltip-value'>#</span> de Saúde ao alvo a cada segundo por 4 segundos. O efeito final de cura restaura o dobro dessa quantidade. Aumenta a Saúde Máxima do alvo em <span class='tooltip-value'>#</span> por 10 segundos. Tem uma Chance Crítica de 4%, o que faz com que esta habilidade cure o dobro da quantidade.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [424, 689, 949, 1204],
			rankInfo3: ['719-794', '1072-1184', '1428-1577', '1787-1973'],
			rankInfo4: [2000, 3000, 4000, 5000],
		},
		{
			index: 11,
			name: "Dádiva dos Deuses",
			ranks: 2,
			desc: "A Luz do Santuário aumenta a eficácia das habilidades de cura lançadas no alvo em <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20],
			rankInfo2: [25, 50],
			parent: 3,
		},
		{
			index: 15,
			name: "Primeiros Socorros",
			ranks: 3,
			ranksnw: 2,
			desc: "Reduz o intervalo de uso da Luz da Cura em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2, 3],
		},
		{
			index: 16,
			name: "Calma",
			ranks: 4,
			desc: "Reduz o custo de Mana das suas habilidades de cura em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [6, 12, 18, 24],
		},
		{
			index: 18,
			name: "Cura Sagrada",
			ranks: 3,
			desc: "Aumenta a quantidade de Saúde restaurada pela Luz Divina em <span class='tooltip-value'>#%</span>, e reduz a chance de sofrer uma interrupção durante o lançamento da habilidade em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [25, 50, 75],
			parent: 6,
		},
		{
			index: 20,
			name: "Tranquilidade",
			ranks: 4,
			desc: "Reduz a quantidade de ameaça gerada pelas habilidades de cura em <span class='tooltip-value'>#%</span> e a chance de sofrer uma interrupção durante a ativação em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [15, 30, 45, 60],
		},
		{
			index: 21,
			name: "Cura Combinada",
			ranks: 3,
			desc: "Restaura uma quantidade de Mana equivalente a <span class='tooltip-value'>#%</span> do seu Mana Máximo contra alvos afetados pela Luz da Cura ou Proteção Natural.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 1.5, 2],
		},
		{
			index: 22,
			name: "Poder Sagrado",
			ranks: 3,
			desc: "Aumenta o dano base das suas habilidades de ataque em <span class='tooltip-value'>#%</span> depois de lançar Curar, Luz da Cura ou Luz Divina. Este efeito tem duração de 20 segundos, pode ser acumulado 3 vezes e acaba depois que o ataque tiver sucesso.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [6, 8, 10],
		},
		{
			index: 23,
			name: "Cura Aprimorada",
			ranks: 3,
			desc: "Aumenta a quantidade de Saúde restaurada pela Luz da Cura em <span class='tooltip-value'>#</span> mais <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [50, 100, 150],
			rankInfo2: [0.5, 1, 1.5],
			parent: 8,
		},
		{
			index: 25,
			name: "Coração Persistente",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta a duração da Bênção da Persistência em <span class='tooltip-value'>#</span> minuto(s) e reduz o custo de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 26,
			name: "Conscientização",
			ranks: 2,
			desc: "Aumenta a quantidade de Saúde e Mana que a Luz da Ressurreição restaura ao alvo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [20, 40],
		},
		{
			index: 28,
			name: "Espírito de Cura",
			ranks: 3,
			desc: "Aumenta a Chance Crítica de Curar, Luz da Cura e Luz Divina em <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 30,
			name: "Escudo Divino",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 30 segundo(s)</span>\n<span class='left'>Bênção para alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nConcede o efeito de Escudo Sagrado ao alvo, que absorve 80% do dano sofrido por <span class='tooltip-value'>#</span> segundo(s). O escudo pode absorver uma quantidade de dano equivalente a <span class='tooltip-value'>#%</span> da Saúde Máxima do alvo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [702, 861],
			rankInfo3: [20, 21],
			rankInfo4: [60, 80],
		},
		{
			index: 31,
			name: "Luz da Natureza",
			ranks: 3,
			desc: "A Luz de Cura tem <span class='tooltip-value'>#%</span> de chance de restaurar o total integral da Saúde, imediatamente quando a mesma é lançada em um alvo afetado pela Proteção Natural.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 33,
			name: "Armadura da Luz",
			ranks: 2,
			desc: "A Bênção da Persistência aumenta a Defesa do alvo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6],
			parent: 15,
		},
		{
			index: 34,
			name: "Escudo Imortal",
			ranks: 3,
			desc: "Aumenta a quantidade de dano absorvido pelo Escudo Divino em <span class='tooltip-value'>#%</span> mais uma quantidade equivalente a <span class='tooltip-value'>#%</span> do seu Mana Máximo.",
			rankInfo: [20, 40, 60],
			rankInfo2: [1, 2, 3],
			parent: 18,
		},
		{
			index: 35,
			name: "Iluminação",
			ranks: 3,
			desc: "Habilidades de cura ganham uma chance de <span class='tooltip-value'>#%</span> de acionar o efeito de Inspiração, que reduz o custo em Mana das habilidades de cura em 10% por 10 segundos. Acumula 3 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Luz da Benevolência",
			ranks: 2,
			desc: "Aumenta o bônus de cura de Simpatia em <span class='tooltip-value'>#%</span> do seu ataque.",
			rankInfo: [5, 10],
		},
		{
			index: 40,
			name: "Dádiva da Deusa",
			ranks: 3,
			desc: "Aumenta a quantidade de Saúde restaurada pelas habilidades de cura em <span class='tooltip-value'>#%</span>. Bônus de cura de outras habilidades e talentos também aumentam.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 41,
			name: "Advento",
			ranks: 3,
			desc: "Aumenta a quantidade de Saúde restaurada pela Harmonia Angelical em <span class='tooltip-value'>#%</span> e reduz o intervalo em <span class='tooltip-value'>#</span> segundo(s). Também reduz o intervalo da Luz do Santuário em <span class='tooltip-value'>#</span> segundos por ponto nesse talento.",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 2, 3],
			rankInfo3: [20, 40, 60],
		},
		{
			index: 42,
			name: "Exaltação Divina",
			ranks: 2,
			desc: "Reduz os intervalos da Luz do Paraíso e do Escudo Divino em <span class='tooltip-value'>#</span> e <span class='tooltip-value'>#</span> segundos, respectivamente. Reduz os custos de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [3, 6],
			rankInfo3: [15, 30],
		},
		{
			index: 46,
			name: "Luz Purificadora",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>378 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: 8 segundo(s)</span>\n<span class='left'>Bênção para alvo único</span><span class='right'>Alcance: 8 metro(s)</span>\n\nDissipa o efeito de maldição mais recente lançado sobre o alvo.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// two
	[
		{
			index: 1,
			name: "Queima da Luz",
			ranks: 5,
			ranksnw: 2,
			desc: "O Ataque Divino causa uma quantidade de dano bônus equivalente a <span class='tooltip-value'>#</span> mais <span class='tooltip-value'>#%</span> da sua Maestria em Luz.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [40, 80, 120, 160, 200],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 3,
			name: "Benção Vigorosa",
			ranks: 5,
			ranksnw: 2,
			desc: "Aumenta a quantidade de Saúde restaurada pela Bênção da Vida em <span class='tooltip-value'>#%</span> e a Precisão das suas habilidades de Luz em <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Fortuna de Luz",
			ranks: 5,
			desc: "A Bênção da Fortuna aumenta a Chance Crítica das suas habilidades de Luz em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3, 4, 5],
		},
		{
			index: 8,
			name: "Conhecimento Divino",
			ranks: 5,
			desc: "Aumenta a sua Maestria em Luz em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 9,
			name: "Penalidade Celestial",
			ranks: 4,
			ranksnw: 2,
			desc: "O Ataque Divino ganha uma chance de <span class='tooltip-value'>#%</span> de causar o efeito da Punição Leve ao alvo, que reduz a Resistência de Luz do alvo em <span class='tooltip-value'>#</span> por 15 segundos. Acumula 5 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [40, 60, 80, 100],
			rankInfo2: [10, 15, 20, 25],
			parent: [0],
		},
		{
			index: 10,
			name: "Ataque da Punição",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de luz</span><span class='right'>Intervalo: 5 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nInflige 100% do seu Ataque básico mais <span class='tooltip-value'>#</span> de bônus de dano. Causa o efeito Punição Leve no alvo, o que reduz sua Resistência de Luz em 8 por 15 segundo(s). Acumula 5 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [147, 210, 275, 339],
			rankInfo3: [794, 1326, 1849, 2363],
		},
		{
			index: 11,
			name: "Surto da Vida",
			ranks: 3,
			desc: "Aumenta a duração da Bênção da Vida em <span class='tooltip-value'>#</span> minuto(s) e reduz seu custo de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
			parent: 1,
		},
		{
			index: 15,
			name: "Vento da Aurora",
			ranks: 4,
			ranksnw: 2,
			desc: "A Bênção da Tempestade aumenta a velocidade do movimento do alvo em <span class='tooltip-value'>#%</span> e o intervalo de uso é reduzido em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [2, 4, 6, 8],
		},
		{
			index: 16,
			name: "Barreira Divina",
			ranks: 3,
			desc: "Aumenta a sua Resistência de Luz em <span class='tooltip-value'>#</span> e a sua Defesa em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [10, 15, 20],
		},
		{
			index: 17,
			name: "Glória",
			ranks: 3,
			desc: "Aumenta o dano base do Ataque Divino em <span class='tooltip-value'>#%</span>. O Ataque Divino ganha uma chance de <span class='tooltip-value'>#%</span> de acionar o efeito de Glória que faz com que o próximo Ataque Divino não gaste Mana nem tenha intervalo de uso. Este efeito tem duração de 15 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			parent: 4,
		},
		{	
			index: 18,
			name: "Marca da Penalidade",
			ranks: 2,
			desc: "Aumenta o dano base do Ataque da Punição em <span class='tooltip-value'>#%</span>. Tem uma chance de <span class='tooltip-value'>#%</span> de causar o efeito Marca da Convicção no alvo, que reduz o Mana Máximo em 5% a cada 4 segundos por 20 segundos.",
			rankInfo: [10, 20],
			rankInfo2: [25, 50],
			parent: 5,
		},
		{
			index: 19,
			name: "Vento Caloroso",
			ranks: 2,
			desc: "A Bênção da Tempestade concede o efeito de Vento Caloroso ao alvo, restaurando uma quantidade de Saúde equivalente a <span class='tooltip-value'>#%</span> da quantidade que a sua habilidade de Curar restaurar quando o alvo for atacado.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [70, 120],
			parent: 7,
		},
		{
			index: 22,
			name: "Retribuição",
			ranks: 4,
			desc: "Aumenta o dano base das suas habilidades ofensivas de Água em <span class='tooltip-value'>#%</span> enquanto você for afetado pela Proteção Natural ou Luz de Cura.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 23,
			name: "Vento de Bênçãos",
			ranks: 3,
			desc: "A Luz do Santuário aciona o efeito de Vento de Bênçãos, que aumenta a velocidade do movimento dos integrantes do grupo em <span class='tooltip-value'>#%</span> e deixa você imune a todo dano direto por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [40, 50, 60],
			rankInfo2: [4, 6, 8],
		},
		{
			index: 26,
			name: "Poderio Divino",
			ranks: 3,
			desc: "A Condenação reduz a Chance Crítica do alvo em <span class='tooltip-value'>#%</span> e a Evasão em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 30, 40],
		},
		{
			index: 28,
			name: "Clarão",
			ranks: 4,
			desc: "Aumenta a sua Evasão em <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 29,
			name: "Energia Sagrada",
			ranks: 3,
			desc: "Concede ao alvo o efeito Energia Sagrada por 5 segundos. Quando o alvo é atacado, a Energia Sagrada causa <span class='tooltip-value'>#</span> de dano em um agressor e drena <span class='tooltip-value'>#%</span> do seu Mana máximo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [200, 400, 600],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 30,
			name: "Punição Leve",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Dano de luz</span><span class='right'>Intervalo: 15 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nAcerta o alvo três vezes. Cada ataque que acertar causa 80% do seu Ataque base mais <span class='tooltip-value'>#</span> de dano bônus. Cada golpe que acertar tem uma chance de 5%/10%/15% de atordoar um alvo afetado pela Marca da Convicção por 3 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [633, 789],
			rankInfo3: [1254, 1922],
		},
		{
			index: 31,
			name: "Tempestade da Magia",
			ranks: 2,
			desc: "Aumenta o custo de Mana da Bênção da Tempestade em <span class='tooltip-value'>#%</span>. Restaura uma quantidade de Mana equivalente a <span class='tooltip-value'>#%</span> do custo desta habilidade no alvo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [50, 100],
			rankInfo2: [50, 70],
		},
		{
			index: 33,
			name: "Justiça",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduz o intervalo de uso de Exame Divino em <span class='tooltip-value'>#</span> segundo(s) e aumenta o dano bônus em <span class='tooltip-value'>#%</span> da sua Maestria em Luz.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4],
			rankInfo2: [30, 60],
		},
		{
			index: 34,
			name: "Esplendor",
			ranks: 3,
			ranksnw: 2,
			desc: "Aumenta a chance de que cada golpe da Punição Leve atordoe o alvo em <span class='tooltip-value'>#</span>.",
			rankInfo: ['1%/3%/5%', '2%/6%/10%', '3%/9%/15%'],
			parent: 17,
		},
		{
			index: 36,
			name: "Proteção da Luz",
			ranks: 3,
			desc: "Aumenta a quantidade de danos de Luz que você causa e o total de Saúde restaurada por suas habilidades de cura em <span class='tooltip-value'>#</span> para cada ponto de sua Maestria em Luz.",
			rankInfo: [0.5, 1, 1.5],
		},
		{
			index: 38,
			name: "Luz Vingadora",
			ranks: 3,
			desc: "Reduz o intervalo de uso da Punição Leve em <span class='tooltip-value'>#</span> segundo(s), a chance de sofrer interrupção durante o lançamento em <span class='tooltip-value'>#%</span> e o custo de Mana em <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [10, 20, 30],
			parent: 20,
		},
		{
			index: 39,
			name: "Fusão da Luz",
			ranks: 2,
			desc: "Usar ataques de Luz reduzirá o custo de Mana do próximo ataque de Luz de luz em <span class='tooltip-value'>#%</span> por 10 segundos. O efeito pode ser acumulado 5 vezes.",
			rankInfo: [2, 4],
		},
		{
			index: 41,
			name: "Julgamento",
			ranks: 2,
			desc: "Aumenta o dano bônus do Exame Divino em <span class='tooltip-value'>#%</span>. O Julgamento Divino ativa o efeito de Proteção Natural, o que aumenta a quantidade de Saúde restaurada por suas habilidades de cura em 20% por <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 15],
			rankInfo2: [10, 15],
			parent: 19,
		},
		{
			index: 42,
			name: "Abandono",
			ranks: 2,
			desc: "Reduz o intervalo de uso do Ataque da Punição em <span class='tooltip-value'>#</span> segundo(s). O Ataque da Punição e a Punição Leve têm uma chance de dissipar efeitos de cura no alvo. O alvo não pode ser curado por 3 segundos.",
			rankInfo: [1, 2],
		},
		{
			index: 46,
			name: "Remoção Punitiva",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>913 Mana</span><span class='right'>Tempo de ativação: 3 segundo(s)</span>\n<span class='left'>Luz</span><span class='right'>Intervalo: 60 segundo(s)</span>\n<span class='left'>Maldição contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nRemove os buffs de Ataque de até 20 alvos em um raio de 10 metros.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// three
	[
		{
			index: 2,
			name: "Luz Congelante",
			ranks: 5,
			desc: "O Ataque Divino causa uma quantidade de dano contra alvos lentos igual a <span class='tooltip-value'>#%</span> do dano bônus do Ataque Divino. Dá ao Ataque Divino uma chance de <span class='tooltip-value'>#%</span> de enredar o alvo devagar por 2 segundos.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 4,
			name: "Coração Congelado",
			ranks: 5,
			desc: "Aumenta a Precisão das suas habilidades de Água em <span class='tooltip-value'>#</span> e a Chance Crítica em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 1, 2, 2, 3],
		},
		{
			index: 5,
			name: "Núcleo Gelado",
			ranks: 3,
			ranksnw: 2,
			desc: "Concentração Gélida reduz a velocidade de movimento do alvo em um adicional de <span class='tooltip-value'>#%</span>. Aumenta o dano bônus da Concentração Gélida em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 6,
			name: "Doação Aquática",
			ranks: 2,
			desc: "A Bênção da Fortuna aumenta as Resistências do alvo em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10],
		},
		{
			index: 7,
			name: "Luz da Salvação",
			ranks: 3,
			desc: "Concede à Luz do Santuário uma chance de <span class='tooltip-value'>#%</span> de dissipar todos efeitos de controle dos alvos e dá a eles imunidade contra os efeitos de controle por 5 segundos.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 10,
			name: "Oração da Geada",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: 60 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nAumenta o dano base das suas habilidades de Água em 50% e reduz os intervalos de uso em 75% por <span class='tooltip-value'>#</span> segundo(s). Enquanto a Oração da Geada estiver ativa, você não pode sofrer interrupção ao lançar habilidades de Água.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [276, 394, 513, 634],
			rankInfo3: [12, 15, 18, 21],
		},
		{
			index: 11,
			name: "Ventos da Salvação",
			ranks: 3,
			desc: "Aumenta a duração da Bênção da Tempestade em <span class='tooltip-value'>#</span> segundo(s) e concede uma chance de <span class='tooltip-value'>#%</span> dissipar o efeito devagar no alvo.",
			rankInfo: [2, 4, 6],
			rankInfo2: [40, 70, 100],
		},
		{
			index: 12,
			name: "Maestria em Congelamento",
			ranks: 4,
			desc: "Aumenta a sua Maestria em Água em <span class='tooltip-value'>#</span>.",
			rankInfo: [12, 24, 36, 48],
		},
		{
			index: 13,
			name: "Congelamento Instantâneo",
			ranks: 3,
			ranksnw: 2,
			desc: "Reduz o intervalo de uso da Concentração Gélida em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
			parent: 2,
		},
		{
			index: 15,
			name: "Frieza Arcana",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta o dano base da Oração Santa - Enigma em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 16,
			name: "Barreira da Geada",
			ranks: 3,
			desc: "Aumenta a sua Resistência Aquática em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Frio de Rachar",
			ranks: 4,
			desc: "A Concentração Gélida reduz a Resistência Aquática do alvo em <span class='tooltip-value'>#</span> e a sua Esquiva Crítica em <span class='tooltip-value'>#%</span> durante 15 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 25, 35, 45],
			rankInfo2: [0.5, 1, 1.5, 2],
			parent: 8,
		},
		{
			index: 18,
			name: "Claridade do Gelo",
			ranks: 4,
			desc: "A Oração da Geada aumenta os alcances das habilidades de Água em <span class='tooltip-value'>#</span> metro(s) e suas Chances Críticas em <span class='tooltip-value'>#%</span>. A Oração da Geada ganha uma chance de <span class='tooltip-value'>#%</span> zerar os intervalos de uso das outras habilidades de Água.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: [25, 50, 75, 100],
			parent: 5,
		},
		{
			index: 22,
			name: "Corrente Devoradora",
			ranks: 3,
			desc: "Seus ataques de Água ganham uma chance de <span class='tooltip-value'>#%</span> de atordoar o alvo sob efeito devagar por 3 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [7, 14, 21],
		},
		{
			index: 23,
			name: "Sifão",
			ranks: 3,
			desc: "Aumenta a quantidade de Mana absorvido pela Oração Santa - Enigma em <span class='tooltip-value'>#%</span>. Reduz a Saúde Máxima do alvo pelo dobro do Mana absorvido por <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [25, 50, 75],
			rankInfo2: [20, 25, 30],
			parent: 9,
		},
		{
			index: 25,
			name: "Lâmina Congelada",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta o dano bônus do Ataque da Lâmina de Gelo em <span class='tooltip-value'>#%</span> e reduz o intervalo de uso em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 26,
			name: "Ar do Norte",
			ranks: 3,
			desc: "Aumenta a chance de causar o Ataque da Lâmina de Gelo e causar efeito de lentidão em <span class='tooltip-value'>#%</span>. O alcance aumenta em <span class='tooltip-value'>#</span> metro(s).",
			rankInfo: [25, 50, 75],
			rankInfo2: [1, 2, 3],
			parent: 15
		},
		{
			index: 27,
			name: "Bênção Aquática",
			ranks: 2,
			desc: "A Bênção da Tenacidade dá ao alvo o efeito Bênção do Deus da Água, que reduz os danos de Água recebidos em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6],
		},
		{
			index: 30,
			name: "Confissão no Gelo",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Água</span><span class='right'>Intervalo: 45 segundo(s)</span>\n<span class='left'>Maldição contra alvo único</span><span class='right'>Alcance: 18 metro(s)</span>\n\nPor 10 segundo(s), todo golpe que acertar no alvo interromperá o lançamento e enredará o alvo por <span class='tooltip-value'>#</span> segundo(s). Este efeito termina depois que o alvo é atingido 6 vezes. Se o alvo não for atingido na duração do efeito, ele será congelado por 5 segundos quando o efeito terminar.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [409, 502],
			rankInfo3: [1, 2],
		},
		{
			index: 31,
			name: "Água Ondulante",
			ranks: 3,
			desc: "Aumenta a quantidade de danos de Água que você causa e o total de Saúde restaurada por suas habilidades de cura em <span class='tooltip-value'>#</span> para cada ponto de sua Maestria em Água.",
			rankInfo: [0.5, 1, 1.5],
		},
		{
			index: 32,
			name: "Barreira Angelical",
			ranks: 3,
			desc: "Aumenta o bônus de Defesa da Barreira da Alma em <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 33,
			name: "Convicção",
			ranks: 3,
			desc: "Aumenta a quantidade de Mana que o alvo do Julgamento Divino perde em <span class='tooltip-value'>#</span>. Enreda os alvos sob o efeito devagar por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [200, 400, 600],
			rankInfo2: [3, 4, 5],
		},
		{
			index: 34,
			name: "Coração Frio",
			ranks: 3,
			desc: "Aumenta a duração da Confissão no Gelo em <span class='tooltip-value'>#</span> segundo(s) e reduz o intervalo de uso em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [2, 4, 6],
			rankInfo2: [5, 10, 15],
			parent: 18,
		},
		{
			index: 38,
			name: "Resposta Rápida",
			ranks: 2,
			desc: "Reduz o intervalo de uso da Simpatia em <span class='tooltip-value'>#</span> segundo(s) e seu custo de Mana em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6],
			rankInfo2: [20, 40],
		},
		{
			index: 39,
			name: "Calma de Cristal",
			ranks: 3,
			desc: "Aumenta a duração do efeito Devagar causado por suas habilidades em <span class='tooltip-value'>#</span> segundo(s). Eles reduzem a velocidade de movimento do alvo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 41,
			name: "Asilo Angelical",
			ranks: 2,
			desc: "Reduz o custo de Mana da Harmonia Angelical em <span class='tooltip-value'>#%</span>. Cada efeito de cura tem uma chance de <span class='tooltip-value'>#%</span> de dissipar o efeito mais recente de sangramento ou de queima colocado no alvo. Esta chance é duplicada para alvos dentro de um raio de 8 metros.",
			rankInfo: [15, 30],
			rankInfo2: [10, 20],
		},
		{
			index: 42,
			name: "Abraço da Aurora",
			ranks: 2,
			desc: "Aumenta o dano base das suas habilidades de Água em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 46,
			name: "Mundo Imóvel",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>845 Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de água</span><span class='right'>Intervalo: 15 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 18 metro(s)</span>\n\nAtaca todos os inimigos em um raio de 8 metros do alvo. Inflige 100% do seu Ataque básico mais 3328 de bônus de dano. Reduz a efetividade de habilidades de cura lançadas sobre o alvo em 20%. e sua resistência de Água em 60 por 10 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	]
];