var data = [
    // one
    [
        {
            index: 1,
            name: "Demonio de Sangre",
            ranks: 5,
			desc: "Incrementa la posibilidad que el Sello del Vampiro, el Fortalecimiento, la Semilla de Vida, el Contrato Oscuro, y el Rito de Sangre activen la forma Vampiro en un <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>Incrementa la posibilidad que el Sello del Vampiro, el Fortalecimiento, la Semilla de Vida, el Contrato Oscuro, y el Rito de Sangre activen la forma Vampiro en un <span class="tooltip-value">12%</span>.</div>'],
        },
        {
            index: 2,
            name: "Signo de Sangre",
            ranks: 5,
			desc: "Incrementa la cantidad de Salud restaurada por el Sello de Vampiro <span class='tooltip-value'>#</span> más <span class='tooltip-value'>#%</span> de tu Salud máxima.",
            rankInfo: [5, 10, 15, 20, 25],
            rankInfo2: [0.6, 1.2, 1.8, 2.4, 3.0],
        },
        {
            index: 5,
            name: "Golpe Encantado Extendido",
            ranks: 2,
            ranksnw: 1,
			desc: "Incrementa el rango del Golpe Encantado <span class='tooltip-value'>#%</span>.",
            rankInfo: [20, 40],
        },
        {
            index: 6,
            name: "Sello del Vampiro Avanzado",
            ranks: 4,
            ranksnw: 2,
			desc: "Reduce la reactivación del Sello del Vampiro <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>Reduce la reactivación del Sello del Vampiro <span class="tooltip-value">2.5</span> segundo(s).</div>'],
        },
        {
            index: 8,
            name: "Sangre Maligna",
            ranks: 4,
			desc: "Incrementa la duración de la Maldición de la Sangre <span class='tooltip-value'>#</span> segundos. Reduce la Salud máxima del blanco en un <span class='tooltip-value'>#%</span> adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [5, 10, 15, 20],
            rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>Incrementa la duración de la Maldición de la Sangre <span class="tooltip-value">25</span> segundos. Reduce la Salud máxima del blanco en un <span class="tooltip-value">5%</span> adicional.</div>'],
        },
        {
            index: 9,
            name: "Golpe Sangriento Maligno",
            ranks: 4,
			desc: "El Golpe Encantado extrae <span class='tooltip-value'>#</span> de Salud del blanco y propina un <span class='tooltip-value'>#%</span> de daño extra a los blancos afectados por la Maldición de Sangre.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [50, 100, 150, 200],
            rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>El Golpe Encantado extrae <span class="tooltip-value">250</span> de Salud del blanco y propina un <span class="tooltip-value">50%</span> de daño extra a los blancos afectados por la Maldición de Sangre.</div>'],
			parent: 2,
        },
        {
            index: 11,
            name: "Semilla de Vida",
            ranks: 3,
            ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 10 segundos</span>\n<span class='left'>Bendición objetivo único</span><span class='right'>Alcance: 16 metros</span>\n\nDespués de 5 segundos, la Semilla de Vida sana el blanco por <span class='tooltip-value'>#</span> Salud. Tiene un 2% Chance Crítico, la cual causa que esta habilidad sane el doble de la cantidad. El efecto sanador instantáneamente se activa si la Salud del blanco disminuye por debajo de 50%. Tiene una 10% probabilidad de activar la forma Vampiro.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n'],
            rankInfo2: [211, 313, 416],
            rankInfo3: ['1896-2093', '2787-3077', '3632-4011'],
			rankInfo4: ['', '', '<div class="runelvl">\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br><span class="left"><span class="tooltip-value">522</span> Maná</span><span class="right">Tiempo de hechizar: 2 segundos</span>\n<br><span class="left">Defensa</span><span class="right">Reactivación: 10 segundos</span>\n<br><span class="left">Bendición objetivo único</span><span class="right">Alcance: 16 metros</span>\n\n<br><br>Después de 5 segundos, la Semilla de Vida sana el blanco por <span class="tooltip-value">4432-4894</span> Salud. Tiene un 2% Chance Crítico, la cual causa que esta habilidad sane el doble de la cantidad. El efecto sanador instantáneamente se activa si la Salud del blanco disminuye por debajo de 50%. Tiene una 10% probabilidad de activar la forma Vampiro.</div>'],
        },
        {
            index: 12,
            name: "Conocimiento de Sangre",
            ranks: 3,
			desc: "Reduce el costo de Maná de tus poderes sanadores <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [8, 16, 24],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>Reduce el costo de Maná de tus poderes sanadores <span class="tooltip-value">32%</span>.</div>'],
        },
        {
            index: 13,
            name: "Contrato Oscuro Avanzado",
            ranks: 5,
			desc: "Reduce la reactivación del Contrato Oscuro <span class='tooltip-value'>#</span> segundo(s). Incrementa la cantidad de Salud restaurada por el Contrato Oscuro <span class='tooltip-value'>#%</span>.",
            rankInfo: [0.5, 1, 1.5, 2, 2.5],
			rankInfo2: [6, 12, 18, 24, 30],
        },
        {
            index: 14,
            name: "Energía Insignia",
            ranks: 4,
			desc: "Incrementa el daño base del Sello del Vampiro <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [10, 20, 30, 40],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>Incrementa el daño base del Sello del Vampiro <span class="tooltip-value">50%</span>.</div>'],
			parent: 3,
        },
        {
            index: 18,
            name: "Sombra del Ala del Murciélago",
            ranks: 2,
			desc: "Las Alas de Vendaval te otorgan inmunidad a los efectos de encierro por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [4, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>Las Alas de Vendaval te otorgan inmunidad a los efectos de encierro por <span class="tooltip-value">8</span> segundos.</div>'],
        },
        {
            index: 19,
            name: "Fuerza de Vida",
            ranks: 4,
			desc: "Incrementa la cantidad de Salud restaurada por la Semilla de la Vida <span class='tooltip-value'>#%</span> y su Chance Crítico en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30, 40],
            rankInfo2: [2, 4, 6, 8],
			parent: 6,
        },
        {
            index: 20,
            name: "Festín de Sangre",
            ranks: 3,
			desc: "El festín incrementa tu Defensa en un <span class='tooltip-value'>#%</span> adicional y tu taza de recuperación de Salud en un <span class='tooltip-value'>#%</span> adicional por segundo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [80, 160, 240],
            rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>El festín incrementa tu Defensa en un <span class="tooltip-value">320%</span> adicional y tu taza de recuperación de Salud en un <span class="tooltip-value">8%</span> adicional por segundo.</div>'],
        },
        {
            index: 21,
            name: "Vínculo de Sangre",
            ranks: 4,
			ranksnw: 1,
			desc: "El Fortalecimiento cuesta un <span class='tooltip-value'>#%</span> adicional de tu Salud máxima e incrementa el Ataque del blanco <span class='tooltip-value'>#%</span>.",
            rankInfo: [0.5, 1, 1.5, 2],
            rankInfo2: [8, 16, 24, 32],
        },
        {
            index: 22,
            name: "Lazo de Sangre",
            ranks: 3,
			ranksnw: 2,
			desc: "Cuando estés en forma de Vampiro, la efectividad de tus habilidades sanadoras se incrementa en un <span class='tooltip-value'>#%</span> adicional, y matar enemigos restaura <span class='tooltip-value'>#%</span> adicional de tu Salud máxima.",
            rankInfo: [10, 20, 30],
            rankInfo2: [1, 2, 3],
        },
        {
            index: 24,
            name: "Escape Nocturno",
            ranks: 2,
			desc: "Reduce la cantidad de amenaza generada por tus habilidades sanadoras <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [15, 30],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>Reduce la cantidad de amenaza generada por tus habilidades sanadoras <span class="tooltip-value">45%</span>.</div>'],
        },
        {
            index: 25,
            name: "Conceder la Vida",
            ranks: 2,
			ranksnw: 1,
			desc: "El Fortalecimiento incrementa la Salud del blanco <span class='tooltip-value'>#%</span> por 20 segundos.",
            rankInfo: [10, 20],
			parent: 13,
        },
        {
            index: 26,
            name: "Pacto de Sangre",
            ranks: 3,
			desc: "Incrementa el Chance Crítico del Contrato Oscuro y de la Semilla de la Vida en un <span class='tooltip-value'>#%</span> adicional, mientras estés en forma Vampiro.",
            rankInfo: [15, 30, 45],
			parent: 14,
        },
        {
            index: 27,
            name: "Muerte Sangrienta Maligna",
            ranks: 2,
			ranksnw: 2,
			desc: "Incrementa la cantidad de Salud extraída por la Muerte Iracunda <span class='tooltip-value'>#%</span>.",
            rankInfo: [100, 200],
        },
        {
            index: 30,
            name: "Maldición de la Sangre",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Oscuridad</span><span class='right'>Reactivación: 30 segundos</span>\n<span class='left'>Maldición multiobjetivo</span><span class='right'>Alcance: 16 metros</span>\n\nDentro de 6 metros, hasta <span class='tooltip-value'>#</span> enemigos son infligidos con la Maldición de la Sangre por 15 segundos. Los blancos afectados por la Maldición de la Sangre son infligidos con el efecto de la Sangre Coagulada por 20 segundos cuando son atacados. La Sangre Coagulada reduce la Salud máxima del blanco 4% Se acumula 5 veces. Tiene un 10% probabilidad de activar la forma Vampiro.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [385, 464],
            rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br><span class="left"><span class="tooltip-value">549</span> Maná</span><span class="right">Tiempo de hechizar: 1 segundos</span>\n<br><span class="left">Oscuridad</span><span class="right">Reactivación: 30 segundos</span>\n<br><span class="left">Maldición multiobjetivo</span><span class="right">Alcance: 16 metros</span>\n\n<br><br>Dentro de 6 metros, hasta <span class="tooltip-value">25</span> enemigos son infligidos con la Maldición de la Sangre por 15 segundos. Los blancos afectados por la Maldición de la Sangre son infligidos con el efecto de la Sangre Coagulada por 20 segundos cuando son atacados. La Sangre Coagulada reduce la Salud máxima del blanco 4% Se acumula 5 veces. Tiene un 10% probabilidad de activar la forma Vampiro.</div>'],
        },
        {
            index: 31,
            name: "Muerte Iracunda Mejorada",
            ranks: 3,
			desc: "Reduce la reactivación de la Muerte Iracunda en <span class='tooltip-value'>#</span> segundo(s). Los blancos afectados por la Maldición de la Sangre son infligidos con un efecto sangrante que inflige <span class='tooltip-value'>#</span> de dalo cada 2 segundos.",
            rankInfo: [1, 2, 3],
            rankInfo2: [80, 160, 240],
			parent: 18,
        },
        {
            index: 33,
            name: "Sangre Fresca",
            ranks: 2,
			desc: "Incrementa la cantidad de Salud restaurada por el Fortalecimiento en <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [4, 8],
            rankInfo2: [10, 20],
			parent: 16,
        },
        {
            index: 34,
            name: "Estancamiento",
            ranks: 2,
			desc: "Incrementa el rango de la Maldición de la Sangre en <span class='tooltip-value'>#</span> metro(s). Los blancos afectados por la Sangre Coagulada también se verán infligidos por el efecto de la Salud Coagulada, el cual reduce la efectividad de las habilidades sanadoras desplegadas en el blanco en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [1, 2],
            rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>Incrementa el rango de la Maldición de la Sangre en <span class="tooltip-value">3</span> metro(s). Los blancos afectados por la Sangre Coagulada también se verán infligidos por el efecto de la Salud Coagulada, el cual reduce la efectividad de las habilidades sanadoras desplegadas en el blanco en <span class="tooltip-value">45%</span>.</div>'],
			parent: 19,
        },
        {
            index: 37,
            name: "Análisis de Sangre",
            ranks: 2,
			desc: "Usar las habilidades de Sangre incrementa la duración de la forma Vampiro en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [4, 8],
        },
        {
            index: 38,
            name: "Sanacíón Acelerada",
            ranks: 2,
			desc: "Reduce las reactivaciones de la Semilla de la Vida y del Fortalecimiento en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [2, 4],
        },
        {
            index: 39,
            name: "Tiempo de Rituales",
            ranks: 2,
            ranksnw: 1,
			desc: "Incrementa la duración del Rito de la Sangre en 2 segundos. Incrementa la cantidad de Salud restaurada por el Contrato Oscuro y la Semilla de la Vida en una cantidad igual al <span class='tooltip-value'>#%</span> de tu Salud.",
            rankInfo: [1, 2],
        },
        {
            index: 40,
            name: "Sangre Brotando",
            ranks: 2,
			desc: "Incrementa tu Salud máxima <span class='tooltip-value'>#%</span>. Incrementa tu Salud máxima y tu Maná máximo en un <span class='tooltip-value'>#</span> adicional.",
            rankInfo: [2, 4],
            rankInfo2: [300, 600],
        },
        {
            index: 42,
            name: "Extensión del Lazo de Sangre",
            ranks: 2,
            ranksnw: 1,
			desc: "Incrementa el rango de tus habilidades sanadoras en <span class='tooltip-value'>#</span> metros y la cantidad de Salud que restauran en <span class='tooltip-value'>#%</span>.",
            rankInfo: [2, 4],
            rankInfo2: [15, 30],
        },
        {
            index: 43,
            name: "Fiebre de Sangre",
            ranks: 2,
            ranksnw: 1,
			desc: "Mientras el Rito de Sangre está activo, el Contrato Oscuro y el Fortalecimiento incrementan la velocidad de movimiento y todos los Dominios del blanco en <span class='tooltip-value'>#%</span> y <span class='tooltip-value'>#</span> respectivamente por 5 segundos y el Sello del Vampiro reduce la velocidad de movimiento y todos los Dominio del blanco en <span class='tooltip-value'>#%</span> y <span class='tooltip-value'>#</span> respectivamente por 5 segundos.",
            rankInfo: [25, 30],
            rankInfo2: [80, 160],
            rankInfo3: [25, 30],
            rankInfo4: [80, 160],
			parent: 26,
        },
        {
            index: 46,
            name: "Espacio Marchito",
            ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>327 Maná</span><span class='right'>Tiempo de hechizar: Instantáneo</span>\n<span class='left'>Oscuridad</span><span class='right'>Reactivación: 300 segundos</span>\n<span class='left'>Maldición multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nNo puedes moverte o usar tus ataques por 25 segundos. Puedes usar habilidades sanadoras y maldiciones. Incrementa tu Salud máxima en 50%, e incrementa la rango de tus hechizos sanadores en 50%. Despliega el Contrato Oscuro y la Semilla de la Vida en el blanco, y aplica los mismos efectos en ti. Reduce a 200 todas las Resistencias de todos los enemigos en un rango de 20 metros. Cancela esta habilidad usándola de nuevo.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
			parent: 28,
        },
    ],
        // two
    [
        {
            index: 1,
            name: "Demonio de la Oscuridad",
            ranks: 5,
            desc: "Incrementa la probabilidad de que el Rizo Oscuro, la Semilla de la Oscuridad, el Contrato Oscuro, la Muerte de Ira, la Explosión de Maná, y la Cicatriz de Sombra activen la forma de Vampiro en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>Incrementa la probabilidad de que el Rizo Oscuro, la Semilla de la Oscuridad, el Contrato Oscuro, la Muerte de Ira, la Explosión de Maná, y la Cicatriz de Sombra activen la forma de Vampiro en <span class="tooltip-value">12%</span>.</div>'],
        },
        {
            index: 3,
            name: "Fuerza de la Sombra",
            ranks: 5,
            desc: "El Rizo Oscuro y la Cicatriz de la Sombra cuestan un <span class='tooltip-value'>#%</span> adicional de tu Salud máxima. Esa cantidad aun se suma a su daño. Incrementa el Chance Crítico del Rizo Oscuro <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [0.5, 1, 1.5, 2, 2.5],
            rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>El Rizo Oscuro y la Cicatriz de la Sombra cuestan un <span class="tooltip-value">3%</span> adicional de tu Salud máxima. Esa cantidad aun se suma a su daño. Incrementa el Chance Crítico del Rizo Oscuro <span class="tooltip-value">6%</span>.</div>'],
        },
        {
            index: 5,
            name: "Hechizo de Aumento",
            ranks: 2,
            desc: "Reduce la reactivación del Golpe Encantado <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [0.3, 0.5],
        },
        {
            index: 7,
            name: "Rizo Oscuro Avanzado",
            ranks: 4,
            ranksnw: 2,
            desc: "Reduce la reactivación del Rizo Oscuro <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>Reduce la reactivación del Rizo Oscuro <span class="tooltip-value">2.5</span> segundo(s).</div>'],
        },
        {
            index: 8,
            name: "Expansión de la Oscuridad",
            ranks: 4,
            desc: "Incrementa la duración de la Maldición Oscura <span class='tooltip-value'>#</span> segundos. Reduce la Precisión del blanco un <span class='tooltip-value'>#%</span> adicional.",
            rankInfo: [5, 10, 15, 20],
            rankInfo2: [6, 12, 18, 24],
        },
        {
            index: 9,
            name: "Golpe Oscuro",
            ranks: 4,
            desc: "El primer ataque del Golpe Oscuro tiene un <span class='tooltip-value'>#%</span> de probabilidad de aturdir el blanco por 1 segundo. El segundo ataque tiene un <span class='tooltip-value'>#%</span> de probabilidad de aturdir el blanco por 1 segundo. El Golpe Encantado importe un <span class='tooltip-value'>#%</span> de daño extra a los blancos afectados por la Maldición Oscura.",
            rankInfo: [25, 50, 75, 100],
            rankInfo2: [12, 25, 37, 50],
            rankInfo3: [10, 20, 30, 40],
        },
        {
            index: 10,
            name: "Semilla de Oscuridad",
            ranks: 3,
            ranksnw: 1,
            desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Oscuridad</span><span class='right'>Reactivación: 30 segundos</span>\n<span class='left'>Maldición objetivo único</span><span class='right'>Alcance: 12 metros</span>\n\nCuesta 1 % de tu Salud máxima. Luego de 5 segundos, reduce la velocidad de movimiento del blanco 50.0% por <span class='tooltip-value'>#</span> segundos. La Maldición Oscura puede disparar este efecto tempranamente. Tiene un 10% de probabilidad de activar la forma Vampiro.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n'],
            rankInfo2: [235, 337, 441],
            rankInfo3: [8, 10, 12],
			rankInfo4: ['', '', '<div class="runelvl">\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br><span class="left"><span class="tooltip-value">548</span> Maná</span><span class="right">Tiempo de hechizar: 1 segundos</span>\n<br><span class="left">Oscuridad</span><span class="right">Reactivación: 30 segundos</span>\n<br><span class="left">Maldición objetivo único</span><span class="right">Alcance: 12 metros</span>\n\n<br><br>Cuesta 1 % de tu Salud máxima. Luego de 5 segundos, reduce la velocidad de movimiento del blanco 50.0% por <span class="tooltip-value">14</span> segundos. La Maldición Oscura puede disparar este efecto tempranamente. Tiene un 10% de probabilidad de activar la forma Vampiro.</div>'],
        },
        {
            index: 12,
            name: "Hemofilia",
            ranks: 3,
            desc: "Incrementa la duración del Festín en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>Incrementa la duración del Festín en <span class="tooltip-value">4</span> segundo(s).</div>'],
        },
        {
            index: 14,
            name: "Fuerza de la Oscuridad",
            ranks: 3,
            ranksnw: 2,
            desc: "La Semilla de la Oscuridad reduce la velocidad de movimiento del blanco en un <span class='tooltip-value'>#%</span> adicional. Los blancos afectados por la Semilla de la Oscuridad se silencian por <span class='tooltip-value'>#</span> segundo(s) luego de ser golpeados 4 veces.",
            rankInfo: [10, 20, 30],
            rankInfo2: [1, 2, 3],
			parent: 6,
        },
        {
            index: 15,
            name: "Invasión de la Oscuridad",
            ranks: 5,
            desc: "El Rizo Oscuro reduce la Resistencia a la Oscuridad del blanco en un <span class='tooltip-value'>#</span> adicional por 15 segundos. Incrementa la probabilidad del Rizo Oscuro de infligir la Maldición Oscura en el blanco en <span class='tooltip-value'>#%</span> cuando se despliega bajo la forma Vampiro.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [15, 30, 45, 60, 75],
            rankInfo2: [4, 8, 12, 16, 20],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>El Rizo Oscuro reduce la Resistencia a la Oscuridad del blanco en un <span class="tooltip-value">90</span> adicional por 15 segundos. Incrementa la probabilidad del Rizo Oscuro de infligir la Maldición Oscura en el blanco en <span class="tooltip-value">24%</span> cuando se despliega bajo la forma Vampiro.</div>'],
			parent: 3,
        },
        {
            index: 17,
            name: "Estimulación",
            ranks: 4,
            desc: "Incrementa la duración del Fortalecimiento en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 18,
            name: "Retoño",
            ranks: 2,
            desc: "Reduce la reactivación de la Semilla de la Oscuridad en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>Reduce la reactivación de la Semilla de la Oscuridad en <span class="tooltip-value">15</span> segundos.</div>'],
			parent: 8,
        },
        {
            index: 20,
            name: "Ojos de la Oscuridad",
            ranks: 3,
            desc: "Incrementa la Precisión de tus habilidades Oscuras en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>Incrementa la Precisión de tus habilidades Oscuras en <span class="tooltip-value">40</span>.</div>'],
        },
        {
            index: 21,
            name: "Ilusión de Ira",
            ranks: 4,
			ranksnw: 1,
            desc: "Incrementa el Chance Crítico de la Muerte Iracunda <span class='tooltip-value'>#%</span> y reduce su reactivación en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [1, 2, 3, 4],
            rankInfo2: [1, 2, 3, 4],
        },
        {
            index: 23,
            name: "Resultado del Contrato",
            ranks: 4,
            desc: "El Contrato Oscuro incrementa la Evasión del blanco en <span class='tooltip-value'>#</span> por 3 segundos si el blanco es un miembro del grupo.",
            rankInfo: [20, 40, 60, 80],
        },
        {
            index: 26,
            name: "Vínculos Oscuros Avanzados",
            ranks: 2,
            desc: "Incrementa la duración de Vínculos Oscuros que controlan los efectos en los jugadores en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [2, 4],
        },
        {
            index: 28,
            name: "Poder Vampiro",
            ranks: 3,
            desc: "La forma Vampiro incrementa tu Ataque en un <span class='tooltip-value'>#%</span> adicional.",
            rankInfo: [3, 6, 9],
        },
        {
            index: 29,
            name: "Muerte Iracunda Oscurecida",
            ranks: 2,
            desc: "La Muerte Iracunda reduce el Ataque de los blancos afectados por la Maldición Oscura en un <span class='tooltip-value'>#%</span> adicional y reduce su velocidad de movimiento en un <span class='tooltip-value'>#%</span> adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [10, 20],
            rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>La Muerte Iracunda reduce el Ataque de los blancos afectados por la Maldición Oscura en un <span class="tooltip-value">30%</span> adicional y reduce su velocidad de movimiento en un <span class="tooltip-value">30%</span> adicional.</div>'],
			parent: 13,
        },
        {
            index: 30,
            name: "Explosión de Maná",
            ranks: 2,
            ranksnw: 1,
            desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>El daño oscuro</span><span class='right'>Reactivación: 8 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nAfecta enemigos múltiples dentro de un rango de 10. Cuesta 1%  de tu Salud. Inflige 100%  de tu Ataque base más <span  class='tooltip-value'>#</span> de daño extra. Esta habilidad tiene el mismo efecto en maldiciones que la Muerte de Ira. La forma de Vampiro aumenta los efectos de esta habilidad. Tiene un 10% de probabilidad de activar la forma Vampiro.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [432, 520],
            rankInfo3: [1047, 1532],
			rankInfo4: ['', '<div class="runelvl">\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br><span class="left"><span class="tooltip-value">615</span> Maná</span><span class="right">Tiempo de hechizar: 1 segundos</span>\n<br><span class="left">El daño oscuro</span><span class="right">Reactivación: 8 segundos</span>\n<br><span class="left">Ataque multiobjetivo</span><span class="right">Alcance: Ninguno</span>\n\n<br><br>Afecta enemigos múltiples dentro de un rango de 10. Cuesta 1%  de tu Salud. Inflige 100%  de tu Ataque base más <span  class="tooltip-value">1987</span> de daño extra. Esta habilidad tiene el mismo efecto en maldiciones que la Muerte de Ira. La forma de Vampiro aumenta los efectos de esta habilidad. Tiene un 10% de probabilidad de activar la forma Vampiro.</div>'],
        },
        {
            index: 32,
            name: "Experticia de la Oscuridad",
            ranks: 3,
            desc: "Incrementa tu Dominio de la Oscuridad <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 34,
            name: "Dominio Explosión de Maná",
            ranks: 2,
            desc: "Incrementa el daño de base de la Explosión de Maná en <span class='tooltip-value'>#%</span> y su rango en <span class='tooltip-value'>#</span> meter(s).",
            rankInfo: [10, 20],
            rankInfo2: [1, 2],
			parent: 18,
        },
        {
            index: 35,
            name: "Oscuridad Repentina",
            ranks: 2,
            desc: "Reduce la reactivación de los Vínculos Oscuros y de la Explosión de Maná en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>Reduce la reactivación de los Vínculos Oscuros y de la Explosión de Maná en <span class="tooltip-value">30%</span>.</div>'],
        },
        {
            index: 37,
            name: "Estado de Vampiro Oscuro",
            ranks: 1,
            desc: "Durante la forma Vampiro, las habilidades que cuestan Salud lo dejan de hacer y en su lugar restauran el doble de la Salud normalmente consumida.",
            rankInfo: [],
        },
        {
            index: 38,
            name: "Defensa Inscrita ",
            ranks: 2,
            desc: "Reduce la reactivación del Rito de Sangre en <span class='tooltip-value'>#</span> segundos, y le otorga un <span class='tooltip-value'>#%</span> de probabilidad de repeler cualquier efecto de encierro o aturdidor que te afecten.",
            rankInfo: [20, 40],
            rankInfo2: [50, 100],
        },
        {
            index: 40,
            name: "Oscuridad Sin Fin",
            ranks: 2,
            desc: "Incrementa tu Resistencia a la Oscuridad <span class='tooltip-value'>#</span> y tu Evasión <span class='tooltip-value'>#</span>.",
            rankInfo: [25, 50],
            rankInfo2: [4, 8],
        },
        {
            index: 41,
            name: "Venas Coaguladas",
            ranks: 1,
            desc: "Eres inmune a los efectos lentos mientras la forma Vampiro esté activa.",
            rankInfo: [],
        },
        {
            index: 42,
            name: "Poder del Alma",
            ranks: 4,
            desc: "Incrementa el daño de base del Rizo Oscuro, el Golpe Encantador, la Muerte Iracunda, y la Cicatriz de Sombra en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15, 20],
        },
        {
            index: 43,
            name: "Rabia Sombra",
            ranks: 2,
            desc: "Reduce la reactivación de la Cicatriz de Sombra en <span class='tooltip-value'>#</span> segundos, e incrementa el Chance Crítico de sus ataques en <span class='tooltip-value'>#%</span> y <span class='tooltip-value'>#%</span> respectivamente.",
            rankInfo: [2, 4],
            rankInfo2: [2, 4],
            rankInfo3: [4, 8],
        },
        {
            index: 46,
            name: "Forma de Diablillo",
            ranks: 1,
            desc: "<span class='tooltip-value'>#</span><span class='left'>249 Maná</span><span class='right'>Tiempo de hechizar: Instantáneo</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 120 segundos</span>\n<span class='left'>Bendición objetivo único</span><span class='right'>Alcance: Ninguno</span>\n\nTe transformas en un diablillo y tu Evasión se incrementa en 100. La única habilidad que puedes usar el Golpe Encantado por 20 segundos. La reactivación del Golpe Encantado se vuelve de 3 segundos, y su daño de base se reduce a 10%. Reduce la Evasión de los blancos en un rango de 5 metros en 60 Cancela el efecto de esta habilidad usándola de nuevo.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // three
    [
        {
            index: 2,
            name: "Llamas Inextinguibles",
            ranks: 5,
			ranksnw: 2,
            desc: "Incrementa la duración de la Maldición Oscura <span class='tooltip-value'>#</span> segundos. Incrementa el rango de la Maldición Oscura <span class='tooltip-value'>#</span> metros(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [4, 8, 12, 16, 20],
            rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>Incrementa la duración de la Maldición Oscura <span class="tooltip-value">24</span> segundos. Incrementa el rango de la Maldición Oscura <span class="tooltip-value">6</span> metros(s).</div>'],
        },
        {
            index: 3,
            name: "Calcinación del Inframundo",
            ranks: 5,
            desc: "Incrementa el daño extra de la Llama Maligna en <span class='tooltip-value'>#</span> más <span class='tooltip-value'>#%</span> de tu Dominio del Fuego.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [50, 100, 150, 200, 250],
            rankInfo2: [40, 80, 120, 160, 200],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>Incrementa el daño extra de la Llama Maligna en <span class="tooltip-value">300</span> más <span class="tooltip-value">240%</span> de tu Dominio del Fuego.</div>'],
        },
        {
            index: 6,
            name: "Maldición de la Energía",
            ranks: 3,
            desc: "La Maldición oscura reduce la Resistencia al Fuego y a la Oscuridad del blanco en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>La Maldición oscura reduce la Resistencia al Fuego y a la Oscuridad del blanco en <span class="tooltip-value">40</span>.</div>'],
			parent: [0],
        },
        {
            index: 7,
            name: "Destello de Llama",
            ranks: 5,
			ranksnw: 1,
            desc: "Reduce la reactivación de la Llama Maligna <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 6/5 (necesitará runa)\n\n<br><br>Reduce la reactivación de la Llama Maligna <span class="tooltip-value">6</span> segundo(s).</div>'],
        },
        {
            index: 9,
            name: "Golpe Encantado Centellante",
            ranks: 4,
            desc: "El Golpe Encantado reduce la Defensa de los blancos afectados por la Maldición Oscura en <span class='tooltip-value'>#</span> por 30 segundos. Se acumula 5 veces. El Golpe Encantado inflige un 49 de daño extra a los blancos afectados por la Maldición de la Llama.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [3, 6, 9, 12],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>El Golpe Encantado reduce la Defensa de los blancos afectados por la Maldición Oscura en <span class="tooltip-value">15</span> por 30 segundos. Se acumula 5 veces. El Golpe Encantado inflige un 49 de daño extra a los blancos afectados por la Maldición de la Llama.</div>'],
        },
        {
            index: 10,
            name: "Semilla de la Llama",
            ranks: 3,
			ranksnw: 1,
            desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Fuego</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Maldición objetivo único</span><span class='right'>Alcance: 12 metros</span>\n\nLos blancos afectados por la Semilla de la Llama arden por <span class='tooltip-value'>#</span> de daño cada vez que los atacan o son atacados. Este efecto dura 20 segundos. La Semilla de la Llama	retira todos los efectos de maldición en el blanco y asesta daño instantáneamente por cada maldición removida. La Maldición de la Llama propina <span class='tooltip-value'>#</span> de daño, mientras que la Maldición de la Sangre y la Maldición Oscura propinan <span class='tooltip-value'>#</span> de daño. Tiene una 5% de probabilidad de activar la forma Vampiro.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n'],
            rankInfo2: [200, 287, 376],
            rankInfo3: [50, 80, 110],
            rankInfo4: [1202, 1922, 2634],
            rankInfo5: [601, 961, 1317],
			rankInfo6: ['', '', '<div class="runelvl">\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br><span class="left"><span class="tooltip-value">466</span> Maná</span><span class="right">Tiempo de hechizar: 1 segundos</span>\n<br><span class="left">Fuego</span><span class="right">Reactivación: 20 segundos</span>\n<br><span class="left">Maldición objetivo único</span><span class="right">Alcance: 12 metros</span>\n\n<br><br>Los blancos afectados por la Semilla de la Llama arden por <span class="tooltip-value">140</span> de daño cada vez que los atacan o son atacados. Este efecto dura 20 segundos. La Semilla de la Llama	retira todos los efectos de maldición en el blanco y asesta daño instantáneamente por cada maldición removida. La Maldición de la Llama propina <span class="tooltip-value">3339</span> de daño, mientras que la Maldición de la Sangre y la Maldición Oscura propinan <span class="tooltip-value">1669</span> de daño. Tiene una 5% de probabilidad de activar la forma Vampiro.</div>'],
        },
        {
            index: 12,
            name: "Llamarada Persistente",
            ranks: 4,
            desc: "Incrementa la duración de la Maldición de la Llama <span class='tooltip-value'>#</span> segundos. Reduce la Resistencia al Fuego en un <span class='tooltip-value'>#</span> adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [5, 10, 15, 20],
            rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>Incrementa la duración de la Maldición de la Llama <span class="tooltip-value">25</span> segundos. Reduce la Resistencia al Fuego en un <span class="tooltip-value">50</span> adicional.</div>'],
        },
        {
            index: 13,
            name: "Demonio de la Llama",
            ranks: 5,
            desc: "Incrementa la probabilidad de que la Maldición Oscura, la Llama Oscura, la Muerte del Fuego del Infierno, la Semilla de la Llama, y la Masacre Infernal activen la forma Vampiro en <span class='tooltip-value'>#%</span>.",
            rankInfo: [2, 4, 6, 8, 10],
        },
        {
            index: 15,
            name: "Maldición de la Necro Llama",
            ranks: 2,
            desc: "La Llama Maligna tiene un <span class='tooltip-value'>#%</span> de probabilidad de aplicar dos pilas de Llama Mágica a los blancos afectados por la Maldición oscura.",
            rankInfo: [50, 100],
			parent: 3,
        },
        {
            index: 16,
            name: "Glotonería",
            ranks: 3,
            desc: "El Festín extrae una cantidad adicional de Salud igual a <span class='tooltip-value'>#%</span> de tu Salud máxima. Reduce la duración del efecto de encierro que tengas sobre ti en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [0.5, 1, 1.5],
            rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>El Festín extrae una cantidad adicional de Salud igual a <span class="tooltip-value">2%</span> de tu Salud máxima. Reduce la duración del efecto de encierro que tengas sobre ti en <span class="tooltip-value">4</span> segundo(s).</div>'],
        },
        {
            index: 18,
            name: "Tortura de Llama",
            ranks: 4,
			ranksnw: 1,
            desc: "Los blancos afectados por la Semilla de la Llama sufren un <span class='tooltip-value'>#%</span> de daño extra cuando atacan o son atacados.",
            rankInfo: [25, 50, 75, 100],
			parent: 5,
        },
        {
            index: 19,
            name: "Alas de Fantasma",
            ranks: 3,
            desc: "Cuando una forma d murciélago termina, retienes el 60% of de la velocidad de movimiento adicional por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [5, 7, 9],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>Cuando una forma d murciélago termina, retienes el 60% of de la velocidad de movimiento adicional por <span class="tooltip-value">11</span> segundos.</div>'],
        },
        {
            index: 21,
            name: "Muerte Maligna Abrazadora",
            ranks: 4,
            desc: "La Muerte Iracunda reduce la Defensa de los blancos afectados por la Maldición de la Llama en un <span class='tooltip-value'>#%</span> adicional por <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [25, 50, 75, 100],
            rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Nivel: 5/4 (necesitará runa)\n\n<br><br>La Muerte Iracunda reduce la Defensa de los blancos afectados por la Maldición de la Llama en un <span class="tooltip-value">125%</span> adicional por <span class="tooltip-value">5</span> segundo(s).</div>'],
        },
        {
            index: 23,
            name: "Flame Suppression",
            ranks: 2,
            desc: "Reduce la cantidad de amenaza generada por tus habilidades de Fuego y Maldiciones y reduce sus costos de Maná en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20],
        },
        {
            index: 26,
            name: "Eclipse Mágico",
            ranks: 4,
            desc: "Cuando un blanco afectado por la Semilla de la Llama ataca o es atacado, pierde una cantidad de Maná igual a <span class='tooltip-value'>#%</span> de tu Dominio del Fuego.",
            rankInfo: [15, 30, 45, 60],
			parent: 10,
        },
        {
            index: 28,
            name: "Entereza de la Necro Llama",
            ranks: 4,
            desc: "Incrementa tu Resistencia al fuego <span class='tooltip-value'>#</span> y tu defensa <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30, 40],
            rankInfo2: [1, 2, 3, 4],
        },
        {
            index: 30,
            name: "Murciélago del Infierno",
            ranks: 2,
			ranksnw: 1,
            desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: Instantáneo</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nTe transformas en un Murciélago del Infierno por <span class='tooltip-value'>#</span> segundos. Tu Ataque se incrementa en <span class='tooltip-value'>#%</span> tu velocidad de movimiento se incrementa en <span class='tooltip-value'>#%</span> y el rango de tus habilidades se incrementa en 50%. En esta forma, solo puedes usar habilidades de Fuego. La Llama maligna no tiene un reactivación, pero propina 40% menos de daño extra. Su tiempo de despliegue se reduce a 1 segundo. La Semilla de la Llama inflige <span class='tooltip-value'>#</span> de daño y aturde al blanco por 2 segundos. Reduce la reactivación de las Alas de Vendaval a 6 segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [162, 199],
            rankInfo3: [150, 120],
            rankInfo4: [20, 25],
            rankInfo5: [5, 7],
            rankInfo6: [20, 30],
            rankInfo7: [1202, 1922],
			rankInfo8: ['', '<div class="runelvl">\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br><span class="left"><span class="tooltip-value">239</span> Maná</span><span class="right">Tiempo de hechizar: Instantáneo</span>\n<br><span class="left">Ataque</span><span class="right">Reactivación: <span class="tooltip-value">90</span> segundos</span>\n<br><span class="left">Auto bendición</span><span class="right">Alcance: Ninguno</span>\n\n<br><br>Te transformas en un Murciélago del Infierno por <span class="tooltip-value">30</span> segundos. Tu Ataque se incrementa en <span class="tooltip-value">9%</span> tu velocidad de movimiento se incrementa en <span class="tooltip-value">40%</span> y el rango de tus habilidades se incrementa en 50%. En esta forma, solo puedes usar habilidades de Fuego. La Llama maligna no tiene un reactivación, pero propina 40% menos de daño extra. Su tiempo de despliegue se reduce a 1 segundo. La Semilla de la Llama inflige <span class="tooltip-value">2634</span> de daño y aturde al blanco por 2 segundos. Reduce la reactivación de las Alas de Vendaval a 6 segundos.</div>'],
        },
        {
            index: 31,
            name: "Debilitado",
            ranks: 3,
            desc: "Los Vínculos Oscuros reducen las Resistencias del blanco en <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [20, 40, 60],
            rankInfo2: [20, 35, 50],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Nivel: 4/3 (necesitará runa)\n\n<br><br>Los Vínculos Oscuros reducen las Resistencias del blanco en <span class="tooltip-value">80</span> por <span class="tooltip-value">65</span> segundos.</div>'],
        },
        {
            index: 33,
            name: "Hasted Hellfire",
            ranks: 2,
			ranksnw: 1,
            desc: "Reduce la reactivación de la Muerte de Fuego del Infierno en <span class='tooltip-value'>#</span> segundo(s) e incrementa el daño de base <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b><span class='tooltip-value'>#</span>",
            rankInfo: [1, 2],
            rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Nivel: 3/2 (necesitará runa)\n\n<br><br>Reduce la reactivación de la Muerte de Fuego del Infierno en <span class="tooltip-value">3</span> segundo(s) e incrementa el daño de base <span class="tooltip-value">45%</span>.</div>'],
        },
        {
            index: 34,
            name: "Figura de Murciélago",
            ranks: 3,
			ranksnw: 1,
            desc: "Reduce la reactivación del Murciélago del Infierno en <span class='tooltip-value'>#</span> segundos. Mientras tengas la forma Murciélago del Infierno, infliges una cantidad de daño igual a <span class='tooltip-value'>#</span> más <span class='tooltip-value'>#%</span> de tu Dominio del Fuego cada 3 segundos a los blancos dentro de 10 metros que estén afectados por la Maldición Oscura.",
            rankInfo: [10, 20, 30],
            rankInfo2: [300, 600, 900],
            rankInfo3: [10, 20, 30],
			parent: 16,
        },
        {
            index: 37,
            name: "Pulso del Fuego del Infierno",
            ranks: 2,
            desc: "La Muerte del Fuego del Infierno hace retroceder al blanco <span class='tooltip-value'>#</span> metros, y tiene un <span class='tooltip-value'>#%</span> de probabilidad de aturdir el blanco por 3 segundos.",
            rankInfo: [2, 4],
            rankInfo2: [20, 40],
			parent: 18,
        },
        {
            index: 38,
            name: "Murciélago Fuego del Infierno",
            ranks: 2,
            desc: "Reduce la reactivación de la Muerte del Fuego del Infierno en <span class='tooltip-value'>#</span> segundo(s), su tiempo de despliegue en <span class='tooltip-value'>#</span> segundo(s), e incrementa su rango en <span class='tooltip-value'>#%</span> mientras esté en la forma Murciélago del Infierno.",
            rankInfo: [1, 2],
            rankInfo2: [0.5, 1],
            rankInfo3: [25, 50],
			parent: 19,
        },
        {
            index: 40,
            name: "Maniobra de la Llama",
            ranks: 3,
            desc: "Incrementa tu Dominio del Fuego <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 42,
            name: "Furia del Fuego del Infierno",
            ranks: 3,
            desc: "Incrementa el daño extra de la Llama Maligna y de la Muerte del Fuego del Infierno en un <span class='tooltip-value'>#%</span> adicional, e incrementa su Chance Crítico en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15],
            rankInfo2: [3, 6, 9],
        },
        {
            index: 43,
            name: "Maldición Abrasadora",
            ranks: 3,
            desc: "La Maldición Oscura y la Muerte del Fuego del Infierno infligen el efecto de la Maldición del Fuego del Alma en sus blancos, los cuales absorben una cantidad de Salud igual a <span class='tooltip-value'>#</span> veces tu Dominio del Fuego y extrae <span class='tooltip-value'>#</span> Maná del blanco.",
            rankInfo: [3, 4, 5],
            rankInfo2: [400, 800, 1200],
        },
        {
            index: 46,
            name: "Masacre Infernal",
            ranks: 1,
            desc: "<span class='tooltip-value'>#</span><span class='left'>365 Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>El daño de fuego</span><span class='right'>Reactivación: 12 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Alcance: 12 metros</span>\n\n\Inflige 120% de tu Ataque más 2119 de daño extra. Inflige una cantidad de daño igual a 1500 más 100% de tu Dominio del Fuego a los blancos afectados por la Maldición de la Llama. Aturde un blanco afectado por la Maldición de la Sangre, la Maldición Oscura, y la Maldición de la Llama al mismo tiempo por 3 segundos. Tiene una probabilidad de 5% de disparar la forma Vampiro.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ]
];