var data = [
	// one
	[
		{
			index: 1,
			name: "Ураганный ветер",
			ranks: 5,
			ranksnw: 2,
			desc: "«Ветер смерти» уменьшает сопротивление Воздуху цели на <span class='tooltip-value'>#</span> ед.; продолжительность - 12 сек.",
			rankInfo: [8, 16, 24, 32, 40],
		},
		{
			index: 3,
			name: "Буря",
			ranks: 5,
			desc: "«Хватка ветра» снижает скорость передвижения цели на 50%, продолжительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [3, 4, 5, 6, 7],
		},
		{
			index: 6,
			name: "Беспощадность",
			ranks: 3,
			desc: "Навык «Дурная кровь» увеличивает скорость передвижения персонажа на 60%; продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 4, 5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Навык «Дурная кровь» увеличивает скорость передвижения персонажа на 60%; продолжительность – <span class="tooltip-value">6</span> сек.</div>'],
		},
		{
			index: 7,
			name: "Пульс ветра",
			ranks: 3,
			desc: "«Кровь древних» дополнительно повышает уклонение на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 8,
			name: "Концентрация",
			ranks: 4,
			desc: "Увеличивает меткость на <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 9,
			name: "Тайфун",
			ranks: 4,
			desc: "Увеличивает базовую атаку навыка «Ветер смерти» на <span class='tooltip-value'>#%</span>, снижает время его восстановления на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Увеличивает базовую атаку навыка «Ветер смерти» на <span class="tooltip-value">25%</span>, снижает время его восстановления на <span class="tooltip-value">5</span> сек.</div>'],
			parent: [0],
		},
		{
			index: 10,
			name: "Ревущий ветер",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 60 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nАтакующие навыки стихии Воздуха, наносящие урон одной цели, теперь наносят урон нескольким целям (кроме навыка «Кровь огня»). Навык наносит урон целям в радиусе 4 м. (не более 5 целей). Дальность действия атакующих навыков стихии Воздуха увеличена на 3 м. Продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [59, 100, 142, 185],
			rankInfo3: [20, 30, 40, 50],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">229</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 60 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – ближняя</span>\n\n<br><br>Атакующие навыки стихии Воздуха, наносящие урон одной цели, теперь наносят урон нескольким целям (кроме навыка «Кровь огня»). Навык наносит урон целям в радиусе 4 м. (не более 5 целей). Дальность действия атакующих навыков стихии Воздуха увеличена на 3 м. Продолжительность – <span class="tooltip-value">60</span> сек.</div>'],
		},
		{
			index: 12,
			name: "Путы",
			ranks: 3,
			desc: "Увеличивает время действия эффектов замедления от навыка «Упрямство ветра» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 14,
			name: "Ловец ветра",
			ranks: 3,
			ranksnw: 2,
			desc: "«Ревущий ветер» увеличивает скорость передвижения персонажа на <span class='tooltip-value'>#%</span>, а также увеличивает баз овую атаку на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [2, 4, 6],
			parent: 6,
		},
		{
			index: 16,
			name: "Контроль бури",
			ranks: 4,
			desc: "Увеличивает мастерство Воздуха на <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Провокация",
			ranks: 4,
			desc: "Во время действия эффекта «Быстрая кровь» дальность действия навыков «Упрямство ветра» и «Хватка ветра» увеличивается на <span class='tooltip-value'>#</span> м. Если количество ОЗ больше 60%, цель также получает урон в размере количества ОЗ больше 50%, умноженных на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: [5, 10, 15, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Во время действия эффекта «Быстрая кровь» дальность действия навыков «Упрямство ветра» и «Хватка ветра» увеличивается на <span class="tooltip-value">2.5</span> м. Если количество ОЗ больше 60%, цель также получает урон в размере количества ОЗ больше 50%, умноженных на <span class="tooltip-value">25%</span>.</div>'],
		},
		{
			index: 20,
			name: "Воронка урагана",
			ranks: 3,
			desc: "Увеличивает эффект ускорения навыка «Кулак ветра» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 21,
			name: "Рывок ветра",
			ranks: 3,
			desc: "«Яростный ветер» увеличивает базовую атаку на <span class='tooltip-value'>#%</span>, снижает время восстановления на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Яростный ветер» увеличивает базовую атаку на <span class="tooltip-value">40%</span>, снижает время восстановления на <span class="tooltip-value">4</span> сек.</div>'],
		},
		{
			index: 22,
			name: "Неудержимый ветер",
			ranks: 3,
			desc: "«Ревущий ветер» увеличивает дальность действия навыка «Яростный ветер» на <span class='tooltip-value'>#</span> м. Навык «Лезвие ассасина» с вероятностью <span class='tooltip-value'>#%</span> вызывает у цели головокружение; продолжительность - 2 сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 8,
		},
		{
			index: 23,
			name: "Жестокий ветер",
			ranks: 2,
			desc: "Все навыки стихии Ветра, требующие, чтобы ОЗ цели были выше 50%, активируются, если ОЗ цели выше <span class='tooltip-value'>#%</span>. Требующие, чтобы ОЗ цели были выше 40%, активируются, если ОЗ цели выше <span class='tooltip-value'>#%</span>.",
			rankInfo: [55, 50],
			rankInfo2: [35, 30],
		},
		{
			index: 25,
			name: "Танцующий с ветром",
			ranks: 3,
			ranksnw: 1,
			desc: "При каждом применении атакующего навыка стихии Ветер с вероятностью <span class='tooltip-value'>#%</span> накладывается эффект «Танцующий с ветром», продолжительность - 10 сек, эффект суммируется до 10 раз. Все десять действующих эффектов увеличат базовую атаку навыков ветра на 100%.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При каждом применении атакующего навыка стихии Ветер с вероятностью <span class="tooltip-value">100%</span> накладывается эффект «Танцующий с ветром», продолжительность - 10 сек, эффект суммируется до 10 раз. Все десять действующих эффектов увеличат базовую атаку навыков ветра на 100%.</div>'],
		},
		{
			index: 26,
			name: "Поступь ветра",
			ranks: 2,
			desc: "Повышает скорость передвижения жнеца и скакуна на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 28,
			name: "Ветер чумы",
			ranks: 2,
			desc: "Атака «Кулака ветра» снижает эффективность исцеления, получаемого целью на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 30,
			name: "Водоворот крови",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 0.50 сек.</span>\n<span class='left'>Тьма</span><span class='right'>Время перезарядки: 180 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – 16 м.</span>\n\nПритягивает противников, находящихся на удалении 16 и 10 м. Вызывает головокружение на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [109, 197],
			rankInfo3: [2, 2.5],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">281</span> ОМ</span><span class="right">Чтение: 0.50 сек.</span>\n<br><span class="left">Тьма</span><span class="right">Время перезарядки: 180 сек.</span>\n<br><span class="left">Массовое проклятие</span><span class="right">Расстояние атаки – 16 м.</span>\n\n<br><br>Притягивает противников, находящихся на удалении 16 и 10 м. Вызывает головокружение на <span class="tooltip-value">3.0</span> сек.</div>'],
		},
		{
			index: 31,
			name: "Стена ветра",
			ranks: 5,
			desc: "Увеличивает базовую атаку на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4, 5],
		},
		{
			index: 33,
			name: "Зов ветра",
			ranks: 2,
			desc: "Каждый эффект «Танцующий с ветром» с вероятностью <span class='tooltip-value'>#%</span> создает еще один эффект «Танцующий с ветром».",
			rankInfo: [20, 40],
			parent: 15,
		},
		{
			index: 34,
			name: "Утрата ветра",
			ranks: 3,
			desc: "«Водоворот крови» увеличивает дальность действия заклинания на <span class='tooltip-value'>#</span> м., а также снижает время восстановления навыка на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 18,
		},
		{
			index: 35,
			name: "Изменчивость",
			ranks: 3,
			desc: "Если цели нанесен удар навыком «Водоворот крови» или «Хватка ветра», ее крит. защита снижается на <span class='tooltip-value'>#%</span>; продолжительность - 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Если цели нанесен удар навыком «Водоворот крови» или «Хватка ветра», ее крит. защита снижается на <span class="tooltip-value">24%</span>; продолжительность - 10 сек.</div>'],
		},
		{
			index: 38,
			name: "Ярость ветра",
			ranks: 2,
			desc: "Увеличивает урон, наносимый навыками стихии Воздух, на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 40,
			name: "Проклятие ветра",
			ranks: 3,
			desc: "«Искупление кровью» увеличивает мастерство Воздуха персонажа на <span class='tooltip-value'>#</span> ед.; продолжительность - 30 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 60, 90],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Искупление кровью» увеличивает мастерство Воздуха персонажа на <span class="tooltip-value">120</span> ед.; продолжительность - 30 сек.</div>'],
		},
		{
			index: 41,
			name: "Бесстрашие",
			ranks: 3,
			desc: "Уменьшает время восстановления навыка «Ветер смерти» на <span class='tooltip-value'>#</span> сек., а также уменьшает время восстановления навыка «Яростный ветер» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [1.5, 3, 4.5],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время восстановления навыка «Ветер смерти» на <span class="tooltip-value">4</span> сек., а также уменьшает время восстановления навыка «Яростный ветер» на <span class="tooltip-value">6</span> сек.</div>'],
		},
		{
			index: 42,
			name: "Воронка ветра",
			ranks: 2,
			desc: "Навыки «Ветер смерти» и «Яростный ветер» с вероятностью <span class='tooltip-value'>#%</span> сбрасывают время восстановления навыка «Хватка ветра».",
			rankInfo: [5, 10],
		},
		{
			index: 46,
			name: "Лезвие ассасина",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>416 ОМ</span><span class='right'>Чтение: 2.50 сек.</span>\n<span class='left'>Урон от воздуха</span><span class='right'>Время перезарядки: 25 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – ближняя</span>\n\nАтака, состоящая из трех этапов. Атакует цель в радиусе 12 м. Каждая атака наносит 100% базового урона и дополнительно 1507. Если запас ОЗ цели выше 40%, каждая атака наносит урон кровотечением в размере 25% от максимальной силы атаки жнеца. Если запас ОЗ цели выше 60%, каждая атака наносит урон кровотечением в размере 50% от максимальной силы атаки жнеца. Каждое очко мастерства жнеца дополнительно увеличивает урон от кровотечения на 0.1%.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Черный песок",
			ranks: 4,
			desc: "Уменьшает время восстановления навыка «Лезвие ассасина» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6, 8],
			parent: 27,
		},
		{
			index: 49,
			name: "Лезвие урагана",
			ranks: 3,
			desc: "Повышает шанс крит. удара на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 51,
			name: "Ничтожность",
			ranks: 2,
			desc: "Во время действия эффекта «Танцующий с ветром» каждый действующий эффект «Танцующий с ветром» повышает критический урон жнеца на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Во время действия эффекта «Танцующий с ветром» каждый действующий эффект «Танцующий с ветром» повышает критический урон жнеца на <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 54,
			name: "Боевой призыв",
			ranks: 1,
			desc: "Увеличивает базовую атаку навыка «Лезвие ассасина» на 50%. Удар, нанесенный с помощью навыка «Лезвие ассасина», парализует цель на 5 сек.",
			rankInfo: [],
			parent: 27,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Защитная стойка",
			ranks: 5,
			ranksnw: 3,
			desc: "«Рубящий взмах» увеличивает базовую защиту персонажа на <span class='tooltip-value'>#%</span>. Эффект суммируется до 5 раз, продолжительность – 20 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.6, 1.2, 1.8, 2.4, 3],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>«Рубящий взмах» увеличивает базовую защиту персонажа на <span class="tooltip-value">3.6%</span>. Эффект суммируется до 5 раз, продолжительность – 20 сек.</div>'],
		},
		{
			index: 4,
			name: "Вихрь теней",
			ranks: 5,
			desc: "«Тень мертвеца» увеличивает дальность действия на <span class='tooltip-value'>#</span> м.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 6,
			name: "Быстрые тени",
			ranks: 5,
			desc: "Уменьшает время восстановления навыка «Тень мертвеца» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 8,
			name: "Защита крови",
			ranks: 5,
			desc: "«Быстрая кровь» дополнительно повышает базовую защиту на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>«Быстрая кровь» дополнительно повышает базовую защиту на <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 9,
			name: "Мастер-рубака",
			ranks: 3,
			ranksnw: 2,
			desc: "Уменьшает время восстановления навыка «Рубящий взмах» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [0.5, 1, 1.5],
			parent: [0],
		},
		{
			index: 10,
			name: "Кровавый панцирь",
			ranks: 4,
			ranksnw: 2,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nВ течение 20 сек. поглощает урон, равный <span class='tooltip-value'>#%</span> от максимального количества ОЗ. Если персонажа атакуют, защита нападающего снизится на <span class='tooltip-value'>#</span> ед. Продолжительность – 20 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [45, 104, 161, 219],
			rankInfo3: [15, 20, 25, 30],
			rankInfo4: [50, 100, 150, 200],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">277</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 90 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>В течение 20 сек. поглощает урон, равный <span class="tooltip-value">35%</span> от максимального количества ОЗ. Если персонажа атакуют, защита нападающего снизится на <span class="tooltip-value">250</span> ед. Продолжительность – 20 сек.</div>'],
		},
		{
			index: 11,
			name: "Твердая оболочка",
			ranks: 3,
			desc: "Увеличивает крит. защиту на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 15,
			name: "Удар тени",
			ranks: 4,
			ranksnw: 2,
			desc: "Эффект исцеления навыка «Тень палача» активируется, если запас ОЗ ниже <span class='tooltip-value'>#%</span>. Если запас ОЗ ниже <span class='tooltip-value'>#%</span>, эффективность исцеления повышается вдвое.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [85, 90, 95, 100],
			rankInfo2: [15, 20, 25, 30],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Эффект исцеления навыка «Тень палача» активируется, если запас ОЗ ниже <span class="tooltip-value">100%</span>. Если запас ОЗ ниже <span class="tooltip-value">35%</span>, эффективность исцеления повышается вдвое.</div>'],
		},
		{
			index: 16,
			name: "Стена Тьмы",
			ranks: 3,
			desc: "Увеличивает сопротивление Тьме и сопротивление Воздуху персонажа на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Провоцирующий удар",
			ranks: 3,
			desc: "«Рубящий взмах» с вероятностью <span class='tooltip-value'>#%</span> прерываетзаклинание цели и накладывает на нее эффект «Насмешка» на 3 сек.",
			rankInfo: [5, 10, 15],
			parent: 4,
		},
		{
			index: 18,
			name: "Кровавый голод",
			ranks: 3,
			desc: "«Кровавый панцирь» восстанавливает ОЗ персонажа в размере <span class='tooltip-value'>#%</span> от его максимального количества ОЗ. В течение 12 сек. ежесекундно цель теряет 1% ОЗ. Третья атака может прекратить эффект кровотечения.",
			rankInfo: [10, 20, 30],
			parent: 5,
		},
		{
			index: 19,
			name: "Разбитая стена",
			ranks: 2,
			desc: "Во время действия эффекта исцеления навыка «Тень палача» повышается крит. уклонение персонажа на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
			parent: 7,
		},
		{
			index: 22,
			name: "Запекшаяся кровь",
			ranks: 4,
			desc: "«Тень мертвеца» с вероятностью <span class='tooltip-value'>#%</span> парализует цель на 1 сек. при нанесении удара по цели.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 23,
			name: "Ярость тени",
			ranks: 3,
			desc: "Атакующие навыки стихии Тьмы увеличивают количество генерируемой ненависти, а также урон, наносимый навыком, на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [70, 140, 210],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Атакующие навыки стихии Тьмы увеличивают количество генерируемой ненависти, а также урон, наносимый навыком, на <span class="tooltip-value">280%</span>.</div>'],
		},
		{
			index: 26,
			name: "Рокот волн",
			ranks: 3,
			desc: "Увеличивает базовое количество ОЗ персонажа на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 28,
			name: "Незаметная тень",
			ranks: 4,
			desc: "Повышает крит. уклонение на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 29,
			name: "Кровавые реки",
			ranks: 3,
			desc: "Увеличивает время действия навыка «Кровавая война» на <span class='tooltip-value'>#</span> сек. и повышает меткость на <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [300, 600, 900],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает время действия навыка «Кровавая война» на <span class="tooltip-value">1200</span> сек. и повышает меткость на <span class="tooltip-value">40</span>.</div>'],
		},
		{
			index: 30,
			name: "Путь теней",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Тьма</span><span class='right'>Время перезарядки: 60 сек.</span>\n<span class='left'>Кольцо благословения</span><span class='right'>Расстояние атаки – нет</span>\n\nНавык можно отключить. В радиусе <span class='tooltip-value'>#</span> м. ежесекундно уменьшает скорость цели на 5%, длительность – 4 сек. Эффект суммируется до 10 раз, длительность – 30 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [128, 164],
			rankInfo3: [12, 14],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">200</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Тьма</span><span class="right">Время перезарядки: 60 сек.</span>\n<br><span class="left">Кольцо благословения</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Навык можно отключить. В радиусе <span class="tooltip-value">16</span> м. ежесекундно уменьшает скорость цели на 5%, длительность – 4 сек. Эффект суммируется до 10 раз, длительность – 30 сек.</div>'],
		},
		{
			index: 31,
			name: "Прыткость",
			ranks: 2,
			desc: "Уменьшает время восстановления навыков «Тень палача» и «Верткая тень» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшает время восстановления навыков «Тень палача» и «Верткая тень» на <span class="tooltip-value">3</span> сек.</div>'],
		},
		{
			index: 33,
			name: "Кровавый источник",
			ranks: 2,
			ranksnw: 1,
			desc: "Эффект исцеления навыка «Верткая тень» активируется, если запас ОЗ ниже <span class='tooltip-value'>#%</span>. Если запас ОЗ персонажа ниже <span class='tooltip-value'>#%</span>, эффективность исцеления повышается вдвое.",
			rankInfo: [85, 90],
			rankInfo2: [20, 25],
		},
		{
			index: 34,
			name: "Глубокая тьма",
			ranks: 3,
			ranksnw: 2,
			desc: "Время действия навыка «Путь теней» увеличивается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
			parent: 17,
		},
		{
			index: 36,
			name: "Бегущая тень",
			ranks: 3,
			desc: "Каждое очко сопротивления Тьме увеличивает максимальное количество ОЗ персонажа на <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 38,
			name: "Пронзительный свет",
			ranks: 3,
			desc: "Увеличивает дальность действия навыка «Путь теней» на <span class='tooltip-value'>#</span> м.; при наложении эффекта замедления прибавляется очко ненависти.",
			rankInfo: [1, 2, 3],
			parent: 20,
		},
		{
			index: 39,
			name: "Смеющаяся тень",
			ranks: 2,
			desc: "«Хватка ветра» провоцирует действие эффекта «Насмешка»; эффект действует в течение <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 3],
		},
		{
			index: 41,
			name: "Ускользающая тень",
			ranks: 2,
			desc: "Навык «Неистовое сердце» может сбросить время восстановления навыка «Тень палача».",
			rankInfo: [],
			parent: 19,
		},
		{
			index: 42,
			name: "Кипение крови",
			ranks: 3,
			desc: "Во время действия эффекта «Быстрая кровь» максимальный запас ОЗ персонажа увеличивается на <span class='tooltip-value'>#%</span>; эффективность получаемого исцеления увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12],
			rankInfo2: [8, 16, 24],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Во время действия эффекта «Быстрая кровь» максимальный запас ОЗ персонажа увеличивается на <span class="tooltip-value">16%</span>; эффективность получаемого исцеления увеличивается на <span class="tooltip-value">32%</span>.</div>'],
		},
		{
			index: 46,
			name: "Ядовитый коготь",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>299 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Тьмы</span><span class='right'>Время перезарядки: 30 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 20 м.</span>\n\nПритягивает цель в радиусе 20 м. к персонажу. Наносит 100% базового урона и дополнительно 2999. Цель оказывается под действием эффекта «Насмешка», и ее базовая атака снижается на 30%. Уменьшает эффект от получаемого лечения на 20%. Длительность – 5 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Тень отравителя",
			ranks: 4,
			desc: "Уменьшает время восстановления навыка «Ядовитый коготь» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6, 8],
			parent: 26,
		},
		{
			index: 51,
			name: "Дурной удар",
			ranks: 3,
			desc: "Увеличивает дальность действия навыка «Пляска теней» на <span class='tooltip-value'>#</span> м.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает дальность действия навыка «Пляска теней» на <span class="tooltip-value">4</span> м.</div>'],
		},
		{
			index: 52,
			name: "Железный кулак",
			ranks: 2,
			desc: "Увеличивает PVE-стойкость персонажа на <span class='tooltip-value'>#</span>.",
			rankInfo: [100, 200],
		},
		{
			index: 54,
			name: "Смертельная отрава",
			ranks: 1,
			desc: "Увеличивает базовую атаку навыка «Ядовитый коготь» на 100% и вызывает головокружение у цели на 4 сек. «Ядовитый коготь» может спровоцировать действие эффекта «Гниющая плоть». Увеличивает РУЕ-стойкость персонажа на 50 ед., продолжительность - 45 сек.; эффект суммируется до 5 раз.",
			rankInfo: [],
			parent: 26,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Боевая решимость",
			ranks: 5,
			desc: "Время действия навыка «Воля чемпиона» увеличивается на <span class='tooltip-value'>#</span> сек.; дополнительно увеличивает крит. урон на <span class='tooltip-value'>#%</span> от количества крит. защиты, даваемого навыком «Воля чемпиона».",
			rankInfo: [300, 600, 900, 1200, 1500],
			rankInfo2: [20, 40, 60, 80, 90],
		},
		{
			index: 4,
			name: "Мастерство боя",
			ranks: 5,
			ranksnw: 2,
			desc: "Увеличивает силу атаки навыка «Рубящий взмах» на <span class='tooltip-value'>#</span>; сила атаки увеличивается на <span class='tooltip-value'>#%</span> отзначения мастерства Тьмы.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 80, 120, 160, 200],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивает силу атаки навыка «Рубящий взмах» на <span class="tooltip-value">240</span>; сила атаки увеличивается на <span class="tooltip-value">60%</span> отзначения мастерства Тьмы.</div>'],
		},
		{
			index: 5,
			name: "Чистая кровь",
			ranks: 3,
			ranksnw: 2,
			desc: "«Дурная кровь» теперь увеличивает силу атаки персонажа на <span class='tooltip-value'>#%</span>; продолжительность - 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Дурная кровь» теперь увеличивает силу атаки персонажа на <span class="tooltip-value">20%</span>; продолжительность - 10 сек.</div>'],
		},
		{
			index: 6,
			name: "Долгие страдания",
			ranks: 4,
			desc: "Во время действия эффекта «Быстрая кровь» мастерство Тьмы и Воздуха персонажа увеличивается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 7,
			name: "Долгое кровотечение",
			ranks: 3,
			desc: "Увеличивает бонус к атаке навыка «Кровь Тьмы» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 10,
			name: "Лютая ненависть",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 0.50 сек.</span>\n<span class='left'>Тьма</span><span class='right'>Время перезарядки: 25 сек.</span>\n<span class='left'>Проклятие</span><span class='right'>Расстояние атаки – 22 м.</span>\n\nАтакует цель. Она получает <span class='tooltip-value'>#%</span> урона Тьмы от контузии, длительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [69, 120, 172, 225],
			rankInfo3: [9, 10, 11, 12],
			rankInfo4: [3, 4, 5, 6],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">280</span> ОМ</span><span class="right">Чтение: 0.50 сек.</span>\n<br><span class="left">Тьма</span><span class="right">Время перезарядки: 25 сек.</span>\n<br><span class="left">Проклятие</span><span class="right">Расстояние атаки – 22 м.</span>\n\n<br><br>Атакует цель. Она получает <span class="tooltip-value">13%</span> урона Тьмы от контузии, длительность – <span class="tooltip-value">7</span> сек.</div>'],
		},
		{
			index: 11,
			name: "Марадерство",
			ranks: 3,
			desc: "Увеличивает крит. урон, наносимый навыком «Тень палача», на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает крит. урон, наносимый навыком «Тень палача», на <span class="tooltip-value">20%</span>.</div>'],
		},
		{
			index: 12,
			name: "Жестокая резня",
			ranks: 4,
			ranksnw: 2,
			desc: "Увеличивает шанс крит. удара навыка «Рубящий взмах» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12],
			parent: 1,
		},
		{
			index: 13,
			name: "Потоки крови",
			ranks: 3,
			desc: "Уменьшает время восстановления навыков «Быстрая кровь» и «Дурная кровь» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время восстановления навыков «Быстрая кровь» и «Дурная кровь» на <span class="tooltip-value">80</span> сек.</div>'],
			parent: 2,
		},
		{
			index: 15,
			name: "Клинок ветра",
			ranks: 3,
			desc: "Увеличивает дальность действия навыка «Упрямство ветра» на <span class='tooltip-value'>#</span> м.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 17,
			name: "Похищение крови",
			ranks: 4,
			desc: "Повышает шанс крит. удара навыка «Тень палача» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
		},
		{
			index: 18,
			name: "Кровоточащая рана",
			ranks: 4,
			desc: "Повышает эффективность эффекта глубоких ран навыка «Лютая ненависть» на <span class='tooltip-value'>#%</span>, увеличивает дальность действия заклинания на <span class='tooltip-value'>#</span> м.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [1, 2, 3, 4],
			parent: 5,
		},
		{
			index: 20,
			name: "Дух крови",
			ranks: 3,
			desc: "«Рубящий взмах» с вероятностью <span class='tooltip-value'>#%</span> сбрасывает время восстановления навыка «Тень палача».",
			rankInfo: [15, 30, 45],
			parent: 7,
		},
		{
			index: 22,
			name: "Едкая кровь",
			ranks: 3,
			desc: "Навыки стихии Тьмы снижают сопротивление Тьмы цели на <span class='tooltip-value'>#</span> ед.; эффект суммируется до 5 раз, продолжительность - 60 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Навыки стихии Тьмы снижают сопротивление Тьмы цели на <span class="tooltip-value">40</span> ед.; эффект суммируется до 5 раз, продолжительность - 60 сек.</div>'],
		},
		{
			index: 23,
			name: "Кровь бойца",
			ranks: 3,
			desc: "Увеличивает базовую атаку навыка «Рубящий взмах» на <span class='tooltip-value'>#%</span>, уменьшает время его восстановления на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30],
			rankInfo2: [0.5, 1, 1.5],
		},
		{
			index: 25,
			name: "Защитный кокон",
			ranks: 3,
			desc: "«Кровавая война» увеличивает шанс крит. удара на <span class='tooltip-value'>#%</span> крит. уклонения, даваемого навыком «Кровавая война». Время действия эффекта увеличивается на 300 сек.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 26,
			name: "Азарт крови",
			ranks: 2,
			desc: "Увеличивает время действия эффекта «Быстрая кровь» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает время действия эффекта «Быстрая кровь» на <span class="tooltip-value">45</span> сек.</div>'],
		},
		{
			index: 27,
			name: "Темный обман",
			ranks: 3,
			desc: "«Хватка ветра» снижает крит. уклонение цели на <span class='tooltip-value'>#%</span>, продолжительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [2, 3, 4],
		},
		{
			index: 30,
			name: "Взрыв крови",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 120 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nНа <span class='tooltip-value'>#</span> сек. увеличивает максимальное количество ОЗ персонажа на 100%. При атаке восстанавливается 2% ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [63, 115],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">165</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 120 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>На <span class="tooltip-value">25</span> сек. увеличивает максимальное количество ОЗ персонажа на 100%. При атаке восстанавливается 2% ОЗ.</div>'],
		},
		{
			index: 31,
			name: "Удар темной души",
			ranks: 3,
			desc: "Если во время действия навыка «Быстрая кровь», количество ОЗ персонажа больше 80%, увеличивает урон, наносимый атакующими навыками стихии Тьмы, на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 32,
			name: "Владения Тьмы",
			ranks: 4,
			desc: "Повышает показ атель мастерства Тьмы на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 33,
			name: "Кровь ненависти",
			ranks: 3,
			desc: "Навыки «Лютая ненависть» и «Искупление кровью» повышают меткость персонажа на <span class='tooltip-value'>#</span>; продолжительность - 15 сек.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 34,
			name: "Рев крови",
			ranks: 3,
			desc: "Навык «Взрыв крови» повышает скорость чтения заклинаний персонажа на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			parent: 18,
		},
		{
			index: 38,
			name: "Плач теней",
			ranks: 2,
			desc: "Увеличивает базовую атаку навыка «Верткая тень» на <span class='tooltip-value'>#%</span>, если ОЗ персонажа выше 80%; базовая атака дополнительно увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает базовую атаку навыка «Верткая тень» на <span class="tooltip-value">30%</span>, если ОЗ персонажа выше 80%; базовая атака дополнительно увеличивается на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 39,
			name: "Гордость Тьмы",
			ranks: 3,
			desc: "Увеличивает урон, наносимый навыками стихии Тьмы, на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 41,
			name: "Кровь ночи",
			ranks: 3,
			desc: "Во время действия эффекта «Быстрая кровь» в случае нанесения крит. удара навыком стихии Тьмы у цели начинается кровотечение. В секунду наносит урон, равный <span class='tooltip-value'>#%</span> от з начения мастерства Тьмы; продолжительность - 5 сек.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 42,
			name: "Побежденный холод",
			ranks: 2,
			desc: "Уменьшает время восстановления навыка «Неистовое сердце» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшает время восстановления навыка «Неистовое сердце» на <span class="tooltip-value">45</span> сек.</div>'],
		},
		{
			index: 46,
			name: "Безумие смерти",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>395 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Тьмы</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nАтака, состоящая из нескольких этапов. Наносит 100% базового урона и дополнительно 4046. На каждом этапе расходуется 5% от маскимального количества ОЗ, при этом критический урон увеличивается на 30%. Если у персонажа больше 80% ОЗ, оглушает цель на 3 сек. Если у персонажа больше 40% ОЗ, парализует цель на 2 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Кровь берсерка",
			ranks: 4,
			desc: "Уменьшает время восстановления навыка «Безумие смерти» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Уменьшает время восстановления навыка «Безумие смерти» на <span class="tooltip-value">10</span> сек.</div>'],
			parent: 27,
		},
		{
			index: 49,
			name: "Кровавый призрак",
			ranks: 3,
			desc: "Если запас ОЗ персонажа выше 80%, удар навыка «Пляска теней» по цели выз овет у нее головокружение на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 51,
			name: "Бурая кровь",
			ranks: 2,
			desc: "Применимо к навыкам, требующим, чтобы запас ОЗ был больше 80% или 40%; снижает нужное количество ОЗ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 54,
			name: "Кровавое безумие",
			ranks: 1,
			desc: "Увеличивает шанс крит. удара навыком «Безумие смерти» на 5%. Если запас ОЗ персонажа выше 40%, базовая атака навыка увеличивается на 50%. Если запас ОЗ персонажа выше 80%, базовая атака навыка увеличивается на 100%.",
			rankInfo: [],
			parent: 27,
		},
	]
];