var data = [
	// one
	[
		{
			index: 1,
			name: "Burn",
			ranks: 5,
			ranksnw: 2,
			desc: "Infernal Pyre deals additional Burning damage based on the number of Ignite stacks on the target. Each stack of Ignite deals extra damage equal <span class='tooltip-value'>#%</span> of your Attack. Burning damage is influenced by Fire Mastery and Resistance.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Infernal Pyre deals additional Burning damage based on the number of Ignite stacks on the target. Each stack of Ignite deals extra damage equal <span class="tooltip-value">6%</span> of your Attack. Burning damage is influenced by Fire Mastery and Resistance.</div>'],
		},
		{
			index: 3,
			name: "Heart Burning",
			ranks: 5,
			desc: "Wound Splitter reduces the target's Fire Resistance by <span class='tooltip-value'>#</span> for 30 seconds.",
			rankInfo: [15, 30, 45, 60, 75],
		},
		{
			index: 6,
			name: "Searing-Iron Sting",
			ranks: 3,
			desc: "Mana Sting's range is increased by <span class='tooltip-value'>#</span> meters, and its Base Attack and Bonus Damage are reduced by <span class='tooltip-value'>#%</span>. The reduced Base Attack and Bonus Damage are converted into Burning Damage Mana Sting critstrikes will trigger Burning damage twice.",
			rankInfo: [4, 8, 12],
			rankInfo2: [40, 70, 100],
		},
		{
			index: 7,
			name: "Incinerate",
			ranks: 3,
			desc: "Each stack of Ignite reduces the target's Fire Resistance by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Each stack of Ignite reduces the target\'s Fire Resistance by <span class="tooltip-value">12</span>.</div>'],
		},
		{
			index: 8,
			name: "Burning Ire",
			ranks: 4,
			desc: "Crit Chance is increased by <span class='tooltip-value'>#%</span> and Crit Dodge is reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 9,
			name: "Enraged Pyre",
			ranks: 4,
			desc: "Infernal Pyre's Crit Chance is increased by <span class='tooltip-value'>#%</span>. Infernal Pyre critstrikes will trigger Burning damage twice.",
			rankInfo: [3, 6, 9, 12],
			parent: [0],
		},
		{
			index: 10,
			name: "Inferno Rain",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 12 seconds</span>\n<span class='left'>AoE Attack</span><span class='right'>Range: 18 meters</span>\n\nAttacks multiple targets within a radius of 10 meters around the target Strikes twice; each strike deals 100% Base Attack plus <span class='tooltip-value'>#</span> bonus damage Each strike applies a stack of Ignite and stuns the target for 1 second.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [134, 205, 281, 362],
			rankInfo3: [964, 1964, 2980, 4013],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">448</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Fire damage</span><span class="right">Cooldown: 12 seconds</span>\n<br><span class="left">AoE Attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Attacks multiple targets within a radius of 10 meters around the target Strikes twice; each strike deals 100% Base Attack plus <span class="tooltip-value">5062</span> bonus damage Each strike applies a stack of Ignite and stuns the target for 1 second.</div>'],
		},
		{
			index: 12,
			name: "Disordered Mana",
			ranks: 3,
			desc: "The Mana cost of active Fire-damage skills is reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 14,
			name: "Inflame",
			ranks: 3,
			ranksnw: 2,
			desc: "The Base Attack of Inferno Rain is increased by <span class='tooltip-value'>#%</span> and its Cooldown is reduced by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>The Base Attack of Inferno Rain is increased by <span class="tooltip-value">40%</span> and its Cooldown is reduced by <span class="tooltip-value">4</span> second(s).</div>'],
			parent: 6,
		},
		{
			index: 16,
			name: "Flame of Abyss",
			ranks: 4,
			desc: "Fire Mastery is increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 17,
			name: "Burning Down",
			ranks: 4,
			ranksnw: 2,
			desc: "The Crit Chance of Burnout is increased by <span class='tooltip-value'>#%</span>. Burnout critstrikes have a <span class='tooltip-value'>#%</span> chance to deal extra Burning damage.",
			rankInfo: [3, 6, 9, 12],
			rankInfo2: [25, 50, 75, 100],
		},
		{
			index: 20,
			name: "Hellfire",
			ranks: 3,
			desc: "The acceleration effect of Flashing Shift is increased by <span class='tooltip-value'>#%</span> and its duration is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>The acceleration effect of Flashing Shift is increased by <span class="tooltip-value">40%</span> and its duration is increased by <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 22,
			name: "Pyrokinesis",
			ranks: 4,
			desc: "For each stack of Ignite on the target, Inferno Rain deals Burning Damage equal to <span class='tooltip-value'>#%</span> of your Attack. The skill's critstrike will trigger Burning damage twice.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>For each stack of Ignite on the target, Inferno Rain deals Burning Damage equal to <span class="tooltip-value">7.5%</span> of your Attack. The skill\'s critstrike will trigger Burning damage twice.</div>'],
			parent: 8,
		},
		{
			index: 24,
			name: "Lava Heat",
			ranks: 4,
			desc: "Crit damage is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12],
		},
		{
			index: 25,
			name: "Fire Step",
			ranks: 3,
			ranksnw: 1,
			desc: "Movement Speed after using Burnout is increased by 60% for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Movement Speed after using Burnout is increased by 60% for <span class="tooltip-value">5</span> second(s).</div>'],
			parent: 10,
		},
		{
			index: 27,
			name: "Scorching Pain",
			ranks: 4,
			desc: "The cooldowns of Inferno Rain and Infernal Pyre are reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [0.5, 1, 1.5, 2],
		},
		{
			index: 30,
			name: "Ignition",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Fire Curse</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>AoE Curse</span><span class='right'>Range: 18 meters</span>\n\nIgnite multiple targets within a radius of 8 meters around the target Applies a stack of Ignite on the target every second for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [194, 342],
			rankInfo3: [15, 18],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">483</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Fire Curse</span><span class="right">Cooldown: 60 seconds</span>\n<br><span class="left">AoE Curse</span><span class="right">Range: 18 meters</span>\n\n<br><br>Ignite multiple targets within a radius of 8 meters around the target Applies a stack of Ignite on the target every second for <span class="tooltip-value">21</span> second(s).</div>'],
		},
		{
			index: 32,
			name: "Ember",
			ranks: 5,
			desc: "The second Burning Damage created by critstrikes is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>The second Burning Damage created by critstrikes is increased by <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 33,
			name: "Undying Heartfire",
			ranks: 2,
			desc: "Every second for 10 seconds. Burnout deals damage equal to <span class='tooltip-value'>#%</span> of your Attack to targets who have 5 or more stacks of Ignite. This damage is only influenced by your Fire Mastery and ignores the target's Fire Resistance.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Every second for 10 seconds. Burnout deals damage equal to <span class="tooltip-value">15%</span> of your Attack to targets who have 5 or more stacks of Ignite. This damage is only influenced by your Fire Mastery and ignores the target\'s Fire Resistance.</div>'],
			parent: 14,
		},
		{
			index: 34,
			name: "Flesh Burn",
			ranks: 3,
			ranksnw: 1,
			desc: "Ignition reduces the target's Movement Speed by <span class='tooltip-value'>#%</span>.",
			rankInfo: [30, 40, 50],
			parent: 16,
		},
		{
			index: 36,
			name: "Akdaka Follower",
			ranks: 3,
			desc: "Magma Touch's Base Attack is increased by <span class='tooltip-value'>#%</span> and its Crit Chance is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Hyperheat",
			ranks: 3,
			desc: "Ignition's duration is increased by <span class='tooltip-value'>#%</span> and each stack of Ignite has a <span class='tooltip-value'>#%</span> chance to create an extra stack.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Ignition\'s duration is increased by <span class="tooltip-value">40%</span> and each stack of Ignite has a <span class="tooltip-value">40%</span> chance to create an extra stack.</div>'],
			parent: 19,
		},
		{
			index: 40,
			name: "Confusion",
			ranks: 2,
			desc: "Magma Touch's Crit Chance is increased by <span class='tooltip-value'>#%</span> and its critstrike stuns targets for <span class='tooltip-value'>#</span> second(s) For 6 seconds, the Casting Speed of the target of the critstrike is reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
			rankInfo2: [2, 3],
			rankInfo3: [15, 30],
		},
		{
			index: 41,
			name: "Firebath",
			ranks: 3,
			desc: "Targets affected by Blazing Revenge recover <span class='tooltip-value'>#%</span> Health and Mana per second.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Targets affected by Blazing Revenge recover <span class="tooltip-value">4%</span> Health and Mana per second.</div>'],
		},
		{
			index: 42,
			name: "Radiation",
			ranks: 2,
			desc: "Infernal Pyre has a <span class='tooltip-value'>#%</span> chance to reset the cooldown of Magma Touch For 10 seconds, the next Magma Touch hits an extra target within 6 meters.",
			rankInfo: [8, 16],
		},
		{
			index: 46,
			name: "Doomsday",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>411 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Blessing</span><span class='right'>Cooldown: 300 seconds</span>\n<span class='left'>Self Blessing</span><span class='right'>Range: None</span>\n\nCalls flames from hell to flow into your body, increasing your Fire Mastery by 200 and Crit Dodge by 50%.  Every second, you take damage equal to 3% of your Max Health, and a stack of Ignite is applied to enemies within a radius of 10 meters. This effect lasts a maximum of 20 second(s) and will end when your Health is lower than 20%.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Doomday's Stretch",
			ranks: 4,
			desc: "The range at which Doomsday can apply Ignite stacks is increased by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [2, 4, 6, 8],
			parent: 25,
		},
		{
			index: 49,
			name: "Scorched Land",
			ranks: 3,
			desc: "Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 51,
			name: "Flame Purify",
			ranks: 2,
			desc: "Infernal Pyre, Inferno Rain, Burnout, and Magma Touch have a <span class='tooltip-value'>#%</span> chance to dispel the last buff on the target.",
			rankInfo: [20, 40],
		},
		{
			index: 54,
			name: "World End",
			ranks: 1,
			desc: "The duration of Doomsday is increased by 10 seconds and its Base Attack is increased by 30%.",
			rankInfo: [],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Deepened Pain",
			ranks: 5,
			ranksnw: 3,
			desc: "The damage over time effect of Painful Torture is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20, 25],
		},
		{
			index: 4,
			name: "Torture Mastery",
			ranks: 5,
			desc: "The duration of Torture stacks is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>The duration of Torture stacks is increased by <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 6,
			name: "Mental Abuse",
			ranks: 5,
			desc: "Spiritual Reckoning deals Earth Damage equal to <span class='tooltip-value'>#%</span> of your Attack to stunned targets.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Spiritual Reckoning deals Earth Damage equal to <span class="tooltip-value">120%</span> of your Attack to stunned targets.</div>'],
		},
		{
			index: 7,
			name: "Demonic Torture",
			ranks: 5,
			desc: "When Abyss Fiend reflects damage, it also reflects a Demonic Torture debuff that deals Earth Damage to the target equal to <span class='tooltip-value'>#%</span> of your max Attack every 2 seconds for 6 seconds.",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 9,
			name: "Pricking",
			ranks: 4,
			ranksnw: 2,
			desc: "Painful Torture instantly deals Earth Damage equal to <span class='tooltip-value'>#%</span> of your Attack.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 50, 60, 70],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Painful Torture instantly deals Earth Damage equal to <span class="tooltip-value">80%</span> of your Attack.</div>'],
			parent: [0],
		},
		{
			index: 10,
			name: "Styx Ferry",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1.5 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single Attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% Base Attack plus <span class='tooltip-value'>#</span> bonus damage. For every stack of Torture on the target, Styx Ferry reduces the target\'s Earth Resistance by 20 for 15 second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [137, 263, 382, 493],
			rankInfo3: [1035, 1874, 2735, 3618],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">597</span> Mana</span><span class="right">Cast time: 1.5 seconds</span>\n<br><span class="left">Earth damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single Attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% Base Attack plus <span class="tooltip-value">4523</span> bonus damage. For every stack of Torture on the target, Styx Ferry reduces the target\'s Earth Resistance by 20 for 15 second(s).</div>'],
		},
		{
			index: 11,
			name: "Origin of Sin",
			ranks: 3,
			desc: "The healing effect of Greedy Torment is increased by <span class='tooltip-value'>#%</span>, and healing effects on the target are reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [40, 80, 120],
			rankInfo2: [15, 20, 25],
		},
		{
			index: 15,
			name: "Evil Breath",
			ranks: 4,
			desc: "Whenever you cast Painful Torture, Greedy Torment, Fading Suffering, or Styx Ferry, you can apply a stack of Evil Breath on yourself. Each stack increases your Base Attack by <span class='tooltip-value'>#%</span>. Lasts 10 seconds and can stack up to 5 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Whenever you cast Painful Torture, Greedy Torment, Fading Suffering, or Styx Ferry, you can apply a stack of Evil Breath on yourself. Each stack increases your Base Attack by <span class="tooltip-value">5%</span>. Lasts 10 seconds and can stack up to 5 times.</div>'],
		},
		{
			index: 16,
			name: "Infernal Sorrow",
			ranks: 3,
			desc: "The damage over time and Base Attack of Torture skills are increased by <span class='tooltip-value'>#%</span>. Demonic Torture's damage is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 17,
			name: "Cursed Seed",
			ranks: 4,
			desc: "Painful Torture reduces the target's Movement Speed by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Painful Torture reduces the target\'s Movement Speed by <span class="tooltip-value">50%</span>.</div>'],
			parent: 4,
		},
		{
			index: 18,
			name: "Netherworld Shock",
			ranks: 4,
			ranksnw: 2,
			desc: "Styx Ferry's Base Attack is increased by <span class='tooltip-value'>#%</span> and its cooldown is reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [1, 2, 3, 4],
			parent: 5,
		},
		{
			index: 21,
			name: "Cease Heart",
			ranks: 4,
			desc: "Fading Suffering's cooldown is reduced by <span class='tooltip-value'>#</span> second(s) and its damage over time is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [10, 20, 30, 40],
		},
		{
			index: 24,
			name: "Annihilation",
			ranks: 4,
			ranksnw: 2,
			desc: "Burnout can explode Torture debuffs on the target. Each Torture debuff (except Fading Suffering) deals Earth Damage equal to <span class='tooltip-value'>#%</span> of your Attack. Each stack of Fading Suffering deals Earth Damage equal to <span class='tooltip-value'>#%</span> of your Attack.",
			rankInfo: [20, 40, 60, 80],
			rankInfo2: [3, 6, 9, 12],
		},
		{
			index: 26,
			name: "Styx Ghost",
			ranks: 3,
			desc: "Styx Ferry reduces the target's Casting Time by <span class='tooltip-value'>#%</span> for 10 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Styx Ferry reduces the target\'s Casting Time by <span class="tooltip-value">20%</span> for 10 seconds.</div>'],
			parent: 10,
		},
		{
			index: 28,
			name: "Doomday Dusk",
			ranks: 4,
			desc: "Annihilation has a <span class='tooltip-value'>#%</span> chance not to remove the Torture debuffs on a target.",
			rankInfo: [25, 50, 75, 100],
			parent: 12,
		},
		{
			index: 29,
			name: "Hopeless",
			ranks: 3,
			desc: "When Gut Drain ends, it stuns the target for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>When Gut Drain ends, it stuns the target for <span class="tooltip-value">4</span> second(s).</div>'],
		},
		{
			index: 30,
			name: "Abusive Intention",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Blessing</span><span class='right'>Cooldown: 300 seconds</span>\n<span class='left'>Self Blessing</span><span class='right'>Range: None</span>\n\nThe cooldown of Greedy Torment is halved and Fading Suffering applies one extra stack. Painful Torture is able to hit multiple targets within a radius of 5 meters and Demonic Torture ensnares the target for 2 seconds. This skill lasts <span class='tooltip-value'>#</span> second(s), during which you are immune to Silence, Stun, and Disarm.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [268, 476],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">672</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Blessing</span><span class="right">Cooldown: 300 seconds</span>\n<br><span class="left">Self Blessing</span><span class="right">Range: None</span>\n\n<br><br>The cooldown of Greedy Torment is halved and Fading Suffering applies one extra stack. Painful Torture is able to hit multiple targets within a radius of 5 meters and Demonic Torture ensnares the target for 2 seconds. This skill lasts <span class="tooltip-value">25</span> second(s), during which you are immune to Silence, Stun, and Disarm.</div>'],
		},
		{
			index: 32,
			name: "Brutality",
			ranks: 2,
			desc: "Whenever you kill a target, you ignore damage for <span class='tooltip-value'>#</span> second(s). Every 2 seconds, you recover 10% of your Health. The cooldown of this effect is 60 seconds.",
			rankInfo: [4, 8],
		},
		{
			index: 33,
			name: "God-Sealing Curse",
			ranks: 2,
			desc: "Fading Suffering's Crit Chance is increased by <span class='tooltip-value'>#%</span>, and its critstrike silences the target for 2 second(s).",
			rankInfo: [4, 8],
		},
		{
			index: 34,
			name: "Heartless",
			ranks: 3,
			ranksnw: 2,
			desc: "The duration of Abusive Intention is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			parent: 16,
		},
		{
			index: 36,
			name: "Wither",
			ranks: 3,
			desc: "When it hits a target, Styx Ferry reduces all of the target's Resistances by 4. Lasts <span class='tooltip-value'>#</span> second(s) and can stack up to 50 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 8, 11],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>When it hits a target, Styx Ferry reduces all of the target\'s Resistances by 4. Lasts <span class="tooltip-value">14</span> second(s) and can stack up to 50 times.</div>'],
		},
		{
			index: 38,
			name: "Cruelty",
			ranks: 3,
			desc: "Abusive Intention additionally increases your Earth Mastery by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [60, 120, 180],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Abusive Intention additionally increases your Earth Mastery by <span class="tooltip-value">240</span>.</div>'],
			parent: 19,
		},
		{
			index: 39,
			name: "Gift of the Styx",
			ranks: 2,
			desc: "The Health cost of Nether Lament is reduced by <span class='tooltip-value'>#%</span> and its duration is increased by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [50, 100],
			rankInfo2: [2, 4],
		},
		{
			index: 41,
			name: "Undead Herald",
			ranks: 2,
			desc: "Healing effects are increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [8, 15],
		},
		{
			index: 44,
			name: "Blood melt",
			ranks: 3,
			desc: "Each time you use Blessing of the Demon, you convert 5% of your Max Health into an amount of Mana equal to <span class='tooltip-value'>#%</span> of your lost Health.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 150, 200],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Each time you use Blessing of the Demon, you convert 5% of your Max Health into an amount of Mana equal to <span class="tooltip-value">250%</span> of your lost Health.</div>'],
		},
		{
			index: 46,
			name: "Soul Harvest",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>509 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Single Curse</span><span class='right'>Range: 18 meters</span>\n\nInstantly deals 100% Base Attack plus 6760 bonus damage. For every stack of Torture on the target, this skill's damage increases by 20%. Deals additional damage to the target equal to 20% of the instant damage every 2 seconds for 10 seconds. The Bleeding damage of this skill ignores Bleeding Immunity and Dispel, influenced by Earth Mastery and Resistance.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Soulless Body",
			ranks: 4,
			desc: "Soul Harvest has a <span class='tooltip-value'>#%</span> chance to stun the target for 3 seconds.",
			rankInfo: [20, 40, 60, 80],
			parent: 25,
		},
		{
			index: 51,
			name: "Wraith Explosion",
			ranks: 3,
			desc: "The Casting Speed of Grudge Gathering is increased by <span class='tooltip-value'>#%</span> and its Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 52,
			name: "Hatred",
			ranks: 2,
			desc: "Earth Mastery is increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [30, 60],
		},
		{
			index: 54,
			name: "Embrace of Death",
			ranks: 1,
			desc: "Soul Harvest deals double damage to targets whose Health is lower than 50%. Instead of dealing constant bleeding damage, Soul Harvest deals 40% of the instant bleeding damage every 2 seconds for 6 seconds.",
			rankInfo: [],
			parent: 25,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Alien Force",
			ranks: 5,
			desc: "Ethereal Lunge's Base Attack is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Ethereal Lunge\'s Base Attack is increased by <span class="tooltip-value">36%</span>.</div>'],
		},
		{
			index: 4,
			name: "Penetration Mastery",
			ranks: 5,
			ranksnw: 2,
			desc: "The Base Attack of Mana Sting is increased by <span class='tooltip-value'>#%</span>. Mana Sting increases your Earth Mastery by <span class='tooltip-value'>#</span>. Lasts 15 seconds and can stack up to 5 times.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [3, 6, 9, 12, 15],
		},
		{
			index: 5,
			name: "Constant Dance",
			ranks: 3,
			desc: "The cooldowns of Mana Sting and Ethereal Lunge are reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3],
		},
		{
			index: 6,
			name: "Demonic Pact",
			ranks: 4,
			desc: "Each time Abyss Fiend reflects damage, it increases your Earth Mastery by <span class='tooltip-value'>#</span>. Lasts 15 seconds and can stack up to 5 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Each time Abyss Fiend reflects damage, it increases your Earth Mastery by <span class="tooltip-value">10</span>. Lasts 15 seconds and can stack up to 5 times.</div>'],
		},
		{
			index: 7,
			name: "Deepened Wound",
			ranks: 3,
			desc: "While Wound Splitter is active, it increases the direct Earth Damage dealt to the target by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 9,
			name: "Enhanced Thrust",
			ranks: 4,
			desc: "Cascaded Thrust's Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 10,
			name: "Inferno Rain",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Blessing</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>Self Blessing</span><span class='right'>Range: None</span>\n\nAll melee skills ignore range. Their ranges are increased by 50 meters for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [104, 227, 349, 470],
			rankInfo3: [20, 23, 26, 29],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">589</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Blessing</span><span class="right">Cooldown: 60 seconds</span>\n<br><span class="left">Self Blessing</span><span class="right">Range: None</span>\n\n<br><br>All melee skills ignore range. Their ranges are increased by 50 meters for <span class="tooltip-value">32</span> second(s).</div>'],
		},
		{
			index: 11,
			name: "Darklord Descending",
			ranks: 3,
			desc: "Flashing Shift reduces the Base Attack of targets within a radius of 10 meters by <span class='tooltip-value'>#%</span> for 15 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Flashing Shift reduces the Base Attack of targets within a radius of 10 meters by <span class="tooltip-value">20%</span> for 15 seconds.</div>'],
		},
		{
			index: 13,
			name: "Abyss Source",
			ranks: 3,
			desc: "Targets affected by Stare from the Depths ignore damage for an additional <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Targets affected by Stare from the Depths ignore damage for an additional <span class="tooltip-value">4</span> second(s).</div>'],
		},
		{
			index: 15,
			name: "Call from the Netherworld",
			ranks: 3,
			desc: "Earth Mastery is increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Demonic Physique",
			ranks: 4,
			desc: "Crit Dodge is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [],
		},
		{
			index: 18,
			name: "Distorted Space",
			ranks: 3,
			desc: "If targets hit by melee skills while Living Hunt is active remain within <span class='tooltip-value'>#</span> meters of you when Living Hunt ends, they will be pulled to your side and stunned for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [15, 20, 25],
			rankInfo2: [1, 2, 3],
			parent: 6,
		},
		{
			index: 20,
			name: "Penetration",
			ranks: 3,
			desc: "Mana Sting can hit 3 extra targets within a radius of <span class='tooltip-value'>#</span> meters around the target.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 4, 5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Mana Sting can hit 3 extra targets within a radius of <span class="tooltip-value">6</span> meters around the target.</div>'],
			parent: 1,
		},
		{
			index: 22,
			name: "Crime Buster",
			ranks: 3,
			ranksnw: 1,
			desc: "Targets hit by melee skills will have all their Masteries reduced by <span class='tooltip-value'>#</span> Lasts 10 seconds and can stack up to 5 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Targets hit by melee skills will have all their Masteries reduced by <span class="tooltip-value">20</span> Lasts 10 seconds and can stack up to 5 times.</div>'],
		},
		{
			index: 24,
			name: "Crushed",
			ranks: 3,
			desc: "Each stack of Crime Buster reduces all Resistances by an additional <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15],
			parent: 13,
		},
		{
			index: 26,
			name: "Demon's Disciple",
			ranks: 3,
			desc: "When you are hit, if your Health is lower than <span class='tooltip-value'>#%</span>, you will gain the Demon's Disciple buff. Skills do not consume Mana and their Base Attack is increased by <span class='tooltip-value'>#%</span> for 15 seconds. The cooldown of this effect is 120 seconds.",
			rankInfo: [30, 40, 50],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 28,
			name: "Abyss Bog",
			ranks: 4,
			desc: "Gut Drain's Casting Speed penalty is increased by <span class='tooltip-value'>#%</span> and its Movement Speed penalty is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [5, 10, 15, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Gut Drain\'s Casting Speed penalty is increased by <span class="tooltip-value">50%</span> and its Movement Speed penalty is increased by <span class="tooltip-value">25%</span>.</div>'],
		},
		{
			index: 30,
			name: "Primal Power",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Blessing</span><span class='right'>Cooldown: 180 seconds</span>\n<span class='left'>Self Blessing</span><span class='right'>Range: None</span>\n\nEarth Mastery is increased by <span class='tooltip-value'>#</span> and your melee skills are significantly enhanced for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [163, 290],
			rankInfo3: [100, 120],
			rankInfo4: [15, 20],
			rankInfo5: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">410</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Blessing</span><span class="right">Cooldown: 180 seconds</span>\n<br><span class="left">Self Blessing</span><span class="right">Range: None</span>\n\n<br><br>Earth Mastery is increased by <span class="tooltip-value">140</span> and your melee skills are significantly enhanced for <span class="tooltip-value">25</span> second(s).</div>'],
		},
		{
			index: 31,
			name: "Dimensional Shift",
			ranks: 5,
			ranksnw: 1,
			desc: "Movement Speed and Mount Speed is increased by <span class='tooltip-value'>#%</span>. Lasts 15 seconds, or until you are hit or make an attack.",
			rankInfo: [20, 30, 40, 50, 60],
		},
		{
			index: 33,
			name: "Enchanted Skin",
			ranks: 3,
			desc: "All Resistances are increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 34,
			name: "Amplify Strength",
			ranks: 3,
			ranksnw: 1,
			desc: "The cooldown of Primal Power is reduced by <span class='tooltip-value'>#</span> second(s). While Primal Power is active, your Base Attack is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>The cooldown of Primal Power is reduced by <span class="tooltip-value">80</span> second(s). While Primal Power is active, your Base Attack is increased by <span class="tooltip-value">20%</span>.</div>'],
			parent: 17,
		},
		{
			index: 38,
			name: "Suppression",
			ranks: 2,
			ranksnw: 1,
			desc: "Primal Power inflicts the Suppression effect on targets within a radius of <span class='tooltip-value'>#</span> meters. For 5 seconds, targets who attack you are stunned for <span class='tooltip-value'>#</span> second(s). Only takes effect once per target. Targets less than <span class='tooltip-value'>#</span> meters from you are directly stunned for <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 17],
			rankInfo2: [2, 3],
			rankInfo3: [7, 8],
			rankInfo4: [2, 3],
			rankInfo5: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Primal Power inflicts the Suppression effect on targets within a radius of <span class="tooltip-value">19</span> meters. For 5 seconds, targets who attack you are stunned for <span class="tooltip-value">4</span> second(s). Only takes effect once per target. Targets less than <span class="tooltip-value">9</span> meters from you are directly stunned for <span class="tooltip-value">4</span> second(s).</div>'],
			parent: 20,
		},
		{
			index: 39,
			name: "Broken Walker",
			ranks: 3,
			desc: "Mana Sting, Cascaded Thrust, and Thrust of Slaughter have a <span class='tooltip-value'>#%</span> chance to remove Ensnare and Deceleration debuffs and render you immune to those effects for 4 seconds.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 42,
			name: "Furious Taunt",
			ranks: 2,
			desc: "Base Attack is increased by <span class='tooltip-value'>#%</span> and Base Defense is reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
			rankInfo2: [5, 10],
		},
		{
			index: 44,
			name: "Origin of Sin",
			ranks: 3,
			desc: "Crit Defense is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Crit Defense is increased by <span class="tooltip-value">16%</span>.</div>'],
		},
		{
			index: 46,
			name: "Thrust of Slaughter",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>480 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Single Attack</span><span class='right'>Short Range</span>\n\nDeals 100% Base Attack plus 8010 bonus damage. Dispels all dispellable buffs on both you and your target, and renders those buffs ineffective for 5 second(s). While Primal Power is active, Base Attack is increased by 70% and healing effects are reduced by 80%.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Slaughter's Mission",
			ranks: 4,
			desc: "Thrust of Slaughter's Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60, 80],
			parent: 25,
		},
		{
			index: 49,
			name: "Heritage of Demon",
			ranks: 3,
			desc: "Diabolic Stature additionally increases Base Health by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [],
		},
		{
			index: 51,
			name: "Ominous Soul",
			ranks: 2,
			desc: "The percentage of reflected damage of Abyss Fiend is increased by <span class='tooltip-value'>#%</span>. Grudge Gathering wont kill you, but will instead leave you with <span class='tooltip-value'>#%</span> of your max Health.",
			rankInfo: [2, 4],
			rankInfo2: [4, 8],
		},
		{
			index: 54,
			name: "Fall of Gods",
			ranks: 1,
			desc: "Thrust of Slaughter's Casting Speed is increased by 100%, its Base Attack is increased by 50%, and its Accuracy is significantly increased. The duration of God of Slaughter is increased by 3 seconds.",
			rankInfo: [],
			parent: 25,
		}
	]
];