var data = [
	// one
	[
		{
			index: 1,
			name: "Weakpoint Tag",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the duration of Hunter Mark by <span class='tooltip-value'>#</span> seconds, and reduces its target's basic Defense by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: [60, 75, 90, 105, 120],
			rankInfo4: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the duration of Hunter Mark by <span class="tooltip-value">12</span> seconds, and reduces its target\'s basic Defense by <span class="tooltip-value">6%</span> plus <span class="tooltip-value">135</span>.</div>'],
		},
		{
			index: 3,
			name: "Solid Shot",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the bonus damage of Fire At Will by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#%</span> of your Earth Mastery.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the bonus damage of Fire At Will by <span class="tooltip-value">12%</span> plus <span class="tooltip-value">60%</span> of your Earth Mastery.</div>'],
		},
		{
			index: 6,
			name: "Swift Soul Trap",
			ranks: 5,
			desc: "Reduces the cooldown of Mind Flaying Bullet by <span class='tooltip-value'>#</span> second(s) and increases its bonus damage by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [2, 4, 6, 8, 10],
			rankInfo4: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Reduces the cooldown of Mind Flaying Bullet by <span class="tooltip-value">6</span> second(s) and increases its bonus damage by <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 8,
			name: "Earth Infusion",
			ranks: 5,
			desc: "Increases your Earth Mastery by <span class='tooltip-value'>#</span> and the bonus damage of your Earth skills by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 9,
			name: "Full Analysis",
			ranks: 3,
			desc: "Hunter Mark reduces the target's Resistances by an additional <span class='tooltip-value'>#</span> and Evasion by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
			rankInfo2: [15, 30, 45],
			parent: [0],
		},
		{
			index: 10,
			name: "Aimed Shot",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Earth damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% of your Attack, plus <span class='tooltip-value'>#</span> bonus damage. It will generate a Soul Bullet if Crack Shot Time is not activated. Inflicts a bleed effect on the target, which causes it to lose <span class='tooltip-value'>#</span> Health each second for 10 seconds. Stacks 3 times. Has a 25% chance to knock the target back 4 meters. Aimed Shot consumes 1 Soul Bullet, its base Attack and bonus damage are increased by 20%, the damage of the bleed effect is doubled, Does 120% damage and has a 100% chance to knock a target affected by Hunter Mark back 4 meters while Crack Shot Time is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [124, 185, 246, 309],
			rankInfo3: [1313, 2312, 3293, 4256],
			rankInfo4: [29, 46, 64, 81],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">373</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Earth damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% of your Attack, plus <span class="tooltip-value">5200</span> bonus damage. It will generate a Soul Bullet if Crack Shot Time is not activated. Inflicts a bleed effect on the target, which causes it to lose <span class="tooltip-value">98</span> Health each second for 10 seconds. Stacks 3 times. Has a 25% chance to knock the target back 4 meters. Aimed Shot consumes 1 Soul Bullet, its base Attack and bonus damage are increased by 20%, the damage of the bleed effect is doubled, Does 120% damage and has a 100% chance to knock a target affected by Hunter Mark back 4 meters while Crack Shot Time is active.</div>'],
		},
		{
			index: 11,
			name: "Soul Preservation",
			ranks: 4,
			ranksnw: 2,
			desc: "Reduces the Mana cost of Fire At Will by <span class='tooltip-value'>#%</span>, and increases its Crit Chance by <span class='tooltip-value'>#%</span> while Soul Catching is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [2, 4, 6, 8],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the Mana cost of Fire At Will by <span class="tooltip-value">75%</span>, and increases its Crit Chance by <span class="tooltip-value">10%</span> while Soul Catching is active.</div>'],
			parent: 1,
		},
		{
			index: 14,
			name: "Precise Aiming",
			ranks: 4,
			ranksnw: 2,
			desc: "Increases the Crit Chance of Aimed Shot by <span class='tooltip-value'>#%</span>, Accuracy by an additional <span class='tooltip-value'>#</span> and its chance to knock a target back by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [15, 30, 45, 60],
			rankInfo3: [15, 30, 45, 60],
			parent: 5,
		},
		{
			index: 16,
			name: "Iron Mind",
			ranks: 4,
			desc: "Increases your Defense and your Earth Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Choking Cloud",
			ranks: 2,
			desc: "Weakening Cloud reduces target's movement speed by an additional <span class='tooltip-value'>#%</span>. Reduces the cooldown of Weakening Cloud by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Weakening Cloud reduces target\'s movement speed by an additional <span class="tooltip-value">30%</span>. Reduces the cooldown of Weakening Cloud by <span class="tooltip-value">45</span> seconds.</div>'],
		},
		{
			index: 18,
			name: "Power Surge",
			ranks: 2,
			desc: "Increases the bonus damage of Aimed Shot by <span class='tooltip-value'>#%</span> and the damage of its bleed effect by <span class='tooltip-value'>#%</span>. In addition, there is a <span class='tooltip-value'>#%</span> chance to stun the target for 3 seconds.",
			rankInfo: [5, 10],
			rankInfo2: [50, 100],
			rankInfo3: [50, 100],
			parent: 7,
		},
		{
			index: 19,
			name: "Target Practice",
			ranks: 4,
			ranksnw: 2,
			desc: "Fire At Will reduces the target's Defense by <span class='tooltip-value'>#</span> for 10 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Fire At Will reduces the target\'s Defense by <span class="tooltip-value">125</span> for 10 seconds.</div>'],
			parent: 6,
		},
		{
			index: 21,
			name: "Soul Suspension",
			ranks: 2,
			desc: "Increases the maximum range of Pulse Shot by <span class='tooltip-value'>#</span> meters, and reduces its minimum range by <span class='tooltip-value'>#%</span> while Crack Shot Time is active.",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
		},
		{
			index: 24,
			name: "Soulforce Return",
			ranks: 3,
			ranksnw: 1,
			desc: "Restores <span class='tooltip-value'>#%</span> of your max Mana when you generate a Soul Bullet.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Restores <span class="tooltip-value">2.5%</span> of your max Mana when you generate a Soul Bullet.</div>'],
		},
		{
			index: 25,
			name: "Master Sniper",
			ranks: 2,
			ranksnw: 2,
			desc: "Soul Snipe knocks targets above <span class='tooltip-value'>#%</span> Health back. Increases the Accuracy of Extreme Sniping by <span class='tooltip-value'>#</span>. The casting speed of the next Extreme Sniping is increased by <span class='tooltip-value'>#%</span> within 10 seconds after casting Hunter Mark.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 20],
			rankInfo2: [20, 40],
			rankInfo3: [50, 100],
			rankInfo4: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Soul Snipe knocks targets above <span class="tooltip-value">10%</span> Health back. Increases the Accuracy of Extreme Sniping by <span class="tooltip-value">60</span>. The casting speed of the next Extreme Sniping is increased by <span class="tooltip-value">150%</span> within 10 seconds after casting Hunter Mark.</div>'],
		},
		{
			index: 26,
			name: "Contact",
			ranks: 3,
			desc: "Accuracy Guidance increases your Crit Chance by an additional <span class='tooltip-value'>#%</span>. Increases its duration by <span class='tooltip-value'>#</span> minutes.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Accuracy Guidance increases your Crit Chance by an additional <span class="tooltip-value">2.5%</span>. Increases its duration by <span class="tooltip-value">20</span> minutes.</div>'],
		},
		{
			index: 27,
			name: "Burst Fire",
			ranks: 3,
			desc: "Grants Fire At Will a <span class='tooltip-value'>#%</span> chance to reset the cooldowns of Extreme Sniping. Pulse Shot. Penetrating Shot, and Aimed Shot.",
			rankInfo: [4, 8, 12],
			parent: 11,
		},
		{
			index: 29,
			name: "Fierce Impact",
			ranks: 1,
			desc: "Extreme Sniping will inflict Plant and Humanoid targets with over 75% Health with a sleep effect for 30 seconds. This effect ends when the target is attacked.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 30,
			name: "Encourage",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Aura blessing</span><span class='right'>Range: None</span>\n\nIncreases the Attack of all party members within 16 meters of you by <span class='tooltip-value'>#%</span> of their Accuracy. While this skill is active, it will consume 0.30% of your max Mana every 2 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [206, 254],
			rankInfo3: [50, 70],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">304</span> Mana</span><span class="right">Cast time: Instant</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Aura blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases the Attack of all party members within 16 meters of you by <span class="tooltip-value">90%</span> of their Accuracy. While this skill is active, it will consume 0.30% of your max Mana every 2 seconds.</div>'],
		},
		{
			index: 32,
			name: "Relaxation",
			ranks: 3,
			desc: "Restores <span class='tooltip-value'>#%</span> of your max Health when you generate a Soul Bullet.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Restores <span class="tooltip-value">2.5%</span> of your max Health when you generate a Soul Bullet.</div>'],
			parent: 13,
		},
		{
			index: 33,
			name: "Fissure",
			ranks: 3,
			desc: "When your single-target offensive Earth skills land a Crit, they will reduce the target's Crit Dodge by <span class='tooltip-value'>#%</span> for 10 seconds.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 35,
			name: "Pain Mark",
			ranks: 3,
			desc: "Increases the damage dealt to targets affected by Hunter Mark by <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 6, 8],
		},
		{
			index: 37,
			name: "Amplified Exorcising Bullet",
			ranks: 3,
			desc: "Increases the bonus damage of Exorcising Bullet by <span class='tooltip-value'>#%</span>, and the chance it has to dispel a buff from the target by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 30, 40],
		},
		{
			index: 38,
			name: "Conduct",
			ranks: 2,
			desc: "Increases the amount of Attack granted by Encourage by <span class='tooltip-value'>#%</span> of your Accuracy, and reduces its Mana cost by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
			rankInfo2: [20, 40],
			parent: 18,
		},
		{
			index: 42,
			name: "Lethal Control",
			ranks: 2,
			desc: "Double Shot increases your Earth Mastery and your Crit Chance by <span class='tooltip-value'>#</span> and <span class='tooltip-value'>#%</span> respectively. Each attack has a <span class='tooltip-value'>#%</span> chance to generate a Soul bullet instead of costing one.",
			rankInfo: [40, 80],
			rankInfo2: [4, 8],
			rankInfo3: [50, 100],
		},
		{
			index: 43,
			name: "Strengthen Up",
			ranks: 3,
			desc: "Increases your Attack by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [25, 50, 75],
		},
		{
			index: 46,
			name: "Dazing Shot",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>433 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Earth</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Single-target curse</span><span class='right'>Range: 18 meters</span>\n\nReduces the target's Masteries by 80 and movement speed by 75%, and its Crit damage by 35% for 15 seconds. Generates 1 Soul Bullet.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Disable",
			ranks: 4,
			desc: "Dazing Shot reduces target's Base Attack by <span class='tooltip-value'>#%</span>.",
			rankInfo: [6, 9, 12, 15],
			parent: 26,
		},
		{
			index: 49,
			name: "Hawkeye",
			ranks: 3,
			desc: "Increases accuracy by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 51,
			name: "Armor Penetration",
			ranks: 2,
			desc: "Fire At Will, Pulse Shot, Aimed Shot, and Salvo reduce target's Crit Dodge by <span class='tooltip-value'>#%</span> and Crit Defense by <span class='tooltip-value'>#%</span> for 5 seconds.",
			rankInfo: [1, 2],
			rankInfo2: [2, 4],
		},
		{
			index: 54,
			name: "Stun Gun",
			ranks: 1,
			desc: "Dazing Shot ensnares target for 4 seconds, and increases Earth damage on the target by 20% for 15 seconds.",
			rankInfo: [],
			parent: 26,
		},
	],
		// two
	[
		{
			index: 2,
			name: "Art of Reloading",
			ranks: 5,
			desc: "Reduces the cooldown of Quick Reloading by <span class='tooltip-value'>#</span> seconds. Increases the amount of Mana restored by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 3,
			name: "Absorption",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the base damage of Mind Flaying Bullet by <span class='tooltip-value'>#%</span> and the duration of Soul Catching by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [4, 8, 12, 16, 20],
			rankInfo2: [2, 4, 6, 8, 10],
		},
		{
			index: 5,
			name: "Professional Hunter",
			ranks: 3,
			desc: "Hunter Mark reduces the target's Evasion by an additional <span class='tooltip-value'>#</span>. Increases the range of Hunter Mark by <span class='tooltip-value'>#</span> meters.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [3, 6, 9],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Hunter Mark reduces the target\'s Evasion by an additional <span class="tooltip-value">20</span>. Increases the range of Hunter Mark by <span class="tooltip-value">12</span> meters.</div>'],
		},
		{
			index: 8,
			name: "Deadly Accuracy",
			ranks: 5,
			desc: "Increases the amount of Accuracy granted by Art of Targeting by <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12, 16, 20],
		},
		{
			index: 9,
			name: "Sixth Sense",
			ranks: 3,
			desc: "Increases the duration of Weakening Cloud by <span class='tooltip-value'>#</span> second(s) and the duration of Hunter Mark by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the duration of Weakening Cloud by <span class="tooltip-value">4</span> second(s) and the duration of Hunter Mark by <span class="tooltip-value">8</span> seconds.</div>'],
		},
		{
			index: 10,
			name: "Soul Discharge",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 10 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% of your Attack plus <span class='tooltip-value'>#</span> bonus damage. Generates a Soul Bullet. While Crack Shot Time is active Soul Discharge will not cost or generate any Soul Bullets, and its bonus damage is increased by 20%. A target affected by Hunter Mark will lose <span class='tooltip-value'>#%</span> of its current Mana plus <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [126, 181, 238, 295],
			rankInfo3: [663, 1112, 1552, 1984],
			rankInfo4: [6, 8, 10, 12],
			rankInfo5: [150, 300, 400, 600],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">354</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Fire damage</span><span class="right">Cooldown: 10 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% of your Attack plus <span class="tooltip-value">2407</span> bonus damage. Generates a Soul Bullet. While Crack Shot Time is active Soul Discharge will not cost or generate any Soul Bullets, and its bonus damage is increased by 20%. A target affected by Hunter Mark will lose <span class="tooltip-value">14%</span> of its current Mana plus <span class="tooltip-value">750</span>.</div>'],
		},
		{
			index: 11,
			name: "Soul Rift",
			ranks: 4,
			desc: "Increases Mind Flaying Bullet's chance to trigger Soul Catching by <span class='tooltip-value'>#%</span> and it deals <span class='tooltip-value'>#</span> extra damage to targets below 25% Health.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [60, 120, 180, 240],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases Mind Flaying Bullet\'s chance to trigger Soul Catching by <span class="tooltip-value">25%</span> and it deals <span class="tooltip-value">300</span> extra damage to targets below 25% Health.</div>'],
			parent: 1,
		},
		{
			index: 13,
			name: "Mist",
			ranks: 3,
			desc: "Weakening Cloud reduces the Accuracy of its targets by an additional <span class='tooltip-value'>#%</span>, increase Sealth time by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [20, 40, 60],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 15,
			name: "Durability",
			ranks: 4,
			ranksnw: 2,
			desc: "Increases the duration of Fast Action by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the duration of Fast Action by <span class="tooltip-value">7.5</span> seconds.</div>'],
		},
		{
			index: 18,
			name: "Soul Stripping",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the base damage of Soul Discharge by <span class='tooltip-value'>#%</span>. Increases the amount of Mana drained from targets affected by Hunter Mark by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [25, 50, 75],
			parent: 5,
		},
		{
			index: 19,
			name: "Cast Off",
			ranks: 1,
			desc: "Grants Fast Action a 100% chance to dispel any slow or ensnare effects on you.",
			rankInfo: [],
			parent: 8,
		},
		{
			index: 20,
			name: "Soul Guidance",
			ranks: 3,
			desc: "Increases the Crit Chance of your skills by <span class='tooltip-value'>#%</span> while Crack Shot Time is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the Crit Chance of your skills by <span class="tooltip-value">4%</span> while Crack Shot Time is active.</div>'],
		},
		{
			index: 21,
			name: "Soul Ash",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the damage dealt by Soul Snipe by <span class='tooltip-value'>#%</span> and increases its Crit Chance by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the damage dealt by Soul Snipe by <span class="tooltip-value">40%</span> and increases its Crit Chance by <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 22,
			name: "Soul Extraction",
			ranks: 2,
			desc: "Reduces the cooldown of Soul Discharge by <span class='tooltip-value'>#</span> seconds. It reduces the max Mana of a target affected by Hunter Mark by an amount equal to <span class='tooltip-value'>#%</span> of the total Mana lost for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4],
			rankInfo2: [50, 100],
			rankInfo3: [20, 30],
			parent: 9,
		},
		{
			index: 23,
			name: "Stray Bullet",
			ranks: 2,
			desc: "Grants Fire At Will a <span class='tooltip-value'>#%</span> chance to generate a Soul Bullet while Soul Catching is not active and reduces its cooldown by <span class='tooltip-value'>#</span> seconds per point in this talent.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: [0.5, 1],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Grants Fire At Will a <span class="tooltip-value">60%</span> chance to generate a Soul Bullet while Soul Catching is not active and reduces its cooldown by <span class="tooltip-value">1.5</span> seconds per point in this talent.</div>'],
		},
		{
			index: 26,
			name: "Pulse Precision",
			ranks: 2,
			desc: "Increases the duration of Pulse Shot's slow effect on targets affected by Hunter Mark by <span class='tooltip-value'>#</span> seconds. Increases the slowing effect by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Pulse Shot\'s slow effect on targets affected by Hunter Mark by <span class="tooltip-value">3</span> seconds. Increases the slowing effect by <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 27,
			name: "Soul Concentration",
			ranks: 4,
			desc: "Each time you generate a Soul Bullet while Quick Reloading is active, you have a <span class='tooltip-value'>#%</span> chance to generate an additional Soul Bullet. Reduces the chance of being interrupted while casting by <span class='tooltip-value'>#%</span>. Reduces the cooldown of Quick Reloading by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [25, 50, 75, 100],
			rankInfo3: [3, 7, 11, 15],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Each time you generate a Soul Bullet while Quick Reloading is active, you have a <span class="tooltip-value">75%</span> chance to generate an additional Soul Bullet. Reduces the chance of being interrupted while casting by <span class="tooltip-value">125%</span>. Reduces the cooldown of Quick Reloading by <span class="tooltip-value">19</span> seconds.</div>'],
		},
		{
			index: 29,
			name: "Soul Detonation",
			ranks: 3,
			desc: "Increases the bonus damage of Soul Snipe by <span class='tooltip-value'>#%</span>. When it lands a Crit, it has a <span class='tooltip-value'>#%</span> chance to stun the target for 2 seconds.",
			rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
			parent: 12,
		},
		{
			index: 30,
			name: "Burst of Rage",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 3 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 18 meters</span>\n\nStrikes the target 6 times. Each shot deals 75% of your Attack plus <span class='tooltip-value'>#</span> bonus damage. Requires at least 1 Soul Bullet to cast, and costs up to 3 Soul Bullets. If less than 3 Soul Bullets are available, you will not attack all 6 times, and your casting will be interrupted. While Crack Shot Time is active, each shot has a 30% chance to cost an extra Soul Bullet, but the cooldown will be cut in half.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [517, 639],
			rankInfo3: [643, 1027],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">769</span> Mana</span><span class="right">Cast time: 3 seconds</span>\n<br><span class="left">Fire damage</span><span class="right">Cooldown: 20 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Strikes the target 6 times. Each shot deals 75% of your Attack plus <span class="tooltip-value">1383</span> bonus damage. Requires at least 1 Soul Bullet to cast, and costs up to 3 Soul Bullets. If less than 3 Soul Bullets are available, you will not attack all 6 times, and your casting will be interrupted. While Crack Shot Time is active, each shot has a 30% chance to cost an extra Soul Bullet, but the cooldown will be cut in half.</div>'],
		},
		{
			index: 32,
			name: "Crack Shot Mastery",
			ranks: 3,
			desc: "Firepower Amplification increases your Crit damage by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 33,
			name: "Stunning Shot",
			ranks: 3,
			desc: "Increases the bonus damage of Extreme Sniping by <span class='tooltip-value'>#%</span>, and grants it a <span class='tooltip-value'>#%</span> chance to slow the target by 50% for 4 seconds while Crack Shot Time is active.",
			rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
		},
		{
			index: 35,
			name: "Remains of the Soul",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the amount of damage absorbed by Soul Resolution by <span class='tooltip-value'>#%</span>, and reduces its Mana cost by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the amount of damage absorbed by Soul Resolution by <span class="tooltip-value">40%</span>, and reduces its Mana cost by <span class="tooltip-value">80%</span>.</div>'],
		},
		{
			index: 37,
			name: "Trap of Magic",
			ranks: 3,
			desc: "Increases the damage of Exorcising Bullet by <span class='tooltip-value'>#%</span>. Dismounts and silences players affected by Hunter Mark for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Oppression",
			ranks: 3,
			desc: "Increases the bonus damage of each shot of Burst of Rage by <span class='tooltip-value'>#%</span>. Increases its damage by <span class='tooltip-value'>#%</span> while Crack Shot Time is active.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 18,
		},
		{
			index: 40,
			name: "Dwarfs Luck",
			ranks: 2,
			desc: "Increases the chance for your single-target attacks to apply their effects by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 42,
			name: "Hindering Mark",
			ranks: 2,
			desc: "Reduces the movement speed of targets affected by Hunter Mark by <span class='tooltip-value'>#%</span>. Reduces the effectiveness of healing skills cast on the target by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 43,
			name: "Soul Focus",
			ranks: 3,
			desc: "Reduces the cooldown of Soul Resolution by <span class='tooltip-value'>#</span> seconds, Double Shot by <span class='tooltip-value'>#</span> seconds, and Spare Ammo by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 15, 20],
			rankInfo3: [10, 20, 30],
			parent: 21,
		},
		{
			index: 46,
			name: "Spare Ammo",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>463 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nGenerates 5 Soul Bullets, and resets the cooldowns of Soul Resolution and Double Shot. For the next 10 seconds, your single-target offensive Fire skills cost no Soul Bullets while Crack Shot Time is active. This skill is not affected by controlling effects.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Quartermaster",
			ranks: 4,
			ranksnw: 1,
			desc: "Rapid Loading Has a <span class='tooltip-value'>#%</span> chance to generate 3 additional bullets.",
			rankInfo: [25, 50, 75, 100],
			parent: 27,
		},
		{
			index: 49,
			name: "Hot Fire",
			ranks: 3,
			desc: "Increases single Fire Skill's Crit Chance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 52,
			name: "Incendiary",
			ranks: 2,
			desc: "While Double Shot is active, targets of single-target Fire skills will suffer a Burn effect. Dealing <span class='tooltip-value'>#</span> plus 30% of Fire Mastery in damage each second for 8 seconds.",
			rankInfo: [200, 400],
		},
		{
			index: 55,
			name: "Gun Master",
			ranks: 1,
			desc: "The cooldown of Rapid Reloading is reduced by 30 seconds. Rapid Reloading resets the cooldown of Quick Reloading.",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Heat Bullet",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the bonus damage of Soul Snipe by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [45, 60, 75, 90, 105],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the bonus damage of Soul Snipe by <span class="tooltip-value">12%</span> plus <span class="tooltip-value">120</span>.</div>'],
		},
		{
			index: 2,
			name: "Lava Burst",
			ranks: 5,
			ranksnw: 2,
			desc: "Grants Penetrating Shot a <span class='tooltip-value'>#%</span> chance to reduce the target's Earth and Fire Resistances by <span class='tooltip-value'>#</span> for 10 seconds, and a <span class='tooltip-value'>#%</span> chance to consume no Soul Bullets while Crack Shot Time is active.",
			rankInfo: [80, 85, 90, 95, 100],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Swift Penetration",
			ranks: 4,
			desc: "Reduces the cooldown of Penetrating Shot by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the cooldown of Penetrating Shot by <span class="tooltip-value">5</span> second(s).</div>'],
			parent: 1,
		},
		{
			index: 7,
			name: "Discrete",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the range of Weakening Cloud by <span class='tooltip-value'>#</span> meters and reduces its cooldown by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the range of Weakening Cloud by <span class="tooltip-value">8</span> meters and reduces its cooldown by <span class="tooltip-value">40</span> seconds.</div>'],
		},
		{
			index: 8,
			name: "Flame Mastery",
			ranks: 5,
			desc: "Increases your Fire Mastery by <span class='tooltip-value'>#</span>, and increases its effect by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [2, 4, 6, 8, 10],
		},
		{
			index: 9,
			name: "Soul Burn",
			ranks: 2,
			desc: "Grants Soul Snipe a <span class='tooltip-value'>#%</span> chance to inflict a burn effect on the target for 8 seconds, which deals an amount of damage equal to <span class='tooltip-value'>#</span> plus 10% of your Fire Mastery each second.",
			rankInfo: [50, 100],
			rankInfo2: [75, 100],
			parent: [0],
		},
		{
			index: 10,
			name: "Rake of Fury",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 6 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 16 meters</span>\n\nAttacks targets in a 90 degree arc within 18.0 meters. Deals 100% of your Attack plus <span class='tooltip-value'>#</span> bonus damage. Inflicts a burn effect on each target within 8 meters for 5 seconds, which deals damage equal to <span class='tooltip-value'>#</span> plus 20% of your Fire Mastery. Beyond 8 meters, the chance to burn a target is halved. Rake of Fury costs 1 Soul Bullet, its bonus damage is increased by 20%, the duration of the burning effect is increased by 3 seconds, and it deals bonus damage equal to 30% of your Fire Mastery while Crack Shot Time is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [202, 299, 398, 498],
			rankInfo3: [791, 1436, 2069, 2690],
			rankInfo4: [60, 120, 180, 240],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">601</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Fire damage</span><span class="right">Cooldown: 6 seconds</span>\n<br><span class="left">Multi-target attack</span><span class="right">Range: 16 meters</span>\n\n<br><br>Attacks targets in a 90 degree arc within 18.0 meters. Deals 100% of your Attack plus <span class="tooltip-value">3300</span> bonus damage. Inflicts a burn effect on each target within 8 meters for 5 seconds, which deals damage equal to <span class="tooltip-value">300</span> plus 20% of your Fire Mastery. Beyond 8 meters, the chance to burn a target is halved. Rake of Fury costs 1 Soul Bullet, its bonus damage is increased by 20%, the duration of the burning effect is increased by 3 seconds, and it deals bonus damage equal to 30% of your Fire Mastery while Crack Shot Time is active.</div>'],
		},
		{
			index: 13,
			name: "Speed of Fire",
			ranks: 4,
			ranksnw: 1,
			desc: "Fast Action increases your movement speed by an additional <span class='tooltip-value'>#%</span> and your Evasion by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [15, 30, 45, 60],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Fast Action increases your movement speed by an additional <span class="tooltip-value">25%</span> and your Evasion by <span class="tooltip-value">75</span>.</div>'],
		},
		{
			index: 14,
			name: "Scorching Heat",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the damage of the burn effect inflicted by Rake of Fury by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
			parent: 6,
		},
		{
			index: 15,
			name: "Flammable",
			ranks: 1,
			desc: "Weakening Cloud reduces the Health and Mana of targets affected by a burn effect by 1000. This effect increases by 500 for each level of Weakening Cloud. It also interrupts casting and knocks the targets back. (Only effective against mobs.)",
			rankInfo: [],
			parent: 3,
		},
		{
			index: 17,
			name: "Zealous Support",
			ranks: 2,
			desc: "Reduces the cooldown of Fast Action by <span class='tooltip-value'>#</span> seconds. Grants Fast Action a <span class='tooltip-value'>#%</span> chance to remain active after being struck 5 times.",
			rankInfo: [5, 10],
			rankInfo2: [50, 100],
			parent: 7,
		},
		{
			index: 19,
			name: "Backup Fire",
			ranks: 2,
			desc: "Reduces the cooldowns of Penetrating Shot and Rake of Fury by <span class='tooltip-value'>#%</span> while Quick Reloading is active.",
			rankInfo: [50, 100],
		},
		{
			index: 20,
			name: "Scorching Blood",
			ranks: 3,
			desc: "Increases your Fire Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 21,
			name: "Efficient Penetration",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the bonus damage of Penetrating Shot by <span class='tooltip-value'>#%</span>, and reduces its Mana cost by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the bonus damage of Penetrating Shot by <span class="tooltip-value">20%</span>, and reduces its Mana cost by <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 22,
			name: "Bullet Screen",
			ranks: 4,
			desc: "Increases the range of your multi-target offensive skills by <span class='tooltip-value'>#%</span>. Reduces the cooldown of Rake of Fury by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			parent: 8,
		},
		{
			index: 27,
			name: "Stone Smelt",
			ranks: 4,
			desc: "Pulse Shot reduces the max Health of targets affected by a burn effect by <span class='tooltip-value'>#%</span> and reduces the effectiveness of healing skills cast on them by <span class='tooltip-value'>#%</span> for 10 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12, 16],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Pulse Shot reduces the max Health of targets affected by a burn effect by <span class="tooltip-value">20%</span> and reduces the effectiveness of healing skills cast on them by <span class="tooltip-value">50%</span> for 10 seconds.</div>'],
		},
		{
			index: 28,
			name: "Flame Profession",
			ranks: 5,
			desc: "Reduces the Mana costs of your offensive Fire skills by <span class='tooltip-value'>#%</span>, and increases their damage by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Reduces the Mana costs of your offensive Fire skills by <span class="tooltip-value">36%</span>, and increases their damage by <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 29,
			name: "Shrapnel",
			ranks: 3,
			desc: "Increases the damage of Penetrating Shot by <span class='tooltip-value'>#%</span>. Increases the duration of its slow effect by <span class='tooltip-value'>#</span> second(s) while Crack Shot Time is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the damage of Penetrating Shot by <span class="tooltip-value">40%</span>. Increases the duration of its slow effect by <span class="tooltip-value">4</span> second(s) while Crack Shot Time is active.</div>'],
			parent: 13,
		},
		{
			index: 30,
			name: "Burning Rage",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nIncreases the damage of your next 3 attacks by <span class='tooltip-value'>#%</span> of your max Attack. Lasts for up to 15 seconds. If you're attacked while casting, you will go into an anger state, which increases the Crit Chance of your next 3 attacks by 10% for up to 15 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [245, 301],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">361</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: 30 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases the damage of your next 3 attacks by <span class="tooltip-value">25%</span> of your max Attack. Lasts for up to 15 seconds. If you\'re attacked while casting, you will go into an anger state, which increases the Crit Chance of your next 3 attacks by 10% for up to 15 seconds.</div>'],
		},
		{
			index: 31,
			name: "Motivate",
			ranks: 3,
			desc: "Accuracy Guidance increases your Crit damage by <span class='tooltip-value'>#%</span>. Reduces its Mana cost by <span class='tooltip-value'>#%</span>, and increases its duration by <span class='tooltip-value'>#</span> minutes.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [5, 10, 15],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Accuracy Guidance increases your Crit damage by <span class="tooltip-value">8%</span>. Reduces its Mana cost by <span class="tooltip-value">80%</span>, and increases its duration by <span class="tooltip-value">20</span> minutes.</div>'],
		},
		{
			index: 34,
			name: "Undying Rage",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the duration of Burning Rage by <span class='tooltip-value'>#</span> seconds. If you are attacked within <span class='tooltip-value'>#</span> second(s) of casting it. you will enter the Anger state.",
			rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			parent: 18,
		},
		{
			index: 35,
			name: "Soul Catch",
			ranks: 3,
			desc: "If you use Burning Rage or Double Shot to kill a target within 10 levels of your own, or if you make the kill while Soul Resolution is active, you will have a <span class='tooltip-value'>#%</span> chance to generate a Soul Bullet.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 37,
			name: "Soul Resistance",
			ranks: 3,
			desc: "When you are attacked while Soul Resolution is active, your Resistances will be increased by <span class='tooltip-value'>#</span> and your Defense will be increased by <span class='tooltip-value'>#</span> for 10 seconds. Stacks 3 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>When you are attacked while Soul Resolution is active, your Resistances will be increased by <span class="tooltip-value">40</span> and your Defense will be increased by <span class="tooltip-value">40</span> for 10 seconds. Stacks 3 times.</div>'],
		},
		{
			index: 39,
			name: "Extended Burning",
			ranks: 2,
			desc: "Increases the durations of your burn effects by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 42,
			name: "Soul Spark",
			ranks: 2,
			desc: "Restores <span class='tooltip-value'>#%</span> of your max Health while Extreme Fury is active. Those skills have a <span class='tooltip-value'>#%</span> chance to cost no Soul Bullets while Crack Shot Time is active.",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
			parent: 20,
		},
		{
			index: 43,
			name: "Enervating Fire",
			ranks: 2,
			desc: "Soul Snipe and Rake of Fury inflict a burn effect on the target that reduces the target's base Attack by <span class='tooltip-value'>#%</span>. Stacks 10 times.",
			rankInfo: [1, 2],
		},
		{
			index: 46,
			name: "High Velocity Shot",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>781 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 18 meters</span>\n\nAttack fires a shot in a straight line for 16.0 meters, hitting up to 15 targets. Deals 100% of your base Attack, plus 4366 bonus damage. While Crack Shot Time is active, High Velocity Shot costs 1 Soul Bullet, its bonus damage is increased by 20%, and it dispels burn effects inflicted by Soul Snipe and Rake of Fury on the target. Silences the target for up to 4 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Wild Fire",
			ranks: 4,
			desc: "Reduces the cooldown of High Velocity Shot by <span class='tooltip-value'>#</span> seconds, and increases the Base Attack of High Velocity Shot by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [10, 20, 30, 40],
			parent: 26,
		},
		{
			index: 49,
			name: "Flame Vortex",
			ranks: 2,
			desc: "Increases the Base Attack of Burning Swirl by <span class='tooltip-value'>#%</span>, and increases the duration of the Disarm effect by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [10, 20],
			rankInfo2: [1, 2],
		},
		{
			index: 51,
			name: "Hollow Point",
			ranks: 3,
			desc: "Increases Crit Damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 54,
			name: "Rail Gun",
			ranks: 1,
			desc: "Increases bonus damage of High Velocity Shot by 50%. Reduces the skill’s casting time by 50%, and reduces the skill’s cooldown by 8 seconds.",
			rankInfo: [],
			parent: 26,
		},
	]
];