var data = [
	// one
	[
		{
			index: 1,
			name: "Отчаянная атака",
			ranks: 5,
			ranksnw: 1,
			desc: "Повышает меткость навыков «Аккорды ветра», «Рапсодия ветра» и «Реквием» на <span class='tooltip-value'>#</span> ед. Усиливает базовый урон от навыка «Аккорды ветра» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [9, 18, 27, 36, 45],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 3,
			name: "Темперамент",
			ranks: 5,
			desc: "Усиление «Пьес». С каждым уровнем таланта усиление атаки повышается на <span class='tooltip-value'>#</span> очков.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Усиление «Пьес». С каждым уровнем таланта усиление атаки повышается на <span class="tooltip-value">30</span> очков.</div>'],
		},
		{
			index: 5,
			name: "Дирижер ветра",
			ranks: 4,
			ranksnw: 1,
			desc: "Сокращает время перезарядки навыков «Аккорды ветра», «Рапсодия ветра» и «Реквием» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [0.5, 1, 1.5, 2],
			parent: [0],
		},
		{
			index: 6,
			name: "Ветер беззакония",
			ranks: 3,
			desc: "Сокращает время перезарядки навыка «Какофония» на <span class='tooltip-value'>#</span> сек. Навык ослабляет у цели сопротивление Воздуху на <span class='tooltip-value'>#</span> очков. С каждым уровнем дополнительно ослабляется на 5 очков, действует <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
		},
		{
			index: 7,
			name: "Мастерство музыканта",
			ranks: 2,
			desc: "Увеличивает радиус действия массовых эффектов Пьес, Арий и Нот на <span class='tooltip-value'>#</span> м.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает радиус действия массовых эффектов Пьес, Арий и Нот на <span class="tooltip-value">6</span> м.</div>'],
		},
		{
			index: 8,
			name: "Протяжные напевы",
			ranks: 3,
			desc: "Увеличивает время действия Пьес и аккордов «C» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает время действия Пьес и аккордов «C» на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 10,
			name: "Ария ветра",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: <span class='tooltip-value'>#</span> сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nПозволяющий получить 2 аккорда «C». Эффект тот же, что и от аккорда «C», порожденного «Аккордами ветра». На 15 сек. увеличивает мастерство Ветра на <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [230, 327, 425, 524],
			rankInfo3: [30, 27, 24, 21],
			rankInfo4: [100, 120, 140, 160],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">625</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: <span class="tooltip-value">18</span> сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Позволяющий получить 2 аккорда «C». Эффект тот же, что и от аккорда «C», порожденного «Аккордами ветра». На 15 сек. увеличивает мастерство Ветра на <span class="tooltip-value">180</span>.</div>'],
		},
		{
			index: 11,
			name: "Скорость звука",
			ranks: 3,
			desc: "Каждый аккорд «C» ускоряет передвижение персонажа на <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 12,
			name: "Легкий ветерок",
			ranks: 4,
			desc: "Усиливает навыки «Пьеса: Мужество», «Пьеса: Грезы», «Ария величия», «Ария исцеления», «Ария искупления». Эффект массового благословения <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Усиливает навыки «Пьеса: Мужество», «Пьеса: Грезы», «Ария величия», «Ария исцеления», «Ария искупления». Эффект массового благословения <span class="tooltip-value">25%</span>.</div>'],
		},
		{
			index: 13,
			name: "Тень ветра",
			ranks: 3,
			ranksnw: 1,
			desc: "Повышает шанс нанести критический урон навыками «Аккорды ветра», «Рапсодия ветра» и «Реквием» на <span class='tooltip-value'>#%</span>. Позволяет с их помощью ослабить у выбранной цели базовую защиту на <span class='tooltip-value'>#%</span> и постоянное значение на <span class='tooltip-value'>#</span> очков. Длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [0.5, 1, 1.5],
			rankInfo3: [25, 50, 75],
			rankInfo4: [10, 12, 14],
			parent: 2,
		},
		{
			index: 15,
			name: "Божественная песнь ветра",
			ranks: 3,
			desc: "Увеличивает время действия сна на <span class='tooltip-value'>#</span> сек. Также у персонажа усиливается уклонение на <span class='tooltip-value'>#</span> очков. Длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			rankInfo3: [13, 14, 15],
		},
		{
			index: 16,
			name: "Ритмы ветра",
			ranks: 4,
			desc: "Повышает мастерство Воздуха на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Песчаная буря",
			ranks: 2,
			desc: "Позволяет с помощью навыков «Аккорды ветра», «Рапсодия ветра» и «Реквием» ослабить получаемое выбранной целью лечение на <span class='tooltip-value'>#%</span>, длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [15, 30],
			rankInfo2: [10, 15],
			parent: 9,
		},
		{
			index: 18,
			name: "Изысканная ария ветра",
			ranks: 3,
			desc: "Сокращает время перезарядки навыка «Ария ветра» на <span class='tooltip-value'>#</span> сек. «Ария ветра» может ввести персонажа в состояние повышенной защиты, сокращая весь получаемый урон на <span class='tooltip-value'>#%</span>. Длительность - 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 7, 10],
			rankInfo2: [3, 6, 9],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращает время перезарядки навыка «Ария ветра» на <span class="tooltip-value">13</span> сек. «Ария ветра» может ввести персонажа в состояние повышенной защиты, сокращая весь получаемый урон на <span class="tooltip-value">12%</span>. Длительность - 15 сек.</div>'],
			parent: 6,
		},
		{
			index: 19,
			name: "Управление ветром",
			ranks: 2,
			desc: "Одновременно с ускорением «Песнь ветра» также дает эффект иммунитета к <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['замедлению', 'замедлению и параличу'],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Одновременно с ускорением «Песнь ветра» также дает эффект иммунитета к <span class="tooltip-value">замедлению, параличу и кровотечению</span>.</div>'],
		},
		{
			index: 22,
			name: "Ритмы ветра",
			ranks: 2,
			desc: "Уменьшает время восстановления «Паузы» на <span class='tooltip-value'>#</span> сек. Во время действия «Паузы» увеличивает силу атаки «Аккорда ветра», «Рапсодии ветра» и «Реквиема» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 15],
			rankInfo2: [15, 30],
		},
		{
			index: 24,
			name: "Отпор ветрам",
			ranks: 4,
			desc: "Повышение сопротивления Воздуху на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 25,
			name: "Улучшенные аккорды ветра",
			ranks: 3,
			desc: "Аккорды «C» могут усиливать базовый урон от навыков «Аккорды ветра», «Рапсодия ветра», «Реквием», и базовый урон первого этапа навыка «Блики инея» на <span class='tooltip-value'>#%</span>; степень усиления не зависит от количества аккордов «C».\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Аккорды «C» могут усиливать базовый урон от навыков «Аккорды ветра», «Рапсодия ветра», «Реквием», и базовый урон первого этапа навыка «Блики инея» на <span class="tooltip-value">40%</span>; степень усиления не зависит от количества аккордов «C».</div>'],
		},
		{
			index: 26,
			name: "Пьеса: Ветер",
			ranks: 2,
			desc: "Срабатывает автоматически, когда у барда соберется комбинация из трех аккордов «C» и «Паузы» (последовательность не имеет значения). Дает увеличение скорости союзникам в радиусе 16 м., ускоряя передвижение до 170%. Длительность - <span class='tooltip-value'>#%</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 12],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Срабатывает автоматически, когда у барда соберется комбинация из трех аккордов «C» и «Паузы» (последовательность не имеет значения). Дает увеличение скорости союзникам в радиусе 16 м., ускоряя передвижение до 170%. Длительность - <span class="tooltip-value">14%</span> сек.</div>'],
		},
		{
			index: 28,
			name: "Отчаянная атака ветра",
			ranks: 2,
			desc: "Массовые «Пьесы» могут повышать меткость окружающих союзников на <span class='tooltip-value'>#%</span> очков.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 25],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Массовые «Пьесы» могут повышать меткость окружающих союзников на <span class="tooltip-value">35%</span> очков.</div>'],
		},
		{
			index: 29,
			name: "Изысканная рапсодия ветра",
			ranks: 2,
			desc: "Время перезарядки навыка «Рапсодия ветра» сокращается на <span class='tooltip-value'>#</span> сек., базовый урон усиливается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 30,
			name: "Песнь свободы",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: <span class='tooltip-value'>#</span> сек.</span>\n<span class='left'>Массовое благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nСнимает с союзников в радиусе 16 м. вокруг персонажа замедление и паралич. Данный навык нельзя изменить с помощью контроля эффектов.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [345, 414],
			rankInfo3: [90, 60],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">487</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: <span class="tooltip-value">30</span> сек.</span>\n<br><span class="left">Массовое благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Снимает с союзников в радиусе 16 м. вокруг персонажа замедление и паралич. Данный навык нельзя изменить с помощью контроля эффектов.</div>'],
		},
		{
			index: 31,
			name: "Скорость ветра",
			ranks: 2,
			desc: "Эффект ускорения от навыков «Песнь ветра» и «Пьеса: Ветер» усиливается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
		},
		{
			index: 35,
			name: "Ураганная пьеса",
			ranks: 2,
			desc: "Пьесы, действующие на несколько целей, увеличивают шанс нанесения крит. урона на <span class='tooltip-value'>#%</span>, а критическое уклонение - на <span class='tooltip-value'>#%</span>. Каждые 4 секунды с вероятностью 25% восстанавливается <span class='tooltip-value'>#%</span> от максимального количества очков маны. «Пьеса: Ветер» каждую секунду с вероятностью в 25% восстанавливает указанное выше количество маны.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.5, 1],
			rankInfo2: [1, 2],
			rankInfo3: [0.5, 1],
			rankInfo4: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Пьесы, действующие на несколько целей, увеличивают шанс нанесения крит. урона на <span class="tooltip-value">1.5%</span>, а критическое уклонение - на <span class="tooltip-value">3%</span>. Каждые 4 секунды с вероятностью 25% восстанавливается <span class="tooltip-value">1.5%</span> от максимального количества очков маны. «Пьеса: Ветер» каждую секунду с вероятностью в 25% восстанавливает указанное выше количество маны.</div>'],
		},
		{
			index: 36,
			name: "Сопротивление лезвиям ветра",
			ranks: 3,
			desc: "Сокращает весь получаемый урон на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращает весь получаемый урон на <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 38,
			name: "Изысканная песнь свободы",
			ranks: 2,
			desc: "«Песнь свободы» снимает эффект сна. (Навык 2 ур. снимает эффект головокружения, а навык 3 ур. – эффекты безмолвия и разоружения). Уменьшает время перезарядки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			parent: 21,
		},
		{
			index: 39,
			name: "Воодушевление",
			ranks: 3,
			desc: "Каждый уровень «Пьесы: Мужество» увеличивает силу атаки отряда на <span class='tooltip-value'>#%</span> от силы атаки барда.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [0.6, 1.2, 1.8],
		},
		{
			index: 41,
			name: "Буря",
			ranks: 2,
			desc: "Увеличивает базовый урон навыков «Аккорды ветра», «Рапсодия ветра», «Реквием» и «Блики инея» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
		},
		{
			index: 42,
			name: "Постижение пения ветра",
			ranks: 3,
			desc: "Уменьшает время восстановления навыков «Ария ветра», «Песнь свободы», «Реквием» и «Блики инея» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 46,
			name: "Реквием",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>491 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Воздуха</span><span class='right'>Время перезарядки: 6 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 14 м.</span>\n\nАтакует противников в радиусе 10 м. вокруг цели (не более 15). Наносит 100% базового урона и дополнительно 1495 ед. урона. Добавляет аккорд «C».",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Вечный покой",
			ranks: 4,
			desc: "Повышает базовую атаку навыка «Реквием» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
			parent: 29,
		},
		{
			index: 49,
			name: "Кольцо ветра",
			ranks: 3,
			desc: "Повышает крит. урон на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 51,
			name: "Лезвие холодного ветра",
			ranks: 2,
			desc: "Увеличивает базовую атаку навыка «Блики инея» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 54,
			name: "Песня души",
			ranks: 1,
			desc: "Повышает бонус к базовой атаке навыка «Реквием» на 50%.",
			rankInfo: [],
			parent: 29,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Изысканные аккорды воды",
			ranks: 5,
			desc: "Увеличивает базовый урон для «Аккордов воды» на <span class='tooltip-value'>#%</span>, дополнительно усиливает атаку в размере <span class='tooltip-value'>#%</span> от мастерства Воды.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [20, 40, 60, 80, 100],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивает базовый урон для «Аккордов воды» на <span class="tooltip-value">30%</span>, дополнительно усиливает атаку в размере <span class="tooltip-value">120%</span> от мастерства Воды.</div>'],
		},
		{
			index: 3,
			name: "Волны",
			ranks: 5,
			desc: "Усиливает атаку навыком «Ноты: Волна» на <span class='tooltip-value'>#</span> очков.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 60, 90, 120, 150],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Усиливает атаку навыком «Ноты: Волна» на <span class="tooltip-value">180</span> очков.</div>'],
		},
		{
			index: 5,
			name: "Управление водной рябью",
			ranks: 4,
			ranksnw: 1,
			desc: "Сокращает время перезарядки навыков «Аккорды воды», «Мелодия воды» и «Рондо водной ряби» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [0.5, 1, 1.5, 2],
		},
		{
			index: 6,
			name: "Воды беззакония",
			ranks: 3,
			desc: "Увеличивает шанс нанесения критического урона навыка «Какофония» на <span class='tooltip-value'>#%</span>. «Какофония» ослабляет у цели сопротивление магии воды на <span class='tooltip-value'>#</span> очков. С каждым уровнем «Воды беззакония» сопротивление дополнительно ослабляется на 5 очков, действует <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает шанс нанесения критического урона навыка «Какофония» на <span class="tooltip-value">4%</span>. «Какофония» ослабляет у цели сопротивление магии воды на <span class="tooltip-value">40</span> очков. С каждым уровнем «Воды беззакония» сопротивление дополнительно ослабляется на 5 очков, действует <span class="tooltip-value">40</span> сек.</div>'],
		},
		{
			index: 7,
			name: "Иней",
			ranks: 3,
			desc: "«Ледяной ветер» дополнительно уменьшает скорость цели на <span class='tooltip-value'>#%</span>. Ледяной ветер 3 ур. замораживает цель на 1 сек.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 8,
			name: "Навязчивая мелодия",
			ranks: 3,
			desc: "Продлевает время действия «Нот» и аккордов «D» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Продлевает время действия «Нот» и аккордов «D» на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 9,
			name: "Ледяные иглы",
			ranks: 3,
			desc: "Позволяют навыкам «Аккорды воды», «Мелодия воды» и «Рондо водной ряби» дополнительно сокращать текущее количество маны у цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
			parent: 2,
		},
		{
			index: 10,
			name: "Ария воды",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: <span class='tooltip-value'>#</span> сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nПозволяет персонажу войти в состояние повышенной защиты. В этом состоянии персонаж обладает иммунитетом к головкружению и немоте, получаемый урон сокращается на 40% и при каждом получении урона восстанавливается <span class='tooltip-value'>#%</span> маны (не более 6 раз). Каждый аккорд «D» добавляет 2 дополнительных раза. Это состояние длится не дольше <span class='tooltip-value'>#</span> сек. Данный навык нельзя изменить с помощью контроля эффектов.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [268, 381, 496, 612],
			rankInfo3: [40, 35, 30, 25],
			rankInfo4: [5, 7, 9, 11],
			rankInfo5: [12, 14, 16, 18],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">729</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: <span class="tooltip-value">20</span> сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Позволяет персонажу войти в состояние повышенной защиты. В этом состоянии персонаж обладает иммунитетом к головкружению и немоте, получаемый урон сокращается на 40% и при каждом получении урона восстанавливается <span class="tooltip-value">13%</span> маны (не более 6 раз). Каждый аккорд «D» добавляет 2 дополнительных раза. Это состояние длится не дольше <span class="tooltip-value">20</span> сек. Данный навык нельзя изменить с помощью контроля эффектов.</div>'],
		},
		{
			index: 12,
			name: "Колдовское мастерство",
			ranks: 3,
			desc: "Сокращает затраты на все заклинания атаки на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 13,
			name: "Наплыв вдохновения",
			ranks: 3,
			desc: "Каждый аккорд «D» усиливает защиту на <span class='tooltip-value'>#%</span>, значение уклонения на <span class='tooltip-value'>#</span> очков.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [3, 6, 9],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Каждый аккорд «D» усиливает защиту на <span class="tooltip-value">4%</span>, значение уклонения на <span class="tooltip-value">12</span> очков.</div>'],
		},
		{
			index: 15,
			name: "Божественная песнь воды",
			ranks: 1,
			desc: "При использовании навыка «Чарующие звуки» цель в течение 20 сек. при получении ледяной атаки замораживается на 3 сек., после получения 3 атак состояние прерывается.",
			rankInfo: [],
		},
		{
			index: 16,
			name: "Постижение потока",
			ranks: 4,
			desc: "Увеличивает мастерство Воды на <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 18,
			name: "Изысканная ария воды",
			ranks: 3,
			desc: "Сокращает время перезарядки навыка «Ария воды» на <span class='tooltip-value'>#</span> сек., продлевает время его действия на <span class='tooltip-value'>#</span> сек. При каждом получении урона восстанавливает персонажу здоровье в размере <span class='tooltip-value'>#%</span> от максимального запаса маны.",
			rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			rankInfo3: [2, 4, 6],
			parent: 7,
		},
		{
			index: 19,
			name: "Пение ветра и воды",
			ranks: 3,
			desc: "Продлевает время действия навыка «Песнь ветра» на <span class='tooltip-value'>#</span> сек. Сокращает время перезарядки навыка «Песнь ветра» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 20,
			name: "Загрузка",
			ranks: 2,
			desc: "Позволяет повысить шанс иммунитета к крит. урону для бардов во время действия «Нот» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Позволяет повысить шанс иммунитета к крит. урону для бардов во время действия «Нот» на <span class="tooltip-value">3%</span>.</div>'],
		},
		{
			index: 22,
			name: "Усиление водной ряби",
			ranks: 2,
			desc: "Во время «Паузы» увеличивает шанс нанесения крит. урона «Аккорда воды», «Мелодии воды» и «Рондо водной ряби» на <span class='tooltip-value'>#%</span>. Увеличивает критический урон на <span class='tooltip-value'>#%</span>, длительность эффекта заморозки при использовании навыков «Мелодия воды» и «Рондо водной ряби» увеличивается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4],
			rankInfo2: [5, 10],
			rankInfo3: [1, 2],
		},
		{
			index: 24,
			name: "Разделение потока",
			ranks: 4,
			desc: "Повышает сопротивление Воде на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 25,
			name: "Улучшенные аккорды воды",
			ranks: 3,
			desc: "Аккорды «D» могут усиливать базовой урон от навыков «Аккорды воды», «Мелодия воды», «Рондо водной ряби» и базовый урон от второго этапа навыка «Блики инея» на <span class='tooltip-value'>#%</span>, степень усиления не зависит от количества аккордов «D».",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Ноты: Песня воды",
			ranks: 2,
			ranksnw: 1,
			desc: "Срабатывает автоматически, когда у барда собирается комбинация из трех аккордов «D» и «Паузы» (последовательность не имеет значения). В течение <span class='tooltip-value'>#</span> сек. каждый сыгранный аккорд увеличивает базовый урон на <span class='tooltip-value'>#%</span>. Длительность - 10 сек., суммируется до 5 раз.",
			rankInfo: [15, 17],
			rankInfo2: [5, 6],
		},
		{
			index: 27,
			name: "Острие",
			ranks: 2,
			desc: "Увеличивает атаку навыка «Ноты: Песня воды» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает атаку навыка «Ноты: Песня воды» на <span class="tooltip-value">3%</span>.</div>'],
			parent: 18,
		},
		{
			index: 29,
			name: "Хрупкий лед",
			ranks: 3,
			desc: "В момент срабатываний любой из «Нотных тетрадей» существует <span class='tooltip-value'>#%</span> вероятности обнуления периода перезарядки навыков «Аккорды воды», «Мелодия воды» и «Рондо водной ряби».",
			rankInfo: [30, 60, 100],
		},
		{
			index: 30,
			name: "Трио",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>295 ОМ</span><span class='right'>Чтение: 1.5 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nУменьшает время перезарядки навыков Воды, на 60%; увеличивает время перезарядки навыков Воздуха и Света на 60%. Увеличивает критический шанс навыков Воды, на 4%; время действия - 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n'],
			rankInfo2: ['<div class="runelvl">\n<br>Уровень: 2/1 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">362</span> ОМ</span><span class="right">Чтение: 1.5 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 90 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Уменьшает время перезарядки навыков Воды, на 60%; увеличивает время перезарядки навыков Воздуха и Света на 60%. Увеличивает критический шанс навыков Воды, на <span class="tooltip-value">6%</span>; время действия - 15 сек.</div>'],
		},
		{
			index: 31,
			name: "Водяная цитра",
			ranks: 1,
			ranksnw: 1,
			desc: "«Трио» увеличивает дальность атаки навыков Воды на 6 м. Длительность действия увеличивается на 3 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [],
			parent: 21,
		},
		{
			index: 33,
			name: "Изысканная пьеса воды",
			ranks: 3,
			desc: "«Мелодия воды» отнимает у цели ману и одновременно наносит соразмерные физические повреждения, урон дополнительно усиливается на <span class='tooltip-value'>#</span> ед. Время перезарядки сокращено на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [100, 200, 300],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 36,
			name: "Ледяное лезвие",
			ranks: 3,
			desc: "Усиливает атаку на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [30, 60, 90],
		},
		{
			index: 38,
			name: "Изысканное трио",
			ranks: 3,
			desc: "«Трио» усиливает шанс критической атаки навыков Воды на <span class='tooltip-value'>#%</span>, после добавления 3 очков сокращает время перезарядки навыков Воды на 20%. Сокращает время перезарядки навыка «Трио» сокращено на 10 сек.",
			rankInfo: [1, 2, 3],
			parent: 21,
		},
		{
			index: 39,
			name: "Рифмы воды",
			ranks: 2,
			desc: "Персонаж в состоянии Волны посредством навыков «Мелодия воды» и «Рондо водной ряби» ослабляет атаку у цели на <span class='tooltip-value'>#%</span>. Также понижается меткость цели на <span class='tooltip-value'>#</span> очков. Длительность - 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Персонаж в состоянии Волны посредством навыков «Мелодия воды» и «Рондо водной ряби» ослабляет атаку у цели на <span class="tooltip-value">15%</span>. Также понижается меткость цели на <span class="tooltip-value">45</span> очков. Длительность - 10 сек.</div>'],
		},
		{
			index: 42,
			name: "Перевернутое отражение",
			ranks: 3,
			desc: "Если персонаж, находясь в состоянии «Ария воды», получает урон, на атакующих персонажей накладывается эффект замедления. Скорость передвижения противников снижается на <span class='tooltip-value'>#%</span> на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 40, 50],
			rankInfo2: [5, 6, 7],
		},
		{
			index: 43,
			name: "Удар лезвием воды",
			ranks: 2,
			desc: "Дополнительный урон навыков «Аккорды воды», «Мелодии воды» и «Рондо водной ряби» увеличивается на <span class='tooltip-value'>#%</span>. Применение навыка «Блики инея» с вероятностью <span class='tooltip-value'>#%</span> прервет сотворение заклинания цели.",
			rankInfo: [10, 20],
			rankInfo2: [50, 100],
		},
		{
			index: 46,
			name: "Рондо водной ряби",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>425 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Воды</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 14 м.</span>\n\nНаносит 100% базового урона и дополнительно 2217 ед. урона. Добавляет аккорд «D». С вероятностью в 25% замораживает цель на 2 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Глубокий укол",
			ranks: 4,
			desc: "Повышает крит. урон, наносимый навыком «Рондо водной ряби» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12, 16],
			parent: 29,
		},
		{
			index: 49,
			name: "Ария льда",
			ranks: 3,
			desc: "«Ноты: Вьюга» повышают базовую силу атаки барда на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 52,
			name: "Пронизывающая вьюга",
			ranks: 2,
			desc: "«Блики инея» снижает крит. уклонение цели на <span class='tooltip-value'>#%</span>, длительность - 15 сек.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Загробная песнь",
			ranks: 1,
			desc: "Увеличивает базовую силу атаки навыка «Рондо водной ряби» на 50%.",
			rankInfo: [],
			parent: 29,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Изысканные аккорды света",
			ranks: 5,
			desc: "Увеличивает базовый урон «Аккордов света» на <span class='tooltip-value'>#%</span>, дополнительно усиливают атаку в размере <span class='tooltip-value'>#%</span> от мастерства Света.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [20, 40, 60, 80, 100],
		},
		{
			index: 2,
			name: "Благословение света",
			ranks: 5,
			desc: "Позволяет в момент появления аккорда «E» восстанавливать персонажу <span class='tooltip-value'>#</span> ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 80, 120, 160, 200],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Позволяет в момент появления аккорда «E» восстанавливать персонажу <span class="tooltip-value">240</span> ОЗ.</div>'],
		},
		{
			index: 5,
			name: "Слепящее сияние",
			ranks: 3,
			desc: "При действии «Аккордов света», «Музыки света» и «Фантазии света» дополнительно снижается меткость цели на <span class='tooltip-value'>#</span> ед. Длительность - <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [12, 16, 20],
			rankInfo2: [6, 8, 10],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При действии «Аккордов света», «Музыки света» и «Фантазии света» дополнительно снижается меткость цели на <span class="tooltip-value">24</span> ед. Длительность - <span class="tooltip-value">12</span> сек.</div>'],
		},
		{
			index: 6,
			name: "Свет беззакония",
			ranks: 3,
			desc: "Увеличивает базовый урон навыка «Какофония» на <span class='tooltip-value'>#%</span>. «Какофония» ослабляет у цели сопротивление магии света на <span class='tooltip-value'>#</span> очков. С каждым уровнем «Света беззакония» сопротивление дополнительно ослабляется на 5 очков, длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
		},
		{
			index: 7,
			name: "Божественная песнь света",
			ranks: 3,
			desc: "При использовании навыка «Чарующие звуки» снижает защиту окружающих противников на <span class='tooltip-value'>#%</span>, а также ослабляется меткость противников на <span class='tooltip-value'>#</span> очков, длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 13, 18],
			rankInfo2: [20, 30, 50],
			rankInfo3: [11, 13, 15],
		},
		{
			index: 8,
			name: "Длань закона",
			ranks: 3,
			desc: "Продлевает время действия арий и аккордов «E» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Продлевает время действия арий и аккордов «E» на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 9,
			name: "Концентрация взгляда",
			ranks: 3,
			desc: "Уменьшает вероятность прерывания всех навыков благословений и проклятий на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 30, 50],
		},
		{
			index: 10,
			name: "Ария света",
			ranks: 4,
			ranksnw: 1,	
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Лечение</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nВ зависимости от количества аккордов «E» моментально восстанавливает персонажу <span class='tooltip-value'>#</span> ОЗ. Имеется 2% вероятности срабатывания эффекта двойного исцеления (не суммируется). Также навыки исцеления персонажа, а также эффект получаемого лечения усиливается на 20% на 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [201, 305, 410, 516],
			rankInfo3: ['1272-1404/1881-2078/2461-2717/3010-3324', '1462-1615/2164-2389/2830-3125/3462-3822', '1653-1825/2446-2701/3199-3533/3913-4321', '1844-2036/2728-3013/3569-3941/4365-4820'],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">622</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Лечение</span><span class="right">Время перезарядки: 15 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>В зависимости от количества аккордов «E» моментально восстанавливает персонажу <span class="tooltip-value">3529-3897/4058-4481/4588-5066/5117-5650</span> ОЗ. Имеется 2% вероятности срабатывания эффекта двойного исцеления (не суммируется). Также навыки исцеления персонажа, а также эффект получаемого лечения усиливается на 20% на 10 сек.</div>'],
		},
		{
			index: 12,
			name: "Ореол света",
			ranks: 3,
			desc: "Увеличивает радиус действия «Чарующие звуки», «Песнь ветра» и «Соната жизни» на <span class='tooltip-value'>#</span> м.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает радиус действия «Чарующие звуки», «Песнь ветра» и «Соната жизни» на <span class="tooltip-value">8</span> м.</div>'],
		},
		{
			index: 13,
			name: "Божественная защита",
			ranks: 3,
			desc: "Увеличивает защиту от «Арии величия» на <span class='tooltip-value'>#%</span>. Защита увеличивается на <span class='tooltip-value'>#%</span> от базового показателя (прочие бонусы не учитываются). «Ария величия» поглощается <span class='tooltip-value'>#%</span> урона от навыков, наносящих урон по площади.",
			rankInfo: [10, 20, 30],
			rankInfo2: [3, 6, 9],
			rankInfo3: [3, 6, 9],
		},
		{
			index: 15,
			name: "Сияние жизни",
			ranks: 3,
			desc: "Сокращает время перезарядки навыка «Соната жизни» на <span class='tooltip-value'>#</span> сек. Добавляет навыку «Соната жизни» <span class='tooltip-value'>#%</span> вероятности снятия с цели состояний замедления, паралича и головокружения, а также последнего наложенного состояния кровотечения и горения. Для союзников в радиусе 8 м. вероятность рассеивания увеличивается в 2 раза.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4],
			rankInfo2: [15, 25, 35],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращает время перезарядки навыка «Соната жизни» на <span class="tooltip-value">5</span> сек. Добавляет навыку «Соната жизни» <span class="tooltip-value">45%</span> вероятности снятия с цели состояний замедления, паралича и головокружения, а также последнего наложенного состояния кровотечения и горения. Для союзников в радиусе 8 м. вероятность рассеивания увеличивается в 2 раза.</div>'],
		},
		{
			index: 16,
			name: "Ритмы света",
			ranks: 4,
			desc: "Повышает мастерство Света на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Колдовская тень",
			ranks: 2,
			desc: "Барды в момент активации любого из эффектов восстановления (кроме «Благословения света») могут с <span class='tooltip-value'>#%</span>-ной вероятностью войти в состояние «Колдовская тень» на 10 сек. В этом состоянии время перезарядки и затраты навыков лечения сокращаются вдвое.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Барды в момент активации любого из эффектов восстановления (кроме «Благословения света») могут с <span class="tooltip-value">45%</span>-ной вероятностью войти в состояние «Колдовская тень» на 10 сек. В этом состоянии время перезарядки и затраты навыков лечения сокращаются вдвое.</div>'],
		},
		{
			index: 18,
			name: "Изысканная ария света",
			ranks: 3,
			desc: "Усиливает эффект исцеления навыка «Ария света» на <span class='tooltip-value'>#%</span>. Сокращает время перезарядки на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 7,
		},
		{
			index: 19,
			name: "Законы исцеления",
			ranks: 3,
			desc: "Позволяет усиливать эффект получаемого лечения на <span class='tooltip-value'>#%</span> за каждый аккорд «E».\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Позволяет усиливать эффект получаемого лечения на <span class="tooltip-value">20%</span> за каждый аккорд «E».</div>'],
		},
		{
			index: 22,
			name: "Божественные силы",
			ranks: 2,
			desc: "Уменьшает время восстановления «Аккорда света», «Музыки света», «Фантазии света» на <span class='tooltip-value'>#</span> сек. В состоянии «Паузы» бард, будучи атакованным, восстанавливает <span class='tooltip-value'>#%</span> от максимального количества ОЗ. Можно использовать не больше 10 раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [3, 5],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшает время восстановления «Аккорда света», «Музыки света», «Фантазии света» на <span class="tooltip-value">3</span> сек. В состоянии «Паузы» бард, будучи атакованным, восстанавливает <span class="tooltip-value">7%</span> от максимального количества ОЗ. Можно использовать не больше 10 раз.</div>'],
		},
		{
			index: 24,
			name: "Отпор свету",
			ranks: 4,
			desc: "Повышает сопротивление Свету на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 25,
			name: "Улучшенные аккорды света",
			ranks: 3,
			desc: "Аккорды «E» могут усиливать базовый урон от навыков «Аккорды света», «Музыка света» и «Фантазия следов света» на <span class='tooltip-value'>#%</span>. Степень усиления не зависит от количества аккордов «E».",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Ария искупления",
			ranks: 2,
			ranksnw: 1,
			desc: "Срабатывает автоматически, когда у барда соберется комбинация из трех аккордов «E» и «Паузы» (последовательность не имеет значения). У союзников в радиусе 16 м. моментально восстанавливается <span class='tooltip-value'>#%</span> здоровья, а также снимается последнее полученное негативное состояние. Максимальное количество ОЗ увеличивается на <span class='tooltip-value'>#%</span>. Длительность - 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 25],
			rankInfo2: [10, 15],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Срабатывает автоматически, когда у барда соберется комбинация из трех аккордов «E» и «Паузы» (последовательность не имеет значения). У союзников в радиусе 16 м. моментально восстанавливается <span class="tooltip-value">30%</span> здоровья, а также снимается последнее полученное негативное состояние. Максимальное количество ОЗ увеличивается на <span class="tooltip-value">20%</span>. Длительность - 10 сек.</div>'],
		},
		{
			index: 27,
			name: "Песнь святых",
			ranks: 2,
			desc: "«Искупление» увеличивает максимальный запас здоровья на <span class='tooltip-value'>#%</span>. «Песнь» ускоряет передвижение барда на <span class='tooltip-value'>#%</span> и увеличивает уклонение на <span class='tooltip-value'>#</span> очков. Длительность - 6 сек.",
			rankInfo: [5, 10],
			rankInfo2: [15, 30],
			rankInfo3: [15, 30],
			parent: 18,
		},
		{
			index: 29,
			name: "Крещение светом",
			ranks: 2,
			desc: "Эффект восстановления, вызываемый навыком «Ария исцеления», усиливается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 30,
			name: "Мелодия воскрешения",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 5 сек.</span>\n<span class='left'>Восстановление</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Расстояние атаки – 16 м.</span>\n\nВоскрешает цель. После воскрешения у цели восстанавливается <span class='tooltip-value'>#%</span> ОЗ и ОМ. Каждый аккорд «C» увеличивает дальность применения навыка на 20%. Каждый аккорд «D» сокращает затраты на 20%. Каждый аккорд «E» сокращает время перезарядки навыка «Мелодия воскрешения» на 5 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [1250, 1531],
			rankInfo3: [15, 30],
		},
		{
			index: 31,
			name: "Божественный купол",
			ranks: 2,
			desc: "Всем массовым нелечебным мелодиям добавляется эффект восстановления <span class='tooltip-value'>#%</span> ОЗ цели.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Всем массовым нелечебным мелодиям добавляется эффект восстановления <span class="tooltip-value">15%</span> ОЗ цели.</div>'],
		},
		{
			index: 33,
			name: "Мелодия ангельского света",
			ranks: 1,
			desc: "<span class='left'>1000 ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 10 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nУменьшает атаку персонажа и мастерство света на 25%, на 25% увеличивает сопротивление всем стихиям от мастерства света. Увеличивает объем навыков исцеления «Соната жизни», «Ария исцеления», «Ария света» на 25% от силы атаки. Сокращает время перезарядки навыка «Ария исцеления» на 2 сек. При повторном использовании навыка действие прекращается.",
			rankInfo: [],
		},
		{
			index: 35,
			name: "Пробуждение жизни",
			ranks: 3,
			desc: "Дает <span class='tooltip-value'>#%</span> вероятности полной перезарядки навыков «Соната жизни» и «Ария света» в момент срабатывания любой из арий.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 36,
			name: "Лезвие света",
			ranks: 3,
			desc: "Повышает уклонение на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 38,
			name: "Изысканная мелодия воскрешения",
			ranks: 2,
			desc: "Повышает восстанавливаемое после воскрешения союзника посредством навыка «Мелодия воскрешения» количество ОЗ и ОМ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
			parent: 21,
		},
		{
			index: 39,
			name: "Оглушительный аккорд",
			ranks: 3,
			desc: "«Аккорды света», «Музыка света» и «Фантазия следов света» теперь могут понизить значение уклонения цели на <span class='tooltip-value'>#</span> очков и значение защиты на <span class='tooltip-value'>#%</span>. Длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [8, 16, 24],
			rankInfo2: [4, 7, 10],
			rankInfo3: [9, 12, 15],
		},
		{
			index: 41,
			name: "Музыка священного исцеления",
			ranks: 3,
			desc: "Вероятность двойного исцеления навыками «Соната жизни», «Ария света» и «Ария исцеления» увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 43,
			name: "Яркий блеск",
			ranks: 2,
			desc: "Дополнительный урон навыков «Аккорды света», «Музыка света» и «Фантазия света» увеличивается на <span class='tooltip-value'>#%</span>. Время перезарядки уменьшается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [15, 30],
			rankInfo2: [0.5, 1],
		},
		{
			index: 46,
			name: "Фантазия света",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>736 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 8 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 14 м.</span>\n\nНаносит 130% базового урона и дополнительно 5124 ед. урона. Добавляет аккорд «Е». Восстанавливает 5% от макс. ОЗ. Вызывает состояние «Иллюзии жизни», эффективность произ водимого лечения увеличивается на 15%. Длительность - 10 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Потеря зрения",
			ranks: 4,
			desc: "«Фантазия света» снижает меткость цели на <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60, 80],
			parent: 30,
		},
		{
			index: 49,
			name: "Военная песня",
			ranks: 2,
			desc: "Увеличивает крит. защиту на <span class='tooltip-value'>#%</span>.",
			rankInfo: [7, 14],
		},
		{
			index: 51,
			name: "Несбыточная мечта",
			ranks: 3,
			desc: "«Пьеса: Грезы» увеличивает крит. защиту цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 54,
			name: "Ария",
			ranks: 1,
			desc: "Уменьшает время чтения заклинания «Фантазия света» на 50% и ставитна цель одно клеймо света; продолжительность - 10 сек. Если цель с клеймом будет атакована, атакующий восстанавливает 5% от максимального запаса ОЗ; эффект суммируется до 10 раз.",
			rankInfo: [],
			parent: 30,
		},
	]
];