var data = [
	// one
	[
		{
			index: 1,
			name: "Zéfiro",
			ranks: 5,
			ranksnw: 1,
			desc: "Aumenta a Precisão do Acorde do Vento, Rapsódia do Vento e Réquiem em <span class='tooltip-value'>#</span>.",
			rankInfo: [9, 18, 27, 36, 45],
		},
		{
			index: 3,
			name: "Enfurecer",
			ranks: 5,
			desc: "Aumenta o bônus de Ataque concedido por Movimento: Coragem em <span class='tooltip-value'>#</span> por acumulação.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [3, 6, 9, 12, 15],
		},
		{
			index: 5,
			name: "Conhecimento da Melodia do Vento",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduz os intervalos do Acorde do Vento, Rapsódia do Vento e Réquiem em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [0.5, 1, 1.5, 2],
			parent: [0],
		},
		{
			index: 6,
			name: "Vento Desafinado",
			ranks: 3,
			desc: "Reduz o intervalo do Som Desafinado em <span class='tooltip-value'>#</span> segundo(s). O Som Desafinado reduz a Resistência de Vento do alvo em <span class='tooltip-value'>#</span> mais 5 por nível do Som Desafinado durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
		},
		{
			index: 7,
			name: "Arte da Música",
			ranks: 2,
			desc: "Aumenta o alcance de todos os Movimentos e Hinos em <span class='tooltip-value'>#</span> metro(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4],
		},
		{
			index: 8,
			name: "Alongamento Acústico",
			ranks: 3,
			desc: "Incrementa la duración de tus Movimientos y de los Acordes en Do <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 10,
			name: "Solo do Vento",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nGera 2 Acordes C que fornecem os mesmos efeitos que aqueles gerados pelo Acorde do Vento.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [230, 327, 425, 524],
			rankInfo3: [30, 27, 24, 21],
		},
		{
			index: 11,
			name: "Melodia Rápida",
			ranks: 3,
			desc: "Cada Acorde C ativo aumenta a sua velocidade de movimento em <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 12,
			name: "Balanço Suave",
			ranks: 4,
			desc: "Aumenta o efeito de Movimento: Coragem, Movimento: Fantasia, Hino: Batismo, Hino: Majestade e Hino: A Canção da Vida sobre integrantes do grupo em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 13,
			name: "Sombra do Vento",
			ranks: 3,
			ranksnw: 1,
			desc: "Aumenta a Chance Crítica do Acorde do Vento, Réquiem e Rapsódia do Vento em <span class='tooltip-value'>#%</span>. Elas reduzem a Defesa do alvo em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [0.5, 1, 1.5],
			rankInfo3: [25, 50, 75],
			rankInfo4: [10, 12, 14],
			parent: 2,
		},
		{
			index: 15,
			name: "Música Divina do Vento",
			ranks: 3,
			desc: "Aumenta a duração do efeito de adormecimento da Divina Comédia em <span class='tooltip-value'>#</span> segundo(s). A Divina Comédia aumenta a sua Evasão em <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			rankInfo3: [13, 14, 15],
		},
		{
			index: 16,
			name: "Melodia do Vento",
			ranks: 4,
			desc: "Aumenta a sua Maestria em Vento em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Tempestade de Areia",
			ranks: 2,
			desc: "Acorde do Vento, Rapsódia do Vento e Réquiem reduzem a efetividade de habilidades de cura lançadas sobre o alvo em <span class='tooltip-value'>#%</span> durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [15, 30],
			rankInfo2: [10, 15],
			parent: 9,
		},
		{
			index: 18,
			name: "Solo do Vento Avançado",
			ranks: 3,
			desc: "Reduz o intervalo do Solo do Vento em 10 segundos. O Solo do Vento desencadeia o efeito Proteção do Vento, o que Reduz o dano futuro em <span class='tooltip-value'>#%</span> durante 10 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [4, 7, 10],
			parent: 6,
		},
		{
			index: 19,
			name: "Manobra do Vento",
			ranks: 2,
			desc: "A Canção do Vento concede imunidade aos alvos afetados pelos efeitos de retardamento.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [],
			rankInfo2: [],
		},
		{
			index: 22,
			name: "Ritmo do Vento",
			ranks: 2,
			desc: "Reduz o intervalo da Nota de Descanso em <span class='tooltip-value'>#</span> segundo(s). Aumenta o dano base do Acorde do Vento, Rapsódia do Vento e Réquiem em <span class='tooltip-value'>#%</span> enquanto a Nota de Descanso estiver ativa.",
			rankInfo: [10, 15],
			rankInfo2: [8, 16],
		},
		{
			index: 24,
			name: "Resistência de Vento",
			ranks: 4,
			desc: "Aumenta a sua Resistência de Vento em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 25,
			name: "Acorde do Vento Melhorado",
			ranks: 3,
			desc: "Um Acorde C ativo aumenta o dano base do Acorde do Vento, Rapsódia do Vento e Réquiem em <span class='tooltip-value'>#%</span>. Este efeito não se acumula com múltiplos Acordes C.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Movimento: Canção do Vento",
			ranks: 2,
			desc: "<span class='tooltip-value'>#</span>Gerado quando você completa uma combinação de Acordes CCC e toca a Nota de Descanso. Aumenta a velocidade de movimento dos integrantes do grupo em um raio de 16 metro (s) em 170% durante <span class='tooltip-value'>#</span> segundo (s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 50</span>\n\n', '<span class="req">Requer que o personagem seja nível 65</span>\n\n'],
			rankInfo2: [10, 12],
		},
		{
			index: 28,
			name: "Ferocidade do Vento",
			ranks: 2,
			desc: "As suas habilidades de Movimento aumentam a Precisão de todos os integrantes do grupo em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 25],
		},
		{
			index: 29,
			name: "Rapsódia do Vento Avançada",
			ranks: 2,
			desc: "Reduz o intervalo da Rapsódia do Vento em <span class='tooltip-value'>#</span> segundo(s). Aumenta o dano base do Acorde do Vento em <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 30,
			name: "Voz da Liberdade",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Bênção para múltiplos alvos</span><span class='right'>Alcance: Nenhum</span>\n\nRemove todos os efeitos de retardamento e enredamento de integrantes do grupo em um raio de 16 metro(s). Pode ser usada quando estiver atordoado ou silenciado.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [345, 414],
			rankInfo3: [90, 60],
		},
		{
			index: 31,
			name: "Velocidade do Vento",
			ranks: 2,
			desc: "Aumenta o bônus da velocidade de movimento da Canção do Vento em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
		},
		{
			index: 35,
			name: "Movimento da Tempestade de Vento",
			ranks: 2,
			desc: "Suas habilidades de Movimento aumentam a sua Chance Crítica e Esquiva Crítica dos integrantes do grupo em <span class='tooltip-value'>#%</span> e <span class='tooltip-value'>#%</span> respectivamente, e têm <span class='tooltip-value'>#%</span> de chance de restaurar 25% do Mana Máximo dos integrantes do grupo a cada 4 segundos. Movimento: Canção do Vento tem 20% de chance de restaurar Mana a cada segundo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [0.5, 1],
			rankInfo2: [1, 2],
			rankInfo3: [0.5, 1],
		},
		{
			index: 36,
			name: "Escudo da Lâmina de Vento",
			ranks: 3,
			desc: "Reduz o dano futuro em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
		},
		{
			index: 38,
			name: "Voz da Liberdade Avançada",
			ranks: 2,
			desc: "Voz da Liberdade elimina efeitos de adormecimento. Reduz o intervalo da Liberdade do Vento em <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20],
			parent: 21,
		},
		{
			index: 39,
			name: "Inspiração",
			ranks: 3,
			desc: "Cada pilha do Movimento: A Coragem aumenta o Ataque dos integrantes do grupo afetado em <span class='tooltip-value'>#%</span> do seu Ataque.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [0.6, 1.2, 1.8],
		},
		{
			index: 41,
			name: "Notas do Vento",
			ranks: 2,
			desc: "Aumenta o dano base do Acorde do Vento, Rapsódia do Vento, Tempestade Gélida e Réquiem em <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
		},
		{
			index: 42,
			name: "Inspiração do Vento",
			ranks: 3,
			desc: "Reduz os intervalos do Solo do Vento, Voz da Liberdade, Réquiem e Tempestade Gélida em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 46,
			name: "Réquiem",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>491 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de vento</span><span class='right'>Intervalo: 6 segundo(s)</span>\n<span class='left'>Ataque contra múltiplos alvos</span><span class='right'>Alcance: 14 metro(s)</span>\n\nInflige 100% do seu Ataque básico mais 1495 de bônus de dano em até 15 alvos a no máximo 10 metros de distância. Gera um Acorde C.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// two
	[
		{
			index: 1,
			name: "Acorde dos Pingos de Chuva Avançado",
			ranks: 5,
			desc: "Aumenta o dano base do Acorde da Água em <span class='tooltip-value'>#%</span> mais <span class='tooltip-value'>#%</span> da sua Maestria em Água.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [20, 40, 60, 80, 100],
		},
		{
			index: 3,
			name: "Ondulação da Onda",
			ranks: 5,
			desc: "Aumenta o bônus de Ataque concedido por Melodia: Surto em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [30, 60, 90, 120, 150],
		},
		{
			index: 5,
			name: "Maestria em Ondulação",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduz os intervalos do Acorde da Água e Rapsódia da Água, além de Sonata Congelada em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [0.5, 1, 1.5, 2],
		},
		{
			index: 6,
			name: "Água Desafinada",
			ranks: 3,
			desc: "Aumenta a Chance Crítica do Som Desafinado em <span class='tooltip-value'>#%</span>. O Som Desafinado reduz a Resistência Aquática do alvo em <span class='tooltip-value'>#</span> mais 5 por nível do Som Desafinado durante <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
		},
		{
			index: 7,
			name: "Selo de Gelo",
			ranks: 3,
			desc: "Melodia: Vento do Gelo reduz a velocidade de movimento do alvo em um adicional de <span class='tooltip-value'>#%</span>. Nível 3 aumenta a duração do efeito congelante em 1 segundo.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 8,
			name: "Melodia Persistente",
			ranks: 3,
			desc: "Aumenta a duração das Arias e dos Acordes D em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 9,
			name: "Gelo Irregular",
			ranks: 3,
			desc: "Acorde da Água, Rapsódia da Água e Sonata Congelada reduzem o Mana do alvo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
			parent: 2,
		},
		{
			index: 10,
			name: "Sonata da Água",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Defesa</span><span class='right'>Intervalo: <span class='tooltip-value'>#</span> segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nDesencadeia o efeito de Aria de Égide, o que impede que você fique atordoado ou silenciado e reduz o dano futuro em <span class='tooltip-value'>#%</span>. Restaura <span class='tooltip-value'>#%</span> do seu Mana Máximo sempre que você é atingido. Este efeito pode ocorrer até 6 vezes. A duração aumenta para <span class='tooltip-value'>#</span> segundo(s) enquanto 2 Acordes D estiverem ativos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [268, 381, 496, 612],
			rankInfo3: [40, 35, 30, 25],
			rankInfo4: [5, 7, 9, 11],
			rankInfo5: [12, 14, 16, 18],
		},
		{
			index: 12,
			name: "Código da Mágica",
			ranks: 3,
			desc: "Reduz o custo de Mana das suas habilidades de ataque em <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 13,
			name: "Aparência Inspirada",
			ranks: 3,
			desc: "Cada Acorde D aumenta a sua Defesa em <span class='tooltip-value'>#%</span> e Evasão em <span class='tooltip-value'>#</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2, 3],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 15,
			name: "Música da Água",
			ranks: 1,
			desc: "Os alvos da Divina Comédia são atingidos com o efeito da Punição Divina. Quando um alvo afetado é atacado por uma das habilidades dentro de 20 segundos, o alvo é congelado durante 3 segundos. O estado congelado termina se o alvo for atingido 3 vezes.",
			rankInfo: [],
		},
		{
			index: 16,
			name: "Maestria em Melodia",
			ranks: 4,
			desc: "Aumenta a sua Maestria em Água em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 18,
			name: "Solo da Fluência Avançado",
			ranks: 3,
			desc: "Reduz o intervalo da Sonata da Água em <span class='tooltip-value'>#</span> segundo(s) e aumenta a duração em <span class='tooltip-value'>#</span> segundo(s). Restaura uma quantidade de Saúde equivalente a <span class='tooltip-value'>#%</span> da sua Saúde Máxima quando atingido enquanto Aria de Égide está ativa.",
			rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			rankInfo3: [2, 4, 6],
			parent: 7,
		},
		{
			index: 19,
			name: "Chantre do Vento",
			ranks: 3,
			desc: "Aumenta a duração da Canção do Vento em <span class='tooltip-value'>#</span> segundo(s). O intervalo da Canção do Vento também é reduzido em <span class='tooltip-value'>#</span> segundos para todos os pontos colocados nesse Talento.",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 20,
			name: "Resistir",
			ranks: 2,
			desc: "Aumenta a sua Esquiva Crítica em <span class='tooltip-value'>#%</span> enquanto uma habilidade de Melodia está ativa.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
		},
		{
			index: 22,
			name: "Maestria em Água Ondulante",
			ranks: 2,
			desc: "Aumenta a Chance Crítica do Acorde da Água, Rapsódia da Água e Sonata Congelada em <span class='tooltip-value'>#%</span>, e o Dano Crítico em <span class='tooltip-value'>#%</span> enquanto a Nota de Descanso estiver ativa. Aumenta a duração do efeito congelante da Sonata Congelante em <span class='tooltip-value'>#</span> segundo para cada ponto desse talento.",
			rankInfo: [2, 4],
			rankInfo2: [5, 10],
			rankInfo3: [1, 2],
		},
		{
			index: 24,
			name: "Fluxo Dividido",
			ranks: 4,
			desc: "Aumenta a sua Resistência Aquática em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 25,
			name: "Acorde da Água Melhorado",
			ranks: 3,
			desc: "Um Acorde D ativo aumenta o dano base do Acorde da Água, Rapsódia da Água e Sonata Congelada em <span class='tooltip-value'>#%</span>. Este efeito não se acumula com Acordes D adicionais.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Melodia: Canção da Água",
			ranks: 2,
			ranksnw: 1,
			desc: "Gerado quando você completa uma combinação de Acordes DDD e toca a Nota de Descanso. Dura <span class='tooltip-value'>#</span> segundo(s). Aumenta o seu Ataque base em <span class='tooltip-value'>#%</span> para cada Acorde D subsequente que você gerar. Acumula 5 vezes. Cada acumulação reinicia a duração de 10 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 50</span>\n\n', '<span class="req">Requer que o personagem seja nível 65</span>\n\n'],
			rankInfo2: [15, 17],
			rankInfo3: [5, 6],
		},
		{
			index: 27,
			name: "Acuidade",
			ranks: 2,
			desc: "Aumenta o bônus de Ataque concedido por Melodia: Canção da Água em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
			parent: 18,
		},
		{
			index: 29,
			name: "Quebra de Gelo",
			ranks: 3,
			desc: "Você terá <span class='tooltip-value'>#%</span> de chance de reiniciar os intervalos do Acorde da Água e Rapsódia da Água quando ativar uma habilidade de Melodia.",
			rankInfo: [30, 60, 100],
		},
		{
			index: 30,
			name: "Jogo Triplo",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>295 Mana</span><span class='right'>Tempo de ativação: 1.50 segundo(s)</span>\n<span class='left'>Ataque</span><span class='right'>Intervalo: 90 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nReduz os intervalos de suas habilidades ofensivas de Água em 60%. Aumenta os intervalos de habilidades de ataque de Vento e Luz em 60%. Aumenta a Chance Crítica das habilidades ofensivas de Água em 4% por 15 segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n'],
		},
		{
			index: 31,
			name: "Harmônicos da Água",
			ranks: 1,
			ranksnw: 1,
			desc: "Aumenta a duração do Jogo Triplo em 6 segundo(s). Aumenta o alcance das habilidades de Água em 3 metro(s) enquanto o Jogo Triplo estiver ativo.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [],
			parent: 21,
		},
		{
			index: 33,
			name: "Rapsódia da Água Avançada",
			ranks: 3,
			desc: "A Rapsódia da Água consome o Mana do alvo e causa dano equivalente à quantidade consumida, mais <span class='tooltip-value'>#</span>. Reduz o intervalo da Rapsódia da Água em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [100, 200, 300],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 36,
			name: "Impulso da Lâmina de Gelo",
			ranks: 3,
			desc: "Aumenta o seu Ataque em <span class='tooltip-value'>#</span>.",
			rankInfo: [30, 60, 90],
		},
		{
			index: 38,
			name: "Jogo Triplo Avançado",
			ranks: 3,
			desc: "O Jogo Triplo aumenta a Chance Crítica de suas habilidades da Água em <span class='tooltip-value'>#%</span>. No Nível 3 reduz os seus intervalos em 20% e reduz o intervalo do Jogo Triplo em 10 segundos.",
			rankInfo: [1, 2, 3],
			parent: 21,
		},
		{
			index: 39,
			name: "Rimas da Aqua",
			ranks: 2,
			desc: "A Rapsódia da Água e a Sonata Congelada reduzem o Ataque dos alvos em <span class='tooltip-value'>#%</span> e a sua Precisão em <span class='tooltip-value'>#</span> durante 10 segundos enquanto estiver sob o efeito da Aria: Surto estiver ativa.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10],
			rankInfo2: [15, 30],
		},
		{
			index: 42,
			name: "Reflexão",
			ranks: 3,
			desc: "Enquanto Sonata da Água estiver ativa, inflige o estado Devagar a qualquer alvo que lhe atacar, reduzindo as suas velocidades de movimento em <span class='tooltip-value'>#%</span> por <span class='tooltip-value'>#</span> segundo(s). Eles ficam enredados enquanto a Aria de Égide estiver ativa.",
			rankInfo: [30, 40, 50],
			rankInfo2: [5, 6, 7],
		},
		{
			index: 43,
			name: "Pulso da Lâmina de Água",
			ranks: 2,
			desc: "Aumenta a dano bônus do Acorde da Água, Rapsódia da Água e Sonata Congelada em <span class='tooltip-value'>#%</span>. Tempestade Gélida tem <span class='tooltip-value'>#%</span> de chance de interromper o lançamento do alvo.",
			rankInfo: [10, 20],
			rankInfo2: [50, 100],
		},
		{
			index: 46,
			name: "Sonata Congelada",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>425 Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Dano de água</span><span class='right'>Intervalo: 5 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 14 metro(s)</span>\n\nInflige 100% do seu Ataque básico mais 2217 de bônus de dano. Gera um Acorde D. Tem uma chance de 25% de congelar o alvo durante 2 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	],
		// three
	[
		{
			index: 1,
			name: "Harmonia da Luz Avançada",
			ranks: 5,
			desc: "Aumenta o dano base do Acorde da Luz em <span class='tooltip-value'>#%</span> e o bônus de dano em <span class='tooltip-value'>#%</span> da sua Maestria em Luz.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [20, 40, 60, 80, 100],
		},
		{
			index: 2,
			name: "Bênçãos da Luz",
			ranks: 5,
			desc: "Restaura <span class='tooltip-value'>#</span> da sua Saúde quando você gera um Acorde E.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [40, 80, 120, 160, 200],
		},
		{
			index: 5,
			name: "Brilhar",
			ranks: 3,
			desc: "Acorde da Luz, Sonata de Luz e Concerto da Vida reduzem a Precisão dos seus alvos em <span class='tooltip-value'>#</span> durante <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [12, 16, 20],
			rankInfo2: [6, 8, 10],
		},
		{
			index: 6,
			name: "Luz Desafinada",
			ranks: 3,
			desc: "Aumenta o dano base do Som Desafinado em <span class='tooltip-value'>#%</span>. O Som Desafinado reduz a Resistência de Luz do alvo em <span class='tooltip-value'>#</span> mais 5 por nível do Som Desafinado durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 20, 30],
			rankInfo3: [10, 20, 30],
		},
		{
			index: 7,
			name: "Música Divina da Luz",
			ranks: 3,
			desc: "Divina Comédia reduz a Defesa dos inimigos próximos em <span class='tooltip-value'>#%</span> e sua Precisão em <span class='tooltip-value'>#</span> durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 13, 18],
			rankInfo2: [20, 30, 50],
			rankInfo3: [11, 13, 15],
		},
		{
			index: 8,
			name: "Melodia Sustentada",
			ranks: 3,
			desc: "Aumenta a duração dos Hinos e dos Acordes E em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 9,
			name: "Encarar",
			ranks: 3,
			desc: "Reduz a chance de sofrer uma interrupção durante o lançamento de bênçãos e maldições em <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 30, 50],
		},
		{
			index: 10,
			name: "Solo da Luz",
			ranks: 4,
			ranksnw: 1,	
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 1 segundo(s)</span>\n<span class='left'>Curar</span><span class='right'>Intervalo: 15 segundo(s)</span>\n<span class='left'>Autobênção</span><span class='right'>Alcance: Nenhum</span>\n\nRestaura <span class='tooltip-value'>#</span> de sua Saúde enquanto os Acordes E 0/1/2/3 estiverem ativos. Tem uma Chance Crítica de 2%, o que faz com que esta habilidade cure o dobro da quantidade. Desencadeia o efeito Batida Suave, o que aumenta a quantidade de Saúde restaurada por suas habilidades de cura em 20% por 10 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 30</span>\n\n', '<span class="req">Requer que o personagem seja nível 45</span>\n\n', '<span class="req">Requer que o personagem seja nível 60</span>\n\n', '<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
			rankInfo2: [201, 305, 410, 516],
			rankInfo3: ['1272-1404/1462-1615/1653-1825/1844-2036', '1881-2078/2164-2389/2446-2701/2728-3013', '2461-2717/2830-3125/3199-3533/3569-3941', '3010-3324/3462-3822/3913-4321/4365-4820'],
		},
		{
			index: 12,
			name: "Auréola",
			ranks: 3,
			desc: "Aumenta o alcance de todas as bênçãos e maldições do grupo em <span class='tooltip-value'>#</span> metro(s).\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 4, 6],
		},
		{
			index: 13,
			name: "Chuveiro Divino",
			ranks: 3,
			desc: "Hino: A Majestade aumenta a sua Defesa em <span class='tooltip-value'>#%</span> e a Defesa dos integrantes do grupo afetado em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [3, 6, 9],
		},
		{
			index: 15,
			name: "Luz da Vida",
			ranks: 3,
			desc: "Reduz o intervalo da Sonata da Vida em <span class='tooltip-value'>#</span> segundo(s). Você tem <span class='tooltip-value'>#%</span> de chance de remover os efeitos Devagar, Enredar, Atordoar, Sangramento e efeitos de queimadura do alvo. A chance de remover os efeitos em alvos em um raio de 8 metros é dobrada.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [2, 3, 4],
			rankInfo2: [15, 25, 35],
		},
		{
			index: 16,
			name: "Melodia da Luz",
			ranks: 4,
			desc: "Aumenta a sua Maestria em Luz em <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Coro Angelical",
			ranks: 2,
			desc: "Concede às suas habilidades de cura <span class='tooltip-value'>#%</span> de chance de acionar o efeito do Coro Angelical durante 10 segundos. O Coro Angelical reduz os intervalos e custos de Mana das suas habilidades de cura em 50%.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [15, 30],
		},
		{
			index: 18,
			name: "Solo da Luz Avançado",
			ranks: 3,
			desc: "Aumenta a quantidade de Saúde restaurada pelo Solo de Luz em <span class='tooltip-value'>#%</span> e reduz seu intervalo em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 7,
		},
		{
			index: 19,
			name: "Melodia da Cura",
			ranks: 3,
			desc: "Cada Acorde E ativo aumenta a efetividade de habilidades de cura lançadas sobre você em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10, 15],
		},
		{
			index: 22,
			name: "Notas da Luz",
			ranks: 2,
			desc: "Reduz o intervalo do Acorde da Luz, Sonata da Luz e Concerto da Vida em <span class='tooltip-value'>#</span> segundo(s). Quando a Nota de Descanso está ativa, danos futuros restauram <span class='tooltip-value'>#%</span> da sua Saúde Máxima. Este efeito aciona até 10 vezes.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [1, 2],
			rankInfo2: [3, 5],
		},
		{
			index: 24,
			name: "Resistência da Auréola",
			ranks: 4,
			desc: "Aumenta a sua Resistência de Luz em <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 25,
			name: "Acorde da Luz Melhorado",
			ranks: 3,
			desc: "Um Acorde E ativo aumenta o dano base do Acorde da Luz, Sonata de Luz e Concerto da Vida em <span class='tooltip-value'>#%</span>. Este efeito não se acumula com Acordes E adicionais.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Hino: Canção da Vida",
			ranks: 2,
			ranksnw: 1,
			desc: "Ativado quando você completa uma combinação de Acordes EEE e toca a Nota de Descanso. Restaura 16% da Saúde Máxima de todos os integrantes do grupo em um raio de <span class='tooltip-value'>#</span> metro(s) e remove todos os efeitos negativos. Aumenta a Saúde Máxima dos integrantes do grupo em <span class='tooltip-value'>#%</span> durante 10 segundos.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 50</span>\n\n', '<span class="req">Requer que o personagem seja nível 65</span>\n\n'],
			rankInfo2: [20, 25],
			rankInfo3: [10, 15],
		},
		{
			index: 27,
			name: "Canção dos Santos",
			ranks: 2,
			desc: "Hino: Canção da Vida aumenta a efetividade das habilidades de cura lançadas em alvos afetados em <span class='tooltip-value'>#%</span> da sua Saúde Máxima. Aumenta sua velocidade de movimento e Evasão em <span class='tooltip-value'>#%</span> e <span class='tooltip-value'>#</span> respectivamente por 6 segundos.",
			rankInfo: [5, 10],
			rankInfo2: [15, 30],
			rankInfo3: [15, 30],
			parent: 18,
		},
		{
			index: 29,
			name: "Banho de Luz",
			ranks: 2,
			desc: "Aumenta a quantidade de Saúde restaurada pelo Hino: Batismo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 30,
			name: "Chantre da Nova Vida",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Tempo de ativação: 5 segundo(s)</span>\n<span class='left'>Reviver</span><span class='right'>Intervalo: 15 segundo(s)</span>\n<span class='left'>Bênção para alvo único</span><span class='right'>Alcance: 16 metro(s)</span>\n\nRevive o alvo e restaura <span class='tooltip-value'>#%</span> da sua Saúde e Mana. Cada Acorde C aumenta o alcance em 20%. Cada Acorde D ativo reduz o custo de Mana em 20%. Cada Acorde E ativo reduz o intervalo em 5 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 55</span>\n\n', '<span class="req">Requer que o personagem seja nível 70</span>\n\n'],
			rankInfo2: [1250, 1531],
			rankInfo3: [15, 30],
		},
		{
			index: 31,
			name: "Melodia Suavizante",
			ranks: 2,
			desc: "Aumenta a efetividade das habilidades de cura em todos os alvos afetados pelas Arias, Movimentos e Hinos em <span class='tooltip-value'>#%</span>.\n\n<b>Você pode aumentar o nível de talento usando runas.</b>",
			rankInfo: [5, 10],
		},
		{
			index: 35,
			name: "Despertar da Vida",
			ranks: 3,
			desc: "Você terá <span class='tooltip-value'>#%</span> de chance de reiniciar os intervalos do Sonata da Vida e Solo de Luz quando ativar a habilidade Hino.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 36,
			name: "Troca da Lâmina de Luz",
			ranks: 3,
			desc: "Aumenta a sua Evasão em <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 38,
			name: "Chantre da Nova Vida Avançado",
			ranks: 2,
			desc: "Chantre da Nova Vida restaura um adicional de <span class='tooltip-value'>#%</span> da Saúde e Mana do alvo.",
			rankInfo: [15, 30],
			parent: 21,
		},
		{
			index: 39,
			name: "Crescendo",
			ranks: 3,
			desc: "Acorde da Luz, Sonata de Luz e Concerto da Vida reduzem a Evasão do alvo em <span class='tooltip-value'>#</span> e Defesa em <span class='tooltip-value'>#%</span> durante <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [8, 16, 24],
			rankInfo2: [4, 7, 10],
			rankInfo3: [9, 12, 15],
		},
		{
			index: 41,
			name: "Melodia Curativa",
			ranks: 3,
			desc: "Aumenta a Chance Crítica da Sonata da Vida, Solo de Luz e Hino: Batismo em <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 43,
			name: "Brilho",
			ranks: 2,
			desc: "Aumenta os bônus de dano do Acorde da Luz, Voz da Luz e Concerto da Vida em <span class='tooltip-value'>#%</span>. Reduz o intervalo em <span class='tooltip-value'>#</span> segundo(s).",
			rankInfo: [15, 30],
			rankInfo2: [0.5, 1],
		},
		{
			index: 46,
			name: "Concerto da Vida",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>736 Mana</span><span class='right'>Tempo de ativação: 2 segundo(s)</span>\n<span class='left'>Dano de luz</span><span class='right'>Intervalo: 8 segundo(s)</span>\n<span class='left'>Ataque contra alvo único</span><span class='right'>Alcance: 14 metro(s)</span>\n\nInflige 90% do seu Ataque básico mais 6124 de bônus de dano. Gera um Acorde E. Restaura a Saúde em uma quantidade equivalente a 5% da sua Saúde atual. Ativa o efeito Enigma da Vida que aumenta a eficiência das habilidades de cura lançadas em você em 15% por 10 segundos.",
			rankInfo: ['<span class="req">Requer que o personagem seja nível 75</span>\n\n'],
		},
	]
];