var data = [
	// one
	[
		{
			index: 1,
			name: "Знак слабости",
			ranks: 5,
			ranksnw: 2,
			desc: "Увеличивает время действия эффекта «Охотничьей метки» на <span class='tooltip-value'>#</span> сек. Уменьшает защиту цели на <span class='tooltip-value'>#%</span> и <span class='tooltip-value'>#</span> очков.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: [60, 75, 90, 105, 120],
			rankInfo4: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивает время действия эффекта «Охотничьей метки» на <span class="tooltip-value">12</span> сек. Уменьшает защиту цели на <span class="tooltip-value">6%</span> и <span class="tooltip-value">135</span> очков.</div>'],
		},
		{
			index: 3,
			name: "Усиленная пуля",
			ranks: 5,
			ranksnw: 2,
			desc: "Дополнительный урон навыка «Стрельба» увеличивается на <span class='tooltip-value'>#%</span> + <span class='tooltip-value'>#%</span> от значения мастерства Земли.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Дополнительный урон навыка «Стрельба» увеличивается на <span class="tooltip-value">12%</span> + <span class="tooltip-value">60%</span> от значения мастерства Земли.</div>'],
		},
		{
			index: 6,
			name: "Быстрое обескураживание",
			ranks: 5,
			desc: "Уменьшает время перезарядки навыка «Выстрел ужаса» на <span class='tooltip-value'>#</span> сек. и увеличивает дополнительный урон навыка на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [2, 4, 6, 8, 10],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Уменьшает время перезарядки навыка «Выстрел ужаса» на <span class="tooltip-value">6</span> сек. и увеличивает дополнительный урон навыка на <span class="tooltip-value">12%</span>.</div>'],
		},
		{
			index: 8,
			name: "Огневая мощь",
			ranks: 5,
			desc: "Увеличивает мастерство Земли на <span class='tooltip-value'>#</span> и усиливает атаку с использованием навыков стихии земли на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 9,
			name: "Анализ свойств",
			ranks: 3,
			desc: "Охотничья метка дополнительно уменьшает сопротивление цели всем стихиям на <span class='tooltip-value'>#</span> и уменьшает уклонение цели на <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
			rankInfo2: [15, 30, 45],
			parent: [0],
		},
		{
			index: 10,
			name: "Меткий выстрел",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 22 м.</span>\n\nНаносит 100% базового урона и дополнительно <span class='tooltip-value'>#</span> ед. урона. Во время действия эффекта «Разрывные пули» попавшая в цель «Меткая пуля» вызывает кровотечение. В течение 10 секунд цели теряет <span class='tooltip-value'>#</span> ОЗ в секунду. Если эффект будет суммирован 3 раза, имеется вероятность 25%, что монстр будет отброшен на 4 метра. Если во время действия этого состояния персонаж осуществит «Меткий выстрел», он может потратить 1 «Меткую пулю», которая увеличит силу его атаки на 20% и удвоит эффект от кровотечения. Целю, на которую будет нанесена Охотничья метка, с вероятностью 100% отбрасывается на 4 метра.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [124, 185, 246, 309],
			rankInfo3: [1313, 2312, 3293, 4256],
			rankInfo4: [29, 46, 64, 81],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">373</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Урон от Земли</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – 22 м.</span>\n\n<br><br>Наносит 100% базового урона и дополнительно <span class="tooltip-value">5200</span> ед. урона. Во время действия эффекта «Разрывные пули» попавшая в цель «Меткая пуля» вызывает кровотечение. В течение 10 секунд цели теряет <span class="tooltip-value">98</span> ОЗ в секунду. Если эффект будет суммирован 3 раза, имеется вероятность 25%, что монстр будет отброшен на 4 метра. Если во время действия этого состояния персонаж осуществит «Меткий выстрел», он может потратить 1 «Меткую пулю», которая увеличит силу его атаки на 20% и удвоит эффект от кровотечения. Целю, на которую будет нанесена Охотничья метка, с вероятностью 100% отбрасывается на 4 метра.</div>'],
		},
		{
			index: 11,
			name: "Концентрация духа",
			ranks: 4,
			ranksnw: 2,
			desc: "При стрельбе в состоянии обескураживания расход уменьшается на <span class='tooltip-value'>#%</span>, а вероятность нанести крит. урон увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [2, 4, 6, 8],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>При стрельбе в состоянии обескураживания расход уменьшается на <span class="tooltip-value">75%</span>, а вероятность нанести крит. урон увеличивается на <span class="tooltip-value">10%</span>.</div>'],
			parent: 1,
		},
		{
			index: 14,
			name: "Точный прицел",
			ranks: 4,
			ranksnw: 2,
			desc: "Увеличивает вероятнотсь нанести крит. урон при использовании навыка «Меткий выстрел» на <span class='tooltip-value'>#%</span>, увеличивает меткость на 15, а вероятность отбросить противника - на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [15, 30, 45, 60],
			parent: 5,
		},
		{
			index: 16,
			name: "Укрепление",
			ranks: 4,
			desc: "Увеличивает защиту и сопротивление земле на <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Густое облако",
			ranks: 2,
			desc: "Усиливает эффект замедления, вызванный слабостью, на <span class='tooltip-value'>#%</span>, и уменьшает время перезарядки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Усиливает эффект замедления, вызванный слабостью, на <span class="tooltip-value">30%</span>, и уменьшает время перезарядки на <span class="tooltip-value">45</span> сек.</div>'],
		},
		{
			index: 18,
			name: "Сбор сил",
			ranks: 2,
			desc: "Дополнительный урон навыка «Меткий выстрел» увеличивается на <span class='tooltip-value'>#%</span>, кровоточение усиливается на <span class='tooltip-value'>#%</span>. С вероятностью 50% вызывает у цели головокружение на 3 сек.",
			rankInfo: [5, 10],
			rankInfo2: [50, 100],
			parent: 7,
		},
		{
			index: 19,
			name: "След пули",
			ranks: 4,
			ranksnw: 2,
			desc: "Стрельба уменьшает защиту цели на <span class='tooltip-value'>#</span> в течение 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Стрельба уменьшает защиту цели на <span class="tooltip-value">125</span> в течение 10 сек.</div>'],
			parent: 6,
		},
		{
			index: 21,
			name: "Дальнобойность",
			ranks: 2,
			desc: "При использовании «Ловчей сети» в состоянии «Скорость пуль» максимальная дистанция выстрела увеличивается на <span class='tooltip-value'>#</span> м., минимальная уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
		},
		{
			index: 24,
			name: "Энергия души",
			ranks: 3,
			ranksnw: 1,
			desc: "При получении меткой пули восстанавливается <span class='tooltip-value'>#%</span> максимального количества ОМ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При получении меткой пули восстанавливается <span class="tooltip-value">2.5%</span> максимального количества ОМ.</div>'],
		},
		{
			index: 25,
			name: "Снайпер",
			ranks: 2,
			ranksnw: 2,
			desc: "Навык «Жгучий выстрел» отбрасывает цели у которых ОЗ выше <span class='tooltip-value'>#%</span>. Меткость «Мощного выстрела» увеличивается на <span class='tooltip-value'>#</span>. После использования «Охотничей метки» в течение 10 сек. скорость применения «Мощного выстрела» увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 20],
			rankInfo2: [20, 40],
			rankInfo3: [50, 100],
			rankInfo4: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Навык «Жгучий выстрел» отбрасывает цели у которых ОЗ выше <span class="tooltip-value">10%</span>. Меткость «Мощного выстрела» увеличивается на <span class="tooltip-value">60</span>. После использования «Охотничей метки» в течение 10 сек. скорость применения «Мощного выстрела» увеличивается на <span class="tooltip-value">150%</span>.</div>'],
		},
		{
			index: 26,
			name: "Контакт",
			ranks: 3,
			desc: "Увеличивает вероятность нанести крит. урон при использовании навыка «Прицельный огонь» на <span class='tooltip-value'>#%</span>, увеличивает время действия навыка на <span class='tooltip-value'>#</span> мин.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает вероятность нанести крит. урон при использовании навыка «Прицельный огонь» на <span class="tooltip-value">2.5%</span>, увеличивает время действия навыка на <span class="tooltip-value">20</span> мин.</div>'],
		},
		{
			index: 27,
			name: "Залповый огонь",
			ranks: 3,
			desc: "При стрельбе существует <span class='tooltip-value'>#%</span>-ная вероятность обнулить время перезарядки атакующих навыков стихии Земли.",
			rankInfo: [4, 8, 12],
			parent: 11,
		},
		{
			index: 29,
			name: "Жестокий штурм",
			ranks: 1,
			desc: "Мощный выстрел вводит в кому животных и гуманоидов с уровнем здоровья 75% и выше на 30 сек. (на игроков действует в 1/3 от полной силы). Атакуемый персонаж восстанавливается.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 30,
			name: "Отважный настрой",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Кольцо благословения</span><span class='right'>Расстояние атаки – нет</span>\n\nУсиливает атаку всех членов отряда в области диаметром 16 м. на <span class='tooltip-value'>#%</span> от уровня их меткости. После активации ауры каждые 2 сек. расходуются ОМ в размере 0.30%.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [206, 254],
			rankInfo3: [50, 70],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">304</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Кольцо благословения</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Усиливает атаку всех членов отряда в области диаметром 16 м. на <span class="tooltip-value">90%</span> от уровня их меткости. После активации ауры каждые 2 сек. расходуются ОМ в размере 0.30%.</div>'],
		},
		{
			index: 32,
			name: "Передышка",
			ranks: 3,
			desc: "При получении меткой пули восстанавливается <span class='tooltip-value'>#%</span> максимального количества ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При получении меткой пули восстанавливается <span class="tooltip-value">2.5%</span> максимального количества ОЗ.</div>'],
			parent: 13,
		},
		{
			index: 33,
			name: "Разлом",
			ranks: 3,
			desc: "Навыки стихии Земли при атаке одиночных целей после критического удара уменьшают шанс ответного критического удара противника на <span class='tooltip-value'>#%</span> в течение 10 сек.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 35,
			name: "Командная охота",
			ranks: 3,
			desc: "Цель под знаком охотника получает <span class='tooltip-value'>#%</span> дополнительного урона.",
			rankInfo: [4, 6, 8],
		},
		{
			index: 37,
			name: "Окончательное изгнание",
			ranks: 3,
			desc: "При выстреле экзорциста сила атаки увеличивается на <span class='tooltip-value'>#%</span>, вероятность рассеивания состояния противника – на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 30, 40],
		},
		{
			index: 38,
			name: "Командующий",
			ranks: 2,
			desc: "Отважный настрой увеличивает силу атаки на <span class='tooltip-value'>#%</span> от показателя меткости и снижает расход на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30],
			rankInfo2: [20, 40],
			parent: 18,
		},
		{
			index: 42,
			name: "Земля смерти",
			ranks: 2,
			desc: "Навык «Многократная смерть» увеличивает мастерство Земли на <span class='tooltip-value'>#</span> ед., а шанс критического удара - на <span class='tooltip-value'>#%</span>. Каждая атака имеет <span class='tooltip-value'>#%</span> вероятность добавить меткую пулю вместо того, чтобы тратить ее.",
			rankInfo: [40, 80],
			rankInfo2: [4, 8],
			rankInfo3: [50, 100],
		},
		{
			index: 43,
			name: "Сила",
			ranks: 3,
			desc: "Увеличивает показатель атаки на <span class='tooltip-value'>#%</span> и дополнительно на <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [25, 50, 75],
		},
		{
			index: 46,
			name: "Ослабляющая атака",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>433 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Земля</span><span class='right'>Время перезарядки: 30 сек.</span>\n<span class='left'>Проклятие</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nОслабляет цель, уменьшая ее скорость передвижения на 75%, а мастерство всех стихий - на 80. Уменьшает критический урон, наносимый целью на 35%, продолжительность: 15 сек. Можно получить Меткую пулю.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Увечащий удар",
			ranks: 4,
			desc: "«Ослабляющая атака» дополнительно снижает базовую атаку цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [6, 9, 12, 15],
			parent: 26,
		},
		{
			index: 49,
			name: "Меткость",
			ranks: 3,
			desc: "Увеличивает меткость на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 51,
			name: "Бронебойность",
			ranks: 2,
			desc: "Навыки «Стрельба», «Ловчая сеть», «Меткий выстрел» и «Плотный огонь» снижают крит. уклонение цели на <span class='tooltip-value'>#%</span>, а крит. защиту – на <span class='tooltip-value'>#%</span>. Продолжительность – 5 сек.",
			rankInfo: [1, 2],
			rankInfo2: [2, 4],
		},
		{
			index: 54,
			name: "Меткость",
			ranks: 1,
			desc: "«Ослабляющая атака» может парализовать цель на 4 сек., к тому же в течение 15 сек. урон цели, наносимый навыками земли, увеличен на 20%.",
			rankInfo: [],
			parent: 26,
		},
	],
		// two
	[
		{
			index: 2,
			name: "Искусство заряжания",
			ranks: 5,
			desc: "Сокращает время скоростной зарядки на <span class='tooltip-value'>#</span> сек. и увеличивает восстановление ОМ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [6, 12, 18, 24, 30],
		},
		{
			index: 3,
			name: "Поглощение",
			ranks: 5,
			ranksnw: 2,
			desc: "Базовый урон навыка «Выстрел ужаса» увеличивается на <span class='tooltip-value'>#%</span>, длительность состояния обескураживания увеличивается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [4, 8, 12, 16, 20],
			rankInfo2: [2, 4, 6, 8, 10],
		},
		{
			index: 5,
			name: "Опытный охотник",
			ranks: 3,
			desc: "Охотничья метка дополнительно уменьшает уклонение цели на <span class='tooltip-value'>#</span> и увеличивает расстояние действия на <span class='tooltip-value'>#</span> м.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [3, 6, 9],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Охотничья метка дополнительно уменьшает уклонение цели на <span class="tooltip-value">20</span> и увеличивает расстояние действия на <span class="tooltip-value">12</span> м.</div>'],
		},
		{
			index: 8,
			name: "Стрельба без промаха",
			ranks: 5,
			desc: "Навык «Меткость» дополнительно увеличивает меткость персонажа на <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12, 16, 20],
		},
		{
			index: 9,
			name: "Плавное исчезновение",
			ranks: 3,
			desc: "Увеличивает время действия слабости на <span class='tooltip-value'>#</span> сек. и время действия охотничьей метки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает время действия слабости на <span class="tooltip-value">4</span> сек. и время действия охотничьей метки на <span class="tooltip-value">8</span> сек.</div>'],
		},
		{
			index: 10,
			name: "Выстрел ловца душ",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Огня</span><span class='right'>Время перезарядки: 10 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 22 м.</span>\n\nНаносит 100% базового урона и дополнительно <span class='tooltip-value'>#</span> ед. урона. Персонажу дается 1 меткая пуля, каждая меткая пуля повышает меткость на 1. Можно собрать не более 20 пуль. После активации состояния «Разрывные пули» на выстрел ловца душ меткие пули не тратятся, сила атаки увеличивается на 20%. Цель, находящаяся под воздействием «Охотничьей метки», теряет <span class='tooltip-value'>#%</span> ОМ и дополнительно <span class='tooltip-value'>#</span> ОМ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [126, 181, 238, 295],
			rankInfo3: [663, 1112, 1552, 1984],
			rankInfo4: [6, 8, 10, 12],
			rankInfo5: [150, 300, 400, 600],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">354</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Урон от Огня</span><span class="right">Время перезарядки: 10 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – 22 м.</span>\n\n<br><br>Наносит 100% базового урона и дополнительно <span class="tooltip-value">2407</span> ед. урона. Персонажу дается 1 меткая пуля, каждая меткая пуля повышает меткость на 1. Можно собрать не более 20 пуль. После активации состояния «Разрывные пули» на выстрел ловца душ меткие пули не тратятся, сила атаки увеличивается на 20%. Цель, находящаяся под воздействием «Охотничьей метки», теряет <span class="tooltip-value">14%</span> ОМ и дополнительно <span class="tooltip-value">750</span> ОМ.</div>'],
		},
		{
			index: 11,
			name: "Разлад души",
			ranks: 4,
			desc: "Вероятность возникновения состояния обескураживания при использовании выстрела ужаса увеличивается на <span class='tooltip-value'>#%</span>. Противнику с показателем ОЗ ниже 25% наносится дополнительный урон в размере <span class='tooltip-value'>#</span> очков.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [60, 120, 180, 240],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Вероятность возникновения состояния обескураживания при использовании выстрела ужаса увеличивается на <span class="tooltip-value">25%</span>. Противнику с показателем ОЗ ниже 25% наносится дополнительный урон в размере <span class="tooltip-value">300</span> очков.</div>'],
			parent: 1,
		},
		{
			index: 13,
			name: "Мгла",
			ranks: 3,
			desc: "Усиливает эффект «Слабости», уменьшающий точность на <span class='tooltip-value'>#%</span>. Продлевает эфффект невидимости на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [20, 40, 60],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 15,
			name: "Долговечность",
			ranks: 4,
			ranksnw: 2,
			desc: "Длительность эффекта ускорения возрастает на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Длительность эффекта ускорения возрастает на <span class="tooltip-value">7.5</span> сек.</div>'],
		},
		{
			index: 18,
			name: "Отделение души",
			ranks: 3,
			ranksnw: 2,
			desc: "Урон от базовой атаки при использовании выстрела ловца душ увеличивается на <span class='tooltip-value'>#%</span>, потеря ОМ цели под знаком увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [25, 50, 75],
			parent: 5,
		},
		{
			index: 19,
			name: "Избавление",
			ranks: 1,
			desc: "«Ускорение» с вероятностью 100% снимает замедление и паралич, наложенные на персонажа.",
			rankInfo: [],
			parent: 8,
		},
		{
			index: 20,
			name: "Астральный проводник",
			ranks: 3,
			desc: "В состоянии «Разрывные пули» вероятность нанести крит. урон при использовании навыков увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>В состоянии «Разрывные пули» вероятность нанести крит. урон при использовании навыков увеличивается на <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 21,
			name: "Сжигание духа",
			ranks: 3,
			ranksnw: 2,
			desc: "Урон навыка «Жгучий выстрел» увеличивается на <span class='tooltip-value'>#%</span>, шанс критического урона увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Урон навыка «Жгучий выстрел» увеличивается на <span class="tooltip-value">40%</span>, шанс критического урона увеличивается на <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 22,
			name: "Смятение",
			ranks: 2,
			desc: "Сокращает время перезарядки выстрела ловца душ на <span class='tooltip-value'>#</span> сек., уменьшает максимум ОМ цели под знаком на <span class='tooltip-value'>#%</span> от показателя потерянных ОМ. Длительность - <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4],
			rankInfo2: [50, 100],
			rankInfo3: [20, 30],
			parent: 9,
		},
		{
			index: 23,
			name: "Шальная пуля",
			ranks: 2,
			desc: "Если стрелок не находится в состоянии обескураживания, также существует <span class='tooltip-value'>#%</span>-ная вероятность получить меткую пулю. После активации состояния «Разрывные пули» время перезарядки сокращается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: [0.5, 1],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Если стрелок не находится в состоянии обескураживания, также существует <span class="tooltip-value">60%</span>-ная вероятность получить меткую пулю. После активации состояния «Разрывные пули» время перезарядки сокращается на <span class="tooltip-value">1.5</span> сек.</div>'],
		},
		{
			index: 26,
			name: "Застывание души",
			ranks: 2,
			desc: "При применение навыка «Ловчья сеть» к целям, находящимся по действием эффекта «Охотничья метка», время замедления увеличивается на <span class='tooltip-value'>#</span> сек., а эффект замедления усиливается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>При применение навыка «Ловчья сеть» к целям, находящимся по действием эффекта «Охотничья метка», время замедления увеличивается на <span class="tooltip-value">3</span> сек., а эффект замедления усиливается на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 27,
			name: "Средоточие духа",
			ranks: 4,
			desc: "Каждый раз при получении меткой пули при использовании навыка «Перезарядка» существует <span class='tooltip-value'>#%</span>-ная вероятность получить 1 меткую пулю. Вероятность прерывания навыка уменьшается на <span class='tooltip-value'>#%</span>. Время перезарядки навыка «Перезарядка» уменьшается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [25, 50, 75, 100],
			rankInfo3: [3, 7, 11, 15],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Каждый раз при получении меткой пули при использовании навыка «Перезарядка» существует <span class="tooltip-value">75%</span>-ная вероятность получить 1 меткую пулю. Вероятность прерывания навыка уменьшается на <span class="tooltip-value">125%</span>. Время перезарядки навыка «Перезарядка» уменьшается на <span class="tooltip-value">19</span> сек.</div>'],
		},
		{
			index: 29,
			name: "Взрыв души",
			ranks: 3,
			desc: "При использовании обжигающего удара сила атаки увеличивается на <span class='tooltip-value'>#%</span>. При критическом ударе существует вероятность <span class='tooltip-value'>#%</span> оглушить цель на 2 сек.",
			rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
			parent: 12,
		},
		{
			index: 30,
			name: "Гневная очередь",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Урон от Огня</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 22 м.</span>\n\nПроизводит 6 выстрелов подряд, наносящих 75% базового урона и увеличивающих силу атаки на <span class='tooltip-value'>#</span>. Для применения требуется не менее 1 меткой пули. Расходуется до 3 метких пуль. Если пуль меньше трех, все 6 атак провести не удастся, они будут прерваны. После активации состояния «Разрывные пули» существует 30% вероятность при каждом выстреле израсходовать 1 меткую пулю. При этом время перезарядки сокращается вдвое.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [517, 639],
			rankInfo3: [643, 1027],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">769</span> ОМ</span><span class="right">Чтение: 3 сек.</span>\n<br><span class="left">Урон от Огня</span><span class="right">Время перезарядки: 20 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – 22 м.</span>\n\n<br><br>Производит 6 выстрелов подряд, наносящих 75% базового урона и увеличивающих силу атаки на <span class="tooltip-value">1383</span>. Для применения требуется не менее 1 меткой пули. Расходуется до 3 метких пуль. Если пуль меньше трех, все 6 атак провести не удастся, они будут прерваны. После активации состояния «Разрывные пули» существует 30% вероятность при каждом выстреле израсходовать 1 меткую пулю. При этом время перезарядки сокращается вдвое.</div>'],
		},
		{
			index: 32,
			name: "Мастер артобстрела",
			ranks: 3,
			desc: "Урон от критического удара при использовании растущего пламени увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 33,
			name: "Притеснение",
			ranks: 3,
			desc: "В состоянии «Разрывные пули» сила атаки при сильнейшем ударе увеличивается на <span class='tooltip-value'>#%</span>. С вероятностью <span class='tooltip-value'>#%</span> уменьшает скорость цели на 50% в течение 4 сек.",
			rankInfo: [5, 10, 15],
			rankInfo2: [50, 70, 90],
		},
		{
			index: 35,
			name: "Остатки силы",
			ranks: 3,
			ranksnw: 1,
			desc: "При использовании разлома души поглощаемый урон увеличивается на <span class='tooltip-value'>#%</span>, расход уменьшается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При использовании разлома души поглощаемый урон увеличивается на <span class="tooltip-value">40%</span>, расход уменьшается на <span class="tooltip-value">80%</span>.</div>'],
		},
		{
			index: 37,
			name: "Магические путы",
			ranks: 3,
			desc: "увеличивает урон от навыка «Выстрел экзорциста» на <span class='tooltip-value'>#%</span>, заставляет цели, находившиеся под действием «Охотничьей метки», спешиться и накладывает на них эффект немоты на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Гнет",
			ranks: 3,
			desc: "На каждом этапе применения гневной очереди сила атаки увеличивается на <span class='tooltip-value'>#%</span>. В состоянии «Разрывные пули» базовый урон увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 18,
		},
		{
			index: 40,
			name: "Гномья удача",
			ranks: 2,
			desc: "Вероятность наложения эффектов от навыков по одиночным целям увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 42,
			name: "Помеха",
			ranks: 2,
			desc: "Скорость передвижения противника под меткой охотника снижается на <span class='tooltip-value'>#%</span>, эффект исцеления – на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 43,
			name: "Концентрация духа",
			ranks: 3,
			desc: "Время перезарядки «Разлома души» снижается на <span class='tooltip-value'>#</span> сек., время перезарядки «Многократной смерти» - на <span class='tooltip-value'>#</span> сек., время перезарядки «Быстрой зарядки» - на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 15, 20],
			rankInfo3: [10, 20, 30],
			parent: 21,
		},
		{
			index: 46,
			name: "Быстрая зарядка",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>463 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 120 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nВосстанавливает 5 пуль и сбрасывает время восстановления навыков «Разлом души» и «Многократная смерть». На 10 сек. дает имунитет к безмолвию, атакующие навыки Огня при активации не расходуют пули. Применение данного навыка не контролируется.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Полный патронташ",
			ranks: 4,
			ranksnw: 1,
			desc: "«Быстрая зарядка» с вероятностью <span class='tooltip-value'>#%</span> дает персонажу 3 пули.",
			rankInfo: [25, 50, 75, 100],
			parent: 27,
		},
		{
			index: 49,
			name: "Жаркое пламя",
			ranks: 3,
			desc: "Повышает шанс крит. удара от атакующих навыков стихии Огня на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 52,
			name: "Рука огня",
			ranks: 2,
			desc: "Во время действия эффекта «Многократная смерть» атакующие навыки стихии Огня поджигают цель. Наносит <span class='tooltip-value'>#</span> ед. урона в секунду и восстанавливает персонажу ОЗ в размере 30% от мастерства Огня; длительность-8 сек. В случае действия нескольких эффектов «Удар огня» они прекращают действовать поочередно.",
			rankInfo: [200, 400],
		},
		{
			index: 55,
			name: "Мастер оружия",
			ranks: 1,
			desc: "«Быстрая зарядка» уменьшает время восстановления на 30 сек. «Быстрая зарядка» может сбросить время восстановления навыка «Перезарядка».",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Раскаленная пуля",
			ranks: 5,
			ranksnw: 2,
			desc: "Сила атаки при использовании «Обжигающего удара» увеличивается на <span class='tooltip-value'>#%</span> и дополнительно на <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [45, 60, 75, 90, 105],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Сила атаки при использовании «Обжигающего удара» увеличивается на <span class="tooltip-value">12%</span> и дополнительно на <span class="tooltip-value">120</span>.</div>'],
		},
		{
			index: 2,
			name: "Стихийный обстрел",
			ranks: 5,
			ranksnw: 2,
			desc: "Сквозная рана с вероятностью <span class='tooltip-value'>#%</span> уменьшает сопротивление противника Земле и Огню на <span class='tooltip-value'>#</span> в течение 10 сек. В состоянии «Разрывные пули» существует <span class='tooltip-value'>#%</span>-ная вероятность не расходовать пули.",
			rankInfo: [80, 85, 90, 95, 100],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Скоростная стрельба",
			ranks: 4,
			desc: "Время перезарядки «Сквозного выстрела» сокращается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Время перезарядки «Сквозного выстрела» сокращается на <span class="tooltip-value">5</span> сек.</div>'],
			parent: 1,
		},
		{
			index: 7,
			name: "Рассеивание",
			ranks: 3,
			ranksnw: 2,
			desc: "Увеличивает область действия слабости на <span class='tooltip-value'>#</span> м. и уменьшает время перезарядки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает область действия слабости на <span class="tooltip-value">8</span> м. и уменьшает время перезарядки на <span class="tooltip-value">40</span> сек.</div>'],
		},
		{
			index: 8,
			name: "Владение пламенем",
			ranks: 5,
			desc: "Мастерство Огня увеличивается на <span class='tooltip-value'>#</span> очков, усиливая эффект горения на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [2, 4, 6, 8, 10],
		},
		{
			index: 9,
			name: "Горение души",
			ranks: 2,
			desc: "Жгучий выстрел с вероятностью <span class='tooltip-value'>#%</span> вызывает эффект горения, длительностью 8 сек. Цель теряет <span class='tooltip-value'>#</span> здоровья каждую секунду, а фиксированная сила атаки персонажа с использованием мастерства Огня увеличивается на 10%.",
			rankInfo: [50, 100],
			rankInfo2: [75, 100],
			parent: [0],
		},
		{
			index: 10,
			name: "Ураганный огонь",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Огня</span><span class='right'>Время перезарядки: 6 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 16 м.</span>\n\nАтакует цели в пределах сектора 120° радиуса 18 м. и наносит 100% базового урона и дополнительно <span class='tooltip-value'>#</span> ед. урона. Накладывает на цель эффект горения, ежесекундно снижающий здоровье в течение 5 сек. на <span class='tooltip-value'>#</span> и дополнительно на 20% от показателя мастерства Огня. Эффект множественного возгорания от «Ураганного огня» может сняться постепенно со всех целей. В состоянии «Разрывные пули» навык расходует 1 меткую пулю и наносит на 30% больше урона. Время горения увеличивается на 3 сек. и наносит дополнительный урон в размере 30% от показателя мастерства Огня.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [202, 299, 398, 498],
			rankInfo3: [791, 1436, 2069, 2690],
			rankInfo4: [60, 120, 180, 240],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">601</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Урон от Огня</span><span class="right">Время перезарядки: 6 сек.</span>\n<br><span class="left">Массовая атака</span><span class="right">Расстояние атаки – 16 м.</span>\n\n<br><br>Атакует цели в пределах сектора 120° радиуса 18 м. и наносит 100% базового урона и дополнительно <span class="tooltip-value">3300</span> ед. урона. Накладывает на цель эффект горения, ежесекундно снижающий здоровье в течение 5 сек. на <span class="tooltip-value">300</span> и дополнительно на 20% от показателя мастерства Огня. Эффект множественного возгорания от «Ураганного огня» может сняться постепенно со всех целей. В состоянии «Разрывные пули» навык расходует 1 меткую пулю и наносит на 30% больше урона. Время горения увеличивается на 3 сек. и наносит дополнительный урон в размере 30% от показателя мастерства Огня.</div>'],
		},
		{
			index: 13,
			name: "Скорость огня",
			ranks: 4,
			ranksnw: 1,
			desc: "Эффект ускорения при использовании спешки усиливается на <span class='tooltip-value'>#%</span>. Во время ускорения уклонение увеличивается на <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [15, 30, 45, 60],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Эффект ускорения при использовании спешки усиливается на <span class="tooltip-value">25%</span>. Во время ускорения уклонение увеличивается на <span class="tooltip-value">75</span>.</div>'],
		},
		{
			index: 14,
			name: "Пламенный гнев",
			ranks: 3,
			ranksnw: 1,
			desc: "Урон от эффекта горения при использовании навыка «Ураганный огонь» увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
			parent: 6,
		},
		{
			index: 15,
			name: "Взрывоопасность",
			ranks: 1,
			desc: "Навык слабости позволяет взорвать противника в состоянии возгорания, уменьшая ОЗ и ОМ на 1000. К навыку добавляется 500 очков на каждом уровне. Прерывает применение магических навыков и позволяет контратаковать противника (контратаковать можно только монстров).",
			rankInfo: [],
			parent: 3,
		},
		{
			index: 17,
			name: "Горячая поддержка",
			ranks: 2,
			desc: "Время перезарядки спешки сокращается на <span class='tooltip-value'>#</span> сек. Если персонажа атакуют 5 раз, вероятность рассеивания состояния уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
			rankInfo2: [50, 100],
			parent: 7,
		},
		{
			index: 19,
			name: "Резервная мощь",
			ranks: 2,
			desc: "При использовании навыка «Перезарядка» время восстановления навыков «Сквозная рана» и «Ураганный огонь» сокращается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
		},
		{
			index: 20,
			name: "Пылающая кровь",
			ranks: 3,
			desc: "Увеличивает сопротивление Огню на <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 21,
			name: "Эффективная стрельба",
			ranks: 3,
			ranksnw: 2,
			desc: "Дополнительный урон навыка «Сквозная рана» увеличивается на <span class='tooltip-value'>#%</span>, расход ОМ навыка уменьшается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Дополнительный урон навыка «Сквозная рана» увеличивается на <span class="tooltip-value">20%</span>, расход ОМ навыка уменьшается на <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 22,
			name: "Заградительный огонь",
			ranks: 4,
			desc: "Область действия навыков массовой атаки увеличивается на <span class='tooltip-value'>#%</span>. Время перезарядки «Ураганного огня» уменьшается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			parent: 8,
		},
		{
			index: 27,
			name: "Плавление камней",
			ranks: 4,
			desc: "Если на цель наложен эффект возгорания, «Ловчая сеть» уменьшает максимум ОЗ цели на <span class='tooltip-value'>#%</span> и ослабляет эффект исцеления на <span class='tooltip-value'>#%</span> в течение 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12, 16],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Если на цель наложен эффект возгорания, «Ловчая сеть» уменьшает максимум ОЗ цели на <span class="tooltip-value">20%</span> и ослабляет эффект исцеления на <span class="tooltip-value">50%</span> в течение 10 сек.</div>'],
		},
		{
			index: 28,
			name: "Очищающее пламя",
			ranks: 5,
			desc: "Уменьшает расход атакующих навыков Огня на <span class='tooltip-value'>#%</span> и увеличивает силу атаки на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Уменьшает расход атакующих навыков Огня на <span class="tooltip-value">36%</span> и увеличивает силу атаки на <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 29,
			name: "Разрывающая шрапнель",
			ranks: 3,
			desc: "Урон от базовой атаки при использовании сквозного выстрела увеличивается на <span class='tooltip-value'>#%</span>. В состоянии «Разрывные пули» время замедления увеличивается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Урон от базовой атаки при использовании сквозного выстрела увеличивается на <span class="tooltip-value">40%</span>. В состоянии «Разрывные пули» время замедления увеличивается на <span class="tooltip-value">4</span> сек.</div>'],
			parent: 13,
		},
		{
			index: 30,
			name: "Яростное пламя",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 30 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nТри последующих атаки увеличивают урон базовой атаки на <span class='tooltip-value'>#%</span> на 15 сек. Если персонаж получает урон во время активации навыка, он может войти в состояние «Взрыв гнева». Три последующие атаки увеличивают шанс нанесения крит. урона на 10%; максимальная продолжительность: 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [245, 301],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">361</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 30 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Три последующих атаки увеличивают урон базовой атаки на <span class="tooltip-value">25%</span> на 15 сек. Если персонаж получает урон во время активации навыка, он может войти в состояние «Взрыв гнева». Три последующие атаки увеличивают шанс нанесения крит. урона на 10%; максимальная продолжительность: 15 сек.</div>'],
		},
		{
			index: 31,
			name: "Поощрение",
			ranks: 3,
			desc: "Урон от критического удара при использовании «Прицельного огня» увеличивается на <span class='tooltip-value'>#%</span>, расход уменьшается на <span class='tooltip-value'>#%</span>, время действия увеличивается на <span class='tooltip-value'>#</span> мин.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [5, 10, 15],
			rankInfo4: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Урон от критического удара при использовании «Прицельного огня» увеличивается на <span class="tooltip-value">8%</span>, расход уменьшается на <span class="tooltip-value">80%</span>, время действия увеличивается на <span class="tooltip-value">20</span> мин.</div>'],
		},
		{
			index: 34,
			name: "Бесконечная ярость",
			ranks: 3,
			ranksnw: 2,
			desc: "Время действия «Яростного пламени» увеличивается на <span class='tooltip-value'>#</span> сек. Если в течение <span class='tooltip-value'>#</span> сек. после применения навыка персонаж будет атакован, он перейдет в состояние ярости.",
			rankInfo: [3, 6, 9],
			rankInfo2: [1, 2, 3],
			parent: 18,
		},
		{
			index: 35,
			name: "Душа добычи",
			ranks: 3,
			desc: "Если разница в уровнях персонажа и цели во время применения навыков «Разлом души», «Яростное пламя» и «Многократная смерть» не превышает 10, существует <span class='tooltip-value'>#%</span>-ная вероятность получить одну пулю.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 37,
			name: "Сопротивление души",
			ranks: 3,
			desc: "Если персонаж в состоянии разлома души подвергается атаке, его сопротивление всем стихиям увеличивается на <span class='tooltip-value'>#</span>, а защита – на <span class='tooltip-value'>#</span>. Суммируется до 3 раз, длительность – 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Если персонаж в состоянии разлома души подвергается атаке, его сопротивление всем стихиям увеличивается на <span class="tooltip-value">40</span>, а защита – на <span class="tooltip-value">40</span>. Суммируется до 3 раз, длительность – 10 сек.</div>'],
		},
		{
			index: 39,
			name: "Долгое горение",
			ranks: 2,
			desc: "Длительность эффекта горения, вызванного стрелком, увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
		},
		{
			index: 42,
			name: "Искра души",
			ranks: 2,
			desc: "В состоянии ярости атакующие навыки Огня, наносящие урон по определенной площади, восстанавливают <span class='tooltip-value'>#%</span> от макс. ОЗ. С вероятностью в <span class='tooltip-value'>#%</span> эти навыки не потратят меткую пулю при активном навыке «Разрывные пули».",
			rankInfo: [3, 6],
			rankInfo2: [50, 100],
			parent: 20,
		},
		{
			index: 43,
			name: "Слабость огня",
			ranks: 2,
			desc: "Эффект горения, вызванный атакой стрелка, уменьшается урон базовой атаки цели на <span class='tooltip-value'>#%</span>. Эффект горения складывается до 10 раз.",
			rankInfo: [1, 2],
		},
		{
			index: 46,
			name: "Огненный обстрел",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>781 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Огня</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nВ радиусе 16 м. наносит урон сразу 15 целям. Наносит 100% базового урона и дополнительно 4366 ед. урона. При активном навыке «Разрывные пули» на применение навыка «Огненный обстрел» расходует одну меткую пулю, дополнительный урон увеличивается на 20%, снимает с цели эффект горения, вызванный одновременно навыками «Жгучий выстрел» и «Ураганный огонь». Может наложить на цель молчание 4 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Безумное пламя",
			ranks: 4,
			desc: "Снижает время восстановления навыка «Огненный обстрел» на <span class='tooltip-value'>#</span> сек., а также повышает бонус к базовой атаке этого навыка на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [10, 20, 30, 40],
			parent: 26,
		},
		{
			index: 49,
			name: "Укротитель огня",
			ranks: 2,
			desc: "Увеличивает базовую атаку навыка «Водоворот огня» на <span class='tooltip-value'>#%</span>, а также увеличивает продолжительность действия эффекта разоружения на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20],
			rankInfo2: [1, 2],
		},
		{
			index: 51,
			name: "Раздражение",
			ranks: 3,
			desc: "Увеличивает урон от критической атаки на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 54,
			name: "Пули ярости",
			ranks: 1,
			desc: "Увеличивает бонус к урону навыка «Огненный обстрел» на 50%, уменьшает время чтения заклинания на 50%; уменьшает время восстановления на 8 сек.",
			rankInfo: [],
			parent: 26,
		},
	]
];