var data = [
	// one
	[
		{
			index: 1,
			name: "Wind Break",
			ranks: 5,
			ranksnw: 2,
			desc: "Whirlwind Strike reduces target's Wind Resistance by <span class='tooltip-value'>#</span> for 12 second(s).",
			rankInfo: [8, 16, 24, 32, 40],
		},
		{
			index: 3,
			name: "Wild Storm",
			ranks: 5,
			desc: "Searing Gust reduces target's Movement Speed by 50% for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [3, 4, 5, 6, 7],
		},
		{
			index: 6,
			name: "Ballistic",
			ranks: 3,
			desc: "Blood Mist increases your Movement Speed by 60% for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [3, 4, 5],
		},
		{
			index: 7,
			name: "Wind Lineage",
			ranks: 3,
			desc: "Archaic Lineage increases your Evasion by <span class='tooltip-value'>#</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 8,
			name: "Concentration",
			ranks: 4,
			desc: "Accuracy increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 9,
			name: "Cyclone",
			ranks: 4,
			desc: "Whirlwind Strike's Base Attack is increased by <span class='tooltip-value'>#%</span> and it's Cooldown is reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
			parent: [0],
		},
		{
			index: 10,
			name: "Rending Gale",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nWhile active, all single-target Wind Skills (except Blood Rush) will act as multi-target skills, attacking up to 5 targets within 4 meters. Also, Range of multi-target Wind skills is increased by 3 meters. Lasts <span class='tooltip-value'>#</span> second(s).",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [59, 100, 142, 185],
			rankInfo3: [20, 30, 40, 50],
		},
		{
			index: 12,
			name: "Immoblize",
			ranks: 3,
			desc: "The Duration of the Slow effect of Choking Gale is increased by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 4, 6],
		},
		{
			index: 14,
			name: "Pillage Gale",
			ranks: 3,
			ranksnw: 2,
			desc: "While Rending Gale is active, your Movement Speed is increased by <span class='tooltip-value'>#%</span>, and your Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [2, 4, 6],
			parent: 6,
		},
		{
			index: 16,
			name: "Storm Master",
			ranks: 4,
			desc: "Wind Mastery is increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Windthorn",
			ranks: 4,
			desc: "While Sanguine Surge is active, the Range of Choking Gale and Searing Gust is increased by <span class='tooltip-value'>#</span> meters. When the target's Health is higher than 60%, deals damage equal to <span class='tooltip-value'>#%</span> of their max Health.",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: [5, 10, 15, 20],
		},
		{
			index: 20,
			name: "Tornado",
			ranks: 3,
			desc: "The Movement Speed increasing effect of Sinister Speed is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 21,
			name: "Gale Rip",
			ranks: 3,
			desc: "The Base Attack of Wrathful Twister is increased by <span class='tooltip-value'>#%</span>, and it's Cooldown is reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 22,
			name: "Invasion Gust",
			ranks: 3,
			desc: "Rending Gale increases the Range of Wrathful Twister by <span class='tooltip-value'>#</span> meters. While Rending Gale is active, Sickle Assault has a <span class='tooltip-value'>#%</span> chance to stun targets for 2 seconds.",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 8,
		},
		{
			index: 23,
			name: "Wind Load",
			ranks: 2,
			desc: "Wind skills that requires a target's Health to be 60% have that requirement changed to <span class='tooltip-value'>#%</span>. Wind skills that require a target's Health to be 40% have that requirement changed to <span class='tooltip-value'>#%</span>.",
			rankInfo: [55, 50],
			rankInfo2: [35, 30],
		},
		{
			index: 25,
			name: "Wind Dancer",
			ranks: 3,
			ranksnw: 1,
			desc: "Each wind skill has a <span class='tooltip-value'>#%</span> chance to grant the Wind Dancer effect. Lasts 10 seconds, stacks 10 times. 10 stacks of Wind Dancer increase your next Wind skill's Base Attack by 100%.",
			rankInfo: [25, 50, 75],
		},
		{
			index: 26,
			name: "Wind Walk",
			ranks: 2,
			desc: "Increases Movement Speed and Mount Speed by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 28,
			name: "Draining Wind",
			ranks: 2,
			desc: "Targets affected by Sinister Speed have their Health recovery from Healing Effects reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 30,
			name: "Crimson Vortex",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 0.50 seconds</span>\n<span class='left'>Darkness</span><span class='right'>Cooldown: 180 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: 16 meters</span>\n\nPulls a target within 16 meters plus any other enemies within 10 meters of the target to your side and stuns them for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [109, 197],
			rankInfo3: [2, 2.5],
		},
		{
			index: 31,
			name: "Relentless Wind",
			ranks: 5,
			desc: "Base Attack increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4, 5],
		},
		{
			index: 33,
			name: "Dance Maestro",
			ranks: 2,
			desc: "Has a <span class='tooltip-value'>#%</span> chance to grant an additional stack of Wind Dancer.",
			rankInfo: [20, 40],
			parent: 15,
		},
		{
			index: 34,
			name: "Wind Heritage",
			ranks: 3,
			desc: "Increases Crimson Vortex’s Casting Range by <span class='tooltip-value'>#</span> meters and reduces the skill's Cooldown by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [10, 20, 30],
			parent: 18,
		},
		{
			index: 35,
			name: "Enfeebling Wind",
			ranks: 3,
			desc: "Crimson Vortex and Searing Gust reduce target's Crit Defense by <span class='tooltip-value'>#%</span> for lasts 10 seconds.",
			rankInfo: [6, 12, 18],
		},
		{
			index: 38,
			name: "Wind of Rage",
			ranks: 2,
			desc: "Bonus Damage of Wind Skills increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 40,
			name: "Zephyr",
			ranks: 3,
			desc: "Blood of the Weak increases your Wind Mastery by <span class='tooltip-value'>#</span> for 30 seconds.",
			rankInfo: [30, 60, 90],
		},
		{
			index: 41,
			name: "Wind Strider",
			ranks: 3,
			desc: "Reduces the Cooldown of Whirlwind Strike by <span class='tooltip-value'>#</span> seconds, and the Cooldown of Wrathful Twister by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [1.5, 3, 4.5],
		},
		{
			index: 42,
			name: "Wind Conch",
			ranks: 2,
			desc: "Whirlwind Strike and Wrathful Twister have a <span class='tooltip-value'>#%</span> chance to reset the Cooldown of Searing Gust.",
			rankInfo: [5, 10],
		},
		{
			index: 46,
			name: "Sickle Assault",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>416 Mana</span><span class='right'>Cast time: 2.5 seconds</span>\n<span class='left'>Wind damage</span><span class='right'>Cooldown: 25 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Short Range</span>\n\nStrikes targets within 12 meters three times. Each strike deals 100% Base Attack plus 1507 bonus damage. When target's Health is higher than 40%, each strike deals additional damage equal to 25% of your Max Attack. When target's Health is higher than 60%, each strike deals additional damage equal to 50% of your Max Attack. Each of your Masteries increase the Additional Damage by 0.1%.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Dark Sand",
			ranks: 4,
			desc: "Reduces the Cooldown of Sickle Assault by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 4, 6, 8],
			parent: 27,
		},
		{
			index: 49,
			name: "Tempest of Blades",
			ranks: 3,
			desc: "Crit Chance increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 51,
			name: "Dark Void",
			ranks: 2,
			desc: "While Wind Dancer is active, each stack of Wind Dancer increases Crit Damage by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Fatal Raid",
			ranks: 1,
			desc: "Sickle Assault increases your Base Attack by 50%, and Ensnares targets for 5 seconds.",
			rankInfo: [],
			parent: 27,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Scythe Wall",
			ranks: 5,
			ranksnw: 3,
			desc: "Each Grand Cleave increases your Base Defense by <span class='tooltip-value'>#%</span>. Stack 5 times, lasts 20 seconds.",
			rankInfo: [0.6, 1.2, 1.8, 2.4, 3],
		},
		{
			index: 4,
			name: "Shadow",
			ranks: 5,
			desc: "The Range of Shadow Twister is increased by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 6,
			name: "Fast Shadow",
			ranks: 5,
			desc: "The Cooldown of Shadow Twister is reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 8,
			name: "Sanguine Armor",
			ranks: 5,
			desc: "While Sanguine Surge is active, your Base Defense is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 9,
			name: "Cleave Master",
			ranks: 3,
			ranksnw: 2,
			desc: "Reduces the Cooldown of Grand Cleave by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [0.5, 1, 1.5],
			parent: [0],
		},
		{
			index: 10,
			name: "Blood Mail",
			ranks: 4,
			ranksnw: 2,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 90 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nAbsorbs damage equal to <span class='tooltip-value'>#%</span> of your Max Health. Reduces attacker's Defense by <span class='tooltip-value'>#</span>. Lasts 20 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [45, 104, 161, 219],
			rankInfo3: [15, 20, 25, 30],
			rankInfo4: [50, 100, 150, 200],
		},
		{
			index: 11,
			name: "Hard Skin",
			ranks: 3,
			desc: "Increases your Crit Defense by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 15,
			name: "Shadow Touch",
			ranks: 4,
			ranksnw: 2,
			desc: "Shadow Strike's Healing Effect now requires your Health to be less than <span class='tooltip-value'>#%</span>. When your Health is less than <span class='tooltip-value'>#%</span>, the Healing Effect is doubled.",
			rankInfo: [85, 90, 95, 100],
			rankInfo2: [15, 20, 25, 30],
		},
		{
			index: 16,
			name: "Dark Shadow Wall",
			ranks: 3,
			desc: "Increaes your Dark Resistance and Wind Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Provocative Cleave",
			ranks: 3,
			desc: "Grand Cleave Has a <span class='tooltip-value'>#%</span> chance to interupt target's casting and Taunt the target for 3 seconds.",
			rankInfo: [5, 10, 15],
			parent: 4,
		},
		{
			index: 18,
			name: "Blood Thirst",
			ranks: 3,
			desc: "Blood Mail heals you an amount equal to <span class='tooltip-value'>#%</span> of your Max Health. For 12 seconds, you will lose 3% Health each second. Being struck 3 times will end the Health loss.",
			rankInfo: [10, 20, 30],
			parent: 5,
		},
		{
			index: 19,
			name: "Broken Shadow Wall",
			ranks: 2,
			desc: "While Shadow Strike's Healing Effect is active, your Crit Dodge is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
			parent: 7,
		},
		{
			index: 22,
			name: "Sluggish Blood",
			ranks: 4,
			desc: "Shadow Twister Has a <span class='tooltip-value'>#%</span> chance to Ensnare targets for 1 second.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 23,
			name: "Shadewrath",
			ranks: 3,
			desc: "Dark Skills generate Threat equal to <span class='tooltip-value'>#%</span> of the skill's Bonus Damage.",
			rankInfo: [70, 140, 210],
		},
		{
			index: 26,
			name: "Surge",
			ranks: 3,
			desc: "Increases your Base Health by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 28,
			name: "Dark Shadow Armor",
			ranks: 4,
			desc: "Increases your Crit Dodge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 29,
			name: "Blood Surge",
			ranks: 3,
			desc: "Increaes the Duration of Warblood Pact by <span class='tooltip-value'>#</span> seconds, and increases your Accuracy by <span class='tooltip-value'>#</span>.",
			rankInfo: [300, 600, 900],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 30,
			name: "Shadow Miasma",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: Instant</span>\n<span class='left'>Darkness</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>Aura blessing</span><span class='right'>Range: None</span>\n\nToggle Skill (cancel effect by casting again). Slows targets within <span class='tooltip-value'>#</span> meters by 5% per second, lasts 4 seconds, stacks 10 times, lasts 30 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [128, 164],
			rankInfo3: [12, 14],
		},
		{
			index: 31,
			name: "Epitome",
			ranks: 2,
			desc: "Reduces the Cooldown of Shadow Strike and Shadow Grip by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2],
		},
		{
			index: 33,
			name: "Blood Fountain",
			ranks: 2,
			ranksnw: 1,
			desc: "Shadow Grip's Healing Effect will be trigger when your Health is lower than <span class='tooltip-value'>#%</span>. When your Health is lower than <span class='tooltip-value'>#%</span>, the Healing Effect doubles.",
			rankInfo: [85, 90],
			rankInfo2: [20, 25],
		},
		{
			index: 34,
			name: "Dark Shadow",
			ranks: 3,
			ranksnw: 2,
			desc: "The Duration of Shadow Miasma is increased by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [5, 10, 15],
			parent: 17,
		},
		{
			index: 36,
			name: "Floating Shadow",
			ranks: 3,
			desc: "Each Dark Resistance increases your Max Health by <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 38,
			name: "Shadow Glaze",
			ranks: 3,
			desc: "Increaes the range of Shadow Miasma by <span class='tooltip-value'>#</span> meters. Each stack of the Slow Effect will generate additional threat.",
			rankInfo: [1, 2, 3],
			parent: 20,
		},
		{
			index: 39,
			name: "Shadow Taunt",
			ranks: 2,
			desc: "Searing Gust Taunts targets for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 3],
		},
		{
			index: 41,
			name: "Vanishing Shadow",
			ranks: 2,
			desc: "Brawler's Heart is able to reset the Cooldown of Shadow Strike.",
			rankInfo: [],
			parent: 19,
		},
		{
			index: 42,
			name: "Bloodboil",
			ranks: 3,
			desc: "Sanguine Surge increases your Max Health by <span class='tooltip-value'>#%</span> and increases the Health you recover from Healing Effects by <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
			rankInfo2: [8, 16, 24],
		},
		{
			index: 46,
			name: "Corrupting Seizure",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>299 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Dark damage</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 20 meters</span>\n\nPulls a target within 20 meters to your side. Deals 100% Base Attack plus 2999 bonus damage. Taunts the target, and reduces the target's Base Attack by 30%. Reduces target's Health recovered from Healing Effects by 20%. Lasts 5 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Corrupt Shadow",
			ranks: 4,
			desc: "Reduces the Cooldown of Corrupting Seizure by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 4, 6, 8],
			parent: 26,
		},
		{
			index: 51,
			name: "Cursed Touch",
			ranks: 3,
			desc: "Increases the Range of Shadow Cyclone by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 52,
			name: "Iron Touch",
			ranks: 2,
			desc: "Increases your Tenacity by <span class='tooltip-value'>#</span> (PvE only).",
			rankInfo: [100, 200],
		},
		{
			index: 54,
			name: "Cursed Poison",
			ranks: 1,
			desc: "Increases the Base Attack of Corrupting Seizure by 100%, and Stuns targets affected by the skill for 4 seconds. Corrupting Seizure will trigger Corrupting Skin, increasing your Tenacity by 60 (PvE only). Lasts 45 seconds, stacks 5 times.",
			rankInfo: [],
			parent: 26,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Conviction",
			ranks: 5,
			desc: "Increases the Duration of Instigator by <span class='tooltip-value'>#</span> seconds. Increases your Crit Damage by <span class='tooltip-value'>#%</span> of your Crit Defense.",
			rankInfo: [300, 600, 900, 1200, 1500],
			rankInfo2: [20, 40, 60, 80, 90],
		},
		{
			index: 4,
			name: "Dark Cleave",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the Bonus Damage of Grand Cleave by <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your Dark Mastery.",
			rankInfo: [40, 80, 120, 160, 200],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 5,
			name: "Pure Blood",
			ranks: 3,
			ranksnw: 2,
			desc: "Blood Mist increases your Base Attack by <span class='tooltip-value'>#%</span> for 10 seconds.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 6,
			name: "Sorrow Rules",
			ranks: 4,
			desc: "While Sanguine Surge is active, your Dark Mastery and Wind Mastery are increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 7,
			name: "Heritage Lineage",
			ranks: 3,
			desc: "The Attack increase from Blood Pact is further increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 10,
			name: "Hostility",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 0.5 seconds</span>\n<span class='left'>Darkness</span><span class='right'>Cooldown: 25 seconds</span>\n<span class='left'>Single-target curse</span><span class='right'>Range: 22 meters</span>\n\nCurses the target. Increases Dark Damage the target receives by <span class='tooltip-value'>#%</span>. Lasts <span class='tooltip-value'>#</span> second(s).",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [69, 120, 172, 225],
			rankInfo3: [9, 10, 11, 12],
			rankInfo4: [3, 4, 5, 6],
		},
		{
			index: 11,
			name: "Plunderer",
			ranks: 3,
			desc: "Increases the Crit Damage of Shadow Strike by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 12,
			name: "Rampage Slash",
			ranks: 4,
			ranksnw: 2,
			desc: "Increases the Crit Chance of Grand Cleave by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12],
			parent: 1,
		},
		{
			index: 13,
			name: "Life Swap",
			ranks: 3,
			desc: "Reduces the Cooldown of Sanguine Surge and Blood Mist by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [20, 40, 60],
			parent: 2,
		},
		{
			index: 15,
			name: "Wind Dagger",
			ranks: 3,
			desc: "The Range of Choking Gale is increased by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 17,
			name: "Blood Loot",
			ranks: 4,
			desc: "The Crit Chance of Shadow Strike is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
		},
		{
			index: 18,
			name: "Blood Lancet",
			ranks: 4,
			desc: "The increased Bonus Damage effect of Hostility is increased by <span class='tooltip-value'>#%</span>. and the Range is increased by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [1, 2, 3, 4],
			parent: 5,
		},
		{
			index: 20,
			name: "Accelerated Cleave",
			ranks: 3,
			desc: "Grand Cleave Has a <span class='tooltip-value'>#%</span> chance to reset the Cooldown of Shadow Strike.",
			rankInfo: [15, 30, 45],
			parent: 7,
		},
		{
			index: 22,
			name: "Blood Consume",
			ranks: 3,
			desc: "Crit Strikes of dark skills reduce target's Dark Resisatnce by <span class='tooltip-value'>#</span>. Stacks 5 times, lasts 60 seconds.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 23,
			name: "Root of Bloodfight",
			ranks: 3,
			desc: "Increaes the Base Attack of Grand Cleave by <span class='tooltip-value'>#%</span> and reduces the Cooldown by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [10, 20, 30],
			rankInfo2: [0.5, 1, 1.5],
		},
		{
			index: 25,
			name: "Restless Cocoon",
			ranks: 3,
			desc: "Warblood Pact increases your Crit Chance by <span class='tooltip-value'>#%</span> of your Crit Dodge. The Duration is increased by 300 second(s).",
			rankInfo: [40, 70, 100],
		},
		{
			index: 26,
			name: "Bloodbrawl Fury",
			ranks: 2,
			desc: "The Duration of Sanguine Surge is increased by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [15, 30],
		},
		{
			index: 27,
			name: "Blood Pact Pit",
			ranks: 3,
			desc: "Searing Gust reduces target's Crit Dodge by <span class='tooltip-value'>#%</span> for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3],
			rankInfo2: [2, 3, 4],
		},
		{
			index: 30,
			name: "Blood Blast",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: Instant</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 120 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nIncreases your Max Health by 100%. Each attack recovers 2% Health. Lasts <span class='tooltip-value'>#</span> seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [63, 115],
			rankInfo3: [15, 20],
		},
		{
			index: 31,
			name: "Dark Touch",
			ranks: 3,
			desc: "When your Health is higher than 80%, Sanguine Surge increaes the Bonus Damage of your dark skills by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 32,
			name: "Dark World",
			ranks: 4,
			desc: "Dark Mastery is increased by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 33,
			name: "Blood of Hatred",
			ranks: 3,
			desc: "Hostility and Blood of the Weak increase your Accuracy by <span class='tooltip-value'>#</span> for 15 seconds.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 34,
			name: "Bloodwave Yowl",
			ranks: 3,
			desc: "Blood Blast increases your Casting Speed by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			parent: 18,
		},
		{
			index: 38,
			name: "Shadehowl",
			ranks: 2,
			desc: "Increases the Base Attack of Shadow Grip by <span class='tooltip-value'>#%</span>. When your Health is higher than 80%, your Base Attack will be increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 39,
			name: "Pride of Dark",
			ranks: 3,
			desc: "Dark Skill's Bonus Damage is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 41,
			name: "Blackblood Control",
			ranks: 3,
			desc: "While Sanguine Surge is active, Crit Strikes of dark skills will cause the target to Bleed, losing health equal to <span class='tooltip-value'>#%</span> of your Dark Mastery each second for 5 seconds.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 42,
			name: "Melee Chill",
			ranks: 2,
			desc: "The Cooldown of Brawler's Heart is reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [15, 30],
		},
		{
			index: 46,
			name: "Mad Cleave",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>395 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Dark damage</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Short Range</span>\n\nStrikes twice. Deals 100% Base Attack plus 4046 bonus damage. Each strike consumes 5% of your Max Health, and deals 30% extra Crit Damage. When your Health is more than 80%, targets are stunned for 3 seconds. When your Health is more than 40%, targets are Ensnared for 2 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Blood Frenzy",
			ranks: 4,
			desc: "The Cooldown of Mad Cleave is reduced by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [2, 4, 6, 8],
			parent: 27,
		},
		{
			index: 49,
			name: "Blood Soul",
			ranks: 3,
			desc: "When your Health is higher than 80%, Shadow Cyclone will stun targets for <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2, 3],
		},
		{
			index: 51,
			name: "Blood Block",
			ranks: 2,
			desc: "For effects that require 80% or 40% Health, that requirement is reduced by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 54,
			name: "Frenzied Roar",
			ranks: 1,
			desc: "Increases the Crit Chance of Mad Cleave by 5%. When your Health is higher than 40%, increases your Base Attack by 50% When your Health is higher than 80%, increases your Base Attack by 100%.",
			rankInfo: [],
			parent: 27,
		},
	]
];