var data = [
	// one
	[
		{
			index: 1,
			name: "Жгучее клеймо",
			ranks: 5,
			ranksnw: 2,
			desc: "«Огонь смерти» за каждый действующий на цель эффект «Чистый огонь» наносит дополнительный урон «Жгучим клеймом». Каждый активный эффект «Чистого огня» дополнительно наносит урон в размере <span class='tooltip-value'>#%</span> от силы атаки. Размер урона, наносимого «Жгучим клеймом», зависит от мастерства Огня и сопротивления Огню цели.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>«Огонь смерти» за каждый действующий на цель эффект «Чистый огонь» наносит дополнительный урон «Жгучим клеймом». Каждый активный эффект «Чистого огня» дополнительно наносит урон в размере <span class="tooltip-value">6%</span> от силы атаки. Размер урона, наносимого «Жгучим клеймом», зависит от мастерства Огня и сопротивления Огню цели.</div>'],
		},
		{
			index: 3,
			name: "Душа огня",
			ranks: 5,
			desc: "«Живая рана» снижает сопротивление огню цели на <span class='tooltip-value'>#</span> ед.; продолжительность – 30 сек.",
			rankInfo: [15, 30, 45, 60, 75],
		},
		{
			index: 6,
			name: "Клеймящий удар",
			ranks: 3,
			desc: "Увеличивает дальность атаки навыком «Дьявольские вилы» на <span class='tooltip-value'>#</span> метра. Снижает урон базовой и дополнительных атак на <span class='tooltip-value'>#%</span>. Снижает урон базовой и дополнительных атак в пользу урона стихией Огня. Если навык «Дьявольские вилы» наносит критический урон, «Жгучее клеймо» применяется дважды.",
			rankInfo: [4, 8, 12],
			rankInfo2: [40, 70, 100],
		},
		{
			index: 7,
			name: "Чистый огонь",
			ranks: 3,
			desc: "Каждый активный эффект «Чистого огня» уменьшает сопротивление Огню цели на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Каждый активный эффект «Чистого огня» уменьшает сопротивление Огню цели на <span class="tooltip-value">12</span> ед.</div>'],
		},
		{
			index: 8,
			name: "Огненная ярость",
			ranks: 4,
			desc: "Уменьшает силу атаки на <span class='tooltip-value'>#%</span>. Увеличивает крит. шанс на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [2, 4, 6, 8],
		},
		{
			index: 9,
			name: "Яростный огонь",
			ranks: 4,
			desc: "Увеличивает шанс нанести критический урон навыком «Огонь смерти» на <span class='tooltip-value'>#%</span>. При нанесении критического урона «Огнем смерти» урон от «Жгучего клейма» наносится дважды.",
			rankInfo: [3, 6, 9, 12],
			parent: [0],
		},
		{
			index: 10,
			name: "Огонь чистилища",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Огня</span><span class='right'>Время перезарядки: 12 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nАтакует несколько целей в радиусе 10 м. Атака состоит из нескольких этапов; каждый этап наносит 100% базового урона + <span class='tooltip-value'>#</span> ед. доп. урона. Каждый этап атаки накладывает 1 эффект «Чистый огонь» и после критического удара вызывает головокружение у цели на 1 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [134, 205, 281, 362],
			rankInfo3: [964, 1964, 2980, 4013],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">448</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Урон от Огня</span><span class="right">Время перезарядки: 12 сек.</span>\n<br><span class="left">Массовая атака</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Атакует несколько целей в радиусе 10 м. Атака состоит из нескольких этапов; каждый этап наносит 100% базового урона + <span class="tooltip-value">5062</span> ед. доп. урона. Каждый этап атаки накладывает 1 эффект «Чистый огонь» и после критического удара вызывает головокружение у цели на 1 сек.</div>'],
		},
		{
			index: 12,
			name: "Крушение чар",
			ranks: 3,
			desc: "Снижает затраты ОМ на атакующие навыки огня на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 14,
			name: "Огненная земля",
			ranks: 3,
			ranksnw: 2,
			desc: "Увеличивает базовый урон навыка «Огонь чистилища» на <span class='tooltip-value'>#%</span>, снижает время перезарядки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает базовый урон навыка «Огонь чистилища» на <span class="tooltip-value">40%</span>, снижает время перезарядки на <span class="tooltip-value">4</span> сек.</div>'],
			parent: 6,
		},
		{
			index: 16,
			name: "Огненная бездна",
			ranks: 4,
			desc: "Увеличивает мастерство Огня на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 17,
			name: "Угасающий чистый огонь",
			ranks: 4,
			ranksnw: 2,
			desc: "При нанесении критического урона навыком «Тлеющие угли» с вероятностью <span class='tooltip-value'>#%</span> будет дополнительно нанесен «Обжигающий удар».",
			rankInfo: [25, 50, 75, 100],
		},
		{
			index: 20,
			name: "Быстрое пламя",
			ranks: 3,
			desc: "Повышает эффективность ускорения «Бесовского предела» на <span class='tooltip-value'>#%</span>, увеличивает продолжительность на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Повышает эффективность ускорения «Бесовского предела» на <span class="tooltip-value">40%</span>, увеличивает продолжительность на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 22,
			name: "Обжигающий удар",
			ranks: 4,
			desc: "За каждый действующий на цель эффект «Чистый огонь» навык «Огонь чистилища» наносит урон стихией Огня в размере <span class='tooltip-value'>#%</span> от силы атаки душегуба. При нанесении критического урона «Обжигающий удар» наносит урон дважды.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>За каждый действующий на цель эффект «Чистый огонь» навык «Огонь чистилища» наносит урон стихией Огня в размере <span class="tooltip-value">7.5%</span> от силы атаки душегуба. При нанесении критического урона «Обжигающий удар» наносит урон дважды.</div>'],
			parent: 8,
		},
		{
			index: 24,
			name: "Ярость жара",
			ranks: 4,
			desc: "Критический урон увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9, 12],
		},
		{
			index: 25,
			name: "Путь огня",
			ranks: 3,
			ranksnw: 1,
			desc: "Применение навыка «Тлеющие угли» увеличит скорость передвижения на 60% продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Применение навыка «Тлеющие угли» увеличит скорость передвижения на 60% продолжительность – <span class="tooltip-value">5</span> сек.</div>'],
			parent: 10,
		},
		{
			index: 27,
			name: "Растущая боль",
			ranks: 4,
			desc: "Уменьшает время перезарядки навыков «Огонь чистилища» и «Огонь смерти» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [0.5, 1, 1.5, 2],
		},
		{
			index: 30,
			name: "Рождение огня",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Огненное проклятие</span><span class='right'>Время перезарядки: 60 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nПоджигает цели в радиусе 8 м. Горящие цели ежесекундно получают один активный эффект «Чистый огонь»; продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [194, 342],
			rankInfo3: [15, 18],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">483</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Огненное проклятие</span><span class="right">Время перезарядки: 60 сек.</span>\n<br><span class="left">Массовое проклятие</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Поджигает цели в радиусе 8 м. Горящие цели ежесекундно получают один активный эффект «Чистый огонь»; продолжительность – <span class="tooltip-value">21</span> сек.</div>'],
		},
		{
			index: 32,
			name: "Прах",
			ranks: 5,
			desc: "При нанесении критического урона второй урон «Жгучего клейма» увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>При нанесении критического урона второй урон «Жгучего клейма» увеличивается на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 33,
			name: "Неугасимая ярость",
			ranks: 2,
			desc: "Если количество действующих на цель эффектов «Чистый огонь» больше 5, навык «Тлеющие угли» наносит цели урон в размере <span class='tooltip-value'>#%</span> силы атаки стихии огня,; продолжительность – 10 сек. Размер урона определяется исключительно мастерством Огня душегуба, на него никак не влияет показатель защиты цели.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Если количество действующих на цель эффектов «Чистый огонь» больше 5, навык «Тлеющие угли» наносит цели урон в размере <span class="tooltip-value">15%</span> силы атаки стихии огня; продолжительность – 10 сек. Размер урона определяется исключительно мастерством Огня душегуба, на него никак не влияет показатель защиты цели.</div>'],
			parent: 14,
		},
		{
			index: 34,
			name: "Сожженная плоть",
			ranks: 3,
			ranksnw: 1,
			desc: "«Рождение огня» уменьшит скорость передвижения цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [30, 40, 50],
			parent: 16,
		},
		{
			index: 36,
			name: "Адепт Штормиона",
			ranks: 3,
			desc: "Увеличивает базовый урон навыка «Касание дьявола» на <span class='tooltip-value'>#%</span>, а шанс нанесения критического урона на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Вечный огонь",
			ranks: 3,
			desc: "Увеличивает продолжительность действия «Рождение огня» на <span class='tooltip-value'>#%</span>, при каждом наложении эффекта «Чистый огонь» с вероятностью <span class='tooltip-value'>#%</span> накладывается еще один эффект.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает продолжительность действия «Рождение огня» на <span class="tooltip-value">40%</span>, при каждом наложении эффекта «Чистый огонь» с вероятностью <span class="tooltip-value">40%</span> накладывается еще один эффект.</div>'],
			parent: 19,
		},
		{
			index: 40,
			name: "Душевное помешательство",
			ranks: 2,
			desc: "Увеличивает шанс нанесения критического удара навыком «Касание дьявола» на <span class='tooltip-value'>#%</span>, крит. удар вызовет у цели головокружение на <span class='tooltip-value'>#</span> сек. Также на 6 секунд уменьшает скорость чтения заклинаний цели, получившей критический урон, на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
			rankInfo2: [2, 3],
			rankInfo3: [15, 30],
		},
		{
			index: 41,
			name: "Очищение огнем",
			ranks: 3,
			desc: "Персонаж и союзники оказавшиеся под действием эффекта «Месть огня», ежесекундно восстанавливают <span class='tooltip-value'>#%</span> ОЗ и ОМ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Персонаж и союзники оказавшиеся под действием эффекта «Месть огня», ежесекундно восстанавливают <span class="tooltip-value">4%</span> ОЗ и ОМ.</div>'],
		},
		{
			index: 42,
			name: "Излучение",
			ranks: 2,
			desc: "«Огонь смерти» с вероятностью <span class='tooltip-value'>#%</span> сбрасывает время восстановления «Касания дьявола»; следующее «Касание дьявола», примененное в течение 10 сек., затронет еще одну цель в радиусе 6 м.",
			rankInfo: [8, 16],
		},
		{
			index: 46,
			name: "Знамение Армагеддона",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>411 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Время перезарядки: 300 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nАдское пламя окутывает тебя. Увеличивает мастерство Огня на 200 ед., увеличивает крит. уклонение на 50%. Ежесекундно наносит персонажу урон в размере 3% от макс. ОЗ. Каждую секунду на противников в радиусе 10 м. накладывается эффект «Чистый огонь». Если осталось меньше 20% ОЗ, действие эффекта прекращается; максимальная продолжительность – 20 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Долгий Армагеддон",
			ranks: 4,
			desc: "«Знамение Армагеддона» увеличивает дальность применения навыка «Чистый огонь» на <span class='tooltip-value'>#</span> м.",
			rankInfo: [2, 4, 6, 8],
			parent: 25,
		},
		{
			index: 49,
			name: "Пепелище",
			ranks: 3,
			desc: "Повышает силу базовой атаки на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 51,
			name: "Огонь искупления",
			ranks: 2,
			desc: "Навыки «Огонь смерти», «Огоньчистилища», «Тлеющие угли» и «Касание дьявола» с вероятностью <span class='tooltip-value'>#%</span> снимут с цели последний атакующий эффект благословения.",
			rankInfo: [20, 40],
		},
		{
			index: 54,
			name: "Гибель миров",
			ranks: 1,
			desc: "Увеличивает продолжительность навыка «Знамение Армагеддона» на 10 сек., дополнительно увеличивает базовую силу атаки персонажа под действием этого навыка на 30%.",
			rankInfo: [],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Глубокие страдания",
			ranks: 5,
			ranksnw: 3,
			desc: "Увеличивает урон, наносимый в течение некоторого времени навыком «Пытка душегуба», на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20, 25],
		},
		{
			index: 4,
			name: "Опытный мучитель",
			ranks: 5,
			desc: "Увеличивает продолжительность действия эффекта «Мучитель» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивает продолжительность действия эффекта «Мучитель» на <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 6,
			name: "Подавление разума",
			ranks: 5,
			desc: "Каждый раз, когда цель находится под действием эффекта головокружения от навыка «Пытка духа», она получает урон стихией Земли в размере <span class='tooltip-value'>#%</span> от силы атаки душегуба.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Каждый раз, когда цель находится под действием эффекта головокружения от навыка «Пытка духа», она получает урон стихией Земли в размере <span class="tooltip-value">120%</span> от силы атаки душегуба.</div>'],
		},
		{
			index: 7,
			name: "Демон-мучитель",
			ranks: 5,
			desc: "Урон, отражаемый навыком «Бесовская яма», активирует эффект «Демон-мучитель», который каждые 2 сек. наносит цели урон в размере <span class='tooltip-value'>#%</span> от максимальной силы атаки цели в виде урона стихией Земли; продолжительность – 6 сек.",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 9,
			name: "Укол боли",
			ranks: 4,
			ranksnw: 2,
			desc: "«Пытка душегуба» наносит урон стихией земли в размере <span class='tooltip-value'>#%</span> от силы атаки душегуба.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 50, 60, 70],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>«Пытка душегуба» наносит урон стихией земли в размере <span class="tooltip-value">80%</span> от силы атаки душегуба.</div>'],
			parent: [0],
		},
		{
			index: 10,
			name: "Река мертвых",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1.5 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Простая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nНаносит 100% базового урона + <span class='tooltip-value'>#</span> ед. дополнительного урона. Если цель находится под действием какого-либо эффекта Мучителя, «Река мертвых» уменьшает сопротивление Земле на 20 ед., продолжительность – 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [137, 263, 382, 493],
			rankInfo3: [1035, 1874, 2735, 3618],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">597</span> ОМ</span><span class="right">Чтение: 1.5 сек.</span>\n<br><span class="left">Урон от Земли</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Простая атака</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Наносит 100% базового урона + <span class="tooltip-value">4523</span> ед. дополнительного урона. Если цель находится под действием какого-либо эффекта Мучителя, «Река мертвых» уменьшает сопротивление Земле на 20 ед., продолжительность – 15 сек.</div>'],
		},
		{
			index: 11,
			name: "Источник злобы",
			ranks: 3,
			desc: "Увеличивает эффективность исцеления от навыка «Жажда боли» на <span class='tooltip-value'>#%</span>, при этом снижает эффективность исцеления цели, на которую действует эффект «Мучитель», на <span class='tooltip-value'>#%</span>.",
			rankInfo: [40, 80, 120],
			rankInfo2: [15, 20, 25],
		},
		{
			index: 15,
			name: "Смердение",
			ranks: 4,
			desc: "При каждом использовании навыков «Пытка душегуба», «Жажда боли», «Удушающая пытка» и «Река мертвых» на персонажа накладывается один эффект «Смердение». Каждый активный эффект увеличивает базовую силу атаки персонажа на <span class='tooltip-value'>#%</span>, эффект суммируется до 5 раз, продолжительность – 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>При каждом использовании навыков «Пытка душегуба», «Жажда боли», «Удушающая пытка» и «Река мертвых» на персонажа накладывается один эффект «Смердение». Каждый активный эффект увеличивает базовую силу атаки персонажа на <span class="tooltip-value">5%</span>, эффект суммируется до 5 раз, продолжительность – 10 сек.</div>'],
		},
		{
			index: 16,
			name: "Адские муки",
			ranks: 3,
			desc: "Увеличивает урон в течение некоторого времени, на <span class='tooltip-value'>#%</span>",
			rankInfo: [10, 20, 30],
		},
		{
			index: 17,
			name: "Зародыш проклятия",
			ranks: 4,
			desc: "«Пытка душегуба» снижает скорость передвижения цели на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>«Пытка душегуба» снижает скорость передвижения цели на <span class="tooltip-value">50%</span>.</div>'],
			parent: 4,
		},
		{
			index: 18,
			name: "Смертельная встряска",
			ranks: 4,
			ranksnw: 2,
			desc: "Увеличивает базовый урон навыка «Река мертвых» на <span class='tooltip-value'>#%</span>, а также сокращает время перезарядки этого навыка на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [1, 2, 3, 4],
			parent: 5,
		},
		{
			index: 21,
			name: "Замершее сердце",
			ranks: 4,
			desc: "Уменьшает время перезарядки навыка «Удушающая пытка» на <span class='tooltip-value'>#</span> сек.; увеличивает урон, наносимый в течение некоторого времени, на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [10, 20, 30, 40],
		},
		{
			index: 24,
			name: "Уничтожение",
			ranks: 4,
			ranksnw: 2,
			desc: "При атаке навыком «Тлеющие угли» все активные эффекты «Рождения огня» на цели взрываются как эффекты мучителя. Каждый взорванный эффект мучителя (за исключением «Удушающей пытки») наносит урон стихией Земли в размере <span class='tooltip-value'>#%</span> от базовой атаки. Каждый уровень «Удулиающей пытки» наносит урон стихией Земли в размере <span class='tooltip-value'>#%</span> от базовой атаки.",
			rankInfo: [20, 40, 60, 80],
			rankInfo2: [3, 6, 9, 12],
		},
		{
			index: 26,
			name: "Пленный дух",
			ranks: 3,
			desc: "При нанесении урона навыком «Река мертвых» увеличивается время чтения заклинаний цели на <span class='tooltip-value'>#%</span>, продолжительность – 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При нанесении урона навыком «Река мертвых» увеличивается время чтения заклинаний цели на <span class="tooltip-value">20%</span>, продолжительность – 10 сек.</div>'],
			parent: 10,
		},
		{
			index: 28,
			name: "Сумерки Армагеддона",
			ranks: 4,
			desc: "При использовании навыка «Тлеющие угли» с вероятностью <span class='tooltip-value'>#%</span> цель не теряет эффект «Мучитель».",
			rankInfo: [25, 50, 75, 100],
			parent: 12,
		},
		{
			index: 29,
			name: "Угасающая надежда",
			ranks: 3,
			desc: "По завершению действия навыка «Зерно трусости», цель получает оглушение на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>По завершению действия навыка «Зерно трусости», цель получает оглушение на <span class="tooltip-value">4</span> сек.</div>'],
		},
		{
			index: 30,
			name: "Abusive Intention",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Время перезарядки: 300 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nThe cooldown of Greedy Torment is halved and Fading Suffering applies one extra stack. Painful Torture is able to hit multiple targets within a radius of 5 meters and Demonic Torture ensnares the target for 2 seconds. This skill lasts <span class='tooltip-value'>#</span> second(s), during which you are immune to Silence, Stun, and Disarm.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [268, 476],
			rankInfo3: [15, 20],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">672</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Благословение</span><span class="right">Время перезарядки: 300 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>The cooldown of Greedy Torment is halved and Fading Suffering applies one extra stack. Painful Torture is able to hit multiple targets within a radius of 5 meters and Demonic Torture ensnares the target for 2 seconds. This skill lasts <span class="tooltip-value">25</span> second(s), during which you are immune to Silence, Stun, and Disarm.</div>'],
		},
		{
			index: 32,
			name: "Лютость",
			ranks: 2,
			desc: "При каждом убийстве цели персонаж каждые 2 сек. восстанавливает ОЗ на <span class='tooltip-value'>#</span> %, срабатывает не чаще одного раза в 60 сек.",
			rankInfo: [20, 40],
		},
		{
			index: 33,
			name: "Канонизация",
			ranks: 2,
			desc: "Увеличивает шанс критического удара навыка «Удушающая пытка» на <span class='tooltip-value'>#%</span>. Критический удар, наносимый «Удушающей пыткой», вызывает у цели молчание на 2 сек.",
			rankInfo: [4, 8],
		},
		{
			index: 34,
			name: "Жестокость",
			ranks: 3,
			ranksnw: 2,
			desc: "Увеличивает продолжительность действия эффекта «Жестокая душа» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			parent: 16,
		},
		{
			index: 36,
			name: "Угасание",
			ranks: 3,
			desc: "Навык «Река мертвых», уменьшает сопротивления всех стихий цели, по которой пришелся урон, на 4 ед., эффект суммируется до 50 раз; продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 8, 11],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Навык «Река мертвых», уменьшает сопротивления всех стихий цели, по которой пришелся урон, на 4 ед., эффект суммируется до 50 раз; продолжительность – <span class="tooltip-value">14</span> сек.</div>'],
		},
		{
			index: 38,
			name: "Адская жестокость",
			ranks: 3,
			desc: "«Жестокая душа» дополнительно увеличивает мастерство Земли персонажа на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [60, 120, 180],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Жестокая душа» дополнительно увеличивает мастерство Земли персонажа на <span class="tooltip-value">240</span> ед.</div>'],
			parent: 19,
		},
		{
			index: 39,
			name: "Дары смерти",
			ranks: 2,
			desc: "Снижает потерю ОЗ от навыка «Последняя песня» на <span class='tooltip-value'>#%</span> и увеличивает продолжительность на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [50, 100],
			rankInfo2: [2, 4],
		},
		{
			index: 41,
			name: "Ангел духов",
			ranks: 2,
			desc: "Увеличивает эффективность получаемого исцеления на <span class='tooltip-value'>#%</span>.",
			rankInfo: [8, 15],
		},
		{
			index: 44,
			name: "Тающая кровь",
			ranks: 3,
			desc: "При каждом использовании навыка «Благословение демона» персонаж жертвует 5% от своего макс. ОЗ и восстанавливает ОМ в количестве <span class='tooltip-value'>#%</span> от пожертвованного количества ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 150, 200],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При каждом использовании навыка «Благословение демона» персонаж жертвует 5% от своего макс. ОЗ и восстанавливает ОМ в количестве <span class="tooltip-value">250%</span> от пожертвованного количества ОЗ.</div>'],
		},
		{
			index: 46,
			name: "Серп духов",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>509 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Простое проклятье</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nНаносит 100% базового урона + 6760 ед дополнительного урона в виде кровотечения. Каждый действующий на цель эффект «Мучитель» дополнительно уменьшает показатели мастерства цели на 20%. Каждые 2 секунды цель получает урон в размере 20% от суммарного урона, нанесенного кровотечением; продолжительность – 10 сек. Кровотечение, вызываемое этим навыком, игнорирует иммунитет к кровотечению и навыки, снимающие эффекты. Получаемый урон стихии Земли зависит от мастерства и сопротивления этой стихии.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Бренное тело",
			ranks: 4,
			desc: "«Серп духов» с вероятностью <span class='tooltip-value'>#%</span> вызовет у цели головокружение на 3 сек.",
			rankInfo: [20, 40, 60, 80],
			parent: 25,
		},
		{
			index: 51,
			name: "Вспышка гнева",
			ranks: 3,
			desc: "Увеличивает скорость чтения навыка «Жгучая ненависть» на <span class='tooltip-value'>#%</span>, а базовый урон – на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 52,
			name: "Ненависть",
			ranks: 2,
			desc: "Увеличивает мастерство Земли на <span class='tooltip-value'>#</span>.",
			rankInfo: [30, 60],
		},
		{
			index: 54,
			name: "Объятия смерти",
			ranks: 1,
			desc: "Увеличивает в два раза урон, наносимый навыком «Серп духов», если количество ОЗ у цели меньше 20%. Урон от кровотечения, вызванного «Серпом духов», изменяется каждые 2 сек., увеличиваясь каждый раз на 40%; продолжительность – 6 сек.",
			rankInfo: [],
			parent: 25,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Иная сила",
			ranks: 5,
			desc: "Базовый урон навыка «Пляски лезвий» увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Базовый урон навыка «Пляски лезвий» увеличивается на <span class="tooltip-value">36%</span>.</div>'],
		},
		{
			index: 4,
			name: "Мастер-фехтовальщик",
			ranks: 5,
			ranksnw: 2,
			desc: "Увеличивает базовый урон навыка «Дьявольские вилы» на <span class='tooltip-value'>#%</span>. Навык «Дьявольские вилы» увеличивает мастерство Земли персонажа на <span class='tooltip-value'>#</span>; эффект суммируется до 5 раз; продолжительность – 15 сек. На пятом уровне таланта после каждого использования навыка “Дьявольские вилы” душегуб получает бафф, каждый стак которого уменьшает откат дьявольских вил на 0.2 секунды.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [3, 6, 9, 12, 15],
		},
		{
			index: 5,
			name: "Скованный танец",
			ranks: 3,
			desc: "Уменьшает время перезарядки навыков «Дьявольские вилы» и «Пляска лезвий» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 6,
			name: "Одержимый бесами",
			ranks: 4,
			desc: "«Бесовская яма» при каждом отражении урона увеличивает мастерство Земли душегуба на <span class='tooltip-value'>#</span> ед., эффект суммируется до 5 раз, продолжительность – 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>«Бесовская яма» при каждом отражении урона увеличивает мастерство Земли душегуба на <span class="tooltip-value">10</span> ед., эффект суммируется до 5 раз, продолжительность – 15 сек.</div>'],
		},
		{
			index: 7,
			name: "Глубокая рана",
			ranks: 3,
			desc: "«Живая рана» увеличивает урон, наносимый цели стихией земли на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 9,
			name: "Внезапное подкрепление",
			ranks: 4,
			desc: "Увеличивает базовый урон навыка «Хищные шипы» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 10,
			name: "Дикая охота",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Время перезарядки: 60 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает дальность действия навыков ближнего боя на 50 м.; продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [104, 227, 349, 470],
			rankInfo3: [20, 23, 26, 29],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">589</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Благословение</span><span class="right">Время перезарядки: 60 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает дальность действия навыков ближнего боя на 50 м.; продолжительность – <span class="tooltip-value">32</span> сек.</div>'],
		},
		{
			index: 11,
			name: "Вторжение бесов",
			ranks: 3,
			desc: "«Бесовской предел» уменьшает базовую силу атаки противников в радиусе 10 м. на <span class='tooltip-value'>#%</span>, продолжительность – 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Бесовской предел» уменьшает базовую силу атаки противников в радиусе 10 м. на <span class="tooltip-value">20%</span>, продолжительность – 15 сек.</div>'],
		},
		{
			index: 13,
			name: "Сила бездны",
			ranks: 3,
			desc: "Увеличивает время действия иммунитета к урону от навыка «Опасная бездна» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает время действия иммунитета к урону от навыка «Опасная бездна» на <span class="tooltip-value">4</span> сек.</div>'],
		},
		{
			index: 15,
			name: "Крик земли",
			ranks: 3,
			desc: "Увеличивает мастерство Земли на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Тело демона",
			ranks: 4,
			desc: "Увеличивает крит. уклонение на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [],
		},
		{
			index: 18,
			name: "Искривление пространства",
			ranks: 3,
			desc: "Если по окончании действия навыка «Дикая охота» цель, которую атаковали с помощью этого навыка, все еще находится в пределах <span class='tooltip-value'>#</span> м. от душегуба, она окажется рядом с ним, и на нее будет наложен эффект головокружения на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [15, 20, 25],
			rankInfo2: [1, 2, 3],
			parent: 6,
		},
		{
			index: 20,
			name: "Пронзающий удар",
			ranks: 3,
			desc: "Навык «Дьявольские вилы» дополнительно атакует не более 3 целей в радиусе <span class='tooltip-value'>#</span> м.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 4, 5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Навык «Дьявольские вилы» дополнительно атакует не более 3 целей в радиусе <span class="tooltip-value">6</span> м.</div>'],
			parent: 1,
		},
		{
			index: 22,
			name: "Истязатель",
			ranks: 3,
			ranksnw: 1,
			desc: "Удары, нанесенные в ближнем бою, снижают мастерство всех стихий цели на <span class='tooltip-value'>#</span> ед., эффект суммируется до 5 раз, продолжительность – 10 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Удары, нанесенные в ближнем бою, снижают мастерство всех стихий цели на <span class="tooltip-value">20</span> ед., эффект суммируется до 5 раз, продолжительность – 10 сек.</div>'],
		},
		{
			index: 24,
			name: "Измельчение",
			ranks: 3,
			desc: "Каждый эффект таланта «Истязатель» дополнительно снижает сопротивления всех стихий цели на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [5, 10, 15],
			parent: 13,
		},
		{
			index: 26,
			name: "Апостол ада",
			ranks: 3,
			desc: "Если душегуб был атакован, когда текущее количество его ОЗ меньше <span class='tooltip-value'>#%</span>, он получает эффект «Апостол ада». При использовании навыков не расходуются ОМ, а сила атаки увеличивается на <span class='tooltip-value'>#%</span>. Максимальная продолжительность – 15 сек. Эффект можно получить только один раз в 120 сек.",
			rankInfo: [30, 40, 50],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 28,
			name: "Бездонный омут",
			ranks: 4,
			desc: "Увеличивает эффективность снижения скорости чтения заклинаний навыка «Зерно трусости» на <span class='tooltip-value'>#%</span>, уменьшает эффективность замедления скорости передвижения на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [5, 10, 15, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Увеличивает эффективность снижения скорости чтения заклинаний навыка «Зерно трусости» на <span class="tooltip-value">#%</span>, уменьшает эффективность замедления скорости передвижения на <span class="tooltip-value">50%</span>.</div>'],
		},
		{
			index: 30,
			name: "Первородная сила",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Время перезарядки: 180 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает мастерство Земли на <span class='tooltip-value'>#</span> и значительно повышает базовый урон навыков ближнего боя. Продолжительность – <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [163, 290],
			rankInfo3: [100, 120],
			rankInfo4: [15, 20],
			rankInfo5: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">410</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Благословение</span><span class="right">Время перезарядки: 180 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает мастерство Земли на <span class="tooltip-value">140</span> и значительно повышает базовый урон навыков ближнего боя. Продолжительность – <span class="tooltip-value">25</span> сек.</div>'],
		},
		{
			index: 31,
			name: "Шаг между мирами",
			ranks: 5,
			ranksnw: 1,
			desc: "Увеличивает скорость передвижения и скорость передвижения верхом на <span class='tooltip-value'>#%</span> вне боя. Если персонаж атакован или сам использует атакующий навык, эффект прекращается. Эффект будет повторно наложен, если персонаж выйдет из состояния боя на 15 сек.",
			rankInfo: [20, 30, 40, 50, 60],
		},
		{
			index: 33,
			name: "Демоническая кожа",
			ranks: 3,
			desc: "Увеличивает сопротивления всех стихий на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 34,
			name: "Растущая сила",
			ranks: 3,
			ranksnw: 1,
			desc: "Снижает время перезарядки навыка «Первородная сила» на <span class='tooltip-value'>#</span> сек. Во время действия навыка «Первородная сила» сила атаки увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Снижает время перезарядки навыка «Первородная сила» на <span class="tooltip-value">80</span> сек. Во время действия навыка «Первородная сила» сила атаки увеличивается на <span class="tooltip-value">20%</span>.</div>'],
			parent: 17,
		},
		{
			index: 38,
			name: "Сила угнетения",
			ranks: 2,
			ranksnw: 1,
			desc: "Во время действия эффекта «Первородная сила» противники в радиусе <span class='tooltip-value'>#</span> м. оказываются под действием эффекта «Сила угнетения». Если цель в течение 5 сек. совершает атаку, она оказывается под действием эффекта «Головокружение» на <span class='tooltip-value'>#</span> сек. Если расстояние между персонажем и целью меньше <span class='tooltip-value'>#</span> м., время действия головокружения увеличивается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 17],
			rankInfo2: [2, 3],
			rankInfo3: [7, 8],
			rankInfo4: [2, 3],
			rankInfo5: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Во время действия эффекта «Первородная сила» противники в радиусе <span class="tooltip-value">19</span> м. оказываются под действием эффекта «Сила угнетения». Если цель в течение 5 сек. совершает атаку, она оказывается под действием эффекта «Головокружение» на <span class="tooltip-value">4</span> сек. Если расстояние между персонажем и целью меньше <span class="tooltip-value">9</span> м., время действия головокружения увеличивается на <span class="tooltip-value">4</span> сек.</div>'],
			parent: 20,
		},
		{
			index: 39,
			name: "Раненый путник",
			ranks: 3,
			desc: "Навыки «Дьявольские вилы», «Хищные шипы» и «Дух смерти» с вероятностью <span class='tooltip-value'>#%</span> снимут с персонажа эффекты паралича и замедления. Персонаж на 4 сек. получит иммунитет к параличу' и замедляющим эффектам.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 42,
			name: "Бешенство",
			ranks: 2,
			desc: "Увеличивает силу базовой атаки на <span class='tooltip-value'>#%</span>, уменьшает силу основной защиты на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
			rankInfo2: [5, 10],
		},
		{
			index: 44,
			name: "Источник злобы",
			ranks: 3,
			desc: "Увеличивает крит. защиту на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает крит. защиту на <span class="tooltip-value">16%</span>.</div>'],
		},
		{
			index: 46,
			name: "Коготь духа смерти",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>480 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 30 сек.</span>\n<span class='left'>Простая атака</span><span class='right'>Short Range</span>\n\nНаносит 150% базового урона + 8010 ед. дополнительного урона. Персонаж и цель оказываются под действием эффекта «Дух смерти», снимает все положительные эффекты, включая иммунитеты. Также запрещает накладывать положительные эффекты в течение 5 сек. Во время действия эффекта «Первородная сила» базовый урон увеличивается на 70%; «Дух смерти» уменьшает эффективность исцеления на 8о%.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Миссия убийцы",
			ranks: 4,
			desc: "Увеличивает базовый урон навыка «Коготь духа смерти» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60, 80],
			parent: 25,
		},
		{
			index: 49,
			name: "Наследие шамана",
			ranks: 3,
			desc: "«Плоть шамана» увеличивает запас ОЗ персонажа на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [],
		},
		{
			index: 51,
			name: "Злодейское сердце",
			ranks: 2,
			desc: "Увеличивает долю отражаемого урона навыком «Бесовская яма» на <span class='tooltip-value'>#%</span>. «Жгучая ненависть» не убивает персонажа, восстанавливает ОЗ в размере <span class='tooltip-value'>#%</span> от потраченного на навык количества ОЗ.",
			rankInfo: [2, 4],
			rankInfo2: [4, 8],
		},
		{
			index: 54,
			name: "Гибель богов",
			ranks: 1,
			desc: "Повышает скорость чтения навыка «Коготь духа смерти» на 100%, увеличивает базовый урон на 50%, существенно увеличивает меткость. Время действия эффекта «Дух смерти» увеличивается на 3 сек.",
			rankInfo: [],
			parent: 25,
		}
	]
];