var data = [
	// one
	[
		{
			index: 1,
			name: "Fireball Explosion",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases the damage of the burn effect caused by Fireball by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100, 125],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the damage of the burn effect caused by Fireball by <span class="tooltip-value">150%</span>.</div>'],
		},
		{
			index: 3,
			name: "Force of Protection",
			ranks: 5,
			desc: "If you are struck while using Sinister Protection, you gain the Force of Protection effect for 6 seconds. Stacks 5 times. Each stack increases your Attack by an amount equal to <span class='tooltip-value'>#%</span> of your max Mana. This effect lasts for one attack.",
			rankInfo: [0.4, 0.8, 1.2, 1.6, 2],
		},
		{
			index: 5,
			name: "Fireball Energy",
			ranks: 5,
			ranksnw: 1,
			desc: "Increases the chance for Fireball to inflict its target with a burn effect by <span class='tooltip-value'>#%</span>. Reduces the Mana cost of Fireball by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [7, 14, 21, 28, 35],
			parent: [0],
		},
		{
			index: 6,
			name: "Advanced Art of Magic",
			ranks: 2,
			desc: "Increases the duration of Art of Magic by <span class='tooltip-value'>#</span> minutes, Art of Magic reduces the consumption of fire skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: [5, 10],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Art of Magic by <span class="tooltip-value">45</span> minutes, Art of Magic reduces the consumption of fire skills by <span class="tooltip-value">15%</span>.</div>'],
		},
		{
			index: 8,
			name: "Sinister Flame",
			ranks: 3,
			desc: "Increases the Fire Mastery bonus granted by Sinister Knowledge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Flame Inspiration",
			ranks: 2,
			desc: "Reduces the cooldown of Fireball by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Fireball by <span class="tooltip-value">3</span> second(s).</div>'],
			parent: 2,
		},
		{
			index: 10,
			name: "Flame of Fury",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 3 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% of your base Attack plus <span class='tooltip-value'>#</span> bonus damage to the target and all enemies within 8 meters of it.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [250, 368, 487, 608],
			rankInfo3: [782, 1420, 2047, 2663],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">730</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Fire damage</span><span class="right">Cooldown: 3 seconds</span>\n<br><span class="left">Multi-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% of your base Attack plus <span class="tooltip-value">3268</span> bonus damage to the target and all enemies within 8 meters of it.</div>'],
		},
		{
			index: 11,
			name: "Lingering Fire",
			ranks: 4,
			desc: "Fire spells apply the Lingering Fire effect to paralyzed targets, instantly causing damage equal to <span class='tooltip-value'>#%</span> of your max Mana.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4, 5],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Fire spells apply the Lingering Fire effect to paralyzed targets, instantly causing damage equal to <span class="tooltip-value">6%</span> of your max Mana.</div>'],
		},
		{
			index: 14,
			name: "Advanced Flame of Fury",
			ranks: 4,
			desc: "Flame of Fury reduces target's Water, Fire, and Wind Resistances by <span class='tooltip-value'>#</span> for 15 seconds. Stacks 3 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Flame of Fury reduces target\'s Water, Fire, and Wind Resistances by <span class="tooltip-value">25</span> for 15 seconds. Stacks 3 times.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Swift Transform",
			ranks: 3,
			ranksnw: 3,
			desc: "Reduces the cooldown of Transform by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Transform by <span class="tooltip-value">20</span> seconds.</div>'],
		},
		{
			index: 16,
			name: "Flame Barrier",
			ranks: 3,
			desc: "Increases your Fire Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Flame of Demons",
			ranks: 3,
			ranksnw: 1,
			desc: "Rage of Demons inflicts a burn effect on the target for 5 seconds, which deals <span class='tooltip-value'>#</span> Fire damage each second.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 18,
			name: "Steady Wind Drive",
			ranks: 2,
			desc: "Increases the duration of Wind Drive by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Wind Drive by <span class="tooltip-value">6</span> seconds.</div>'],
		},
		{
			index: 19,
			name: "Conjuration",
			ranks: 1,
			desc: "Transform can be cast on monsters that were previously immune.",
			rankInfo: [],
			parent: 9,
		},
		{
			index: 21,
			name: "Call of Demons",
			ranks: 2,
			desc: "Reduces the cooldown of Rage of Demons by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2],
			parent: 11,
		},
		{
			index: 24,
			name: "Fire Knowledge",
			ranks: 6,
			desc: "Increases the damage of your offensive Fire spells by <span class='tooltip-value'>#%</span> of your max Mana.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
		},
		{
			index: 26,
			name: "Ignition Master",
			ranks: 4,
			desc: "Increases the damage of the burn effects caused by your Fire skills by <span class='tooltip-value'>#%</span>. Increases their durations by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 27,
			name: "Fire Meditation",
			ranks: 3,
			ranksnw: 1,
			desc: "Your Fire Mastery and Resistance are increased by an additional by <span class='tooltip-value'>#</span> while Magic Meditation is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Your Fire Mastery and Resistance are increased by an additional by <span class="tooltip-value">60</span> while Magic Meditation is active.</div>'],
		},
		{
			index: 29,
			name: "Reflex Mirror",
			ranks: 3,
			desc: "Fire Shield blinds attackers, reducing their Accuracy by <span class='tooltip-value'>#</span> for 5 seconds. Stacks 10 times.",
			rankInfo: [3, 6, 9],
			parent: [19],
		},
		{
			index: 30,
			name: "Fire Shield",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nIncreases your Physical and Fire Resistances by <span class='tooltip-value'>#</span> and your Crit Chance by <span class='tooltip-value'>#%</span> for 5 minutes. Increases your Fire Mastery by <span class='tooltip-value'>#</span> for 10 seconds when you are attacked. Stacks 8 times. Cannot be used with Ice Shield.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [3, 5],
			rankInfo5: [5, 7],
			rankInfo6: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">510</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 20 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases your Physical and Fire Resistances by <span class="tooltip-value">60</span> and your Crit Chance by <span class="tooltip-value">7%</span> for 5 minutes. Increases your Fire Mastery by <span class="tooltip-value">9</span> for 10 seconds when you are attacked. Stacks 8 times. Cannot be used with Ice Shield.</div>'],
		},
		{
			index: 31,
			name: "Hasted Burning",
			ranks: 2,
			desc: "Increases the damage of your burn effects by <span class='tooltip-value'>#%</span> and reduces their durations by <span class='tooltip-value'>#%</span> while Magic Meditation is active.",
			rankInfo: [100, 200],
			rankInfo2: [20, 40],
			parent: [17],
		},
		{
			index: 33,
			name: "Hasted Flames",
			ranks: 3,
			desc: "Reduces the cooldowns of Fireball, Flame of Fury, and Rage of Demons by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldowns of Fireball, Flame of Fury, and Rage of Demons by <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 34,
			name: "Infuriated Mind",
			ranks: 2,
			desc: "Increases the Crit damage of Flame of Fury and Rage of Demons by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the Crit damage of Flame of Fury and Rage of Demons by <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 36,
			name: "Vaporize",
			ranks: 3,
			desc: "Fireball has a <span class='tooltip-value'>#%</span> chance to reset the cooldowns of Fireball, Flame of Fury, and Rage of Demons.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Master of Heat",
			ranks: 3,
			desc: "When your Mana is over 50%, your offensive Fire skills inflict the Melted Armor effect on the target. Melted Armor reduces the target's Defense by <span class='tooltip-value'>#</span> for 10 seconds. Stacks 10 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>When your Mana is over 50%, your offensive Fire skills inflict the Melted Armor effect on the target. Melted Armor reduces the target\'s Defense by <span class="tooltip-value">60</span> for 10 seconds. Stacks 10 times.</div>'],
		},
		{
			index: 39,
			name: "Magic Dispel",
			ranks: 3,
			desc: "Magic Purge reduces the target's Fire Resistance by <span class='tooltip-value'>#</span> for 20 seconds, and drains an amount of the target's Mana equal to <span class='tooltip-value'>#%</span> of your Attack.",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 42,
			name: "Breath of Inferno",
			ranks: 3,
			desc: "Increases the base damage of Fireball, Rage of Demons, and Flame of Fury by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 43,
			name: "Evoke",
			ranks: 2,
			desc: "Grants your Fire spells a <span class='tooltip-value'>#%</span> chance to increase your Crit damage by 2%. Stacks 10 times and lasts for 10 seconds.",
			rankInfo: [50, 100],
		},
		{
			index: 46,
			name: "Spark Burst",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>1346 Mana</span><span class='right'>Cast time: 5 seconds</span>\n<span class='left'>Fire damage</span><span class='right'>Cooldown: 25 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 200% of your Attack plus 5229 bonus damage to enemies within 10 meters of the target. Enemies that are struck will be stunned for 1-5 second(s).",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Meteor",
			ranks: 4,
			desc: "Spark Burst's Base Attack is increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [25, 50, 75, 100],
			parent: 28,
		},
		{
			index: 49,
			name: "Ancalis Blessing",
			ranks: 3,
			desc: "Flame of Fury and Rage of Demons have a <span class='tooltip-value'>#%</span> chance to reset the cooldown on Spark Burst. Base Attack bonus for Flame of Fury and Rage of Demons increased by <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 10],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 51,
			name: "Destruction",
			ranks: 2,
			desc: "Crit Strikes from AoE fire attacks (Flame of Fury, Rage of Demons, Spark Burst) will reduce target's Crit Dodge by <span class='tooltip-value'>#%</span> for 30 seconds.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Elemental Dominator",
			ranks: 1,
			desc: "Spark Burst's casting time is reduced by 2 seconds and stuns targets for 2 seconds.",
			rankInfo: [],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Thunder Paralyze",
			ranks: 4,
			ranksnw: 1,
			desc: "Increases Thunderclap's chance to paralyze an enemy by <span class='tooltip-value'>#%</span> and reduces its Mana cost by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [5, 10, 15, 20],
		},
		{
			index: 2,
			name: "Magic Fountain",
			ranks: 3,
			desc: "Art of Magic increases your max Mana by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Art of Magic increases your max Mana by an additional <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 3,
			name: "Lightning Fury",
			ranks: 3,
			desc: "Increases the base damage of Thunderclap by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45], 
		},
		{
			index: 5,
			name: "Shock Expansion",
			ranks: 4,
			ranksnw: 2,
			desc: "Increases the range of Thunderclap by <span class='tooltip-value'>#%</span>. Increases the maximum number of targets struck by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 60, 90, 120],
			rankInfo2: [2, 4, 6, 8],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the range of Thunderclap by <span class="tooltip-value">150%</span>. Increases the maximum number of targets struck by <span class="tooltip-value">10</span>.</div>'],
			parent: [0],
		},
		{
			index: 7,
			name: "Soul Contract",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the duration of Sinister Protection by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Sinister Protection by <span class="tooltip-value">30</span> seconds.</div>'],
		},
		{
			index: 8,
			name: "Sinister Wind",
			ranks: 3,
			desc: "Increases the Wind Mastery bonus granted by Sinister Knowledge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Rolling Thunder",
			ranks: 4,
			desc: "Increases the Crit Chance of Thunderclap by <span class='tooltip-value'>#%</span>. This effect is doubled while Thunder Tempest is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the Crit Chance of Thunderclap by <span class="tooltip-value">7.5%</span>. This effect is doubled while Thunder Tempest is active.</div>'],
			parent: 3,
		},
		{
			index: 10,
			name: "Streak of Lightning",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Wind damage</span><span class='right'>Cooldown: <span class='tooltip-value'>#</span> seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% of your Attack plus <span class='tooltip-value'>#</span> bonus damage to targets in a straight line in front of you within 21 meters. Has a 25% chance to interrupt the target's casting.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [259, 382, 506, 631],
			rankInfo3: [8, 7, 6, 5],
			rankInfo4: [1339, 2362, 3366, 4351],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">757</span> Mana</span><span class="right">Cast time: 2 seconds</span>\n<br><span class="left">Wind damage</span><span class="right">Cooldown: <span class="tooltip-value">4</span> seconds</span>\n<br><span class="left">Multi-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% of your Attack plus <span class="tooltip-value">5319</span> bonus damage to targets in a straight line in front of you within 21 meters. Has a 25% chance to interrupt the target\'s casting.</div>'],
		},
		{
			index: 11,
			name: "Energy of Protection",
			ranks: 3,
			desc: "Reduces the amount of Mana drained per point of damage that Sinister Protection absorbs by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 50],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the amount of Mana drained per point of damage that Sinister Protection absorbs by <span class="tooltip-value">60%</span>.</div>'],
			parent: 4,
		},
		{
			index: 14,
			name: "Advanced Shock Hit",
			ranks: 4,
			desc: "Streak of Lightning has a <span class='tooltip-value'>#%</span> chance to paralyze and knock back targets.",
			rankInfo: [25, 50, 75, 100],
			parent: 7,
		},
		{
			index: 15,
			name: "High Voltage",
			ranks: 2,
			ranksnw: 1,
			desc: "Your offensive Wind spells have a <span class='tooltip-value'>#%</span> chance to generate a High Voltage charge. Once 8 charges have been generated, you receive the Thunder Tempest buff. Thunder Tempest increases the Crit Chance of your Wind spells and shortens their cooldowns. Lasts 10 seconds.",
			rankInfo: [50, 100],
		},
		{
			index: 16,
			name: "Wind Mastery",
			ranks: 4,
			ranksnw: 3,
			desc: "Increases your Wind Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Advanced Transform",
			ranks: 3,
			desc: "Increases the duration of Transform by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 18,
			name: "Swift Wind Drive",
			ranks: 2,
			desc: "Wind Drive increases your movement speed by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Wind Drive increases your movement speed by an additional <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 20,
			name: "Thunder Focusing",
			ranks: 6,
			desc: "Increases the damage of your offensive Wind spells by <span class='tooltip-value'>#%</span> of your max Mana.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
			parent: 11,
		},
		{
			index: 21,
			name: "Advanced Paralyze",
			ranks: 2,
			desc: "Your paralyze effects reduce the target's Evasion by <span class='tooltip-value'>#%</span> and its Wind Resistance by <span class='tooltip-value'>#</span>. Their durations are increased by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100],
			rankInfo2: [10, 20],
			rankInfo3: [3, 6],
			rankInfo4: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Your paralyze effects reduce the target\'s Evasion by <span class="tooltip-value">150%</span> and its Wind Resistance by <span class="tooltip-value">30</span>. Their durations are increased by <span class="tooltip-value">9</span> seconds.</div>'],
		},
		{
			index: 23,
			name: "Sustained Energy",
			ranks: 4,
			desc: "The duration of the Thunder Tempest effect is increased by <span class='tooltip-value'>#</span> second(s). Each stack of High Voltage increases your movement speed by 5%, movement speed is increased by 50% with Thunder Tempest effect.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>The duration of the Thunder Tempest effect is increased by <span class="tooltip-value">5</span> second(s). Each stack of High Voltage increases your movement speed by 5%, movement speed is increased by 50% with Thunder Tempest effect.</div>'],
			parent: 10,
		},
		{
			index: 26,
			name: "Meditation of Wind",
			ranks: 3,
			desc: "Your Wind Mastery and Resistance are increased by an additional by <span class='tooltip-value'>#</span> while Magic Meditation is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Your Wind Mastery and Resistance are increased by an additional by <span class="tooltip-value">60</span> while Magic Meditation is active.</div>'],
		},
		{
			index: 28,
			name: "Thunder Barrier",
			ranks: 3,
			desc: "Increases your Wind Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 29,
			name: "Static Field",
			ranks: 3,
			ranksnw: 1,
			desc: "Sinister Force has a <span class='tooltip-value'>#%</span> chance to paralyze targets within range every 4 seconds.",
			rankInfo: [40, 70, 100],
			parent: 20,
		},
		{
			index: 30,
			name: "Sinister Force",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>50% of current Mana</span><span class='right'>Cast time: 3 seconds</span>\n<span class='left'>Wind</span><span class='right'>Cooldown: 180 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: None</span>\n\nCosts 50% of your current Mana. Within <span class='tooltip-value'>#</span> meters, it drains the Mana of up to <span class='tooltip-value'>#</span> targets. The amount of Mana lost is equal to 30% of the target’s current Mana. Mana Explosion can be used once every 20 seconds. For 20 seconds, targets that attack you will lose Mana equal to 1.0% of your max Mana. This ability can only be used in PvP.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [12, 15],
			rankInfo3: [20, 25],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left">50% of current Mana</span><span class="right">Cast time: 3 seconds</span>\n<br><span class="left">Wind</span><span class="right">Cooldown: 180 seconds</span>\n<br><span class="left">Multi-target curse</span><span class="right">Range: None</span>\n\n<br><br>Costs 50% of your current Mana. Within <span class="tooltip-value">18</span> meters, it drains the Mana of up to <span class="tooltip-value">30</span> targets. The amount of Mana lost is equal to 30% of the target\'s current Mana. Mana Explosion can be used once every 20 seconds. For 20 seconds, targets that attack you will lose Mana equal to 1.0% of your max Mana. This ability can only be used in PvP.</div>'],
		},
		{
			index: 33,
			name: "Sinister Constriction",
			ranks: 4,
			desc: "Increases the amount of Mana drained from attackers by <span class='tooltip-value'>#%</span> while Sinister Force is active. Silences targets when their Mana drops below 20% for <span class='tooltip-value'>#</span> seconds. (This effect can occur once every 20 seconds). Restores an amount of your Mana equal to the amount of Mana drained from the target. This effect can occur up to 20 times.",
			rankInfo: [50, 100, 150, 200],
			rankInfo2: [1, 2, 3, 4],
			parent: 19,
		},
		{
			index: 35,
			name: "Icebreak",
			ranks: 2,
			desc: "Your offensive Wind spells inflict the Broken Ice effect on frozen targets. For the next 15 seconds, the target takes <span class='tooltip-value'>#%</span> more damage when attacked.",
			rankInfo: [5, 10],
		},
		{
			index: 37,
			name: "Windblast",
			ranks: 3,
			desc: "Grants your offensive Wind spells a <span class='tooltip-value'>#%</span> chance to interrupt the target's casting.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 38,
			name: "Blessing of Thunder",
			ranks: 2,
			desc: "Reduces the cooldowns of Thunderclap and Streak of Lightning by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [1, 2],
		},
		{
			index: 39,
			name: "Dispelling Wind",
			ranks: 3,
			desc: "Grants Magic Purge a <span class='tooltip-value'>#%</span> chance to dispel an additional buff from the target.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 42,
			name: "Amplified Paralyze",
			ranks: 2,
			desc: "Grants Nature's Fury a <span class='tooltip-value'>#%</span> chance to inflict a powerful paralyze effect on the target, which reduces its Accuracy by 60 and its Evasion by 40 for 15 seconds.",
			rankInfo: [50, 100],
		},
		{
			index: 43,
			name: "Thunder Tempest",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>5% of max Mana</span><span class='right'>Cast Time: Instant</span>\n<span class='left'>Wind damage</span><span class='right'>Cooldown: 90 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nGrants the Thunder Tempest buff.",
			rankInfo: ['<span class="req">Requires character to be Lv70</span>\n\n'],
		},
		{
			index: 46,
			name: "Purgatory of Lightning",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>1064 Mana</span><span class='right'>Cast time: 3 seconds</span>\n<span class='left'>Wind damage</span><span class='right'>Cooldown: 15 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: None</span>\n\nStrikes targets within 16 meters six times. Each strike deals 50% of your base Attack plus 818 bonus damage. Has a 40% chance to paralyze affected targets.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Live Wire",
			ranks: 4,
			desc: "Targets hit by Purgatory of Lightning have a <span class='tooltip-value'>#%</span> chance to suffer Electric Shock. Purgatory of Lightning will ensnare afflicted targets for 1-5 seconds based on the stack size. Each stack increases Purgatory of Lightning's Base Attack by 1%. Electric Shock lasts 20 seconds, stacks 5 times.",
			rankInfo: [10, 20, 30, 40],
			parent: 28,
		},
		{
			index: 49,
			name: "Purity",
			ranks: 3,
			desc: "Reduces the cooldown of Magic Purge by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 51,
			name: "Electrical Inhibition",
			ranks: 2,
			desc: "Paralyzed targets suffer a <span class='tooltip-value'>#%</span> reduced casting speed and a <span class='tooltip-value'>#%</span> reduction in movement speed for lasts 15 seconds.",
			rankInfo: [5, 10],
			rankInfo2: [10, 20],
		},
		{
			index: 54,
			name: "Raging Shock",
			ranks: 1,
			desc: "Increases the Base Attack bonus of Purgatory of Lightning by 20%, and grants an additional 50% chance to trigger the Electric Shock effect.",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Precision of Water",
			ranks: 5,
			ranksnw: 3,
			desc: "Increases the Accuracy of Ice Arrow by <span class='tooltip-value'>#</span> and its base damage by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [5, 10, 15, 20, 25],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the Accuracy of Ice Arrow by <span class="tooltip-value">18</span> and its base damage by <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 2,
			name: "Chilling Ice",
			ranks: 5,
			ranksnw: 1,
			desc: "Ice Arrow applies the Chilling Ice effect, which reduces the target's Water and Fire Resistances by <span class='tooltip-value'>#</span> for 15 seconds. Stacks 10 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Ice Arrow applies the Chilling Ice effect, which reduces the target\'s Water and Fire Resistances by <span class="tooltip-value">12</span> for 15 seconds. Stacks 10 times.</div>'],
		},
		{
			index: 5,
			name: "Ice Inspiration",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduces the cooldown of Ice Arrow by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Ice Arrow by <span class="tooltip-value">3</span> second(s).</div>'],
			parent: [0],
		},
		{
			index: 7,
			name: "Extremity Dimension",
			ranks: 4,
			desc: "Increases the duration of Ice Barrier by <span class='tooltip-value'>#</span> seconds. Restores <span class='tooltip-value'>#%</span> of your Health per second while Ice Barrier is active.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Increases the duration of Ice Barrier by <span class="tooltip-value">7.5</span> seconds. Restores <span class="tooltip-value">5%</span> of your Health per second while Ice Barrier is active.</div>'],
		},
		{
			index: 8,
			name: "Sinister Stream",
			ranks: 3,
			desc: "Increases the Water Mastery bonus granted by Sinister Knowledge by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Ice Crystal",
			ranks: 5,
			desc: "Grants Ice Arrow a <span class='tooltip-value'>#%</span> chance to freeze targets for 6 seconds. Frozen targets are paralyzed and silenced, but also have their Defense increased by 15%.",
			rankInfo: [3, 6, 9, 12, 15],
			parent: 2,
		},
		{
			index: 10,
			name: "Ice Spike",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Water damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% of your base Attack plus <span class='tooltip-value'>#</span> bonus damage. This skill applies 3 stacks of Chilling Ice when it lands a Crit. If the target is already frozen, it will deal <span class='tooltip-value'>#</span> bonus damage.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [168, 240, 313, 386],
			rankInfo3: [991, 1650, 2297, 2932],
			rankInfo4: [200, 300, 400, 500],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">460</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Water damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% of your base Attack plus <span class="tooltip-value">3555</span> bonus damage. This skill applies 3 stacks of Chilling Ice when it lands a Crit. If the target is already frozen, it will deal <span class="tooltip-value">600</span> bonus damage.</div>'],
			parent: 1,
		},
		{
			index: 11,
			name: "Drake Skin",
			ranks: 3,
			desc: "Sinister Protection creates an additional protective shield for <span class='tooltip-value'>#</span> second(s). The shield absorbs 100% of incoming damage, and it can absorb a total amount of damage equal to <span class='tooltip-value'>#%</span> of your max Mana.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 13,
			name: "Magic Suppression",
			ranks: 2,
			desc: "Transform reduces the target's movement speed by <span class='tooltip-value'>#%</span> and its Health recovery rate by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [30, 60],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Transform reduces the target\'s movement speed by <span class="tooltip-value">90%</span> and its Health recovery rate by <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 14,
			name: "Advanced Ice Spike",
			ranks: 5,
			desc: "Increases the bonus damage Ice Spike deals to frozen targets by <span class='tooltip-value'>#%</span> and its Crit Chance by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: [2, 4, 6, 8, 10],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the bonus damage Ice Spike deals to frozen targets by <span class="tooltip-value">120%</span> and its Crit Chance by <span class="tooltip-value">12%</span>.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Advanced Wind Drive",
			ranks: 2,
			desc: "Wind Drive can dispel <span class='tooltip-value'>#</span> effects.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['slow', 'slow and ensnare'],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Wind Drive can dispel <span class="tooltip-value">slow, ensnare and bleed</span> effects.</div>'],
		},
		{
			index: 18,
			name: "Harsh Freeze",
			ranks: 5,
			desc: "Ice Arrow and Ice Spike each have a <span class='tooltip-value'>#%</span> chance to trigger the Harsh Freeze effect for 20 seconds. This effect will disappear after one use. While Harsh Freeze is active, your next Ice Spike has a 100% chance to land a Crit and your next Ice Arrow has a 100% chance to freeze the target.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Ice Arrow and Ice Spike each have a <span class="tooltip-value">12%</span> chance to trigger the Harsh Freeze effect for 20 seconds. This effect will disappear after one use. While Harsh Freeze is active, your next Ice Spike has a 100% chance to land a Crit and your next Ice Arrow has a 100% chance to freeze the target.</div>'],
		},
		{
			index: 20,
			name: "Ice Concentration",
			ranks: 6,
			desc: "Increases the damage of your offensive Water spells by <span class='tooltip-value'>#%</span> of your max Mana.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
		},
		{
			index: 21,
			name: "Advanced Frost Realm",
			ranks: 2,
			ranksnw: 1,
			desc: "Increases the duration of Frost Realm's freeze effect by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the duration of Frost Realm\'s freeze effect by <span class="tooltip-value">3</span> second(s).</div>'],
		},
		{
			index: 23,
			name: "Glacier Shield",
			ranks: 3,
			desc: "Increases your Water Resistance by <span class='tooltip-value'>#</span> and your Defense by <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 25,
			name: "Boundary",
			ranks: 4,
			desc: "Targets frozen by Frost Realm continuously lose <span class='tooltip-value'>#%</span> of their max Mana. Increases the base damage of Frost Realm by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [15, 30, 45, 60],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Targets frozen by Frost Realm continuously lose <span class="tooltip-value">5%</span> of their max Mana. Increases the base damage of Frost Realm by <span class="tooltip-value">75%</span>.</div>'],
			parent: 13,
		},
		{
			index: 26,
			name: "Piercing Cold",
			ranks: 3,
			desc: "Increases the bonus damage of Ice Arrow and Ice Spike by <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 30,
			name: "Ice Shield",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 20 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nIncreases your Physical and Water Resistances by <span class='tooltip-value'>#</span> and your Defense by <span class='tooltip-value'>#</span>. Reduces all incoming damage by <span class='tooltip-value'>#%</span>. Lasts for 5 minutes. When you're attacked, the attacker's speed is reduced by 10%. Lasts for 5 seconds. Stacks 5 times. Cannot be used together with Fire Shield.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [50, 80],
			rankInfo5: [3, 5],
			rankInfo6: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">510</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 20 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases your Physical and Water Resistances by <span class="tooltip-value">60</span> and your Defense by <span class="tooltip-value">110</span>. Reduces all incoming damage by <span class="tooltip-value">7%</span>. Lasts for 5 minutes. When you\'re attacked, the attacker\'s speed is reduced by 10%. Lasts for 5 seconds. Stacks 5 times. Cannot be used together with Fire Shield.</div>'],
		},
		{
			index: 31,
			name: "Frozen Shield",
			ranks: 3,
			desc: "Ice Shield increases your Defense by an additional <span class='tooltip-value'>#%</span>. The duration of the slow effect is increased by <span class='tooltip-value'>#</span> second(s).",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
			parent: 17,
		},
		{
			index: 33,
			name: "Water Meditation",
			ranks: 2,
			desc: "Reduces the cooldowns of Ice Arrow, Ice Spike, and Frost Realm by <span class='tooltip-value'>#%</span> while Magic Meditation is active.",
			rankInfo: [30, 60],
		},
		{
			index: 34,
			name: "Extended Harsh Freeze",
			ranks: 2,
			desc: "The Harsh Freeze effect has a <span class='tooltip-value'>#%</span> chance to remain active after being used.",
			rankInfo: [15, 30],
		},
		{
			index: 36,
			name: "Ice Mastery",
			ranks: 3,
			desc: "Increases your Water Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 38,
			name: "Blizzard",
			ranks: 3,
			ranksnw: 3,
			desc: "Fury of Ice has a <span class='tooltip-value'>#%</span> chance to inflict the target with the Ice Crystal effect. Stuns the target for 3 seconds and removes burn effects.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 39,
			name: "Ice Storm Spirit",
			ranks: 2,
			desc: "Increases the base damage of Fury of Ice by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			parent: 22,
		},
		{
			index: 42,
			name: "Frozen Prison",
			ranks: 2,
			desc: "Ice Arrow and Ice Spike dispel burn and paralyze effects on the target and inflict the Frozen Prison effect for 10 seconds. Frozen Prison reduces the target's Attack, Defense and movement speed by <span class='tooltip-value'>#%</span>, <span class='tooltip-value'>#%</span> and 25% respectively.",
			rankInfo: [10, 20],
			rankInfo2: [10, 20],
		},
		{
			index: 43,
			name: "Dispelling Water",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduces the cooldowns of Frost Realm and Ice Edge by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10],
		},
		{
			index: 47,
			name: "Ice Edge",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>775 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Water damage</span><span class='right'>Cooldown: 45 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 18 meters</span>\n\nStrikes up to 16 targets within 10 meters. Deals 100% of your Attack plus 1852 bonus damage. Inflicts affected targets with a freeze effect that increases their Defense by 5% and renders them unable to move. The freeze effect ends after the target is struck twice.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
			parent: 25,
		},
		{
			index: 48,
			name: "Winter",
			ranks: 4,
			ranksnw: 1,
			desc: "Reduces Ice Resistance of targets affected by Ice Edge by <span class='tooltip-value'>#</span> for 12 seconds.",
			rankInfo: [20, 40, 60, 80],
			parent: 26,
		},
		{
			index: 49,
			name: "Frostbite",
			ranks: 2,
			desc: "Arctic Rage's Crit Chance is increased by <span class='tooltip-value'>#%</span>. Crit Strikes trigger the Frostbite effect, causing the target to Bleed <span class='tooltip-value'>#</span> Health per second for 5 seconds.",
			rankInfo: [3, 6],
			rankInfo2: [546, 1092],
		},
		{
			index: 51,
			name: "Fragile",
			ranks: 3,
			desc: "Targets ensnared by Ice Edge or Frost Realm suffer a <span class='tooltip-value'>#%</span> reduction in Crit Dodge.",
			rankInfo: [7, 14, 21],
		},
		{
			index: 56,
			name: "Deep Freeze",
			ranks: 1,
			desc: "Ice Edge's Base Attack is increased by 50%. Using Fury of Ice after casting Ice Edge will grant you immunity to Bleed damage and reflected damage for 12 seconds.",
			rankInfo: [],
			parent: 27,
		},
	]
];