var data = [
	// one
	[
		{
			index: 1,
			name: "Заживление",
			ranks: 5,
			ranksnw: 2,
			desc: "Количество ОЗ, восполняемое навыком «Врачевание», увеличивается на <span class='tooltip-value'>#</span> + <span class='tooltip-value'>#%</span> от максимального количества ОМ жреца.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 200, 400, 600, 800],
			rankInfo2: [2, 3, 4, 5, 6],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Количество ОЗ, восполняемое навыком «Врачевание», увеличивается на <span class="tooltip-value">300</span> + <span class="tooltip-value">7%</span> от максимального количества ОМ жреца.</div>'],
		},
		{
			index: 3,
			name: "Поток жизни",
			ranks: 5,
			desc: "Увеличивает максимальное количество ОЗ, повышаемое навыком «Молитва жизни» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивает максимальное количество ОЗ, повышаемое навыком «Молитва жизни» на <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 6,
			name: "Сила молитвы",
			ranks: 3,
			desc: "Длительность действия навыка «Милость судьбы» увеличивается на <span class='tooltip-value'>#</span> мин. Эффект от исцеляющих навыков увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 7,
			name: "Сияние",
			ranks: 3,
			ranksnw: 1,
			desc: "Увеличивает количество здоровья, восстанавливаемое навыком «Провидение», на <span class='tooltip-value'>#%</span> и уменьшает время его перезарядки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает количество здоровья, восстанавливаемое навыком «Провидение», на <span class="tooltip-value">16%</span> и уменьшает время его перезарядки на <span class="tooltip-value">80</span> сек.</div>'],
		},
		{
			index: 8,
			name: "Источник магии",
			ranks: 4,
			desc: "Увеличивает максимальное количество ОМ на <span class='tooltip-value'>#%</span> и дополнительно на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [200, 400, 600, 800],
		},
		{
			index: 9,
			name: "Мастер-целитель",
			ranks: 4,
			desc: "Уменьшает время перезарядки навыка «Врачевание» на <span class='tooltip-value'>#</span> сек. Уменьшает расход ОМ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: [5, 10, 15, 20],
			parent: [0],
		},
		{
			index: 10,
			name: "Небесный свет",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 4 сек.</span>\n<span class='left'>Лечение</span><span class='right'>Время перезарядки: 8 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nВ течение 4 сек. восстанавливает <span class='tooltip-value'>#</span> ОЗ цели. При последнем исцелении восстанавливается в два раза больше ОЗ. Макс. здоровье цели увеличивается на <span class='tooltip-value'>#</span> ед. на 10 сек. С вероятностью 4% количество восполняемых ОЗ может удвоится.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [424, 689, 949, 1204],
			rankInfo3: ['719-794', '1072-1184', '1428-1577', '1787-1973'],
			rankInfo4: [5000, 7000, 9000, 11000],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">1456</span> ОМ</span><span class="right">Чтение: 4 сек.</span>\n<br><span class="left">Лечение</span><span class="right">Время перезарядки: 8 сек.</span>\n<br><span class="left">Благословение</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>В течение 4 сек. восстанавливает <span class="tooltip-value">2148-2372</span> ОЗ цели. При последнем исцелении восстанавливается в два раза больше ОЗ. Макс. здоровье цели увеличивается на <span class="tooltip-value">6000</span> ед. на 10 сек. С вероятностью 4% количество восполняемых ОЗ может удвоится.</div>'],
		},
		{
			index: 11,
			name: "Дар богов",
			ranks: 2,
			desc: "В течение <span class='tooltip-value'>#</span> сек. после применения умения «Провидение», эффекты исцеления на цели увеличиваются на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
			rankInfo2: [25, 50],
			parent: 3,
		},
		{
			index: 15,
			name: "Мгновенное исцеление",
			ranks: 3,
			ranksnw: 2,
			desc: "Во время восстановления здоровья навыком «Исцеляющий свет» количество восполняемых ОЗ при первом лечении увеличивается на <span class='tooltip-value'>#</span> ед. Среднее количество восполняемых ОЗ повышается на <span class='tooltip-value'>#%</span> от максимального количества ОМ жреца.",
			rankInfo: [100, 200, 300],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 16,
			name: "Спокойствие",
			ranks: 4,
			desc: "Расход ОМ на исцеляющие навыки снижается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Расход ОМ на исцеляющие навыки снижается на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 18,
			name: "Чудесное исцеление",
			ranks: 3,
			desc: "Эффект от лечения навыком «Небесный свет» увеличивается на <span class='tooltip-value'>#%</span>, вероятность прерывания уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [25, 50, 75],
			parent: 6,
		},
		{
			index: 20,
			name: "Дисциплина",
			ranks: 4,
			desc: "Уменьшает угрозу атаки монстров после использования лечения на <span class='tooltip-value'>#%</span>. Снижает вероятность прерывания исцеляющих навыков на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [15, 30, 45, 60],
		},
		{
			index: 21,
			name: "Добавка маны",
			ranks: 4,
			desc: "При применении навыка «Врачевание» к персонажу, находящемуся под действием «Исцеляющего света», его ОМ восстанавливаются в размере <span class='tooltip-value'>#%</span> от максимального количества ОМ жреца.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>При применении навыка «Врачевание» к персонажу, находящемуся под действием «Исцеляющего света», его ОМ восстанавливаются в размере <span class="tooltip-value">5%</span> от максимального количества ОМ жреца.</div>'],
		},
		{
			index: 22,
			name: "Священная сила",
			ranks: 3,
			desc: "После применения навыков «Врачевание», «Целительный свет» или «Небесный свет», базовый урон жреца увеличивается на <span class='tooltip-value'>#%</span>, длительность - 20 сек. Эффект суммируется до 3 раз, исчезает после получения урона.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 8, 10],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>После применения навыков «Врачевание», «Целительный свет» или «Небесный свет», базовый урон жреца увеличивается на <span class="tooltip-value">12%</span>, длительность - 20 сек. Эффект суммируется до 3 раз, исчезает после получения урона.</div>'],
		},
		{
			index: 23,
			name: "Восстановление",
			ranks: 2,
			desc: "Продлевает время действия навыка «Исцеление» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4],
			parent: 8,
		},
		{
			index: 25,
			name: "Гордое сердце",
			ranks: 3,
			ranksnw: 1,
			desc: "Длительность действия навыка «Молитва защиты» увеличивается на <span class='tooltip-value'>#</span> мин. Расход маны уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 26,
			name: "Просветление",
			ranks: 2,
			desc: "Количество ОЗ и ОМ воскрешенного жрецом персонажа увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Количество ОЗ и ОМ воскрешенного жрецом персонажа увеличивается на <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 28,
			name: "Дух исцеления",
			ranks: 3,
			desc: "Дополнительно повышает вероятность двойного лечения для навыков «Врачевание», «Исцеляющий свет» и «Небесный свет» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 30,
			name: "Священный щит",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 30 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nЗащищает цель щитом, поглащающим 80% урона в течение <span class='tooltip-value'>#</span> сек. Макс. урон, который может поглатить щит, составляет <span class='tooltip-value'>#%</span> от максимального здоровья цели.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [702, 861],
			rankInfo3: [20, 21],
			rankInfo4: [60, 80],
			rankInfo5: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">1028</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 30 сек.</span>\n<br><span class="left">Благословение</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Защищает цель щитом, поглащающим 80% урона в течение <span class="tooltip-value">22</span> сек. Макс. урон, который может поглатить щит, составляет <span class="tooltip-value">100%</span> от максимального здоровья цели.</div>'],
		},
		{
			index: 31,
			name: "Быстрое исцеление",
			ranks: 3,
			desc: "Использование навыка «Врачевание» дает <span class='tooltip-value'>#%</span>-ную вероятность восстановить <span class='tooltip-value'>#%</span> ОЗ цели, находящейся под действием навыка «Исцеляющий свет», но при этом действие навыка прекращается.",
			rankInfo: [20, 40, 60],
			rankInfo2: [200, 250, 300],
		},
		{
			index: 33,
			name: "Доспехи света",
			ranks: 2,
			desc: "Эффект от «Молитвы защиты» усиливается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Эффект от «Молитвы защиты» усиливается на <span class="tooltip-value">9%</span>.</div>'],
			parent: 15,
		},
		{
			index: 34,
			name: "Щит бессмертия",
			ranks: 3,
			desc: "Общее количество урона, поглащаемого навыком «Священный щит», увеличивается на <span class='tooltip-value'>#%</span> + <span class='tooltip-value'>#%</span> от максимального количества ОМ жреца.",
			rankInfo: [20, 40, 60],
			rankInfo2: [1, 2, 3],
			parent: 18,
		},
		{
			index: 35,
			name: "Вдохновение",
			ranks: 3,
			desc: "С <span class='tooltip-value'>#%</span>-ной вероятностью исцеляющие навыки могут ввести жреца в состояние «Вдохновения», в котором затраты ОМ на исцеляющие навыки сокращаются на 10%. Длительность - 10 сек. Суммируется до трех раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>С <span class="tooltip-value">40%</span>-ной вероятностью исцеляющие навыки могут ввести жреца в состояние «Вдохновения», в котором затраты ОМ на исцеляющие навыки сокращаются на 10%. Длительность - 10 сек. Суммируется до трех раз.</div>'],
		},
		{
			index: 38,
			name: "Добрая воля",
			ranks: 2,
			desc: "Количество лечения увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
		},
		{
			index: 40,
			name: "Великий дар",
			ranks: 3,
			desc: "Исцеляющие навыки, а также бонусы к навыкам от талантов, усиливаются на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 41,
			name: "Благословение ангела",
			ranks: 3,
			desc: "Увеличивает объем исцеления от «Ангельской песни» на <span class='tooltip-value'>#%</span> и сокращает время перезарядки навыка «Провидение» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 42,
			name: "Покровительство",
			ranks: 2,
			desc: "Уменьшает время восстановления навыков «Небесный свет» и «Священный щит» на <span class='tooltip-value'>#</span> сек. и <span class='tooltip-value'>#</span> сек. соответственно. Расход маны уменьшается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [3, 6],
			rankInfo3: [15, 30],
		},
		{
			index: 46,
			name: "Свет очищения",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>378 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 8 сек.</span>\n<span class='left'>Благословение</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nСнимает один негативный эффект с дружественной цели.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Кристальная чистота",
			ranks: 4,
			desc: "Уменьшает время восстановления навыка «Свет очищения» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3, 4],
			parent: 27,
		},
		{
			index: 49,
			name: "Набожность",
			ranks: 3,
			desc: "Усиливает эффект повышения максимального количества ОЗ навыка «Небесный свет» на <span class='tooltip-value'>#%</span>; увеличивает дальность действия навыка «Провидение» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
			rankInfo2: [30, 60, 90],
		},
		{
			index: 51,
			name: "Великодушие",
			ranks: 2,
			desc: "Во время действия эффекта «Милосердие» увеличивает дальность действия навыков «Врачевание», «Небесный свет» и «Исцеляющий свет» на <span class='tooltip-value'>#</span> м.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Узы магии",
			ranks: 1,
			desc: "Уменьшает время восстановления навыка «Свет очищения» на 4 сек. и дает иммунитет к эффектам контроля во время применения навыка.",
			rankInfo: [],
			parent: 27,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Обжигающий огонь",
			ranks: 5,
			ranksnw: 2,
			desc: "Урон от навыка «Небесный огонь» увеличивается на <span class='tooltip-value'>#</span> ед. + <span class='tooltip-value'>#%</span> от мастерства Света жреца.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 80, 120, 160, 200],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Урон от навыка «Небесный огонь» увеличивается на <span class="tooltip-value">240</span> ед. + <span class="tooltip-value">60%</span> от мастерства Света жреца.</div>'],
		},
		{
			index: 3,
			name: "Дуновение жизни",
			ranks: 5,
			ranksnw: 2,
			desc: "При применении навыка «Молитва жизни» накладывается эффект «Благословение жизненной силы», увеличивающей эффект получаемого исцеления на <span class='tooltip-value'>#%</span>. Меткость навыков Света повышается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Свет удачи",
			ranks: 5,
			desc: "«Милость судьбы» увеличивает вероятность критического урона навыков Света на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>	",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>«Милость судьбы» увеличивает вероятность критического урона навыков Света на <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 8,
			name: "Священный контроль",
			ranks: 5,
			desc: "Мастерство Света увеличивается на <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45, 60, 75],
		},
		{
			index: 9,
			name: "Небесная кара",
			ranks: 4,
			ranksnw: 2,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> навыку «Небесный огонь» добавляется состояние справедливого наказания. Сопротивление цели Свету уменьшается на <span class='tooltip-value'>#</span> ед. на 15 секунд. Эффект суммируется до 5 раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 60, 80, 100],
			rankInfo2: [11, 14, 17, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>С вероятностью <span class="tooltip-value">100%</span> навыку «Небесный огонь» добавляется состояние справедливого наказания. Сопротивление цели Свету уменьшается на <span class="tooltip-value">23</span> ед. на 15 секунд. Эффект суммируется до 5 раз.</div>'],
			parent: [0],
		},
		{
			index: 10,
			name: "Карающий удар",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nНаносит 100% базового урона + <span class='tooltip-value'>#</span> ед. дополнительного урона. На 15 секунд снижает цели сопротивление Свету на 8 ед. Суммируется до 5 раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [147, 210, 275, 339],
			rankInfo3: [794, 1326, 1849, 2363],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">405</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Урон от Света</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Наносит 100% базового урона + <span class="tooltip-value">2867</span> ед. дополнительного урона. На 15 секунд снижает цели сопротивление Свету на 8 ед. Суммируется до 5 раз.</div>'],
		},
		{
			index: 11,
			name: "Жизнь",
			ranks: 3,
			desc: "Длительность действия навыка «Молитва жизни» увеличивается на <span class='tooltip-value'>#</span> мин., расход ОМ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
			parent: 1,
		},
		{
			index: 15,
			name: "Помощь ветра",
			ranks: 4,
			ranksnw: 2,
			desc: "Эффект ускорения от навыка «Молитва ветра» усиливается на <span class='tooltip-value'>#%</span>, время перезарядки уменьшается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [2, 4, 6, 8],
		},
		{
			index: 16,
			name: "Усиление защиты",
			ranks: 3,
			desc: "Усиливает сопротивление жреца Свету на <span class='tooltip-value'>#</span> ед. и усиливает защиту на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
			rankInfo2: [120, 240, 360],
		},
		{
			index: 17,
			name: "Мерцание",
			ranks: 3,
			desc: "Увеличивает базовый урон навыка «Небесный огонь» на <span class='tooltip-value'>#%</span>. С вероятностью <span class='tooltip-value'>#%</span> вводит жреца в состояние мерцания, при котором следующее использование навыка «Небесный огонь» не расходует ОМ и не требует перезарядки. Длительность - 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает базовый урон навыка «Небесный огонь» на <span class="tooltip-value">20%</span>. С вероятностью <span class="tooltip-value">20%</span> вводит жреца в состояние мерцания, при котором следующее использование навыка «Небесный огонь» не расходует ОМ и не требует перезарядки. Длительность - 15 сек.</div>'],
			parent: 4,
		},
		{	
			index: 18,
			name: "Клеймо",
			ranks: 2,
			desc: "Увеличивает базовый урон навыка «Карающий удар» на <span class='tooltip-value'>#%</span>. С вероятностью <span class='tooltip-value'>#%</span> навык «Карающий удар» может оставить на теле врага клеймо, которое уменьшает его макс ОМ на 5% каждые 4 сек. Длительность - 20 сек.",
			rankInfo: [20, 40],
			rankInfo2: [25, 50],
			parent: 5,
		},
		{
			index: 19,
			name: "Теплый ветер",
			ranks: 2,
			desc: "Навык «Молитва ветру» может вызвать состояние теплого ветра, при котором у персонажа может быть восстановлено до <span class='tooltip-value'>#%</span> от количества ОЗ, восполняемого навыком «Врачевание», если он будет атакован.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [70, 120],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Навык «Молитва ветру» может вызвать состояние теплого ветра, при котором у персонажа может быть восстановлено до <span class="tooltip-value">170%</span> от количества ОЗ, восполняемого навыком «Врачевание», если он будет атакован.</div>'],
			parent: 7,
		},
		{
			index: 22,
			name: "Магическая призма",
			ranks: 4,
			desc: "Навыки Света наносят врагу, находящемуся под действием «Клейма», <span class='tooltip-value'>#</span> ед. урона + <span class='tooltip-value'>#%</span> от мастерства Света.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 200, 300, 400],
			rankInfo2: [25, 50, 75, 100],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Навыки Света наносят врагу, находящемуся под действием «Клейма», <span class="tooltip-value">500</span> ед. урона + <span class="tooltip-value">125%</span> от мастерства Света.</div>'],
		},
		{
			index: 23,
			name: "Божественный ветер",
			ranks: 3,
			desc: "Навык «Провидение» может вызвать эффект «Божественный ветер», при котором скорость передвижения всех членов отряда увеличится на <span class='tooltip-value'>#%</span>, а жрец получает невосприимчивость к урону от всех прямых атак на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [40, 50, 60],
			rankInfo2: [4, 6, 8],
		},
		{
			index: 26,
			name: "Божественная мощь",
			ranks: 3,
			desc: "Снижает у врага, находящегося под действием эффекта «Наказание богов» шанс критического урона на <span class='tooltip-value'>#%</span> и уклонение на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Снижает у врага, находящегося под действием эффекта «Наказание богов» шанс критического урона на <span class="tooltip-value">5%</span> и уклонение на <span class="tooltip-value">40</span> ед.</div>'],
		},
		{
			index: 28,
			name: "Вспышка",
			ranks: 4,
			desc: "Увеличивает меткость и уклонение на <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 29,
			name: "Священная энергия",
			ranks: 3,
			desc: "Использовав навык «Исцеляющий свет», жрец на 5 секунд оказывается под действием эффекта «Священная энергия». Действие эффекта прекратится, когда персонаж будет атакован. Атакующий получает <span class='tooltip-value'>#</span> ед. урона и теряет ОМ в количестве <span class='tooltip-value'>#%</span> от максимума.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [200, 400, 600],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Использовав навык «Исцеляющий свет», жрец на 5 секунд оказывается под действием эффекта «Священная энергия». Действие эффекта прекратится, когда персонаж будет атакован. Атакующий получает <span class="tooltip-value">800</span> ед. урона и теряет ОМ в количестве <span class="tooltip-value">8%</span> от максимума.</div>'],
		},
		{
			index: 30,
			name: "Наказание",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nТройной урон. Каждый из ударов навыка наносит цели 80% базового урона + <span class='tooltip-value'>#</span> ед. дополнительного урона. С вероятностью 5%/10%/15% цель, находящаяся под действием «Клейма», может быть оглушена на 3 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [633, 789],
			rankInfo3: [1654.4, 2536.6],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">951</span> ОМ</span><span class="right">Чтение: 3 сек.</span>\n<br><span class="left">Урон от Света</span><span class="right">Время перезарядки: 15 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>Тройной урон. Каждый из ударов навыка наносит цели 80% базового урона + <span class="tooltip-value">3052</span> ед. дополнительного урона. С вероятностью 5%/10%/15% цель, находящаяся под действием «Клейма», может быть оглушена на 3 сек.</div>'],
		},
		{
			index: 31,
			name: "Магический ветер",
			ranks: 2,
			desc: "Расход ОМ на навык «Молитва ветру» возрастает на <span class='tooltip-value'>#%</span>, но цель восстанавливает <span class='tooltip-value'>#%</span> от значения ОМ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100],
			rankInfo2: [50, 70],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Расход ОМ на навык «Молитва ветру» возрастает на <span class="tooltip-value">150%</span>, но цель восстанавливает <span class="tooltip-value">90%</span> от значения ОМ.</div>'],
		},
		{
			index: 33,
			name: "Правосудие",
			ranks: 2,
			ranksnw: 1,
			desc: "Время перезарядки навыка «Божественная Кара» уменьшается на <span class='tooltip-value'>#</span> сек., а урон увеличивается на <span class='tooltip-value'>#%</span> от мастерства Света жреца.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: [30, 60],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Время перезарядки навыка «Божественная Кара» уменьшается на <span class="tooltip-value">6</span> сек., а урон увеличивается на <span class="tooltip-value"	>90%</span> от мастерства Света жреца.</div>'],
		},
		{
			index: 34,
			name: "Дезориентация",
			ranks: 3,
			ranksnw: 2,
			desc: "Вероятность оглушить цель навыком «Наказание» возрастает на <span class='tooltip-value'>#</span> для каждого удара соответственно.",
			rankInfo: ['1%-3%-5%', '2%-6%-10%', '3%-9%-15%'],
			parent: 17,
		},
		{
			index: 36,
			name: "Покровительство света",
			ranks: 3,
			desc: "Каждое очко мастерства света увеличивает урон и исцеляющий эффект от навыков жреца на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [0.5, 1, 1.5],
		},
		{
			index: 38,
			name: "Возмездие",
			ranks: 3,
			desc: "Время перезарядки навыка «Наказание» уменьшается на <span class='tooltip-value'>#</span> сек. Вероятность прерывания навыка снижается на <span class='tooltip-value'>#%</span>, а расход ОМ на навык - на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [10, 20, 30],
			parent: 20,
		},
		{
			index: 39,
			name: "Вихрь света",
			ranks: 2,
			desc: "Уменьшает расход последующих атак Света на <span class='tooltip-value'>#%</span> в течение 10 сек., суммируется до 5 раз.",
			rankInfo: [2, 4],
		},
		{
			index: 41,
			name: "Осуждение",
			ranks: 2,
			desc: "«Божественная воля» увеличивает силу атаки на <span class='tooltip-value'>#%</span>. Цель получает знак приговора, а эффективность исцеления цели уменьшается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 15],
			rankInfo2: [10, 15],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>«Божественная воля» увеличивает силу атаки на <span class="tooltip-value">20%</span>. Цель получает знак приговора, а эффективность исцеления цели уменьшается на <span class="tooltip-value">20%</span>.</div>'],
			parent: 19,
		},
		{
			index: 42,
			name: "Произвол судьбы",
			ranks: 2,
			desc: "Уменьшает время восстановления способности «Карающий удар» на <span class='tooltip-value'>#</span> сек. Навыки «Карающий удар» и «Наказание» с вероятностью в <span class='tooltip-value'>#%</span> снимает эффекты исцеления с атакованной цели. В течение 3 сек. цель не может применять способности исцеления.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 46,
			name: "Праведная кара",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>913 ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Свет</span><span class='right'>Время перезарядки: 60 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nВ радиусе 10 метров снимает с целей (до 20 целей) эффекты, атаки и поддержки.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Суровость",
			ranks: 4,
			desc: "«Праведная кара» снижает шанс крит. удара цели на <span class='tooltip-value'>#%</span> ед., продолжительность - 15 сек.",
			rankInfo: [2, 4, 6, 8],
			parent: 26,
		},
		{
			index: 49,
			name: "Усыпляющая глубина",
			ranks: 2,
			desc: "Молитва сну вызывает головокружение у цели на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 3],
		},
		{
			index: 51,
			name: "Долгая смерть",
			ranks: 3,
			desc: "Увеличивает время действия навыка «Туман смерти» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 54,
			name: "Злая кара",
			ranks: 1,
			desc: "Снижает время чтения заклинания «Праведная кара» на 50%, уменьшает сопротивление Свету цели на 150 ед., а уклонение - на 100 ед; продолжительность - 15 сек.",
			rankInfo: [],
			parent: 26,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Холодный свет",
			ranks: 5,
			desc: "Атака навыком «Небесный огонь» наносит дополнительный урон замедленной цели. Количество урона составляет <span class='tooltip-value'>#%</span> от дополнительного урона навыка. С вероятностью <span class='tooltip-value'>#%</span> на замедленную цель на 2 сек. насылается паралич.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 4,
			name: "Холодная голова",
			ranks: 5,
			desc: "Меткость всех навыков Воды увеличивается на <span class='tooltip-value'>#</span> ед. Критический урон увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 1, 2, 2, 3],
		},
		{
			index: 5,
			name: "Лютый холод",
			ranks: 3,
			ranksnw: 2,
			desc: "Эффект замедления от навыка «Оледенение» усиливается на <span class='tooltip-value'>#%</span>, дополнительный урон от навыка увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Эффект замедления от навыка «Оледенение» усиливается на <span class="tooltip-value">20%</span>, дополнительный урон от навыка увеличивается на <span class="tooltip-value">20%</span>.</div>'],
		},
		{
			index: 6,
			name: "Холодная стойкость",
			ranks: 2,
			desc: "«Милость судьбы» дополнительно повышает все виды сопротивления на <span class='tooltip-value'>#</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>«Милость судьбы» дополнительно повышает все виды сопротивления на <span class="tooltip-value">15</span>.</div>'],
		},
		{
			index: 7,
			name: "Спасительный свет",
			ranks: 3,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> персонаж, благословленный навыком «Провидение», избавляется от всех эффектов контроля и получает иммунитет на 5 сек.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 10,
			name: "Молитва холоду",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 60 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает базовый урон навыков «Оледенение», «Тайное проклятие», «Ледяной удар» и «Ледяное царство» на 25%. Сокращает время перезарядки на 75%. Время действия - <span class='tooltip-value'>#</span> сек. Во время действия данного эффекта навыки Воды не могут быть прерваны.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [276, 394, 513, 634],
			rankInfo3: [12, 15, 18, 21],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">755</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 60 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает базовый урон навыков «Оледенение», «Тайное проклятие», «Ледяной удар» и «Ледяное царство» на 25%. Сокращает время перезарядки на 75%. Время действия - <span class="tooltip-value">24</span> сек. Во время действия данного эффекта навыки Воды не могут быть прерваны.</div>'],
		},
		{
			index: 11,
			name: "Спасительный ветер",
			ranks: 3,
			desc: "Длительность действия навыка «Молитва ветру» увеличивается на <span class='tooltip-value'>#</span> сек. С вероятностью <span class='tooltip-value'>#%</span> цель избавляется от действия эффекта замедления.",
			rankInfo: [2, 4, 6],
			rankInfo2: [40, 70, 100],
		},
		{
			index: 12,
			name: "Власть холода",
			ranks: 4,
			desc: "Мастерство Воды увеличивается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [12, 24, 36, 48],
		},
		{
			index: 13,
			name: "Мгновенная заморозка",
			ranks: 3,
			ranksnw: 2,
			desc: "Уменьшает время перезарядки «Оледенения» на <span class='tooltip-value'>#</span> сек. Уменьшает время чтения «Оледенения» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время перезарядки «Оледенения» на <span class="tooltip-value">4</span> сек. Уменьшает время чтения «Оледенения» на <span class="tooltip-value">20</span> сек.</div>'],
			parent: 2,
		},
		{
			index: 15,
			name: "Таинственный холод",
			ranks: 3,
			ranksnw: 1,
			desc: "Увеличивает базовый урон «Тайного проклятия» на <span class='tooltip-value'>#%</span> и увеличивает вероятность поглощения маны на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает базовый урон «Тайного проклятия» на <span class="tooltip-value">40%</span> и увеличивает вероятность поглощения маны на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 16,
			name: "Ледяное препятствие",
			ranks: 3,
			desc: "Сопротивление Воде увеличивается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Ледяная боль",
			ranks: 4,
			desc: "Навык «Оледенение» снижает сопротивление Воде цели на <span class='tooltip-value'>#</span> ед. и вероятность критической атаки на <span class='tooltip-value'>#%</span>. Длительность - 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 25, 35, 45],
			rankInfo2: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Навык «Оледенение» снижает сопротивление Воде цели на <span class="tooltip-value">55</span> ед. и вероятность критической атаки на <span class="tooltip-value">2.5%</span>. Длительность - 15 сек.</div>'],
			parent: 8,
		},
		{
			index: 18,
			name: "Холодное прозрение",
			ranks: 4,
			desc: "Во время действия «Молитвы холоду» дальность атаки навыков Воды увеличивается на <span class='tooltip-value'>#</span> м. Вероятность нанести крит. урон навыками Воды повышается на <span class='tooltip-value'>#%</span>. При использовании «Молитвы холоду» с вероятностью <span class='tooltip-value'>#%</span> сбрасывается перезарядка навыков Воды.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: [25, 50, 75, 100],
			parent: 5,
		},
		{
			index: 22,
			name: "Средоточие холода",
			ranks: 3,
			desc: "Атакующий навык Воды с вероятностью <span class='tooltip-value'>#%</span> может парализовать земедленную цель на 3 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Атакующий навык Воды с вероятностью <span class="tooltip-value">60%</span> может парализовать земедленную цель на 3 сек.</div>'],
		},
		{
			index: 23,
			name: "Разъедающий холод",
			ranks: 3,
			desc: "Количество ОМ противника, сжигаемое навыком «Тайное проклятье» увеличивается на <span class='tooltip-value'>#%</span>. На <span class='tooltip-value'>#</span> сек. ОМ противника снижаются на удвоенное значение от сожженного.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75],
			rankInfo2: [20, 25, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Количество ОМ противника, сжигаемое навыком «Тайное проклятье» увеличивается на <span class="tooltip-value">100%</span>. На <span class="tooltip-value">35</span> сек. ОМ противника снижаются на удвоенное значение от сожженного.</div>'],
			parent: 9,
		},
		{
			index: 25,
			name: "Ледяной клинок",
			ranks: 3,
			ranksnw: 1,
			desc: "Увеличивает дополнительный урон навыка «Ледяной удар» на <span class='tooltip-value'>#%</span> и снижает время его перезарядки на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличивает дополнительный урон навыка «Ледяной удар» на <span class="tooltip-value">20%</span> и снижает время его перезарядки на <span class="tooltip-value">4</span> сек.</div>'],
		},
		{
			index: 26,
			name: "Холодное дыхание",
			ranks: 3,
			desc: "Увеличивает вероятность замедления цели навыком «Ледяной удар» на <span class='tooltip-value'>#%</span>. Дальность действия навыка увеличивается на <span class='tooltip-value'>#</span> м.",
			rankInfo: [25, 50, 75],
			rankInfo2: [1, 2, 3],
			parent: 15
		},
		{
			index: 27,
			name: "Холодная сень",
			ranks: 2,
			desc: "Навык «Молитва защиты» снижает получаемый урон всех стихий на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Навык «Молитва защиты» снижает получаемый урон всех стихий на <span class="tooltip-value">9%</span>.</div>'],
		},
		{
			index: 30,
			name: "Ледяная исповедь",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Вода</span><span class='right'>Время перезарядки: 45 сек.</span>\n<span class='left'>Проклятие</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nВ следующие 10 сек. после того, как цель получает урон, ее заклинания прерываются и на нее накладывается паралич на <span class='tooltip-value'>#</span> сек. Цель можно оглушить не более 6 раз. Если в течение действия эффекта цель не была атакована, то по окончании действия цель замораживается на 5 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [409, 502],
			rankInfo3: [1, 2],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">599</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Вода</span><span class="right">Время перезарядки: 45 сек.</span>\n<br><span class="left">Проклятие</span><span class="right">Расстояние атаки – 18 м.</span>\n\n<br><br>В следующие 10 сек. после того, как цель получает урон, ее заклинания прерываются и на нее накладывается паралич на <span class="tooltip-value">3</span> сек. Цель можно оглушить не более 6 раз. Если в течение действия эффекта цель не была атакована, то по окончании действия цель замораживается на 5 сек.</div>'],
		},
		{
			index: 31,
			name: "Власть воды",
			ranks: 3,
			desc: "Каждое очко мастерства Воды увеличивает на <span class='tooltip-value'>#</span> ед. урон от навыков стихии Воды и объем лечения у исцеляющих навыков.",
			rankInfo: [0.5, 1, 1.5],
		},
		{
			index: 32,
			name: "Божественный барьер",
			ranks: 3,
			desc: "Защита при использовании «Барьер души» возрастает на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 33,
			name: "Двойное наказание",
			ranks: 3,
			desc: "Потеря ОМ цели, которая находится под воздействием навыка «Божественная кара», увеличивается на <span class='tooltip-value'>#</span>. Если цель находится в состоянии замедления, ей наносится урон, равный <span class='tooltip-value'>#%</span> от потерянных ОМ.",
			rankInfo: [200, 400, 600],
			rankInfo2: [30, 40, 50],
		},
		{
			index: 34,
			name: "Холодное сердце",
			ranks: 3,
			desc: "Длительность действия навыка «Ледяная исповедь» увеличивается на <span class='tooltip-value'>#</span> сек., время перезарядки сокращается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6],
			rankInfo2: [5, 10, 15],
			parent: 18,
		},
		{
			index: 38,
			name: "Быстрая реакция",
			ranks: 2,
			desc: "Сокращает время перезарядки навыка «Милосердие» на <span class='tooltip-value'>#</span> сек. и уменьшает расход ОМ на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: [20, 40],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Сокращает время перезарядки навыка «Милосердие» на <span class="tooltip-value">9</span> сек. и уменьшает расход ОМ на <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 39,
			name: "Пронзающий холод",
			ranks: 3,
			desc: "Время замедления, вызванного навыками жреца, возрастает на <span class='tooltip-value'>#</span> сек., а эффект замедления усиливается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 41,
			name: "Ангел-хранитель",
			ranks: 2,
			desc: "Ангельская песнь расходует на <span class='tooltip-value'>#%</span> меньше энергии. Во время лечения с вероятностью в <span class='tooltip-value'>#%</span> снимает эффект кровоточения или горения. Если цель находится в радиусе 8 м., вероятность снятия этих эффектов возрастает в 2 раза.",
			rankInfo: [15, 30],
			rankInfo2: [10, 20],
		},
		{
			index: 42,
			name: "Сияющий купол",
			ranks: 2,
			desc: "Увеличивает урон, наносимый атаками стихией Воды на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 46,
			name: "Ледяное царство",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>845 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Воды</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – 18 м.</span>\n\nАтакует противников в радиусе 8 метров от цели. Наносит 125% базового урона и дополнительно 3328 ед. урона. На 10 сек. уменьшает эффективность исцеления цели на 20%, а сопротивление Воде – на 60 ед.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Крепкий иней",
			ranks: 4,
			desc: "Увеличивает радиус действия навыка «Ледяное царство» на <span class='tooltip-value'>#</span> м.",
			rankInfo: [0.5, 1, 1.5, 2],
			parent: 27,
		},
		{
			index: 49,
			name: "Дрожь",
			ranks: 3,
			desc: "Увеличивает продолжительность паралича, вызванного навыком «Ледяная исповедь» на <span class='tooltip-value'>#</span> сек., а также снижает скорость чтения заклинаний парализованной цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 51,
			name: "Пронизывающий холод",
			ranks: 2,
			desc: "После нанесения критического удара навыком воды базовая защита цели снижается на 15%; если цель получила 3 и более ударов, действие эффекта «Пронизывающий холод» прекращается. Продолжительность - 15 сек.",
			rankInfo: [15, 30],
		},
		{
			index: 54,
			name: "Аскетизм",
			ranks: 1,
			desc: "Уменьшает время чтения заклинания «Ледяное царство» на 50%, увеличивает бонус к базовой атаке на 25%. Во время применения этого навыка на персонажа не действуют эффекты контроля.",
			rankInfo: [],
			parent: 27,
		},
	]
];