var data = [
    // one
    [
        {
            index: 2,
            name: "Púa Misteriosa",
            ranks: 5,
			desc: "Aumenta el daño extra de Asesinar en <span class='tooltip-value'>#%</span> y le concede un <span class='tooltip-value'>#%</span> de posibilidad de generar una Orbe de Agonía.",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [6, 12, 18, 24, 30],
        },
        {
            index: 3,
            name: "Golpe de Dolor",
            ranks: 5,
			desc: "Aumenta el efecto de Orbes de Agonía sobre Terminación de Pesadilla en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40, 60, 80, 100],
        },
        {
            index: 5,
            name: "Golpe Súbito",
            ranks: 3,
			ranksnw: 1,
			desc: "Aumenta el daño base de Estocada del Dolor en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 7,
            name: "Dolor de Pesadilla",
            ranks: 3,
			desc: "Concede a Terminación de Pesadilla un <span class='tooltip-value'>#%</span> de posibilidad de no consumir ninguna Orbe de Agonía.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40, 60],
        },
        {
            index: 8,
            name: "Asesino de la Oscuridad",
            ranks: 4,
			desc: "Aumenta tu Dominio de lo Oscuro en <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 9,
            name: "Dolor Apresurado",
            ranks: 4,
			ranksnw: 1,
			desc: "Reduce la reactivación de Estocada del Dolor en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [0.5, 1, 1.5, 2],
			parent: 2,
        },
        {
            index: 10,
            name: "Picadura Acechante",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño oscuro</span><span class='right'>Reactivación: 8 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcanсe</span>\n\nGolpea al objetivo dos veces. Cada golpe inflige 70% de daño más <span class='tooltip-value'>#</span> de daño extra. El Chance Crítico del primer ataque es aumentado en un 2% y el segundo en un 4%. Genera un Orbe de Agonía.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [179, 262, 346, 431],
			rankInfo3: [801, 1418, 2024, 2619],
        },
        {
            index: 11,
            name: "Evasión de Sombra",
            ranks: 2,
			desc: "Aumenta la duración del bono de Evasión de Protección de Sombra en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 3],
        },
        {
            index: 13,
            name: "Picaduras Dobles",
            ranks: 3,
			desc: "Estocada del Dolor tiene un <span class='tooltip-value'>#%</span> de posibilidad de generar una Orbe de Agonía adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [9, 18, 27],
			parent: 5,
        },
        {
            index: 14,
            name: "Picadura Acechante Avanzada",
            ranks: 3,
			ranksnw: 1,
			desc: "Reduce la reactivación de Picadura Acechante en <span class='tooltip-value'>#</span> segundo(s) y aumenta su Precisión en <span class='tooltip-value'>#</span>.",
            rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			parent: 6,
        },
        {
            index: 16,
            name: "Golpe Tóxico",
            ranks: 2,
			desc: "Terminación de Pesadilla reduce la Defensa de los objetivos que no están en plena Salud en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 15],
        },
        {
            index: 17,
            name: "Golpe de Dolor",
            ranks: 3,
			desc: "Reduce la reactivación de Lanzamiento en <span class='tooltip-value'>#</span> segundos y aumenta su daño base en <span class='tooltip-value'>#%</span> Cada Orbe de Agonía aumenta el daño base de Lanzamiento en un <span class='tooltip-value'>#%</span> adicional. En Posición 3, también silencia al objetivo por 1 segundo si tienes 3 Orbes de Agonía.",
            rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: [5, 10, 15],
        },
        {
            index: 19,
            name: "Amplificación del Dolor",
            ranks: 3,
			desc: "Cada Orbe de Agonía aumenta tu Ataque en un <span class='tooltip-value'>#</span> adicional. Aumenta la duración de los Orbes de Agonía en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
			rankInfo2: [3, 6, 9],
        },
        {
            index: 20,
            name: "El Arte de lo Oscuro",
            ranks: 3,
			desc: "Reduce el costo de Maná de tus habilidades ofensivas Oscuras en <span class='tooltip-value'>#%</span>.",
            rankInfo: [5, 10, 15],
        },
        {
            index: 21,
            name: "Espada de Hipnosis Avanzada",
            ranks: 3,
			ranksnw: 1,
			desc: "Reduce la reactivación de la Espada de Hipnosis en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 22,
            name: "Impacto Acechante",
            ranks: 3,
			desc: "Aumenta el daño base de Picadura Acechante en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45],
			parent: 9,
        },
        {
            index: 23,
            name: "Veneno de la Oscuridad",
            ranks: 3,
			desc: "Tus ataques Oscuros tienen un <span class='tooltip-value'>#%</span> de posibilidad de envenenar al objetivo, lo cual drena <span class='tooltip-value'>#</span> de Salud cada segundo y reduce su velocidad de movimiento en un 10% por <span class='tooltip-value'>#</span> segundos. Reduce su velocidad de movimiento en un 15%, en Nivel 4.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [60, 80, 100],
			rankInfo2: [50, 70, 90],
			rankInfo3: [4, 5, 5],
        },
        {
            index: 25,
            name: "Teoría de Hipnosis",
            ranks: 1,
			desc: "La Espada de Hipnosis es eficaz contra todos los monstruos.",
            rankInfo: [],
			parent: 14,
        },
        {
            index: 26,
            name: "Finales Amplificados",
            ranks: 2,
			desc: "Aumenta el daño base de tus habilidades de Finalizador en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20],
        },
        {
            index: 28,
            name: "Fortificación de Fortaleza",
            ranks: 4,
			desc: "Aumenta tu Ataque base en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 29,
            name: "Ruptura Ofensiva",
            ranks: 2,
			desc: "Estocada del Dolor y Picadura Acechante reducen el Ataque del objetivo en <span class='tooltip-value'>#%</span> por 8 segundos.",
            rankInfo: [3, 6],
        },
        {
            index: 30,
            name: "Arte Secreto - Agonía",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcanсe: Ninguno</span>\n\nReinicia las reutilizaciones de Picadura Acechante y Estocada del Dolor y genera 2 Orbes de Agonía.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [333, 408],
            rankInfo3: [60, 45],
        },
        {
            index: 31,
            name: "Pesadilla Intensificada",
            ranks: 2,
			desc: "Pesadilla Oscura reduce las resistencias del objetivo en un <span class='tooltip-value'>#</span> adicional y su duración es aumentada en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
            rankInfo2: [2, 4],
        },
        {
            index: 34,
            name: "Arte Avanzado - Agonía",
            ranks: 2,
			desc: "Arte Secreto - Agonía tiene un <span class='tooltip-value'>#%</span> de posibilidad de generar una Orbe de Agonía adicional. Reduce su reactivación en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [40, 80],
            rankInfo2: [5, 10],
			parent: 21,
        },
        {
            index: 35,
            name: "Manipulación de Agonía",
            ranks: 3,
			desc: "Intención Feroz consume Orbes de Agonía para aumentar tu Defensa y Evasión en <span class='tooltip-value'>#</span> segundos. Con 0/1/2/3/4 Orbes de Agonía, tu Defensa es aumentada en <span class='tooltip-value'>#</span> y tu Evasión en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
            rankInfo2: ['10/20/30/40/50', '20/30/40/50/60', '30/40/50/60/70'],
            rankInfo3: ['2/4/6/8/10', '4/6/8/10/12', '6/8/10/12/14'],
        },
        {
            index: 38,
            name: "Semilla de Agonía",
            ranks: 2,
			desc: "Tus habilidades de Finalizador infligen el efecto de Semilla de Agonía en el objetivo, lo que hace que pierda Salud cada vez que ataca. Consume 0/1/2/3/4 Orbes de Agonía para infligir daño igual a <span class='tooltip-value'>#</span> de la Salud actual del objetivo. Este efecto dura 10 segundos y se acumula 3 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: ['2%/3%/4%/5%/6%', '4%/5%/6%/7%/8%'],
        },
        {
            index: 39,
            name: "Experto en Oscuridad",
            ranks: 3,
			desc: "Inflige un efecto de sangrado en el objetivo y reduce sus Dominios en 15. Aumenta el daño extra de tus habilidades ofensivas Oscuras en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 42,
            name: "Espada Venenosa",
            ranks: 3,
			desc: "Don y Mutilación tienen la posibilidad de envenenar al objetivo por 10 segundos. El veneno aumenta el daño infligido por los efectos de sangrado en 20% y frena al objetivo en <span class='tooltip-value'>#%</span>. Con 0/1/2/3/4 Orbes de Agonía, esta habilidad tiene un <span class='tooltip-value'>#</span> de posibilidad de que ocurra.",
            rankInfo: [15, 30, 45],
            rankInfo2: ['10%/20%/30%/40%/50%', '20%/30%/40%/50%/60%', '30%/40%/50%/60%/70%'],
        },
        {
            index: 43,
            name: "Abominación",
            ranks: 3,
			desc: "Tus habilidades de Finalizador tratan a <span class='tooltip-value'>#</span> Orbes Explosivos como si fueran Orbes de Agonía. En posición 3, el efecto de los Orbes Explosivos no es reducido.",
            rankInfo: [1, 2, 3],
        },
        {
            index: 46,
            name: "Mutilación",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>604 Maná</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>EI daño oscuro</span><span class='right'>No reactivación</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nPesadilla Oscura tiene una posibilidad para permitirte usar Mutilación. 0/1/2/3/4 Orbes de Agonía tiene(n) un 10%/20%/30%/40%/50% de posibilidad de activar el uso de esta habilidad. Dura 45 segundos. Este efecto desaparece después de usar Mutilación una vez. Golpea al objetivo 4 veces. Cada golpe obtiene un Chance Crítico adicional del 2%. Cada golpe inflige 70% de tu Ataque más 1219 de daño extra. El objetivo pierde 1 % de tu Salud actual por segundo, y es frenado un 10% por 10 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        }
    ],
        // two
    [
        {
            index: 2,
            name: "Sello Final",
            ranks: 5,
			desc: "Cuando los Orbes Explosivos son consumidos por Terminación de Pesadilla, el Ataque del objetivo es reducido en un <span class='tooltip-value'>#</span> adicional por Orbe.",
            rankInfo: [20, 40, 60, 80, 100],
        },
        {
            index: 3,
            name: "Sello de Espina",
            ranks: 5,
			ranksnw: 3,
			desc: "Aumenta el daño extra de Asesinar en <span class='tooltip-value'>#%</span> y le da un <span class='tooltip-value'>#%</span> de posibilidad de generar una Orbe Explosiva.",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [6, 12, 18, 24, 30],
        },
        {
            index: 5,
            name: "Sombra Oscura",
            ranks: 3,
			ranksnw: 1,
			desc: "Aumenta el daño base de Sello de Garganta en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 6,
            name: "Sello de Velocidad",
            ranks: 2,
			desc: "Aumenta el efecto lento de Terminación de Pesadilla causado por los Orbes Explosivos en <span class='tooltip-value'>#%</span>.",
            rankInfo: [40, 80],
        },
        {
            index: 8,
            name: "Ojo Agudo",
            ranks: 4,
			desc: "Aumenta tu Dominio Físico en <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 9,
            name: "Crueldad Salvaje",
            ranks: 4,
			ranksnw: 1,
			desc: "Reduce la reactivación de Sello de Garganta en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [0.5, 1, 1.5, 2],
			parent: 2,
        },
        {
            index: 10,
            name: "Sacaojos",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño físico</span><span class='right'>Reactivación: 8 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nGolpea al objetivo dos veces. Cada golpe inflige 70% de tu Ataque más <span class='tooltip-value'>#</span> de daño extra. El Chance Crítico del primer ataque es aumentado en 2% y el segundo en 4%. Genera un Orbe Explosiva.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [179, 262, 346, 431],
            rankInfo3: [801, 1418, 2024, 2619],
        },
        {
            index: 11,
            name: "Estocada",
            ranks: 3,
			desc: "Aumenta el Chance Crítico de Asesinar en <span class='tooltip-value'>#%</span>.",
            rankInfo: [4, 7, 10],
			parent: 1,
        },
        {
            index: 13,
            name: "Destierro Drástico",
            ranks: 3,
			desc: "Sello de Garganta obtiene un <span class='tooltip-value'>#%</span> de posibilidad de generar una Orbe Explosiva adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [8, 16, 24],
			parent: 5,
        },
        {
            index: 15,
            name: "Persecución",
            ranks: 3,
			desc: "Aumenta la duración del efecto de Perseguidor Mortal en <span class='tooltip-value'>#</span> segundo(s). Perseguidor Mortal reduce la velocidad de movimiento de los objetivos afectados por Marca de Cacería en un <span class='tooltip-value'>#%</span> adicional.",
            rankInfo: [1, 2, 3],
            rankInfo2: [8, 16, 24],
        },
        {
            index: 16,
            name: "Golpe de Filo",
            ranks: 3,
			desc: "Aumenta la Precisión de tus habilidades ofensivas Físicas en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
		},
        {
            index: 17,
            name: "Golpe de Sombra Rota",
            ranks: 2,
			desc: "Aumenta tu Chance Crítico en <span class='tooltip-value'>#%</span> mientras que se está en sigilo.",
            rankInfo: [20, 40],
        },
        {
            index: 18,
            name: "Sacaojos Avanzado",
            ranks: 3,
			ranksnw: 1,
			desc: "Aumenta el Chance Crítico de ambos ataques Sacaojos en <span class='tooltip-value'>#%</span>.",
            rankInfo: [3, 6, 9],
			parent: 6,
		},
        {
            index: 19,
            name: "Conocimiento de Sellos",
            ranks: 3,
			desc: "Cada Orbe Explosiva aumenta tu Daño Crítico en un <span class='tooltip-value'>#%</span> adicional. Aumenta la duración de los Orbes Explosivos en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
            rankInfo2: [3, 6, 9],
        },
        {
            index: 21,
            name: "Fastidio Hipnótico",
            ranks: 3,
			desc: "La Espada de Hipnosis silencia al objetivo por <span class='tooltip-value'>#</span> segundos o hasta que el objetivo reciba 3 golpes.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
        },
        {
            index: 22,
            name: "Espada Afilada",
            ranks: 3,
			desc: "Aumenta el daño base de Sacaojos en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45],
			parent: 12,
        },
        {
            index: 23,
            name: "Sello de Pesadilla",
            ranks: 3,
			desc: "Da a tus habilidades de Finalizador un <span class='tooltip-value'>#%</span> de posibilidad de activar el efecto de las Orbes Explosivos sin consumir ninguna.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 26,
            name: "Blanco",
            ranks: 3,
			desc: "Cuando Sello de Garganta o Sacaojos asestan un golpe exitoso, el objetivo queda aturdido por <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: ['0-1', '1-2', '2-3'],
        },
        {
            index: 28,
            name: "Crueldad",
            ranks: 3,
			desc: "Aumenta tu Daño Crítico en <span class='tooltip-value'>#%</span>.",
            rankInfo: [4, 8, 12],
        },
        {
            index: 29,
            name: "Sello de Polvo",
            ranks: 2,
			desc: "Aumenta la duración del efecto de silencio de Pesadilla Oscura por <span class='tooltip-value'>#</span> segundo(s) y aumenta su daño base en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2],
            rankInfo2: [10, 20],
        },
        {
            index: 30,
            name: "Arte Secreto - Explosión",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Ataque</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nReinicia las reutilizaciones de Sello de Garganta y Sacaojos y genera 2 Orbes Explosivos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [333, 408],
            rankInfo3: [60, 45],
        },
        {
            index: 31,
            name: "Espadas Compuestas",
            ranks: 2,
			desc: "Aumenta el Chance Crítico de tus habilidades de Finalizador en <span class='tooltip-value'>#%</span> y aumenta el daño extra en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2],
            rankInfo2: [10, 20],
        },
        {
            index: 33,
            name: "Oposición Veloz",
            ranks: 3,
			desc: "Mientras eres frenado, Lanzamiento frena al objetivo a un ritmo igual a tu reducción de la velocidad de movimiento por <span class='tooltip-value'>#</span> segundos. Tiene un <span class='tooltip-value'>#%</span> de posibilidad de eliminar el efecto lento en ti.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [4, 6, 8],
            rankInfo2: [10, 20, 30],
        },
        {
            index: 34,
            name: "Arte Avanzado - Explosión",
            ranks: 2,
			desc: "Arte Secreto - Explosión tiene un <span class='tooltip-value'>#%</span> de posibilidad de generar un Orbe Explosiva adicional. Reduce su reactivación en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [40, 80],
            rankInfo2: [5, 10],
			parent: 20,
        },
        {
            index: 37,
            name: "Púas de Sombra",
            ranks: 3,
			desc: "Habilidades con múltiples ataques tienen la posibilidad de reducir la Evasión del objetivo en <span class='tooltip-value'>#</span> y su Salud Máxima en <span class='tooltip-value'>#%</span> por 8 segundos. Con 1/2/3/4 Orbes Explosivos, la posibilidad de que este efecto ocurra es 15%/30%/45%/60%.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
            rankInfo2: [5, 10, 15],
        },
        {
            index: 38,
            name: "Agresión Intensificada",
            ranks: 2,
			desc: "Aumenta la duración de Intención Feroz en <span class='tooltip-value'>#</span> segundos. Si Asesinar, Sello de Garganta o Sacaojos asestan un golpe crítico mientras que Intención Feroz está activo, el objetivo recibe <span class='tooltip-value'>#%</span> de daño extra de ataques Físicos y de Oscuridad posteriores por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4],
            rankInfo2: [15, 30],
            rankInfo3: [10, 15],
        },
        {
            index: 41,
            name: "Abrazo de la Muerte",
            ranks: 3,
			desc: "Aumenta la duración de Ruptura de Sombra y Diputado de la Muerte en <span class='tooltip-value'>#</span> segundos. Mientras Diputado de la Muerte está activo, la Precisión de habilidades con múltiples golpes es aumentada en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6],
            rankInfo2: [10, 20, 30],
        },
        {
            index: 43,
            name: "Prohibición",
            ranks: 2,
			desc: "Sello de Garganta y Sacaojos tienen la posibilidad de reducir la velocidad de movimiento del objetivo en <span class='tooltip-value'>#%</span> y su Precisión en 15 por 4 segundos. Con 0/1/2/3/4 Orbes Explosivos, este efecto tiene un <span class='tooltip-value'>#</span> de posibilidad de que ocurra.",
            rankInfo: [25, 50],
            rankInfo2: [15, 30],
            rankInfo3: ['10%/20%/30%/40%/50%', '20%/30%/40%/50%/60%'],
        },
        {
            index: 46,
            name: "Hachazo del Peligro",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>559 Maná</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>El daño físico</span><span class='right'>No reactivación</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nTerminación de Pesadilla tiene una posibilidad para permitirte usar Hachazo del Peligro. 0/1/2/3/4 Orbes Explosivos tienen un 10%/20%/30%/40%/50% de posibilidad para permitir el uso de esta habilidad. Dura 45 segundos. Este efecto desaparece después de usar Hachazo del Peligro una vez. Golpea al objetivo 4 veces. El Daño Crítico de cada golpe es aumentado 4%/6%/8%/10%, respectivamente. Cada golpe inflige 70% de tu Ataque base, más 1396 de daño extra.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // three
    [
        {
            index: 2,
            name: "Acecho Veloz",
            ranks: 5,
			desc: "Reduce la reactivación de Sombra Acechante en <span class='tooltip-value'>#</span> segundos. Aumenta tu Evasión en <span class='tooltip-value'>#%</span> mientras estás en sigilo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [20, 40, 60, 80, 100],
        },
        {
            index: 4,
            name: "Sombra Fantasma",
            ranks: 5,
			desc: "Aumenta tu velocidad de movimiento en <span class='tooltip-value'>#%</span> mientras que Sombra Acechadora está activo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [7.5, 15, 22.5, 30, 37.5],
        },
        {
            index: 5,
            name: "Corte de Garganta",
            ranks: 3,
			desc: "Aumenta el daño base de Sello de Garganta en <span class='tooltip-value'>#%</span> y le concede un <span class='tooltip-value'>#%</span> de posibilidad de activar el efecto de Sombra Rápida. Mientras Sombra Rápida está activo, Sello de Garganta y Estocada del Dolor no tienen reactivación. El efecto de Sombra Rápida termina después de un uso.",
            rankInfo: [8, 16, 24],
            rankInfo2: [6, 12, 18],
        },
        {
            index: 6,
            name: "Asesino de Sombra",
            ranks: 3,
			desc: "Aumenta el Chance Crítico de Estocada del Dolor en <span class='tooltip-value'>#%</span> y le da un <span class='tooltip-value'>#%</span> de posibilidad de activar el efecto de Sombra Rápida. Mientras que te ves afectado por Sombra Rápida, Sello de Garganta y Estocada del Dolor no tienen reactivación. Sombra Rápida dura 5 segundos y termina después de un uso.",
            rankInfo: [3, 6, 9],
            rankInfo2: [6, 12, 18],
        },
        {
            index: 7,
            name: "Dominio de Asesinato",
            ranks: 4,
			desc: "Sello de Garganta y Estocada de Dolor drenan el Maná del objetivo en <span class='tooltip-value'>#%</span> e infligen 50% de la cantidad drenada como daño al objetivo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 4, 5, 6],
        },
        {
            index: 9,
            name: "Persecución Persistente",
            ranks: 3,
			ranksnw: 1,
			desc: "Aumenta el alcance de Perseguidor Mortal en <span class='tooltip-value'>#</span> metro(s).",
            rankInfo: [1, 2, 3],
        },
        {
            index: 10,
            name: "Evasión Veloz",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 300 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nAumenta tu Evasión en <span class='tooltip-value'>#</span> y reduce el daño a recibir en <span class='tooltip-value'>#%</span>. Dura <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [106, 151, 197, 243],
            rankInfo3: [150, 180, 210, 240],
            rankInfo4: [20, 17, 14, 11],
            rankInfo5: [12, 14, 16, 18],
        },
        {
            index: 12,
            name: "Impulso de Precisión",
            ranks: 4,
			desc: "Aumenta tu Precisión en <span class='tooltip-value'>#</span>.",
            rankInfo: [6, 12, 18, 24],
        },
        {
            index: 13,
            name: "El Arte de la Gaza",
            ranks: 3,
			desc: "Reduce la reactivación de Perseguidor Mortal en <span class='tooltip-value'>#</span> segundos. Aumenta tu velocidad de movimiento en un <span class='tooltip-value'>#%</span> adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6, 9],
            rankInfo2: [20, 40, 60],
			parent: 5,
        },
        {
            index: 14,
            name: "Evasivo",
            ranks: 3,
			ranksnw: 1,
			desc: "Reduce la reactivación de Evasión Veloz en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40, 60],
			parent: 6,
        },
        {
            index: 15,
            name: "Protección de Sombra Avanzada",
            ranks: 4,
			ranksnw: 2,
			desc: "Reduce la reactivación de Protección de Sombra en <span class='tooltip-value'>#</span> segundos, y aumenta su duración en <span class='tooltip-value'>#</span> segundos. En posición 4, también eliminará los efectos de sangrado.",
            rankInfo: [15, 30, 45, 60],
            rankInfo2: [2, 4, 6, 8],
        },
        {
            index: 17,
            name: "Sombra Inmóvil",
            ranks: 2,
			desc: "Reduce la reactivación de Asesinar en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [1, 2],
        },
        {
            index: 18,
            name: "Destello de Velocidad",
            ranks: 2,
			desc: "Evasión Veloz aumenta tu velocidad de movimiento en <span class='tooltip-value'>#%</span>.",
            rankInfo: [20, 40],
			parent: 9,
        },
        {
            index: 20,
            name: "Ataque Rápido",
            ranks: 3,
			desc: "Aumenta la posibilidad de que Estocada del Dolor y Sello de Garganta activen el efecto de Sombra Rápida en <span class='tooltip-value'>#%</span> y aumenta la duración de Sombra Rápida en <span class='tooltip-value'>#</span> segundo(s). Mientras eres afectado por Sombra Rápida, Sello de Garganta y Estocada del Dolor no tienen reactivación. El efecto de Sombra Rápida termina después de un uso.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [6, 12, 18],
            rankInfo2: [1, 2, 3],
        },
        {
            index: 21,
            name: "Vento Veloz",
            ranks: 4,
			ranksnw: 3,
			desc: "El bono de velocidad de movimiento concedido por Sombra de Vendaval es aumentado en <span class='tooltip-value'>#%</span> y su duración es aumentada en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [5, 10, 15, 20],
            rankInfo2: [0.5, 1, 1.5, 2],
        },
        {
            index: 22,
            name: "Sentido de Movimiento",
            ranks: 1,
			desc: "Aumenta la Precisión de todas sus habilidades con múltiples ataques en 15.",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Ojos de Sombra",
            ranks: 1,
			desc: "Protección de Sombra genera una Orbe de Agonía y una Orbe Explosiva.",
            rankInfo: [],
			parent: 10,
        },
        {
            index: 25,
            name: "Imagen Fantasma",
            ranks: 1,
			desc: "Mientras Sombra de Vendaval está activo, obtienes inmunidad para efectos de lento y atrapar.",
            rankInfo: [],
			parent: 14,
        },
        {
            index: 26,
            name: "Velocidad de Oscuridad",
            ranks: 1,
			desc: "Sombra Rápida reinicia las reutilizaciones de tus habilidades de Finalizador.",
            rankInfo: [],
        },
        {
            index: 28,
            name: "Amorfo",
            ranks: 4,
			desc: "Aumenta tu Evasión en <span class='tooltip-value'>#</span>.",
            rankInfo: [4, 8, 12, 16],
        },
        {
            index: 29,
            name: "Trampa de Sombra",
            ranks: 1,
			desc: "Perseguidor Mortal aturde al objetivo por 2 segundos si la distancia entre tu y el objetivo es mayor a 15 metros.",
            rankInfo: [],
        },
        {
            index: 30,
            name: "Libertad del Viento",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: Instantáneo</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 90 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nTiene un <span class='tooltip-value'>#%</span> de posibilidad de reiniciar la reactivación de Sombra de Vendaval. Está habilidad no se ve afectada por habilidades controladoras.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [306, 376],
            rankInfo3: [50, 100],
        },
        {
            index: 31,
            name: "Teoría de Sigilo",
            ranks: 3,
			desc: "Aumenta los efectos de Intención Feroz y Evasión Veloz en <span class='tooltip-value'>#%</span> mientras estás en sigilo. Aumenta el alcance de la Espada de Hipnosis en <span class='tooltip-value'>#</span> metros.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
            rankInfo2: [4, 8, 12],
        },
        {
            index: 33,
            name: "Creencia de Velocidad",
            ranks: 3,
			desc: "Cada Orbe de Agonía y Orbe Explosiva aumentan tu velocidad de movimiento en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3],
        },
        {
            index: 35,
            name: "Maniobra Enfocada",
            ranks: 3,
			desc: "Maniobra Enfocada se activa cada vez que entras en sigilo u obtienes un bono para tu velocidad de movimiento. Maniobra Enfocada aumenta tu Precisión en <span class='tooltip-value'>#</span> y tu Evasión en <span class='tooltip-value'>#</span> por <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
            rankInfo2: [6, 12, 18],
            rankInfo3: [9, 12, 15],
        },
        {
            index: 37,
            name: "Dominio de Golpe de Muerte",
            ranks: 2,
			desc: "Reduce las reutilizaciones de tus habilidades de Finalizador en <span class='tooltip-value'>#</span> segundo(s) y aumenta su daño base en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2],
            rankInfo2: [10, 20],
        },
        {
            index: 38,
            name: "Libertad del Viento Avanzada",
            ranks: 2,
			desc: "Reduce la reactivación de la Libertad del Viento en <span class='tooltip-value'>#</span> segundos. Aumenta tu velocidad de movimiento en 50%, y te concede inmunidad para los efectos de atrapar y lento por <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [10, 20],
            rankInfo2: [2, 4],
			parent: 21,
        },
        {
            index: 40,
            name: "Calidad de Implacable",
            ranks: 3,
			desc: "Aumenta tu Chance Crítico en <span class='tooltip-value'>#%</span>.",
            rankInfo: [1, 2, 3],
        },
        {
            index: 42,
            name: "Acción por Etapas",
            ranks: 3,
			desc: "Si evades 5 ataques mientras Evasión Veloz está activo, un estado mayor de sigilo es activado. Sigilo no termina cuando atacas o eres atacado por <span class='tooltip-value'>#</span> segundos o hasta que eres golpeado por 4 ataques. El tiempo entre dos evasiones exitosas no debe exceder 2 segundos.",
            rankInfo: [3, 4, 5],
        },
        {
            index: 43,
            name: "Acechador Encubierto",
            ranks: 2,
			desc: "El daño extra de Asesinar, Estocada del Dolor, Sello de Garganta y Lanzamiento es aumentado en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30],
        },
        {
            index: 46,
            name: "Mordiscos de Sombra",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>489 Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño oscuro</span><span class='right'>Reactivación: 10 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Corto Alcance</span>\n\nRequiere que estés en sigilo. Golpea al objetivo tres veces. Cada golpe inflige 70% de tu Ataque base más 1680 de daño extra, y tiene un 15% de posibilidad de silenciar al objetivo por 3 segundos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },	
    ]
];