var data = [
	// one
	[
		{
			index: 1,
			name: "Ярость",
			ranks: 5,
			desc: "Каждое очко гнева дополнительно увеличивает базовую атаку силы гнева на <span class='tooltip-value'>#%</span> и силу атаки на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 2,
			name: "Сила критического удара",
			ranks: 5,
			desc: "Сила критического удара навыка «Тяжелый удар» увеличивается на <span class='tooltip-value'>#%</span>, а урон от навыка – на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [20, 40, 60, 80, 100],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Сила критического удара навыка «Тяжелый удар» увеличивается на <span class="tooltip-value">12%</span>, а урон от навыка – на <span class="tooltip-value">120%</span>.</div>'],
		},
		{
			index: 5,
			name: "Восстановление",
			ranks: 5,
			desc: "На <span class='tooltip-value'>#%</span> увеличивает эффект восстановления ОЗ навыком «Аура жизни».",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Взрыв силы защитника",
			ranks: 3,
			desc: "Увеличивает базовый урон от навыка «Защитный удар» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 7,
			name: "Воля земли",
			ranks: 3,
			desc: "Вероятность получить очко гнева, подвергаясь атаки в состоянии «Концентрация», увеличивается на <span class='tooltip-value'>#%</span>. Каждое очко гнева ускоряет передвижение защитника на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 9,
			name: "Раскол камня",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 2 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nНаносит 125% базового урона + <span class='tooltip-value'>#</span> ед. Сопротивление цели Земле уменьшается на <span class='tooltip-value'>#</span> сек. на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун. После изучения данного скилла, этот скилл заменит любой эффект связанный с Яростью генерируемой навыком Удар защиты.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [111, 168, 227, 287],
			rankInfo3: [1243, 2211, 3162, 4096],
			rankInfo4: [9, 10, 11, 12],
			rankInfo5: [30, 45, 60, 75],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">349</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Урон от Земли</span><span class="right">Время перезарядки: 2 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – ближняя</span>\n\n<br><br>Наносит 125% базового урона + <span class="tooltip-value">5012</span> ед. Сопротивление цели Земле уменьшается на <span class="tooltip-value">13</span> сек. на <span class="tooltip-value">90</span> ед.</div>'],
		},
		{
			index: 10,
			name: "Раскалывающий гнев",
			ranks: 3,
			desc: "Каждое очко гнева увеличивает вероятность крит. удара дробящего камень на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Каждое очко гнева увеличивает вероятность крит. удара дробящего камень на <span class="tooltip-value">4%</span>.</div>'],
			parent: 5,
		},
		{
			index: 11,
			name: "Наследие каменного бога",
			ranks: 4,
			ranksnw: 4,
			desc: "Время действия навыка «Каменный дух» увеличивается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Время действия навыка «Каменный дух» увеличивается на <span class="tooltip-value">5</span> сек.</div>'],
		},
		{
			index: 13,
			name: "Тайна гнева",
			ranks: 3,
			desc: "Уменьшает время перезарядки силы гнева на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время перезарядки силы гнева на <span class="tooltip-value">8</span> сек.</div>'],
		},
		{
			index: 15,
			name: "Сила каменного бога",
			ranks: 2,
			desc: "В состоянии непобедимости базовая сила атаки защитника не снижается, а увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 30],
			parent: 7,
		},
		{
			index: 16,
			name: "Мать-земля",
			ranks: 3,
			desc: "Повышает сопротивление Земле на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [20, 30, 40],
		},
		{
			index: 17,
			name: "Тайна раскола земли",
			ranks: 3,
			ranksnw: 2,
			desc: "Уменьшает время перезарядки «Разлома земли» на <span class='tooltip-value'>#</span> сек., увеличивает меткость «Разлома земли» на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 18,
			name: "Осмеяние магии",
			ranks: 3,
			desc: "Насмешка уменьшает количество ОМ цели на <span class='tooltip-value'>#</span> и дополнительно на <span class='tooltip-value'>#%</span> от текущего количества ОМ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Насмешка уменьшает количество ОМ цели на <span class="tooltip-value">20</span> и дополнительно на <span class="tooltip-value">20%</span> от текущего количества ОМ.</div>'],
		},
		{
			index: 20,
			name: "Пульс земли",
			ranks: 4,
			desc: "Мастерство Земли увеличивается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [20, 30, 40, 50],
		},
		{
			index: 21,
			name: "Раскол",
			ranks: 3,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> использование навыка «Разлом земли» оглушит цель на 1-3 сек. Чем меньше расстояние до защитника, тем дольше состояние оглушения.",
			rankInfo: [20, 35, 50],
			parent: 11,
		},
		{
			index: 22,
			name: "Ветер",
			ranks: 4,
			ranksnw: 2,
			desc: "Усиливает эффект ускорения от навыка «Защита ветра» на <span class='tooltip-value'>#%</span>, сокращает время перезарядки навыка на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [5, 10, 15, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Усиливает эффект ускорения от навыка «Защита ветра» на <span class="tooltip-value">25%</span>, сокращает время перезарядки навыка на <span class="tooltip-value">25</span> сек.</div>'],
		},
		{
			index: 23,
			name: "Душа ветра",
			ranks: 1,
			desc: "«Защитник ветра» устраняет эффект снижения скорости и паралича.",
			rankInfo: [],
			parent: 15,
		},
		{
			index: 25,
			name: "Грубая сила",
			ranks: 3,
			desc: "Увеличивает продолжительность головокружения, вызванного «Расколом земли» и «Силой гнева» на <span class='tooltip-value'>#</span> сек. С некоторой вероятностью продление времени головокружения цели может не сработать. Есть шанс не получить данный эффект при применении навыков.",
			rankInfo: [1, 2, 3],
		},
		{
			index: 26,
			name: "Сбережение земли",
			ranks: 3,
			desc: "Снижаются затраты атакующих навыков Земли на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Снижаются затраты атакующих навыков Земли на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 27,
			name: "Дикий грабеж",
			ranks: 2,
			desc: "Вероятность обезоружить цель при использовании навыка «Гнев света» увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 30,
			name: "Надежный рубеж",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nДлится <span class='tooltip-value'>#</span> сек., все атакующие защитника в этом состоянии получают урон, равный <span class='tooltip-value'>#%</span> очков защиты защитника, также есть 50% вероятность головокружения на 2 сек., каждое очко гнева защитника увеличивает вероятность головокружения на 5%.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [185, 232],
			rankInfo3: [8, 10],
			rankInfo4: [100, 200],
			rankInfo5: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">281</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 90 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Длится <span class="tooltip-value">12</span> сек., все атакующие защитника в этом состоянии получают урон, равный <span class="tooltip-value">300%</span> очков защиты защитника, также есть 50% вероятность головокружения на 2 сек., каждое очко гнева защитника увеличивает вероятность головокружения на 5%.</div>'],
		},
		{
			index: 32,
			name: "Жизненный путь",
			ranks: 3,
			desc: "Максимум ОЗ защитника увеличивается на <span class='tooltip-value'>#%</span> и еще на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [2, 4, 6],
			rankInfo2: [200, 400, 600],
		},
		{
			index: 33,
			name: "Гнев земли",
			ranks: 2,
			desc: "Используя атакующие навыки Земли с вероятностью <span class='tooltip-value'>#%</span> можно получить дополнительное очко ярости.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Используя атакующие навыки Земли с вероятностью <span class="tooltip-value">18%</span> можно получить дополнительное очко ярости.</div>'],
		},
		{
			index: 35,
			name: "Верное сердце",
			ranks: 1,
			desc: "Стоимость ОЗ «Верного стража» уменьшается на 50%. После применения навыка персонаж и цель освобождается от одного эффекта кровотечения.",
			rankInfo: [],
		},
		{
			index: 37,
			name: "Сила земли",
			ranks: 3,
			ranksnw: 1,
			desc: "Базовый урон «Критического удара», «Силы гнева», «Дробящего камень удара» и «Кары земли» увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 15, 20],
		},
		{
			index: 38,
			name: "Время ответного удара",
			ranks: 3,
			desc: "Время перезарядки «Надежного рубежа» снижается на <span class='tooltip-value'>#</span> сек. в состоянии «Абсолютного контроля» макс. ОЗ защитника поднимается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Время перезарядки «Надежного рубежа» снижается на <span class="tooltip-value">20</span> сек. в состоянии «Абсолютного контроля» макс. ОЗ защитника поднимается на <span class="tooltip-value">40%</span>.</div>'],
			parent: 20,
		},
		{
			index: 42,
			name: "Слабое место",
			ranks: 1,
			desc: "Дополнительно снижает шанс критического удара цели на 9-12%. Увеличивает длительность на 5 сек.",
			rankInfo: [],
		},
		{
			index: 43,
			name: "Твердая воля",
			ranks: 2,
			desc: "Каждая единица «Гнева» имеет <span class='tooltip-value'>#%</span> вероятность снять паралич и замедляющий эффект. На втором уровне таланта отменяет последний наложенный на вас негативный эффект.",
			rankInfo: [5, 10],
		},
		{
			index: 45,
			name: "Душа земли",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>498 ОМ</span><span class='right'>Чтение: 2.5 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 25 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nНаносит 200% базового урона и дополнительно 5164 иувеличивает скорость передвижения на 30%. Вводит противника в состояние «Разрушение земли», что увеличивает получаемый противником урон на 8%, длится 8 сек. Каждая ед. гнева увеличивает продолжительность состояния на 1 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			parent: 24,
		},
		{
			index: 46,
			name: "Проклятое сердце",
			ranks: 4,
			desc: "«Проклятое сердце» накладывает на цель эффект, увеличивающий урон, наносимый ей, на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			parent: 28,
		},
		{
			index: 50,
			name: "Ревущие горы",
			ranks: 3,
			desc: "Снижает время восстановления навыка «Горная лавина» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 52,
			name: "Острый шип",
			ranks: 2,
			desc: "Дополнительно повышает силу атаки защитника на <span class='tooltip-value'>#%</span> от показателя защиты.",
			rankInfo: [10, 20],
		},
		{
			index: 53,
			name: "Милость предков",
			ranks: 1,
			desc: "Уменьшает время чтения заклинания «Душа земли» на 1 сек., а также уменьшает время восстановления навыка на 15 сек. дополнительно повышает меткость на 50 ед.",
			rankInfo: [],
			parent: 28,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Защита воли",
			ranks: 5,
			ranksnw: 3,
			desc: "В состоянии «Концентрация воли» базовый урон от навыка «Контрудар» увеличивается на <span class='tooltip-value'>#%</span>. На пятом уровне таланта уменьшает атаку цели на 10% на 9 сек.",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 2,
			name: "Гнев воли",
			ranks: 5,
			desc: "Продолжительность состояния «Концентрация воли» увеличивается на <span class='tooltip-value'>#</span> сек. Каждое очко гнева повышает атаку защитника на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [60, 120, 180, 240, 300],
			rankInfo2: [0.2, 0.4, 0.6, 0.8, 1.0],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Продолжительность состояния «Концентрация воли» увеличивается на <span class="tooltip-value">360</span> сек. Каждое очко гнева повышает атаку защитника на <span class="tooltip-value">1.2%</span>.</div>'],
		},
		{
			index: 5,
			name: "Дух-защитник",
			ranks: 3,
			desc: "Увеличивает продолжительность состояния защиты на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6],
			parent: [0],
		},
		{
			index: 6,
			name: "Блокировка гнева",
			ranks: 3,
			desc: "«Сила Гнева» и «Гнев света» с вероятностью <span class='tooltip-value'>#%</span> не расходуют очки гнева.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 50],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Сила Гнева» и «Гнев света» с вероятностью <span class="tooltip-value">60%</span> не расходуют очки гнева.</div>'],
		},
		{
			index: 7,
			name: "Поддержка света",
			ranks: 5,
			desc: "Участники отряда, находящиеся под воздействием «Ауры света», при получении урона восстанавливают дополнительно <span class='tooltip-value'>#%</span> от восстановленных ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Участники отряда, находящиеся под воздействием «Ауры света», при получении урона восстанавливают дополнительно <span class="tooltip-value">120%</span> от восстановленных ОЗ.</div>'],
		},
		{
			index: 9,
			name: "Защита каменного бога",
			ranks: 3,
			desc: "Навык «Каменный дух» с вероятностью 100% дополнительно рассеивает негативные эффекты со всех дружественных персонажей в пределах 20 м., также делая их невосприимчивыми ко всем негативным эффектам на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 3, 5],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Навык «Каменный дух» с вероятностью 100% дополнительно рассеивает негативные эффекты со всех дружественных персонажей в пределах 20 м., также делая их невосприимчивыми ко всем негативным эффектам на <span class="tooltip-value">7</span> сек.</div>'],
		},
		{
			index: 10,
			name: "Кольцо природного цвета",
			ranks: 4,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Кольцо благословения</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает сопротивление Земле и Воздуху всех участников отряда в радиусе 16 м. от защитника на <span class='tooltip-value'>#</span> ед. Расходует 0.5% максимума ОМ кадые 5 сек. Одновременно активна может быть только одна аура.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [112, 160, 210, 261],
			rankInfo3: [45, 70, 95, 120],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">313</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Кольцо благословения</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает сопротивление Земле и Воздуху всех участников отряда в радиусе 16 м. от защитника на <span class="tooltip-value">145</span> ед. Расходует 0.5% максимума ОМ кадые 5 сек. Одновременно активна может быть только одна аура.</div>'],
		},
		{
			index: 12,
			name: "Дар света",
			ranks: 3,
			desc: "Меткость повышается на <span class='tooltip-value'>#</span> ед. При использовании навыков «Кольцо ледяного огня», «Кольцо природного света», «Кольцо хаоса» накладывается эффект «Дар небес», повышающий меткость членов отряда (кроме защитника) на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [11, 16, 21],
			rankInfo2: [11, 16, 21],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Меткость повышается на <span class="tooltip-value">26</span> ед. При использовании навыков «Кольцо ледяного огня», «Кольцо природного света», «Кольцо хаоса» накладывается эффект «Дар небес», повышающий меткость членов отряда (кроме защитника) на <span class="tooltip-value">26</span> ед.</div>'],
		},
		{
			index: 13,
			name: "Общая защита",
			ranks: 3,
			desc: "Продолжительность «Ауры защитника» увеличивается на <span class='tooltip-value'>#</span> сек., затраты ОМ снижаются на <span class='tooltip-value'>#%</span>.",
			rankInfo: [300, 600, 900],
			rankInfo2: [15, 30, 45],
		},
		{
			index: 14,
			name: "Кольцо ледяного огня",
			ranks: 4,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Кольцо благословения</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает сопротивление Воде и Огню всех участников отряда в радиусе 16 м. от защитника на <span class='tooltip-value'>#</span> ед. Расходует 0.5% максимума ОМ каждые 5 сек. Одновременно активна может быть только одна аура.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 35</span>\n\n', '<span class="req">Требуемый уровень персонажа: 50</span>\n\n', '<span class="req">Требуемый уровень персонажа: 65</span>\n\n', '<span class="req">Требуемый уровень персонажа: 80</span>\n\n'],
			rankInfo2: [112, 160, 210, 261],
			rankInfo3: [45, 70, 95, 120],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">313</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Кольцо благословения</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает сопротивление Воде и Огню всех участников отряда в радиусе 16 м. от защитника на <span class="tooltip-value">145</span> ед. Расходует 0.5% максимума ОМ каждые 5 сек. Одновременно активна может быть только одна аура.</div>'],
		},
		{
			index: 16,
			name: "Оборона света",
			ranks: 3,
			desc: "Повышает сопротивление Свету на <span class='tooltip-value'>#</span> очков, увеличивает очки защиты на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [20, 30, 40],
			rankInfo2: [10, 15, 20],
		},
		{
			index: 18,
			name: "Кольцо хаоса",
			ranks: 4,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: мгновенное</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Кольцо благословения</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает сопротивление Свету и Тьме всех участников отряда в радиусе 16 м. от защитника на <span class='tooltip-value'>#</span> ед. После включения «Кольца света» каждую минуту расходуется 0.5% максимального ОМ каждые 5 сек. Одновременно активна может быть только одна аура.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 40</span>\n\n', '<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n', '<span class="req">Требуемый уровень персонажа: 80</span>\n\n'],
			rankInfo2: [112, 160, 210, 261],
			rankInfo3: [45, 70, 95, 120],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">313</span> ОМ</span><span class="right">Чтение: мгновенное</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Кольцо благословения</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает сопротивление Свету и Тьме всех участников отряда в радиусе 16 м. от защитника на <span class="tooltip-value">145</span> ед. После включения «Кольца света» каждую минуту расходуется 0.5% максимального ОМ каждые 5 сек. Одновременно активна может быть только одна аура.</div>'],
		},
		{
			index: 20,
			name: "Владение светом",
			ranks: 4,
			desc: "Мастерство Света увеличивается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [20, 30, 40, 50],
		},
		{
			index: 21,
			name: "Попутный ветер",
			ranks: 3,
			desc: "Бонус скорости передвижения от «Защиты ветра» увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 23,
			name: "Концентрация света",
			ranks: 4,
			ranksnw: 2,
			desc: "«Кольцо света» защитника увеличивает его уклонение на <span class='tooltip-value'>#</span> ед. и уменьшает вероятность критического удара на <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12, 16],
			rankInfo2: [1.5, 2.0, 2.5, 3.0],
		},
		{
			index: 25,
			name: "Ярость света",
			ranks: 4,
			ranksnw: 2,
			desc: "Критическое уклонение целей с ОЗ менее 50% снижается на <span class='tooltip-value'>#%</span>, а эффективность применяемого к ним лечения на <span class='tooltip-value'>#%</span>, длительность – 15 сек.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [10, 20, 30, 40],
		},
		{
			index: 26,
			name: "Контроль гнева",
			ranks: 2,
			desc: "Снижает время перезарядки «Гнева света» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Снижает время перезарядки «Гнева света» на <span class="tooltip-value">4.5</span> сек.</div>'],
			parent: 15,
		},
		{
			index: 28,
			name: "Энергия кольца света",
			ranks: 4,
			desc: "Снижает расход навыков «Кольца света» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45, 60],
		},
		{
			index: 29,
			name: "Ветер свободы",
			ranks: 2,
			desc: "Радиус действия навыка «Защита ветра» увеличивается на <span class='tooltip-value'>#</span> метров. В области действия избавляет от эффектов замедления (со второго уровня дополнительно снимает эффект паралича, а с третьего – снимает эффект разоружения).\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Радиус действия навыка «Защита ветра» увеличивается на <span class="tooltip-value">15</span> метров. В области действия избавляет от эффектов замедления (со второго уровня дополнительно снимает эффект паралича, а с третьего – снимает эффект разоружения).</div>'],
		},
		{
			index: 30,
			name: "Удар света",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nНаносит 100% базового урона и дополнительно <span class='tooltip-value'>#</span> ед. снижает все виды сопротивления противника на <span class='tooltip-value'>#</span> ед., длительность – <span class='tooltip-value'>#</span> сек., возможно утроение эффекта. Каждое очко гнева повышает на 2% базовый урон атаки и увеличивает на 0.5 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [218, 280],
			rankInfo3: [1802, 2746],
			rankInfo4: [30, 45],
			rankInfo5: [9, 10],
			rankInfo6: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">344</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Урон от Света</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – ближняя</span>\n\n<br><br>Наносит 100% базового урона и дополнительно <span class="tooltip-value">3626</span> ед. снижает все виды сопротивления противника на <span class="tooltip-value">60</span> ед., длительность – <span class="tooltip-value">11</span> сек., возможно утроение эффекта. Каждое очко гнева повышает на 2% базовый урон атаки и увеличивает на 0.5 сек.</div>'],
		},
		{
			index: 33,
			name: "Бешенство",
			ranks: 2,
			desc: "Есть вероятность <span class='tooltip-value'>#%</span> получить очки гнева при «Атаке света».\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [8, 16],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Есть вероятность <span class="tooltip-value">24%</span> получить очки гнева при «Атаке света».</div>'],
		},
		{
			index: 35,
			name: "Мудрость кольца света",
			ranks: 3,
			desc: "Кольцо света защитника повышает его макс ОМ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 30, 40],
			parent: 14,
		},
		{
			index: 37,
			name: "Душа кары небес",
			ranks: 2,
			desc: "Время перезарядки «Кары небес» снижается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10],
		},
		{
			index: 38,
			name: "Разрушающий свет",
			ranks: 2,
			desc: "При добавлении навыков «Гнева света» и «Удара света» сила атаки увеличивается на <span class='tooltip-value'>#%</span>. Удар света снижает сопротивление и эффективность лечения врага на <span class='tooltip-value'>#%</span>, возможно утроение эффекта.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: [5, 10],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>При добавлении навыков «Гнева света» и «Удара света» сила атаки увеличивается на <span class="tooltip-value">30%</span>. Удар света снижает сопротивление и эффективность лечения врага на <span class="tooltip-value">15%</span>, возможно утроение эффекта.</div>'],
			parent: 19,
		},
		{
			index: 41,
			name: "Величие света",
			ranks: 2,
			desc: "Уменьшает время восстановления навыков, наносящих урон светом, на <span class='tooltip-value'>#</span> сек., увеличивает шанс нанесения крит. урона на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [3, 6],
		},
		{
			index: 43,
			name: "Импульс защитника",
			ranks: 2,
			desc: "Критическое уклонение защитника увеличивается на <span class='tooltip-value'>#%</span>, пока активна любая аура.",
			rankInfo: [1, 2],
		},
		{
			index: 46,
			name: "Помощь защиты",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>343 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 120 сек.</span>\n<span class='left'>Массовое благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nНа 15 секунд уменьшает на 30% получаемый участниками отряда урон, находящимися в радиусе 10 м. от защитника. Данный эффект не распространяется на самого защитника.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Чудесное спасение",
			ranks: 4,
			desc: "Во время действия заклинания «Помощь защиты» цели, оказ авшиеся под действием эффекта, каждые 2 сек. восстанавливают ОЗ в количестве <span class='tooltip-value'>#%</span> от показателя защиты защитника.",
			rankInfo: [30, 60, 90, 120],
			parent: 26,
		},
		{
			index: 49,
			name: "Гнев света",
			ranks: 3,
			desc: "Повышает бонус к силе атаки навыков стихии Свет на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 51,
			name: "Набожность",
			ranks: 2,
			desc: "Повышает эффективно сть исцеления целей, оказавшихся под действием навыка «Кольцо покровительства», на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 54,
			name: "Тело богов",
			ranks: 1,
			desc: "Защитники союзники оказываются под действием эффекта «Помощь защиты»; время действия эффекта увеличивается на 5 сек., время восстановления навыка снижается на 30 сек.",
			rankInfo: [],
			parent: 26,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Тайна защиты",
			ranks: 5,
			desc: "Уменьшает время перезарядки «Удара защиты» на <span class='tooltip-value'>#</span> сек., эффект снижения урона в состоянии защиты возрастает на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Уменьшает время перезарядки «Удара защиты» на <span class="tooltip-value">6</span> сек., эффект снижения урона в состоянии защиты возрастает на <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 2,
			name: "Дробящий критический удар",
			ranks: 5,
			desc: "«Тяжелый удар» с вероятностью <span class='tooltip-value'>#%</span> снизит силу атаки цели на <span class='tooltip-value'>#%</span>. Длительность – 20 сек., эффект может суммироваться до трех раз.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 5,
			name: "Тайна провокации",
			ranks: 4,
			desc: "Уменьшает время перезарядки «Насмешки» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span> , дополнительно замедляет цель на </b><span class='tooltip-value'>#%</span>" ,
			rankInfo: [4, 6, 8, ''],
			rankInfo2: [30, 40, 50, 60],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Уменьшает время перезарядки «Насмешки» на <span class="tooltip-value">10</span> сек.</div>'],
		},
		{
			index: 6,
			name: "Воля ненависти",
			ranks: 3,
			desc: "«Концентрация» увеличивает меткость на <span class='tooltip-value'>#</span> ед., а количество генерируемой угрозы на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Концентрация» увеличивает меткость на <span class="tooltip-value">24</span> ед., а количество генерируемой угрозы на <span class="tooltip-value">80%</span>.</div>'],
		},
		{
			index: 7,
			name: "Источник восстановления",
			ranks: 5,
			desc: "Увеличивает эффективность исцеляющих навыков на <span class='tooltip-value'>#%</span> к участникам отряда, находящимся под эффектом «Ауры жизни», увеличивает количество ОЗ восстанавливаемых им при при получении урона на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [20, 40, 60, 80, 100],
		},
	   {
			index: 9,
			name: "Массовая провокация",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Земля</span><span class='right'>Время перезарядки: 120 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – нет</span>\n\nВ радиусе 20 м. провоцирует до <span class='tooltip-value'>#</span> противников, длится <span class='tooltip-value'>#</span> сек. Убирает эффект невидимости с противников на 8 сек. Шанс успеха «Массовой провокации» равен шансу успеха «Насмешки».\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n'],
			rankInfo2: [624, 893, 1170],
			rankInfo3: [16, 17, 18],
			rankInfo4: [6, 7, 8],
			rankInfo5: ['', '', '<div class="runelvl">\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">1454</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Земля</span><span class="right">Время перезарядки: 120 сек.</span>\n<br><span class="left">Массовое проклятие</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>В радиусе 20 м. провоцирует до <span class="tooltip-value">19</span> противников, длится <span class="tooltip-value">9</span> сек. Убирает эффект невидимости с противников на 8 сек. Шанс успеха «Массовой провокации» равен шансу успеха «Насмешки».</div>'],
		},
		{
			index: 10,
			name: "Провокация хаоса",
			ranks: 3,
			ranksnw: 1,
			desc: "«Провокация» снижает уклонение на <span class='tooltip-value'>#</span> ед., длится 8 сек. Массовая провокация снижает меткость на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: [30, 60, 90],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Провокация» снижает уклонение на <span class="tooltip-value">60</span> ед., длится 8 сек. Массовая провокация снижает меткость на <span class="tooltip-value">120</span> ед.</div>'],
			parent: 5,
		},
	   {
			index: 11,
			name: "Душа каменного бога",
			ranks: 4,
			desc: "Время перезарядки навыка «Каменный дух» уменьшается на <span class='tooltip-value'>#</span> сек. В состоянии «Непобедимость» объем лечений, получаемого защитником, увеличивается на <span class='tooltip-value'>#%</span>. Каждые 2 сек. защитник восстанавливает <span class='tooltip-value'>#%</span> от максимума ОЗ (влияет увеличение объема лечения).\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: [2, 4, 6, 8],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Время перезарядки навыка «Каменный дух» уменьшается на <span class="tooltip-value">75</span> сек. В состоянии «Непобедимость» объем лечений, получаемого защитником, увеличивается на <span class="tooltip-value">50%</span>. Каждые 2 сек. защитник восстанавливает <span class="tooltip-value">10%</span> от максимума ОЗ (влияет увеличение объема лечения).</div>'],
		},
		{
			index: 13,
			name: "Вера в защиту",
			ranks: 3,
			ranksnw: 1,
			desc: "При получении урона защитником, находящимся под действием «Ауры защитника», увеличивает его макс. ОЗ на <span class='tooltip-value'>#</span> ед. и 4%. Эффект суммируется до 10 раз и длится 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 200, 300],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>При получении урона защитником, находящимся под действием «Ауры защитника», увеличивает его макс. ОЗ на <span class="tooltip-value">400</span> ед. и 4%. Эффект суммируется до 10 раз и длится 15 сек.</div>'],
		},
		{
			index: 15,
			name: "Влечение силы огня",
			ranks: 2,
			desc: "Увеличивает очки ненависти атаки на <span class='tooltip-value'>#%</span>.",
			rankInfo: [260, 520],
		},
		{
			index: 16,
			name: "Твердая кожа",
			ranks: 4,
			desc: "Увеличивает физическое сопротивление на <span class='tooltip-value'>#</span> очков.",
			rankInfo: [20, 30, 40, 50],
		},
		{
			index: 17,
			name: "Свет веры",
			ranks: 3,
			desc: "Продолжительность защиты веры увеличивается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
			parent: 8,
		},
		{
			index: 19,
			name: "Обвал горы",
			ranks: 3,
			ranksnw: 2,
			desc: "Навык «Разлом земли» дополнительно воздействует на <span class='tooltip-value'>#</span> враждебные цели. Дальность увеличена на <span class='tooltip-value'>#</span> м.",
			rankInfo: [2, 4, 6],
			rankInfo2: [2, 4, 6],
		},
	   {
			index: 20,
			name: "Усиление защиты",
			ranks: 4,
			desc: "Увеличивает очки защиты на <span class='tooltip-value'>#</span>.",
			rankInfo: [50, 100, 150, 200],
		},
		{
			index: 21,
			name: "Покровительство ветра",
			ranks: 3,
			desc: "Увеличивает продолжительность «Защиты ветра» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6],
		},
	   {
			index: 23,
			name: "Разлом земли",
			ranks: 4,
			desc: "Навык «Разлом земли» дополнительно снижает скорость целей на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3.5, 7, 10.5, 14],
			parent: 12,
		},
		{
			index: 25,
			name: "Защита скалы",
			ranks: 3,
			ranksnw: 2,
			desc: "В состоянии «Удара защиты», защита защитника увеличивается на <span class='tooltip-value'>#%</span>, эффект устранения урона повышается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>В состоянии «Удара защиты», защита защитника увеличивается на <span class="tooltip-value">8%</span>, эффект устранения урона повышается на <span class="tooltip-value">8%</span>.</div>'],
		},
		{
			index: 26,
			name: "Наглый провокатор",
			ranks: 3,
			desc: "Снижает время перезарядки «Массовой провокации» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [20, 40, 60],
			parent: 6,
		},
		{
			index: 27,
			name: "Мудрость",
			ranks: 2,
			desc: "Снижается расход ОМ на применение навыков «Концентрация», «Насмешка», «Массовая провокация» и «Аура защитника» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 30,
			name: "Дракон земли",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Урон от Земли</span><span class='right'>Время перезарядки: 8 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – дальняя</span>\n\nПоражает до 15 врагов перед защитником в пределах 8 м. Наносит 100% базового урона и дополнительно <span class='tooltip-value'>#</span> ед. урона. Снижает уклонение цели на <span class='tooltip-value'>#</span> очков, длится 10 сек. Каждое очко гнева увеличивает на 2% дополнительный урон и продлевает эффект снижения уклонения цели на 0.5 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [292, 373],
			rankInfo3: [2319, 3526],
			rankInfo4: [10, 12],
			rankInfo5: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">458</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Урон от Земли</span><span class="right">Время перезарядки: 8 сек.</span>\n<br><span class="left">Массовая атака</span><span class="right">Расстояние атаки – дальняя</span>\n\n<br><br>Поражает до 15 врагов перед защитником в пределах 8 м. Наносит 100% базового урона и дополнительно <span class="tooltip-value">4651</span> ед. урона. Снижает уклонение цели на <span class="tooltip-value">14</span> очков, длится 10 сек. Каждое очко гнева увеличивает на 2% дополнительный урон и продлевает эффект снижения уклонения цели на 0.5 сек.</div>'],
		},
		{
			index: 31,
			name: "Охотник на драконов",
			ranks: 2,
			desc: "Дополнительный урон от навыка «Дракона земли» увеличивается на <span class='tooltip-value'>#%</span>. Использование навыков «Дракон земли» и «Раскол земли» вызывает на <span class='tooltip-value'>#%</span> больше угрозы.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: [50, 100],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Дополнительный урон от навыка «Дракона земли» увеличивается на <span class="tooltip-value">45%</span>. Использование навыков «Дракон земли» и «Раскол земли» вызывает на <span class="tooltip-value">150%</span> больше угрозы.</div>'],
			parent: 19,
		},
		{
			index: 34,
			name: "Сердце стража",
			ranks: 2,
			ranksnw: 1,
			desc: "Время действия щита «Верного стража» увеличивается на <span class='tooltip-value'>#</span> сек. Максимальное расстояние действия на друзей увеличивается на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: [15, 30],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Время действия щита «Верного стража» увеличивается на <span class="tooltip-value">9</span> сек. Максимальное расстояние действия на друзей увеличивается на <span class="tooltip-value">45%</span>.</div>'],
		},
		{
			index: 35,
			name: "Стойкость камня",
			ranks: 3,
			desc: "Добавляет PVE-стойкости за каждый уровень на <span class='tooltip-value'>#%</span>.",
			rankInfo: [66, 132, 198],
		},
		{
			index: 37,
			name: "Победа защитника",
			ranks: 3,
			desc: "В состоянии «Удара защиты» эффект нейтрализации атаки снижается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [30, 60, 100],
			parent: 16,
		},
		{
			index: 39,
			name: "Силы земли",
			ranks: 2,
			desc: "Каждое очко гнева увеличивает базовый урон «Разлома земли» и «Кары земли» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Каждое очко гнева увеличивает базовый урон «Разлома земли» и «Кары земли» на <span class="tooltip-value">4%</span>.</div>'],
		},
		{
			index: 42,
			name: "Вера",
			ranks: 2,
			desc: "Уменьшает время восстановления навыка «Верный страж» на <span class='tooltip-value'>#</span> сек. При получении урона, в течение 12 сек. после применения навыка «Верный страж» защитник восстанавливает <span class='tooltip-value'>#%</span> от потраченных на создание щита ОЗ. Данный эффект можно получить до 5 раз.",
			rankInfo: [5, 10],
			rankInfo2: [15, 30],
			parent: 21,
		},
		{
			index: 43,
			name: "Защитная мощь",
			ranks: 3,
			desc: "Увеличивает дополнительный урон навыков «Тяжелый удар», «Контрудар» и «Гнев света» на <span class='tooltip-value'>#%</span> от показателей защиты. На <span class='tooltip-value'>#%</span> увеличивает количество урона, отражаемого в атакующих навыках «Кольцо ответного удара».",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 47,
			name: "Окаменелая кожа",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>150 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 120 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nСнимает негативные эффекты с персонажа. В течение 15 сек. поглощает 60% получаемого урона. Снижает скорость передвижения защитника на 25%.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 48,
			name: "Закалка",
			ranks: 4,
			desc: "«Окаменелая кожа» дополнительно увеличивает защиту защитника на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [300, 600, 900, 1200],
			parent: 27,
		},
		{
			index: 50,
			name: "Бешенство",
			ranks: 2,
			desc: "Использование навыков «Насмешка» или «Массовая провокация» с вероятностью <span class='tooltip-value'>#%</span> прибавляет несколько очков ярости.",
			rankInfo: [50, 100],
		},
		{
			index: 52,
			name: "Твердая решимость",
			ranks: 3,
			desc: "Если количество ОЗ защитника ниже 30%, мгновенно восстанавливает <span class='tooltip-value'>#%</span> ОЗ и ОМ защитника. В течение следующих 5 сек. предотвращает прямой урон, нанесенный следующей атакой. Навык можно использ овать раз в 10 минут.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 55,
			name: "Непоколебимость",
			ranks: 1,
			desc: "«Окаменелая кожа» больше не уменьшает скорость передвижения.",
			rankInfo: [],
			parent: 27,
		},
	]
];