var data = [
    // one
    [
        {
            index: 1,
            name: "Explosión de Bola de Fuego",
            ranks: 5,
			ranksnw: 3,
			desc: "Incrementa el daño del efecto de quemadura causado por Bola de Fuego en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [25, 50, 75, 100, 125],
        },
        {
            index: 3,
            name: "Fuerza de Protección",
            ranks: 5,
			desc: "Si estás golpeado mientras estás usando Protección Siniestra, obtienes el efecto de la Fuerza de Protección por 5 segundos. Se acumula 5 veces. Incrementa el daño adicionadle tu próximo ataque por una cantidad igual a <span class='tooltip-value'>#%</span> de tu Maná máximo.",
            rankInfo: [0.4, 0.8, 1.2, 1.6, 2],
        },
        {
            index: 5,
            name: "Energía de Bola de Fuego",
            ranks: 5,
			ranksnw: 1,
			desc: "Incrementa la posibilidad de que Bola de Fuego ocasione un efecto de quemadura en su objetivo en <span class='tooltip-value'>#%</span>. Reduce el costo de Maná de Bola de Fuego en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30, 40, 50],
            rankInfo2: [6, 12, 18, 24, 30],
			parent: [0],
        },
        {
            index: 6,
            name: "Arte de Magia Avanzado",
            ranks: 2,
			desc: "Incrementa la duración de Arte de Magia en <span class='tooltip-value'>#</span> minutos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30],
        },
        {
            index: 8,
            name: "llama Siniestra",
            ranks: 3,
			desc: "Incrementa el bono de Dominio de Fuego concedido por Conocimiento Siniestro en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100, 150],
        },
        {
            index: 9,
            name: "Inspiración de Llama",
            ranks: 2,
			desc: "Reduce la reactivación de Bola de Fuego en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
			parent: 2,
        },
        {
            index: 10,
            name: "Llama de Furia",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>El daño de fuego</span><span class='right'>Reactivación: 3 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 18 metros</span>\n\nCausa 100% de tu base de Ataque más <span class='tooltip-value'>#</span> de daño extra al objetivo y todos los enemigos dentro de 8 metros de él.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [250, 368, 487, 608],
            rankInfo3: [782, 1420, 2047, 2663],
        },
        {
            index: 11,
            name: "Fuego Prolongado",
            ranks: 4,
			desc: "Hechizos de fuego aplican el efecto de Fuego Prolongado a objetivos paralizados, causando instantáneamente daño igual al <span class='tooltip-value'>#%</span> de tu Maná máximo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 3, 4, 5],
        },
        {
            index: 14,
            name: "Llama de Furia Avanzada",
            ranks: 4,
			desc: "La Llama de Furia reduce las Resistencias de Agua, Fuego y Viento del objetivo en <span class='tooltip-value'>#</span> por 15 segundos. Se acumula 3 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15, 20],
			parent: 6,
        },
        {
            index: 15,
            name: "Transformación Rápida",
            ranks: 3,
			ranksnw: 3,
			desc: "Reduce la reactivación de Transformación en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [5, 10, 15],
        },
        {
            index: 16,
            name: "Barrera de Llama",
            ranks: 3,
			desc: "Incrementa tu Resistencia de Fuego en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 17,
            name: "Llama de Demonios",
            ranks: 3,
			ranksnw: 1,
			desc: "Furia de Demonios ocasiona un efecto de quemadura en el objetivo por 5 segundos, que causa <span class='tooltip-value'>#</span> daño de Fuego cada segundo.",
            rankInfo: [50, 100, 150],
        },
        {
            index: 18,
            name: "Impulso de Viento Estable",
            ranks: 2,
			desc: "Incrementa la duración de Impulso de Viento en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4],
        },
        {
            index: 19,
            name: "Conjuración",
            ranks: 1,
			desc: "Transformación puede ser proyectada en los monstruos que antes eran inmunes.",
            rankInfo: [],
			parent: 9,
        },
        {
            index: 21,
            name: "Llamada de Demonios",
            ranks: 2,
			desc: "Reduce la reactivación de la Ira de Demonios en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [1, 2],
			parent: 11,
        },
        {
            index: 24,
            name: "Conocimiento de Fuego",
            ranks: 6,
			desc: "Incrementa el daño de tus hechizos ofensivos de Fuego en <span class='tooltip-value'>#%</span> de tu Maná máximo.",
            rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
        },
        {
            index: 26,
            name: "Maestro de la Ignición",
            ranks: 4,
			desc: "Incrementa el daño de los efectos de quemadura causados por tus habilidades de Fuego en <span class='tooltip-value'>#%</span>. Incrementa sus duraciones en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [5, 10, 15, 20],
            rankInfo2: [1, 2, 3, 4],
        },
        {
            index: 27,
            name: "Meditación de Fuego",
            ranks: 3,
			ranksnw: 1,
			desc: "Incrementa el bono de Dominio de Fuego concedido por Meditación Mágica en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
        },
        {
            index: 29,
            name: "Espejo de Reflejo",
            ranks: 3,
			desc: "El Escudo de Fuego enceguece a los atacantes, reduciendo su Precisión en <span class='tooltip-value'>#</span> por 5 segundos. Acumula 10 veces.",
            rankInfo: [3, 6, 9],
			parent: [19],
        },
        {
            index: 30,
            name: "Escudo de Fuego",
            ranks: 2,
            ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nIncrementa tus Resistencias Física y de Fuego en <span class='tooltip-value'>#</span> y tu Chance Crítico en <span class='tooltip-value'>#%</span> por 5 minutos. Incrementa tu Dominio de Fuego en <span class='tooltip-value'>#</span> por 10 segundos cuando eres atacado. Se acumula 8 veces. No puede ser usado con el Escudo de Hielo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [350, 428],
			rankInfo3: [30, 45],
			rankInfo4: [3, 5],
			rankInfo5: [5, 7],
        },
        {
            index: 31,
            name: "Quemadura Apresurada",
            ranks: 2,
			desc: "Incrementa el daño de tus efectos de quemadura en <span class='tooltip-value'>#%</span> y reduce sus duraciones en <span class='tooltip-value'>#%</span> mientras la Meditación Mágica está activa.",
            rankInfo: [100, 200],
			rankInfo2: [20, 40],
			parent: [17],
        },
        {
            index: 33,
            name: "Llamas Apresuradas",
            ranks: 3,
			desc: "Reduce las reactivaciones de Bola de Fuego, Llama de Furia, e Ira de Demonios en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20, 30],
        },
        {
            index: 34,
            name: "Mente Enfurecida",
            ranks: 2,
			desc: "Incrementa el Daño Crítico de Llama de Furia e Ira de Demonios en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
        },
        {
            index: 36,
            name: "Vaporiza",
            ranks: 3,
			desc: "Bola de Fuego tiene una posibilidad del <span class='tooltip-value'>#%</span> de reajustar las reactivaciones de Bola de Fuego, Llama de Furia, e Ira de Demonios.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 38,
            name: "Maestro de Calor",
            ranks: 3,
			desc: "Cuando tu Maná está por encima de 50%, a los objetivos se les inflige el efecto Armadura Derretida. Armadura Derretida reduce la Defensa del objetivo en <span class='tooltip-value'>#</span> por 10 segundos. Acumula 10 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
        },
        {
            index: 39,
            name: "Disipador de Magia",
            ranks: 3,
			desc: "La Purga Mágica reduce la Resistencia de Fuego del objetivo en <span class='tooltip-value'>#</span> por 20 segundos, y drena una cantidad de Maná del objetivo igual a <span class='tooltip-value'>#%</span> de tu Ataque.",
            rankInfo: [10, 20, 30],
            rankInfo2: [15, 30, 45],
        },
        {
            index: 42,
            name: "Aliento del Infierno",
            ranks: 3,
			desc: "Incrementa el daño de base de Bola de Fuego, Ira de Demonios, y Llama de Furia en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 43,
            name: "Evocar",
            ranks: 2,
			desc: "Concede a tus hechizos de Fuego una posibilidad del <span class='tooltip-value'>#%</span> de incrementar tu Daño Crítico en 2%. Se acumula 10 veces y dura 10 segundos.",
            rankInfo: [50, 100],
        },
        {
            index: 46,
            name: "Estallido de Chispa",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>1346 Maná</span><span class='right'>Tiempo de hechizar: 5 segundos</span>\n<span class='left'>El daño de fuego</span><span class='right'>Reactivación: 25 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 18 metros</span>\n\nCausa el 200% de tu Ataque más 5229 de daño extra a los enemigos dentro de 10 metros del objetivo. Los enemigos que sean golpeados serán aturdidos por 1 -5 segundo(s).",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // two
    [
        {
            index: 1,
            name: "Parálisis de Rayo",
            ranks: 4,
			ranksnw: 1,
			desc: "Incrementa la posibilidad del Trueno de paralizar a un enemigo en <span class='tooltip-value'>#%</span> y reduce su costo de Maná en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45, 60],
            rankInfo2: [5, 10, 15, 20],
        },
        {
            index: 2,
            name: "Magic Fountain",
            ranks: 3,
			desc: "Art of Magic increases your max Mana by an additional <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1.5, 3, 4.5],
        },
        {
            index: 3,
            name: "Furia Relámpago",
            ranks: 3,
			desc: "Incrementa el daño de base de Trueno en <span class='tooltip-value'>#%</span>.",
            rankInfo: [15, 30, 45], 
        },
        {
            index: 5,
            name: "Expansión de Choque",
            ranks: 4,
			ranksnw: 2,
			desc: "Incrementa el rango del Trueno por <span class='tooltip-value'>#%</span>. Incrementa el número máximo de objetivos golpeados en <span class='tooltip-value'>#</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [30, 60, 90, 120],
            rankInfo2: [2, 4, 6, 8],
			parent: [0],
        },
        {
            index: 7,
            name: "Contrato de Alma",
            ranks: 2,
			ranksnw: 1,
			desc: "Incrementa la duración de Protección Siniestra en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [10, 20],
        },
        {
            index: 8,
            name: "Viento Siniestro",
            ranks: 3,
			desc: "Incrementa el bono de Dominio de Viento concedido por Conocimiento Siniestro en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100, 150],
        },
        {
            index: 9,
            name: "Trueno Retumbante",
            ranks: 4,
			desc: "Incrementa el Chance Crítico de Trueno en <span class='tooltip-value'>#%</span>. Este efecto es duplicado mientras Tempestad de Truenos está activa.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1.5, 3, 4.5, 6],
			parent: 3,
        },
        {
            index: 10,
            name: "Relámpago",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 2 segundos</span>\n<span class='left'>EI daño de viento</span><span class='right'>Reactivación: <span class='tooltip-value'>#</span> segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 18 metros</span>\n\nCausa <span class='tooltip-value'>#</span> de tu ataque más 16 de daño extra a objetivos en una línea recta frente a ti dentro de 21 metros. Tiene una posibilidad del 25% de interrumpir el hechizo del objetivo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [259, 382, 506, 631],
            rankInfo3: [8, 7, 6, 5],
            rankInfo4: [1339, 2362, 3366, 4351],
        },
        {
            index: 11,
            name: "Energía de Protección",
            ranks: 3,
			desc: "Reduce la cantidad de Maná drenado por punto de daño que la Protección Siniestra absorbe en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 50],
			parent: 4,
        },
        {
            index: 14,
            name: "Golpe de Choque Avanzado",
            ranks: 4,
			desc: "El Relámpago tiene una posibilidad del <span class='tooltip-value'>#%</span> de paralizar y bloquear a los objetivos.",
            rankInfo: [25, 50, 75, 100],
			parent: 7,
        },
        {
            index: 15,
            name: "Alto Voltaje",
            ranks: 2,
            ranksnw: 1,
			desc: "Tus hechizos ofensivos de Viento tienen una posibilidad del <span class='tooltip-value'>#%</span> para generar una carga de Alto Voltaje. Una vez que 8 cargas han sido generadas, recibes el buff de Tempestad de Truenos. La Tempestad de Truenos incrementa el Chance Crítico de tus hechizos de Viento y acorta sus reactivaciones. Dura 10 segundos.",
            rankInfo: [50, 100],
        },
        {
            index: 16,
            name: "Dominio de Viento",
            ranks: 4,
			ranksnw: 3,
			desc: "ncrementa tu Dominio de Viento en <span class='tooltip-value'>#</span>.",
            rankInfo: [10, 20, 30, 40],
        },
        {
            index: 17,
            name: "Transformación Avanzada",
            ranks: 3,
			desc: "Incrementa la duración de Transformación en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [3, 6, 9],
        },
        {
            index: 18,
            name: "Impulso de Viento Rápido",
            ranks: 2,
			desc: "El Impulso de Viento incrementa la velocidad de tu movimiento en un <span class='tooltip-value'>#%</span> adicional.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40],
        },
        {
            index: 20,
            name: "Enfoque de Trueno",
            ranks: 6,
			desc: "Incrementa el daño de tus hechizos ofensivos de Viento en <span class='tooltip-value'>#%</span> de tu Maná máximo.",
            rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
			parent: 11,
        },
        {
            index: 21,
            name: "Parálisis Avanzada",
            ranks: 2,
			desc: "El efecto paralizador del trueno reduce la Evasión del objetivo en <span class='tooltip-value'>#%</span> y su Resistencia de Viento en <span class='tooltip-value'>#</span> Su duración se incrementa en <span class='tooltip-value'>#</span> segundos.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [50, 100],
            rankInfo2: [10, 20],
            rankInfo3: [3, 6],
        },
        {
            index: 23,
            name: "Energía Continua",
            ranks: 4,
			desc: "Incrementa la duración de la Tempestad de Truenos en <span class='tooltip-value'>#</span> segundo(s). Cada carga de Alto Voltaje incrementa la velocidad de tu movimiento en 5%.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3, 4],
			parent: 10,
        },
        {
            index: 26,
            name: "Meditación de Viento",
            ranks: 3,
			desc: "Incrementa el bono de Dominio de Viento concedido por Meditación Mágica en <span class='tooltip-value'>#</span> while Magic Meditation is active.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [15, 30, 45],
        },
        {
            index: 28,
            name: "Barrera de Trueno",
            ranks: 3,
			desc: "Incrementa tu Resistencia de Viento en <span class='tooltip-value'>#</span>.",
            rankInfo: [20, 40, 60],
        },
        {
            index: 29,
            name: "Campo Estático",
            ranks: 3,
			ranksnw: 1,
			desc: "Fuerza Siniestra tiene una posibilidad del <span class='tooltip-value'>#%</span> de paralizar objetivos dentro del rango cada 4 segundos.",
            rankInfo: [40, 70, 100],
			parent: 20,
        },
        {
            index: 30,
            name: "Fuerza Siniestra",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>50% de Maná actual</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>Viento</span><span class='right'>Reactivación: 180 segundos</span>\n<span class='left'>Maldición multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\Cuesta el 50% de tu Maná actual. Dentro de <span class='tooltip-value'>#</span> metros, drena el Maná de hasta <span class='tooltip-value'>#</span> objetivos. La cantidad de Maná perdido es igual al 30% del Maná actual del objetivo. La explosión de Maná puede ser usada una vez cada 20 segundos. Por 20 segundos, los objetivos que te ataquen perderán Maná igual al 1.0% de tu Maná máximo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [12, 15],
            rankInfo3: [20, 25],
        },
        {
            index: 33,
            name: "Opresión Siniestra",
            ranks: 4,
			desc: "Incrementa la cantidad de Maná drenado de los atacantes en <span class='tooltip-value'>#%</span> mientras la Fuerza Siniestra está activa. Silencia los objetivos cuando su Maná cae por debajo de 20% por <span class='tooltip-value'>#</span> segundos. (Este efecto puede ocurrir una vez cada 20 segundos.) Restablece una cantidad de tu Maná igual a la cantidad de Maná drenado del objetivo. Este efecto puede ocurrir hasta por 20 veces.",
            rankInfo: [50, 100, 150, 200],
            rankInfo2: [1, 2, 3, 4],
			parent: 19,
        },
        {
            index: 35,
            name: "Rotura de Hielo",
            ranks: 2,
			desc: "Tus hechizos ofensivos de Viento infligen el efecto de Hielo Roto en los objetivos congelados. Por los próximos 15 segundos, el objetivo toma <span class='tooltip-value'>#%</span> más de daño cuando es atacado.",
            rankInfo: [5, 10],
        },
        {
            index: 37,
            name: "Ráfaga de Viento",
            ranks: 3,
			desc: "Concede a tus hechizos ofensivos de Viento una posibilidad del <span class='tooltip-value'>#%</span> de interrumpir el hechizo del objetivo.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 38,
            name: "Bendición de Trueno",
            ranks: 2,
			desc: "Reduce las reactivaciones de Trueno y Relámpago en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [1, 2],
        },
        {
            index: 39,
            name: "Viento Disipador",
            ranks: 3,
			desc: "Le concede a la Purga Mágica una posibilidad del <span class='tooltip-value'>#%</span> de disipar un buff adicional del objetivo.",
            rankInfo: [40, 70, 100],
        },
        {
            index: 42,
            name: "Parálisis Amplificada",
            ranks: 2,
			desc: "Concede a Furia de la Naturaleza una posibilidad del <span class='tooltip-value'>#%</span> de infligir al objetivo un poderoso efecto paralizador, lo que reduce su Precisión en 60 y su Evasión en 40 por 15 segundos.",
            rankInfo: [50, 100],
        },
        {
            index: 43,
            name: "Tempestad de Truenos",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>5% de Maná máximo</span><span class='right'>Tiempo de hechizar: Instantáneo</span>\n<span class='left'>El daño de viento</span><span class='right'>Reactivación: 90 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nConcede el buff de Tempestad de Truenos.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
        },
        {
            index: 46,
            name: "Purgatorio de Relámpago",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>1064 Maná</span><span class='right'>Tiempo de hechizar: 3 segundos</span>\n<span class='left'>EI daño de viento</span><span class='right'>Reactivación: 15 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: Ninguno</span>\n\nGolpea a objetivos dentro de 16 metros seis veces. Cada golpe causa 50% de tu Base de Ataque más 818 de daño extra. Tiene una posibilidad del 40% de paralizar objetivos afectados.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
        },
    ],
        // three
    [
        {
            index: 1,
            name: "Precisión de Agua",
            ranks: 5,
			ranksnw: 3,
			desc: "Incrementa la Precisión de Flecha de Hielo por <span class='tooltip-value'>#</span> y su base de daño en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [3, 6, 9, 12, 15],
            rankInfo2: [5, 10, 15, 20, 25],
        },
        {
            index: 2,
            name: "Hielo Escalofriante",
            ranks: 5,
			ranksnw: 1,
			desc: "Flecha de Hielo aplica el efecto Hielo Escalofriante, que reduce las Resistencias de Agua y Viento del objetivo en <span class='tooltip-value'>#</span> por 15 segundos. Se acumula 10 veces.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6, 8, 10],
        },
        {
            index: 5,
            name: "Inspiración de Hielo",
            ranks: 2,
			ranksnw: 1,
			desc: "Reduce la reactivación de Flecha de Hielo en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
			parent: [0],
        },
        {
            index: 7,
            name: "Dimensión Extremidad",
            ranks: 4,
			desc: "Incrementa la duración de la Barrera de Hielo en <span class='tooltip-value'>#</span> segundos. Restablece el <span class='tooltip-value'>#%</span> de tu Salud por segundo mientras la Barrera de Hielo está activa.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1.5, 3, 4.5, 6],
            rankInfo2: [1, 2, 3, 4],
        },
        {
            index: 8,
            name: "Corriente Siniestra",
            ranks: 3,
			desc: "Incrementa el bono de Dominio de Agua concedido por Conocimiento Siniestro en <span class='tooltip-value'>#%</span>.",
            rankInfo: [50, 100, 150],
        },
        {
            index: 9,
            name: "Cristal de Hielo",
            ranks: 5,
			desc: "Concede a la Flecha de Hielo una posibilidad de <span class='tooltip-value'>#%</span> de congelar objetivos por 6 segundos. Los objetivos congelados son paralizados y silenciados, pero también tienen su Defensa incrementada en 15%.",
            rankInfo: [3, 6, 9, 12, 15],
			parent: 2,
        },
        {
            index: 10,
            name: "Púa de Hielo",
            ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>El daño de agua</span><span class='right'>Reactivación: 5 segundos</span>\n<span class='left'>Ataque objetivo único</span><span class='right'>Alcance: 18 metros</span>\n\nCausa 100% de tu Base de Ataque más <span class='tooltip-value'>#</span> de daño extra. Esta habilidad aplica 3 aumulaciones de Hielo Escalofriante cuando baja una Creatura. Si el objetivo ya está congelado, repartirá <span class='tooltip-value'>#</span> de daño extra.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 30</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 45</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 60</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
            rankInfo2: [168, 240, 313, 386],
            rankInfo3: [991, 1650, 2297, 2932],
            rankInfo4: [200, 300, 400, 500],
			parent: 1,
        },
        {
            index: 11,
            name: "Piel de Draco",
            ranks: 3,
			desc: "La Protección Siniestra crea un escudo protector adicional por <span class='tooltip-value'>#</span> segundo(s). El escudo absorbe el 100% de daño a recibir, y puede absorber una cantidad total de daño igual al <span class='tooltip-value'>#%</span> de tu Maná máximo.",
            rankInfo: [1, 2, 3],
            rankInfo2: [20, 40, 60],
        },
        {
            index: 13,
            name: "Supresión Mágica",
            ranks: 2,
			desc: "Transformación reduce la velocidad de movimiento del objetivo en <span class='tooltip-value'>#%</span> y su tasa de recuperación de Salud en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [30, 60],
            rankInfo2: [15, 30],
        },
        {
            index: 14,
            name: "Púa de Hielo Avanzada",
            ranks: 5,
			desc: "Incrementa el daño extra que Púa de Hielo causa a los objetivos congelados en <span class='tooltip-value'>#%</span> y su Chance Crítico en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [20, 40, 60, 80, 100],
            rankInfo2: [2, 4, 6, 8, 10],
			parent: 6,
        },
        {
            index: 15,
            name: "Impulso de Viento Avanzado",
            ranks: 2,
			desc: "Le concede al Impulso de Viento una posibilidad del <span class='tooltip-value'>#%</span> para disipar efectos de atrapar y lentos sobre ti.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [50, 100],
        },
        {
            index: 18,
            name: "Congelación Severa",
            ranks: 5,
			desc: "Flecha de Hielo y Púa de Hielo cada uno tienen una posibilidad del <span class='tooltip-value'>#%</span> de desencadenar el efecto de Congelación Severa por 20 segundos. Este efecto desaparecerá después de un uso. Mientras Congelación Severa está activa, tu próxima Púa de Hielo tiene una posibilidad del 100% de bajar una Criatura y tu próxima Flecha de Hielo tiene una posibilidad del 100% de congelar el objetivo.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [2, 4, 6, 8, 10],
        },
        {
            index: 20,
            name: "Concentración de Hielo",
            ranks: 6,
			desc: "Incrementa el daño de tus hechizos ofensivos de Agua en <span class='tooltip-value'>#%</span> de tu Maná máximo.",
            rankInfo: [0.5, 1, 1.5, 2, 2.5, 3],
        },
        {
            index: 21,
            name: "Reino Congelado Avanzado",
            ranks: 2,
			ranksnw: 1,
			desc: "Incrementa la duración del efecto congelador del Reino Congelado en <span class='tooltip-value'>#</span> segundo(s).\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2],
        },
        {
            index: 23,
            name: "Escudo Glaciar",
            ranks: 3,
			desc: "Incrementa tu Resistencia de Agua en <span class='tooltip-value'>#</span> y tu Defensa en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20, 30],
            rankInfo2: [2, 4, 6],
        },
        {
            index: 25,
            name: "Límite",
            ranks: 4,
			desc: "Los objetivos congelados por el Reino Congelado pierden continuamente <span class='tooltip-value'>#%</span> de su Maná máximo. Incrementa el daño de base del Reino Congelado en <span class='tooltip-value'>#%</span>.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
            rankInfo: [1, 2, 3, 4],
            rankInfo2: [15, 30, 45, 60],
			parent: 13,
        },
        {
            index: 26,
            name: "Frió Penetrante",
            ranks: 3,
			desc: "Incrementa el daño extra de la Flecha de Hielo y de la Púa de Hielo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [4, 8, 12],
        },
        {
            index: 30,
            name: "Escudo de Hielo",
            ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'><span class='tooltip-value'>#</span> Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>Defensa</span><span class='right'>Reactivación: 20 segundos</span>\n<span class='left'>Auto bendición</span><span class='right'>Alcance: Ninguno</span>\n\nResistencias Física y de Agua en <span class='tooltip-value'>#</span> y tu Defensa en <span class='tooltip-value'>#</span> Reduce todo daño a recibir en <span class='tooltip-value'>#%</span> Dura 5 minutos. Cuando eres atacado, la velocidad del atacante se reduce en 10%. Dura 5 segundos. Se acumula 5 veces. No puede ser usado junto con el Escudo de Fuego.\n\n<b>Se puede aumentar el nivel de talento usando runas.</b>",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 55</span>\n\n', '<span class="req">Requiere que el personaje sea Nivel 70</span>\n\n'],
            rankInfo2: [350, 428],
            rankInfo3: [30, 45],
			rankInfo4: [50, 80],
			rankInfo5: [3, 5],
        },
        {
            index: 31,
            name: "Escudo Congelado",
            ranks: 3,
			desc: "El Escudo de Hielo incrementa tu Defensa en un <span class='tooltip-value'>#%</span> adicional. La duración del efecto lento se incrementa en <span class='tooltip-value'>#</span> segundo(s).",
            rankInfo: [10, 20, 30],
            rankInfo2: [1, 2, 3],
			parent: 17,
        },
        {
            index: 33,
            name: "Meditación de Agua",
            ranks: 2,
			desc: "Reduce las reactivaciones de Flecha de Hielo, Púa de Hielo, Reino Congelado y Borde de Hielo en <span class='tooltip-value'>#%</span> mientras Meditación Mágica está activa.",
            rankInfo: [30, 60],
        },
        {
            index: 34,
            name: "Congelación Severa Prolongada",
            ranks: 2,
			desc: "El efecto de Congelación Severa tiene una posibilidad del <span class='tooltip-value'>#%</span> de permanecer activo después de haber sido usado.",
            rankInfo: [15, 30],
        },
        {
            index: 36,
            name: "Dominio de Hielo",
            ranks: 3,
			desc: "Incrementa tu Dominio de Agua en <span class='tooltip-value'>#</span>.",
            rankInfo: [15, 30, 45],
        },
        {
            index: 38,
            name: "Ventisca",
            ranks: 3,
			ranksnw: 3,
			desc: "Furia de Hielo tiene una posibilidad del <span class='tooltip-value'>#%</span> de infligir el efecto de Cristal de Hielo al objetivo por 3 segundos. Quita los efectos de quemadura del objetivo.",
            rankInfo: [10, 20, 30],
        },
        {
            index: 39,
            name: "Espíritu de Tormenta de Hielo",
            ranks: 2,
			desc: "Incrementa el daño de base de Furia de Hielo en <span class='tooltip-value'>#%</span>.",
            rankInfo: [10, 20],
			parent: 22,
        },
        {
            index: 42,
            name: "Prisión Congelada",
            ranks: 2,
			desc: "Flecha de Hielo y Púa de Hielo disipan efectos de quemadura y paralizadores en el objetivo e infligen el efecto de Prisión Congelada por 10 segundos. Prisión Congelada reduce la velocidad de Ataque, Defensa y movimiento del objetivo en <span class='tooltip-value'>#%</span>, <span class='tooltip-value'>#%</span> y 25% respectivamente.",
            rankInfo: [10, 20],
            rankInfo2: [10, 20],
        },
        {
            index: 43,
            name: "Agua Disipadora",
            ranks: 2,
			ranksnw: 1,
			desc: "Reduce las reactivaciones de Reino Congelado y Borde de Hielo en <span class='tooltip-value'>#</span> segundos.",
            rankInfo: [5, 10],
        },
        {
            index: 47,
            name: "Borde de Hielo",
            ranks: 1,
			desc: "<span class='tooltip-value' style='font-weight:normal;'>#</span><span class='left'>775 Maná</span><span class='right'>Tiempo de hechizar: 1 segundos</span>\n<span class='left'>EI daño de agua</span><span class='right'>Reactivación: 45 segundos</span>\n<span class='left'>Ataque multiobjetivo</span><span class='right'>Alcance: 18 metros</span>\n\nGolpea hasta 16 objetivos dentro de 10 metros. Causa el 100% de tu Ataque más 1852 de daño extra. Inflige a los objetivos afectados un efecto congelador que incrementa su Defensa en 5% y los vuelve incapaces de moverse. El efecto congelador termina luego de que el objetivo ha sido golpeado dos veces.",
			rankInfo: ['<span class="req">Requiere que el personaje sea Nivel 75</span>\n\n'],
			parent: 25,
        },	
    ]
];