var data = [
		// one
	[
		{
			index: 1,
			name: "Лунный пульс",
			ranks: 5,
			ranksnw: 2,
			desc: "«Лунный удар» накладывает «Лунную тень», которая длится 15 сек. и похищает <span class='tooltip-value'>#%</span> от скорости передвижения цели. Лунная тень (проклятие) - Замедляет цель. Суммируется до 5 раз. Лунная тень (благословение) - Ускоряет вас. Суммируется до 5 раз. После достижения ур. 6 использование «Лунного удара» против цели с макс. количеством ступеней «Лунной тени» снимет с нее эффект «Скакун».",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 4,
			name: "Лунный блеск",
			ranks: 5,
			desc: "Увеличивает базовый урон «Удара затмения» на <span class='tooltip-value'>#%</span> и замедляет его восстановление на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 6,
			name: "Мастер меча",
			ranks: 3,
			desc: "Усиливает дополнительный урон атакующих навыков на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 7,
			name: "Благословение небес",
			ranks: 5,
			desc: "Благословения «Затмение», «Лунная тень», «Неровный узор» и «Темный дух» увеличивают все виды сопротивления на <span class='tooltip-value'>#</span> за ступень.",
			rankInfo: [1, 2, 3, 4, 5],
		},
		{
			index: 10,
			name: "Удар по дуге",
			ranks: 4,
			ranksnw: 2,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Мана</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Атака по области</span><span class='right'>Расстояние атаки – ближняя</span>\n\nАтакует до 15 целей в радиусе 10 метров. Наносит урон в 110% от базовой атаки +<span class='tooltip-value'>#</span>. Снимает с вас благословение «Затмения», а с цели — одноименное проклятие. Базовый урон «Удара по дуге» усиилвается на 20% за каждую ступень благословения «Затмения».",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [137, 263, 382, 493],
			rankInfo3: [1219, 2206, 3171, 4114],
		},
		{
			index: 11,
			name: "Свет воскрешения",
			ranks: 3,
			desc: "Ускоряет восстановление «Крыльев свободы» на <span class='tooltip-value'>#</span> сек. и продлевает эффект на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 12,
			name: "Дар света",
			ranks: 4,
			desc: "Увеличивает ваше мастерство Света на <span class='tooltip-value'>#</span>.",
			rankInfo: [20, 40, 60, 80],
		},
		{
			index: 13,
			name: "Ложное зрение",
			ranks: 4,
			desc: "Увеличивает базовый урон «Лунного удара» на <span class='tooltip-value'>#%</span> и ускоряет его восстановление на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [1.5, 3, 4.5, 6],
			parent: [0],
		},
		{
			index: 16,
			name: "Ночной мираж",
			ranks: 4,
			desc: "Увеличивает шанс критического урона на <span class='tooltip-value'>#%</span> и снижает критическое уклонение на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
			rankInfo2: [1, 2, 3, 4],
		},
		{
			index: 18,
			name: "Разрушение луны",
			ranks: 4,
			ranksnw: 2,
			desc: "Увеличивает базовый урон «Удара по дуге» на <span class='tooltip-value'>#%</span> и ускоряет его восстановление на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [1, 2, 3, 4],
			parent: 4,
		},
		{
			index: 19,
			name: "Призрачные крылья",
			ranks: 3,
			desc: "Использование «Крыльев свободы» даст вам <span class='tooltip-value'>#</span> сек. иммунитета к параличу и замедлению. После ур. 4 снимает эффекты оглушения, замедления и паралича.",
			rankInfo: [6, 8, 10],
		},
		{
			index: 21,
			name: "Ущерб луны",
			ranks: 3,
			desc: "«Звездная песнь» дополнительно восстанавливает <span class='tooltip-value'>#%</span> от потерянных вами ОЗ.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 24,
			name: "Небесный лотос",
			ranks: 3,
			ranksnw: 2,
			desc: "Увеличивает базовый урон «Священного лунного клинка» на <span class='tooltip-value'>#%</span> и ускоряет его восстановление на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 26,
			name: "Серебрянная звезда",
			ranks: 4,
			desc: "«Удар по дуге» может с вероятностью <span class='tooltip-value'>#%</span> снять с цели проклятие «Затмение» и разоружить ее. С каждой новой ступенью «Затмения» длительность разоружения увеличивается на 1 сек.",
			rankInfo: [20, 40, 60],
			parent: 9,
		},
		{
			index: 28,
			name: "Вечное затмение",
			ranks: 3,
			desc: "«Священный лунный клинок» может с вероятностью <span class='tooltip-value'>#%</span> снять с цели проклятие «Затмение» и парализовать ее. С каждой новой ступенью «Затмения» длительность паралича увеличивается на 1 сек.",
			rankInfo: [40, 80, 120],
			parent: 12,
		},
		{
			index: 30,
			name: "Сверхновая",
			ranks: 3,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Мана</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Одиночная атака</span><span class='right'>Расстояние атаки – ближняя</span>\n\nНавык мечника. 4 раза наносит урон в 110% от базовой атаки +<span class='tooltip-value'>#</span>.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [517, 639, 769],
			rankInfo3: [1084, 1961, 2839],
		},
		{
			index: 31,
			name: "Сверкающий",
			ranks: 3,
			desc: "На <span class='tooltip-value'>#%</span> сокращает расходы ОМ на навыки.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 32,
			name: "Универсальное правило",
			ranks: 3,
			desc: "Восстановление «Разума» ускоряется на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 33,
			name: "Лунное лезвие",
			ranks: 4,
			desc: "Увеличивает базовую атаку на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1.5, 3, 4.5, 6],
		},
		{
			index: 34,
			name: "Темный враг",
			ranks: 3,
			ranksnw: 1,
			desc: "Увеличивает базовый урон «Сверхновой» на <span class='tooltip-value'>#%</span>. У каждого удара есть шанс <span class='tooltip-value'>#%</span> оглушить цель на 1 сек.",
			rankInfo: [15, 30, 45],
			rankInfo2: [25, 50, 75],
			parent: 15,
		},
		{
			index: 36,
			name: "Клинок ярости",
			ranks: 3,
			desc: "<span class='tooltip-value'>#%</span> от сопротивления, сожженного «Грядущей войной», преобразуется в мастерство Света.",
			rankInfo: [4, 8, 12],
		},
		{
			index: 38,
			name: "Грязная луна",
			ranks: 3,
			desc: "Если на цель наложено одно из проклятий — «Затмение» или «Лунная тень», каждый удар может добавить ступень «Затмения» или «Лунной тени» с вероятностью <span class='tooltip-value'>#%</span>. Если на вас наложено одно из благословения — «Затмение» или «Лунная тень», каждый удар может добавить ступень «Затмения» или «Лунной тени» с вероятностью <span class='tooltip-value'>#%</span>.",
			rankInfo: [25, 50, 75],
			rankInfo2: [25, 50, 75],
			parent: 19,
		},
		{
			index: 40,
			name: "Темный дух",
			ranks: 3,
			desc: "Атакующие навыки будут накладывать эффект «Темный дух», который крадет <span class='tooltip-value'>#</span> очков мастерства у цели. Темный дух (Проклятие) - снижает все виды мастерства цели на <span class='tooltip-value'>#</span> сек. Суммируется до 25 раз. Темный дух (Благословение) - усиливает все виды мастерства на <span class='tooltip-value'>#</span> сек. Суммируется до 25 раз.",
			rankInfo: [1, 2, 3],
			rankInfo2: [3, 6, 9],
			rankInfo3: [3, 6, 9],
		},
		{
			index: 41,
			name: "Ритуал рассвета и сумрака",
			ranks: 5,
			desc: "Во время действия «Бесстрашного сердца» ваша базовая атака увеличивается на <span class='tooltip-value'>#%</span>. Во время действия «Сердца защитника» ваша базовая защита увеличивается на <span class='tooltip-value'>#%</span>. Во время действия «Благочестивого сердца» базовое здоровье повышается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [2, 4, 6, 8, 10],
			rankInfo3: [2, 4, 6, 8, 10],
		},
		{
			index: 43,
			name: "Непростительный грех",
			ranks: 3,
			desc: "Когда «Щит света» активен, при получении вами урона атакующий каждый раз теряет <span class='tooltip-value'>#</span> ед. Сопротивления Свету. Суммируется до 5 раз. Длится 60 сек.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 46,
			name: "Холодная бездна",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>306 Мана</span><span class='right'>Чтение: 2.5 сек.</span>\n<span class='left'>Урон от Света</span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Проклятие по области</span><span class='right'>Расстояние атаки – ближняя</span>\n\nСоздает Ауру слабости на 30 сек. Оглушает до 15 целей в радиусе 8 метров с интервалом в 60 секунд. Существует вероятность 4% в сек., что цель получит эффект «Увядающая луна»: в течение 10 сек. применение навыков замедляется на 10%. Суммируется до 8 раз.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Бесконечная кара",
			ranks: 4,
			desc: "Каждая ступень «Увядающей луны» замедляет цель еще на <span class='tooltip-value'>#%</span>. Каждый раз, когда цель подвергается воздействию «Увядающей луны», есть шанс <span class='tooltip-value'>#%</span>, что она онемеет на 2 сек. Эффект слабости не аннулируется иммунитетом к замедлению.",
			rankInfo: [2, 4, 6],
			rankInfo2: [3, 6, 9],
			parent: 25,
		},
		{
			index: 49,
			name: "Зачарованный клинок",
			ranks: 3,
			desc: "Каждый раз при применении к вам атакующего навыка на 10 секунд накладывается эффект «Зачарованный клинок», который суммируется до 10 раз. Каждая ступень усиливает дальность действия атакующих навыков на <span class='tooltip-value'>#</span> метров. С 3-й ступени также повышает шанс критического урона на 1%.",
			rankInfo: [0.2, 0.4, 0.6],
		},
		{
			index: 52,
			name: "Святое сердце",
			ranks: 2,
			desc: "В течение <span class='tooltip-value'>#</span> сек. после начала действия эффекта «Разум» его влияние на атакующие навыки усиливается вдвое.",
			rankInfo: [5, 10],
		},
		{
			index: 54,
			name: "Греховный ритуал",
			ranks: 1,
			desc: "Во время действия «Холодной бездны» каждые 3 сек. с вас будут сниматься негативные эффекты. Время действия «Увядающей луны», «Удар затмения» может раз в 3 секунды снять положительный эффект с цели.",
			rankInfo: [],
			parent: 25,
		},
	],
		// two
	[
		{
			index: 2,
			name: "Слепящая вспышка",
			ranks: 5,
			ranksnw: 3,
			desc: "Увеличивает базовый урон «Солнечного удара» на <span class='tooltip-value'>#%</span> и ускоряет его восстановление на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 3,
			name: "Сумеречная защита",
			ranks: 5,
			ranksnw: 2,
			desc: "Увеличивает базовый урон «Мерцающего удара» на <span class='tooltip-value'>#%</span> и ускоряет его восстановление на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 5,
			name: "Буря перьев",
			ranks: 5,
			ranksnw: 2,
			desc: "Продлевает действие «Крыльев свободы» на <span class='tooltip-value'>#</span> сек. и усиливает эффективность ускорения на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 8,
			name: "Огненный песок",
			ranks: 5,
			desc: "При переключении на эффект «Разум» мгновенно восстанавливаются <span class='tooltip-value'>#%</span> от потерянного вами количества ОЗ.",
			rankInfo: [2, 4, 6, 8, 10],
		},
		{
			index: 10,
			name: "Яркая защита",
			ranks: 5,
			ranksnw: 2,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Мана</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Одиночная молитва</span><span class='right'>Расстояние атаки – 8 метр.</span>\n\nЗащитный талант. Мгновенно восстанавливает 1% от максимального запаса ОЗ. Усиливает вашу защиту на 0.1% от максимума ОЗ. Создает Щит поглощения 40%, который поглощает урон до <span class='tooltip-value'>#%</span> от максимума ОЗ. Каждая ступень «Солнечного света» усиливает этот эффект вдвое. Применение снимает одну ступень «Солнечного света».",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n', '<span class="req">Требуемый уровень персонажа: 100</span>\n\n'],
			rankInfo2: [41, 89, 137, 185, 232],
			rankInfo3: [1, 2, 3, 4, 5],
		},
		{
			index: 11,
			name: "Беспокойное тепло",
			ranks: 5,
			desc: "«Мерцающий удар» может с вероятностью <span class='tooltip-value'>#%</span> дать вам эффект «Солнечный свет». «Мерцающий удар» может парализовать цель на 3 сек. с вероятностью <span class='tooltip-value'>#%</span>. Время восстановления эффекта: 30 сек. С 5 уровня «Солнечный удар» может с вероятностью 10% оглушить на 2 сек.",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: [20, 40, 60, 80, 100],
			parent: 1,
		},
		{
			index: 12,
			name: "Нездешний свет",
			ranks: 5,
			desc: "«Звездная песнь» дополнительно восстанавливает ОЗ на <span class='tooltip-value'>#%</span> от максимума.",
			rankInfo: [0.5, 1, 1.5, 2, 2.5],
		},
		{
			index: 13,
			name: "Образ из сна",
			ranks: 4,
			desc: "Во время действия «Крыльев свободы» получаемый урон уменьшается на <span class='tooltip-value'>#%</span>, а крит. защита увеличивается <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [5, 10, 15, 20],
			parent: 2,
		},
		{
			index: 15,
			name: "Солнечный поток",
			ranks: 5,
			ranksnw: 2,
			desc: "Восстановление «Термоядерного взрыва» ускоряется на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15, 20, 25],
		},
		{
			index: 17,
			name: "Рассветное желание",
			ranks: 5,
			desc: "Повышает мастерство Света и сопротивление Свету на <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 18,
			name: "Живое существо",
			ranks: 1,
			ranksnw: 1,
			desc: "Бонус к защите и щит, накладываемый «Яркой защиты», распространяются на союзников в радиусе 8 метров. Действует в течение 40 сек.",
			rankInfo: [],
			parent: 4,
		},
		{
			index: 23,
			name: "Солнечная печать",
			ranks: 5,
			ranksnw: 2,
			desc: "«Термоядерный взрыв» может с вероятностью <span class='tooltip-value'>#%</span> пометить получившую урон цель. Если помеченная цель атакована «Солнечным ударом» или «Мерцающим ударом» в течение 5 сек., она оглушается на 2 сек.",
			rankInfo: [20, 40, 60, 80, 100],
		},
		{
			index: 24,
			name: "Преобразование света",
			ranks: 1,
			desc: "Защитные навыки вырабатывают дополнительную Ненависть.",
			rankInfo: [],
		},
		{
			index: 26,
			name: "Мерцание благословения",
			ranks: 1,
			desc: "Ускоряет восстановление «Яркой защиты» на 30 сек. «Мерцание благословения» снимает эффект «Солнечный свет». Каждая ступень «Солнечного света», которую вы теряете, увеличивает мастерство Света и сопротивление Свету на 6.",
			rankInfo: [],
			parent: 10,
		},
		{
			index: 27,
			name: "Взрыв гало",
			ranks: 5,
			ranksnw: 2,
			desc: "Применение «Термоядерного взрыва» ослабляет до 15 целей в радиусе 8 метров, понижая все виды мастерства на <span class='tooltip-value'>#</span>. Также увеличивает базовый урон «Термоядерного взрыва» на <span class='tooltip-value'>#%</span> на 15 сек.",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: [5, 10, 15, 20, 25],
			parent: 8,
		},
		{
			index: 29,
			name: "Горячая вспышка",
			ranks: 2,
			ranksnw: 1,
			desc: "Переключаемый навык, который через <span class='tooltip-value'>#</span> сек. расходует 1% от максимума ОМ в секунду. Если вас атакуют <span class='tooltip-value'>#</span> раз, на вас накладывается эффект «Раскаленный призыв», который дает ускорение и снимает эффекты контроля. Пока действует «Горячая вспышка», урон от «Солнечного удара» и «Мерцающего удара» также замедляет атакующего на 60% в течение 3 сек.",
			rankInfo: [20, 25],
			rankInfo2: [8, 7],
		},
		{
			index: 31,
			name: "Пепел",
			ranks: 2,
			desc: "В течение 3 секунд после применения «Термоядерного взрыва» существует вероятность <span class='tooltip-value'>#%</span> наложить на 2 сек. немоту на 15 целей в радиусе 8 метров.",
			rankInfo: [40, 70],
			parent: 14,
		},
		{
			index: 32,
			name: "Страж милосердия",
			ranks: 1,
			desc: "«Грядущая война» сжигает на 40% меньше сопротивления.",
			rankInfo: [],
		},
		{
			index: 33,
			name: "Горячий отсвет",
			ranks: 2,
			ranksnw: 2,
			desc: "Восстановление ускоряется на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [15, 30],
			parent: 15,
		},
		{
			index: 34,
			name: "Сильнейший удар",
			ranks: 2,
			desc: "«Передышка» больше не накладывает на вас немоту, но длительность навыка уменьшается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [4, 3],
		},
		{
			index: 36,
			name: "Непорочность",
			ranks: 2,
			desc: "Увеличивает воздействующие на вас исцеляющие эффекты на <span class='tooltip-value'>#%</span>, а Мощь PVE на <span class='tooltip-value'>#</span>.",
			rankInfo: [3, 6],
			rankInfo2: [100, 200],
		},
		{
			index: 37,
			name: "Пламенная чистота",
			ranks: 2,
			ranksnw: 2,
			desc: "Бонус к скорости «Раскаленного призыва» увеличивается на <span class='tooltip-value'>#%</span>, а также увеличивает мастерство Света на <span class='tooltip-value'>#</span>. После 2 уровня также снимает последний негативный эффект.",
			rankInfo: [20, 40],
			rankInfo2: [80, 160],
			parent: 18,
		},
		{
			index: 39,
			name: "Вечный свет",
			ranks: 2,
			ranksnw: 2,
			desc: "Ускоряет восстановление «Щита света» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [20, 40],
		},
		{
			index: 41,
			name: "Солнечный гейзер",
			ranks: 2,
			desc: "<span class='left'><span class='tooltip-value'>#</span> Мана</span><span class='right'>Чтение: 1.5 сек.</span>\n<span class='left'>Light Защита</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Атака по области</span><span class='right'>Расстояние атаки – 10 метр.</span>\n\nЭтот навык будет доступен после начала действия бонуса к скорости навыка «Горячая вспышка». На 3 сек. оглушает цели в радиусе 10 метров и наносит урон, равный 180% от вашего базового урона и еще <span class='tooltip-value'>#</span> урона.",
			rankInfo: [542, 737],
			rankInfo2: [2130, 3150],
			parent: 21,
		},
		{
			index: 43,
			name: "Божественная мощь",
			ranks: 2,
			desc: "Во время действия «Щита света» каждый раз, когда вы получаете урон ваша крит. защита увеличится на <span class='tooltip-value'>#%</span> на 15 сек. Суммируется до 20 раз.",
			rankInfo: [2, 4],
			parent: 22,
		},
		{
			index: 46,
			name: "Божественное вмешательство",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>686 Мана</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Молитва</span><span class='right'>Время перезарядки: 180 сек.</span>\n<span class='left'>Массовое благословение</span><span class='right'>Расстояние атаки – 18 метр.</span>\n\nПри активации защитного навыка вы будете парализованы на 20 сек. Союзники в радиусе 15 метров получают 30% Поглощающий щит.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Священный знак",
			ranks: 4,
			desc: "Во время действия «Божественного вмешательства» базовая защита союзников увеличивается на <span class='tooltip-value'>#%</span>, а их эффект исцеления увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60, 80],
			rankInfo2: [5, 10, 15, 20],
			parent: 25,
		},
		{
			index: 49,
			name: "Божественная суть",
			ranks: 3,
			desc: "Ваша базовая защита увеличивается на 2%, а физическое сопротивление - на <span class='tooltip-value'>#</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 51,
			name: "Сверхволя",
			ranks: 2,
			desc: "Окончательная крит. защита будет увеличена на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Свет богов",
			ranks: 1,
			desc: "Увеличивает длительность «Божественного вмешательства» на 4 сек. Когда «Божественное вмешательство» активно, радиус действия «Солнечного удара» увеличивается до 15 м.",
			rankInfo: [],
			parent: 25,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Наследие богов",
			ranks: 5,
			desc: "Эффект исцеления «Полночной молитвы» усиливается на <span class='tooltip-value'>#</span>.",
			rankInfo: [25, 50, 75, 100, 125],
		},
		{
			index: 2,
			name: "Ритуал звездного края",
			ranks: 5,
			desc: "Усиливает дополнительное исцеление, которое дает «Звездная печать» «Хвале небесам», на <span class='tooltip-value'>#%</span> и ускоряет восстановление «Хвалы небесам» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [20, 40, 60, 80, 100],
			rankInfo2: [1, 2, 3, 4, 5],
		},
		{
			index: 5,
			name: "Темная прелюдия",
			ranks: 2,
			ranksnw: 2,
			desc: "Звездная печать «Полночной молитвы» усиливает исцеляющий эффект цели на <span class='tooltip-value'>#%</span> и увеличивает радиус исцеления «Полночной молитвы» на <span class='tooltip-value'>#</span> м.",
			rankInfo: [3, 6],
			rankInfo2: [1, 2],
		},
		{
			index: 7,
			name: "Простор",
			ranks: 3,
			ranksnw: 1,
			desc: "Сокращает расход ОМ на исцеление на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 8,
			name: "Высший свет",
			ranks: 2,
			ranksnw: 1,
			desc: "«Полночная молитва» может с вероятностью <span class='tooltip-value'>#%</span> снять отрицательный эффект с цели.",
			rankInfo: [5, 10],
		},
		{
			index: 10,
			name: "Лунное возрождение",
			ranks: 5,
			ranksnw: 2,
			desc: "<span class='tooltip-value'>#</span><span class='left'>0 Мана</span><span class='right'>Чтение: 0.5 сек.</span>\n<span class='left'>Молитва</span><span class='right'>Время перезарядки: 40 сек.</span>\n<span class='left'>Одиночная молитва</span><span class='right'>Расстояние атаки – ближняя</span>\n\nПереключаемый навык. Повышает расход ОМ на исцеление на <span class='tooltip-value'>#%</span>, усиливает эффективность исцеления на <span class='tooltip-value'>#%</span>. Щит «Темной жертвы» поглощает на <span class='tooltip-value'>#%</span> больше урона. Длится 18 сек.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n', '<span class="req">Требуемый уровень персонажа: 90</span>\n\n'],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: [8, 16, 24, 32, 40],
			rankInfo4: [10, 20, 30, 40, 50],
		},
		{
			index: 11,
			name: "Круг ночи",
			ranks: 5,
			desc: "«Звездная песнь» восстанавливает <span class='tooltip-value'>#%</span> от ОЗ, которые цель теряет в секунду. «Хвала небесам» восстанавливает <span class='tooltip-value'>#%</span> от потерянных ОМ.",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: [1, 2, 3, 4, 5],
			parent: 3,
		},
		{
			index: 12,
			name: "Сияние энергии",
			ranks: 2,
			desc: "При накоплении 5 ступеней «Звездной печати» «Хвала небесам» также снимает с вас один отрицательный эффект. На 2 уровне снимает один отрицательный эффект с цели.",
			rankInfo: [],
			parent: 4,
		},
		{
			index: 13,
			name: "Песня очищения",
			ranks: 2,
			desc: "Эффект крит. исцеления «Хвалы небесам» и «Полночной молитвы» усиливается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
			parent: 2,
		},
		{
			index: 15,
			name: "Ночная ловушка",
			ranks: 1,
			desc: "При применении «Крыльев свободы» снимает с вас все эффекты контроля. На 2 уровне уровне также снимает с вас оглушение.",
			rankInfo: [],
		},
		{
			index: 16,
			name: "Равнодушие",
			ranks: 2,
			desc: "Через 6 сек. после применения эффектов «Бесстрашное сердце», «Сердце защитника» и «Благочестивое сердце» на <span class='tooltip-value'>#%</span> снижается риск прерывания для навыков «Полночная молитва», «Хвала небесам», «Лунное возрождение» и «Темная жертва».",
			rankInfo: [20, 40],
		},
		{
			index: 18,
			name: "Галактическая зыбь",
			ranks: 3,
			ranksnw: 1,
			desc: "На <span class='tooltip-value'>#%</span> снижает риск прерывания навыков «Полночная молитва», «Хвала небесам», «Лунное возрождение» и «Темная жертва».",
			rankInfo: [15, 30, 45],
			parent: 5,
		},
		{
			index: 19,
			name: "Праздность",
			ranks: 4,
			desc: "Во время действия «Лунного возрождения» затраты ОМ на использование исцеляющих навыков снижаются на <span class='tooltip-value'>#%</span>. Увеличивает длительность действия «Лунного возрождения» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [1, 2, 3, 4],
			parent: 11,
		},
		{
			index: 20,
			name: "Могила Небулы",
			ranks: 2,
			desc: "Количество ОЗ и ОМ, восстанавливаемых при воскрешении, увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40],
		},
		{
			index: 21,
			name: "Вечная тьма",
			ranks: 4,
			desc: "Увеличивает массовую крит. защиту «Искусства ловкости» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6, 8],
		},
		{
			index: 23,
			name: "Серебрянная мелодия",
			ranks: 3,
			desc: "Ускоряет восстановление «Звездной песни» на <span class='tooltip-value'>#</span> сек. Превращает «Звездную песнь» в массовое благословение с радиусом в <span class='tooltip-value'>#</span> м.",
			rankInfo: [5, 10, 15],
			rankInfo2: [2, 5, 8],
		},
		{
			index: 26,
			name: "Благочестие",
			ranks: 4,
			desc: "Длительность «Разума» увеличивается на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6, 8],
		},
		{
			index: 27,
			name: "Отпрыск Темного лорда",
			ranks: 2,
			desc: "When Lunar Revival is active, increases your Darkness Mastery by <span class='tooltip-value'>#%</span> of your Max MP.",
			rankInfo: [0.1, 0.2],
		},
		{
			index: 30,
			name: "Очищение души",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>318 Мана</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Молитва</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Массовое благословение</span><span class='right'>Расстояние атаки – 12 метр.</span>\n\nСнимает последний отрицательный эффект со всех союзников в радиусе 6 метров. Также навык ускоряет его на 50% в течение 3 сек. На ур. 2 его можно применить, игнорируя эффекты контроля.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
		},
		{
			index: 31,
			name: "Тело очищения",
			ranks: 4,
			desc: "Усиливает все виды сопротивления цели <span class='tooltip-value'>#</span> на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [6, 7, 8, 9],
			parent: 18,
		},
		{
			index: 33,
			name: "Адское эхо",
			ranks: 5,
			ranksnw: 1,
			desc: "Увеличивает урон от «Темной жертвы» цели на <span class='tooltip-value'>#</span> и еще <span class='tooltip-value'>#%</span> от вашего мастерства Тьмы.",
			rankInfo: [50, 100, 150, 200, 250],
			rankInfo2: [20, 40, 60, 80, 100],
		},
		{
			index: 34,
			name: "Дуновение эфира",
			ranks: 4,
			desc: "Ускоряет восстановление «Очищения души» на <span class='tooltip-value'>#</span> сек. Продлевает действие бонуса к скорости от «Очищения души» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [1, 2, 3, 4],
			parent: 18,
		},
		{
			index: 38,
			name: "Звездный прилив",
			ranks: 2,
			desc: "Окончательный исцеляющий эффект от «Хвалы небесам» и «Полночной молитвы»: <span class='tooltip-value'>#%</span>-<span class='tooltip-value'>#%</span>.",
			rankInfo: [95, 90],
			rankInfo2: [110, 120],
		},
		{
			index: 39,
			name: "Звездная зола",
			ranks: 3,
			desc: "«Грядущая война» увеличивает шанс крит. урона целей на <span class='tooltip-value'>#%</span>. Каждое дополнительное очко мастерства Тьмы (ваш уровень x6) повышает крит. урон цели еще на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [0.01, 0.02, 0.03],
		},
		{
			index: 41,
			name: "Звездный кодекс",
			ranks: 4,
			desc: "Ускоряет восстановление «Темной жертвы» на <span class='tooltip-value'>#</span> сек. Снижает затраты ОМ на применение «Темной жертвы» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [4, 8, 12, 16],
			rankInfo2: [1, 2, 3, 4],
			parent: 20,
		},
		{
			index: 42,
			name: "Звездная слеза",
			ranks: 2,
			desc: "Во время действия «Передышки» здоровье целей восстанавливается на <span class='tooltip-value'>#%</span> в сек.",
			rankInfo: [5, 10],
		},
		{
			index: 46,
			name: "Безысходный ад",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>344 Мана</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Молитва</span><span class='right'>Время перезарядки: 180 сек.</span>\n<span class='left'>Одиночная молитва</span><span class='right'>Расстояние атаки – 12 метр.</span>\n\nДает вам 5 сек. неуязвимости. У этого эффекта 90-секундный интервал.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Манна небесная",
			ranks: 4,
			desc: "«Безысходный ад» может с вероятностью <span class='tooltip-value'>#%</span> наложить на цель эффект «Манна небесная» на 45 сек. Когда здоровье цели падает ниже 30%, «Манна небесная» восстанавливает его на <span class='tooltip-value'>#%</span> от максимума ОЗ цели.",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [10, 20, 30, 40],
			parent: 26,
		},
		{
			index: 49,
			name: "Врата изгнания",
			ranks: 3,
			desc: "«Щит света» накладывает эффект «Кара» на атакующего при получении вами урона. После накопления 3 ступеней «Кара» преобразуется в «Признание», который расходует <span class='tooltip-value'>#%</span> ОМ в секунду в течение 8 сек.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 51,
			name: "Звездное сознание",
			ranks: 1,
			desc: "Емкость щита «Завесы хаоса» увеличивается на 10%. Может снять с цели кровотечение с вероятностью 15%.",
			rankInfo: [],
		},
		{
			index: 52,
			name: "Солнечное правило",
			ranks: 1,
			desc: "Время на создание щита «Завесы хаоса» сокращается на 1 сек.",
			rankInfo: [],
		},
		{
			index: 54,
			name: "Вечное блаженство",
			ranks: 1,
			desc: "Длительность «Безысходного ада» увеличивается на 1 сек., а его восстановление ускоряется на 30 сек. После 2-го уровня при применении навыка к другим вы тоже получите эффекты.",
			rankInfo: [],
			parent: 26,
		},
	]
];