var data = [
	// one
	[
		{
			index: 1,
			name: "Blessed Recovery",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the amount of Health restored by Heal by <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your max Mana.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100, 150, 200, 250],
			rankInfo2: [2, 3, 4, 5, 6],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Increases the amount of Health restored by Heal by <span class="tooltip-value">300</span> plus <span class="tooltip-value">7%</span> of your max Mana.</div>'],
		},
		{
			index: 3,
			name: "Blooming Life",
			ranks: 5,
			desc: "Blessings of Life increases targets' max Health by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Blessings of Life increases targets\' max Health by an additional <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 6,
			name: "Fortune's Wheel",
			ranks: 3,
			desc: "Increases the duration of Blessings of Fortune by <span class='tooltip-value'>#</span> minutes and the effectiveness of healing skills cast on the target by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 7,
			name: "Brilliance",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the amount of Health restored by Light of Sanctuary by <span class='tooltip-value'>#%</span> and reduces its cooldown by <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [4, 8, 12],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the amount of Health restored by Light of Sanctuary by <span class="tooltip-value">16%</span> and reduces its cooldown by <span class="tooltip-value">80</span> seconds.</div>'],
		},
		{
			index: 8,
			name: "Source of Magic",
			ranks: 4,
			desc: "Increases your max Mana by <span class='tooltip-value'>#%</span> plus <span class='tooltip-value'>#</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [50, 100, 150, 200],
		},
		{
			index: 9,
			name: "Natural Healing",
			ranks: 4,
			desc: "Reduces the cooldown of Heal by <span class='tooltip-value'>#</span> second(s) and its Mana cost by <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5, 2],
			rankInfo2: [5, 10, 15, 20],
			parent: [0],
		},
		{
			index: 10,
			name: "Divine Light",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 3.60 seconds</span>\n<span class='left'>Heal</span><span class='right'>Cooldown: 8 seconds</span>\n<span class='left'>Single-target blessing</span><span class='right'>Range: 18 meters</span>\n\nRestores <span class='tooltip-value'>#</span> Health to the target each second for 4 seconds. The final healing effect restores double that amount. Increases the target's max Health by <span class='tooltip-value'>#</span> for 10 seconds. Has a 4% Crit Chance, which causes this skill to heal for double the amount.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [424, 689, 949, 1204],
			rankInfo3: ['719-794', '1072-1184', '1428-1577', '1787-1973'],
			rankInfo4: [2000, 3000, 4000, 5000],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">1456</span> Mana</span><span class="right">Cast time: 3.60 seconds</span>\n<br><span class="left">Heal</span><span class="right">Cooldown: 8 seconds</span>\n<br><span class="left">Single-target blessing</span><span class="right">Range: 18 meters</span>\n\n<br><br>Restores <span class="tooltip-value">2148-2372</span> Health to the target each second for 4 seconds. The final healing effect restores double that amount. Increases the target\'s max Health by <span class="tooltip-value">6000</span> for 10 seconds. Has a 4% Crit Chance, which causes this skill to heal for double the amount.</div>'],
		},
		{
			index: 11,
			name: "God's Gift",
			ranks: 2,
			desc: "Light of Sanctuary increases the effectiveness of healing skills cast on the target by <span class='tooltip-value'>#%</span> for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [10, 20],
			rankInfo2: [25, 50],
			parent: 3,
		},
		{
			index: 15,
			name: "Instant Healing",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the amount of Health restored by Light of Healing by <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your max Mana.",
			rankInfo: [100, 200, 300],
			rankInfo2: [1, 2, 3],
		},
		{
			index: 16,
			name: "Calmness",
			ranks: 4,
			desc: "Reduces the Mana costs of your healing skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Reduces the Mana costs of your healing skills by <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 18,
			name: "Sacred Healing",
			ranks: 3,
			desc: "Increases the amount of Health restored by Divine Light by <span class='tooltip-value'>#%</span>, and reduces the chance of being interrupted while casting the skill by <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
			rankInfo2: [25, 50, 75],
			parent: 6,
		},
		{
			index: 20,
			name: "Tranquility",
			ranks: 4,
			desc: "Reduces the amount of threat generated by healing skills by <span class='tooltip-value'>#%</span> and the chance of being interrupted while casting them by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40],
			rankInfo2: [15, 30, 45, 60],
		},
		{
			index: 21,
			name: "Combined Healing",
			ranks: 4,
			desc: "Heal restores an amount of the target's Mana equal to <span class='tooltip-value'>#%</span> of your max Mana to targets affected by Light of Healing.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Heal restores an amount of the target\'s Mana equal to <span class="tooltip-value">5%</span> of your max Mana to targets affected by Light of Healing.</div>'],
		},
		{
			index: 22,
			name: "Holy Power",
			ranks: 3,
			desc: "Increases the base damage of your offensive skills by <span class='tooltip-value'>#%</span> after you cast Heal, Light of Healing, or Divine Light. This effect lasts for 20 seconds, stacks up to 3 times, and ends after you successfully land an attack.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 8, 10],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the base damage of your offensive skills by <span class="tooltip-value">12%</span> after you cast Heal, Light of Healing, or Divine Light. This effect lasts for 20 seconds, stacks up to 3 times, and ends after you successfully land an attack.</div>'],
		},
		{
			index: 23,
			name: "Recuperate",
			ranks: 2,
			desc: "Increases the duration of Light of Healing by <span class='tooltip-value'>#%</span> seconds.",
			rankInfo: [2, 4],
			parent: 8,
		},
		{
			index: 25,
			name: "Tenacious Heart",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the duration of Blessings of Tenacity by <span class='tooltip-value'>#</span> minutes and reduces its Mana cost by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 26,
			name: "Awareness",
			ranks: 2,
			desc: "Increases the amount of Health and Mana that Light of Resurrection restores to the target by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the amount of Health and Mana that Light of Resurrection restores to the target by <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 28,
			name: "Healing Spirit",
			ranks: 3,
			desc: "Increases the Crit Chance of Heal. Light of Healing, and Divine Light by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 30,
			name: "Divine Shield",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 30 seconds</span>\n<span class='left'>Single-target blessing</span><span class='right'>Range: 18 meters</span>\n\nGrants the Holy Shield effect to the target, which absorbs 80% of incoming damage for <span class='tooltip-value'>#</span> seconds. The shield can absorb an amount of damage equal to <span class='tooltip-value'>#%</span> of the target's max Health.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [702, 861],
			rankInfo3: [20, 21],
			rankInfo4: [60, 80],
			rankInfo5: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">1028</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Defense</span><span class="right">Cooldown: 30 seconds</span>\n<br><span class="left">Single-target blessing</span><span class="right">Range: 18 meters</span>\n\n<br><br>Grants the Holy Shield effect to the target, which absorbs 80% of incoming damage for <span class="tooltip-value">22</span> seconds. The shield can absorb an amount of damage equal to <span class="tooltip-value">100%</span> of the target\'s max Health.</div>'],
		},
		{
			index: 31,
			name: "Rapid Healing",
			ranks: 3,
			desc: "Heal gains a <span class='tooltip-value'>#%</span> chance to restore an additional 200%. Health to targets affected by Light of Healing, and remove the effect.",
			rankInfo: [20, 40, 60],
		},
		{
			index: 33,
			name: "Armor of Light",
			ranks: 2,
			desc: "Blessings of Tenacity increases the target's Defense by an additional <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Blessings of Tenacity increases the target\'s Defense by an additional <span class="tooltip-value">9%</span>.</div>'],
			parent: 15,
		},
		{
			index: 34,
			name: "Immortal Shield",
			ranks: 3,
			desc: "Increases the amount of damage absorbed by Divine Shield by <span class='tooltip-value'>#%</span> plus an amount equal to <span class='tooltip-value'>#%</span> of your max Mana.",
			rankInfo: [20, 40, 60],
			rankInfo2: [1, 2, 3],
			parent: 18,
		},
		{
			index: 35,
			name: "Enlightenment",
			ranks: 3,
			desc: "Grants your healing skills a <span class='tooltip-value'>#%</span> chance to trigger the Inspiration effect, which reduces the Mana cost of your healing skills by 10% for 10 seconds. Stacks 3 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Grants your healing skills a <span class="tooltip-value">40%</span> chance to trigger the Inspiration effect, which reduces the Mana cost of your healing skills by 10% for 10 seconds. Stacks 3 times.</div>'],
		},
		{
			index: 38,
			name: "Light of Benevolence",
			ranks: 2,
			desc: "Increases the healing bonus granted by Sympathy by an additional <span class='tooltip-value'>#%</span> of your Attack.",
			rankInfo: [5, 10],
		},
		{
			index: 40,
			name: "Gift of the Goddess",
			ranks: 3,
			desc: "Increases the amount of Health restored by healing skills by <span class='tooltip-value'>#%</span>. Healing bonuses from other skills and talents are also increased.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 41,
			name: "Angelic Blessing",
			ranks: 3,
			desc: "Increases the amount of Health restored by Angelic Harmony by <span class='tooltip-value'>#%</span>. Reduces the cooldown of Light of Sanctuary by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
		},
		{
			index: 42,
			name: "Divined Extolment",
			ranks: 2,
			desc: "Reduces the cooldowns of Light of Heaven and Divine Shield by <span class='tooltip-value'>#</span> and <span class='tooltip-value'>#</span> second(s) respectively. Reduces their Mana costs by <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2],
			rankInfo2: [3, 6],
			rankInfo3: [15, 30],
		},
		{
			index: 46,
			name: "Purifying Light",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>378 Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Defense</span><span class='right'>Cooldown: 8 seconds</span>\n<span class='left'>Single-target blessing</span><span class='right'>Range: 18 meters</span>\n\nDispels the most recent curse effect placed on the target.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Pure Faith",
			ranks: 4,
			desc: "Reduces Purifying Light's cooldown by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [1, 2, 3, 4],
			parent: 27,
		},
		{
			index: 49,
			name: "Piety",
			ranks: 3,
			desc: "Divine Light increases max Health by <span class='tooltip-value'>#%</span>, Light of Sanctuary increases max Health by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
			rankInfo2: [30, 60, 90],
		},
		{
			index: 51,
			name: "Mercy",
			ranks: 2,
			desc: "While Sympathy is active, the range of Heal. Divine Light, and Light of Healing is increased by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [2, 4],
		},
		{
			index: 54,
			name: "Divine Favor",
			ranks: 1,
			desc: "Purifying Light's cooldown is reduced by 4 seconds and is immune to controlling effects while casting.",
			rankInfo: [],
			parent: 27,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Light Burn",
			ranks: 5,
			ranksnw: 2,
			desc: "Divine Strike inflicts an additional amount of bonus damage equal to <span class='tooltip-value'>#</span> plus <span class='tooltip-value'>#%</span> of your Light Mastery.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 80, 120, 160, 200],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Divine Strike inflicts an additional amount of bonus damage equal to <span class="tooltip-value">240</span> plus <span class="tooltip-value">60%</span> of your Light Mastery.</div>'],
		},
		{
			index: 3,
			name: "Vigorous Blessing",
			ranks: 5,
			ranksnw: 2,
			desc: "Increases the amount of Health restored by Blessings of Life by <span class='tooltip-value'>#%</span>, and the Accuracy of your Light skills by <span class='tooltip-value'>#</span>.",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 6,
			name: "Light of Fortune",
			ranks: 5,
			desc: "Blessings of Fortune increases the Crit Chance of your Light skills by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4, 5],
			rankInfo2: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Level: 6/5 (need rune)\n\n<br><br>Blessings of Fortune increases the Crit Chance of your Light skills by <span class="tooltip-value">6%</span>.</div>'],
		},
		{
			index: 8,
			name: "Divine Knowledge",
			ranks: 5,
			desc: "Increases your Light Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [10, 20, 30, 40, 50],
		},
		{
			index: 9,
			name: "Heavenly Penalty",
			ranks: 4,
			ranksnw: 2,
			desc: "Divine Strike gains a <span class='tooltip-value'>#%</span> chance to inflict the Light Punishment effect on the target, which reduces the target's Light Resistance by <span class='tooltip-value'>#</span> for 15 seconds. Stacks 5 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [40, 60, 80, 100],
			rankInfo2: [11, 14, 17, 20],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Divine Strike gains a <span class="tooltip-value">100%</span> chance to inflict the Light Punishment effect on the target, which reduces the target\'s Light Resistance by <span class="tooltip-value">23</span> for 15 seconds. Stacks 5 times.</div>'],
			parent: [0],
		},
		{
			index: 10,
			name: "Strike of Punishment",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Light damage</span><span class='right'>Cooldown: 5 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 18 meters</span>\n\nDeals 100% of your base Attack plus <span class='tooltip-value'>#</span> bonus damage. Inflicts the Light Punishment effect on the target, which reduces its Light Resistance by 8 for 15 seconds. Stacks 5 times.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [147, 210, 275, 339],
			rankInfo3: [794, 1326, 1849, 2363],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">405</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Light damage</span><span class="right">Cooldown: 5 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Deals 100% of your base Attack plus <span class="tooltip-value">2867</span> bonus damage. Inflicts the Light Punishment effect on the target, which reduces its Light Resistance by 8 for 15 seconds. Stacks 5 times.</div>'],
		},
		{
			index: 11,
			name: "Life Surge",
			ranks: 3,
			desc: "Increases the duration of Blessings of Life by <span class='tooltip-value'>#</span> minutes and reduces the Mana cost by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [15, 30, 45],
			parent: 1,
		},
		{
			index: 15,
			name: "Aurora Wind",
			ranks: 4,
			ranksnw: 2,
			desc: "Blessings of Gale increases the target's movement speed by an additional <span class='tooltip-value'>#%</span> and its cooldown is reduced by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [5, 10, 15, 20],
			rankInfo2: [2, 4, 6, 8],
		},
		{
			index: 16,
			name: "Divine Barrier",
			ranks: 3,
			desc: "Increases your Light Resistance by <span class='tooltip-value'>#</span> and your Defense by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
			rankInfo2: [10, 15, 20],
		},
		{
			index: 17,
			name: "Glory",
			ranks: 3,
			desc: "Increases the base damage of Divine Strike by <span class='tooltip-value'>#%</span>. Divine Strike gains a <span class='tooltip-value'>#%</span> chance to trigger the Glory effect, which causes the next Divine Strike to cost no Mana and have no cooldown. This effect lasts 15 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the base damage of Divine Strike by <span class="tooltip-value">20%</span>. Divine Strike gains a <span class="tooltip-value">20%</span> chance to trigger the Glory effect, which causes the next Divine Strike to cost no Mana and have no cooldown. This effect lasts 15 seconds.</div>'],
			parent: 4,
		},
		{	
			index: 18,
			name: "Penalty Mark",
			ranks: 2,
			desc: "Increases the base damage of Strike of Punishment by <span class='tooltip-value'>#%</span>. Has a <span class='tooltip-value'>#%</span> chance to inflict the Conviction Mark effect on the target, which reduces its max Mana by 5% every 4 seconds for 20 seconds.",
			rankInfo: [10, 20],
			rankInfo2: [25, 50],
			parent: 5,
		},
		{
			index: 19,
			name: "Warming Wind",
			ranks: 2,
			desc: "Blessings of Gale grants the Warming Wind effect to the target, which restores an amount of Health equal to <span class='tooltip-value'>#%</span> of the amount your Heal skill restores when the target is attacked.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [70, 120],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Blessings of Gale grants the Warming Wind effect to the target, which restores an amount of Health equal to <span class="tooltip-value">170%</span> of the amount your Heal skill restores when the target is attacked.</div>'],
			parent: 7,
		},
		{
			index: 22,
			name: "Magic Prism",
			ranks: 4,
			desc: "Offensive Light skills deal <span class='tooltip-value'>#</span> damage plus <span class='tooltip-value'>#%</span> of your Light Mastery as bonus damage to targets affected by Conviction Mark.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [100, 200, 300, 400],
			rankInfo2: [25, 50, 75, 100],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Offensive Light skills deal <span class="tooltip-value">500</span> damage plus <span class="tooltip-value">125%</span> of your Light Mastery as bonus damage to targets affected by Conviction Mark.</div>'],
		},
		{
			index: 23,
			name: "Wind of Blessings",
			ranks: 3,
			desc: "Light of Sanctuary triggers the Wind of Blessings effect, which increases the movement speed of party members by <span class='tooltip-value'>#%</span> and makes you immune to all direct damage for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [40, 50, 60],
			rankInfo2: [4, 6, 8],
		},
		{
			index: 26,
			name: "Godly Might",
			ranks: 3,
			desc: "Damnation reduces the target's Crit Chance by <span class='tooltip-value'>#%</span> and its Evasion by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 3, 4],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Damnation reduces the target\'s Crit Chance by <span class="tooltip-value">5%</span> and its Evasion by <span class="tooltip-value">40</span>.</div>'],
		},
		{
			index: 28,
			name: "Flash",
			ranks: 4,
			desc: "Increases your Evasion by <span class='tooltip-value'>#</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 29,
			name: "Sacred Energy",
			ranks: 3,
			desc: "Heal grants the Sacred Energy effect to the caster for 5 seconds. When the caster is attacked, Sacred Energy deals <span class='tooltip-value'>#</span> damage to the attacker and drains <span class='tooltip-value'>#%</span> of its max Mana.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [200, 400, 600],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Heal grants the Sacred Energy effect to the caster for 5 seconds. When the caster is attacked, Sacred Energy deals <span class="tooltip-value">800</span> damage to the attacker and drains <span class="tooltip-value">8%</span> of its max Mana.</div>'],
		},
		{
			index: 30,
			name: "Light Punishment",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 3 seconds</span>\n<span class='left'>Light damage</span><span class='right'>Cooldown: 15 seconds</span>\n<span class='left'>Single-target attack</span><span class='right'>Range: 18 meters</span>\n\nStrikes the target three times. Each attack deals 80% of your base Attack plus <span class='tooltip-value'>#</span> bonus damage. Each hit has a 5%/10%/15% chance to stun a target affected by Conviction Mark for 3 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [633, 789],
			rankInfo3: [1504, 2306],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">951</span> Mana</span><span class="right">Cast time: 3 seconds</span>\n<br><span class="left">Light damage</span><span class="right">Cooldown: 15 seconds</span>\n<br><span class="left">Single-target attack</span><span class="right">Range: 18 meters</span>\n\n<br><br>Strikes the target three times. Each attack deals 80% of your base Attack plus <span class="tooltip-value">3052</span> bonus damage. Each hit has a 5%/10%/15% chance to stun a target affected by Conviction Mark for 3 seconds.</div>'],
		},
		{
			index: 31,
			name: "Gale of Magic",
			ranks: 2,
			desc: "Increases the Mana cost of Blessings of Gale by <span class='tooltip-value'>#%</span>. It restores an amount of Mana equal to <span class='tooltip-value'>#%</span> of the skill’s cost to the target.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [50, 100],
			rankInfo2: [50, 70],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the Mana cost of Blessings of Gale by <span class="tooltip-value">150%</span>. It restores an amount of Mana equal to <span class="tooltip-value">90%</span> of the skill’s cost to the target.</div>'],
		},
		{
			index: 33,
			name: "Justice",
			ranks: 2,
			ranksnw: 1,
			desc: "Reduces the cooldown of Divine Judgment by <span class='tooltip-value'>#</span> seconds, and increases its base damage by <span class='tooltip-value'>#%</span> of your Light Mastery.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4],
			rankInfo2: [30, 60],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Divine Judgment by <span class="tooltip-value">6</span> seconds, and increases its base damage by <span class="tooltip-value">90%</span> of your Light Mastery.</div>'],
		},
		{
			index: 34,
			name: "Radiance",
			ranks: 3,
			ranksnw: 2,
			desc: "Increases the chance for each hit of Light Punishment to stun the target by <span class='tooltip-value'>#</span>.",
			rankInfo: ['1%-3%-5%', '2%-6%-10%', '3%-9%-15%'],
			parent: 17,
		},
		{
			index: 36,
			name: "Light Protection",
			ranks: 3,
			desc: "Increases the amount of Light damage you deal and the amount of Health restored by your healing skills by <span class='tooltip-value'>#</span> for each point of your Light Mastery.",
			rankInfo: [0.5, 1, 1.5],
		},
		{
			index: 38,
			name: "Avenging Light",
			ranks: 3,
			desc: "Reduces the cooldown of Light Punishment by <span class='tooltip-value'>#</span> seconds, the chance of being interrupted while casting it by <span class='tooltip-value'>#%</span> and its Mana cost by <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4, 6],
			rankInfo2: [20, 40, 60],
			rankInfo3: [10, 20, 30],
			parent: 20,
		},
		{
			index: 39,
			name: "Light Fusion",
			ranks: 2,
			desc: "Using Light attacks reduces the Mana cost of the next Light attacks by <span class='tooltip-value'>#%</span> for 10 seconds. The effect stacks 5 times.",
			rankInfo: [2, 4],
		},
		{
			index: 41,
			name: "Verdict",
			ranks: 2,
			desc: "Increases the bonus damage of Divine Judgment by <span class='tooltip-value'>#%</span>. Inflicts the Conviction Mark effect and reduces the effectiveness of healing skills cast on the target by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 15],
			rankInfo2: [10, 15],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Increases the bonus damage of Divine Judgment by <span class="tooltip-value">20%</span>. Inflicts the Conviction Mark effect and reduces the effectiveness of healing skills cast on the target by <span class="tooltip-value">20%</span>.</div>'],
			parent: 19,
		},
		{
			index: 42,
			name: "Abandonment",
			ranks: 2,
			desc: "Reduces the cooldown of Strike of Punishment by <span class='tooltip-value'>#</span> second(s). Grants Strike of Punishment and Light Punishment a <span class='tooltip-value'>#%</span> chance to dispel healing effects on the target. The target cannot be healed for 3 seconds.",
			rankInfo: [1, 2],
			rankInfo2: [10, 20],
		},
		{
			index: 46,
			name: "Punishing Removal",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>913 Mana</span><span class='right'>Cast time: 3 seconds</span>\n<span class='left'>Light</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>Multi-target curse</span><span class='right'>Range: 18 meters</span>\n\nDispels the Attack buffs of up to 20 enemies within a 10 meter radius.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Majesty",
			ranks: 4,
			desc: "Punishing Removal reduces target's Crit Chance by <span class='tooltip-value'>#%</span> for 15 seconds.",
			rankInfo: [2, 4, 6, 8],
			parent: 26,
		},
		{
			index: 49,
			name: "Deep Hypnosis",
			ranks: 2,
			desc: "Holy Prayer - Trance stuns targets for <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 3],
		},
		{
			index: 51,
			name: "Plague",
			ranks: 3,
			desc: "Increases Wither's duration by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [3, 6, 9],
		},
		{
			index: 54,
			name: "Punishing Evil",
			ranks: 1,
			desc: "Reduces Punishing Removal's casting time by 50%, reduces target's Light Resistance by 150 and Evasion by 100 for 15 seconds.",
			rankInfo: [],
			parent: 26,
		},
	],
		// three
	[
		{
			index: 2,
			name: "Freezing Light",
			ranks: 5,
			desc: "Divine Strike deals an amount of damage to slowed targets equal to <span class='tooltip-value'>#%</span> of Divine Strike's bonus damage. Grants Divine Strike a <span class='tooltip-value'>#%</span> chance to ensnare a slowed target for 2 seconds.",
			rankInfo: [5, 10, 15, 20, 25],
			rankInfo2: [5, 10, 15, 20, 25],
		},
		{
			index: 4,
			name: "Heart of Frost",
			ranks: 5,
			desc: "Increases the Accuracy of your Water skills by <span class='tooltip-value'>#</span> and their Crit Chance by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30, 40, 50],
			rankInfo2: [1, 1, 2, 2, 3],
		},
		{
			index: 5,
			name: "Icy Core",
			ranks: 3,
			ranksnw: 2,
			desc: "Frost Concentration reduces the target's movement speed by an additional <span class='tooltip-value'>#%</span>. Increases the bonus damage of Frost Concentration by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Frost Concentration reduces the target\'s movement speed by an additional <span class="tooltip-value">20%</span>. Increases the bonus damage of Frost Concentration by <span class="tooltip-value">20%</span>.</div>'],
		},
		{
			index: 6,
			name: "Aqua Bestowal",
			ranks: 2,
			desc: "Blessings of Fortune increases the target's Resistances by <span class='tooltip-value'>#</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Blessings of Fortune increases the target\'s Resistances by <span class="tooltip-value">15</span>.</div>'],
		},
		{
			index: 7,
			name: "Light of Salvation",
			ranks: 3,
			desc: "Grants Light of Sanctuary a <span class='tooltip-value'>#%</span> chance to dispel all controlling effects from targets and grant them immunity to controlling effects for 5 seconds.",
			rankInfo: [40, 70, 100],
		},
		{
			index: 10,
			name: "Prayer of Frost",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Attack</span><span class='right'>Cooldown: 60 seconds</span>\n<span class='left'>Self blessing</span><span class='right'>Range: None</span>\n\nIncreases the base damage of your Water skills by 50% and reduces their cooldowns by 75% for <span class='tooltip-value'>#</span> seconds. While Prayer of Frost is active, you cannot be interrupted while casting Water skills.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv30</span>\n\n', '<span class="req">Requires character to be Lv45</span>\n\n', '<span class="req">Requires character to be Lv60</span>\n\n', '<span class="req">Requires character to be Lv75</span>\n\n'],
			rankInfo2: [276, 394, 513, 634],
			rankInfo3: [12, 15, 18, 21],
			rankInfo4: ['', '', '', '<div class="runelvl">\n<br>Level: 5/4 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">755</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Attack</span><span class="right">Cooldown: 60 seconds</span>\n<br><span class="left">Self blessing</span><span class="right">Range: None</span>\n\n<br><br>Increases the base damage of your Water skills by 50% and reduces their cooldowns by 75% for <span class="tooltip-value">24</span> seconds. While Prayer of Frost is active, you cannot be interrupted while casting Water skills.</div>'],
		},
		{
			index: 11,
			name: "Winds of Salvation",
			ranks: 3,
			desc: "Increases the duration of Blessings of Gale by <span class='tooltip-value'>#</span> seconds and grants it a <span class='tooltip-value'>#%</span> chance to dispel slow effects placed on the target.",
			rankInfo: [2, 4, 6],
			rankInfo2: [40, 70, 100],
		},
		{
			index: 12,
			name: "Frost Mastery",
			ranks: 4,
			desc: "Increases your Water Mastery by <span class='tooltip-value'>#</span>.",
			rankInfo: [12, 24, 36, 48],
		},
		{
			index: 13,
			name: "Flash Freeze",
			ranks: 3,
			ranksnw: 2,
			desc: "Reduces the cooldown of Frost Concentration by <span class='tooltip-value'>#</span> second(s). Reduces the cooldown of Frost Concentration by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Reduces the cooldown of Frost Concentration by <span class="tooltip-value">4</span> second(s). Reduces the cooldown of Frost Concentration by <span class="tooltip-value">20</span> second(s).</div>'],
			parent: 2,
		},
		{
			index: 15,
			name: "Arcane Coldness",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the base damage of Holy Prayer - Enigma by <span class='tooltip-value'>#%</span>, Mana absorption rate is increased by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the base damage of Holy Prayer - Enigma by <span class="tooltip-value">40%</span>, Mana absorption rate is increased by <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 16,
			name: "Frost Barrier",
			ranks: 3,
			desc: "Increases your Water Resistance by <span class='tooltip-value'>#</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 17,
			name: "Biting Cold",
			ranks: 4,
			desc: "Frost Concentration reduces the target's Water Resistance by <span class='tooltip-value'>#</span> and its Crit Dodge by <span class='tooltip-value'>#%</span> for 15 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 25, 35, 45],
			rankInfo2: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Level: 5/4 (need rune)\n\n<br><br>Frost Concentration reduces the target\'s Water Resistance by <span class="tooltip-value">55</span> and its Crit Dodge by <span class="tooltip-value">2.5%</span> for 15 seconds.</div>'],
			parent: 8,
		},
		{
			index: 18,
			name: "Clarity of Ice",
			ranks: 4,
			desc: "Prayer of Frost increases the range of your Water skills by <span class='tooltip-value'>#</span> meter(s) and their Crit Chance by <span class='tooltip-value'>#%</span>. Prayer of Frost gains a <span class='tooltip-value'>#%</span> chance to reset the cooldowns of other Water skills.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: [25, 50, 75, 100],
			parent: 5,
		},
		{
			index: 22,
			name: "Realm of Ice",
			ranks: 3,
			desc: "Grants your offensive Water skills a <span class='tooltip-value'>#%</span> chance to ensnare slowed targets for 3 seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Grants your offensive Water skills a <span class="tooltip-value">60%</span> chance to ensnare slowed targets for 3 seconds.</div>'],
		},
		{
			index: 23,
			name: "Siphon",
			ranks: 3,
			desc: "Increases the amount of Mana absorbed by Holy Prayer - Enigma by <span class='tooltip-value'>#%</span>. It reduces the target's max Health by double the Mana absorbed for <span class='tooltip-value'>#</span> seconds.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75],
			rankInfo2: [20, 25, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the amount of Mana absorbed by Holy Prayer - Enigma by <span class="tooltip-value">100%</span>. It reduces the target\'s max Health by double the Mana absorbed for <span class="tooltip-value">35</span> seconds.</div>'],
			parent: 9,
		},
		{
			index: 25,
			name: "Frozen Blade",
			ranks: 3,
			ranksnw: 1,
			desc: "Increases the bonus damage of Ice Blade Strike by <span class='tooltip-value'>#%</span> and reduces the cooldown by <span class='tooltip-value'>#</span> second(s).\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 2, 3],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Level: 4/3 (need rune)\n\n<br><br>Increases the bonus damage of Ice Blade Strike by <span class="tooltip-value">20%</span> and reduces the cooldown by <span class="tooltip-value">4</span> second(s).</div>'],
		},
		{
			index: 26,
			name: "Northern Air",
			ranks: 3,
			desc: "Increases the chance for Ice Blade Strike to inflict a slow effect by <span class='tooltip-value'>#%</span>. Increases its range by <span class='tooltip-value'>#</span> meter(s).",
			rankInfo: [25, 50, 75],
			rankInfo2: [1, 2, 3],
			parent: 15
		},
		{
			index: 27,
			name: "Aqua Blessings",
			ranks: 2,
			desc: "Blessings of Tenacity grants the target the Water God's Blessing effect, which reduces incoming Water damage by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Blessings of Tenacity grants the target the Water God\'s Blessing effect, which reduces incoming Water damage by <span class="tooltip-value">9%</span>.</div>'],
		},
		{
			index: 30,
			name: "Icebound Confession",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> Mana</span><span class='right'>Cast time: 1 seconds</span>\n<span class='left'>Water</span><span class='right'>Cooldown: 45 seconds</span>\n<span class='left'>Single-target curse</span><span class='right'>Range: 18 meters</span>\n\nFor 10 seconds, every hit the target takes will interrupt its casting and ensnare it for <span class='tooltip-value'>#</span> second(s). This effect ends after the target is struck 6 times. If the target is not hit during the duration of the effect, it will be frozen for 5 seconds when the effect ends.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Requires character to be Lv55</span>\n\n', '<span class="req">Requires character to be Lv70</span>\n\n'],
			rankInfo2: [409, 502],
			rankInfo3: [1, 2],
			rankInfo4: ['', '<div class="runelvl">\n<br>Level: 3/2 (need rune)\n\n<br><br><span class="left"><span class="tooltip-value">599</span> Mana</span><span class="right">Cast time: 1 seconds</span>\n<br><span class="left">Water</span><span class="right">Cooldown: 45 seconds</span>\n<br><span class="left">Single-target curse</span><span class="right">Range: 18 meters</span>\n\n<br><br>For 10 seconds, every hit the target takes will interrupt its casting and ensnare it for <span class="tooltip-value">3</span> second(s). This effect ends after the target is struck 6 times. If the target is not hit during the duration of the effect, it will be frozen for 5 seconds when the effect ends.</div>'],
		},
		{
			index: 31,
			name: "Rippling Water",
			ranks: 3,
			desc: "Increases the amount of Water damage you deal and the amount of Health restored by your healing skills by <span class='tooltip-value'>#</span> for each point of your Water Mastery.",
			rankInfo: [0.5, 1, 1.5],
		},
		{
			index: 32,
			name: "Angelic Barrier",
			ranks: 3,
			desc: "Increases the Defense bonus granted by Soul Barrier by <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 33,
			name: "Severe Punishment",
			ranks: 3,
			desc: "Increases the amount of Mana the target of Divine Judgment loses by <span class='tooltip-value'>#</span>. Deals damage equal to <span class='tooltip-value'>#%</span> of the amount of Mana lost to slowed targets.",
			rankInfo: [200, 400, 600],
			rankInfo2: [30, 40, 50],
		},
		{
			index: 34,
			name: "Cold Heart",
			ranks: 3,
			desc: "Increases the duration of Icebound Confession by <span class='tooltip-value'>#</span> seconds and reduces its cooldown by <span class='tooltip-value'>#</span> seconds.",
			rankInfo: [2, 4, 6],
			rankInfo2: [5, 10, 15],
			parent: 18,
		},
		{
			index: 38,
			name: "Rapid Response",
			ranks: 2,
			desc: "Reduces the cooldown of Sympathy by <span class='tooltip-value'>#</span> seconds and its Mana cost by <span class='tooltip-value'>#%</span>.\n\n<b>You can increase the level of talent using runes.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: [20, 40],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Level: 3/2 (need rune)\n\n<br><br>Reduces the cooldown of Sympathy by <span class="tooltip-value">9</span> seconds and its Mana cost by <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 39,
			name: "Crystal Calmness",
			ranks: 3,
			desc: "Increases the duration of slow effects caused by your skills by <span class='tooltip-value'>#</span> second(s). They reduce the target's movements speed by an additional <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [5, 10, 15],
		},
		{
			index: 41,
			name: "Angelic Asylum",
			ranks: 2,
			desc: "Reduces the Mana cost of Angelic Harmony by <span class='tooltip-value'>#%</span>. Each healing effect has a <span class='tooltip-value'>#%</span> chance to dispel the last bleed or burn effect placed on the target. This chance doubles for targets within 8 meters of you.",
			rankInfo: [15, 30],
			rankInfo2: [10, 20],
		},
		{
			index: 42,
			name: "Embrace of Aurora",
			ranks: 2,
			desc: "Increases the base damage of your offensive Water skills by <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20],
		},
		{
			index: 46,
			name: "Stilled World",
			ranks: 1,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>845 Mana</span><span class='right'>Cast time: 2 seconds</span>\n<span class='left'>Water damage</span><span class='right'>Cooldown: 15 seconds</span>\n<span class='left'>Multi-target attack</span><span class='right'>Range: 18 meters</span>\n\nStrikes all enemies within 8 meters of the target. Deals 100% of your base Attack plus 3328 bonus damage. Reduces the effectiveness of healing skills cast on the target by 20% and its Water Resistance by 60 for 10 seconds.",
			rankInfo: ['<span class="req">Requires character to be Lv75</span>\n\n'],
		},
		{
			index: 47,
			name: "Stretched Freeze",
			ranks: 4,
			desc: "Increases Stilled World's range by <span class='tooltip-value'>#</span> meters.",
			rankInfo: [0.5, 1, 1.5, 2],
			parent: 27,
		},
		{
			index: 49,
			name: "Tremble",
			ranks: 3,
			desc: "Increases Icebound Confession's Ensnare effect duration by <span class='tooltip-value'>#</span> seconds, and reduces target's casting speed by <span class='tooltip-value'>#%</span>.",
			rankInfo: [0.5, 1, 1.5],
			rankInfo2: [10, 20, 30],
		},
		{
			index: 51,
			name: "Freezing Cold",
			ranks: 2,
			desc: "Water skill Crit Strikes reduce target's basic Defense by <span class='tooltip-value'>#%</span>. The Freezing Cold effect will be removed when the target is hit 3 times. Lasts 15 seconds.",
			rankInfo: [15, 30],
		},
		{
			index: 54,
			name: "Austerity",
			ranks: 1,
			desc: "Stilled World's casting time reduced by 50%, Base Attack bonus is increased by 25%, and it is immune to controlling effects while casting.",
			rankInfo: [],
			parent: 27,
		},
	]
];