var data = [
	// one
	[
		{
			index: 1,
			name: "Разрушение",
			ranks: 5,
			desc: "При применении навыка «Яростный удар» с вероятностью 50% защита цели снизится на <span class='tooltip-value'>#</span>. В состоянии боеготовности вероятность увеличивается на 20%. Суммируется 3 раза, длительность 20 сек. На пятом уровне таланта каждое очко боеготовности дополнительно ослабляет защиту цели 1%.",
			rankInfo: [5, 10, 15, 20, 25],
		},
		{
			index: 3,
			name: "Безумная битва",
			ranks: 5,
			desc: "Боеготовность дополнительно увеличивает защиту на <span class='tooltip-value'>#%</span> + <span class='tooltip-value'>#</span> ед.",
			rankInfo: [0.9, 1.8, 2.7, 3.6, 4.5],
			rankInfo2: [9, 18, 27, 36, 45],
		},
		{
			index: 5,
			name: "Гнев молний",
			ranks: 3,
			desc: "Дополнительный урон от первой и второй молнии увеличивается на <span class='tooltip-value'>#%</span> и <span class='tooltip-value'>#%</span> соответсвенно.",
			rankInfo: [2, 4, 6],
			rankInfo2: [4, 8, 12],
		},
		{
			index: 7,
			name: "Искусная боевая песня",
			ranks: 5,
			ranksnw: 2,
			desc: "Боевая песня дополнительно повышает собственную защиту на <span class='tooltip-value'>#</span> ед., уклонение на <span class='tooltip-value'>#</span> ед. Увеличивает базовую защиту на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [1, 2, 3, 4, 5],
			rankInfo3: [0.5, 1, 1.5, 2, 2.5],
			rankInfo4: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Боевая песня дополнительно повышает собственную защиту на <span class="tooltip-value">18</span> ед., уклонение на <span class="tooltip-value">6</span> ед. Увеличивает базовую защиту на <span class="tooltip-value">3%</span>.</div>'],
		},
		{
			index: 8,
			name: "Презрение",
			ranks: 3,
			desc: "Увеличение  <span class='tooltip-value'>#%</span> навыков добавляет ненависти при атаке.",
			rankInfo: [50, 100, 150],
		},
		{
			index: 9,
			name: "Ужасающий рев",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Физ.</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – нет</span>\n\nСнижает меткость врагов на <span class='tooltip-value'>#</span> ед. и силу атаки на <span class='tooltip-value'>#</span> ед. в радиусе 10 м., при этом повышая их злобу; продолжительность; 10 сек. Может развеять вражескую скрытность, а также наносит <span class='tooltip-value'>#%</span> урона от базовой атаки. В течение 5 секунд после использования навыка «Ужасающий рев», навыки «Танец хаоса» и «Громовое крыло» могут быть использованы без перезарядки, однако они значительно повысят злобу монстров. Однако при этом бонус к атаке уменьшается на 50% и становятся невозможными эффекты паралича, разоружения и прерывания заклинания.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [104, 148, 193, 239],
			rankInfo3: [20, 30, 40, 50],
			rankInfo4: [20, 40, 60, 80],
			rankInfo5: [20, 30, 40, 50],
			rankInfo6: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">286</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Физ.</span><span class="right">Время перезарядки: 20 сек.</span>\n<br><span class="left">Массовое проклятие</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Снижает меткость врагов на <span class="tooltip-value">60</span> ед. и силу атаки на <span class="tooltip-value">100</span> ед. в радиусе 10 м., при этом повышая их злобу; продолжительность; 10 сек. Может развеять вражескую скрытность, а также наносит <span class="tooltip-value">60%</span> урона от базовой атаки. В течение 5 секунд после использования навыка «Ужасающий рев», навыки «Танец хаоса» и «Громовое крыло» могут быть использованы без перезарядки, однако они значительно повысят злобу монстров. Однако при этом бонус к атаке уменьшается на 50% и становятся невозможными эффекты паралича, разоружения и прерывания заклинания.</div>'],
		},
		{
			index: 10,
			name: "Знание Бога войны",
			ranks: 4,
			desc: "Сокращение времени перезарядки «Благословения Бога войны» на <span class='tooltip-value'>#</span> сек. если количество ОЗ менее 50%, происходит увеличение дополнительно защиты на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [10, 20, 30, 40],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Сокращение времени перезарядки «Благословения Бога войны» на <span class="tooltip-value">75</span> сек. если количество ОЗ менее 50%, происходит увеличение дополнительно защиты на <span class="tooltip-value">50%</span>.</div>'],
		},
		{
			index: 12,
			name: "Могучий удар",
			ranks: 4,
			desc: "Увеличивает максимум ОЗ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
		},
		{
			index: 13,
			name: "Ужас",
			ranks: 3,
			desc: "Увеличение времени действия «Ужасающего рева» на <span class='tooltip-value'>#</span> сек. <span class='tooltip-value'>#%</span> шанс прервать чтение заклинания врагу.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			parent: 5,
		},
		{
			index: 14,
			name: "Демон ветра",
			ranks: 5,
			ranksnw: 3,
			desc: "Навык «Смертельный удар» увеличивает силу атаки на <span class='tooltip-value'>#%</span>, дополнительно ослабляет сопротивление цели Воздуху на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [3, 6, 9, 12, 15],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 16,
			name: "Противостояние ветру",
			ranks: 3,
			desc: "Усиление сопротивления Воздуху на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Усиление сопротивления Воздуху на <span class="tooltip-value">60</span> ед.</div>'],
		},
		{
			index: 18,
			name: "Насмешка над демонами",
			ranks: 4,
			desc: "Навык «Смертельный удар» с вероятностью <span class='tooltip-value'>#%</span> накладывает на цель эффект «Насмешка» на 2 сек., увеличивает расстояние атаки на <span class='tooltip-value'>#</span> м. В состоянии Боеготовности с вероятностью <span class='tooltip-value'>#%</span> снимает с цели одно состояние, увеличивающее защиту или прочие параметры. Если «Боеготовность» не действует, вероятность уменьшается вдвое.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [1, 2, 3, 4],
			rankInfo3: [20, 40, 60, 80],
			rankInfo4: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Навык «Смертельный удар» с вероятностью <span class="tooltip-value">100%</span> накладывает на цель эффект «Насмешка» на 2 сек., увеличивает расстояние атаки на <span class="tooltip-value">5</span> м. В состоянии Боеготовности с вероятностью <span class="tooltip-value">100%</span> снимает с цели одно состояние, увеличивающее защиту или прочие параметры. Если «Боеготовность» не действует, вероятность уменьшается вдвое.</div>'],
			parent: 9,
		},
		{
			index: 20,
			name: "Усиление защиты",
			ranks: 3,
			desc: "Увеличение физ. сопротивление на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 21,
			name: "Искусство выживания",
			ranks: 3,
			desc: "Расход ОМ для «Боевой песни», »Боеготовности», «Устрашающего рева» и »Запугивающего рева» снижается на <span class='tooltip-value'>#%</span>. Увеличивает продолжительность эффекта «Бога войны» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: [2, 4, 6],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Расход ОМ для «Боевой песни», »Боеготовности», «Устрашающего рева» и »Запугивающего рева» снижается на <span class="tooltip-value">60%</span>. Увеличивает продолжительность эффекта «Бога войны» на <span class="tooltip-value">8</span> сек.</div>'],
		},
		{
			index: 23,
			name: "Мастер сражения",
			ranks: 2,
			desc: "Боеготовность дополнительно снижает урон от всех стихий на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Боеготовность дополнительно снижает урон от всех стихий на <span class="tooltip-value">9%</span>.</div>'],
			parent: 3,
		},
		{
			index: 25,
			name: "Источник силы",
			ranks: 3,
			ranksnw: 2,
			desc: "Сила дракона увеличивает время действия на <span class='tooltip-value'>#</span> мин.",
			rankInfo: [10, 20, 30],
		},
		{
			index: 26,
			name: "Искусство наступления",
			ranks: 2,
			desc: "Уменьшение минимального расстояния при наступлении в режиме боеготовности на <span class='tooltip-value'>#%</span> увеличение ненависти к монстрам.",
			rankInfo: [50, 100],
		},
		{
			index: 27,
			name: "Начало битвы",
			ranks: 2,
			desc: "Уменьшение ослабления в режиме боеготовности силы атаки воина на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 29,
			name: "Кровь дракона",
			ranks: 2,
			desc: "Сила дракона дополнительно повышает базовое количество ОЗ цели на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [3, 6],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Сила дракона дополнительно повышает базовое количество ОЗ цели на <span class="tooltip-value">9%</span>.</div>'],
			parent: 15,
		},
		{
			index: 30,
			name: "Страж жизни",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Защита</span><span class='right'>Время перезарядки: 180 сек.</span>\n<span class='left'>Массовое благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nУвеличивает максимум ОЗ союзников в радиусе 16 м. на <span class='tooltip-value'>#%</span> и восстанавливает соответсвующее количество ОЗ. Собственный максимум ОЗ увеличивается на 5% на <span class='tooltip-value'>#</span> сек. На запуск этого навыка не действуют эффекты контроля.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [223, 277],
			rankInfo3: [15, 16],
			rankInfo4: [25, 30],
			rankInfo5: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">335</span> ОМ</span><span class="right">Чтение: 3 сек.</span>\n<br><span class="left">Защита</span><span class="right">Время перезарядки: 180 сек.</span>\n<br><span class="left">Массовое благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Увеличивает максимум ОЗ союзников в радиусе 16 м. на <span class="tooltip-value">17%</span> и восстанавливает соответсвующее количество ОЗ. Собственный максимум ОЗ увеличивается на 5% на <span class="tooltip-value">35</span> сек. На запуск этого навыка не действуют эффекты контроля.</div>'],
		},
		{
			index: 31,
			name: "Прорыв защиты",
			ranks: 2,
			desc: "Оглушенное состояние при ударе грома понижает шанс уклониться от крит. удара на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Оглушенное состояние при ударе грома понижает шанс уклониться от крит. удара на <span class="tooltip-value">3%</span>.</div>'],
		},
		{
			index: 35,
			name: "Желание крови",
			ranks: 2,
			desc: "Снижение количества теряемого собственных ОЗ на <span class='tooltip-value'>#%</span>. Снижение расходования ОЗ на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [25, 50],
			rankInfo2: [25, 50],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Снижение количества теряемого собственных ОЗ на <span class="tooltip-value">75%</span>. Снижение расходования ОЗ на <span class="tooltip-value">75%</span>.</div>'],
		},
		{
			index: 36,
			name: "Защита в бою",
			ranks: 3,
			desc: "Защита усиливается на <span class='tooltip-value'>#%</span> + <span class='tooltip-value'>#</span> ед.",
			rankInfo: [1, 2, 3],
			rankInfo2: [15, 25, 40],
		},
		{
			index: 38,
			name: "Надежда",
			ranks: 3,
			ranksnw: 1,
			desc: "Cокращение времени перезарядки «Стража жизни» на <span class='tooltip-value'>#</span> сек. С каждой атакой во время пения «Стража жизни» можно восстановить <span class='tooltip-value'>#%</span> максимального количества ОЗ.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40, 60],
			rankInfo2: [2, 5, 8],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Cокращение времени перезарядки «Стража жизни» на <span class="tooltip-value">80</span> сек. С каждой атакой во время пения «Стража жизни» можно восстановить <span class="tooltip-value">11%</span> максимального количества ОЗ.</div>'],
			parent: 19,
		},
		{
			index: 39,
			name: "Угасание битвы",
			ranks: 2,
			desc: "«Громовое крыло» с вероятностью 75% уменьшает силу атаки цели на <span class='tooltip-value'>#%</span>, длительность – 15 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>«Громовое крыло» с вероятностью 75% уменьшает силу атаки цели на <span class="tooltip-value">30%</span>, длительность – 15 сек.</div>'],
		},
		{
			index: 42,
			name: "Концентрация",
			ranks: 2,
			desc: "В состоянии «Страж жизни» увеличивается эффективность применяемого к персонажу исцеления на <span class='tooltip-value'>#%</span>, и применение персонажем навыков не может быть прервано.",
			rankInfo: [20, 40],
			parent: 23,
		},
		{
			index: 43,
			name: "Гром и молния",
			ranks: 3,
			ranksnw: 1,
			desc: "Увеличивает базовый урон навыков «Мгновенный удар», «Удар грома», «Гнев Бога грома» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 47,
			name: "Гнев Бога грома",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>301 ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Урон от Воздуха</span><span class='right'>Время перезарядки: 6 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nНаносит 100% базового урона и дополнительно 2193 ед. урона. Требует нахождение в состоянии «Боеготовность». Уменьшает показатели мастерства цели на 300 ед. на две ее следующие атаки. Вызывает большое количество угрозы.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			parent: 26,
		},
		{
			index: 48,
			name: "Взрыв гнева",
			ranks: 4,
			desc: "Увеличивает количество очков ненависти, получаемых в результате применения навыка «Гнев Бога грома», на <span class='tooltip-value'>#%</span>; повышает эффективность уменьшения мастерства цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [20, 40, 60, 80],
			rankInfo2: [10, 20, 30, 40],
			parent: 27,
		},
		{
			index: 50,
			name: "Правила выживания",
			ranks: 2,
			desc: "Воин находится в состоянии боеготовности; при получении урона восстанавливает ОЗ в количестве <span class='tooltip-value'>#%</span> от полученного урона. Эффект срабатывает не чаще 1 раз а в 3 секунды.",
			rankInfo: [2, 4],
		},
		{
			index: 52,
			name: "Воля воина",
			ranks: 3,
			desc: "«Танец хаоса» создает немного больше очков ненависти; в состоянии боеготовности повышает PVE-стойкость на 33 ед.",
			rankInfo: [33, 66, 99],
		},
		{
			index: 55,
			name: "Наказание богов",
			ranks: 1,
			desc: "«Гнев Бога грома» повышает PVE-стойкосгь персонажа на 50 ед., длится 10 сек., эффект суммируется до 8 раз.",
			rankInfo: [],
			parent: 27,
		},
	],
		// two
	[
		{
			index: 1,
			name: "Бешеная атака",
			ranks: 5,
			ranksnw: 3,
			desc: "Повышение силы атаки при использовании «Яростного удара» на <span class='tooltip-value'>#%</span> дополнительно увеличение фиксированной силы атаки, равной <span class='tooltip-value'>#%</span> собственного физического мастерства.",
			rankInfo: [2, 4, 6, 8, 10],
			rankInfo2: [10, 20, 30, 40, 50],
		},
		{
			index: 2,
			name: "Рывок",
			ranks: 2,
			desc: "Уменьшение минимальной дистанции наступления на <span class='tooltip-value'>#</span> м.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшение минимальной дистанции наступления на <span class="tooltip-value">3</span> м.</div>'],
		},
		{
			index: 3,
			name: "Тайна наступления",
			ranks: 3,
			desc: "Сокращение времени перезарядки навыка «Наступление» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращение времени перезарядки навыка «Наступление» на <span class="tooltip-value">4</span> сек.</div>'],
		},
		{
			index: 5,
			name: "Секущий удар",
			ranks: 3,
			desc: "Повышение шанса крит. удара при использовании «Яростного удара» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Повышение шанса крит. удара при использовании «Яростного удара» на <span class="tooltip-value">8%</span>.</div>'],
			parent: [0],
		},
		{
			index: 6,
			name: "Песня ветра",
			ranks: 4,
			desc: "Боевая песня дополнительно повышает мастерство Воздуха и физ. мастерство на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 7,
			name: "Болото молний",
			ranks: 3,
			desc: "Повышение вероятности замедления со вторым ударом молнии на <span class='tooltip-value'>#%</span>.",
			rankInfo: [15, 30, 45],
		},
		{
			index: 9,
			name: "Шквал ударов",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Физ. урон</span><span class='right'>Время перезарядки: 5 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nДважды атакует врага. Каждый удар наносит цели 90% базового урона + <span class='tooltip-value'>#</span> ед. дополнительного урона. С вероятностью 25% наносит цели <span class='tooltip-value'>#</span> урона в секунду в течение 10 сек. Кровожадность увеличивает эффект кровоточения у цели на 15%.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [105, 162, 221, 281],
			rankInfo3: [446, 876, 1299, 1715],
			rankInfo4: [50, 100, 150, 200],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">343</span> ОМ</span><span class="right">Чтение: 2 сек.</span>\n<br><span class="left">Физ. урон</span><span class="right">Время перезарядки: 5 сек.</span>\n<br><span class="left">Атака единичной цели</span><span class="right">Расстояние атаки – ближняя</span>\n\n<br><br>Дважды атакует врага. Каждый удар наносит цели 90% базового урона + <span class="tooltip-value">2123</span> ед. дополнительного урона. С вероятностью 25% наносит цели <span class="tooltip-value">250</span> урона в секунду в течение 10 сек. Кровожадность увеличивает эффект кровоточения у цели на 15%.</div>'],
		},
		{
			index: 10,
			name: "Расцвет жизни",
			ranks: 5,
			desc: "Кровожадность увеличивает максимум ОЗ на <span class='tooltip-value'>#%</span> и <span class='tooltip-value'>#</span> очков.",
			rankInfo: [0.9, 1.8, 2.7, 3.6, 4.5],
			rankInfo2: [150, 300, 450, 600, 750],
		},
		{
			index: 12,
			name: "Уравновешенность",
			ranks: 3,
			desc: "Снижает вероятность прерывания всех навыков на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30, 45],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Снижает вероятность прерывания всех навыков на <span class="tooltip-value">60%</span>.</div>'],
		},
		{
			index: 13,
			name: "Резак",
			ranks: 3,
			ranksnw: 2,
			desc: "«Шквал ударов» увеличивает урон на <span class='tooltip-value'>#%</span> от максимума ОЗ.",
			rankInfo: [1, 1.5, 2],
			parent: 6,
		},
		{
			index: 14,
			name: "Кровожадный Бог войны",
			ranks: 3,
			desc: "Увеличение времени действия навыка «Бог войны» на <span class='tooltip-value'>#%</span>. Увеличение урона от крит. удара в состоянии «Бог войны» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличение времени действия навыка «Бог войны» на <span class="tooltip-value">40%</span>. Увеличение урона от крит. удара в состоянии «Бог войны» на <span class="tooltip-value">40%</span>.</div>'],
		},
		{
			index: 15,
			name: "Кровавая резня",
			ranks: 3,
			ranksnw: 2,
			desc: "Увеличение доп. атаки «Кровавый удар» на <span class='tooltip-value'>#%</span>. Увеличение макс. собственного количества ОЗ на <span class='tooltip-value'>#%</span> количества поглощаемого здоровья.",
			rankInfo: [5, 10, 15],
			rankInfo2: [1, 1.5, 2],
		},
		{
			index: 18,
			name: "Ускорение",
			ranks: 3,
			desc: "Сокращение времени перезарядки в «Стремительном рывке» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращение времени перезарядки в «Стремительном рывке» на <span class="tooltip-value">40</span> сек.</div>'],
		},
		{
			index: 19,
			name: "Горячая кровь",
			ranks: 3,
			desc: "Сокращение времени перезарядки навыка «Кровавый удар» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращение времени перезарядки навыка «Кровавый удар» на <span class="tooltip-value">8</span> сек.</div>'],
			parent: 11,
		},
		{
			index: 20,
			name: "Владение клинком",
			ranks: 4,
			desc: "Повышение собственного физического мастерства на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 21,
			name: "Кровавое сияние",
			ranks: 3,
			desc: "Сокращение времени перезарядки «Сияния крови» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 1.5, 2],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращение времени перезарядки «Сияния крови» на <span class="tooltip-value">2.5</span> сек.</div>'],
			parent: 9,
		},
		{
			index: 22,
			name: "Кипение крови",
			ranks: 2,
			desc: "Кровожадность увеличивает эффект от получаемого лечения на <span class='tooltip-value'>#%</span>.",
			rankInfo: [9, 18],
		},
		{
			index: 25,
			name: "Разгром оружия",
			ranks: 2,
			desc: "Увеличивает вероятность разоружения вторым этапом атаки «Громового удара» на <span class='tooltip-value'>#%</span>. Каждый этап атаки «Танца хаоса» с вероятностью <span class='tooltip-value'>#%</span> разоружает цель на 3 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [20, 40],
			rankInfo2: [10, 20],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Увеличивает вероятность разоружения вторым этапом атаки «Громового удара» на <span class="tooltip-value">30%</span>. Каждый этап атаки «Танца хаоса» с вероятностью <span class="tooltip-value">30%</span> разоружает цель на 3 сек.</div>'],
		},
		{
			index: 26,
			name: "Доблесть",
			ranks: 4,
			desc: "Базовый урон от навыков «Кровавый удар» и «Шквал ударов» увеличивается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15, 20],
		},
		{
			index: 29,
			name: "Пробуждение гнева",
			ranks: 2,
			desc: "Уменьшение ослабления в режиме кровожадности защиты на <span class='tooltip-value'>#%</span>.",
			rankInfo: [50, 100],
		},
		{
			index: 30,
			name: "Жажда крови",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 120 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nРасходует 5% от макс. количества собственного здоровья., в след. 18 сек. приобретается иммунитет к потере здоровья. С каждой атакой цель теряет 1% от максимального количества собственного здоровья, а также повышает шанс крит. удара на <span class='tooltip-value'>#%</span>. Шанс крит. удара повышается на 15 сек., максимум 8 этапов.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [189, 236],
			rankInfo3: [1, 1.5],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">285</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 125 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Расходует 5% от макс. количества собственного здоровья., в след. 18 сек. приобретается иммунитет к потере здоровья. С каждой атакой цель теряет 1% от максимального количества собственного здоровья, а также повышает шанс крит. удара на <span class="tooltip-value">2%</span>. Шанс крит. удара повышается на 15 сек., максимум 8 этапов.</div>'],
		},
		{
			index: 31,
			name: "Безумный кровосос",
			ranks: 2,
			desc: "Сокращение времени перезарядки удара навыка «Кровавый удар» на <span class='tooltip-value'>#%</span>, увеличение количества ОЗ на <span class='tooltip-value'>#%</span>.",
			rankInfo: [30, 60],
			rankInfo2: [100, 200],
			parent: 20,
		},
		{
			index: 33,
			name: "Свет безмолвия",
			ranks: 2,
			desc: "Если второй этап атаки навыков «Мгновенный удар» и «Шквал ударов» наносит критический урон, цель находится в состоянии молчания <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 2],
		},
		{
			index: 35,
			name: "Кровавое соглашение",
			ranks: 3,
			ranksnw: 2,
			desc: "Уменьшает время восстановления навыка «Кровопролития» на <span class='tooltip-value'>#</span> сек., и увеличивает его время действия на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [5, 10, 15],
			rankInfo2: [2, 4, 6],
		},
		{
			index: 38,
			name: "Последние капли крови",
			ranks: 2,
			desc: "Увеличение времени действия «Жажды крови» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [3, 6],
			parent: 20,
		},
		{
			index: 39,
			name: "Кровавый танец",
			ranks: 3,
			desc: "Увеличение урона от основной атаки «Яростного удара» в состоянии «Кровотечения» на <span class='tooltip-value'>#%</span>, <span class='tooltip-value'>#%</span> вероятности заморозки цели на 2 сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20, 30],
			rankInfo2: [20, 40, 60],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличение урона от основной атаки «Яростного удара» в состоянии «Кровотечения» на <span class="tooltip-value">40%</span>, <span class="tooltip-value">80%</span> вероятности заморозки цели на 2 сек.</div>'],
			parent: 23,
		},
		{
			index: 42,
			name: "Лезвие меча",
			ranks: 3,
			desc: "Увеличивает критический урон навыков «Яростный удар», «Смертельный удар», «Кровавый удар» и «Жертвоприношение» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 43,
			name: "Извлечение души",
			ranks: 2,
			desc: "«Поглощение душ» увеличивает время действия на <span class='tooltip-value'>#</span> сек. Каждая полученная атака с вероятностью <span class='tooltip-value'>#%</span> сбрасывает время перезарядки навыка «Наступление». Атака, усиленная эффектом «Поглощение душ», повышается на <span class='tooltip-value'>#%</span>.",
			rankInfo: [2, 4],
			rankInfo2: [12, 24],
			rankInfo3: [0.5, 1],
		},
		{
			index: 46,
			name: "Жертвоприношение",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>231 ОМ</span><span class='right'>Чтение: 2 сек.</span>\n<span class='left'>Физ. урон</span><span class='right'>Время перезарядки: 15 сек.</span>\n<span class='left'>Атака единичной цели</span><span class='right'>Расстояние атаки – ближняя</span>\n\nДвойная атака. Каждый удар наносит 90% базового урона и дополнительно 1159 ед. урона. Требует нахождение персонажа в режиме кровожадности. Жертвует 10% максимума ОЗ и добавляет это количество к урону.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Тяжелая рана",
			ranks: 4,
			desc: "С вероятностью <span class='tooltip-value'>#%</span> совершающий жертвоприношение выз ывает у цели кровотечение и з амедление. В течение 4 сек. цель теряет <span class='tooltip-value'>#</span> ОЗ в секунду и замедляется на <span class='tooltip-value'>#%</span>.",
			rankInfo: [25, 50, 75, 100],
			rankInfo2: [200, 300, 400, 500],
			rankInfo3: [10, 20, 30, 40],
			parent: 28,
		},
		{
			index: 49,
			name: "Мастерство танца хаоса",
			ranks: 3,
			desc: "Увеличивает бонус к базовому урону «Танца хаоса» на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10, 15],
		},
		{
			index: 51,
			name: "Грозный зов войны",
			ranks: 2,
			desc: "Увеличивает время действия эффекта «Зова войны» на <span class='tooltip-value'>#</span> сек. / повышает эффективно сть исцеления выбранной цели на <span class='tooltip-value'>#%</span>.",
			rankInfo: [300, 600],
			rankInfo2: [3, 6],
		},
		{
			index: 54,
			name: "Воля смертоносности",
			ranks: 1,
			desc: "Жертвоприношение дополнительно повышает меткость на 80 ед.",
			rankInfo: [],
			parent: 28,
		},
	],
		// three
	[
		{
			index: 1,
			name: "Буря",
			ranks: 5,
			desc: "Неистовство дополнительно увеличивает силу атаки на <span class='tooltip-value'>#%</span> + <span class='tooltip-value'>#</span> ед.",
			rankInfo: [0.9, 1.8, 2.7, 3.6, 4.5],
			rankInfo2: [30, 60, 90, 120, 150],
		},
		{
			index: 2,
			name: "Молния-убийца",
			ranks: 5,
			ranksnw: 3,
			desc: "Если в течение 10 сек. после использования навыка «Мгновенный удар» убить цель с разницей уровней не более 10, то сила атаки увеличится на <span class='tooltip-value'>#</span> на 30 сек. Суммируется до 5 раз, каждый раз сила атаки дополнительно увеличивается на 1%.",
			rankInfo: [20, 35, 50, 65, 80],
		},
		{
			index: 5,
			name: "Остаток сил",
			ranks: 5,
			desc: "Увеличивеет вероятность получить эффект «Отголоски атаки» на <span class='tooltip-value'>#%</span>. Эффект увеличивает меткость на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [6, 12, 18, 24, 30],
			rankInfo2: [10, 20, 30, 40, 50],
			rankInfo3: ['', '', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 6/5 (требуется руна)\n\n<br><br>Увеличивеет вероятность получить эффект «Отголоски атаки» на <span class="tooltip-value">36%</span>. Эффект увеличивает меткость на <span class="tooltip-value">60</span> ед.</div>'],
		},
		{
			index: 6,
			name: "Тайна молнии",
			ranks: 3,
			desc: "Сокращение времени перезарядки после «Мгновенного удара» на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Сокращение времени перезарядки после «Мгновенного удара» на <span class="tooltip-value">4</span> сек.</div>'],
			parent: 1,
		},
		{
			index: 7,
			name: "Дикая песнь",
			ranks: 3,
			ranksnw: 3,
			desc: "Увеличение времени действия боевой песни на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [300, 600, 900],
		},
		{
			index: 9,
			name: "Безумие Бога войны",
			ranks: 3,
			desc: "Под воздействием эффекта «Бог Войны», атаки персонажа усиливают атаку на <span class='tooltip-value'>#%</span> на 10 сек. Эффект суммируется до 5 раз.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Под воздействием эффекта «Бог Войны», атаки персонажа усиливают атаку на <span class="tooltip-value">8%</span> на 10 сек. Эффект суммируется до 5 раз.</div>'],
		},
		{
			index: 10,
			name: "Устрашающий рык",
			ranks: 4,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Физ.</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Массовое проклятие</span><span class='right'>Расстояние атаки – нет</span>\n\nУменьшает уклонение врага в радиусе 10 м. на <span class='tooltip-value'>#</span> ед., защиту на <span class='tooltip-value'>#</span> ед. и скорость передвижения на 25%. Время действия 10 сек., может рассеять вражескую скрытность.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 30</span>\n\n', '<span class="req">Требуемый уровень персонажа: 45</span>\n\n', '<span class="req">Требуемый уровень персонажа: 60</span>\n\n', '<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
			rankInfo2: [87, 123, 161, 199],
			rankInfo3: [20, 30, 40, 50],
			rankInfo4: [20, 40, 60, 80],
			rankInfo5: ['', '', '', '<div class="runelvl">\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">239</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Физ.</span><span class="right">Время перезарядки: 20 сек.</span>\n<br><span class="left">Массовое проклятие</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Уменьшает уклонение врага в радиусе 10 м. на <span class="tooltip-value">55</span> ед., защиту на <span class="tooltip-value">125</span> ед. и скорость передвижения на 25%. Время действия 10 сек., может рассеять вражескую скрытность.</div>'],
		},
		{
			index: 11,
			name: "Боевая песня эльфов",
			ranks: 3,
			desc: "Боевая песня дополнительно увеличивает атаку на <span class='tooltip-value'>#</span> ед., меткость на <span class='tooltip-value'>#</span> ед. Увеличивает базовую атаку на <span class='tooltip-value'>#%</span>.",
			rankInfo: [10, 20, 30],
			rankInfo2: [2, 4, 6],
			rankInfo3: [0.5, 1, 1.5],
			parent: 4,
		},
		{
			index: 14,
			name: "Рев",
			ranks: 3,
			desc: "Увеличение времени действия «Рева небес» на <span class='tooltip-value'>#</span> сек. Дополнительно снижение физического сопротивления врагов на <span class='tooltip-value'>#</span> ед.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [2, 4, 6],
			rankInfo2: [10, 20, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличение времени действия «Рева небес» на <span class="tooltip-value">8</span> сек. Дополнительно снижение физического сопротивления врагов на <span class="tooltip-value">40</span> ед.</div>'],
			parent: 6,
		},
		{
			index: 15,
			name: "Разгром демонов",
			ranks: 4,
			desc: "Навык «Смертельный удар» дополнительно ослабляет физическое сопротивление цели на <span class='tooltip-value'>#</span> ед. Восстанавливает цели <span class='tooltip-value'>#%</span> от максимума ОМ на время действия эффекта «Сокрушение демона».",
			rankInfo: [15, 30, 45, 60],
			rankInfo2: [5, 10, 15, 20],
		},
		{
			index: 16,
			name: "Управление ветром",
			ranks: 4,
			desc: "Мастерство Воздуха повышается на <span class='tooltip-value'>#</span> ед.",
			rankInfo: [10, 20, 30, 40],
		},
		{
			index: 17,
			name: "Тайна стремительности",
			ranks: 3,
			desc: "Увеличение времени действия «Стремительного рывка» на <span class='tooltip-value'>#</span> сек., эффект ускорения на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3],
			rankInfo2: [2.5, 5, 7.5],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>Увеличение времени действия «Стремительного рывка» на <span class="tooltip-value">4</span> сек., эффект ускорения на <span class="tooltip-value">10%</span>.</div>'],
		},
		{
			index: 18,
			name: "Кровавое прикосновение",
			ranks: 3,
			desc: "Навык «Кровавый удар» снижает эффект исцеления цели на <span class='tooltip-value'>#%</span>, время действия <span class='tooltip-value'>#</span> сек.",
			rankInfo: [25, 35, 45],
			rankInfo2: [6, 8, 10],
		},
		{
			index: 19,
			name: "Танец ветра",
			ranks: 4,
			desc: "Неистовство увеличивает крит. шанс «Мгновенного удара» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1.5, 3, 4.5, 6],
			rankInfo2: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Неистовство увеличивает крит. шанс «Мгновенного удара» на <span class="tooltip-value">7.5%</span>.</div>'],
		},
		{
			index: 21,
			name: "Слабое место",
			ranks: 2,
			ranksnw: 2,
			desc: "Снижает шанс уклониться от крит. удара на <span class='tooltip-value'>#%</span> при наступлении, время действия 10 сек., окончание до начала третьей атаки.",
			rankInfo: [2, 4],
		},
		{
			index: 22,
			name: "Гроза",
			ranks: 4,
			ranksnw: 3,
			desc: "Повышение шанса крит. удара с каждым «Ударом грома» на <span class='tooltip-value'>#%</span>. Время перезарядки сокращается на <span class='tooltip-value'>#</span> сек.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [0.5, 1, 1.5, 2],
			rankInfo3: ['', '', '', '<div class="runelvl">\n\n\n<br>Уровень: 5/4 (требуется руна)\n\n<br><br>Повышение шанса крит. удара с каждым «Ударом грома» на <span class="tooltip-value">5%</span>. Время перезарядки сокращается на <span class="tooltip-value">2,5</span> сек.</div>'],
		},
		{
			index: 25,
			name: "Гнев Бога войны",
			ranks: 1,
			desc: "Если в режиме «Бог войны» не восстанавливаться после наступления, время головокружения от наступления сокращается до 1 сек.",
			rankInfo: [],
			parent: 14,
		},
		{
			index: 26,
			name: "Оглушающий гром",
			ranks: 2,
			desc: "Если со вторым ударом грома наносится крит. удар, цель находится в состоянии головокружения от <span class='tooltip-value'>#</span> до <span class='tooltip-value'>#</span> сек.",
			rankInfo: [1, 3],
			rankInfo2: [2, 4],
			parent: 15,
		},
		{
			index: 28,
			name: "Стремительное безумие",
			ranks: 2,
			desc: "Неистовство воина уменьшает время перезарядки навыков «Бог войны», «Рывок», «Сила дракона» и «Клинок ответного удара» на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [10, 20],
			rankInfo2: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Неистовство воина уменьшает время перезарядки навыков «Бог войны», «Рывок», «Сила дракона» и «Клинок ответного удара» на <span class="tooltip-value">30%</span>.</div>'],
		},
		{
			index: 29,
			name: "Тайна сердца дракона",
			ranks: 2,
			desc: "Сила дракона дополнительно увеличивает силу базовой атаки на <span class='tooltip-value'>#%</span>.",
			rankInfo: [3, 6],
		},
		{
			index: 30,
			name: "Клинок ответного удара",
			ranks: 2,
			ranksnw: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'><span class='tooltip-value'>#</span> ОМ</span><span class='right'>Чтение: 1 сек.</span>\n<span class='left'>Атака</span><span class='right'>Время перезарядки: 90 сек.</span>\n<span class='left'>Личное благословение</span><span class='right'>Расстояние атаки – нет</span>\n\nПрименив, можно дать отпор любой прямой атаке, равный 100% урона от собственной атаки. На этот урон не действует защита и сопротивление, время действия <span class='tooltip-value'>#</span> сек. Применение данного навыка не контролируется.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 55</span>\n\n', '<span class="req">Требуемый уровень персонажа: 70</span>\n\n'],
			rankInfo2: [213, 265],
			rankInfo3: [12, 15],
			rankInfo4: ['', '<div class="runelvl">\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br><span class="left"><span class="tooltip-value">321</span> ОМ</span><span class="right">Чтение: 1 сек.</span>\n<br><span class="left">Атака</span><span class="right">Время перезарядки: 90 сек.</span>\n<br><span class="left">Личное благословение</span><span class="right">Расстояние атаки – нет</span>\n\n<br><br>Применив, можно дать отпор любой прямой атаке, равный 100% урона от собственной атаки. На этот урон не действует защита и сопротивление, время действия <span class="tooltip-value">18</span> сек. Применение данного навыка не контролируется.</div>'],
		},
		{
			index: 31,
			name: "Пробуждение безумия",
			ranks: 2,
			desc: "Уменьшение ослабления уклонения и защиты на <span class='tooltip-value'>#%</span> в режиме неистовства.",
			rankInfo: [25, 50],
		},
		{
			index: 33,
			name: "Контроль кровотечения",
			ranks: 2,
			ranksnw: 1,
			desc: "Увеличение времени действия «Кровотечения» на <span class='tooltip-value'>#</span> сек., повышение вероятности выхода из состояния наездника на <span class='tooltip-value'>#%</span>.",
			rankInfo: [5, 10],
			rankInfo2: [5, 10],
		},
		{
			index: 35,
			name: "Сила безумия",
			ranks: 2,
			desc: "В состоянии «Неистовства» увеличивает силу атаки навыков «Яростный удар», «Мгновенный удар» и «Громовой удар» на <span class='tooltip-value'>#%</span>. Урон, нанесенный «Яростным ударом», становится уроном Воздуха.",
			rankInfo: [8, 16],
		},
		{
			index: 38,
			name: "Мастер ответного удара",
			ranks: 3,
			desc: "Увеличение времени действия «Клинка ответного удара» на <span class='tooltip-value'>#</span> сек., повышение урона от ответного удара на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3],
			rankInfo2: [20, 40, 60],
			parent: 20,
		},
		{
			index: 39,
			name: "Шторм",
			ranks: 3,
			desc: "«Громовое крыло» сокращает время перезарядки на <span class='tooltip-value'>#</span> сек., уменьшает время чтения заклинаний на <span class='tooltip-value'>#%</span>.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [5, 10, 15],
			rankInfo2: [20, 25, 30],
			rankInfo3: ['', '', '<div class="runelvl">\n\n\n<br>Уровень: 4/3 (требуется руна)\n\n<br><br>«Громовое крыло» сокращает время перезарядки на <span class="tooltip-value">20</span> сек., уменьшает время чтения заклинаний на <span class="tooltip-value">80%</span>.</div>'],
		},
		{
			index: 41,
			name: "Кровавый дождь",
			ranks: 3,
			desc: "«Кровопролитие» уменьшает базовую защиту цели на <span class='tooltip-value'>#%</span>, а уклонение - на <span class='tooltip-value'>#</span> ед. Радиус действия эффекта: <span class='tooltip-value'>#</span> м.",
			rankInfo: [5, 10, 15],
			rankInfo2: [15, 30, 45],
			rankInfo3: [2, 4, 6],
			parent: 22,
		},
		{
			index: 43,
			name: "Удар пожирателя",
			ranks: 2,
			desc: "Уменьшает время восстановления способности «Поглощение душ» на <span class='tooltip-value'>#</span> сек. В состоянии «Поглощение душ» персонаж с вероятностью <span class='tooltip-value'>#%</span> получает иммунитет к головокружению и сну. Следующая атака прекращает действие эффекта «Поглощение душ» и действие этих иммунитетов прекращается.\n\n<b>Возможно увеличение уровня таланта с помощью рун.</b><span class='tooltip-value'>#</span>",
			rankInfo: [15, 30],
			rankInfo2: [30, 60],
			rankInfo3: ['', '<div class="runelvl">\n\n\n<br>Уровень: 3/2 (требуется руна)\n\n<br><br>Уменьшает время восстановления способности «Поглощение душ» на <span class="tooltip-value">45</span> сек. В состоянии «Поглощение душ» персонаж с вероятностью <span class="tooltip-value">100%</span> получает иммунитет к головокружению и сну. Следующая атака прекращает действие эффекта «Поглощение душ» и действие этих иммунитетов прекращается.</div>'],
		},
		{
			index: 46,
			name: "Ураган мечей",
			ranks: 1,
			desc: "<span class='tooltip-value'>#</span><span class='left'>396 ОМ</span><span class='right'>Чтение: 3 сек.</span>\n<span class='left'>Урон от Воздуха</span><span class='right'>Время перезарядки: 20 сек.</span>\n<span class='left'>Массовая атака</span><span class='right'>Расстояние атаки – ближняя</span>\n\nТребуется состояние «Неистовства». Атакует до 10 целей в секторе 120º перед персонажем на удалении до 7 м. Если показатель мастерства Воздуха выше, чем у цели, она получает дополнительный урон в зависимости от разницы. Атака состоит из трех этапов. Каждый этап наносит 100% базового урона + 1067 ед. Если во время первого этапа атаки действует эффект «Раскат грома», то скорость цели на 5 сек. уменьшается на 50%.",
			rankInfo: ['<span class="req">Требуемый уровень персонажа: 75</span>\n\n'],
		},
		{
			index: 47,
			name: "Ураганное ускорение",
			ranks: 4,
			desc: "Снижает время восстановления навыка «Ураган мечей» на <span class='tooltip-value'>#</span> сек., увеличивает бонус к баз овому урону на <span class='tooltip-value'>#%</span>.",
			rankInfo: [1, 2, 3, 4],
			rankInfo2: [5, 10, 15, 20],
			parent: 28,
		},
		{
			index: 49,
			name: "Ревущий гром",
			ranks: 2,
			desc: "Уменьшает время восстановления навыка «Палач грома» на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [3, 6],
		},
		{
			index: 51,
			name: "Кровь бога войны",
			ranks: 3,
			desc: "Увеличение времени действия Кровотечения на <span class='tooltip-value'>#</span> сек.",
			rankInfo: [2, 4, 6],
		},
		{
			index: 54,
			name: "Истребление",
			ranks: 1,
			desc: "Снижает время восстановления навыка «Ураган мечей» на 10 сек., увеличивает бонус к базовой атаке на 50%.",
			rankInfo: [],
			parent: 28,
		},
	]
];